### ISSUE TITLE
Abort/exit after unsuccessful operation

### ISSUE THREAD

**Issue by bennyber01** [igraph/igraph#1000]
Hello,
I want to raise two issues.
I think that I should mention that I compile this lib with vs compiler in windows environment.

1. I tested it with VERY LARGE graphs. In some cases this lib calls
abort method instead of return with an appropriate error.
In my case this happened when I used push_back method on a vector.
When it was impossible to allocate more space it called abort().
This makes this lib very hard to use in applications because I don't want
the application to suddenly close.

2. Some methods use assert method to check the validity of the parameters. I think that it will be better to check the parameters and if something is wrong with them just return with an appropriate error.

Thank you,
    Benny.

**Comment by ntamas** [comment]
Did you replace the default error handler (which indeed aborts when it runs into an issue) with [`igraph_error_handler_ignore`](http://igraph.org/c/doc/igraph-Error.html#igraph_error_handler_ignore) before calling any other functions from the library? Doing so would ensure that the app is not aborted - you just get an error code in the return value and it is then your responsibility to check it and act accordingly.

**Comment by bennyber01** [comment]
Thank you for fast reply.
I'll fix my code according to you suggestion.
Just to clarify, I need to write an empty method and pass it to the method you told me about, right?

**Comment by szhorvat** [comment]
I believe normally you would put an

    IGRAPH_FINALLY_FREE();

in there to free up any memory allocated by the function.

**Comment by ntamas** [comment]
@bennyber01 nope, you'll need to call `igraph_set_error_handler()` with `igraph_error_handler_ignore` as its argument - no need to write your own function. Please read the [chapter about error handling](http://igraph.org/c/doc/igraph-Error.html#igraph_set_error_handler) in the manual. Also, there is no need to call `IGRAPH_FINALLY_FREE` explicitly because `igraph_error_handler_ignore` does it for you already.
