### ISSUE TITLE
Macro collision/redefinition

### ISSUE THREAD

**Issue by bennyber01** [igraph/igraph#1001]
Hello,
There are some macros in the lib (like STR in igraph_strvector.h file) which names are very popular.
It makes it a bit difficult to use this lib in other projects without unwanted macro redefinition. I think that it will be best to add some prefix to macros which will make them unique. like STR -> IGRAPH_STR.
Thank you,
    Benny.

**Comment by iosonofabio** [comment]
This is fair but `VECTOR` is used pretty much everywhere, and changing it into `IGRAPH_VECTOR` will significantly reduce readibility.

Also, we use `TYPE` and `FUNCTION` in our type definitions, with the same problem. I think `TYPE` basically just adds `_t`, so having `IGRAPH_TYPE(igraph_mytype)` instead of just `igraph_mytype_t` seems grotesque...

Any opinions around the table?

**Comment by ntamas** [comment]
We can protect the problematic declarations with another macro like this:

```
#define IGRAPH_STR yadda yadda

#ifndef IGRAPH_PLEASE_DONT_MESS_UP_THE_GLOBAL_NAMESPACE
#define STR IGRAPH_STR
#endif
```

so if it causes problems for someone, there is always an escape hatch:

```
#define IGRAPH_PLEASE_DONT_MESS_UP_THE_GLOBAL_NAMESPACE
#include <igraph/igraph.h>
```

**Comment by iosonofabio** [comment]
so evil!

I'd be in favour, any other opinions?

**Comment by szhorvat** [comment]
> This is fair but `VECTOR` is used pretty much everywhere, and changing it into `IGRAPH_VECTOR` will significantly reduce readibility.

I agree.

Also, personally, I already find it a burden to keep typing `VECTOR` everywhere. It's one of the things that contributes to igraph feeling cumbersome to work with. If it were renamed to `IGRAPH_VECTOR`, that would kill auto-completion in my IDE (now I can type `VE` then use auto-complete, but if everything starts with `IGRAPH_`, then I'd have to type `IGRAPH_VE`, which is much worse). I am strongly against renaming `VECTOR`.

As for `STR`, that one is not used nearly as frequently as `VECTOR`, so the burden is smaller. The question of whether consistency with `VECTOR` is important remains.

**Comment by szhorvat** [comment]
The macro `STR()` is now deprecated and will be removed in a future version, most likely in 1.0.
