### ISSUE TITLE
igraph fails to read some GraphML files

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1004]
igraph fails to read GraphML files written by Mathematica.  While the way Mathematica writes data into GraphML is pretty bad, I fail to see why these files are invalid.  Other programs like Gephi and yEd are able to read these files.

Is this a problem in igraph, or are these files really corrupted?

Here is an example file:

```
<?xml version='1.0' encoding='UTF-8'?>
<graphml>
 <key id='nodeKey1'
     for='node'
     attr.name='VertexCoordinates'
     attr.type='String' />
 <key id='edgeKey1'
     for='edge'
     attr.name='EdgeWeight'
     attr.type='String' />
 <graph id='Graph1'
     edgedefault='undirected'>
  <node id='1'>
   <data key='nodeKey1'>List[1.`, 0.`]</data>
  </node>
  <node id='2'>
   <data key='nodeKey1'>List[-1.`, 0.`]</data>
  </node>
  <edge id='e1'
      source='1'
      target='2'>
   <data key='edgeKey1'>1.23`</data>
  </edge>
 </graph>
</graphml>
```

It is simplest to try importing in R using `read_graph`.

**Comment by ntamas** [comment]
There are at least two reasons why the file above is not valid GraphML:

* First, it fails to declare that XML tags without a namespace in the file belong to the GraphML namespace. This should be fixed by adding `xmlns="http://graphml.graphdrawing.org/xmlns"` into the root tag as an attribute. By failing to do so, the external tool creating the GraphML file does not declare that, e.g., a plain `<graphml>` tag should be interpreted in the context of the GraphML specification.

* Second, `String` is not a valid vertex attribute type according to the [GraphML XSD schema](http://graphml.graphdrawing.org/xmlns/1.1/graphml.xsd) - the valid values are `boolean`, `int`, `long`, `float`, `double` and `string`.

While in theory we could add arbitrary hacks and workarounds for the quirks of third-party tools that create GraphML-like files, the policy has been so far to refrain from such hacks unless it is absolutely necessary.

**Comment by szhorvat** [comment]
Thanks for the clarifications.

Regardless of true compliance, it would be useful to at least remove the requirement for the `xmlns` attribute, especially considering that it does not communicate any practically relevant information, and that there are several tools that do not include it.

The case-sensitivity thing is probably not worth bothering with.

I tried a few tools out of curiosity, to see how they read and write GraphML:

 yEd, Gephi and Cytoscape all read these "broken" files without problems.

igraph and networkx don't.

Cytoscape also does not include the `xmlns` attribute when writing files, thus igraph cannot read its output.

----

As for my practical problem, I will just implement a compliant exporter for Mathematica (and report the problem to Wolfram, but I don't expect much...). I need to write GraphML files that people can read today, not only after a next igraph release comes out.

**Comment by ntamas** [comment]
If we want to fix this on the igraph side, we could add an extra argument to `igraph_read_graph_graphml()` that tells igraph to be "lenient" with the namespace issues outlined above and simply assume that the root namespace is the GraphML namespace if it is not provided in any `xmlns` attribute.

**Comment by ntamas** [comment]
Okay, I am willing to consider the following option: when the GraphML reader detects that the input file has not specified any namespaces (as it is the case in your example), it will simply assume that all tags belong to the GraphML namespace and tries to parse things as such. However, if there is at least one explicitly defined namespace in the input file, it will assume that whoever produced the file understood what XML namespaces are, and therefore the absence of a GraphML namespace means that the input is not valid GraphML. Would that work for your?

**Comment by szhorvat** [comment]
Yes, that would work.

However, the point of my last comment was that personally I no longer need this. I opened the issue because I could not read Mathematica-exported GraphML with e.g. R/igraph.  Mathematica's exporter turned out to be so bad that I just re-implemented it from scratch. (I could not easily interface with igraph's GraphML write because of the need to handle attributes, so it was easier to re-implement it.)

As far as I'm concerned, this is low-priority, and effort is better spent on other issues first.

**Comment by ntamas** [comment]
> As far as I'm concerned, this is low-priority, and effort is better spent on other issues first.
I've got this in my pipeline for quite a while now so I just wanted to get it out.

**Comment by szhorvat** [comment]
It's still a useful fix, as there are other software that do not include the namespace. Above I mention Cytoscape. I remember I found several when I originally opened the issue, but I do not remember which.
