### ISSUE TITLE
Does make_line_graph keep the order of edges

### ISSUE THREAD

**Issue by huanfachen** [igraph/igraph#1006]
When using make_line_graph to generate a line graph _gLine_ of the original graph _g_, labels of vertices in _gLine_ are numbers from 1, meaning that the labels of edges in _g_ are not used. Can users assume that the order of vertices in _gLine_ is consistent with order of edges in _g_? Can users safely run the following code to set the vertex value:

```
require(igraph)
require(dplyr)
# df is an example of graph
df <- data.frame(from = c(1,2,3,2), to = c(2,3,4,4), weight = c(1,2,3,4), edgeName = paste0("E", 1:4), stringsAsFactors = F)
g <- graph.data.frame(df, directed = F) %>% set.edge.attribute("label", value = df$edgeName)
gLine <- make_line_graph(g) %>% set.vertex.attribute(gLine, "name", value = g$edgeName)
```

If this is not safe, is there any way to reserve the labels of edges in the original graph? Thanks!

**Comment by ntamas** [comment]
*Right now* the order of vertices in *gLine* is consistent with the order of edges in *g*, although the documentation does not say that explicitly and *in theory*, there is no guarantee that this will always hold in the future. However, I see no reason why we should ever change this, and anyways, I have told this to people so many times now that I think it is safe to say that it won't change in the foreseeable future - or if it does, it will be considered a breaking change that would necessitate proper documentation and whatnot in the changelog. So, if it ever changes in the future, users will probably be given a warning well ahead in the documentation before we follow through with the changes, or we will provide a backwards-compatible option to keep the ordering.
