### ISSUE TITLE
Inconsistent and ambiguous treatment of edge weight argument in clustering functions

### ISSUE THREAD

**Issue by edmundh** [igraph/igraph#1007]
cluster_edge_betweenness - uses NULL to omit edge weights
cluster_fast_greedy - uses NULL to omit edge weights (though it is not clear on this point?)
cluster_label_prop - uses NA, but in the ‘usage’ states NULL
cluster_leading_eigen - uses NA, but in the ‘usage’ states NULL
cluster_louvain - uses NA, but in the ‘usage’ states NULL
cluster_optimal - uses NA, but in the ‘usage’ states NULL
cluster_walktrap - does not provide any guidance, I assumed NULL was used
cluster_spinglass - uses NA, but usage states NULL

I am still quite new to R so perhaps the ‘usage’ is meant to be read differently, but I thought it meant NULL could be used as a meaningful input

Also note that using NULL where it should be NA still returns a result - giving the impression that it has worked as intended when it has not

Please could this be fixed so there is a uniform and clear approach in the next update to igraph, as it is very confusing at present

Perhaps the solution is to simply create one new ‘master’ function, call it ‘community_detection’ or something, and have a numbered list of input arguments 1-8  for these 8 methods, then you could have a single input NA or NULL for the weight argument. Having just one function would be very convenient, and I do not think the algorithms are so complex that they need to be in separate functions.

(to be clear, all the networks I am analysing are weighted and undirected, but I want to see what the effect is of both taking edge weights into account, and ignoring them, as these have different biological interpretations)

**Comment by edmundh** [comment]
(to be clear, all the networks I am analysing are weighted and undirected, but I want to see what the effect is of both taking edge weights into account, and ignoring them, as these have different biological interpretations)

**Comment by edmundh** [comment]
Can I also point out the modularity function is also extremely confusing, it does not appear to use edge weights by default but these have to be specified explicitly for them to be taken into account

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#198
