### ISSUE TITLE
GraphML truncating numbers

### ISSUE THREAD

**Issue by mfortini** [igraph/igraph#1008]
I exported in python-igraph (igraph 0.7.1 running inside Python 2.7.13) a graph to GraphML and one side effect is that all numbers are exported as floating point in scientific notation.
This wouldn't be an issue if for "large" numbers (around 1M) it didn't output less decimals than needed to go down to unity, so when I read back the graph, numbers are rounded to the closest 10s or 100s.

* Create a new graph
* Assign edges an attribute with value > 1M with non-zero digits
* Write GraphML
* Read back GraphML

Expected:
Read back the same graph

Real result:
The attributes are rounded to nearest 10s

**Comment by ntamas** [comment]
That's a tricky one; it's probably a platform-specific issue. I have tested it on a Mac with igraph 0.7.1 and it worked even for numbers with 24 digits or so. This part is handled by a specialized function called [`igraph_real_fprintf_precise`](https://github.com/igraph/igraph/blob/master/src/types.c#L113) in `src/types.c` and its very purpose is to ensure that numbers are printed in the most precise manner possible.

The function relies on the presence of the `DBL_DIG` macro that tells the number of significant digits in a double-precision floating-point number. In theory, it could be the case that this macro is not present on your platform, although I would find that quite surprising. Either way, we would need to know the platform (OS) you are working with so we can investigate further.

**Comment by mfortini** [comment]
Thank you for your answer.
I'm on Linux 4.11, Debian testing, libc6 2.24-10.
Here's a sample test session:
`$ igraph
No configuration file, using defaults
/usr/lib/python2.7/dist-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
igraph 0.7.1 running inside Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: g=Graph()
In [2]: g.add_vertices([0,1])
In [3]: g.add_edge(0,1,weight=1234567891234)
In [4]: g.write_graphml('graph.graphml')
In [5]: g1=read('graph.graphml')
In [6]: g1.es[0]
Out[6]: igraph.Edge(<igraph.Graph object at 0x7f759b78f908>, 0, {'weight': 1234570000000.0})
`
I attach the resulting graphml file

[graph.zip](https://github.com/igraph/igraph/files/1040745/graph.zip)

**Comment by ntamas** [comment]
How did you compile and install `python-igraph`? Did you simply run `pip install python-igraph` from the command line?

**Comment by mfortini** [comment]
Yes, I used pip

**Comment by ntamas** [comment]
Thanks for the info. I will try to install Debian testing in a VM and check what's going on during the compilation.

**Comment by ntamas** [comment]
Aah, got it. It turns out that the GraphML writer was patched _after_ the release of 0.7.1 so the official release does not use `igraph_real_printf_precise` yet. So, basically, this will be fixed whenever @gaborcsardi decides to release a new version of the C core of igraph.

Alternatively, you can check out the master revision of the C core of igraph from https://github.com/igraph/igraph, compile and install it on your own (it should only be a matter of `./configure && make && make install`), then check out the master revision of the Python interface from https://github.com/igraph/python-igraph and run `python setup.py install` on it. If you have `pkg-config` installed on your machine, it should be able to find the C core of igraph on its own and then link to it dynamically.
