### ISSUE TITLE
R session Aborted when computing betweenness

### ISSUE THREAD

**Issue by mpoirel** [igraph/igraph#1009]
I attached a network for which I cannot compute the betweenness as it aborts the R session. I can't see what's wrong with it, do you?

I use R studio, R version 3.3.2 and igraph 1.0.1.

When I use the NetSwan::swan_combinatory function, which relies on and recomputes betweenness, I get the same result: R session aborted.

Thanks for your help,

[Network_pbl_betweenness.zip](https://github.com/igraph/igraph/files/1041854/Network_pbl_betweenness.zip)

**Comment by mpoirel** [comment]
I extracted a small part of the network which cause the disruption

[NetworkSmall_pbl_betweenness.zip](https://github.com/igraph/igraph/files/1041899/NetworkSmall_pbl_betweenness.zip)

**Comment by ntamas** [comment]
Also happens in the Python interface, and it is caused by the weight of the last edge (`1e-23`). Unweighted betweenness centrality works correctly for the graph; also, even the weighted centrality works correctly if the weight of the last edge is replaced with something larger (e.g., `1e-5`).

**Comment by szhorvat** [comment]
Reproduced with the Mathematica interface (based on a recent dev version).

**Comment by ntamas** [comment]
#591 seems related. In one of the comments for #591, @gaborcsardi says:

> The problem is that you have edge weights that are smaller than the machine precision, and that leads to some numerical instability and violates the assumptions the igraph code has about the shortest paths. If you remove edges with weight less than 1e-10, then it works fine, but I guess this is not an option for you.
> 
> igraph should not crash, of course, but I am not sure what we can do to actually calculate the betweenness for these weights, probably nothing.

He is probably correct about the numerical instability issue, although in this particular simple case, it probably wouldn't matter. I'll check whether there is a simple way to prevent the crash, though.

**Comment by ntamas** [comment]
#820 is also related; although it is about edge betweenness, the stack trace where the crash happens is almost identical.

**Comment by mpoirel** [comment]
Thank you very much for your prompt answer and your explenation!

It indeed works when I put bigger figure for the too small weights.

I'll have to figure out a proper way of converting the edge weights but that's a lesser issue. Thanks!

**Comment by ntamas** [comment]
My advice is: decide in advance what precision you will need (e.g., 10 significant digits), then multiply every weight by 10^10, and round them to the nearest integers. You will not have this problem then because integers are not prone to the accumulation of numeric errors.

**Comment by pkreissel** [comment]
I also have this problem: R Session aborts while using cluster edge betweenness. 
Doing `E(g)$weight <- as.numeric(floor(E(g)$weight*10^10))` didnt solve the issue.

**Comment by ntamas** [comment]
Please provide a [short, self-contained, reproducible example](http://sscce.org/) so we can test this on our own. Your issue seems to be unrelated to #1009 or #820 as it does not go away when switching to integers as weights.

**Comment by vtraag** [comment]
This problem seems to be solved in PR #1199.
