### ISSUE TITLE
igraph_isomorphic_function_vf2() errors out when using colors and different numbers of vertices

### ISSUE THREAD

**Issue by sbstnk** [igraph/igraph#1010]
When checking if two graphs with a different number of vertices are isomorphic without specifying vertex colors, igraph_isomorphic_function_vf2() returns 0, as expected. However when specifying colors it results in an error. This is because the [comparison of the number of vertices](https://github.com/igraph/igraph/blob/master/src/topology.c#L1122) happens only after [checking if both vertex color vectors have the same size as graph1](https://github.com/igraph/igraph/blob/master/src/topology.c#L1108). The same happens for edge colors as well. So the order of these checks should probably be changed.

**Comment by ntamas** [comment]
Thanks, this is now fixed!
