### ISSUE TITLE
Plotting isolated nodes with  graph_from_data_frame, with from-to structure

### ISSUE THREAD

**Issue by skanskan** [igraph/igraph#1011]
I'm working with data.frames with columns "from" and "to" and I would like to create network graphs from them.

For example:   

    mydata <- data.table(from=c("John", "John", "Jim", "Jesse"),
       to=c("John", "Jim", "Jack", NA))
    mygraph <- graph_from_data_frame(d=mydata, directed=T)
    plot(mygraph, vertex.label.dist=2) 

The presence of that NA produces an error.

If I just remove the NA row the lonely node is not plotted.

    mydata <- data.table(from=c("John", "John", "Jim"),to=c("John", "Jim", "Jack"))
    mygraph <- graph_from_data_frame(d=mydata, directed=T)
    plot(mygraph, vertex.label.dist=2) 

![remove](https://user-images.githubusercontent.com/4120283/27516446-ebfb5b8c-59b1-11e7-9649-c6d65db118b8.png)

I would like to get the same result than with:

    g4 <- graph( c("John", "Jim", "Jim",  "Jack", "John", "John"), isolates=c("Jesse") )  
    plot(g4,  vertex.label.dist=2) 

![prueba](https://user-images.githubusercontent.com/4120283/27516451-fd88f814-59b1-11e7-855a-fdf47e9f1247.png)

but working with two columns, from and to.

Could you please add that option to igrapfh, please?  Or tell me another solution.
When any of the "from" or "to" is NA then just plot the node without edges and without producing errors.

Regards

https://stackoverflow.com/questions/44746822/plotting-isolated-nodes-in-igraph-with-graph-from-data-frame-missing

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#202
