### ISSUE TITLE
Generating Barabasi graphs with predefined initial graph

### ISSUE THREAD

**Issue by harshays** [igraph/igraph#1013]
Suppose I have a graph G and I want to add N nodes to it using preferential attachment. Is it possible to use ig.Graph.Barabasi to do this (example: ig.Graph.Barabasi(N, M, initial_graph=G))?

**Comment by ntamas** [comment]
Yes, but 1) you need to specify `N` plus the vertex count of the original graph and 2) you need `start_from` and not `initial_graph`.

**Comment by ntamas** [comment]
This issue was moved to igraph/python-igraph#132
