### ISSUE TITLE
To provide donut shaped vertices

### ISSUE THREAD

**Issue by cndesantana** [igraph/igraph#1014]
Hi,

It would be nice if we could plot donut shaped vertices (donut/torus/ring/...). I know it is possible to plot a donut-vertex by plotting a pie-vertex with a smaller circle-vertex inside. But I wonder it would be much nicer if the donut-shaped was defined in Igraph. We could get inspiration from Plotly: https://plot.ly/r/pie-charts/undefined 

Thanks

**Comment by ntamas** [comment]
Vertex drawing is specific to the R interface so I'm moving this issue there.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#207
