### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by msgoussi** [igraph/igraph#1016]
There is a binary version available but the source version is later:
       binary source needs_compilation
igraph  1.0.1  1.1.1              TRUE

Warning in install.packages :
  running command '"D:/R/R-3.4.1patched/bin/x64/R" CMD INSTALL -l "D:\R\R-3.4.1patched\library" C:\Users\310677\AppData\Local\Temp\Rtmp2HQfNS/downloaded_packages/igraph_1.1.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

**Comment by gaborcsardi** [comment]
Complain to CRAN please. I am not sure why they do not build a new binary.

**Comment by msgoussi** [comment]
Dear I cloned the zip file and tried to build the package, and I get an error. Please advise.
