### ISSUE TITLE
CRAN build fails on solaris

### ISSUE THREAD

**Issue by wlandau-lilly** [igraph/igraph#1017]
Some [CRAN checks for igraph](https://cran.r-project.org/web/checks/check_results_igraph.html) are failing. Specifically, v1.1.1 does not install on the Solaris server, which is [breaking the checks for drake](https://cran.r-project.org/web/checks/check_results_drake.html) and other packages.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#208
