### ISSUE TITLE
Unclear (wrong?) documentation for strength

### ISSUE THREAD

**Issue by Silmathoron** [igraph/igraph#1022]
From the [C](http://igraph.org/c/doc/igraph-Structural.html#igraph_strength) and [Python](http://igraph.org/python/doc/igraph.GraphBase-class.html#strength) docstrings of `strength`, it is difficult to know what `strength` returns if no `weights` arguments is given.

From the C doc, one would believe that the non-weighted degree list is returned. However, from [`centrality.c#L414`](https://github.com/igraph/igraph/blob/02005680aebb4281f2964c6d2d8d98851fce63b9/src/centrality.c#L414) it seems to me that the eigenvector centrality is in fact used by default.

I don't know if this is true in C, but calling from Python, this is what happens. Since I do not think this is a standard behaviour -- and even if it is -- could you add this explicitely in the Python doc? Currently Python users do not know what the default behaviour is.

**Comment by szhorvat** [comment]
I have not looked at the Python version, but in the C interface `igraph_strength` returns what the documentation says for unweighted graphs.  You are linking to the implementation of `igraph_eigenvector_centrality_directed`, but you are talking about strength.  The implementation of `igraph_strength` is here:

https://github.com/igraph/igraph/blob/master/src/structural_properties.c#L6003

You can see that it falls back to `igraph_degree` when there are no weights.

**Comment by Silmathoron** [comment]
My bad, I must be missing sleep, I made a mistake that led me to believe it was EV centrality... don't know how I ended up quoting the wrong code though... sorry for the noise.

Anyway, I think it would still be a good idea to state the same in the Python doc if possible.
