### ISSUE TITLE
igraph_strvector error

### ISSUE THREAD

**Issue by mohkar123** [igraph/igraph#1025]
**python2.7: igraph_strvector.c:128: igraph_strvector_get: Assertion `sv->data[idx] != 0' failed.**
 I'm getting this error when running my code  on a server which I don't have root access to. Why is this happening:?

**Comment by szhorvat** [comment]
It's impossible to tell without a reproducible example. Please see http://sscce.org/ for guidance and construct *the shortest possible* program that exhibits the problem.

**Comment by ntamas** [comment]
@mohkar123 Also, please note that this is an issue tracker and not a support forum. Unless you are certain that this is a bug in igraph and not in your code, please consider sending your question to the igraph-help@nongnu.org mailing list instead.

T.
