### ISSUE TITLE
bfs might have a bug

### ISSUE THREAD

**Issue by tintinthong** [igraph/igraph#1032]
Hi I do not understand why the output is as such. There is a possible bug in bfs (or I might not understand correctly)

```
tree<-graph_from_literal(3-+5:6,6-+2,3-+4)
obj<-graph.bfs(tree,root=3, neimode="out",father=TRUE,order=TRUE,unreachable = FALSE)
```
Observe that the output is obj$order = 6 2 <NA> <NA> <NA> and obj$father= 3 5 6 2 4. But I expect it to be obj$order = 3 5 6 4 2 and obj$father= NA 3 3 3 2

**Comment by tintinthong** [comment]
I was looking at the graph.bfs code and the naming issue of father becomes a problem after `.Call(C_R_igraph_bfs, graph, root, roots, neimode, 
    unreachable, restricted, as.logical(order), as.logical(rank), 
    as.logical(father), as.logical(pred), as.logical(succ), 
    as.logical(dist), callback, extra, rho)` is called in the `graph.bfs` function.

**Comment by tintinthong** [comment]
So although I see that the problem may be due to internals. It usually has to do with the naming of vertices. If the vertices are randomly generated by ID's (not symbolic names as in graph_from_literal), the bfs function works perfectly.

**Comment by ntamas** [comment]
igraph vertices always have numeric IDs from 1 to the number of vertices, inclusive (at least in R; in C or Python, the vertex IDs are zero-based). When you use `graph.from.literal`, the numbers that _you_ use end up being used as vertex _names_, not IDs, and by convention, names are always strings in igraph. Try `graph.bfs(tree, root="3")`.

**Comment by tintinthong** [comment]
This is what I obtain. I am unsure if the output is the named output or the some index(perhaps index of the vertex sequence , ie V(tree))

```
$root
[1] 1 #this is obviously an index

$neimode
[1] "out"

$order
+ 5/5 vertices, named, from 6fee7e1:
[1] 3 5 6 4 2 #this should be the names

$rank
NULL

$father
+ 5/5 vertices, named, from 6fee7e1:
[1] 3 5 6 2 4  #this should be a names

```
$order makes sense but  $father does not. , it still makes no sense. The documentation says that **The father of each vertex, i.e. the vertex it was discovered from.**. Does this mean corresponding to $order or the index of the vertex sequence? Still don't I expect father to be `NA 3 3 3 6`

**Comment by ntamas** [comment]
I think this is a bug in the printing routine corresponding to `obj`; the raw content of `obj$father` _before_ the vertex names are resolved is correct (irrelevant parts omitted):

```
> dput(obj$father)
structure(c(NA, 1L, 1L, 3L, 1L), [...]
```

Resolving `c(NA, 1, 1, 3, 1)` to the corresponding vertex names yields the correct result:

```
> V(tree)$name[c(NA, 1, 1, 3, 1)]
[1] NA  "3" "3" "6" "3"
```

As I am not familiar with the internals of the R interface but it's clearly an R-specific issue, I will move this to igraph/rigraph

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#228
