### ISSUE TITLE
object ‘.innei’ is not exported by 'namespace:igraph'

### ISSUE THREAD

**Issue by mkhezr** [igraph/igraph#1033]
Hello!

I'm developing an R package which depends on igraph.  but R CMD check shows the following:

Warning messages:
1: object ‘.innei’ is not exported by 'namespace:igraph' 
2: object ‘.outnei’ is not exported by 'namespace:igraph'

Is there a workaround to get check to pass clean? Why aren't these special vertex indexing functions exported?

Thanks

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#229
