### ISSUE TITLE
OOM while executing cliques() in SparkR

### ISSUE THREAD

**Issue by minicp9523** [igraph/igraph#1036]
Here is the situation, I have spent so much time researching Clique Percolation Method with SparkR, and it is fine to process data with 200 thousand records(18MB) for single node resource. Then, when I was trying to enhance the performance by adding 3 computing nodes, I found that SparkR job can not be distributed to the other nodes in the cluster, eventually cause the resource of single computer being consumed. However, I have also tried several kinds of job to ensure the SparkR environment is correct. The result shows that the other kinds of SparkR job can be distributed to the other nodes and consume the resource of each node normally.
Even when I execute **cliques()** to process 300 thousand records(24MB) only, the job is still being processed in a single node and running out of memory. 
There are 4 openstack virtual machines in my cluster, and the resource allocation of my computing nodes is 8 cores, 16GB RAM, and 160GB HD, respectively.

Thank you!

**Comment by gaborcsardi** [comment]
Clique finding is a hard problem, unfortunately.

**Comment by buddha314** [comment]
This is almost certainly not a helpful comment, but literally every time I get suckered into trying Spark, I get disappointed…

Good luck!

<~>
Brian Dolan
Co-Founder, Chief Scientist

DEEP 6 AI
+1 323 485 8005  | cell
+1 626 585 8586  | office
deep6.ai<https://deep6.ai/>








On Oct 17, 2017, at 7:16 PM, Roy <notifications@github.com<mailto:notifications@github.com>> wrote:

SparkR

**Comment by ntamas** [comment]
Do you actually need all the cliques? If you want to use the clique percolation method, it is enough to enumerate the maximal cliques only.
