### ISSUE TITLE
lazy_dots "use of NULL environment is defunct" when subsetting edges from function body

### ISSUE THREAD

**Issue by jtatria** [igraph/igraph#1038]
Hello!

Sub-setting an edge vector with a logical vector from inside a function's body fails with the error below if the  logical vector used for sub-setting has previously been evaluated inside the function's body.

Passing the logical vector as an un-eveluated promise works fine.

igraph_version: 1.1.2.9000

PS: google led me to this [Jan 2015 igraph-help thread](https://lists.nongnu.org/archive/html/igraph-help/2015-01/msg00011.html) discussing the same issue.

MWE:
````
require( igraph )

null_defunct <- function( x, set ) {
    bomb <- set
    return( x[ set ] );
}

g   <- sample_grg( 1000, .2 );
set <- ( runif( length( E( g ) ) ) > .3 )
null_defunct( E( g ), set )
````
Error:
````
Error in lazy_dots(..., .follow_symbols = TRUE) : 
  use of NULL environment is defunct
````

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#233
