### ISSUE TITLE
Questionable behaviour of edge betweenness based community detection with weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1040]
This problem concerns the C core, but for now I am going to give examples using the Mathematica interface (because I'm the most fluent in it and because I know precisely how it maps to C). I will add R or Python examples if requested.

Edge betweenness based community detection is works by repeatedly cutting the edge with the highest edge betweenness.  This way it constructs a "dendrogram", i.e. a series of possible clusterings. Then it selects the one with the highest modularity.

Betweenness calculations are based on the concept of graph distance. When the algorithm is given weights, it interprets it as the "length"/"distance" of that edge.  Conceptually, vertices connected with a "short" / "low weight" edge are more tightly coupled than those connected by a "long" / "high weight" edge.

But modularity calculations use weights the opposite way.  It is high weight values (instead of low ones) that indicate tighter coupling.

The problem with `igraph_community_edge_betweennes()` is that it simultaneously uses both "interpretations".

Let's take the following example graph (Mathematica syntax):

```
g = Graph[{1 <-> 2, 2 <-> 3, 3 <-> 4, 4 <-> 1}, 
  EdgeWeight -> {5, 1, 1, 1}, VertexLabels -> "Name", 
  EdgeLabels -> "EdgeWeight"]
```

![image](https://user-images.githubusercontent.com/1212871/32459768-fe5ea566-c330-11e7-8322-f54fda5abaf0.png)

Edge weights are written over the edges.

It is clear that the edge with the highest betweenness is `3 <-> 4`. That's because the shortest path between `1 -> 2` is `1 -> 4 -> 3 -> 2` with a total distance of 3, instead of the distance of 5 along `1 -> 2`.

Once that is removed, the highest betweenness edge is `1 <-> 2` as it's in the "middle" of a graph like this:

![image](https://user-images.githubusercontent.com/1212871/32460092-e4f6a956-c331-11e7-99f6-168124d6c0db.png)

It is reasonable to expect `{1,4}` and `{2,3}` as the communities, since the `1 <-> 2` coupling was less tight than all the others.

----

The function actually finds a single "community":

![image](https://user-images.githubusercontent.com/1212871/32459803-17982386-c331-11e7-956d-e9d53ccb096f.png)

Here are the edges in the order of their removal, and the betweenness of each one at that stage:

```
In[35]:= cl["RemovedEdges"]
Out[35]= {3 <-> 4, 1 <-> 2, 2 <-> 3, 4 <-> 1}

In[36]:= cl["EdgeBetweenness"]
Out[36]= {4., 4., 1., 1.}
```

It's as we expected them.

The following are the modularities for each stage of the partitioning, in *reverse* order:

```
In[20]:= cl["Modularity"]
Out[20]= {-0.3125, -0.28125, -0.25, 0.}
```

We can verify that they indeed correspond to the following partititonings:

```
In[34]:= IGModularity[g, #] & /@
 {
  {{1, 2, 3, 4}},
  {{1, 4}, {2, 3}},
  {{1, 4}, {2}, {3}},
  {{1}, {4}, {2}, {3}}
  }

Out[34]= {0., -0.25, -0.28125, -0.3125}
```

Notice that they are negative, the modularity never improves. This is because `IGModularity` (i.e. `igraph_modularity()`) considers `1 <-> 2` to be very tightly coupled with its weight of 5.  In fact it would prefer the following partitioning:

```
In[40]:= IGModularity[g, {{1, 2}, {3, 4}}]
Out[40]= 0.125
```

I hope it's clear why I think that the current behaviour of `igraph_community_edge_betweennes()` is not quite right.  But figuring out what it should actually do isn't quite a trivial question.

Am I misunderstanding something here?

**Comment by ntamas** [comment]
Szabolcs, your understanding is correct. Modularity and the edge betweenness method should never be "mixed" because they treat edge weights fundamentally differently. I think the problem does not arise when the graph is unweighted, though, and we cannot prevent the user from shooting himself in the foot by calculating modularity on a community structure obtained by edge betweenness clustering.

Anyway, I don't think there's a single "right" way to "fix" this. Any sort of fix would involve somehow translating weights-as-distances into weights-as-similarities, and the choice for such a function is quite arbitrary. Personally, I usually do it by fitting a sigmoid function to the weight distribution such that the median weight is mapped to 0.5 and +/-3 standard deviations from the median are mapped to 0.01 and 0.99, respectively, but that's just a matter of taste. The user *should* have an understanding of how the edge betweenness community detection works (i.e. that it treats edge weights as dissimilarities) instead of just blindly using it. The best we can do is to emphasize this caveat in the documentation.

**Comment by szhorvat** [comment]
Yes, there's no one good choice.

Then basically the right way to use this function *with weights* is to only take the hierarchical information (not the returned partitioning), then pick the desired partitioning manually.

> The user should have an understanding of how the edge betweenness community detection works

The scary thing is that igraph is exactly the kind of package that gets a lot of naïve use from people with a non-quantitative background.

> (i.e. that it treats edge weights as dissimilarities)

... and that *the very same function* will treat them as similarities in the next step (during the same function call), while calculating modularities.

**Comment by ntamas** [comment]
Ah, okay, I get your point. (I have forgotten that `igraph_community_edge_betweenness` happens to return the "best" division according to the modularity score - I was thinking that this is implemented in the higher-level interfaces separately). So, yes, you are right, the `modularity` and `membership` arguments do not really make sense if the graph is weighted and not all weights are equal. We can print a warning in such cases using `IGRAPH_WARNING` in the C layer - or is there anything else that you think we could do to alleviate the problem? (Apart from removing the `modularity` and `membership` arguments completely - I think these can actually be useful to the user in the unweighted case).

**Comment by szhorvat** [comment]
The `modularity` and `membership` arguments are definitely useful for the unweighted case (which is likely the more common usage).

After seeing the problem more clearly, I agree that the best solution is to print a warning.

Actually, my personal preference is to leave the warning to the higher level interfaces (because then I can more easily make *only this* warning toggleable without affecting other igraph warnings), but that's not a very igraph-like solution (most warnings and checks are usually done in C).

Sorry about starting a long thread, and ending up asking for no changes at all.

**Comment by szhorvat** [comment]
Probably the best way is to just add the warning, and force the implementors of high-level interfaces to deal with it in the proper manner (instead of being lazy).

Both the R and the Python interfaces already have a way to *not* calculate modularities.

The fact that the Mathematica one doesn't is my bad decision, and I should fix that.

**Comment by ntamas** [comment]
Also related: https://github.com/igraph/igraph/commit/e96fadb3f1715c7c6256370f707aa693efd46981

**Comment by szhorvat** [comment]
I haven't tested the code yet, but isn't it a bit too much to issue a warning when modularity is requested *even when no weights are used*?

**Comment by ntamas** [comment]
Note that the conditions inserted in e96fadb are in a branch that is executed only when `weights != 0`.

**Comment by szhorvat** [comment]
There's a minor typo:

> Membership vector **is** be selected

should be "will be"

**Comment by ntamas** [comment]
Thanks, fixed in 61bb23d2 (I have no idea how I could have overlooked this).

**Comment by szhorvat** [comment]
It was pointed out to me that one way this situation is handled is to use `centrality/weight` instead of `centrality` to decide which edge to remove next.

See https://arxiv.org/pdf/0906.0612.pdf page 24

> The method can be simply extended to the case of weighted graphs, by suitably generalizing the edge betweenness. The betweenness of a weighted edge equals the betweenness of the edge in the corresponding unweighted graph, divided by the weight of the edge (Newman, 2004).

> https://journals.aps.org/pre/abstract/10.1103/PhysRevE.70.056131

It also applied to multi-graphs.

Do you agree that it would be useful to eventually modify this function to use this method for weighted graphs?

**Comment by ntamas** [comment]
Hmmm, I'll have to think about that and read the Newman paper eventually. I think that the reasoning behind this idea basically says that an edge with weight *w* is the same as having *w* parallel edges, each with weight = 1. This naturally leads to the division of the edge betweenness by *w* (since any shortest path that goes through the edge is equally likely to go through any of the replacement edges). However, I'm not sure whether that can be generalized to fractional weights as well. (Of course one can always argue that if you have fractional weights, just multiply every weight with 1e10 and then round to the nearest integer).

Also, doing it this way might lead to confusion when one applies the weighted edge betweenness community detection on a graph and then tries to "trace" what's going on by calculating the weighted edge betweennesses (using `igraph_edge_betweenness`) after each removal. Not a big deal, but this has to be documented explicitly.

**Comment by pvincentruz** [comment]
So I am really thankful for this discussion thread. Just wanted to check given it was las commented on a year ago. Currently, I am running is as:

cluster_edge_betweenness(chemistry_network, weights = E(chemistry_network)$weight, directed = TRUE,
                                       edge.betweenness = TRUE, merges = TRUE, bridges = TRUE,
                                       modularity = FALSE, membership = FALSE)

That is, as you guys said modularity and membership FALSE. And nothing has changed on the algorithm to make this answer different for weighted networks?

Thanks
> Hmmm, I'll have to think about that and read the Newman paper eventually. I think that the reasoning behind this idea basically says that an edge with weight _w_ is the same as having _w_ parallel edges, each with weight = 1. This naturally leads to the division of the edge betweenness by _w_ (since any shortest path that goes through the edge is equally likely to go through any of the replacement edges). However, I'm not sure whether that can be generalized to fractional weights as well. (Of course one can always argue that if you have fractional weights, just multiply every weight with 1e10 and then round to the nearest integer).

**Comment by ntamas** [comment]
> And nothing has changed on the algorithm to make this answer different for weighted networks?
Nothing has changed as far as I know.
