### ISSUE TITLE
Fastest way to call shortest_path from Python in loop changing the weights

### ISSUE THREAD

**Issue by Birdy3000** [igraph/igraph#1041]
c_t is a python list containing millions of integer values. 
I call graph.get_shortest_paths(origin, destination, c_t, OUT, output="epath") in a loop (1000+ iterations) changing the weights c_t every iteration. Is this call with the python list optimal, or is there a better variant which is faster?

- [ ] This issue is for the C core of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
This is probably as good as it gets. However, please do not file support questions and questions not related to the C core of igraph into this repository. We have a separate mailing list at igraph-help@nongnu.org for support questions.
