### ISSUE TITLE
Wishlist: Graph colouring algorithms

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1042]
This is a feature request to implement graph colouring (vertex or edge colouring) algorithms.

As a start, it would be nice to have the Brélaz algorithm

**Comment by szhorvat** [comment]
Here's a proposal for an interface:

    igraph_vertex_coloring_greedy(
        const igraph_t *graph, 
        igraph_vector_int_t *colors,
        igraph_greedy_coloring_t heuristic);

This function would implement greedy colouring with a selectable heuristic. Greedy colouring works by colouring vertices one by one with the smallest-indexed colour that differs from all already coloured neighbours. The performance depends on the order the vertices are considered. This is chosen based on the `heuristic` argument.  This method does not necessarily find the mimimum colouring.

Later we can have a separate function `igraph_vertex_coloring_minimum`, which may need to have a different signature (e.g. it may be able to find *all* minimum colourings).  This is to be decided when an implementation is ready.

Does this sound good to everyone (before I send a PR for the greedy algorithm)?

**Comment by ntamas** [comment]
Sounds good to me!

**Comment by szhorvat** [comment]
Fixed by #1043

**Comment by euler314** [comment]
@szhorvat We've discussed various aspects of this before, and I'm also very interested in adding more support for graph coloring to igraph. Did you have any plans of adding more heuristics? I'd be happy to contribute too.

**Comment by szhorvat** [comment]
@euler314 I did not have immediate plans (primarily due to lack of time), but I am willing to work with you on this, especially if you can also contribute some code. I can help you get through the initial technical hurdles (i.e. the igraph-specific quirks).

Which specific method do you have in mind?

**Comment by euler314** [comment]
@szhorvat That would actually be quite helpful. I was thinking I could do RLF (recursive largest first), which in general is a bit slower than the sequential method you implemented. I could start out with writing a first implementation using igraph, and we can then see how to adjust it.

**Comment by szhorvat** [comment]
Can you give a link to a concise description of the algorithm (or provide a quick summary)?

**Comment by euler314** [comment]
There should be many resources describing RLF. The following is one of my first search hits: https://www.gerad.ca/~alainh/RLFPaper.pdf (see Figure 1 on page 3).
