### ISSUE TITLE
IGRAPH_CHECK used in function that doesn't return error code

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1044]
[Here](https://github.com/igraph/igraph/blob/61bb23d20e6bf0120123e27961bde9864b2876c5/src/structural_properties.c#L2046) the `IGRAPH_CHECK` macro is used in a function that does not return an error code. This seems like a bug, is it?  `IGRAPH_CHECK` automatically `return`s with an error code.

**Comment by ntamas** [comment]
Yes, that's a bug. Since it is in an internal function, the long-term solution will be to change the function to return an error code and provide the "real" return value in an output argument. This way it can signal errors to the caller, which can then forward the error via its own return value.

**Comment by gaborcsardi** [comment]
Why is this a bug? `igraph_vs_size` sets its `result` argument, and returns an error code.

**Comment by szhorvat** [comment]
The problem is not the function that `IGRAPH_CHECK` wraps, but the function it is contained in, i.e. `igraph_i_induced_subgraph_suggest_implementation`.  `IGRAPH_CHECK` expands to a `return` statement that returns an error code. But `igraph_i_induced_subgraph_suggest_implementation` does not currently return an error code.

**Comment by gaborcsardi** [comment]
In practice this is not a big issue, though, because all sensible error handlers `longjmp`, so the `return` is never actually executed.

**Comment by szhorvat** [comment]
It's not a big issue—I came across it while doing something unrelated, so I reported it.

But I'm confused about the intended use of `IGRAPH_CHECK` then. I thought that an error handler could simply do `IGRAPH_FINALLY_FREE()` and return. Then the error code would propagate up to the top caller.

**Comment by ntamas** [comment]
The error handler of the Python interface won’t longjmp - it will just call IGRAPH_FINALLY_FREE and set a flag in the Python interpreter to denote that an error has occurred.

**Comment by gaborcsardi** [comment]
@ntamas ... and then the interpreter longjmps out, no?

**Comment by ntamas** [comment]
Probably not, or even if it does, it happens after I have taken a look at the return code (which is used to construct the message of the Python exception that I pass to the interpreter using `PyErr_SetString`. So the full story is like this:

# User calls some method on an igraph Graph object.
# The call eventually ends up in the `python-igraph` glue code between Python and igraph.
# The glue code calls the appropriate igraph function in C.
# When an error happens, the error handler calls `IGRAPH_FINALLY_FREE` and then returns. The error code propagates up to the original igraph call, which returns it to the glue code.
# The glue code checks the error code. If it is not `IGRAPH_SUCCESS`, it raises a Python exception using `PyErr_SetString()` (or something similar) and returns `NULL`.
# Execution returns to the Python interpreter, which checks whether the return value was `NULL` and if so, raises the exception to the user.

So, as far as I know, no `longjmp` is involved here.

**Comment by szhorvat** [comment]
That's roughly what I do in the Mathematica interface too, except that it is the error handler that reports the error. This may in principle result in multiple errors reported as the error code propagates up to the top caller, but since the function / line number of the error is printed as well, this can actually be useful for figuring out what happened. The errors that occur due to invalid input (i.e. the ones users are most likely to see) don't usually go through multiple levels.

But, getting back to the original issue:

@ntamas asked me to use `igraph_error_type_t` as the return type of functions that return an error code. Currently, most functions simply return `int`, and `IGRAPH_CHECK` also uses `int` internally. This caused some annoying warnings with my compiler, so I changed `IGRAPH_CHECK` to use `igraph_error_type_t` too.

Then two things happened:

 - Some C++ code won't compile because C++ doesn't allow implicit conversion from an integer type to an enum type.

 - The compiler issued warnings for bugs like the one reported here.

Conclusion:

If the plan is to use `igraph_error_type_t` in the future, it may be worth also transitioning all old functions to this return type, and fixing those non-compiling C++ instances.  It will help find/prevent these types of bugs.

**Comment by ntamas** [comment]
Sorry, forget about my comment re `igraph_error_type_t` - just use `int` as the return type.
