### ISSUE TITLE
error in dyn.load; libiconv.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by arnold3** [igraph/igraph#1049]
Hello,

I'm having an issue with installing igraph on our server.  Here is the error I'm getting when I call install.packages("igraph").

Thanks for any help you can provide
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/raid1/home/micro/arnoldho/src/igraph/libs/igraph.so':
  libiconv.so.2: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/raid1/home/micro/arnoldho/src/igraph’

The downloaded source packages are in
	‘/tmp/RtmpV6NkjT/downloaded_packages’
Warning message:
In install.packages("igraph", lib = "src/") :
  installation of package ‘igraph’ had non-zero exit status
```

**Comment by ntamas** [comment]
I strongly suspect that `igraph` was compiled on a different machine and not on the server where you try to use it. On the machine where `igraph` was compiled, it was linked to a library named `iconv` (provided by `libiconv.so.2`), and this file is missing from the server. The safest is to compile and install `igraph` directly on the server.

**Comment by lambdamoses** [comment]
I compiled `igraph` from source when installing, and made sure that `libiconv` was installed and is on the path. I didn't get any error during the installation. But still, when I did `library(igraph)`, I got the following error:

```
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/lambda/R/x86_64-redhat-linux-gnu-library/3.5/igraph/libs/igraph.so':
  libiconv.so.2: cannot open shared object file: No such file or directory
```

I used coda to install `libiconv`. I have already added where I installed it (in `/home/lambda/anaconda3` to the PATH in `.Renviron`, so I have this:

```
> system("echo $PATH")
/home/lambda/mylibs/bin:/home/lambda/anaconda3/bin:/home/software/bustools_pmelsted/build/src/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> system("echo $LD_LIBRARY_PATH")
/home/lambda/anaconda3/lib:/usr/lib64/R/lib:/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
> system("locate libiconv.so.2")
/home/lambda/anaconda3/lib/libiconv.so.2
/home/lambda/anaconda3/lib/libiconv.so.2.6.0
/home/lambda/anaconda3/pkgs/libiconv-1.15-h516909a_1005/lib/libiconv.so.2
/home/lambda/anaconda3/pkgs/libiconv-1.15-h516909a_1005/lib/libiconv.so.2.6.0
```

So R can find `libiconv.so.2`, which makes it all the more mysterious why `igraph` can't find it. This is on CentOS, R 3.5.1.

**Comment by vtraag** [comment]
Can you manually load the library using `dyn.load("/home/lambda/anaconda3/lib/libiconv.so.2")`? You could then load the igraph library afterwards possibly. If so, R may still look in the wrong path for the libraries. You could perhaps check with `Sys.getenv(“LD_LIBRARY_PATH”)`. Perhaps running `system` launches a separate process with different environment variables?

**Comment by lambdamoses** [comment]
I tried that, but it turns out that the problem is more complicated. Here's the console log:

```
> dyn.load("/home/lambda/anaconda3/lib/libiconv.so.2")
> library(igraph)
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/lambda/R/x86_64-redhat-linux-gnu-library/3.5/igraph/libs/igraph.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
> dyn.load("/home/lambda/anaconda3/lib/libicui18n.so.58")
Error in dyn.load("/home/lambda/anaconda3/lib/libicui18n.so.58") : 
  unable to load shared object '/home/lambda/anaconda3/lib/libicui18n.so.58':
  /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/lambda/anaconda3/lib/libicui18n.so.58)
> Sys.getenv("LD_LIBRARY_PATH")
[1] "/home/lambda/mylibs/lib:/home/software/lib:/home/lambda/anaconda3/lib:/home/software/lib64:/usr/lib64/R/lib:/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib:/usr/lib64"
```
See, the anaconda3 directory is here. The second error is probably because the system wide gcc on our server is outdated. Also, I checked that the relevant shared objects can in fact be found:

```
> system("ldd /home/lambda/R/x86_64-redhat-linux-gnu-library/3.5/igraph/libs/igraph.so")
	linux-vdso.so.1 =>  (0x00007ffde0bfb000)
	libxml2.so.2 => /home/lambda/anaconda3/lib/libxml2.so.2 (0x00007f8bc9abb000)
	libz.so.1 => /home/software/lib/libz.so.1 (0x00007f8bc929e000)
	liblzma.so.5 => /home/lambda/anaconda3/lib/liblzma.so.5 (0x00007f8bc9a91000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f8bc9082000)
	libiconv.so.2 => /home/lambda/mylibs/lib/libiconv.so.2 (0x00007f8bc8d9d000)
	libicui18n.so.58 => /home/lambda/anaconda3/lib/libicui18n.so.58 (0x00007f8bc8b1e000)
	libicuuc.so.58 => /home/lambda/anaconda3/lib/libicuuc.so.58 (0x00007f8bc896b000)
	libicudata.so.58 => /home/lambda/anaconda3/lib/libicudata.so.58 (0x00007f8bc7069000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f8bc6e65000)
	libgmp.so.10 => /home/lambda/anaconda3/lib/libgmp.so.10 (0x00007f8bc6dcd000)
	libRlapack.so => /usr/lib64/R/lib/libRlapack.so (0x00007f8bc69d6000)
	libRblas.so => /usr/lib64/R/lib/libRblas.so (0x00007f8bc44e2000)
	libgfortran.so.4 => /home/lambda/anaconda3/lib/libgfortran.so.4 (0x00007f8bc43b4000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f8bc40b2000)
	libquadmath.so.0 => /home/lambda/anaconda3/lib/libquadmath.so.0 (0x00007f8bc9a59000)
	libR.so => /usr/lib64/R/lib/libR.so (0x00007f8bc3a3e000)
	libstdc++.so.6 => /home/lambda/anaconda3/lib/libstdc++.so.6 (0x00007f8bc38fd000)
	libgcc_s.so.1 => /home/software/lib/libgcc_s.so.1 (0x00007f8bc36e7000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f8bc331a000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f8bc3112000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8bc9a05000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f8bc2df0000)
	libgomp.so.1 => /home/software/lib/libgomp.so.1 (0x00007f8bc2bdb000)
	libreadline.so.6 => /usr/lib64/libreadline.so.6 (0x00007f8bc2995000)
	libtre.so.5 => /usr/lib64/libtre.so.5 (0x00007f8bc2785000)
	libpcre.so.1 => /home/lambda/anaconda3/lib/libpcre.so.1 (0x00007f8bc273e000)
	libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f8bc252e000)
	libicuuc.so.50 => /usr/lib64/libicuuc.so.50 (0x00007f8bc21b5000)
	libicui18n.so.50 => /usr/lib64/libicui18n.so.50 (0x00007f8bc1db6000)
	libtinfo.so.5 => /usr/lib64/libtinfo.so.5 (0x00007f8bc1b8c000)
	libicudata.so.50 => /usr/lib64/libicudata.so.50 (0x00007f8bc05b8000)
```

So I wonder why those shared objects can be found in the terminal but can't be found when attaching igraph. This is all so weird since for months, I've been using R packages that depend on igraph without any problem, and that's with the same outdated gcc. Yesterday I was trying to install the package `dyno`, which requires me to add my `GITHUB_PAT` in `.Renviron`. I still have the correct `PATH`  and `LD_LIBRARY_PATH`, and the only `.Renviron` on the entire server is in my personal home directory and it is the correct one, so I can rule out the possibility of a rogue `.Renviron` causing problems. I don't have any `.Rprofile` file. I don't know why, ever since, I've been getting this error.

**Comment by ntamas** [comment]
Okay, first of all: I find it a bit worrying that random, internal libraries from Anaconda Python end up linked to igraph and then in turn get linked into R. Would it be possible to re-compile igraph completely from scratch _after_ removing `/home/lambda/anaconda3/lib`, `/home/software/lib` and maybe also `/home/software/lib`  from the library path? The ideal situation would be to have a version of the igraph library on your machine that links solely to system libraries and any other libraries provided by R, but not to any libraries provided by third-party software as it can lead to lots of incompatibilities and mysterious error messages. (For instance, the one about `version `CXXABI_1.3.8' not found` means that you are trying to load a library that was linked to a different ABI version of the C++ standard library than the rest of the libraries that you loaded).

**Comment by vtraag** [comment]
As an alternative to the suggestion by @ntamas, you may also simply install `r-igraph` using conda from https://anaconda.org/conda-forge/r-igraph. Or is there any particular reason that you want to compile the package yourself?

**Comment by lambdamoses** [comment]
There's no linux CRAN binary for igraph, so whenever I run `install.packages("igraph")`, it will be compiled from source. Anaconda does cause trouble with compiling R packages on Mac, but so far it hasn't caused trouble on Linux. I'll try removing Anaconda from the path.

**Comment by lambdamoses** [comment]
Thank you, @ntamas. I removed Anaconda3 and anything with `/home/software` and `/home/lambda/mylibs` from `PATH` and `LD_LIBRARY_PATH` in my `.Renviron`. Now I only use system libraries and that error is gone and `igraph` can be loaded normally.

**Comment by hmassalha** [comment]
Dear @ntamas 
I am facing the same error showing that I am missing the same libs... `libiconv.so.2`, `libicui18n.so.58` (which was solved by the help of the IT unit, probably making more linkers). And know I am getting the following message: 
`Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/labs/shalev/hassanm/R/x86_64-pc-linux-gnu-library/3.5/igraph/libs/igraph.so':
  /home/labs/shalev/hassanm/lib64/libgfortran.so.4: version 'GFORTRAN_7' not found (required by /home/labs/shalev/hassanm/R/x86_64-pc-linux-gnu-library/3.5/igraph/libs/igraph.so)`


Here is my system command for `igraph`. do you have any suggestion why I am getting these errors: 
`system("ldd ~/R/x86_64-pc-linux-gnu-library/3.5/igraph/libs/igraph.so")
	linux-vdso.so.1 =>  (0x00007fff551e9000)
	libRlapack.so => /apps/RH7U2/gnu/R/3.5.1/lib64/R/lib/libRlapack.so (0x00007fa3090b1000)
	libgfortran.so.4 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libgfortran.so.4 (0x00007fa308d87000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa308a7b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa30885e000)
	libR.so => /apps/RH7U2/gnu/R/3.5.1/lib64/R/lib/libR.so (0x00007fa3081e2000)
	libstdc++.so.6 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libstdc++.so.6 (0x00007fa3080a1000)
	libgcc_s.so.1 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libgcc_s.so.1 (0x00007fa30808b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa307cca000)
	libRblas.so => /apps/RH7U2/gnu/R/3.5.1/lib64/R/lib/libRblas.so (0x00007fa307a9d000)
	libgfortran.so.3 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libgfortran.so.3 (0x00007fa307776000)
	libquadmath.so.0 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libquadmath.so.0 (0x00007fa307742000)
	libgomp.so.1 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libgomp.so.1 (0x00007fa30771c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa3099f7000)
	libreadline.so.6 => /lib64/libreadline.so.6 (0x00007fa3074d5000)
	libpcre.so.1 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libpcre.so.1 (0x00007fa307290000)
	liblzma.so.5 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/liblzma.so.5 (0x00007fa30706a000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fa306e59000)
	libz.so.1 => /apps/RH7U2/gnu/anaconda/5.2.0/python/3.6/lib/libz.so.1 (0x00007fa306c3c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fa306a34000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa30682f000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007fa3064b6000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007fa3060b7000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007fa305e8c000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007fa3048b8000)`

I have to say that I have `igraph `working before. After I fixed a similar problem with `libboost `for velocyto.R package I started to get all these error messages! 

Any help will be much appreciated,
HM

**Comment by Ge526874** [comment]
> 

Thank you. It works for me!
