### ISSUE TITLE
igraph_closeness returns NaN for a single-vertex graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1052]
`igraph_closeness` returns NaN when the input graph has a single vertex.

Is this by design?  If yes, could it be documented please?  Am I correct in thinking that this is the *only* situation where this function will return NaN?

It isn't clear what is the most reasonable value to return here, but a NaN can potentially wreak havoc in subsequent calculations, therefore it is useful to give users advance warning (i.e. document it for the C interface).

**Comment by ntamas** [comment]
Yes, it is by design and I think it is the only case where you can obtain NaN.
