### ISSUE TITLE
igraph_barabasi_game: allow A=0 when outpref=true

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1055]
In `igraph_barabase_game()`, the `A` parameter is required to be strictly positive. The function does not accept a value of `0`.

I assume that this restriction was considered reasonable because some vertices will have zero in-degree, thus if `A == 0` then `d^beta + A` is also zero for these vertices, i.e. they couldn't attract new connections.

However, if `outpref` is set to true, then the total degree is considered, thus `d^beta + A` is always positive, even if `A == 0`.

Would it be possible to loosen this restriction for the case when `outpref` is true?  Am I misunderstanding something?

http://igraph.org/c/doc/igraph-Generators.html#igraph_barabasi_game

**Comment by ntamas** [comment]
You have a point here and I don't see any problems with letting `A == 0` when `outpref` is true. I'll submit a patch soon.
