### ISSUE TITLE
libigraph.so.0 not found by other node in the cluster

### ISSUE THREAD

**Issue by JunWangmath** [igraph/igraph#1058]
Hi,

I installed the igraph in a local folder( /home/myname/ ) on a cluster without the root privilege. I also added the /home/myname/lib folder into $LD_LIBRARY_PATH. Then a code relies on igraph report the error ''error while loading shared libraries: libigraph.so.0: cannot open shared object file: No such file or directory''

Should I ask the root usrs to add the igraph path to LD_LIBRARY_PATH?
Thanks so much.

**Comment by ntamas** [comment]
No, it shouldn't be necessary -- however, as far as I know it is possible to disable the usage of `LD_LIBRARY_PATH` for security reasons, so it might be the case that this happens on your system.

Just as a quick check, ensure that `libigraph.so.0` is in `/home/myname/lib`, and then execute your program like this:

```
LD_LIBRARY_PATH=/home/myname/lib ./my_program
```

If it fails, post the output of `ldd ./my_program` here.

**Comment by ntamas** [comment]
One more thing. If you compile your own code, you can try linking statically to `libigraph.a` instead of linking dynamically to `libigraph.so.0` -- this would basically include igraph in the executable so it would not depend on the presence of `libigraph.so.0`.

**Comment by JunWangmath** [comment]
Thanks for the quick answer. I found the reason is that the igraph library is not made correctly and all check failed.  After installing it correctly, the cluster can find the libigraph.so.0.
