### ISSUE TITLE
wishlist:  arrow.size to accept a vector 

### ISSUE THREAD

**Issue by dhondorp** [igraph/igraph#1067]
Enable arrow.size to accept a vector that enables customization of arrowhead size by individual edge.

This feature was promised in 2013, but to my knowledge, has not been implemented

Make sure that these boxes are checked before submitting your issue -- thank you!

- [ X] This issue is for the C core of igraph.
- [ X] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
This is not an issue for the C core; the C core is not concerned with graph drawing. Moving this to igraph/rigraph.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#257
