### ISSUE TITLE
Wishlist: Realize a degree sequence

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1076]
Per #1073, it would be useful to have a function that directly constructs a graph having a particular degree sequence, e.g. with a Havel-Hakimi type algorithm.

I opened this bug as a planning ground for this functionality.

I suggest the name and prototype

```
int igraph_realize_degree_sequence(
        igraph_t *graph,
        igraph_vector_int_t *outdeg, igraph_vector_int_t *indeg,
        igraph_realize_degseq_t method)
```

This is analogous to `igraph_degree_sequence_game()`.

The basic Havel-Hakimi goes like this:

 - select a vertex
 - connect its stubs to the other highest-degree vertices
 - repeat until everything is connected or the procedure fails

The typical implementation always selects the highest degree node to connect to the rest. However, *any* node can be selected, and the result will a graph with different properties. The choice can be controlled by `method`.

The directed case would use https://arxiv.org/abs/0905.4913v2

The function will raise an error (`IGRAPH_EINVAIL`) if:
 - there are negative degrees
 - in- and out-degree sequences don't have the same length
 - in- and out-degree sequences don't sum to the same 

Otherwise, it proceeds with the algorithm, and it will return `IGRAPH_FAILURE` if it does not succeed, *but it does not raise an error*. This leaves it up to the user to decide what to do.

I would like to implement the core algorithm in (basic) C++98 instead of C because this will save me a lot of time (and lets me add other functionality instead of fussing with conversion to plain C). In fact, I have much of this working already I am just optimizing the directed case and adding extra methods.  igraph already has many C++ components, so why not use it for implementation new functions as well where it is actually helpful and the core igraph datatypes do not suffice?

Please comment on the idea/design.

Perhaps it'd be better to stick to `igraph_vector_t` (instead of `igraph_vector_int_t`) for the degrees for better interoperability with the other functions.

**Comment by ntamas** [comment]
Why do we need a separate function for this -- can't we simply add the Havel-Hakimi method as another supported method to `igraph_degree_sequence_game()`? It would also sidestep the problem of `igraph_vector_int_t` vs `igraph_vector_t` as the API of `igraph_degree_sequence_game()` has already picked one.

Re not raising an error: actually, `IGRAPH_FAILURE` is a generic error condition just like any other return value that is not equal to `IGRAPH_SUCCESS`. It is the responsibility of higher level interfaces to convert return values into exceptions, so, simply returning `IGRAPH_FAILURE` would still raise an exception in Python.

**Comment by szhorvat** [comment]
I'll make it return EINVAL and report a human-readable error. `vector_t` is indeed better for reasons of consistency.

The reason for a new function is that they are conceptually different.

`degree_sequence_game` is a `_game`, i.e. a random graph generator. The primary application area is network science / modelling.  The primary focus should be *uniform sampling* or at least sampling in a way that we can say something about the final distribution (I'm also working on this function and already updated the documentation with the analytical expression of the distribution for the `SIMPLE` method).

`realize_degree_sequence` constructs a graph directly, using a deterministic algorithm. This is more in a graph theory / combinatorics application area. (Of course, one application is related to sampling: generate one graph, then use `rewire` to approximate uniform sampling.)

Finally, it is good to separate these from an educational point of view. It is a typical student mistake that when they say "random thing" they don't think about what "random" really means. The specific distribution is critically important *will* affect the outcome of the calculation. There's a huge difference between "just give me one graph like this" and sampling many graphs according to some distribution then computing statistics on the result

**Comment by szhorvat** [comment]
Also, it seems to me that other packages that have such functions separate them (networkx, sage)

**Comment by ntamas** [comment]
Okay, understood. I have seen that you have submitted a PR already (#1077) so I'll try to review that soon (although I'm quite a bit behind schedule again so it might take some time).

Just a quick question: is `igraph_realize_degree_sequence()` expected to support any other (non-Havel-Hakimi-type) algorithms in the future, or will it be only HH but with different methods for choosing the next vertex to consider? If the focus is Havel-Hakimi only, then maybe `igraph_havel_hakimi()` is a better name, and we can leave `igraph_realize_degree_sequence()` for later when we add other, similar deterministic algorithms.

**Comment by szhorvat** [comment]
PR is already merged. Closing.
