### ISSUE TITLE
Inconsistency in documentation for igraph_maximal_cliques_count

### ISSUE THREAD

**Issue by carissableker** [igraph/igraph#1087]
![image](https://user-images.githubusercontent.com/26261557/38639739-2f967476-3da0-11e8-8f4e-8d3f0ef13424.png)

The type of argument `res` is given as an integer and as a vector. 

- [X] This issue is for the C core of igraph.
- [X] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
Thank you - probably a copy-paste error. The function declaration is correct - `res` is a pointer to an `igraph_integer_t`.

**Comment by carissableker** [comment]
Great!
