### ISSUE TITLE
igraph_set_contains is buggy

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1091]
`igraph_set_contains` is broken when used on empty sets.

https://github.com/igraph/igraph/blob/02005680aebb4281f2964c6d2d8d98851fce63b9/src/igraph_set.c#L257

It has `right = igraph_set_size(set)-1;`. If the set is empty, then `right == -1`. Despite this, it uses `right` for indexing (out-of-bounds error).

In my situation this led to `igraph_set_contains` claiming that an empty set contains `0`. 

What is the status of the `igraph_set_t` functions?  Are they safe to use?  They seem to get very limited use at the moment.

**Comment by szhorvat** [comment]
I would write it like this:

```
int igraph_set_contains(igraph_set_t* set, igraph_integer_t e) {
  long int left, right, middle;

  assert(set != NULL);
  assert(set->stor_begin != NULL);

  left = 0;
  right = igraph_set_size(set)-1;

  if (right == -1)
      return 0; /* the set is empty */

  /* search for the new element */
  while (left < right-1) {
    middle = (left+right)/2;
    if (SET(*set)[middle] > e) {
      right = middle;
    } else if (SET(*set)[middle] < e) {
      left = middle;
    } else {
      return 1;
    }
  }

  return SET(*set)[left] == e || SET(*set)[right] == e;
}
```

I can include it in the pill request together with the function in which I'm using `set`.

**Comment by ntamas** [comment]
The new version seems okay to me -- please go ahead and include it in your PR.
