### ISSUE TITLE
igraph_is_graphical_degree_sequence wrong result for directed sequence

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1092]
`igraph_is_graphical_degree_sequence` gives a wrong result for some directed sequences.

Here's a demo:

```
> is_graphical(c(1,0,1), c(0,2,0))
[1] FALSE
> is_graphical(c(0,2,0), c(1,0,1))
[1] TRUE
```

Of course, both are graphical. The witnesses are the `1->2<-3` and the `1<-2->3` graphs.

**Comment by szhorvat** [comment]
As far as I can tell, the directed version uses a construction algorithm to test graphicality (the concept is not explained in the comments).

In pull request #1077 I also provide a construction function, which works correctly for these cases.

![image](https://user-images.githubusercontent.com/1212871/38899943-e14cf82c-4299-11e8-8fba-e9e7a204594c.png)

A quick fix would be to simply use that implementation.

However, I am curious if there is an Erdős-Gallai type theorem for directed graphs.  Using that would be a better approach.

**Comment by szhorvat** [comment]
Looks promising: https://en.wikipedia.org/wiki/Fulkerson%E2%80%93Chen%E2%80%93Anstee_theorem

**Comment by ntamas** [comment]
I'll implement the method outlined in the Wikipedia article.
