### ISSUE TITLE
extended_chordal_ring is broken

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1093]
The `extended_chordal_ring` generator is broken.

With the example in the R documentation, it does not produce what is described (the result is not a regular graph, for instance). With many parameters, it'll cause a crash-hang. E.g., try `n=6` and W=`((2,3))`.

**Comment by szhorvat** [comment]
The problem is the original sizing of the `edges` vector:

`IGRAPH_VECTOR_INIT_FINALLY(&edges, nodes*degree);`

where

`long int degree=igraph_matrix_nrow(W)+2;`

Probably the assumption was that for each vertex, we add as many edges as `nrow`. Thus their degree is `2+nrow`. This is flawed because the other end of the edge is connecting to a vertex too, increasing their degree.

Thus, the program generates more edges than the size of `edges` and we get random crashes and hangs due to out-of-bounds access.

There is also a conceptual problem:

The documentation claims that each vertex will have the same degree. This is not true for two reasons:

 1. `i <-> i+offset` edges are added only if `i+offset < nodes`.  Thus the high index nodes won't get these edges.  Wasn't this intended to be `i <-> (i+offset) % nodes`?

 2. Imagining each edge to be directed, with the correction described in point 1., every node would have `nrow + 2` *out*-degree. But they would have differing *in*-degrees.

I have a fix for this that is ready to go: it includes the correction from point 1., and adds the option to use directed edges (which would make it easier for users to uderstand what the function does).

Before I send a PR, I need feedback (@gaborcsardi ?) about the conceptual part.

Here's an illustration:

![image](https://user-images.githubusercontent.com/1212871/39093138-e9249c60-461a-11e8-9021-f30de4a5b2e1.png)

**Comment by szhorvat** [comment]
Here's the proposed fix: https://github.com/szhorvat/igraph/commit/b20248f84ef36eeb8d2182e7ebefbc9f87ca2aaf

Based on my review of the use of the term *chordal ring*, this generalized implementation is reasonable. Given the nature of the generalization, it is also reasonable to allow for directed graphs.

**Comment by szhorvat** [comment]
@gaborcsardi  Could you please comment on whether the proposed fix is acceptable for submission, or otherwise suggest an alternative fix?

**Comment by gaborcsardi** [comment]
I don't remember what I had in mind when implementing this, sorry. If you trust that your changes are  good, go ahead please.

**Comment by szhorvat** [comment]
I think my changes make sense, and they seem consistent with the cited paper. 

My concern is that with these changes, this just seems to be a more restricted version of `igraph_lcf_vector`. It does the same thing, with the difference that there is no possibility to specify the number of repeats (it's always the same), that it may produce multigraphs and loops, and that each row of the matrix acts like a separate shifts vector.  I feel that there may be something I am missing.

**Comment by ntamas** [comment]
Sorry, I dropped the ball on this one.

Unfortunately I'm not that familiar with this function in igraph either (it definitely wasn't me who added this). I won't mind if it's just a restricted version of `igraph_lcf_vector()` - after all, every generator function is just a restricted version of `igraph_create()` ;) So, I'll check the pull request soon and then let you know - probably it's okay as is.

**Comment by szhorvat** [comment]
Was fixed by https://github.com/igraph/igraph/pull/1096
