### ISSUE TITLE
Can't create big graph

### ISSUE THREAD

**Issue by feelos0ff** [igraph/igraph#1094]
I tried to create static power law graph with n = 65536,   m = 262144.
I looked error message: "Error at games.c:3591: Too many edges requested, Invalid value".
I think, that the reason is integer overflow while checking edges count and that igraph uses `typedef int    igraph_integer_t;`

**Comment by ntamas** [comment]
Thanks, it's fixed now.

**Comment by ntamas** [comment]
Okay, I have posted another fix in 6711eba4 ; this will promote `max_no_of_edges` to a `double` so hopefully it should be enough.
