### ISSUE TITLE
Problem with BFS

### ISSUE THREAD

**Issue by feelos0ff** [igraph/igraph#1095]
I generated static power law graph  n = 4096, m = 65536 (If I use higher params it will reply too) and use BFS with random vid, but I had nodes in [0...4096] in output. Graph has no node  id 4096, but BFS result has... 
I had no problem for graphs with m smaller than 2^16.

**Comment by feelos0ff** [comment]
[4096_65536_0_input.txt](https://github.com/igraph/igraph/files/1952792/4096_65536_0_input.txt)
[4096_65536_0_out.txt](https://github.com/igraph/igraph/files/1952793/4096_65536_0_out.txt)

**Comment by feelos0ff** [comment]
I used python-igraph as wrapper.

**Comment by ntamas** [comment]
Please post your _full code_. The above files do not let me see what exactly you are doing.

For what it's worth, I have run a BFS from every single node of your input graph and the vertex indices in the result were always between 0 and 4095, inclusive:

```python
#!/usr/bin/env python

from igraph import Graph

g = Graph.Read_Edgelist("4096_65536_0_input.txt", directed=False)
for v in range(g.vcount()):
    bfs, layers, parents = g.bfs(0)
    if max(bfs) >= g.vcount() or max(parents) >= g.vcount():
        print v
```

The code above did not print anything for me.

**Comment by feelos0ff** [comment]
from igraph import Graph
import random


g = Graph.Static_Power_Law(n, m, exponent_out=3, exponent_in=-1, loops=False, multiple=False,
                           finite_size_correction=False)
init = random.randint(0, g.vcount() - 1)
m = 65536
n = 4096
bfs = g.bfs(init)
for component in bfs:
    for node in component:
        if node >= g.vcount():
            print init, node, g.vcount(), g.ecount()
            print(bfs)

**Comment by feelos0ff** [comment]
I use python2.7 python-igraph + master-branch version igraph

**Comment by ntamas** [comment]
The `bfs()` method does not return a list of components - please read its documentation. In particular, it returns a list of vertices visited in BFS order, then a list that contains indexes into the first list that tell you where a given distance was reached from the source node, and then it also returns the parent of every node in the BFS traversal. In your case, the second item of the returned tuple might contain `g.vcount()`, but that has nothing to do with vertex IDs.

If you want to find the connected components of the graph, use the `components()` method instead.

**Comment by feelos0ff** [comment]
Ok-) Thanks a lot!) It's my mistake
