### ISSUE TITLE
igraph_tree example/test is empty

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1097]
This is empty:

https://github.com/igraph/igraph/blob/master/examples/simple/igraph_tree.c

Did it get lost on the way or was it never written?

**Comment by ntamas** [comment]
It was never written (although it should have been):

https://github.com/igraph/igraph/commits/master/examples/simple/igraph_tree.c

**Comment by szhorvat** [comment]
OK, I'll handle this one.
