### ISSUE TITLE
Use mini-gmp?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1098]
igraph can optionally use the GMP library (a fast library for bigints). As far as I know, it is used only by the Bliss components, for computing the size of the automorphism group.

GMP includes a much smaller implementation of the most common interfaces, called `mini-gmp`.  It is ~4000 lines long and it is meant to be embedded directly in another project.

The tradeoff is speed (the promise is that it won't be more than 10x slower than the full GMP) and the lack of some rarely used features (not needed for igraph).

Would it make sense to just embed mini-gmp, and not make GMP optional anymore?

An alternative is using igraph's existing bigint implementation ... but that is more work since the API is different.

**Comment by ntamas** [comment]
> As far as I know, it is used only by the Bliss components
GMP is also required for the embedded GLPK library (`optional/glpk/glpgmp.h` includes `gmp.h`). Replacing GMP with `mini-gmp` would also mean to re-write the embedded GLPK library to depend on `mini-gmp` instead. The embedded GLPK library is then used by the Sugiyama layout algorithm and `igraph_optimal_modularity`, although these might not require bigints from GLPK directly. Anyway, I'd rather not mess around with it now that we have a working solution.
