### ISSUE TITLE
DFS : "dist" works as "order"

### ISSUE THREAD

**Issue by pptale** [igraph/igraph#1099]
Hi,

(Apologies for formatting. I am attaching the smallest code to highlight error) 

If we run DFS on clique of size 10, Order and Dist vector turns out to be same.

`int main() {
  igraph_t graph;
  igraph_vector_t order, dist;
  igraph_full(&graph, 10, 0, 0);
  igraph_vector_init(&order, 0);
  igraph_vector_init(&dist, 0);
  igraph_dfs(/*const igraph_t */ &graph, /*root*/ 0,
	     /*mode*/ (igraph_neimode_t) IGRAPH_ALL,
	     /*unreachable */(igraph_bool_t) 1,
	     &order, 0, 0, & dist, /*(in_callback)igraph_dfshandler_t */ 0, /*out_callback igraph_dfshandler_t*/ 0, /*extra*/ 0);
  cout<<"Order "; igraph_vector_print(&order);
  cout<<"Dist "; igraph_vector_print(&dist);      
  return 0;
`

This code produces following output.

`Order 0 1 2 3 4 5 6 7 8 9
Dist 0 1 2 3 4 5 6 7 8 9
`

**Comment by ntamas** [comment]
Why is this a problem? igraph visits the vertices in order `0, 1, 2, 3, 4, 5, 6, 7, 8, 9` along a single path that starts from vertex zero, so the distance of vertex _i_ (_in the traversal_, not the shortest-path distance) will be _i_ as well.

**Comment by pptale** [comment]
Sorry. My bad.
I thought distance refers to minimum distance between root and the node.
