### ISSUE TITLE
Testsuite fails with  ARPACK 3.6

### ISSUE THREAD

**Issue by tillea** [igraph/igraph#1107]
Hi,
there is a [bug report](https://bugs.debian.org/902945) against the Debian packaged version of igraph about an issue which was caused by the upload of arpack version 3.6.  The issue is

    197: Eigenvector centrality (igraph_eigenvector_centrality): FAILED (arpack.at:59)
    198: Non-symmetric ARPACK solver (igraph_arpack_rnsolve): FAILED (arpack.at:66)

Feel free to read the [full build log](https://tests.reproducible-builds.org/debian/history/amd64/igraph.html).
Kind regards, Andreas.

**Comment by szhorvat** [comment]
Just wanted to note that by default igraph uses the bundled ARPACK—so that's a quick fix.

Can you attach the relevant `testsuite.log` files for these tests?

**Comment by tillea** [comment]
Thanks for the hint to the quick fix.  However, the Debian rules are to prefer the packaged libraries over code copies.  So this would really be a lost resort.
Sorry for pointing not to the right link for the logs - I hope [this link](https://tests.reproducible-builds.org//debian/rbuild/unstable/amd64/igraph_0.7.1-2.1.rbuild.log.gz) will contain all information you need.

**Comment by szhorvat** [comment]
This has the output of `make check`, but I believe the relevant information is in the `testsuite.log` files for each failed test.  (This is also noted at the end of the `make check` output.) You will find them in `tests/testsuite.dir`.

**Comment by tillea** [comment]
[igraph-test-logs.zip](https://github.com/igraph/igraph/files/2164266/igraph-test-logs.zip)
Here are all test logs I was able to find.  Hope this helps, Andreas.

**Comment by ntamas** [comment]
The zip seems to be empty -- are you sure this is the correct one?

Thanks, T.

**Comment by tillea** [comment]
On Wed, Jul 04, 2018 at 02:08:38PM -0700, Tamás Nepusz wrote:
> The zip seems to be empty -- are you sure this is the correct one?

I admit I had uploaded an empty archive in the first place but realised some minutes later.  What you can download now (just repeated my check) is:

    $ unzip -l igraph-test-logs.zip | sed 's/^/    /'
    Archive:  igraph-test-logs.zip
      Length      Date    Time    Name
    ---------  ---------- -----   ----
            0  2018-07-04 22:26   tests/
            0  2018-07-04 22:22   tests/testsuite.dir/
            0  2018-07-04 22:22   tests/testsuite.dir/197/
          703  2018-07-04 22:22   tests/testsuite.dir/197/expout
         2252  2018-07-04 22:22   tests/testsuite.dir/197/testsuite.log
        17184  2018-07-04 22:22   tests/testsuite.dir/197/itest
          202  2018-07-04 22:22   tests/testsuite.dir/197/run
            0  2018-07-04 22:22   tests/testsuite.dir/198/
         1756  2018-07-04 22:22   tests/testsuite.dir/198/expout
         2669  2018-07-04 22:22   tests/testsuite.dir/198/testsuite.log
        17240  2018-07-04 22:22   tests/testsuite.dir/198/itest
          202  2018-07-04 22:22   tests/testsuite.dir/198/run
            0  2018-07-04 22:21   tests/testsuite.dir/076/
          880  2018-07-04 22:21   tests/testsuite.dir/076/expout
         2519  2018-07-04 22:21   tests/testsuite.dir/076/testsuite.log
        22136  2018-07-04 22:21   tests/testsuite.dir/076/itest
          201  2018-07-04 22:21   tests/testsuite.dir/076/run
            0  2018-07-04 22:22   tests/testsuite.dir/201/
            0  2018-07-04 22:22   tests/testsuite.dir/201/expout
         1295  2018-07-04 22:22   tests/testsuite.dir/201/testsuite.log
        17128  2018-07-04 22:22   tests/testsuite.dir/201/itest
          202  2018-07-04 22:22   tests/testsuite.dir/201/run
       114644  2018-07-04 22:22   tests/testsuite.log
    ---------                     -------
       201213                     23 files

Hope this helps, Andreas.

**Comment by ntamas** [comment]
Ah, tricky, I was clicking on the link in the notification email that I received from Github, and it returned the empty zip. The link above in the comment is correct. Thanks, will take a look at it.

**Comment by ntamas** [comment]
Back from holidays; I managed to reproduce the bug with ARPACK 3.6.2 on my Mac, which makes testing somewhat easier. Stay tuned.

**Comment by ntamas** [comment]
I have narrowed it down to changes made between ARPACK 3.5.0 and ARPACK 3.6.0 (i.e. ARPACK 3.5.0 does not have this issue but 3.6.0 does). [This commit](https://github.com/opencollab/arpack-ng/commit/d04bdf19b9189a971f8c3bf2561b8058994e9cb4) seems to be the only one that could be related, but I am not familiar enough with the ARPACK internals to be certain.

**Comment by ntamas** [comment]
Further narrowed it down to [this single line of code](https://github.com/opencollab/arpack-ng/pull/80/files#diff-cf67d0cc7fc368d2d5d4d1e4d8a6b32cR277) in ARPACK 3.6; reverting this line to where it was in ARPACK 3.5 also resolves the problem.

**Comment by ntamas** [comment]
Okay, I am pretty certain that this is an inherent issue with ARPACK 3.6; the same problem can also be triggered in GNU Octave (4.4.0) when linked with ARPACK 3.6 (I tried it on a Mac with Homebrew). The code below produces the PageRank matrix of the graph from the igraph test case:

```
octave:1> m = ones(11, 11) * 0.15 / 11;
octave:2> m(1, 2:11) += 0.85;
octave:3> m(2:11, 1) = (1 - m(1, 1)) / 10;
```

and it blows up exactly the same way:

```
octave:4> [v, lambda] = eigs(m, 1)
error: __eigs__: eigs: error -9999 in dnaupd
error: called from
    eigs at line 285 column 18
```

I'll file a bug report to `arpack-ng`.

**Comment by ntamas** [comment]
Bug [confirmed](https://github.com/opencollab/arpack-ng/issues/142#issuecomment-408326851) by the ARPACK developers so there's not much I can do about it yet (apart from disabling the test cases). @tillea: what do you think, would that work or shall we wait for the ARPACK devs instead to see if there is anything that can be done about it?

**Comment by tillea** [comment]
Hi Tamás,
On Fri, Jul 27, 2018 at 12:54:08AM -0700, Tamás Nepusz wrote:
> Bug [confirmed](https://github.com/opencollab/arpack-ng/issues/142#issuecomment-408326851) by the ARPACK developers so there's not much I can do about it yet (apart from disabling the test cases). @tillea: what do you think, would that work or shall we wait for the ARPACK devs instead to see if there is anything that can be done about it?
Thanks for the confirmation.  I have no idea how long the fix from arpack side will last.  It received some responses in a short time frame - also the Debian maintainer (sylvestre) involved.  So may be "do nothing and wait for 3 days" is a sensible approach and deactivating the test plus lowering the severity of the bug (not closing it) might be a sensible approach to the issue.  Kind regards, Andreas.

**Comment by ntamas** [comment]
Hi Andreas,

There's a proposed patch on the ARPACK side now, which fixes all but one of the test cases that fail with ARPACK 3.6. The remaining failure is easy to fix, so we can get this sorted out once the ARPACK patch gets released.

**Comment by ntamas** [comment]
Some fixes were committed above (also, trailing whitespace was trimmed here and there). I needed to fix how the eigenvectors are checked in `examples/simple/igraph_arpack_rnsolve.{c,out}` because ARPACK 3.6 will return a different eigenvector than what was hardcoded in the expected output, and both are valid. The remaining test case failures will be fixed when ARPACK is patched. The remaining changes in `src/arpack.c` are not necessary but they make things a bit nicer on igraph's side.

**Comment by tillea** [comment]
Hi, do you plan to do a new upstream release soon or should I rather try to apply this patch to the Debian packaged version?

**Comment by ntamas** [comment]
No plans for an upstream release as far as I know -- @gaborcsardi, let us know if you plan one.

**Comment by tillea** [comment]
Here are new build logs after I have applied patch 6391d0c (as far as possible there is a diff to the latest release in Debian - [here is what I have applied](https://salsa.debian.org/med-team/igraph/blob/master/debian/patches/fix_test_arpack-3.6.patch):
[build_logs.zip](https://github.com/igraph/igraph/files/2702135/build_logs.zip)
@ntamas, you are mentioned as Uploader in the Debian package and I guess your are **way** more competent than me for igraph (I do not use it and just try to get the build working).  Can you have a look at Salsa and try to fix this long standing issue?  If we do not fix it it, igraph will not be part of the next Debian release.
Kind regards, Andreas.

**Comment by tillea** [comment]
On Sun, Dec 23, 2018 at 09:23:37AM -0800, Tamás Nepusz wrote:
> @tillea indeed I was the uploader of the first version of the igraph package to Debian, but I am not using Linux actively any more.
Thanks a lot for your past work on the package.  Considering that you do not Linux any more should I drop you from the list of Uploaders or is there any chance that you will grab up this in the future?  I just want to make sure the package metadata will fit reality.

> Anyway, I'll try to take a look at it during the holiday season.
That would be really welcome.

**Comment by ntamas** [comment]
Back from holidays. So, it turns out that the test failure in one of the test cases can easily be remedied by removing the following four lines from `examples/simple/igraph_arpack_rnsolve.c` (they are not there in master either but they were accidentally left there when the patch was backported):

```patch
--- a/examples/simple/igraph_arpack_rnsolve.c
+++ b/examples/simple/igraph_arpack_rnsolve.c
@@ -167,11 +167,6 @@
     print_debug_output(&values, &vectors);
   }

-  igraph_matrix_print(&values);
-  printf("---\n");
-
-  igraph_matrix_print(&vectors);
-  printf("---\n");
-
   /* -------------- */

   options.nev=3;
```

I'm still investigating the other failure.

**Comment by ntamas** [comment]
> Considering that you do not Linux any more should I drop you from the list of Uploaders
Yes, please do so - it's unlikely that I will have time to pick this up again in the future.

**Comment by ntamas** [comment]
Commit 17cc5be8 seems to have solved the failing test cases in my Debian testing VM. @tillea, please let me know if it worked or not.

**Comment by tillea** [comment]
Hi Tamás,

On Wed, Jan 02, 2019 at 07:52:39AM -0800, Tamás Nepusz wrote:
> Commit 17cc5be8 seems to have solved the failing test cases in my Debian testing VM. @tillea, please let me know if it worked or not.

I applied the patch but it does not solve all issues:

...
197: Non-symmetric ARPACK solver (igraph_arpack_rnsolve): FAILED (arpack.at:66)

Bipartite graphs

...

## ------------- ##
## Test results. ##
## ------------- ##

ERROR: 219 tests were run,
1 failed unexpectedly.
13 tests were skipped.
## -------------------------- ##
## testsuite.log was created. ##
## -------------------------- ##

Please send `tests/testsuite.log' and all information you think might help:

   To: <csardi.gabor@gmail.com>
   Subject: [igraph 0.7.1] testsuite: 197 failed

You may investigate any problem if you feel able to do so, in which
case the test suite provides a good starting point.  Its output may
be found below `tests/testsuite.dir'.


Please let me know if I can provide more information, Andreas.

**Comment by ntamas** [comment]
Please also apply the changes outlined in [this comment](https://github.com/igraph/igraph/issues/1107#issuecomment-450881345). This is already in upstream but was accidentally left out from one of your earlier backporting attempts.

**Comment by tillea** [comment]
Works.  Thanks a lot for your support.  Andreas.
