### ISSUE TITLE
Suggestion: "good first issue" labels

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1108]
This is a suggestion to start using the `good first issue` and `help wanted` labels recommended by GitHub.  https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

Additionally, people could note whether they are willing to provide guidance/mentoring on certain issues.  This can be on the mathematical or technical fronts.  Personally, I have more project ideas than what I have time to implement.

The ultimate goal is to reduce the barrier to contributing to igraph and to attract more contributors.

**Comment by ntamas** [comment]
I have tidied up the labels a bit and added a few of these labels here and there. I will keep on using these for new issues.
