### ISSUE TITLE
igraph_lapack_dsyevr causing memory errors

### ISSUE THREAD

**Issue by carissableker** [igraph/igraph#1109]
This is in C++ 

When using `igraph_lapack_dsyevr` within a for loop, I get one or more of the following errors:
* `Bus error`
* `Segmentation fault`
* The entries of another vector in the program are mysterious changed
* `Error: corrupted size vs. prev_size`

Using valgrind and gdb, we managed to pinpoint the error to the function appearing to be claiming memory illegally. 
I have attached an attempt at a MWE and two of the graphs it fails at. 

Note: 
* When abstol in `igraph_lapack_dsyevr` is 0.0 it crashes on graph0_0.8.ncol
* When abstol is 1e-10 it crashes on graph0_0.5.ncol

[issueMWE.zip](https://github.com/igraph/igraph/files/2193957/issueMWE.zip)

- [X] This issue is for the C core of igraph.
- [X] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
Thanks for the detailed bug report! I have managed to reproduce it but I have yet to investigate where the bug is.

For the record, the errors from `valgrind` are as follows:

```
==14120== Invalid write of size 8
==14120==    at 0x525FCC1: igraphdstebz_ (dstebz.c:725)
==14120==    by 0x525B8B8: igraphdsyevr_ (dsyevr.c:688)
==14120==    by 0x50DB146: igraph_lapack_dsyevr (lapack.c:421)
==14120==    by 0x4015E3: main (mwe.cpp:68)
==14120==  Address 0x91bc5c0 is 0 bytes after a block of size 16 alloc'd
==14120==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14120==    by 0x4FAA870: igraph_vector_init (vector.pmt:128)
==14120==    by 0x40151C: main (mwe.cpp:57)
==14120==
==14120== Invalid read of size 8
==14120==    at 0x525FDE1: igraphdstebz_ (dstebz.c:749)
==14120==    by 0x525B8B8: igraphdsyevr_ (dsyevr.c:688)
==14120==    by 0x50DB146: igraph_lapack_dsyevr (lapack.c:421)
==14120==    by 0x4015E3: main (mwe.cpp:68)
==14120==  Address 0x91bc5c0 is 0 bytes after a block of size 16 alloc'd
==14120==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14120==    by 0x4FAA870: igraph_vector_init (vector.pmt:128)
==14120==    by 0x40151C: main (mwe.cpp:57)
==14120==
```
