### ISSUE TITLE
Infomap algorithm with java interface 

### ISSUE THREAD

**Issue by MohamedAmineOuali** [igraph/igraph#1111]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [ ] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Hello,
I am interesting in the infomap implementation containing in igraph project. I want to use this implementation in a java project. So I want to know if I can use it with the current java wrapper (interface)? And if it is possible how can I do it?

Thank you very much

**Comment by ntamas** [comment]
No, you cannot use the Infomap implementation from Java. In fact, there isn't really any Java interface for igraph as far as I know. I have started one a long long time ago but it was never really finished.

**Comment by MohamedAmineOuali** [comment]
Is there any alternative?  If there aren't can I use swing?

Thank you for your time

**Comment by ntamas** [comment]
Sorry, I have no idea. You need to search for an implementation in Java yourself.
