### ISSUE TITLE
Test #191 fails.

### ISSUE THREAD

**Issue by tabac** [igraph/igraph#1112]
Hi,

I compiled `igraph` after configuring with `--enable-profiling --enable-asan --enable-debug` and got an error for test `#191`. The message was `LeakSanitizer: detected memory leaks`, I attach the log [here](https://github.com/igraph/igraph/files/2315001/testsuite.log).

I looked into it a bit, what happens is that the `best_clique` which is allocated [here](https://github.com/igraph/igraph/blob/master/src/cliquer/cliquer.c#L1608), it is leaked. This takes place in [store_clique](https://github.com/igraph/igraph/blob/master/src/cliquer/cliquer.c#L951). It happens because although `opts->clique_list` contains one element `clique_list_count` is set to `0` [here](https://github.com/igraph/igraph/blob/master/src/cliquer/cliquer.c#L595) instead of `1`. I made that change and the test passed but I think that way we're writing out of bounds since we haven't allocated memory for `opts->clique_list`.

It's confusing to me that we have a `clique_options.clique_list` but only store one clique in it, we don't use it as a list. If it is not a list what's the meaning of `clique_list_count` and `clique_list_length`?

Also, I am not sure if that's the only change we should do. In the same file (`cliquer.c`) there are other places that the same change applies, namely [here](https://github.com/igraph/igraph/blob/master/src/cliquer/cliquer.c#L1183) and [here](https://github.com/igraph/igraph/blob/master/src/cliquer/cliquer.c#L1491).

I am happy to do any changes required but I would like to discuss it first with someone more familiar with this part of the codebase.

Best,
Tasos.

**Comment by szhorvat** [comment]
This part of the code actually belongs to [the Cliquer library](https://users.aalto.fi/~pat/cliquer.html) (which is included in igraph).

**Comment by szhorvat** [comment]
I was the one who integrated it into igraph, but I am also not very familiar with its inner workings. It might be a good idea to contact the original author.

**Comment by tabac** [comment]
I can contact the original author. Does the test pass in your case or is it just my build?

Also, I see that in `.travis.yml` we just do `./configure`, should I add `--enable-asan`?

**Comment by ntamas** [comment]
Not sure if AddressSanitizer is enabled/available in the Travis CI environment. If it is, then it would be a good idea to do so _after we have fixed the current AddressSanitizer issues_ in the codebase.

**Comment by ntamas** [comment]
Also, `store_clique()` increases `clique_list_count` by one at the very beginning, so the initial value of `clique_list_count` should be zero IMHO. I think that the real problem is that we forget to free the clique explicitly after we are done dealing with it, so it stays in memory.

**Comment by ntamas** [comment]
So, after digging into the code, I think that the primary source of the problem is the `localopts.clique_list = &best_clique;` line as stated above; I think that the original author somehow tried to enforce that the best clique found during the search should be written into the `best_clique` variable directly. However, the problem is that `store_clique()` calls `set_duplicate()`, which ignores the pointer previously pre-filled into `localopts.clique_list` and allocates a new set.

I will file a patch for this soon.

**Comment by ntamas** [comment]
Fixed in 675f157
