### ISSUE TITLE
[Feature Request] Support for hypergraphs

### ISSUE THREAD

**Issue by jldevezas** [igraph/igraph#1115]
Given it is incredibly hard to find a good library for the analysis and visualization of hypergraphs, it would be amazing if igraph also provided support for this data structure. 

Hypergraphs are a generalization of graphs, where edges, or rather hyperedges, can contain an arbitrary number of nodes (it can be a single node or ten nodes). Hypergraphs can be directed or undirected. For directed hypergraphs you use a set of nodes to represent a hyperedge and for undirected hypergraphs you use a tail set for source nodes and a head set for target nodes (tail and head as in an arrow, not a list; so [arrow]head is the target, just like in a regular directed graph with the arrow).

Many algorithms can be shared from graph theory to hypergraph theory and igraph already provides community plotting, which should be easy to adapt to hypergraphs for the plotting of hyperedges.

**Comment by szhorvat** [comment]
Hi José,

I am not meaning to sound negative, but I think that you are severely underestimating the work needed to create a useful hypergraph library, and also severely overestimating of how much of the existing igraph code base could be re-used for such a task (probably almost none of it).

**Comment by jldevezas** [comment]
I was simply trying to motivate the implementation, but I am quite aware of the associated effort. Still, I think this might benefit the community and it's also an opportunity for igraph to expand. Given this library is rather stable right now, I'd say there's room for some risk. Logically, if you already know an algorithm from graph theory, you can easily reimplement it for a hypergraph. In practice, however, the code wouldn't be easily reusable (or sometimes not at all). I agree, there's a lot of work there, but igraph has, over time, distinguished itself because of the number of community detection algorithms it implements. Why not take it a step further and keep exploring non-dyadic relationship analysis?

I would say it's for the community to decide, but I also know how latent the concept of a hypergraph generically is and, without actually using this data structure, most of us wouldn't know what types of insights we could extract using such an approach.

Well, I leave the suggestion. :-) 

Best regards!

**Comment by gaborcsardi** [comment]
The igraph data type  cannot support hypergraphs, so a new data type would be needed. You might  as well create a new library.

**Comment by colltoaction** [comment]
I would like to contribute some up-to-date information about popular hypergraph libraries:
* [HypergraphX](https://github.com/HGX-Team/hypergraphx)
* [HyperNetX](https://github.com/pnnl/HyperNetX)
* [XGI](https://github.com/xgi-org/xgi)
