### ISSUE TITLE
Missing VERSION file

### ISSUE THREAD

**Issue by frederik-h** [igraph/igraph#1118]
Running autoconf in a freshly cloned igraph repository fails due to a missing VERSION file
which is used in AC_INIT in configure.ac. The file is also listed in .gitignore.
Is this intended? 

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by gaborcsardi** [comment]
You are supposed to run `./bootstrap.sh` first.

**Comment by frederik-h** [comment]
@gaborcsardi Thanks :+1:
