### ISSUE TITLE
PageRank calculation with Arnoldi method does not work on 3-vertex graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1119]
Since the recent ARPACK-related changes, `igraph_pagerank` fails on graphs with 3 vertices.

The error message is:

> Error at arpack.c:1234 :ARPACK error, NCV must be greater than NEV and less than or equal to N (and for the non-symmetric solver NCV-NEV >=2 must also hold)

Here is a minimal example:

```c
#include <igraph.h>

int main() {
    igraph_t graph;
    igraph_vector_t result;
    double value;
    igraph_arpack_options_t arpack_options;

    igraph_small(&graph, 3, 0 /* directed=false */, 0,1, 1,2, -1);
    igraph_vector_init(&result, 0);

    igraph_arpack_options_init(&arpack_options);

    igraph_pagerank(
            &graph, IGRAPH_PAGERANK_ALGO_ARPACK,
            &result, &value,
            igraph_vss_all(), 0 /* directed=false */,
            0.85 /* damping */,
            NULL /* no weights */,
            &arpack_options);

    igraph_vector_destroy(&result);
    igraph_destroy(&graph);

    return 0;
}
```

**Comment by szhorvat** [comment]
In this case `igraph_i_arpack_auto_ncv` ends up setting NCV=2, and NEV is 1.

It sets NCV to 2 in this section:

```c
  /* ...but at most n-1 */
  if (options->ncv > options->n - 1) {
    options->ncv = options->n - 1;
  }
```

I am not very familiar with this method (forgot the details since my NR course) and do not know why it is limited to N-1. The error message, which seems to come fro ARPACK, states that the upper limit is N.  If I change the upper limit to N in `igraph_i_arpack_auto_ncv`, then the problem seems to go away and none of my other tests fail. However, I do not know if anything else breaks.

**Comment by ntamas** [comment]
`igraph_i_arpack_auto_ncv()` is a result of a trial-and-error process with the older ARPACK implementation after having investigated how Octave sets the value of NCV automatically. It might be the case that the old version does not work nicely any more with the newer ARPACK. If changing the upper limit to N fixes things for you, feel free to send a pull request and I'll merge it.

(I am in Taiwan at the moment so there might be delays, though).
