### ISSUE TITLE
Can not insatll igraph on R

### ISSUE THREAD

**Issue by Lily-WL** [igraph/igraph#1131]
Dear develpers,

The igraph can not be installed on my server because the error:
libicui18n.so.58: cannot open shared object file: No such file or directory

My R is installed by "yum" on a Centos OS.

I found the problem may be the reason of Anaconda, and I can find the file of "libicui18n.so.56" from its library such as ".../anaconda2/lib/libicui18n.so.58"

Can you help to fix the problems?

**Comment by Lily-WL** [comment]
I tried to solve it with a command "conda install conda-forge icu=58.1".

But now a new error came.

"libiconv.so.2: cannot open shared object file: No such file or directory" 
I am sure the file exits:
_# `find -name libiconv.so.2`
./usr/local/lib/libiconv.so.2
./opt/anaconda2/pkgs/libiconv-1.15-h470a237_3/lib/libiconv.so.2
./opt/anaconda2/lib/libiconv.so.2_

**Comment by ntamas** [comment]
I don't understand; you are saying that you try to install igraph on _R_. What does it have to do with Anaconda _Python_ then? Do you want to install igraph in R or in Python?

**Comment by Lily-WL** [comment]
Thank you for your reply.
I am the new for Linux. I found that some needed library file can not find after the installation of Anaconda. So I worried the errors of "igraph" installation is also same reason. The first error of missed file "libicui18n.so.58"  was corrected by the command `"conda install conda-forge icu=58.1"`,but the second error of file "libiconv.so.2" can not be corrected.

**Comment by ntamas** [comment]
The list of installed libraries for Anaconda Python should have nothing to with R; if there is a crossplay between them, then something is seriously wrong on your machine. Anyway, how did you attempt to install igraph in R?

(I'm inclined to move this discussion to igraph/rigraph as most likely this has nothing to do with the C core, but I'm not sure yet).

**Comment by Lily-WL** [comment]
install.packages("igraph")

**Comment by ntamas** [comment]
Discussion continues in igraph/rigraph#302
