### ISSUE TITLE
Appveyor builds fail

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1133]
The Appveyor build currently fails for reasons related to anaconda environment. It would be nice to fix this to get rid of all the red crosses on the PRs.

![image](https://user-images.githubusercontent.com/1212871/48621220-238a3000-e9a3-11e8-86bd-87114a23ba70.png)

Also pinging @jankatins

**Comment by ntamas** [comment]
It seems like the problems are only present if the environment matrix prescribes `PYTHON_VERSION=3.4` or `PYTHON_VERSION=NONE`. What if we drop these and just test on Python 3.6 and 3.7?

I can't find which ones are the supported Python versions in Appveyor -- does anyone know where to look for this info?

**Comment by ntamas** [comment]
For future reference, [this is the list of software installed by default in the build environment](https://www.appveyor.com/docs/windows-images-software/).

**Comment by szhorvat** [comment]
Did you fix this or did it fix itself?

**Comment by ntamas** [comment]
I have changed something in the build file but then I got carried away something else and forgot to come back and test whether the build went fine or not. Looks like I managed to fix it :)
