### ISSUE TITLE
Why does igraph_destroy return an int?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1142]
It appears that almost all `_destroy` functions are `void` in igraph, with the exception of `igraph_destroy`.

Is there a reason for `igraph_destroy` returning an `int`? As far as I can tell, it will never return anything but `0`.

The current implementation is

```
int igraph_destroy(igraph_t *graph) {

  IGRAPH_I_ATTRIBUTE_DESTROY(graph);

  igraph_vector_destroy(&graph->from);
  igraph_vector_destroy(&graph->to);
  igraph_vector_destroy(&graph->oi);
  igraph_vector_destroy(&graph->ii);
  igraph_vector_destroy(&graph->os);
  igraph_vector_destroy(&graph->is);
  
  return 0;
}
```

where 

```
#define IGRAPH_I_ATTRIBUTE_DESTROY(graph) \
        do {if ((graph)->attr) igraph_i_attribute_destroy(graph);} while(0)
```

I bumped into this minor (easy to work around!) issue when I was wrapping some `vector_ptr`s with a C++ class template parametrized on the element type and the element type's destructor.

It is only `igraph_t` that does not fit the simplest variant of the template because of its differing return type.

Since it makes sense for destructors not to be able to fail, we could change it to `void`. It would also reduce confusion.

On the other hand, there's little harm in leaving it an `int`, and the change would certainly break some code that attempts to check the return value.

**Comment by ntamas** [comment]
I think that destructors (i.e. anything of the form `igraph_*_destroy`) should not return anything at all (there should be no way for destructors to fail), so I think it's safe to change this to return void.  Can you send a PR?
