### ISSUE TITLE
cited_type_game does not check its arguments

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1145]
`igraph_cited_type_game` does not check that its arguments are valid.

Unless I misunderstood something, the following fixes are needed:

 - Check that the length of `types` is `nodes`
 - Check if the node count is zero and if yes, return an empty graph right away (do not index into `types`!)
 - Before indexing into `prefs`, check that the index is within the bounds (`prefs` may not be long enough to have values for all types, or a type value may be invalid).
 - Before using any values from `prefs`, check that it is not negative
 - Before `vector_binsearch` check that `cumsum` is not all-zero (i.e. that `sum` is not zero)

**Comment by ntamas** [comment]
The above is probably correct. Note that similar problems are probably also present in `igraph_citing_cited_type_game()`.

**Comment by szhorvat** [comment]
Yes, they are (I checked since opening this issue).

**Comment by iosonofabio** [comment]
I think I have added all these fixes to both functions, anyone can have a look?

**Comment by ntamas** [comment]
Guess I can close this as the PR is merged, right? Please reopen if needed.
