### ISSUE TITLE
[Windows] compilation obstacles to be solved

### ISSUE THREAD

**Issue by jannick0** [igraph/igraph#1161]
I encountered the following compilation obstacles while trying to compile `igraph` with `msys2-mingw64`'s gcc (current version is 8.3.0). After the amendments suggested below the package can be successfully compiled.

1. `USE_CLOCK` in `src/f2c/dtime_.c`:
* On Windows `sys/times.h` does not exist.
* `USE_CLOCK` should be set, on the command line or - preferably from my point of view - in `dtime_.c` in the following lines:
https://github.com/igraph/igraph/blob/b4d8eb64e66c9a789db4ea9b556520fee0868eda/src/f2c/dtime_.c#L3-L6 like so:
~~~c
#if defined MSDOS || defined _WIN32
~~~

2. same for `USE_CLOCK` in  `src/f2c/etime_.c`
3. `pause()` in `src/f2c/s_paus.c`:
* `pause` is not defined on Windows.
* after a quick research, `system("pause")` could be used instead for Windows (`_WIN32`) if anything at all.
* I am not sure, but  `s_paus` appears not to be called by any other procedure of the entire package, so probably not such a big deal.

Happy to submit pull requests. Just let me know which solution of the above - or any other -  you prefer.

Many thanks.

**Comment by szhorvat** [comment]
Here are my notes on compiling igraph with msys2-mingw64 _without_ modification. (In fact, I compiled it half an hour ago).

https://github.com/szhorvat/IGraphM/blob/master/Development.md#windows

Something did not note there is that I needed to delete/rename `libgmp.la` before it agreed to link to GMP. I do not know why this is, or what the exact purpose of the `.la` files are.

**Comment by szhorvat** [comment]
To sum up, I do not think that any changes need to be made to igraph in order to make it compilable with MinGW.

**Comment by jannick0** [comment]
Understood - I was not sure that Windows could easily share the `MSDOS` branch.

To your nice compilation write-up: typing `pacboy -S gmp:x` in the `msys2` shell installs the latest gmp package know to the MSYS2/MINGW64 repository.
