### ISSUE TITLE
[Windows] Test 88 fails (b/c permutation of output lines only)

### ISSUE THREAD

**Issue by jannick0** [igraph/igraph#1162]
On Windows (package successfully compiled with `msys2-mingw64`'s gcc) all current tests pass (or are skipped) except  Test 88. Issue: Permutation of the result rows.

Potentially related: #886. 

Side remark: I had to redefine in `testsuite` the variable `at_diff` as `diff -u --strip-trailing-cr` , since the output files produced by the test progs have `CR LF` line endings while the expected output files have `LF` on my system.  Otherwise all tests which compare files would have failed.

Test log extract:
~~~
## --------------------------------------------- ##
## igraph 0.8.0-pre+b4d8eb64 test suite: igraph. ##
## --------------------------------------------- ##

testsuite: command line was:
  $ testsuite 

## ---------- ##
## ChangeLog. ##
## ---------- ##


## --------- ##
## Platform. ##
## --------- ##

uname -m = x86_64
uname -s = MINGW64_NT-10.0
uname -v = 2018-11-26 09:22

[...]

#                             -*- compilation -*-
88. structural_properties.at:82: testing Get all weighted shortest paths (Dijkstra):  ...
../../tests/structural_properties.at:84: ${CC} ${CFLAGS} ${abs_top_srcdir}/examples/simple/igraph_get_all_shortest_paths_dijkstra.c -I${abs_top_srcdir}/include -I${abs_top_builddir}/include -L${abs_top_builddir}/src/.libs -ligraph -lm  -o itest
../../tests/structural_properties.at:84: cat ${abs_top_srcdir}/examples/'simple/igraph_get_all_shortest_paths_dijkstra.out' | sed "s/@VERSION@/$(cat ${abs_top_srcdir}/VERSION)/g" > expout
../../tests/structural_properties.at:84: 
../../tests/structural_properties.at:84: DYLD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${DYLD_LIBRARY_PATH+:$DYLD_LIBRARY_PATH} LD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH} ./itest
--- expout	2019-04-15 18:11:53.632313600 +0200
+++ /c/myDevel/svn/igraph/build-msys2-mingw64/tests/testsuite.dir/at-groups/88/stdout	2019-04-15 18:11:54.434406500 +0200
@@ -12,8 +12,8 @@
 0 9 8 7 6 5
 0 1
 0 1 2
-0 3
 0 1 2 3
+0 3
 0 1 4
 0 1 5
 4 4 12
88. structural_properties.at:82: 88. Get all weighted shortest paths (Dijkstra):  (structural_properties.at:82): FAILED (structural_properties.at:84)
~~~

**Comment by szhorvat** [comment]
This is not a true failure, just an issue with how infinities are printed (which could be fixed).

I reported it here: https://github.com/igraph/igraph/issues/886

As for the CR/LF issue: git should automatically convert these when you check out the sources (the git in msys does this without additional configuration).

**Comment by szhorvat** [comment]
Please ignore my earlier incorrect (and now deleted) comment.

I can reproduce this failure. What is strange is that the result seems correct, but the ordering has changed. This only happens with MinGW/Windows, not on Mac/Linux.

Regarding CR/LF: I did not have an issue with this. Perhaps on my system the line endings were auto-converted by git upon checkout? I used the git from msys2.

**Comment by jannick0** [comment]
> Please ignore my earlier incorrect (and now deleted) comment.

No worries. :)
 
> I can reproduce this failure. What is strange is that the result seems correct, but the ordering has changed. This only happens with MinGW/Windows, not on Mac/Linux.

Exactly - I tried to describe this as line permutation. I was under the impression that the algorithm should return identical results given the same input.
Or is the result unique up to line permutations only? If so then this should be implemented I believe, shouldn't it?

> Regarding CR/LF: I did not have an issue with this. Perhaps on my system the line endings were auto-converted by git upon checkout? I used the git from msys2.

In the past this got me into hot water with UNIX packages: scripts did not work any more and the packages were completely useless. Since then I keep the EOLs as they are in the repository.  Maybe one day there will be an extension to `autotest`'s  `AT_CHECK` which will easily swallow additional `diff` options.   This would certainly multiply test possiblities.

**Comment by szhorvat** [comment]
> Or is the result unique up to line permutations only?

Not quite.  The paths are supposed to be sorted by the target vertex.  They are, but there are multiple paths to the same target vertex. There is a theoretical freedom in how these are ordered.

Still, it seemed weird that the result would differ from one system to the next (I tried GCC 8.3 on OS X and I get the "expected" result, not the MinGW result).

Looking at the code, the paths are explicitly sorted at the end of the function:

https://github.com/igraph/igraph/blob/master/src/structural_properties.c#L5186

Digging down, this function uses the C standard library `qsort`.  That function likely has a different implementation on different systems, leading to this discrepancy.

This now gives me some peace of mind that `igraph_get_all_shortest_paths_dijkstra` is not broken. :-)

The fix could be to sort the result once more in the test program, now considering the entire path for sorting instead of just the target vertex.

Then it would be good to add yet another test that verifies that the raw result is already sorted according to the target vertex.

**Comment by jannick0** [comment]
> Digging down, this function uses the C standard library `qsort`. That function likely has a different implementation on different systems, leading to this discrepancy.

Yes - `qsort`'s behaviour with regards to equivalent elements is undefined.
 
> Then it would be good to add yet another test that verifies that the raw result is already sorted according to the target vertex.

Here a quick awk script without any bells and whistles that could do this job.  It expects row blocks to be delimited by empty lines and that each row block is entirely part of one input file only.  This would require  in the raw output to insert separating empty lines between blocks for different graphs.
~~~awk
BEGIN{
	RS = "\r?\n"
	e_undefined = -1
}

FNR == 1 {
	e_prev = e_undefined
}

# an empty line resets the previous trailing element
/^$/ {
	e_prev = e_undefined
	next
}

{
	e = $(NF) + 0
	if ( e_prev != e_undefined && e < e_prev )
	{
		print FILENAME ":" FNR ": row violates ordering of rows by last element"
		exit(99)
	}
	e_prev = e
}
~~~

**Comment by ntamas** [comment]
Test case has been updated to sort the result of the shortest path calculation in a deterministic manner. I think this should do the trick (apart from the CRLF problem - I don't think I have a good solution for that). Let me know if the test still fails for you.
