### ISSUE TITLE
VF2 wrong result for graph with self-loop

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1166]
VF2 returns a wrong result for a graph with a self-loop.

```
> patt<-make_graph(c(1,1),dir=F)
> targ<-make_graph(c(1,2, 2,3), dir=F)
> subgraph_isomorphic(patt, targ, "vf2")
[1] TRUE
```

Need to clarify if VF2 is meant to support such graphs at all, and if not, add a check (just like for multigraphs).

Possible workaround: colour each node based on the number of self-loops it has and use the coloured graph isomorphism facilities.

**Comment by szhorvat** [comment]
`igraph_subisomorphic` is currently just a wrapper around `igraph_subisomorphic_vf2`, thus it is also affected.

This is a more serious issue, and should be fixed.  A fix along the lines of PR #1168 should be possible.

**Comment by ntamas** [comment]
Actually, I'm not sure how much effort one should invest in VF2 in general; we could just put a warning in front of the function call if the input graph has multiple edges or self-loops. The old VF2 site seems to propose [VF3](https://mivia.unisa.it/datasets/graph-database/vf3-library/) now, there's also [VF2++](https://web.cs.elte.hu/egres/tr/egres-18-03.pdf) and there could be other new algorithms out there that would serve the purpose better.

**Comment by szhorvat** [comment]
Closing, as it is now documented that VF2 only supports simple graphs. General non-simple-graph isomorphism should go in another issue.
