### ISSUE TITLE
Conflict with <version> header

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1172]
C++20 will have the `<version>` header.

https://en.cppreference.com/w/cpp/header/version

igraph generates a `VERSION` file (uppercase) which happens to be on the include path (it's in the same directory as the generated `config.h`).

This will conflict with the system header when using case insensitive file systems. I found this out while trying to compile with clang 8.0 on macOS.

This is going to become a big pain both on macOS and MinGW as soon as compilers start to implement C++20 support.  It should be fixed in igraph itself if possible, as it would be very user-unfriendly to require a case sensitive file system to compile.

I don't know where exactly this `VERSION` file comes from though: it is specific to igraph or an Autotools thing?

**Comment by szhorvat** [comment]
It is created by the `bootstrap.sh` script and `./configure`, as well as building, works fine if I delete it.

Maybe it could simply be removed from the bootstrap script?

I won't touch this though because I have no Autotools expertise.

**Comment by ntamas** [comment]
The file contains the git-derived version number of the package. I think it is baked into released tarballs. `configure.ac` needs this file in the first line when it invokes `AC_INIT` to figure out what the version number of the package should be. So, it is needed, but it is safe to rename it to, say `IGRAPH_VERSION` or `.version` or something similar as long as `configure.ac` is updated accordingly. I have no objections against renaming it.

**Comment by szhorvat** [comment]
@ntamas Could you please make the change?

Personally, I'd favour a non-hidden file, so I'd go with `IGRAPH_VERSION` instead of `.version`.
