### ISSUE TITLE
igraph_bridges and multigraphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1180]
`igraph_bridges` appears to ignore multi-edges.  Verify that this is the only limitation with multigraphs, and document it (or generalize the function).

**Comment by YasirKusay** [comment]
This is a very interesting issue that I found and decided to run a small program to investigate. I created an undirected graph: 0=1-2 (i.e, two edges between 0 and 1, indexed as edges 0 and 1 respectively and 1 edge between 1 and 2, indexed as edge 2). When I ran the program, I assumed that the multi-edge edges will not be considered as a bridge and that igraph_bridges will only return edge id 2 but surprisingly, edge id 1 and 2 were returned after using igraph_bridges. I removed one of the edges from 0-1 and igraph_bridges  returned correctly (edge id 1 and 2). Is this what the implementation of igraph_bridges intended?

**Comment by ntamas** [comment]
As stated above in the comment of @szhorvat, `igraph_bridges` appears to ignore multi-edges in the current implementation. My conjecture is that essentially it works with _vertex pairs_ instead, so basically for each vertex pair it investigates whether disconnecting the _vertex pair_ would disconnect the graph. If it does, then it returns _all_ edges between that vertex pair as bridges. So, in some sense it may have been better for `igraph_bridges` to return vertex pairs instead of edge indices. On the other hand, most people don't work with multi-edges and this way we spare them an extra edge index lookup in the result vector.

We are open to suggestions about how to generalize `igraph_bridges` in the next release so it works nicely with multigraphs.

**Comment by szhorvat** [comment]
When I implemented `igraph_bridges`, I followed the guide here: https://www.geeksforgeeks.org/bridge-in-a-graph/  I simply forgot about multi-edges, so the code wasn't originally *meant* to handle them one way or another. 

If you'd like to look into this, perhaps the link above will be helpful

**Comment by YasirKusay** [comment]
From my observation of the function, if there is a multi-edge, it is treated as a single edge and if it is a bridge, then the final edge from the multi-edge group is returned. Personally, I think the user should have a choice (perhaps including an extra function parameter) to treat multi-edges as just one edge, such that removing all the edges in that multi-edge group may disconnect the graph and therefore all edges are considered to be a bridge, and returned to the user. In my opinion, that does not require a complete overhaul of how the function is implemented, but rather some minor checks (check to see if the edge pair are multiedges, etc).  If you agree, I am more than happy to give it a go.

**Comment by szhorvat** [comment]
It seems to me that this would bundle the solutions to two conceptually different problems:

 - One is to merge multi-edges into simple ones and retain a mapping between the edges of the original and the simplified graph. I believe we don't yet have such a function, and it might not be a bad idea to have one (we have simplification functions but the ones I am aware of do not retain an edge mapping between the original and simplified graphs).

 - The other is to find bridges in a simple graph.

I would prefer to keep these separate.

**Comment by iosonofabio** [comment]
I'm of the same opinion. Having a function that find bridges in simple graphs and throws an error if the graph is multiedged would be clear and useful. That would cover most users and enable complex code to be compartimentalized in a multigraph-specific function.

**Comment by iosonofabio** [comment]
Maybe we could ask Yasir to try and take a stab at the simple graph-only function implementation?

**Comment by YasirKusay** [comment]
> Maybe we could ask Yasir to try and take a stab at the simple graph-only function implementation?

I would be happy to do that. So from what I understand all I am doing is that I am checking if the graph has multi edges and raising an error if it does. In the event that happens, I call graph_simplify and treat the graph as a simple graph right?

**Comment by ntamas** [comment]
> Having a function that find bridges in simple graphs and throws an error if the graph is multiedged would be clear and useful. 

I agree. And then we could have another function that converts a multi-edged graph into a simple graph and provides a mapping that allows the user to go back and forth between the edge indices.

**Comment by szhorvat** [comment]
To be clear, the function does work fine for simple undirected graphs.

It does make sense to add a check at the beginning for multiple edges.

Two things to keep in mind about this:

 - This is not a simple matter of adding `igraph_has_multiple`. The tricky point is that this function, like many other, ignores edge directions. Thus the graph `1->2, 2->1` is a "simple graph" (`has_multiple` returns false) but when treated as undirected, it is effectively a multigraph.  I suspect that there are several other functions which slip on the same issue—at one point we should do an audit.  Perhaps we need another helper function?

 - I expect a multi-edge check to take O(E) time. (I have not worked with the internals of `igraph_t` before, so I might be wrong.) It is possible that adding the check will cause a noticeable performance hit.

    There is a design question here: Currently, igraph does most input checks in the C core instead of the high-level interfaces. This is, of course, convenient for the high-level interfaces. But it also leads to redundant multigraph checks when a function `f1` calls a function `f2` which calls a function `f3` and all of them do the check. Also, the Mathematica interface converts graphs from Mathematica's data structure to igraph's on the fly and can check if there are multi-edges in O(1) time before the conversion. Thus, for that interface, it's better to do the multigraph check in the high-level interface and save some time.

    We discussed some of this in https://github.com/igraph/igraph/issues/1219  Some ideas were: 1) to cache information about whether the graph is a multigraph, which I would like to have very much, but which I think is hard to implement safely 2) have internal versions of some functions which omit the check (and have the requirements on their input, such as that it must be a simple graph, documented).

**Comment by YasirKusay** [comment]
I guess I can start working on detecting multi-edges in a directed graph, potentially even on a simplify function but for a directed graph and then work on bridge detection for those.

**Comment by iosonofabio** [comment]
I would compartmentalize as much as possible, so:

- change the current function to only work on undirected, simple graphs, throw an error in all other cases (directed and/or `has_multiple`)
- open another issue about a feature request for a `simplify` function (and decide in that thread how to deal with O(1) vs O(n) checks for multiedges

What do you think?

**Comment by YasirKusay** [comment]
I think that would be the most suitable thing to do right now. I can worry about multi-edges later in that case.

**Comment by ntamas** [comment]
> 1) to cache information about whether the graph is a multigraph, which I would like to have very much, but which I think is hard to implement safely

I think that now that 0.8 is out we can probably return to the idea of caching this in `igraph_t`. The first step for doing so would be to validate whether all igraph functions manipulate the graph only through the basic functions provided in `type_indexededgelist.c` (which should be the case as the internal structure is fairly complex so no one should manipulate it directly, apart from the very basic interface in this file). If this is the case, we can add caching and all we need to do is to invalidate the cache when the user mutates the graph in a way that there is even a tiny chance that the info in the cache is invalid.

Newly constructed graphs should start with an "uncached" state so we don't trigger an expensive check until the value is really needed.

**Comment by vtraag** [comment]
> I think that now that 0.8 is out we can probably return to the idea of caching this in `igraph_t`.

Perhaps we can better continue that discussion in #1219?

**Comment by vtraag** [comment]
I wonder if the condition of having multiple edges can simply be checked while executing the algorithm. That way, the impact on runtime complexity should be minimal. I haven't looked at the code though, so perhaps it is not well suited for that.

**Comment by YasirKusay** [comment]
@vtraag I agree that it will minimise runtime complexity, however I also want to implement it independent of any function in case a user wants to check if their directed graph has multi-edges. I would firstly like to implement the function without doing that at runtime, and then when that works, I can check if it has multi-edges on runtime, rather than simply calling a function.

**Comment by vtraag** [comment]
@YasirKusay, yes having such a function is very handy! Perhaps `igraph_has_multiple` can simply be extended for that purpose. My point is that this could be done independently from this particular issue if we can perform the check inside the algorithm (and hence independent from the discussion in #1219).

**Comment by YasirKusay** [comment]
I'll have a crack at that, I really like the current implementation of igraph_bridges, so I will attempt to detect edges on runtime rather than rewriting the whole function (unless there are parts that I must change).

**Comment by YasirKusay** [comment]
Hello, yesterday I managed to come up with a solution that is very simple. The hard part was firstly understanding how the igraph_bridges function works and also how inclists works. I was interested to see if inclists also include multi-edges and they did so I added this set of code in between when you get the value of v and right before you check if v is visited:

    int node_count = 0;
    for (int j = 0; j < nc; j++) {
            long curr_edge = (long) VECTOR(*incedges)[j];
            if (IGRAPH_TO(graph, curr_edge) == v && IGRAPH_FROM(graph, curr_edge) == u) {
                node_count++;
            }
        }
        if (node_count > 1) {
             IGRAPH_WARNING("Function works for undirected graphs only");
        }

This very simple check appears to work for both directed and undirected graphs.

**Comment by YasirKusay** [comment]
I also forgot to add that i checked if a graph had a loop by checking right before the above statement:
if (u == v) // loop detected.
Executing this inside the for loop above will not be efficient for the program.

**Comment by YasirKusay** [comment]
I am just wondering, would you like to add an option in this function (perhaps an extra parameter) to simplify graphs, i.e. remove multi edges and loops and detect bridges from this simplified graph. (I acknowledge that this will mean modifying igraph_bridges, whenever it is called).
This implementation will make a copy of the graph we are using so as not to change the actual graph and then simplify that, detecting bridges within the simplified copy of the graph. 
I have already written an algorithm for this to simplify directed graphs, yet I think integrating it into the code would be more cost efficient than simply calling that function.

If you don't agree with this implementation, the user can also simply call the igraph simplify function and then simply call igraph_bridges.

**Comment by vtraag** [comment]
It is better to separate the two functions. There is no need to let `igraph_bridges` automatically simplify the graph, this should be done by the user. `igraph_bridges` should throw an error if a multigraph is passed as an argument.

**Comment by YasirKusay** [comment]
I agree with that as there is no need to make the function more complex. I will try and finalise the function changes and new functions by tonight.
