### ISSUE TITLE
--enable-asan leads to test failures on Linux / GCC

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1181]
[AddressSanitizer works with GCC as well,](https://github.com/igraph/igraph/issues/1173) in principle. If I try it, all tests fail with 

```
ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```
[According](https://github.com/google/sanitizers/issues/796) to Google, the recommended way to fix this is to compile the executable with `-static-libasan`, which is the default on Linux for clang, but not for gcc.  On macOS, it is _not_ the default with clang, so it is not a good idea to add this switch unconditionally.

While I can confirm that compiling the test executables with `-static-libasan` does work on Linux, I am not sure how best to include this in the build instructions, as I am not familiar with autoconf/automake.

Based on some research, it seems it would be reasonable to make `-static-libasan` the default switch _on Linux only_, if this is easy to do.

P.S. On macOS, AddressSanitizer appears to work fine with the current settings when using MacPorts's GCC 8. The above comments apply to Linux only. I _think_ AddressSanitizer does not support Windows at all, so we do not need to worry about MinGW.

**Comment by ntamas** [comment]
Could it apply only to specific versions of gcc? I was testing things with gcc 7.3.0 on Ubuntu and everything worked just fine. What is your gcc version? (Mine is `gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)`)

**Comment by szhorvat** [comment]
It seems that this will happen on Linux when `/etc/ld.so.preload` is not empty. 

https://github.com/google/sanitizers/issues/679

This happens to be the case on Raspbian.

One way to work around it is to start executables using

```
LD_PRELOAD=/path/tp/correct/libasan.so ./myprog
```

but I do not know how to find out the location of the correct address sanitizer library in general (some systems may have multiple installed).

I would not bother with this for now, but I think it's good to keep the issue open, just in case this starts happening with actually popular Linux distros.

**Comment by szhorvat** [comment]
The easier workaround on Raspbian to run the tests is to add `-static-libasan` to `LDFLAGS` before running `./configure`

**Comment by szhorvat** [comment]
Probably the best way to fix this is to detect the location of libasan on Linux and use `LD_PRELOAD` to run the tests when `--enable-asan`.

Here's how to detect the location.

https://stackoverflow.com/q/48833176/695132

There's no point in fixing this for 0.8 though.

**Comment by yugr** [comment]
> One way to work around it is to start executables using

On newer GCCs you could also `export ASAN_OPTIONS=verify_asan_link_order=0` to suppress the check. But you have to be sure that libraries from /etc/ld.so.preload do not intercept symbols important for Asan e.g. malloc, free, etc., otherwise things will start breaking.

**Comment by szhorvat** [comment]
No longer happens after the cmake transition.
