### ISSUE TITLE
closeness_estimate always gives a warning

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1197]
`closeness_estimate` always displays a warning due to https://github.com/igraph/igraph/commit/b379441d4d55c850502d17016316f1d9f7dc08e7 which fixed #1053 (@ntamas)

![image](https://user-images.githubusercontent.com/1212871/58429615-c506e280-80a6-11e9-961e-c03c0866cb0b.png)

The above session illustrates that whenever the cutoff is less than the diameter (i.e. not all vertices are visited) the warning is issued.

**Comment by szhorvat** [comment]
I suggest fixing this for 0.8 because it would be a regression from 0.7.

**Comment by iosonofabio** [comment]
I'm looking at the code here and I'm wondering what the best approach should be. If a positive cutoff is set, we don't visit all the nodes as "connected neighbors" of the first node, but rather only the nodes within `cutoff`. So we don't really know whether the graph is disconnected or not.

We could add a separate function call at the beginning or end to check whether the graph is connected just for pusposes of warning? Or would that be expensive? Or we could add a runtime flag so the user can choose to pay the runtime cost in exchange of a useful warning?

**Comment by ntamas** [comment]
I'd say let's skip the connectedness check and don't give any warning if `cutoff > 0`. Just document it in the documentation. I wouldn't check connectivity because the cutoffs are typically used on very large graphs where the connectedness check would be prohibitively expensive.

**Comment by ntamas** [comment]
Also, summon @szhorvat - maybe he has a stronger opinion about this than me.

**Comment by szhorvat** [comment]
The original complaint (from me) was #1053, i.e. that the closeness calculation seems unusual, and the in weighted case, unjustified. Let me summarize:

The closeness of a vertex is the inverse of the average distance to all other vertices. The problem is: what do we do when there is no path to another vertex (the graph is not connected)?

The easiest thing to do is to exclude non-reachable vertices from the calculation of the average. Some packages do this.

igraph does something different: it uses the number of vertices `V` as the distance to non-reachable vertices, and includes them in the calculation of the average. The justification is that no distance can be larger than `V-1`.  I am not sure if a better theoretical justification exists (that is not mentioned in the documentation).

Personally, I am not fully convinced that this is a good approach even in the unweighted case. In the weighted case, it doesn't seem to make sense at all as `V` is no longer an upper bound for distances.

When I opened #1053, I did not realize that this choice was probably made for the sake of closeness _estimation_ specifically, where the same problem is encountered even for connected graphs. When limiting the search radius, and undiscovered vertices are considered to be `V` distance away. With this choice, as we increase the search radius, we approach the true mean distance from above. If we excluded undiscovered vertices, we would approach the true mean distance from below.  It is not immediately clear to me if any of these are better.

----

That summary is for the future, so we wouldn't forget about what exactly the issue was.

Finding a good solution to this is not a one-hour task, unfortunately. Since igraph's method of closeness calculation seems to have been inspired by the need to be able to make estimated in large graphs, I suggest that we should do some research and see if there are any papers on closeness estimation, then go from there.

This would be quite a bit of work, so not for 0.8.0.

For 0.8.0 I support @ntamas 's suggestion:

> I'd say let's skip the connectedness check and don't give any warning if cutoff > 0. Just document it in the documentation.

**Comment by szhorvat** [comment]
It would seem reasonable to me to simply do what other packages do and exclude not-yet-reached (or not reachable) vertices from the calculation of the average. But before doing this, it is important to investigate if this leads to worse estimates than the currently implemented approach. This would also take time, which is why I suggest postponing it beyond 0.8.

**Comment by iosonofabio** [comment]
I see, thanks @szhorvat for the info. I agree to postpone actual implementation changes for 0.9.

As of the warning VS no warning, which is the immediate actionable item, it seems like we for sure don't want to calculate connectedness just for that since it could be expensive. I'm fine killing the warning if a `cutoff > 0` is set.

**Comment by vtraag** [comment]
Perhaps best to reopen #1053 then and assign it to 0.9.0. For now, I would suggest we can simply not issue a warning if `cutoff > 0` and close this issue.

**Comment by ntamas** [comment]
Okay, go ahead then!
