### ISSUE TITLE
Re-format all source files for consistency

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1202]
In the chatroom, we talked about re-formatting all source files for consistency.

Comments from @ntamas:

> Actually, I'd be in favour of picking a standard C coding style and then reformatting the entire library (except sources "borrowed" from third-party libs) to a consistent style.

> How about "spaces only, one indentation level is two spaces"? I think this is the closest to what we have now.

> Maybe we should also put an appropriate [EditorConfig](https://editorconfig.org/) file into the root folder so everyone knows what the rules are.

> And make sure to update the vim modelines in the source files

This issue is to agree on a standard before implementing the change.

Here's a more complete proposal based on the above:

 - Indent width of 2, only spaces (no tabs).
 - No trailing whitespace
 - UTF-8 (for comments and docstrings)
 - Sources borrowed from other projects (such as Bliss) should not be changed so that it will be easier to update them when needed.

The topmost `.editorconfig` file would look like this:

```
# https://EditorConfig.org

root = true

[*]

charset = utf-8
insert_final_newline = true

[*.{h,hh,c,cpp,cc,pmt}]

indent_style = space
indent_size = 2

trim_trailing_whitespace = true
```

Vim modeline:

    /* vim:set sts=2 sw=2 et: */

List of directories with borrowed sources that should not be affected (and may need their own settings in `.editorconfig`):

 - `AMD`, `bliss`, `CHOLMOD`, `cliquer`, `cs`, `COLAMD`, `f2c`, `lapack`, `plfit`, `prpack`, `SuiteSparse_config`

All of the above indent with 4 spaces, not 2.

List of sources where it's unclear if they are still in their pristine borrowed state (they are in the `src` directory):

 - `dlr*.cpp`, `gengraph*.cpp`, `infomap*.cc`, `walktrap*.cpp`

These mostly use 2 spaces, but there are inconsistencies. I may have missed some files here.

**Comment by szhorvat** [comment]
Personally, I find 4 spaces more readable for C code than 2 spaces, but I do not have strong feelings about it. The priority is to choose a standard and format the files. Then pull requests will also have fewer accidental changes (such as tab/space conversions or trailing newline removals showing up in the diffs). One thing to note that it seems that _all_ borrowed sources that are in a pristine enough form to warrant not touching them already use 4 spaces.

**Comment by iosonofabio** [comment]
Although I like 2 spaces by now, 4 is cleaner for newer coders. 4 spaces is also Python's standard of course. We might want to keep in line with that to simplify future contributors with that kind of background.

**Comment by ntamas** [comment]
Four spaces it is then! :)

**Comment by ntamas** [comment]
As discussed on Discourse, we'll do this after the feature freeze on the 19th.

**Comment by ntamas** [comment]
I have started implementing this with `astyle`; @vtraag @szhorvat please take a look at the most recent commit where I reformatted the `examples/` folder only. If you spot something that you don't like, please propose alternate settings in `.astylerc`, otherwise I'll proceed with the reformatting in the next few days with `include/` and `src/`, excluding vendored sources.

**Comment by vtraag** [comment]
Thanks! Generally it seems OK to me.

There are some minor alignment issues it seems. For example:
https://github.com/igraph/igraph/blob/fc15b8b4da892faf92bed12fa88d44c1f491e96d/examples/simple/biguint_betweenness.c#L92-L98

https://github.com/igraph/igraph/blob/fc15b8b4da892faf92bed12fa88d44c1f491e96d/examples/simple/biguint_betweenness.c#L186-L187

Perhaps `astyle` doesn't do this alignment at all, it simply is a result of the tab-expansion?

The `astyle.rc` should probably be accompanied by an [`.editorconfig`](https://editorconfig.org/) file that is consistent with it?

**Comment by szhorvat** [comment]
@ntamas Before you go ahead for the full codebase, please take a look at these locations and make sure their readability does not suffer:

https://github.com/igraph/igraph/blob/fc15b8b4da892faf92bed12fa88d44c1f491e96d/src/random.c#L229

https://github.com/igraph/igraph/blob/fc15b8b4da892faf92bed12fa88d44c1f491e96d/src/igraph_error.c#L80

https://github.com/igraph/igraph/blob/fc15b8b4da892faf92bed12fa88d44c1f491e96d/src/topology.c#L47

----

Also, a reminder not to touch Bliss sources at this time, as I'll be updating them shortly after 0.8 and formatting noise in the diffs makes that harder.

**Comment by ntamas** [comment]
@vtraag 

> Perhaps astyle doesn't do this alignment at all, it simply is a result of the tab-expansion?

It definitely does some kind of alignment, but it might be thrown off-course due to the comments. Any manual changes to indentation in these lines are promptly reverted by `astyle` so it's definitely intentional. However, it can be nudged in the right direction by adding a newline after the opening parenthesis - then the arguments are nicely aligned under each other.

**Comment by vtraag** [comment]
>  it can be nudged in the right direction by adding a newline after the opening parenthesis - then the arguments are nicely aligned under each other.

That sounds like a sensible solution then! I'd be happy to help out identifying parts where things go wrong, add a newline and re-run `astyle`.

**Comment by szhorvat** [comment]
I am mildly irritated by forcing braces for one-line `if`, `for`, etc. but I do not have a very strong feeling about it. Is there a way to set astyle to leave it as it is (instead of always adding or always removing braces)?

Example:

```
if (cond)
    x += 2;
```

or

```
if (cond) {
    x += 2;
}
```

**Comment by ntamas** [comment]
Yes, we can change that -- we need to remove `--add-braces` in `.astylerc`. I have gotten into the habit of using braces everywhere because one-line branches often evolve into multi-line branches and it is tiresome to add them later, but I'm okay with either.

**Comment by vtraag** [comment]
I agree with @szhorvat that it clutters one-liners. But in the interest of reducing possible bugs and issues that arise because of forgetting them, I'd still be in favour of keeping them.

**Comment by szhorvat** [comment]
> I have gotten into the habit of using braces everywhere because one-line branches often evolve into multi-line branches and it is tiresome to add them later, but I'm okay with either.

Of course, it's not a huge deal and I'm absolutely willing to go along with the all-braces style if people want that.

However, the following does bother me:

In `degree_sequence.cpp`, line 146, the following would be changed like so:

Current version:

```
        for (it = vertices.begin(), k = 0;
             k != vd.degree && it != vertices.end();
             ++it, ++k)
        {
            if (--(it->degree) < 0)
                goto fail;

            VECTOR(*edges)[2*(ec+k)] = vd.vertex;
            VECTOR(*edges)[2*(ec+k)+1] = it->vertex;
        }
```

astyle changes it to:

```
        for (it = vertices.begin(), k = 0;
                k != vd.degree && it != vertices.end();
                ++it, ++k) {
            if (--(it->degree) < 0) {
                goto fail;
            }

            VECTOR(*edges)[2 * (ec + k)] = vd.vertex;
            VECTOR(*edges)[2 * (ec + k) + 1] = it->vertex;
        }
```
Problems:

 - it messes up the multi-line part in the parentheses in `for (...)`
 - while I strongly prefer attached braces for most cases (`{` the same line as `for`) in this multi-line case it's not helping with readability

**Comment by szhorvat** [comment]
Readability would suffer in `arpack.c`:

https://github.com/igraph/igraph/blob/master/src/arpack.c#L35

![image](https://user-images.githubusercontent.com/1212871/72889533-2f445580-3d10-11ea-9da2-f1418145ba5b.png)

**Comment by szhorvat** [comment]
Another example from `arpack.c` where three statements originally written on the same line do seem to conceptually belong together, but astyle breaks them up. I am wondering it there is an astyle setting that prevents such lines from being forcibly broken up.

![image](https://user-images.githubusercontent.com/1212871/72889776-c0b3c780-3d10-11ea-8fed-5a6121990fa6.png)

**Comment by szhorvat** [comment]
In header files (e.g. `igraph_adjlist.h`), multi-line argument lists end up with an unfortunate indentation (because of all the `DECLDIR`):

![image](https://user-images.githubusercontent.com/1212871/72890497-4b48f680-3d12-11ea-8b86-bb8ce3ee8eae.png)

**Comment by szhorvat** [comment]
I need to stop for today. 

The above are some examples of problems, but they seem to occur rarely. Some of these can therefore be fixed manually.

The `examples/` directory doesn't contain some special things that tend to get messed up, such as `switch` statements or C++ code. These are what we need to pay attention to.

**Comment by ntamas** [comment]
You can always opt-out of `astyle` by wrapping a code section in `// *INDENT-OFF*` and `// *INDENT-ON*`.

**Comment by vtraag** [comment]
>You can always opt-out of astyle by wrapping a code section in // *INDENT-OFF* and // *INDENT-ON*

I assumed that we would only run `astyle` now once? Adding stuff to the source code to ensure proper formatting when running `astyle` only sounds like unnecessarily cluttering the source code. We could then go through the source code manually to correct things that were better before, and keep that style. The most important thing was the different tab/space indentation, and if that is solved, that is at least kept consistent by using `.editorconfig`.

**Comment by ntamas** [comment]
> I assumed that we would only run astyle now once?
Yes, me too. I just wanted to say that we can easily get around `astyle` if we know in advance that there are some problematic parts where the formatting would be messed up -- we can add the markers, run `astyle`, and then either remove them or just leave them as is.

I'll add an `.editorconfig` file in a later commit.

**Comment by ntamas** [comment]
> In degree_sequence.cpp, line 146, the following would be changed like so:

Managed to solve this by setting `--min-conditional-indent=0`.

> Readability would suffer in arpack.c:

This was solved with `--keep-one-line-statements`.

> In header files (e.g. igraph_adjlist.h), multi-line argument lists end up with an unfortunate indentation (because of all the DECLDIR):

Interestingly enough, the indentation is correct for the first function declaration of every such block and is incorrect for the rest. Nevertheless, I'd rather just let astyle do what it wants and spend some time on fixing the indentation in headers later (after the release of 0.8).

**Comment by ntamas** [comment]
Code formatting done. I consider this as a one-time event so I won't be running astyle regularly on the codebase. Therefore, if you don't like the formatting anywhere, you can fix it manually.

I'll adjust the existing vim modelines as well.
