### ISSUE TITLE
Optional checks in several igraph types.

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1204]
It would be good for debugging if some more checks are implemented on types such as the several heaps. These should only be included when compiled for debugging, e.g. 

    #if !defined(NDEBUG) 
    ... 
    #endif

as suggested by @ntamas.

This is probably not something for the short term, but which would be useful in the long term. This is just to track further conversations about this.

**Comment by szhorvat** [comment]
This is basically asking to add `assert()`s (which as `NDEBUG`-conditional, unlike `IGRAPH_ASSERT`s).

However, there is no clear target for this issue. When is it done? Either we should flesh it out or close it. Opinions @vtraag, @ntamas, since you opened it?

**Comment by ntamas** [comment]
Should have been a wontfix or something like that. The scope of this issue is not clear and again, this is a never-ending story and there are always more places to add asserts to. I'd just keep this in mind as a general guideline.
