### ISSUE TITLE
Cluster membership in python igraph is missing

### ISSUE THREAD

**Issue by ztilottama** [igraph/igraph#1206]
This issue is a bug report or a feature request, not a support question.
In R igraph i have a function using which i can get membership of clusters of graph object but similar way in python its missing.

in R  cl <-  split(V(graph)$name, clusters(gg)$membership)

**Comment by vtraag** [comment]
This repository is for the `igraph` core C library, please open the issue at the `python-igraph` repository at https://github.com/igraph/python-igraph/issues next time.

However, this can be answered easily.  The cluster membership is provided as a property of the `VertexClustering` object, see
https://igraph.org/python/doc/igraph.clustering.VertexClustering-class.html.

**Comment by ztilottama** [comment]
Thanks@vtraag , but the results seems different from R. do you mean cl.membership or something. Can I ask you a favour, if you can redirect me to some example to get cluster membership with VertexClustering. 
I used  this, but results are different than R 
cl = Gm.community_fastgreedy().as_clustering()
cl.membership

**Comment by vtraag** [comment]
I don't understand exactly what you mean. 

This is indeed how you get the membership of the clustering
```
cl = Gm.community_fastgreedy().as_clustering()
cl.membership
```
In what way is it different from R and what would you have expected?

**Comment by szhorvat** [comment]
@ztilottama Can you show a [complete minimal example](http://sscce.org/) that reproduces the problem (i.e. that results are different between Python and R)? We can't fix a problem that we can not reproduce.
