### ISSUE TITLE
Add tests for igraph_closeness

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1208]
There are no tests for `igraph_closeness`. We need to add tests both for the weighted and unweighted cases.

A reminder about the guidelines: https://github.com/igraph/igraph/wiki/Checklist-for-new-(and-old)-functions

**Comment by YasirKusay** [comment]
Hello, I would like to be assigned to this issue please.
I have already begun working on some of the tests for igraph_closeness_estimate.

**Comment by iosonofabio** [comment]
Hi Yasir,

It'd be best to proceed as we agreed, which is first open a PR so I/we can see your proposed changes and then we'll assign the issue.

It'll get easier as you get credibility but for now maybe that works best.

**Comment by iosonofabio** [comment]
Assigned to Yasir, as planned. Chances are progress on this will happen on PR #1290 and will be merged, if all goes well, right after 0.8 is released (assuming the code is working).
