### ISSUE TITLE
Building outside source directory fails

### ISSUE THREAD

**Issue by paulmenzel** [igraph/igraph#1212]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Building igraph 0.7.1 outside the source directory fails with the error below.

```
$ mkdir source build
$ cd source
$ # extract source archive
$ cd ../build
$ ../source/configure
$ make
make  all-recursive
make[1]: Entering directory '/dev/shm/bee-root/igraph/igraph-0.7.1-1/build'
Making all in src
make[2]: Entering directory '/dev/shm/bee-root/igraph/igraph-0.7.1-1/build/src'
gcc -g -O2 -I/usr/include/libxml2 -DNO_FPINIT f2c/arithchk.c -lm -o f2c/arith || \
gcc -DNO_LONG_LONG -g -O2 -I/usr/include/libxml2 -DNO_FPINIT f2c/arithchk.c \
        -Wall -lm -o f2c/arith
gcc: error: f2c/arithchk.c: No such file or directory
gcc: error: f2c/arithchk.c: No such file or directory
make[2]: *** [Makefile:7966: f2c/arith.h] Error 1
make[2]: Leaving directory '/dev/shm/bee-root/igraph/igraph-0.7.1-1/build/src'
make[1]: *** [Makefile:480: all-recursive] Error 1
make[1]: Leaving directory '/dev/shm/bee-root/igraph/igraph-0.7.1-1/build'
make: *** [Makefile:382: all] Error 2
```

**Comment by ntamas** [comment]
Seems to work fine for me with the master branch so this has probably been fixed already. Can you try building the master branch?

**Comment by vtraag** [comment]
I can confirm the issue with the released 0.7.1 code, but the master branch does indeed build correctly. I'm not sure what has changed, but whatever used to be the problem now seems to be fixed indeed.

**Comment by paulmenzel** [comment]
I was totally unaware, that version 0.7.1 is from 2014. ;-)

Anyway, commit b379441d (print a warning when calculating closeness on disconnected graph, closes #1053) from last year has the fix included.

```
diff --git a/src/Makefile.am b/src/Makefile.am
index f0b596f8..9ec6b28b 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -67,7 +67,7 @@ if INTERNAL_F2C
   libf2c_la_CFLAGS = -DSkip_f2c_Undefs -I. -I$(top_srcdir)/include -I$(top_builddir)/include $(WARNING_CFLAGS)
   f2c/arith.h: f2c/arithchk.c
        $(CC) $(CFLAGS) -DNO_FPINIT f2c/arithchk.c -lm -o f2c/arith || \
-       $(CC) -DNO_LONG_LONG $(CFLAGS) -DNO_FPINIT f2c/arithchk.c \
+       $(CC) -DNO_LONG_LONG $(CFLAGS) -DNO_FPINIT $(top_srcdir)/src/f2c/arithchk.c \
                $(WARNING_CFLAGS) -lm -o f2c/arith
```

I guess there is no plan for a 0.7.2 release, so I’ll look forward to the next release, where this is fixed.

**Comment by paulmenzel** [comment]
Correction, https://github.com/igraph/igraph/releases/tag/0.7.1 says it’s from December 2016. The author date of the last commit is from 2014. No idea, what is correct.

**Comment by ntamas** [comment]
No plans for 0.7.2 but we are actively working on releasing 0.8 around the end of July if things go well. (We are going through a list of triaged issues for 0.8).
