### ISSUE TITLE
Prüfer decoding has quadratic complexity, should be linear

### ISSUE THREAD

**Issue by Pascal-Ortiz** [igraph/igraph#1221]
In this issue, I'm talking about the `igraph_from_prufer` function.

The algorithm has quadratic time complexity so the implentation was not able to build in a reasonable time a tree having one million of nodes from a Prufer sequence. Here is my test code :

```c
#include <igraph.h>
#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <time.h>

int randrange(int a, int b)
{
    int d = b - a;
    srand((unsigned) time(NULL));
    return a + rand() % d;
}


void print_edges(const igraph_t *graph) {
    long ecount = igraph_ecount(graph);
    long i;

    for (i=0; i < ecount; ++i)
        printf("%d %d\n", IGRAPH_FROM(graph, i), IGRAPH_TO(graph, i));
    printf("\n");
}

int main() {

    clock_t now=0, end=0;
    igraph_t graph;
    int n=100000;
    igraph_integer_t *data=malloc(n*sizeof(igraph_integer_t));
    int i=0;

    for (i=0; i<n-2; i++)
        data[i]=randrange(0, 10);


    igraph_vector_int_t prufer;
    igraph_vector_int_view(&prufer, data, n-2);

    now = clock();

    igraph_from_prufer(&graph, &prufer);

    end=clock();
    fprintf(stderr, "CPU time: %.2fs\n",
            (double) (end - now) / CLOCKS_PER_SEC);


//     print_edges(&graph);
    igraph_destroy(&graph);

    return 0;
}
```

outputting:

```
CPU time: 2.24s
```
(compiled with O3 flag).

There exists linear time algorithms for decoding a Prufer sequence into a tree, for instance this [paper](https://pdfs.semanticscholar.org/f6a7/dffda435d1f732d220312fb667e1ba4d41a5.pdf).

On the other hand, I have tested the encoding `igraph_to_prufer` function and performances are OK, for instance, n = 1723653 vertices takes  0.22s (pure Python code takes 0.91s).

**Comment by szhorvat** [comment]
Here's another paper describing a linear-time algorithm for Prüfer decoding: http://dx.doi.org/10.4236/jsea.2009.22016

(Please try to use permalinks, i.e. DOIs, whenever possible. It's important that the reference material we use for implementation stays accessible even years later.)

Here's an alternative link for the above (just in case!):
 
 * Paulius Micikevicius, Saverio Caminiti, Narsingh Deo: [Linear-time Algorithms for Encoding Trees as Sequences of Node Labels](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.70.5052&rep=rep1&type=pdf)

**Comment by Pascal-Ortiz** [comment]
> Here's another paper describing a linear-time algorithm for Prüfer decoding _even for unsorted sequences_: http://dx.doi.org/10.4236/jsea.2009.22016

I was aware of this paper but some points remains obscure (to me). The [NetworkX implementation](https://networkx.github.io/documentation/latest/_modules/networkx/algorithms/tree/coding.html#from_prufer_sequence) is actually based on this paper and the time complexity seems more quadratic than linear, cf. this [issue](https://github.com/networkx/networkx/issues/3521). Don't get me wrong, this doesn't mean the algorithm described in the paper is not linear.


> 
> (Please try to use permalinks, i.e. DOIs, whenever possible.

OK, thanks, I'll try, I was not aware of.


> * Paulius Micikevicius, Saverio Caminiti, Narsingh Deo: [Linear-time Algorithms for Encoding Trees as Sequences of Node Labels](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.70.5052&rep=rep1&type=pdf)

OK, thanks for the corrected link. My Python algorithm referenced in my first message is based on this paper and is quite easy to understand.

**Comment by szhorvat** [comment]
> I was aware of this paper but some points remains obscure (to me). The [NetworkX implementation](https://networkx.github.io/documentation/latest/_modules/networkx/algorithms/tree/coding.html#from_prufer_sequence) is actually based on this paper and the time complexity seems more quadratic than linear, cf. this [issue](https://github.com/networkx/networkx/issues/3521).

Thanks! Comments like this are very useful.
 
> OK, thanks for the corrected link. My Python algorithm referenced in my first message is based on this paper and is quite easy to understand.

Would you be willing to share it?

**Comment by Pascal-Ortiz** [comment]
> Would you be willing to share it?

The issue as been tagued "Need PR" so I'm going to propose one in the very few days, can you wait for that? If you prefer I can send you the code but it needs some cleanup and some checking.

**Comment by szhorvat** [comment]
If you can send me (privately) a messy but working version, that's already useful.

**Comment by szhorvat** [comment]
Here's a measurement of the speedup for the old vs new (#1222) algorithms, using the Mathematica interface (which may have a significant overhead).

![image](https://user-images.githubusercontent.com/1212871/61716822-35a54500-ad60-11e9-9c4f-80e891f88c34.png)
