### ISSUE TITLE
Compilation for Python 3.7

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1228]
We should make sure that the C core also builds correctly for Python 3.7. We can simply adapt [`appveyor.yml`](https://github.com/igraph/igraph/blob/master/appveyor.yml) to also include Python 3.7 I guess.

**Comment by ntamas** [comment]
Actually, `PYTHON_VERSION=NONE` in `appveyor.yml` seems to correspond to Python 3.7. The naming is misleading, though.

**Comment by vtraag** [comment]
Ah, right. Yes, let's correct the naming then.
