### ISSUE TITLE
all_st_mincuts returns empty cuts

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1235]
For many different inputs, `all_st_mincuts` returns _some_ empty results, in addition to the correct results.

Here's a small example in R:

```R
g<-make_graph(c(4,3, 3,1, 3,2, 2,1))
plot(g)
cuts<-st_min_cuts(g,3,1)
cuts$cuts
```

The output is

```
[[1]]
+ 2/4 edges from 6cc9c03:
[1] 3->1 3->2

[[2]]
+ 2/4 edges from 6cc9c03:
[1] 3->1 2->1

[[3]]
+ 0/4 edges from 6cc9c03:
```

The graph looks like this:

![image](https://user-images.githubusercontent.com/1212871/63197846-338d8800-c079-11e9-8186-68ef4f97b2f3.png)

This function should return all minimum cuts (compare to `igraph_all_st_cuts` which returns all minimal cuts, and can thus be used to verify the result from `igraph_all_st_mincuts`).  Therefore, the size of all returned cuts should be the same.

Possibly related:

 - https://github.com/igraph/igraph/issues/204
 - https://github.com/igraph/igraph/issues/628
 - https://lists.nongnu.org/archive/html/igraph-help/2014-06/msg00005.html

**Comment by vtraag** [comment]
Similar to #1236, the identified minimal cuts are actually wrong. The actual third partition returned by `igraph_all_st_mincuts` is `3`, `2` and `1`, which is not a correct cut to separate `3` from `1`, leading to the empty cut. Possibly a similar solution as proposed in #1248 may work, I am currently investigating.

**Comment by vtraag** [comment]
Note that if you reverse the direction of the edge `4 -> 3` to `3 -> 4`, you will get the cut `2 -> 1`, `3 -> 1` twice. There seems to be something strange going on, definitely some bug, but I have not yet figured out what exactly.

**Comment by vtraag** [comment]
I think the problem may be the following. The set of *active* nodes in the condensed acyclic graph (i.e. the DAG corresponding to the contraction of the strongly connected components) is somewhat ambiguous in the paper, it seems. In the implementation in `igraph` a node is considered *active* independent of the set `S` that is under consideration, which may the root of the problem. Perhaps a node should only be considered *active* when a node is connected to edges in the edge set E_1 relative to the subgraph of the condensed acyclic graph induced by `S`. I will investigate further. But perhaps you may have a suggestion, @gaborcsardi ?
