### ISSUE TITLE
all_st_cuts: inconsistent behaviour when s and t are not connected

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1236]
`igraph_all_st_cuts` behaves in an inconsistent way when `s` and `t` are not connected.

Sometimes it returns no cuts at all, and sometimes it returns a single cut of zero size.

Here's a small example using the (unfinished) Mathematica interface:

![image](https://user-images.githubusercontent.com/1212871/63209451-14c2dc00-c0e1-11e9-9c2b-3c74555a032c.png)

The edge list is:

```
1,2
2,3
1,4
4,3
```

For `s=3, t=1` we get no cuts at all.

For `s=2, t=4` we get a single cut of zero size.

Either would be an acceptable result (it's up to interpretation), but the result should be the same in both cases.

**Comment by szhorvat** [comment]
This was first brought up in the comments on https://github.com/igraph/igraph/pull/1225

**Comment by vtraag** [comment]
This is not only inconsistent behaviour, it is actually incorrect behaviour. The cut itself is empty, but the partition that is returned is not (and is incorrect).

Using the graph
```
igraph_small(&g, 4, IGRAPH_DIRECTED, 
    0,1, 1,2,
    0,3, 3,2,
    -1);
```
and finding cuts using
```
igraph_all_st_cuts(&g, &cuts, &partition1s, 1, 3);
```
the pointer vector `partition1s` contains one partition containing nodes `1` and `2`, which is incorrect. I am currently investigating.
