### ISSUE TITLE
Wishlist: Implement the 2 missing triads from triad_census()

### ISSUE THREAD

**Issue by Marmeladenbrot** [igraph/igraph#1239]
The triad list from the triad_census() function (https://igraph.org/r/doc/triad_census.html) shows 16 different triads

The cited paper (page 12, https://files.eric.ed.gov/fulltext/ED024086.pdf) shows 18 triads

Please implement the missing 2 triads for that function (especially 030a).

**Comment by szhorvat** [comment]
There are only 16 non-isomorphic directed graphs on 3 vertices, not 18.

 030a from the paper is the 8th result returned by igraph's function.

**Comment by szhorvat** [comment]
I'm sorry, I won't go through the drawings in the paper one by one, but perhaps you can use this exhaustive list of the 16 graphs as a guide to find which are listed more than once, and clear up the misunderstanding. I am not personally familiar with MAN labels, but there are no other directed graphs on 16 vertices than these.

![image](https://user-images.githubusercontent.com/1212871/63284480-f6f9a080-c2b3-11e9-9f4a-700c390adb02.png)

**Comment by Marmeladenbrot** [comment]
I mean this triad which I can't find in the list?

![List of triads from the paper](https://i.imgur.com/nFjsWrv.png)

**Comment by ntamas** [comment]
It's in the list, second row, fourth item, labeled `030T` - you just need to flip the two rightmost vertices. (The two graphs are isomorphic).

**Comment by Marmeladenbrot** [comment]
Added an /edit.
Thanks for your help and sorry for the inconvenience.
