### ISSUE TITLE
Community detection benchmark functions

### ISSUE THREAD

**Issue by kenmcgarry** [igraph/igraph#1249]
Would future versions of igraph see the implementation of the Girvan-Newman and the LFR benchmarks for community detection?

**Comment by vtraag** [comment]
The Girvan-Newman benchmarks can already be generated through [`igraph_preference_game`](https://igraph.org/c/doc/igraph-Generators.html#igraph_preference_game), or more generally a block-model. Hence, you can also generate clusters of varying sizes. The only difference with LFR is that the degree distribution will be something like a mixture of Poisson distributions and cannot be separately specified.

**Comment by ntamas** [comment]
Personally, I think that benchmark functions are outside the scope of igraph; I don't think that benchmarks have any general use for people working with graph theory or network science apart from those who want to develop a new community detection algorithm.

**Comment by vtraag** [comment]
I agree that `igraph` need not include functions that are only useful in the context of developing a new community detection algorithm. They can already be generated through `igraph_preference_game`, and I don't think the actual LFR networks need to be generated by `igraph`. However, it might be good to consider sampling from a stochastic block model with a fixed degree distribution. This will probably have applications beyond the more narrow purpose of developing a new community detection algorithm.

**Comment by kenmcgarry** [comment]
Thank you for your consideration and advice.

**Comment by ntamas** [comment]
See https://github.com/ntamas/blockmodel for sampling from stochastic blockmodels. It might not cover the requirements of the LFR benchmark, but maybe it’s a good starting point.

**Comment by salahinfo** [comment]
Could you show me how generate GN network with Igraph pleas ?

**Comment by ntamas** [comment]
Please send support questions to https://igraph.discourse.group and do not hijack the topic of existing issus.

Also, when asking questions on https://igraph.discourse.group, please state whether you are using igraph from C, R, Mathematica or Python as the answer is almost surely different depending on which language you use igraph from.
