### ISSUE TITLE
Wishlist: Cycle basis of undirected graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1252]
This is a suggestion to implement finding a [cycle basis](https://en.wikipedia.org/wiki/Cycle_basis) of an undirected graph. Additionally, implement finding a minimum weight cycle basis (see also [Horton bases](https://en.wikipedia.org/wiki/Cycle_basis#Polynomial_time_algorithms)).

Consider extensions to directed graphs later.

**Comment by szhorvat** [comment]
Should anyone want to take this, I can provide guidance.

**Comment by iosonofabio** [comment]
I'm always happy to learn if this is not urgent - I'll be traveling for a few weeks

**Comment by vtraag** [comment]
I think the implementation of finding a cycle basis in an unweighted undirected graph should be relatively straightforward (essentially a spanning tree). The extension to weights will probably take more time. Perhaps first implement the unweighted version and only then the weighted version?

**Comment by iosonofabio** [comment]
Sounds good

**Comment by szhorvat** [comment]
@iosonofabio I'm happy to walk you through it, including the weighted version (Horton's algorithm). Just contact me whenever you want to get started.

**Comment by szhorvat** [comment]
Fundamental cycle basis and unweighted minimum cycle basis were implemented in https://github.com/igraph/igraph/pull/1957, closing.
