### ISSUE TITLE
Transition lazy_adjlist_t and lazy_inclist_t to vector_int_t

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1255]
`igraph_adjlist_t` and `igraph_inclist_t` work with `igraph_vector_int_t`.

However, `igraph_lazy_adjlist_t` and `igraph_lazy_inclist_t` work with `igraph_vector_t` (i.e. doubles, not integers).

One might want to try both the lazy and non-lazy versions while developing new functionality, to see which performs better. It's a bit inconvenient to swap between them now because of the type mismatch.

We should aim to transition to `vector_int_t` for the lazy versions as well.

If anyone knows a reason why this SHOULD NOT be done, please comment.

**Comment by vtraag** [comment]
Should we perhaps transition `igraph_adjlist_t` and `igraph_inclist_t` to `igraph_vector_t` instead for consistency? Or perhaps simply wait with doing this until we are fully replacing node and edge indices with `igraph_vector_int_t` throughout the project (and in `igraph_t`)?

**Comment by szhorvat** [comment]
> Should we perhaps transition `igraph_adjlist_t` and `igraph_inclist_t` to `igraph_vector_t` instead for consistency? 

I think that would be a lot of work for too little tangible gain.

> Or perhaps simply wait with doing this until we are fully replacing node and edge indices with `igraph_vector_int_t` throughout the project (and in `igraph_t`)?

That's reasonable.

**Comment by szhorvat** [comment]
Fix in 65f459a401e496c2e03e576bcfc347a9ec5afb15

**Comment by ntamas** [comment]
Oh, nice :)
