### ISSUE TITLE
Configure includedir argument

### ISSUE THREAD

**Issue by carissableker** [igraph/igraph#1263]
- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

The argument `includedir` does not affect where header files are installed. For example: 

    ./configure --libdir=/mypath/lib/ --includedir=/mypath/include/ --prefix=/myprefix
    make
    make install

This puts the library files in `/mypath/lib`, but not the header files in `/mypath/include` (but still in `/myprefix/include/igraph`). 

This is in version 0.7.1. 

(I may be misunderstanding the argument -- I am not experienced in compiling C/C++)

**Comment by gaborcsardi** [comment]
Yes, it will always puts them `igraph`, within the specified directory.

**Comment by carissableker** [comment]
The headers end up in `/myprefix/include/igraph/`, but not in `/mypath/include/` (the argument I am specifying to `--includedir`). I can work around it. It's just not the behaviour I expected, as it seems to be ignoring the `--includedir` argument for `./configure`.

**Comment by gaborcsardi** [comment]
Many libraries, that have a lot of headers, like igraph, collect them into a single library, so that they are easier to manage.

**Comment by szhorvat** [comment]
I believe what @carissableker is pointing out is not that the headers are collected within a subdirectory named `igraph`, but that the `--includedir` argument is not respected.

`./configure --help` says:

```
Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [PREFIX]

...

Fine tuning of the installation directories:

...

  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
```

Thus, if `--includedir` is not specified, the headers should go in `PREFIX/include/igraph`.

But if we specify `--includedir=mydir`, I would expect them to go in `mydir/igraph`. This does not work.

It appears to me that there really is a bug with `configure` here.

(Personally I only ever use `--prefix`, and I never needed to find-tune the include locations, so I am not affected by this.)

**Comment by szhorvat** [comment]
Interestingly, the correct `includedir` value does show up in a number of places (e.g. the generated `igraph.pc` file), but it's not where `make install` copies files to.

**Comment by ntamas** [comment]
I think the problem is [this line](https://github.com/igraph/igraph/blob/master/src/Makefile.am#L421); basically we are setting `includedir` in the makefile even if it is already set to a different value.

**Comment by szhorvat** [comment]
@carissableker Can you explain why you need to fine-tune the include directory instead of using the default one in PREFIX?

**Comment by ntamas** [comment]
Also, can you test 1d1e1069? I have made an adjustment to `src/Makefile.am`; it seems like `--includedir` was ignored before but it should be used now.

**Comment by szhorvat** [comment]
> Also, can you test 1d1e106?

I tested this, and unfortunately it breaks collecting headers: now they go into `PREFIX/include` by default and not `PREFIX/include/igraph`. Also with `--includedir=DIR` they go into `DIR` and not `DIR/igraph`.

We do want to retain the `igraph` subdirectory.

Would `includedir = $(includedir)/igraph` make sense? I have almost zero experience with autoconf.

**Comment by ntamas** [comment]
That would be a recursive definition and the makefile syntax does not allow that. However, I think I have found a solution; see commit 3cdb86de

**Comment by carissableker** [comment]
> @carissableker Can you explain why you need to fine-tune the include directory instead of using the default one in PREFIX?

_caveat: I am not experienced in C/C++, this project is my first foray away from Python, so I am probably doing things very wrong_

I am basing a C++ project on igraph. I need it to be very portable, and am therefore compiling igrah with my code when I move it to a different computer or cluster. This makes it easier, since I don't have sudo access on these platforms, and don't want to have to rely on the cluster admin and/or have to change $PATH variables. 
 
I am using the default folder in prefix, but  I was experimenting with my options and by chance found this bug that I thought you may want to know about. 

If you are interested, I can share my repository on github with you. Let me know, I would appreciate your insight.
