### ISSUE TITLE
Feature request: Create directed Watts-Strogatz network

### ISSUE THREAD

**Issue by jxu** [igraph/igraph#1269]
https://www.r-bloggers.com/generating-directed-watts-strogatz-network/ implementation in R although I could not get it to run

**Comment by szhorvat** [comment]
There are countless variations possible on Watts–Strogatz-like models, and I don't think it's reasonable to try to support all of them in a single function. Generally, 1. first some lattice-like network is generated, 2. then it's rewired. What's better is to support these two distinct steps with reasonable flexibility. igraph already does this.

For square lattice like graphs, use [igraph_lattice](https://igraph.org/c/doc/igraph-Generators.html#igraph_lattice). For rewiring, use [igraph_rewire_edges](https://igraph.org/c/doc/igraph-Generators.html#igraph_rewire_edges).

**Comment by szhorvat** [comment]
In R, the corresponding functions are `make_lattice` and `rewire` with `each_edge`.
