### ISSUE TITLE
failed installation 

### ISSUE THREAD

**Issue by akhst7** [igraph/igraph#1272]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

The latest cram version of igraph_1.2.4.2 failed to compile with a following error;

```
checking for gcc... /usr/local/opt/llvm/bin/clang -fopenmp
checking whether the C compiler works... no
```
Here is my system;

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G2022

(base) ➜  ~ clang -v
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/9.2.0_2/libexec/gcc/x86_64-apple-darwin18/9.2.0/lto-wrapper
Target: x86_64-apple-darwin18
Configured with: ../configure --build=x86_64-apple-darwin18 --prefix=/usr/local/Cellar/gcc/9.2.0_2 --libdir=/usr/local/Cellar/gcc/9.2.0_2/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 9.2.0_2' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
Thread model: posix
gcc version 9.2.0 (Homebrew GCC 9.2.0_2)

  
R.version                          
platform       x86_64-apple-darwin18.6.0   
arch           x86_64                      
os             darwin18.6.0                
system         x86_64, darwin18.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes
```
I have a Makevers;

```
LLVM_LOC = /usr/local/opt/llvm
CC=$(LLVM_LOC)/bin/clang -fopenmp
CXX=$(LLVM_LOC)/bin/clang++ -fopenmp

CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include
```
Regardless of having the Makevers, igraph failed to compile with the same error.

**Comment by szhorvat** [comment]
The default compiler on macOS does not support OpenMP. Remove those flags.

--
sent from a phone

**Comment by ntamas** [comment]
Hmmm, this seems to be an issue about building the R interface of `igraph`, not the igraph core library itself. (Note the version number of igraph; 1.2.4.2 is not applicable for the C core). Also, it seems that the C compiler being used is the one from Homebrew, not the stock compiler on macOS.

@akhst7 Is this about the R interface of igraph? If so, let me know and I'll transfer the issue to the igraph/rigraph repo.

**Comment by szhorvat** [comment]
A typical cause of "checking whether the C compiler works... no" is compiler or linker flags that prevent compilation. In this case, the prime suspect is `-fopenmp`. Try removing this.  

If that doesn't help, examine the log file that the configure script tells you about. It will have the error message from the compiler.

This does not look like an igraph issue for me (either C core or R interface). I would expect any configure script to fail the same way if given the same compiler/linker flags.

**Comment by akhst7** [comment]
So, I am not using a OSX compiler as indicated.  I am using brew installed gcc with Clang 9.00 which fully supports openMP.  Looking at config.log,  I see Clang-9 is complaining a lot but the one is killing configure is ;

c```
onfigure:2866: /usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include  conftest.c  >&5
ld: library not found for -lomp
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
It looks like the configure can't find libomp.dylb. which is in multiple locations including  /usr/local/lib which should be accessible to the compiler.   I have no had this issue except another R package, e1071 with same error.

**Comment by ntamas** [comment]
Try reproducing what the configure script attempts to do; create an empty C file named `conftest.c`, put some dummy C code in it (probably an empty `main()` function would do), and then run this:

```
/usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include  conftest.c
```

Then try tweaking your system configuration until it works. One possibility is that `clang` is not looking for libraries in `/usr/local/lib`, only in `/usr/local/opt/llvm/lib`.

**Comment by akhst7** [comment]
I figured this out.  Clang-9 with openmp was working fine but I modified Makevars as follows  and solved the issue I was having.  

Thanks for all the suggestions.

```
#LLVM_LOC = /usr/local/opt/llvm
CC=clang
CXX=clang++
#CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
#CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib 
CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include 
```
