### ISSUE TITLE
Documentation should be built on Travis

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1276]
As suggested by Vincent, there should be a Travis job to build the documentation.  It has happened several times in the past that the documentation stopped building because of some small XML validation issue. We should have a way to detect this immediately.

**Comment by szhorvat** [comment]
@ntamas Would you like to take this, since you're currently fiddling with Travis?

**Comment by vtraag** [comment]
Probably this should be also done in stages, and probably only for a single OS.

**Comment by iosonofabio** [comment]
usually I do this for a single OS which is robust (e.g. linux), a single python version, and with stages

**Comment by ntamas** [comment]
Sounds good to me. My priority right now is to get things sorted out with the building of wheels in `python-igraph`, but I can also take a stab at this one once I'm done over there.

We could probably also auto-deploy the documentation somewhere with Travis and Github Pages, couldn't we? Any best practices out there? The best would be to have the documentation for tagged releases built and pushed automatically to a permanent place, and the master revision could be published somewhere else; something like https://doc.igraph.org/igraph/0.8.0 for the 0.8.0 tag, https://doc.igraph.org/igraph/stable for the latest stable release and https://doc.igraph.org/igraph/master for the head of the master branch.

**Comment by ntamas** [comment]
Documentation is [now built on Travis](https://travis-ci.org/igraph/igraph/jobs/635396255) in HTML and PDF format.

Next step: where can we host the documentation that was built?

**Comment by iosonofabio** [comment]
Fantastic!!

What's behind the current igraph pages?

On Travis you can save encrypted passwords so one can just push it to the igraph server via ssh, aws, or whatever else.

Or am I misunderstanding the question?

**Comment by ntamas** [comment]
Well, igraph.org is currently served from the [igraph/igraph.org](https://github.com/igraph/igraph.org) repo with Github Pages. So, if I want to update anything on the homepage, the process is like this:

1. Modify the content in the repo.
2. Rebuild the page with Jekyll into the `docs/` folder of the repo.
3. Commit the changes to the repo, _including_ the generated `docs/` folder.
4. Push the changes to Github.
5. ???
6. Profit!

I think there's no way I could inject stuff into igraph.org from Travis without changing the process above as well. I'll figure something out.

**Comment by iosonofabio** [comment]
Oh so there's a separate repo/branch just for the website? We could push to that repo from Travis. Happy to help if you need.

Or you wanna have a quick call? I'm in Oz so now or tomorrow same time would work, or anytime in the next 13 hours.

**Comment by szhorvat** [comment]
The documentation is already being built on Travis. The reason this is open is because it is not being pushed to a server, so it can be read immediately, right?

**Comment by ntamas** [comment]
Yes, that's correct.

**Comment by szhorvat** [comment]
Continued in #1702.
