### ISSUE TITLE
Setup archiving on Zenodo

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1278]
The plan is to automatically archive all `igraph` releases on Zenodo.

**Comment by ntamas** [comment]
Is this addressed by #1280 or is there more to the story?

**Comment by szhorvat** [comment]
There's a bit more, as we need to connect Zenodo. I'll look into this. I haven't done it yet because I have to check how people other than myself will be able to change settings on Zenodo if I use my own Zenodo account.

**Comment by vtraag** [comment]
In the `igraph` repository that is all that needs to be done I think. But the hook should also be created in Zenodo so that is watches the repository when a release is made. Perhaps @szhorvat has already done that?

**Comment by szhorvat** [comment]
I'll close the issue when it's done.

**Comment by szhorvat** [comment]
Tamás set this up. DOI will be assigned after the first release is created.
