### ISSUE TITLE
Speed up igraph_rewire

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#128]
igraph_rewire is slow because it is adding and removing edges using igraph_add_edges and igraph_remove_edges instead of working on an adjacency list. Check whether it can be speeded up and also examine whether it is possible to keep the edge attributes.

---

Imported from Launchpad using lp2gh.
- date created: 2012-12-21T11:18:50Z
- owner: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/1092868

**Comment by szhorvat** [comment]
Done already, please close.
