### ISSUE TITLE
Location of 'C_R_igraph_finalizer'

### ISSUE THREAD

**Issue by zamadxarif** [igraph/igraph#1285]
Hello igraph developers,
Apologies if this is not the right place to ask. 
The R function for degree calls the C function 'C_R_igraph_finalizer' and 'C_R_igraph_degree'. I would like to view the code underlying this but am unable to find it in the repository. Could someone kindly guide me to this?
Thanks.

**Comment by gaborcsardi** [comment]
These are in the R package, e.g. https://github.com/igraph/rigraph/blob/675946d0d30a3e29b3562a76d25a52faf2332240/tools/stimulus/rinterface.c.in#L2150
