### ISSUE TITLE
Compilation on Windows

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1287]
Right now, the `igraphtest` solution does not immediately build correctly because of two things.

1. We need to add `#define IGRAPH_NO_IMPORTS 1` to `igraphtest.cpp`, as explained [here](https://github.com/igraph/igraph/pull/1279#issuecomment-577080247). As discussed in that thread, we will change the name of the symbol to `IGRAPH_STATIC`.

2. We need to correct the include/library directory. Right now, all include/lib directories refer to the `igraph-0.7-msvc` directory. There are two possible solutions for this problem:
  a. We generate the `igraphtest.vcproj` dynamically.
  b. We simply use the directory name `igraph-msvc` instead of `igraph-[DIRECTORY]-msvc`.

I would prefer option (b). When making the MSVC zip file for distributing the source when running `make msvc` we could still include the version number though.

**Comment by ntamas** [comment]
Point 1) is now taken care of.

As for point 2), what is the problem with generating `igraphtest.vcproj` dynamically?

**Comment by vtraag** [comment]
We could generate `igraphtest.vcproj` dynamically, but it creates yet another step in the whole build chain, which is already complex enough as it is. Preferably I'd like to make it as simple as possible, more complex chains are only more likely to break at some step of the process. What is the reason to keep the name of the directory as `igraph-[VERSION]-msvc`?

**Comment by ntamas** [comment]
Okay, another idea. Why don't we put the whole `igraphtest` folder as `test` _inside_ `igraph-[VERSION]-msvc`? This way we would not need to use `..\igraph-[VERSION]-msvc\include` in the project file -- we could simply use `..\include`. (Plus, the whole ZIP file would be much cleaner; generally I like when there is only one top-level directory in a ZIP file so I can clear the contents after unzipping easily).

**Comment by ntamas** [comment]
Added a commit with the changes proposed above - can you please test it?

**Comment by vtraag** [comment]
I seem to be running into some issue. Will investigate and make a new PR to fix this. I will also look into compilation with `libxml` support (which also has some issues, as I mentioned [here](https://github.com/igraph/igraph/pull/1279#issuecomment-577557544)).

**Comment by ntamas** [comment]
Thanks for the fix, I missed this point while testing - my build folder always had lots of cr*p in there that needed to be cleaned up while creating the ZIP.
