### ISSUE TITLE
Release timeline for 0.8

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1291]
This issue is to make it easier to keep track of tasks for the 0.8 release and prioritize tasks. Please edit it as needed: add missing tasks, check completed ones, optionally assign yourself to a task.

----

Release happens on Jan 28 or 29 (Tue or Wed). 

Some consider Tuesday announcement ideal for attracting maximal attention.

----

Pre-release checklist:

 - [x] Complete changelog
 - [x] Reformat source code
 - [x] Complete installation instructions
 - [x] Update website:
   * [x] General proofreading, check for outdated info
   * [x] Support links should point to Discourse forum
   * [x] Create release announcement News item on website
 - [x] Update documentation:
   * [x] Installation instructions
   * [x] Make sure all documented functions are included (e.g. `sir` is not)
 - [x] Create official igraph contact email
 - [x] Get forum ready to launch
   * [x] Finalize categories
   * [x] Set up Google login
   * [x] Terms of service review, correct email to official igraph email
   * [x] Seed with a few sample support threads
 - ???
 - [x] **Launch!**
   * [x] Create release on GitHub
   * [x] New website should go live
   * [x] New support forum should go live
----

Post-release checklist (tentative).

 - [x] Announcements
   * [x] Mailing list (@ntamas)
   * [x] Also announce new forum on mailing list (@ntamas)
   * [x] Twitter (don't forget to retweet and credit people) (@vtraag)
   * [x] Facebook groups: Young Researchers Network on Complex Systems Online Community or similar. (@szhorvat) 
   * [x] Hacker news (@szhorvat)
 - [ ] Package managers: https://github.com/igraph/igraph/issues/1284
   * [x] [MacPorts](https://www.macports.org/) (@szhorvat)
   * [x] [homebrew](https://brew.sh/) (@ntamas)
   * [ ] [conda](https://anaconda.org/conda-forge/igraph) (@vtraag)
 - [x] When trying to open GitHub issues, people should see a notice that support issues must go on Discourse (@ntamas)
 - [x] Update tag description on StackOverflow and add link to Discourse and igraph website (@szhorvat)
 - [x] Add Zenodo DOI to docs for citation purposes (DOI is created only after release)

**Comment by szhorvat** [comment]
I marked docs as complete. It's good enough as it is. We can make more doc improvements for a possible 0.8.1.

**Comment by vtraag** [comment]
I just finalized the categories setup and description of the [igraph support forum](https://igraph.discourse.group/). As suggested by @szhorvat, it might be a good idea to have some seed examples in all categories. Suggestions are welcome. Perhaps there are some good previous issues that have come up that we can use?

**Comment by ntamas** [comment]
Updated installation instructions for Windows are now live on the staging version of the website.

**Comment by szhorvat** [comment]
Today is the originally planned release day. It is time to review where we stand. Hopefully, we can release with no more than 2 days delay.

 - Code base is fine (#1302 should be addressed today)
 - Why are the Windows installation instruction PRs still open? #1279 #1289 
 - I think the changelog is complete. Please complain in #1295 if something is missing.
 - Website is complete
 - We need to write the release announcement for the News section of the website. I volunteer to do it tonight and open a PR for the igraph.org repo. If anyone else wants to do it instead, let me know so we don't duplicate work.
 - **The big blocker** is the email address, which is a pre-condition for setting up the Google login for Discourse. What is the status of this @gaborcsardi and @vtraag ? If the `@igraph.org` address won't happen right away, we should go ahead with creating the Google account right away as an easy-to-use Google login is important for the forum if we want people to actually use it.
 - Seeding the website with contents is not critical, but would be nice. I don't think this should block the release. Everyone feel free to post sample questions/answers on your favourite topic.  I will post a few for the Mma interface.

**Comment by szhorvat** [comment]
I tentatively assigned the post-release tasks to people, edit if necessary.

**Comment by gaborcsardi** [comment]
OK, I set up the forwarding, who wants to be included?

I am not sure if this will be the right solution, though. You can reply to a message that was sent to igraph.org, but I don't think others will see your reply, unless it is explicitly sent to igraph.org as well. Anyway we can test it.

**Comment by vtraag** [comment]
@gaborcsardi Thanks for setting it up! Please include me (v.a.traag@cwts.leidenuniv.nl).

This is indeed the downside of the current setup. The most important thing is that we now have the address working. Perhaps in the future we need to setup some shared mailbox or something, I'm not sure what solutions are out there.

**Comment by ntamas** [comment]
Added a notice about the Discourse group in the issue template. Also added [contributing guidelines](https://github.com/igraph/igraph/blob/master/.github/CONTRIBUTING.md).

**Comment by ntamas** [comment]
Updated the Python part of the homepage to refer to the Discourse group instead of the mailing list. The only reference left to the mailing list on the homepage now is under the R subpage. I don't know whether @gaborcsardi prefers to keep on using the mailing list or watch the Discourse forum instead so I've left everything as is in the R territory for the time being.

**Comment by vtraag** [comment]
Might it be an idea to include @szhorvat's [checklist for functions](https://github.com/igraph/igraph/wiki/Checklist-for-new-(and-old)-functions) in `CONTRIBUTING.md`?

**Comment by szhorvat** [comment]
As far I can see, we are ready.

@ntamas Can you go ahead, make the release and publish the website?

**Comment by ntamas** [comment]
@vtraag I have added the checklist to `CONTRIBUTING.md`.

**Comment by ntamas** [comment]
New release and website is live now. Homebrew formula will be sent in for review soon.

**Comment by szhorvat** [comment]
Next step is announcements. 

@ntamas Can you please send an email to the mailing list, link to the news item and the Discourse forum? It should be from a familiar name.

@vtraag Perhaps you can go ahead with the Twitter?

**Comment by ntamas** [comment]
Sent an email to igraph-announce@nongnu.org a few mins ago, but it might have got stuck in the moderation queue. @gaborcsardi used to be the one who sent the announcements back in the old days, I never sent anything there -- anyway, stay tuned :)

**Comment by gaborcsardi** [comment]
I am pretty sure that you have a password for https://lists.nongnu.org/mailman/admindb/igraph-announce but I'll just ok it now. Every message is moderated on this list.

**Comment by gaborcsardi** [comment]
Btw. it would make sense to send it to igraph-help as well, maybe?

**Comment by szhorvat** [comment]
> Btw. it would make sense to send it to igraph-help as well, maybe?

@gaborcsardi Absolutely! Would you like to do that yourself?

**Comment by ntamas** [comment]
I'm doing it now.

**Comment by gaborcsardi** [comment]
If it is not too late, also put "new igraph forum" in the subject pls. It is not too hard to miss it in the email...

**Comment by ntamas** [comment]
I have sent it already, but I'll send a separate message to igraph-help later

**Comment by vtraag** [comment]
The [PR](https://github.com/conda-forge/igraph-feedstock/pull/14) for updating the `conda` build is underway. I will first ensure that it properly builds on Linux/macOS, and then I will look into building it for Windows.

**Comment by vtraag** [comment]
The updated [PR](https://github.com/conda-forge/igraph-feedstock/pull/15) for `igraph` on `conda` now also supports Windows.

**Comment by szhorvat** [comment]
@vtraag Is `igraph` okay on conda-forge now and can we close this?

**Comment by vtraag** [comment]
Yes, it is merged.
