### ISSUE TITLE
Internal functions in public API

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1301]
At the moment there are a number of internal functions exposed in the public API:

- [x] `igraph_flow.h`
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_flow.h#L125
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_flow.h#L132

- [x] `igraph_sparsemat.h`
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_sparsemat.h#L263

    **[Decision](https://github.com/igraph/igraph/issues/1301#issuecomment-726251473):** Rename and expose in public API.

- [x] `igraph_spmatrix.h`
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_spmatrix.h#L92-L95

- [x] `igraph_structural.h`
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_structural.h#L144-L147

- [x] `igraph_visitor.h`
https://github.com/igraph/igraph/blob/41f34a9f01f34965cc918f3ec07a728c5a32edf3/include/igraph_visitor.h#L88

    **Note:** `igraph_i_bfs()` is currently used by the Python interface.

There are also a number of occurrences of `igraph_i_*` declarations in `igraph_attributes.h`, but some of these do seem to be intended for public use. These should probably be cleaned up.

**Comment by szhorvat** [comment]
This we leave for 0.9 or 0.8.x, right? I think it's not critical and we're out of time.

**Comment by vtraag** [comment]
Yes, definitely!

**Comment by iosonofabio** [comment]
Since we just started a discussion on internal types and exposure, this is related.

I'd be for making everything private unless you guys tell me not to. Does anyone use any of the above functions?

**Comment by vtraag** [comment]
I would agree to make all `igraph_i` functions private, in principle.

**Comment by ntamas** [comment]
I can comment on a few of these:

* The feedback arc set related stuff is used by the Sugiyama layout, which is in a different compilation unit. If we move them from `igraph_structural.h`, we need to create a private header that can be included by the Sugiyama layout (which is totally okay for me).

* `igraph_i_bfs` is also referenced from `layout.c` so the same considerations apply. Plus, it is referenced from one of the test cases explicitly, which could pose a problem on Windows - we need to export `igraph_i_bfs` from the DLL explicitly to make it possible to link to this function on Windows, so we would also need to re-write the test there not to call `igraph_i_bfs()` directly (which could be feasible, I haven't checked).

* The sparse matrix related stuff (`igraph_i_spmatrix`, `igraph_i_sparsemat`) seem to be internal indeed, I have no idea why they are in the public header.

**Comment by ntamas** [comment]
General point: considering that these functions have been marked as _internal_ from the beginning of time, anyone who happened to use these in her own code should have known what she (he? which one is correct? :)) was doing and what complications it might cause if we ever decide to pull these from the public API or to change their signature. So I'm also okay with removing these from the public headers.

**Comment by iosonofabio** [comment]
Right, that's a good point. I agree keeping `igraph_i_` functions in the public API is counterproductive.

`igraph_i_bfs` seems like a quicker and less flexible version of `igraph_bfs`. I'd be in favour of renaming it and keeping it public, as it might be useful.

**Comment by szhorvat** [comment]
In #1451 it is noted that `igraph_i_bfs` is used from the Python interface. What do we do with that @ntamas ? I will make a note in the top post so we wouldn't forget.

Note that currently it doesn't have the DECLDIR so it can only be used with static linking.

**Comment by szhorvat** [comment]
`igraph_i_sparsemat_view()` is used by the R interface: https://github.com/igraph/rigraph/blob/a14fc50abf9bf3ae17b870ccbc21f88d0eefed6e/tools/stimulus/rinterface.c.in#L2972

**Comment by szhorvat** [comment]
Beware that GitHub search is not reliable, and does not find `igraph_i_bfs` in the python-igraph repo: https://github.com/igraph/python-igraph/search?q=igraph_i_bfs

It is actually used here:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/graphobject.c#L9687

**Comment by szhorvat** [comment]
Issue #1521 is related, and can be fixed concurrently with this one. The fix to both involves creating header files for internal functions.

**Comment by ntamas** [comment]
The usage of `igraph_i_sparsemat_view()` in the R interface presents a totally valid use-case for the function; external high-level interfaces may avoid copying a sparse matrix if they can somehow ensure that the internal representation is consistent with what `igraph_sparsemat_t` uses. This could even be useful for the Python interface if we ever decide to support SciPy sparse matrices. I vote for exposing this function in the public API, just like `igraph_vector_view()` is exposed. Of course we need to warn the user that the corresponding `igraph_sparsemat_t` should not be destroyed then.

**Comment by szhorvat** [comment]
@ntamas :

 1. Can you check if the Python interface uses any of these except `igraph_i_bfs`?
 2. What do we do with `igraph_i_bfs`? Do you want to rename it before 0.9 or leave as is for the moment?
 3. Do you want to rename `igraph_i_sparsemat_view` before 0.9 and if yes, can you do it?

**Comment by ntamas** [comment]
I think that `igraph_i_bfs()` should be renamed to `igraph_bfs_simple()` and exported. It is clearly useful as a simplified variant of `igraph_bfs()` when one only needs minimal information about the result of the traversal but does not need any of the more advanced functionality that `igraph_bfs()` offers.

`igraph_i_sparsemat_view()` will be dealt with soon; it will be exposed as `igraph_sparsemat_view()`. The old name will be kept in the headers and marked as deprecated.

**Comment by ntamas** [comment]
`igraph_i_sparsemat_view()` is now public in e7e8de3fe; `igraph_set_attribute_table()` is also public in 361fa0e01

**Comment by ntamas** [comment]
`igraph_i_bfs()` is now renamed to `igraph_bfs_simple()` in 13c2ed6a5 and is now part of the public API.
