### ISSUE TITLE
igraph_community_edge_betweenness segfaults on graph with zero edges

### ISSUE THREAD

**Issue by nograpes** [igraph/igraph#1311]
If the function `igraph_community_edge_betweenness` is called on a graph with zero edges, it crashes when attempting to `free` and `invalid pointer`. Here is a reproducible example:

```
#include <igraph.h>

int main(void)
{
    igraph_t g;
    igraph_vector_t eb;
    igraph_vector_t res;

    igraph_full(&g, 1, 0, 0);
    igraph_vector_init(&res, igraph_ecount(&g));
    igraph_vector_init(&eb, igraph_ecount(&g));

    igraph_community_edge_betweenness(&g, 
        &res, // result
        &eb, // edge_betweenness result
        NULL, // merges result
        NULL, // bridges
        NULL, // modularity
        NULL, // membership
        IGRAPH_UNDIRECTED, // directed
        NULL // weights
        );    

    igraph_vector_destroy(&eb); // crashes here
    igraph_vector_destroy(&res);
    igraph_destroy(&g);

}
```

I believe that memory corruption is caused by indexing an array at -1, which leads to invalidating a pointer. This will cause a segfault when `free` is called on the invalid pointer. 

I believe this is the ultimate cause of  igraph/rigraph#336 segfault in the R interface.

**Comment by nograpes** [comment]
Notably, I cannot reproduce this bug on MacOS.

**Comment by szhorvat** [comment]
> Notably, I cannot reproduce this bug on MacOS.

Just because it doesn't segfault doesn't mean it's not buggy.
