### ISSUE TITLE
All graph generators should check their input for validity

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1322]
There are multiple graph generators that currently do not check their input for validity.

These need to be fixed:

 - [x] `callaway_traits_game`
 - [x] `establishment_game`

The following functions have been verified to check their arguments properly:

```
forest_fire_game
```

Please update the lists above as you verify functions or find new ones with problems.

This is marked as "good first issue" because the fixes are usually small and relatively easy, but they are sometimes time-consuming: one needs to read up on and understand the random graph model.

**Comment by szhorvat** [comment]
@YasirKusay, if you're looking for something very easy, but somewhat boring, you can check some of these.

**Comment by siddharth25pandey** [comment]
In which file the multiple graph generator is present?

**Comment by vtraag** [comment]
The graph generation is implemented in [`src/games.c`](https://github.com/igraph/igraph/blob/master/src/games.c).

**Comment by siddharth25pandey** [comment]
What changes we have to do in callaway_traits_game & establishment_game functions?

**Comment by szhorvat** [comment]
Most of the work is not writing code here, but understanding precisely what each function does, thinking about what is valid and invalid input, and checking if the function already verified the input.

**Comment by szhorvat** [comment]
The list in the OP is not exhaustive. It contains functions for which it was confirmed that checks are missing. There are certainly several other functions.

To take `igraph_callaway_traits_game`, it is obvious from the code that there are no checks, and there is even a TODO note.

If you look at the [docs](https://igraph.org/c/doc/igraph-Generators.html#igraph_callaway_traits_game), a few obvious things that should be checked that jump to mind:

 - `type_dist` and `pref_matrix` size consistent with number of types (`types`)?
 - `type_dist` entires non-negative? Are zero entires okay or not (to be determined)?
 - same as above for `pref_matrix` entires
 - `pref_matrix` symmetry consistent with `directed`?
 - okay to have `types == 0` or not?
 - etc.

This would require much more careful thought, of course.

If you would like to contribute, it will be very welcome @siddharth25pandey . I'd suggest to review the function and write a list of requirements (similar to the above, but properly checked) before implementing the checks.

**Comment by vtraag** [comment]
By the way, @siddharth25pandey, feel free to open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) so that we can assist you while coding.  It is not necessary to first try to finish everything before opening a PR. If you have any difficulties, feel free to ask here for any support!

**Comment by StutiV** [comment]
Hello, @vtraag . I'd like to contribute to this issue. Can I get some guidance?

**Comment by szhorvat** [comment]
@StutiV Most of the work that needs to be done to resolve this issue does not involve programming. Instead, we need to go through the existing functions, see whether they check their arguments, and if not, decide what checks are necessary. 

If you would like to contribute to this issue, start by choosing a function (e.g. `igraph_establishment_game`), then:

 - Read its documentation and understand what it does
 - Write down what checks are necessary

Then we can go from there and implement the checks.

Alternatively, skim through the source and identify functions which lack checks. Note which those functions are in this issue.

**Comment by szhorvat** [comment]
@StutiV If you are looking for tasks that require more actual programming, but is still very simple, check out #1585

**Comment by GroteGnoom** [comment]
The mentioned functions are fixed, and the graph generators in general don't seem to require special attention anymore.
