### ISSUE TITLE
MSVC igraphtest Target Machine

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1323]
For some reason, for the 64-bits Configuration of the MSVC `igraphtest` project, the `Target Machine` is set to `MachineX86`, which should then be manually updated to `MachineX64` to get it working properly. This should preferably be corrected.

**Comment by szhorvat** [comment]
Is this obsolete now, and can it be closed?

**Comment by ntamas** [comment]
Yes, it is not relevant any more once we switch to CMake (the `igraphtest` project will be gone).
