### ISSUE TITLE
Find an Eulerian cycle

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1325]
[An Eulerian](https://en.wikipedia.org/wiki/Eulerian_path) cycle is a [graph cycle](https://en.wikipedia.org/wiki/Cycle_(graph_theory)) that traverses every edge precisely once.

This is a feature request to compute an Eulerian cycle if one exists.

Would be nice to also have: enumerate *all* Eulerian cycles.

Consider undirected/directed, simple/multigraphs separately.

References:

 - https://en.wikipedia.org/wiki/Eulerian_path#Constructing_Eulerian_trails_and_circuits
 - https://www.geeksforgeeks.org/eulerian-path-and-circuit/
 - https://www.geeksforgeeks.org/fleurys-algorithm-for-printing-eulerian-path/

**Comment by szhorvat** [comment]
@YasirKusay This is also for you, in case you are interested.

**Comment by YasirKusay** [comment]
An interesting issue. Would you like me to just compute an eulerian cycle or one that also can handle eulerian paths?

**Comment by szhorvat** [comment]
This is just an idea at this point: it's up to you whether you want to do it and how far you want to go. I was simply posting project ideas that I am personally interested in but have no time for at the moment.

**Comment by YasirKusay** [comment]
Thats ok, I have just finished writing a solution for it and am in the process of testing it. I have based most of my code on the solution on the code on geeks for geeks links but I decided that rather than using their method of determining if an edge is a bridge, I simply called igraph_bridges.

**Comment by YasirKusay** [comment]
Hello,
I have finished writing up an implementation for undirected graphs that appears to work for both eulerian circuits and paths. I will now attempt one for directed graphs.

**Comment by szhorvat** [comment]
That's great! Feel free to open a new pull request even before it's fully finished and mark it as a "draft". Then we can comment on your code early. Be sure to only include these changes in the PR, not any other changes you made earlier.

**Comment by YasirKusay** [comment]
I'll do that once a do a few more tiny checks. Would you like me top include my code in src/structural_properties.c?
