### ISSUE TITLE
Where is the "IGRAPH_THREAD_LOCAL" defined?

### ISSUE THREAD

**Issue by AIBluefisher** [igraph/igraph#1329]
Please **do not** use the issue tracker for personal support requests -- use our
[Discourse group](https://igraph.discourse.group) instead.

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

Hi, @shlomif 
I'm using cmake to config the `igraph` library. However, the compiler reports an error for not finding the 'IGRAPH_THREAD_LOCAL' macro. 
```sh
error: ‘IGRAPH_THREAD_LOCAL’ does not name a type
 static IGRAPH_THREAD_LOCAL unsigned int count[256] = {
```
I reviewed the code and didn't find that macro except the config.h.in. Could you help me?

**Comment by szhorvat** [comment]
We would prefer to reserve the issue tracker for bug reports and feature requests. Please post support questions to https://igraph.discourse.group/ instead.

igraph uses autotools as its build system, not cmake. You need to run `./configure` before igraph can be built. The options `--enable-tls` and `--disable-tls` control `IGRAPH_THREAD_LOCAL`

Detailed installation instructions are at https://igraph.org/c/
