### ISSUE TITLE
Tests must be fixed for MinGW-w64

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1337]
The following tests currently fail with MinGW-w64:

193. community.at:86: testing Leiden community detection (igraph_community_leiden) :

```
-Leiden found 3 clusters using modularity, quality is 0.2812.
+Leiden found 3 clusters using modularity, quality is 0.2813.
```

I am surprised that numerical stability would be this bad. Perhaps it's just a coincidence (quality is really close to 0.23130)? Opinions, @vtraag ?

252. scg.at:71: testing SCG of a graph, stochastic matrix (igraph_scg) :

```
@@ -44,10 +44,10 @@
 2 3 1 2 4 4 4 0 0 0
 ---
 0.866025+0i
--3.14295e-16+0i
+-3.14295e-016+0i
 0.316228+0i
 -0.316228+0i
--3.26134e-16+0i
+-3.26134e-016+0i
 0.365148+0i
 0.365148+0i
 0.365148+0i
@@ -106,10 +106,10 @@
 2 3 1 2 4 4 4 0 0 0
 ---
 1+0i 0.866025+0i
--0.316228+0i -3.14295e-16+0i
+-0.316228+0i -3.14295e-016+0i
 -0.316228+0i 0.316228+0i
 -0.316228+0i -0.316228+0i
--0.316228+0i -3.26134e-16+0i
+-0.316228+0i -3.26134e-016+0i
 -0.316228+0i 0.365148+0i
 -0.316228+0i 0.365148+0i
 -0.316228+0i 0.365148+0i
```

This one is just about printing complex numbers as `123e+16` vs `123e+016`

**Comment by ntamas** [comment]
Looks like we would need to brew our own floating-point number printer function in `test_utilities.inc` that ensures a consistent formatting in all supported platforms. Right now these inconsistencies make it a bit hard to rely on `.out` files in the test cases to store the expected output. I cannot believe that no one else has come up with a portable solution for the problem so far.

**Comment by vtraag** [comment]
@szhorvat, regarding the difference I don't immediately know whether it is a numerical error, while the underlying partition result is identical, or whether there is actually a different partition with an (almost) identical quality. I don't have access to a Windows computer today, I will try to check later this week.

**Comment by iosonofabio** [comment]
Is this still open? #1401 also refers to the same platform so maybe we should fix them together?

**Comment by vtraag** [comment]
I haven't taken a look recently to it. I don't have much time these weeks (have to finish some stuff before holidays--and then actual holidays :-)), so I will probably not get around to it shortly.

**Comment by vtraag** [comment]
It seems that the problem for `igraph_community_leiden` is a problem with inconsistent rounding across platforms (see https://www.exploringbinary.com/inconsistent-rounding-of-printed-floating-point-numbers/ for an overview). The exact result is 0.28125, which gets rounded to 0.2813 on Windows ([rounding half away from zero](https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero)), but gets rounded 0.2812 on *nix ([rounding half to even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even)). I will push a PR correcting the problem shortly.
