### ISSUE TITLE
--with-external-arpack does not detect that ARPACK is not available

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1350]
When I tried to compile using `--with-external-arpack`, I got a linked error at the very end:

```
ld: library not found for -larpack
```

Ideally, the `./configure` step would have detected that ARPACK was missing.

This is on macOS.

**Comment by ntamas** [comment]
Same on other platforms; I guess that we trust what the user is doing and we don't check whether the libraries we need to link to indeed exist on the user's system.
