### ISSUE TITLE
Make GMP non-optional

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1351]
GMP is extremely useful for graph theory, and I have already done some work I want to contribute that relies on it.

We should make GMP be non-optional. Currently, the only user of GMP is Bliss, which falls back to using a `long double` (i.e. an ugly hack) when GMP is not available.

For the eventuality that an external GMP is not available, we can bundle "mini-gmp". mini-gmp comes with GMP and is intended exactly for this purpose. Quoting from its README file:

> This is "mini-gmp", a small implementation of a subset of GMP's mpn,
> mpz and mpq interfaces.
> 
> It is intended for applications which need arithmetic on numbers
> larger than a machine word, but which don't need to handle very large
> numbers very efficiently. **Those applications can include a copy of
> mini-gmp to get a GMP-compatible interface with small footprint. One
> can also arrange for optional linking with the real GMP library, using
> mini-gmp as a fallback** when for some reason GMP is not available, or
> not desired as a dependency.

It consists of only two `.h` and two `.c` files.

If we go this route, eventually we can also get rid of igraph's own bignum implementation, and replace it with GMP. GMP may provide much better performance. GMP is continually being developed: it received bugfixes and performance improvements. We don't want to keep maintaining igraph's bignum if we don't have to.

**Comment by vtraag** [comment]
This sounds very useful @szhorvat ! Would `mini-gmp` also provide an alternative to `MPIR` on Windows? Or does that not work? 

I agree that it would be preferable to rely on an externally maintained library over something that should be maintained by us.

**Comment by szhorvat** [comment]
> Would `mini-gmp` also provide an alternative to `MPIR` on Windows? Or does that not work?

Would work, but not a good idea because it does not have good performance.

At this moment, this is not a problem because we do not yet use GMP in any performance-critical way. But later it will be.

**Comment by vtraag** [comment]
> At this moment, this is not a problem because we do not yet use GMP in any performance-critical way. But later it will be.

OK, so in the end we will then have a (non-optional) dependency on `GMP` on Linux/macOS, with `mini-GMP` as a backup, and `MPIR` on Windows? Would using `MPIR` for all platforms and having `mini-GMP` as a backup be easier?

**Comment by szhorvat** [comment]
> Would using `MPIR` for all platforms and having `mini-GMP` as a backup be easier?

I don't think it makes any difference. MPIR is basically indistinguishable from GMP to the program that uses it. If it is compiled with `--enable-gmpcompat`, it produces a `gmp.h`, `libgmp` library, etc.  igraph doesn't need to know about MPIR at all. It just needs to look for GMP, and doesn't have to care if what it finds is not the original, just a lookalike.

**Comment by ntamas** [comment]
Fixed by #1549.
