### ISSUE TITLE
i_graph (weighted) nearest neighbor degree/strength; ref#987/#1214

### ISSUE THREAD

**Issue by MF-git** [igraph/igraph#1354]
#987 and #1051 argue igraph_(weighted)_nearest_neighbor_degree is not inline with Barrat et.al (2004); #1214 claims problem fixed 

looks like weighted-knn still gives: 
knn^w[nn,i] = 1/(s[i]) * sum a[ij]*w[ij]***s**[j] (weighted nearest neighbor strenght)

instead of Barrat's formulation:
knn^w[nn,i] = 1/(s[i]) * sum a[ij]*w[ij]***k**[j] (weighted nearest neighbor degree)

this leads to knn[nn,i]<knn^w[nn,i] for all nodes i with degree k=1 - but should be knn[nn,i]=knn^w[nn,i] 

would be desirable to get Barrat's formulation implemented

**Comment by szhorvat** [comment]
Which version of igraph are you using?

**Comment by MF-git** [comment]
1.2.4.2

**Comment by szhorvat** [comment]
That is the version number of the R interface. This is the repository of the C core of igraph, where this issue was fixed.  The R interface has not yet been updated to the latest C core, but [eventually it will be](https://github.com/igraph/rigraph/pull/372).

**Comment by MF-git** [comment]
Sorry and thanks anyway!
Any idea on update date?

Best,
MF

**Comment by szhorvat** [comment]
Personally I don't know as I have not been working on the R interface, but you can follow the work in the PR I linked to.

**Comment by MF-git** [comment]
Thanks again!

Sendt fra min BlackBerry – den sikreste mobilenheten
Fra: notifications@github.com
Sendt: 4. mars 2020 21:29
Til: igraph@noreply.github.com
Svar til: reply@reply.github.com
Kopi: Falko.Muller@himolde.no; author@noreply.github.com
Emne: Re: [igraph/igraph] i_graph (weighted) nearest neighbor degree/strength; ref#987/#1214 (#1354)


Personally I don't know as I have not been working on the R interface, but you can follow the work in the PR I linked to.
