### ISSUE TITLE
Implement directed modularity

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1358]
`igraph_modularity` should support directed graphs.

@vtraag I need your input on whether there are multiple variations on this concept.

**Comment by vtraag** [comment]
I am only familiar with the definition provided by [Leicht and Newman (2008)](https://doi.org/10.1103/PhysRevLett.100.118703), Eq. (3), and I haven't come across any other definition. This is also the definition that makes most sense, which should be straightforward to implement. Similar adjustments need to be made for the weighted case, but these are again quite straightforward. I'll put it on my list.
