### ISSUE TITLE
Documentation: DECLRDIR should not be included in prototoype

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1360]
Ideally, `DECLDIR` should not be included in prototypes in the documentation.

This is one example where it is included:

https://igraph.org/c/doc/igraph-Error.html#igraph_warning

![image](https://user-images.githubusercontent.com/1212871/76168599-9fe4eb80-6171-11ea-8c60-33b9cace721c.png)

Is this easy to fix @ntamas ?

**Comment by ntamas** [comment]
![Hopefully yes, I'll look into this.](https://cdn-media-1.freecodecamp.org/images/1*w-_7zxjx3gZgx_rLNVq60A.png)

**Comment by ntamas** [comment]
Done; it will be fixed "properly" in 0.8.1 (I have updated `docs/c-docbook.re` to strip DECLDIR from declarations), until then I just patched the docs on the homepage.

**Comment by szhorvat** [comment]
Thanks for the quick fix!

A small undesired effect is that it will cause the argument list not to be as nicely aligned as it was.

If it was

```
DECLDIR int fun(int x,
                int y);
```

it will become

```
int fun(int x,
                int y);
```

But I think this should be the smallest of our concerns right now.

**Comment by ntamas** [comment]
Unfortunately fixing that is beyong my regex-fu at the moment :)
