### ISSUE TITLE
Documentation: misformatted sections

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1361]
This part of the documentation is misformatted. It's unclear to me what's wrong.

https://igraph.org/c/doc/igraph-Data-structures.html#VECTOR

![image](https://user-images.githubusercontent.com/1212871/76168789-1f26ef00-6173-11ea-8062-ff1336442af3.png)

**Comment by szhorvat** [comment]
Doc comment is here:

https://github.com/igraph/igraph/blob/master/include/igraph_vector_pmt.h#L43

Removing the indent does not help.

**Comment by ntamas** [comment]
It does help, you just need to be sure that there is a space before the `*` from the second line onwards.
