### ISSUE TITLE
igraph_lattice creates a 1-vertex graph with empty dimvector

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1367]
I am not yet sure whether to call this a bug or not. In any case, it should be documented.

`igraph_lattice` will create a zero-vertex graph if given a dimvector like `(0,0)` or `(0)`. This is fine.

But it creates a one-vertex graph if given an empty dimvector `()`.

Do you think this behaviour is correct? Should it be changed, or should it be documented? I'd probably just document it because it is an edge case that has no one clear solution.

One argument for the current behaviour: with a dimvector `list = (d_1, d_2, ..., d_n)`, the number of vertices is `prod(list) = d_1 * d_2 * ... * d_n`. What is the product of elements of an empty list? It makes sense to use the identity element of multiplication, in order to satisfy the relation `prod(list1) * prod(list2) = prod(concatenate(list1, list2))`.

Now that I've written this down, I think I convinced myself that the current behaviour is the best one. Any objections to documenting it?

**Comment by ntamas** [comment]
Nope, please go ahead. I think your reasoning is correct; this is probably what's going on behind the scenes anyway.
