### ISSUE TITLE
Test failures with x87 floating point arithmetic

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1371]
Splitting off part of #1370, this issue is for test failures when using x87 arithmetic. 

I can reproduce these on macOS 64-bit (so no 32-bit system needed!), as follows:

I use gcc, not clang. I used gcc from MacPorts. Before running `./configure`, set

```
export CC=gcc-mp-9
export CXX=g++-mp-9
export CXXFLAGS="-mfpmath=387 -O2" CFLAGS="-mfpmath=387 -O2"
```

If you do not use MacPorts, or you are on a different OS, you will need to adjust the compiler names (`CC` and `CXX` lines above).

I did try [`-mfpmath=387 -mno-sse` with clang](https://stackoverflow.com/q/22581350/695132), but I am getting `error: SSE register return with SSE disabled` during compilation.

Failures:

```
129: Merging layouts 2 (igraph_i_layout_merge):      FAILED (layout.at:69)
196: Infomap community structure (igraph_community_infomap) : FAILED (community.at:101)
223: Solving linear systems with LU factorization (igraph_lapack_dgesv): FAILED (arpack.at:48)
238: Missing edge prediction (igraph_hrg_predict) :  FAILED (hrg.at:36)
247: Solving the SCG problem, stochastic matrix (igraph_scg_grouping) : FAILED (scg.at:39)
250: SCG semi-projectors, stochastic (igraph_scg_semiprojectors) : FAILED (scg.at:57)
253: SCG of a graph, stochastic matrix (igraph_scg) : FAILED (scg.at:73)
```

Full test output is here:

[testsuite.dir.zip](https://github.com/igraph/igraph/files/4487174/testsuite.dir.zip)

**Comment by AdrianBunk** [comment]
Works with gcc. All x86_64 CPUs support SSE2, so noone would really care whether clang supports x87 there. "-m32 -mfpmath=387" works with clang if the 32bit libraries are installed.

**Comment by szhorvat** [comment]
@gaborcsardi Would you be able to look at the SCG ones, since none of us have much familiarity with that yet?

**Comment by gaborcsardi** [comment]
They are probably just numeric precision failures, so just increase precision, or allow the "new" result as well.

**Comment by ntamas** [comment]
Made quite a few changes to test cases recently (tests are now fixed on i386 in Debian) - maybe these got solved as well.

**Comment by szhorvat** [comment]
There is one remaining failure,

```
223: Solving linear systems with LU factorization (igraph_lapack_dgesv): FAILED (arpack.at:48)
```

`testsuite.log`:

```
#                             -*- compilation -*-
223. arpack.at:45: testing Solving linear systems with LU factorization (igraph_lapack_dgesv): ...
./arpack.at:48: ${CC} ${CFLAGS} ${abs_top_srcdir}/examples/simple/igraph_lapack_dgesv.c -I${abs_top_srcdir}/include -I${abs_top_builddir}/include -L${abs_top_builddir}/src/.libs -ligraph -lm  -o itest
./arpack.at:48: cat ${abs_top_srcdir}/examples/'simple/igraph_lapack_dgesv.out' | sed "s/@VERSION@/$(cat ${abs_top_srcdir}/IGRAPH_VERSION)/g" > expout
./arpack.at:48: 
./arpack.at:48: DYLD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${DYLD_LIBRARY_PATH+:$DYLD_LIBRARY_PATH} LD_LIBRARY_PATH=${abs_top_builddir}/src/.libs${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH} ./itest
--- expout	2020-04-20 16:25:08.000000000 +0200
+++ /Users/szhorvat/Repos/igraph-c/igraph/tests/testsuite.dir/at-groups/223/stdout	2020-04-20 16:25:08.000000000 +0200
@@ -1 +1 @@
-Warning: LU: factor is exactly singular
+LAPACK returned info = 0, should have been 10
\ No newline at end of file
./arpack.at:48: exit code was 7, expected 0
223. arpack.at:45: 223. Solving linear systems with LU factorization (igraph_lapack_dgesv): (arpack.at:45): FAILED (arpack.at:48)
```

**Comment by ntamas** [comment]
_*sigh*_

This failure is due to the fact that the LU factorization solver does not recognize a random singular matrix (two rows are intentionally set to the same values) with the limited floating point precision offered by the x87 instruction set. I'm not really sure what to do with it.

I don't think that we really need to test the LU solver here - that would be the job of the LAPACK variant that provides the LU solver. We only need to test that `igraph_lapack_dgesv()` responds correctly to the error code returned by the LU solver. I propose that we simplify the test case to a deterministic singular matrix that does not cause problems even with the x87 arithmetics -- say, a matrix with a zero column or row. What do you think @szhorvat?

**Comment by szhorvat** [comment]
> This failure is due to the fact that the LU factorization solver does not recognize a random singular matrix (two rows are intentionally set to the same values) with the limited floating point precision offered by the x87 instruction set.

Doesn't x87 provide *higher* precision, 80 bits instead of 64 bits? I thought it always worked with 80 bit registers internally, but maybe I'm wrong.



> I don't think that we really need to test the LU solver here - that would be the job of the LAPACK variant that provides the LU solver.
> ...
> I propose that we simplify the test case to a deterministic singular matrix that does not cause problems even with the x87 arithmetics

I think this would be fine.

**Comment by ntamas** [comment]
Committed a patch to the LU solver test case, FYI. Can you check whether it still fails for you?

**Comment by szhorvat** [comment]
> Can you check whether it still fails for you?

It does not fail now.
