### ISSUE TITLE
Test failures with external BLAS, LAPACK

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1372]
Another followup for #1370

I get test failures when compiling using

```
./configure --with-external-blas --with-external-lapack --with-external-arpack
```

Failures:

```
129: Merging layouts 2 (igraph_i_layout_merge):      FAILED (layout.at:69)
253: SCG of a graph, stochastic matrix (igraph_scg) : FAILED (scg.at:73)
```

I am not able to separate these options and still compile successfully on macOS.

Full test output:

[testsuite.dir.zip](https://github.com/igraph/igraph/files/4487698/testsuite.dir.zip)

<details><summary>System information</summary>

macOS 10.14

Compiler:

```
~ $ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
```

Packages are from MacPorts. Versions:
```
arpack @3.7.0
lapack @3.9.0
OpenBLAS @0.3.9
```
</details>

**Comment by szhorvat** [comment]
Correction: `--with-external-arpack` can be omitted. The failures will be the same.

**Comment by ntamas** [comment]
I have even more failures on my Mac; I'll start working on this and sort a few of these out, let's see what remains.

**Comment by ntamas** [comment]
The failures reported by @szhorvat are now fixed in the develop branch (at least on my machine). However, test cases 247 (`Solving the SCG problem, stochastic matrix (igraph_scg_grouping)`) and 250 (`SCG semi-projectors, stochastic (igraph_scg_semiprojectors)`) also fail on my machine so I keep this open for the time being.

**Comment by szhorvat** [comment]
@ntamas I think all is good here and can be closed, right?

**Comment by ntamas** [comment]
Yes :)
