### ISSUE TITLE
Test failures with -ffast-math

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1374]
Some tests fail when compiling with `-ffast-math`. Which ones fail precisely depends on the compiler used, and the specific compiler options (e.g. `-march`). The following is with:

```
~ $ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
```

and all defaults except adding `-ffast-math` to `CFLAGS` and `CXXFLAGS`.

Of course `-ffast-math` is non-compliant, but the fact that some tests fail with it can indicate true problems with the code, or just that the tests are not sufficiently robust.

```
61: Preference model (igraph_preference_game):      FAILED (structure_generators.at:61)
246: Solving the SCG problem, adjacency matrix (igraph_scg_grouping) : FAILED (scg.at:33)
247: Solving the SCG problem, stochastic matrix (igraph_scg_grouping) : FAILED (scg.at:39)
250: SCG semi-projectors, stochastic (igraph_scg_semiprojectors) : FAILED (scg.at:57)
```

With `-march=native -O3` I got `96 247 250 264 failed`, just to illustrate which tests may be volatile.

For now, just attaching results; I'll take a more detailed look later.

This is based on latest `master` right now, b3709fb8812baeba7bcc0f97262c309db4a94358

[testsuite.dir.zip](https://github.com/igraph/igraph/files/4504312/testsuite.dir.zip)

**Comment by szhorvat** [comment]
Hm, `61` was actually a crash ...

**Comment by ntamas** [comment]
`-ffast-math` does [quite a few scary things](https://stackoverflow.com/a/22135559/156771) but it definitely shouldn't crash the library. I'll take a closer look at these, though.

**Comment by szhorvat** [comment]
Just a note that today I built igraph with `-fsanitize=address -O2 -ffast-math` to try to figure out what crashes in `61` (without `-O2`, test 61 passes). This time it didn't crash, but the memory usage kept increasing without bound, quickly exhausting by 16 GB.

**Comment by ntamas** [comment]
Same as what I saw when building with `-ffast-math`. I think that the edge list of the graph being generated keeps growing; the algorithm might be generating the same edge over and over again. I think this is the only issue that we should really be worried about -- the other test failures seem to be using heavy math-dependent routines from BLAS / LAPACK / ARPACK that probably rely on "proper" IEEE arithmetics to guarantee certain properties.

(For what it's worth, the only crash I saw when building igraph with `-ffast-math` _but_ external BLAS / LAPACK / ARPACK was the one in test 61).

**Comment by vtraag** [comment]
You all seem to be much more aware of the details of the various CPU architectures than I am. But in the previous discussion on problems with external packages in issue #678, we came to the conclusion that at least some tests involved a limited set of eigenvectors from a degenerate subspace. I'm not sure whether it is possible to guarantee consistent output of such eigenvectors across all architectures and external packages and "proper" IEEE arithmetics. It might then be preferable to only check the resulting eigenvalues (which are correct), not the eigenvectors themselves (which might change).

**Comment by szhorvat** [comment]
For verifying an eigenvector `v` of a matrix `A`, the most reasonable thing is probably to check that `A.v == something * v`.
