### ISSUE TITLE
igraph_lattice: granular periodicity control

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1375]
This is a proposal to either introduce a new function or generalize `igraph_lattice` (IMO preferred) to provide granular control of periodicity.

`igraph_bool_t circular` could be changed to an `igraph_vector_bool` of the same length as `dimvector`. This would control periodicity independently along each direction.

Downside: it will be more complicated for the C interface used to construct this function argument for simple cases.

The `mutual` argument could be generalized too.

----

A marginally related suggestion is to also rename `igraph_lattice` to `igraph_square_lattice` or similar (what's the general name that covers multidimensional cases?). The documentation says, "Creates most kinds of lattices". Well, it doesn't create triangular or hexagonal lattices, or the many kinds of possible regular 3D lattices.

**Comment by ntamas** [comment]
@szhorvat I'm trying to decompose this into actionable items; would something like this suffice? (These are checklist items for a full implementation)

[ ] Add `igraph_rectangular_lattice()` with an API similar to `igraph_lattice()` but using a bool vector for periodicity control. Passing `NULL` to the periodicity vector will mean no periodicity along any of the dimensions.
[ ] Add `igraph_circular_rectangular_lattice()` as a shortcut to calling `igraph_rectangular_lattice()` with an all-true circularity vector.
[ ] Make `igraph_lattice()` call `igraph_rectangular_lattice()` with the appropriate arguments, and mark it as deprecated in 0.10
[ ] Remove `igraph_lattice()` in 0.10 or convert it into a generic high-level entry point for lattices in general (if we add more lattice generators until then).

**Comment by szhorvat** [comment]
Yes, it looks fine to me.

Please call it "periodic", not "circular". I find "circular" confusing. I would also rename the `circular` parameter to `periodic`.

### Minor comment

I would call it `square_lattice` instead of `rectangular_lattice` because this seems to be more common (?), because it's shorter, and because the distinction between "square" and "rectangle" is a geometric one while we're working purely with graphs. But you might argue that both "square" and "rectangle" imply 2D so neither are good. It's not of great importance.

**Comment by ntamas** [comment]
dacb48f7c adds `igraph_square_lattice()` with a provisional API (same as `igraph_lattice()`, but the periodicity argument was changed to an `igraph_vector_bool_t`). I did not add `igraph_periodic_square_lattice()` yet and I'm not convinced that we'd need it -- it's not that hard to create an `igraph_vector_bool_t` and pre-fill it with truthy values. I'm closing this as implemented; if you think we need `igraph_periodic_square_lattice()` as a shortcut, please reopen.

**Comment by szhorvat** [comment]
I think it's fine.
