### ISSUE TITLE
Confusing results of topological_sorting

### ISSUE THREAD

**Issue by ltbyron** [igraph/igraph#1380]
I suppose the topological_sorting function will return a list whose length equals the number of vertices in the graph. However, when I run the following codes I get unexpected results. The behavior is rather confusing. I know the topological order is not unique in general, but I can not find out why this function returns these results. Specifically, maybe the list obtained by mode='IN' should be the reverse of the list obtained by mode='OUT'?

```
>>> g=Graph.Erdos_Renyi(nvt, 0.1, directed=True, loops=False)
>>> print(g)
IGRAPH D--- 10 10 --
+ edges:
6->1 5->2 5->3 2->5 4->5 3->6 9->6 9->7 0->8 6->8
>>> g.topological_sorting(mode='IN')
[1, 7, 8, 0, 6, 3, 9]
>>> g.topological_sorting(mode='OUT')
[0, 4, 9, 7]

```

**Comment by szhorvat** [comment]
This graph is not acyclic, therefore topological sorting makes no sense.

igraph's current behaviour is start the sort, then stop as soon as it finds a cycle and return a partial result:

https://igraph.org/c/doc/igraph-Structural.html#igraph_topological_sorting

>  If the graph is not acyclic (it has at least one cycle), a partial topological sort is returned and a warning is issued. 

Personally, I am not very happy with this behaviour. I would rather have it return an error and no result at all. I guess this is up for discussion.

**Comment by szhorvat** [comment]
When this happens, there should be a warning similar to

> RuntimeWarning: graph contains a cycle, partial result is returned at ...

**Comment by szhorvat** [comment]
P.S. If you are looking for support, please use igraph.discourse.group/ instead of the issue tracker. However, I wanted to discuss this behaviour (returning partial results) anyway, so it's good that there's an issue for it now.

**Comment by vtraag** [comment]
> I would rather have it return an error and no result at all.

I agree that this would make more sense.

**Comment by ltbyron** [comment]
Thanks a lot for your reply! I thought it was a bug so I opened an issue here. In fact, I didn't get any warning, so I didn't realize that the graph is not a DAG. Personally, I prefer the function to return an error when the input graph is not a DAG.

Thanks again for your contribution!

**Comment by szhorvat** [comment]
@ltbyron Which version are you using (hopefully 0.8.x) and in what environment (command line, notebook, IDE, etc.)?

**Comment by ltbyron** [comment]
@szhorvat  I'm using version 0.8.2, in the command line. I notice that if the arg `mode` is not specified, it will return a warning message, but if I set `mode='IN'` or `mode='OUT'` there is no warning message.

```
>>> g = igraph.Graph.Erdos_Renyi(10,0.1,directed=True, loops=False)
>>> print(g)
IGRAPH D--- 10 6 --
+ edges:
8->2 4->3 9->3 7->9 2->8 3->8
>>> g.topological_sorting()
__main__:1: RuntimeWarning: graph contains a cycle, partial result is returned at /Users/runner/miniforge3/conda-bld/python-igraph_1588168269090/work/vendor/source/igraph/src/structural_properties.c:3448
[0, 1, 4, 5, 6, 7, 9, 3]
>>> g.topological_sorting(mode='IN')
[0, 1, 5, 6]
>>> g.topological_sorting(mode='OUT')
[0, 1, 4, 5, 6, 7, 9, 3]
```

**Comment by szhorvat** [comment]
@ltbyron It's not a `mode` argument thing. The underlying C function will always issue the warning, regardless of `mode`. 

But for some reason, if I use plain Python from the command line, the warning is printed only the first time it is issued.

```
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from igraph import *
>>> g = Graph.Erdos_Renyi(10,0.2,directed=True, loops=False)
>>> g.topological_sorting()
<stdin>:1: RuntimeWarning: graph contains a cycle, partial result is returned at /Users/runner/miniforge3/conda-bld/python-igraph_1588168241529/work/vendor/source/igraph/src/structural_properties.c:3448
[2, 6, 9, 8]
>>> g.topological_sorting()
[2, 6, 9, 8]
>>> g.topological_sorting()
[2, 6, 9, 8]
>>> g.topological_sorting()
[2, 6, 9, 8]
>>> 
```

If I use IPython, it is printed every time.

```
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from igraph import *                                                    

In [2]: g = Graph.Erdos_Renyi(10,0.2,directed=True, loops=False)                

In [3]: g.topological_sorting()                                                 
<ipython-input-3-b8d21865468c>:1: RuntimeWarning: graph contains a cycle, partial result is returned at /Users/runner/miniforge3/conda-bld/python-igraph_1588168241529/work/vendor/source/igraph/src/structural_properties.c:3448
  g.topological_sorting()
Out[3]: [2]

In [4]: g.topological_sorting()                                                 
<ipython-input-4-b8d21865468c>:1: RuntimeWarning: graph contains a cycle, partial result is returned at /Users/runner/miniforge3/conda-bld/python-igraph_1588168241529/work/vendor/source/igraph/src/structural_properties.c:3448
  g.topological_sorting()
Out[4]: [2]
```

@vtraag @ntamas any ideas if this is an issue with Python or python-igraph?

**Comment by szhorvat** [comment]
@ltbyron I think this is normal behaviour, I'm just not familiar enough with Python

https://stackoverflow.com/questions/22661745/why-only-one-warning-in-a-loop

Apparently you can set it to always issue warnings using

```
import warnings
warnings.simplefilter('always')
```

**Comment by ltbyron** [comment]
@szhorvat Thanks for your reply! With your kind help, I understand the behavior now and I think it's time to close this issue.

**Comment by vtraag** [comment]
Good that it is now clarified! I think we should change the behaviour, and raise an error of it is not a DAG, so I suggest we keep the issue open to fix that.
