### ISSUE TITLE
Create Dash docsets

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1381]
We should make the docs available for [Dash](https://kapeli.com/dash), as discussed before.

On Windows/Linux, Dash docsets can be browsed with the free [Zeal](https://zealdocs.org/).

**Comment by szhorvat** [comment]
BTW Zeal appears to work perfectly well on macOS if you compile it yourself.  I think they don't provide binaries in order not to step on the toes of Dash, which is paid. Noting just in case some of you who are on macOS want to experiment.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1212871/80953151-43155280-8dfb-11ea-84cc-0076c2c7b76a.png">

**Comment by ntamas** [comment]
>  I think they don't provide binaries in order not to step on the toes of Dash,

Yes, there seems to be a [formal agreement](https://github.com/zealdocs/zeal/issues/363#issuecomment-117875015) between the two teams.

**Comment by szhorvat** [comment]
@ntamas Check this out: https://doc2dash.readthedocs.io/en/stable/ Should make it easy for the Python interface.

**Comment by ntamas** [comment]
Thanks, will look into this!

**Comment by ntamas** [comment]
The Dash docset  generator from @szhorvat is now in the [igraph-dash-docset](https://github.com/igraph/igraph-dash-docset) repository. Submission is underway. I believe this issue can be closed once the submission is accepted.
