### ISSUE TITLE
Crash in igraph_feedback_arc_set

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1382]
`igraph_feedback_arc_set` crashed with the `IGRAPH_FAS_EXACT_IP` method with the attached graph.

Reproduced on macOS with the Mathemtica interface (compiled with external GLPK 4.65) as well as with python-igraph 0.8.2 from anaconda. 

The attached file is an edge list of a directed graph, with vertices indexed from 0.

[offending_graph.txt](https://github.com/igraph/igraph/files/4580952/offending_graph.txt)

**Comment by szhorvat** [comment]
On the command line, I see this:

```
glp_add_rows: nrs = 758841790; too many rows
Error detected in file api/prob1.c at line 259
```

This is all fine and reasonable (I never expected the algorithm to finish on this huge graph), but the error should have been caught by igraph, and the abort should have been prevented. We need to look into why this did not happen.

**Comment by szhorvat** [comment]
To prevent this from happening, we need to install a custom error handler using `glp_error_hook()`. This error handler must not return. Instead, it should call `glp_free_env` and then perform a `longjmp`.

**Comment by ntamas** [comment]
A similar issue in [pywr/pywr](https://github.com/pywr/pywr/issues/759); might be interesting to take a look at how they ended up handling this.

One potential issue that we might have is that `glp_free_env()` frees _all_ GLPK resources on its own. If the user is running multiple GLPK problems in parallel (is that possible?), we could be inadvertedly freeing resources related to all of them, not only ours.
