### ISSUE TITLE
Argument check in igraph_modularity looks weird

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1390]
The argument checks in `igraph_modularity` look strange to me:

https://github.com/igraph/igraph/blame/952241efc6ce2db5a3eba111591c0426758951a3/src/community.c#L915

https://github.com/igraph/igraph/blame/952241efc6ce2db5a3eba111591c0426758951a3/src/community.c#L927

Why is `<` used instead of `!=` here? Is there a specific reason, or can we change it to `!=`?

Pinging @ntamas as it seems you wrote this originally.

**Comment by ntamas** [comment]
I have no idea, it was 10 years ago :) Feel free to change this to `!=` if it is consistent with how we do length checks in other places in the library. (If it is not, maybe we should do it consistently everywhere).
