### ISSUE TITLE
Test failures for "Adjacency spectral embedding (igraph_adjacency_spectral_embedding)"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1393]
This test fails both with x87 floating point arithmetic and when compiling on ARM64 (which Travis supports, and which I was experimenting with).

> Adjacency spectral embedding (igraph_adjacency_spectral_embedding)

https://travis-ci.com/github/szhorvat/igraph/jobs/341257350 (this is my personal setup, with ARM64 enabled)

ARM64 diff:

```
@@ -2,20 +2,20 @@
   0.5689   0.7015  -0.4032   0.0000
   0.5689  -0.7015  -0.4032   0.0000
   0.0330   0.0000   0.1302   0.0000
-  0.0320   0.0511  -0.0660   0.1236
-  0.0320   0.0511  -0.0660   0.5430
-  0.0320   0.0511  -0.0660  -0.6667
-  0.0320  -0.0511  -0.0660   0.1819
-  0.0320  -0.0511  -0.0660  -0.4038
-  0.0320  -0.0511  -0.0660   0.2219
+  0.0320   0.0511  -0.0660   0.1642
+  0.0320   0.0511  -0.0660   0.4759
+  0.0320   0.0511  -0.0660  -0.6401
+  0.0320  -0.0511  -0.0660   0.2130
+  0.0320  -0.0511  -0.0660  -0.4731
+  0.0320  -0.0511  -0.0660   0.2601
 --
   0.2914   0.0000   0.6560   0.0000
   0.5705   0.5262  -0.0063   0.0000
   0.5705  -0.5262  -0.0063   0.0000
   0.1997   0.0000   0.4732   0.0000
-  0.1934   0.2727  -0.2400   0.1236
-  0.1934   0.2727  -0.2400   0.5430
-  0.1934   0.2727  -0.2400  -0.6667
-  0.1934  -0.2727  -0.2400   0.1819
-  0.1934  -0.2727  -0.2400  -0.4038
-  0.1934  -0.2727  -0.2400   0.2219
+  0.1934   0.2727  -0.2400   0.1642
+  0.1934   0.2727  -0.2400   0.4759
+  0.1934   0.2727  -0.2400  -0.6401
+  0.1934  -0.2727  -0.2400   0.2130
+  0.1934  -0.2727  -0.2400  -0.4731
+  0.1934  -0.2727  -0.2400   0.2601
264. embedding.at:23: 264. Adjacency spectral embedding (igraph_adjacency_spectral_embedding):  (embedding.at:23): FAILED (embedding.at:25)
```

x87 diff:

```
@@ -2,20 +2,20 @@
   0.5689   0.7015  -0.4032   0.0000
   0.5689  -0.7015  -0.4032   0.0000
   0.0330   0.0000   0.1302   0.0000
-  0.0320   0.0511  -0.0660   0.1236
-  0.0320   0.0511  -0.0660   0.5430
-  0.0320   0.0511  -0.0660  -0.6667
-  0.0320  -0.0511  -0.0660   0.1819
-  0.0320  -0.0511  -0.0660  -0.4038
-  0.0320  -0.0511  -0.0660   0.2219
+  0.0320   0.0511  -0.0660   0.1335
+  0.0320   0.0511  -0.0660  -0.2894
+  0.0320   0.0511  -0.0660   0.1559
+  0.0320  -0.0511  -0.0660  -0.3088
+  0.0320  -0.0511  -0.0660   0.7590
+  0.0320  -0.0511  -0.0660  -0.4502
 --
   0.2914   0.0000   0.6560   0.0000
   0.5705   0.5262  -0.0063   0.0000
   0.5705  -0.5262  -0.0063   0.0000
   0.1997   0.0000   0.4732   0.0000
-  0.1934   0.2727  -0.2400   0.1236
-  0.1934   0.2727  -0.2400   0.5430
-  0.1934   0.2727  -0.2400  -0.6667
-  0.1934  -0.2727  -0.2400   0.1819
-  0.1934  -0.2727  -0.2400  -0.4038
-  0.1934  -0.2727  -0.2400   0.2219
+  0.1934   0.2727  -0.2400   0.1335
+  0.1934   0.2727  -0.2400  -0.2894
+  0.1934   0.2727  -0.2400   0.1559
+  0.1934  -0.2727  -0.2400  -0.3088
+  0.1934  -0.2727  -0.2400   0.7590
+  0.1934  -0.2727  -0.2400  -0.4502
264. embedding.at:23: 264. Adjacency spectral embedding (igraph_adjacency_spectral_embedding):  (embedding.at:23): FAILED (embedding.at:25)
```

Most likely the test graph is too symmetric, which leads to degeneracies, but I have to check more carefully. I am not very familiar with this functionality area.

**Comment by szhorvat** [comment]
This comment, and the one below, are relevant:

https://github.com/igraph/igraph/issues/1374#issuecomment-617008877

**Comment by vtraag** [comment]
Yes, I think in general that we should move away from testing eigenvectors to testing eigenvalues (and possibly verify they are eigenvectors, as you suggested in https://github.com/igraph/igraph/issues/1374#issuecomment-617024717), unless we can guarantee uniqueness of the eigenvectors.

**Comment by ntamas** [comment]
For the time being I'll just implement a quick fix that changes the graph slightly such that we don't have degenerate eigenvalues. We can switch to validating eigenvectors instead if we have more time -- the key problem in most cases is that you need to derive the matrix whose eigenvector you are validating right in the test case, and the code needed to derive the matrix has to be tested as well (unless you have a function in igraph that gives you the desired matrix from the graph automatically).

**Comment by ntamas** [comment]
First attempt in 3162df71; if it works in CI, I'll merge it to `develop` as well.

**Comment by szhorvat** [comment]
@ntamas Looks good so far! I didn't wait for the IBM Z (s360x) to finish as it is taking forever. It was interesting to try all o the architectures that Travis supports.

![image](https://user-images.githubusercontent.com/1212871/83268039-5a124f00-a1c5-11ea-9238-1b8de7d49ff8.png)

If you don't disagree, I'll add one additional testing configuration which uses Ubuntu Bionic (newer gcc than Xenial) and all external LAPACK/BLAS/ARPACK. We had failures with external dependencies in the past, so I think it's worth adding the test. As for all the different CPU architectures I showed here, that was just something I wanted to try, but I do not think there's any point in including them in the test.

**Comment by ntamas** [comment]
Okay, sure, go ahead. I'll close this issue in the meanwhile.
