### ISSUE TITLE
Document how inclist and adjlist handle self-loops

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1396]
It should be documented how `igraph_inclist_init` handles self-loops. Suppose the edge list is `[(1,1)]`, i.e. a single vertex with a self-loop.

Does the incidence list of `1` contain this edge once or twice?

https://igraph.org/c/doc/igraph-Data-structures.html#igraph_inclist_init

**Comment by ntamas** [comment]
Added some docs for the incidence lists.
