### ISSUE TITLE
Feature request: K shortest paths

### ISSUE THREAD

**Issue by scottishaccent** [igraph/igraph#1397]
I would like to see "K shortest paths" functionality added to the core of igraph. This function would find the K shortest paths through a weighted graph using [Yen's algorithm](https://en.wikipedia.org/wiki/Yen%27s_algorithm).

The yenpathy package implements this, but as you can see in the issue tracker, there are several outstanding issues with the implementation that have not been addressed in several months (https://github.com/ecohealthalliance/yenpathy/issues). 

Thank you for your contributions to this community.

**Comment by GroteGnoom** [comment]
I will work on this :slightly_smiling_face:

**Comment by GroteGnoom** [comment]
Done in #1763
