### ISSUE TITLE
Ensure that betweenness cutoff=0 is treated as infinity on master

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1412]
Ensure that betweenness cutoff=0 is treated as infinity on `master`, but *not* on `develop`.

https://github.com/igraph/igraph/pull/1410#issuecomment-642457183

**Comment by szhorvat** [comment]
@vtraag This is done. please check the last few commits on master and develop to make sure I didn't mess up anything. If it's fine, please close this.

**Comment by vtraag** [comment]
Great, thanks @szhorvat, looks all fine to me!
