### ISSUE TITLE
Hub and authority scores are not computed as a matching pair

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1424]
Let us denote hub and authority scores by `h`, `a` and the adjacency matrix and its transpose by `A`, `At`.

Then `h` and `a` are defined as

   - `A.At.h = alpha h`
   - `At.A.a = beta a`

I.e. they're the leading eigenvectors of `A.At` and `At.A`, respectively. Warning: If you are looking at the book MEJ Newman: Networks, 2nd ed., the definitions are interchanged there! (It's a mistake in the text.)

This is precisely how igraph computes them, using ARPACK.

However, there is an additional expectation that `a` and `h` "match" each other in that `At.h ~ a` and `A.a ~ h`, where I used `~` to denote proportionality.

If the leading eigenvalue is degenerate, and thus there are many possible solutions for `a` and `h`, then the results returned by igraph may not match, i.e. `At.h` may not be proportional to `a` and `A.a` may not be proportional to `h`.

@vtraag Do you have practical experience with these scores? Are they still useful for anything if degeneracy arises? Still, it would make sense for igraph to guarantee returning a matching pair.

Small example graph with degeneracy and its edge list:

![image](https://user-images.githubusercontent.com/1212871/86243162-2c466e80-bba6-11ea-9588-8007d1348629.png)

    {{1, 2}, {2, 1}, {2, 3}, {3, 2}, {3, 4}, {4, 1}}

**Comment by szhorvat** [comment]
Here's a shot Mathematica code illustrating that for these graphs, the results are not matching:

```
In[97]:= g = Graph[DirectedEdge @@@ {{1, 2}, {2, 1}, {2, 3}, {3, 2}, {3, 4}, {4, 1}}];

In[98]:= am = AdjacencyMatrix[g];

In[99]:= {a, h} = {IGAuthorityScore[g], IGHubScore[g]}
Out[99]= {{0.927051, 1., 0.572949, 0.618034}, {0.618034, 0., 1., 0.}}

In[100]:= {Normalize[Transpose[am].h, Max], Normalize[am.a, Max]}
Out[100]= {{0., 1., 0., 0.618034}, {0.618034, 0.927051, 1., 0.572949}}
```

**Comment by vtraag** [comment]
I have little practical experience with these scores. The issue of the degeneracy of the solutions was already discussed earlier (see https://github.com/igraph/igraph/issues/649).

It might make sense to guarantee returning a matching pair of authority scores and hubs. If I understand correctly, we can simply take either `a` or `h` and multiply it to obtain the other, right (assuming they are proper eigenvectors)? It might be good to do that and issue a warning about the degeneracy of the eigenvalues.

**Comment by szhorvat** [comment]
In my opinion, the ideal solution is to have a single function which computes both the hub and authority scores at the same time, because:

 - People usually want both.
 - It's efficient. ARPACK only needs to be called once.
 - Makes it easy to return a matching pair.

My suggestion:

 - Add such a function for 0.9
 - Deprecate the separate functions in 0.9
 - In 0.8.3, add a note to the docs explaining the current behaviour



> and issue a warning about the degeneracy of the eigenvalues

I'm not sure how that can be detected without a significant performance hit. ARPACK will give us the leading eigenvalue/eigenvector, but won't tell us if it's degenerate, unless we also ask for the second eigenvalue. (Or does it?)

**Comment by ntamas** [comment]
Even if we ask for the second eigenvalue, I'm still worried that certain degenerate cases won't be detected due to numerical inaccuracies (say, first eigenvalue is x, second is x minus 1 [ulp](https://wikipedia.org/en/Unit_in_the_last_place), different in a strict sense unless we also choose an epsilon threshold based on some theoretical assumptions).

I agree with having a single function that returns both vectors. I don't know whether we should deprecate the functions that calculate the two scores separately; some might find it useful. We definitely need to provide a warning in the documentation, though, and let the user know that she should call `igraph_hub_and_authority_scores()` if she needs a _matching_ pair of vectors.

**Comment by vtraag** [comment]
Sorry, I wasn't aware there were two separate functions.

> My suggestion:
> 
>     * Add such a function for 0.9
> 
>     * Deprecate the separate functions in 0.9
> 
>     * In 0.8.3, add a note to the docs explaining the current behaviour

This makes sense to me.

>  I don't know whether we should deprecate the functions that calculate the two scores separately; some might find it useful.

Couldn't we simply do this by supplying `NULL` values to (one of the) arguments of the function returning both hub and authority scores in order to get only one?

> > issue a warning about the degeneracy of the eigenvalues
> 
> I'm not sure how that can be detected without a significant performance hit.

I thought we were calculating two eigenvectors anyway, and we could then simply check whether either `At.h ~ a` or `A.a ~ h` holds. If that is not the case, there is a degeneracy, and we can issue a warning and calculate the "matching" hub (or authority) score. However, calculating two eigenvectors may be less efficient than calculating one eigenvector and then simply get the "matching" score.

An alternative would be to check if `A.At` would be connected (in which case Perron-Frobenius would imply uniqueness), but I'm not sure how cheap that would be. Clearly, if `A` is strongly connected, `A.At` is also connected, but this is probably not sufficient. Perhaps @szhorvat you have some idea about that?

**Comment by ntamas** [comment]
> Couldn't we simply do this by supplying NULL values to (one of the) arguments of the function returning both hub and authority scores in order to get only one?

Yes, we could, of course, I'm just thinking that since the higher level interfaces already call `igraph_hub_score()` and `igraph_authority_score()`, we can make both _our_ and _other's_ job easier by not removing these functions (no changes needed in the higher level interfaces) and simply providing `igraph_hub_and_authority_score()` in the C core. `igraph_hub_score()` could then call `igraph_hub_and_authority_score()` internally of course.

**Comment by szhorvat** [comment]
@GroteGnoom Nothing to add, go ahead! It would probably make sense to have a single function which computes one of the scores, then uses the result to compute the other as well. Then we can perhaps deprecate the current functions?

**Comment by GroteGnoom** [comment]
Since the milestone is set to 0.9, should this start from the master branch?

**Comment by szhorvat** [comment]
IMO this is better left for 0.10.  The complete fix will include creating a new function that computes the two scores simultaneously, and deprecating the existing functions.  Nothing wrong with making the fix for 0.9, but it's simply not worth the effort.

If you choose to make the fix for 0.9 as well, I would suggest doing it the same way as for 0.10, except keeping the new function (that computes both) internal and of course not doing the deprecation.

**Comment by szhorvat** [comment]
> but it's simply not worth the effort.

Another comment on this is that I don't think this bug is a very big deal because:

 - The individual scores are correct, they just don't come as a pair
 - It is dubious how meaningful these scores are at all in cases where the solution is not unique. The mismatch between hub and authority scores is only possible when the scores are not unique.

**Comment by GroteGnoom** [comment]
I'm trying to find the hub vector of a basic example, and it doesn't seem to work.

For this graph:
```
igraph_small(&g, 3, IGRAPH_DIRECTED,
        0,2, 1,2, -1);
```
igraph_hub_score gives me a value of 0, and random (but the same ones every time I run the program) vectors.

I expect a hub value of 2, and a vector proportional to [1 1 0], which is what I get when I solve for the A.At directly using igraph_sparsemat_arpack_rnsolve.

I've been trying to debug this, but there's a lot of stuff going on, and I'm not sure where to look. igraph_i_kleinberg_unweighted does seem to do sensible things, but I'm not sure how it interacts with the actual solver.

I at least want tot check: igraph_hub_score should just give me a proper non-random result in this case, right?
(I've also checked for a graph with adjacency matrix [[2 1] [1 2]], and there it does give the correct result.)

**Comment by szhorvat** [comment]
I just tried this and I got a value of `2`, as well as the expected vector of `1 1 0`. Latest develop branch. It also works with the Mathematica interface, which currently uses an older master branch.

Here's the code (sorry for the lack of `destroy`s`)

```

#include <igraph.h>

int main() {
    igraph_t g;
    igraph_vector_t res;
    igraph_real_t val;
    igraph_arpack_options_t opt;
    
    igraph_small(&g, 3, IGRAPH_DIRECTED,
        0,2, 1,2, -1);
    igraph_vector_init(&res, 0);

    igraph_arpack_options_init(&opt);

    igraph_hub_score(&g, &res, &val, 1, NULL, &opt);

    printf("val: %g\n", val);
    igraph_vector_print(&res);

    return 0;
}
```

**Comment by ntamas** [comment]
Are you doing this on the `master` branch or on the `develop` branch? It looks like the `develop` branch has a bug there because the type of the `tmp` vector in `igraph_i_kleinberg_data_t` and igraph_i_kleinberg_data2_t` has been changed to an `igraph_vector_int_t` while it should be an `igraph_vector_t`. Needless to say, this can screw things up big time. I'll fix that in `develop` now.

**Comment by GroteGnoom** [comment]
Ah, thank you both so much. Yes, I did notice the tmp vector being int, but using floats, but couldn't really figure out if that was an actual problem.

**Comment by ntamas** [comment]
`igraph_i_kleinberg_*` is supposed to perform a matrix multiplication when ARPACK requests it to do so. The `tmp` vector is used to hold an intermediate result (as we first need to multiply with `A`, then with `A^T`), so yes, it must be a float vector.

**Comment by GroteGnoom** [comment]
I see I messed that one up when changing all the degrees to ints.

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/igraph/commit/a5f5f5f7756f9c536adffb7d9ad8f816e1534824 now

**Comment by ntamas** [comment]
One thing I don't understand though is that hub and authority scores are unit-tested in the Python interface and the tests did not catch this.

**Comment by szhorvat** [comment]
Something else may be going on. It may depend on ARPACK versions. I also got the correct result in my test above. I was using external ARPACK 3.8.0 from MacPorts.

**Comment by GroteGnoom** [comment]
I used ```arpack: stable 3.8.0 (bottled), HEAD```
from homebrew.

**Comment by GroteGnoom** [comment]
Ah, but your vector isn't normalized, I have [0.707107 0.707107 0]

**Comment by szhorvat** [comment]
I get the same `0.707107 0.707107 0` if I set `scale=false` in `igraph_hub_score`. (This is before applying Tamás's fix.)

**Comment by GroteGnoom** [comment]
I removed my old igraph lib, rebuilt the code from before the fix, and copied your code, which gives me 
val: 0
0 0.289728 1

I'm still not sure if it's a linking/building difference or something else.

**Comment by szhorvat** [comment]
Can you try with bundled ARPACK? I'll be back in ~2 hrs and will try as well.

**Comment by GroteGnoom** [comment]
Yes. I'm now getting
```libigraph.a(amd_dump.c.o) has no symbols```
So I'm trying to figure that one out.

**Comment by ntamas** [comment]
That file comes from GLPK and it is essentially empty if you are compiling with `-DNDEBUG`

**Comment by GroteGnoom** [comment]
Ah, I thought it was a problem because of actually missing symbols, but those were because I now needed to link with BLAS and LAPACK.

Now it works, this is my vendored ARPACK result: 
val: 0
0.5 0.5 1

**Comment by ntamas** [comment]
That's not OK; with your graph the dominant eigenvalue should be 2 and the corresponding eigenvector should be [0 0 1]. 0 is an eigenvalue but it's not the dominant one, and it spans a 2D subspace with two corresponding eigenvector bases.

**Comment by szhorvat** [comment]
Weird. I get the correct result still:

```
val: 2
0.707107 0.707107 2.22045e-16
```

Latest `develop` branch, _including_ Tamás's fix from above, vendored ARPACK/LAPACK/BLAS.  For completeness:

```
-- -----[ Build configuration ]----
-- Version:     0.10.0-dev+9b636bc9
-- CMake build type:        Release
-- Library type:             static
-- igraph_integer_t size:   64 bits
-- Compiler cache:           ccache
--
-- ----------[ Features ]----------
-- GLPK for optimization:       yes
-- Reading GraphML files:       yes
-- Thread-local storage:         no
-- Link-time optimization:       no
--
-- --------[ Dependencies ]--------
-- ARPACK:                 vendored
-- BISON:                       yes
-- BLAS:                   vendored
-- FLEX:                        yes
-- GLPK:                        yes
-- GMP:                         yes
-- LAPACK:                 vendored
-- LibXml2:                     yes
-- OpenMP:                       no
--
-- -----------[ Testing ]----------
-- Diff tool:                  diff
-- Sanitizers:                 none
-- Code coverage:                no
-- Verify 'finally' stack:       no
--
-- --------[ Documentation ]-------
-- HTML:                        yes
-- PDF:                         yes
```

**Comment by GroteGnoom** [comment]
Just to be clear: we're trying to figure out why it _didn't_ fail for @szhorvat and the python tests right?

**Comment by szhorvat** [comment]
> That's not OK; with your graph the dominant eigenvalue should be 2 and the corresponding eigenvector should be [0 0 1].

I believe `0 0 1` is the eigenvector for the authority score, while `1 1 0` is for the hub score. Let's write it down for reference:

Adjacency matrix:

```
A=
0	0	1
0	0	1
0	0	0
```

`A.A^T` is for the hub score:

```
A.A^T=
1	1	0
1	1	0
0	0	0
```

Leading eigenvector is `1 1 0`.

`A^T.A` is for the authority score:

```
A^T.A=
0	0	0
0	0	0
0	0	2
```

Leading eigenvector is `0 0 1`.

**Comment by szhorvat** [comment]
> he problem and the fix seem ok.

OK, so with the fixed version it's good for you?

**Comment by GroteGnoom** [comment]
> > he problem and the fix seem ok.
> 
> OK, so with the fixed version it's good for you?

Yes.

**Comment by szhorvat** [comment]
> we're trying to figure out why it _didn't_ fail for @szhorvat

I have the answer for that. It's because @szhorvat was not paying attention.

I accidentally linked to a system-wide installed igraph 0.9.4 .... sorry

**Comment by GroteGnoom** [comment]
Ah 😄  It's so hard getting this stuff right that it's sort of a relief to see that others can make mistakes too. 
So we're left with the question why the python tests didn't fail. Since this problem was only triggered for a specific graph and not others, it could be that we just missed it, but I'd have to look into the python tests too check that. For now I'll just continue with matching hubs and authorities.
