### ISSUE TITLE
Graphicality for non-simple graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1432]
`igraph_is_graphical_degree_sequence` checks if a degree sequence has a realization as a *simple* graph and `igraph_realize_degree_sequence` constructs it.

I am going to implement checking if there is a realization as a graph with/without self-loops and with/without multi-edges, and eventually also constructing these realizations (because I need it for my work).

I am looking for feedback on the API. We can:

 1. create new functions
 2. extend the existing `igraph_is_graphical_degree_sequence`

I prefer (2), as we can use a consistent extension to both `is_graphical_degree_sequence` and `realize_degree_sequence`.

If we go with (2), my first idea was to add two arguments, `igraph_bool_t multiple, igraph_bool_t loops`, similar to other existing functions. These control if multi-edges and self-loops are allowed respectively. This is not quite ideal because `multiple=false, loops=true` would naturally implies that while self-loops may be present, there may only be at most one. Implementing this case is straightforward enough, but it's kind of pointless (I do not expect many applications). The interesting cases are _loopless multigraphs_ and _loopy multigraphs_. Thus, the next possibility would be to have a single "type" variable with enum values such as `SIMPLE_GRAPH`, `LOOPLESS_MULTIGRAPH`, `LOOPY_MULTIGRAPH`. Not as pretty, but probably more aligned with actual use cases, and saves us implementing some not-so-useful cases. It would also allow specifying that we allow multiple self-loops, but we do not allow multiple edges between distinct vertices (which is probably not needed, but it is considered in papers occasionally). Yet another possibility is to go with the `multiple` and `loops` flags but simply return an `IGRAPH_UNIMPLEMENTED` for the missing cases.

So, the choices are:

 1. `multiple` and `loops` flags, complete implementation right away
 2. `multiple` and `loops` flags, partial implementation for now, return `IGRAPH_UNIMPLEMENTED` for the `multiple=false` and `loops=true` case.
 3. Single control variable with named options.

Do you have any preferences on which one to go with?

----

Note 1: We do already have `igraph_is_degree_sequence`, which is basically the loopy multigraph case. 

Note 2: Eventually, a similar extension could be implemented for `igraph_rewire` as well, but this is more work (especially the directed case).

**Comment by ntamas** [comment]
Personally, I would go with a mix of option (2) and option (3). This would be achieved with an enum where the numeric values of the cases are designed in a way that bit 0 belongs to the "loops allowed" case and bit 1 belongs to the "multiple edges allowed" case, and we return IGRAPH_UNIMPLEMENTED for any combinations without an explicit implementation (right now it would be the "loopy simple graph" case). This allows us to implement the missing cases later if someone really needs it, without breaking the existing API, but it also allows us to avoid having two boolean arguments for the same function (which I tend to dislike nowadays because it's hard to remember which one is which without the IDE and the documentation helping me out).

(In general, I think that we should strive for a smaller number of arguments for most functions in the C layer anyway because it gets really annoying when you have ~15 args, most of which are usually left at some sensible default in 99% of the cases. In such cases, it's better to have a dedicated "options" struct that is passed to the function as a single argument).

**Comment by szhorvat** [comment]
I like this idea because it generalizes well. Then I would do it like this:

 - bit 0: self-loop allowed?
 - bit 1: multi-self-loop allowed? (considered only if bit 0 is also set)
 - bit 2: multi-edge between distinct vertices allowed?

These are a bit strange to work with directly, but they can be hidden behind nicely named constants, and the users never need to see them.

 - `LOOPS = 001`
 - `MULTI_EDGES = 110`

I.e., the constant `MULTI_EDGES` toggled on both multi-edges between distinct vertices and multi-self-loops.

The advantage is that should there be a need to separate these cases in the future (and I definitely *can* imagine a need), we can easily do so.

**Comment by szhorvat** [comment]
Now I just have to figure out how to name these constants so that they do not conflict with existing ones ...

We _could_ in principle repurpose `IGRAPH_LOOPS` and `IGRAPH_MULTIPLE`. Currently, their value is 1, but they are simply used as a Boolean `true`, so any non-zero value is theoretically fine. I just have an uncomfortable feeling that repurposing them may lead to trouble that I can't foresee right now ...

Let me know if you have any thoughts @ntamas (not urgent though)

**Comment by szhorvat** [comment]
@ntamas Any opinion on repurposing old symbols or introducing new ones?

If we introduce new ones, we might choose names which make it immediately clear that these are meant to be combined with `|`. Any tips on a good naming convention?

**Comment by ntamas** [comment]
Sorry, I dropped the ball on this one - thanks for the nudge.

I'd rather not re-purpose old symbols; just introduce new ones and then you are free to choose a naming convention that expresses the purpose of these flags the best. I don't have any particular suggestions -- maybe using `_ALLOWED` or `_ENABLED` as the suffix would make it clear that this is a boolean flag that is meant to be combined with other flags?

**Comment by szhorvat** [comment]
I'm adding a few notes about where the implementation is going, so if any of you have concerns, you can comment now (and I can save time by correcting it early).

### Handling of negative numbers in degree sequences

When deciding if a degree sequence is graphical, there are three options to handle negative values:

 1. document that the function assumes non-negative input
 2. return `IGRAPH_EINVAL`
 3. simply return "not graphical"

(3) is the status quo, and I'm keeping it. I found this behaviour convenient in the past.

### Change API vs replace API

I am not going to change the existing `igraph_is_graphical_degree_sequence` and `igraph_is_degree_sequence` functions. Instead, I will introduce a new function `igraph_is_graphical` which overtakes their duties (and will do more). I will simply mark the existing functions as "deprecated", and make them call the new implementation internally. It makes migration from earlier versions easier.

@ntamas We discussed the "experimental" marker earlier. It would be nice to explicitly support `\experimental` and `\deprecated` in the doc system, if it's not difficult. It'd add a standard notice.

**Comment by szhorvat** [comment]
@ntamas Looking at this, I think we neglected to check that the sum of degrees is even when we switched to Király's algorithm:

https://github.com/igraph/igraph/blob/master/src/structural_properties.c#L6948

**Comment by szhorvat** [comment]
@ntamas `igraph_i_is_graphical_degree_sequence_undirected` is quite severely buggy. `work` is sorted increasingly instead of decreasingly, but that does not matter: it is not used anyway. `degrees` is used. I'll fix this and will send a separate PR for the `master` branch. 

I'm sorry, I did not notice this because IGraph/M was still stuck on the original implementation I did for Kiraly's algorithm (from before igraph got the new one), so it wasn't use igraph.

**Comment by ntamas** [comment]
Thanks for the fix; I think it's probably time for a 0.8.3 release when I get back from the holidays.

As for handling negative numbers, keeping the status quo is okay for me.

Regarding the `\experimental` and `\deprecated` markers, please add an issue and assign it to me (and to 0.8.3). I'll take care of it when I'm back - I have gotten way too familiar with the internals of `doxrox.py` during the CMake conversion so it would probably not take too much time.

**Comment by szhorvat** [comment]
I think 0.9 will be fine. We are not really adding new functions in 0.8 and (so no `\experimental`) and we should probably not start deprecating stuff before 0.9. I'll open the issues.
