### ISSUE TITLE
vector_sort performance

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1443]
I was suspicious of `igraph_vector_sort` performance because it uses a comparison function that cannot be inlined, and can therefore could be theoretically slow.

I wrote a small benchmark program to compare it to `std::sort` from the C++ standard library, which does not suffer from this problem. In short, the conclusion is that igraph's version is ~2x slower, even if igraph is compiled with link-time optimization (LTO seems to make no difference at all).

Given that all `igraph_vector_*` types are numeric, I would like to see an improvement to `igraph_vector_*_sort` that uses `>` directly instead of calling a comparison function.

Original motivation: graphicality tests. The original fast version in IGraph/M was written in C++. I used it in programs that tested a gazillion degree sequences and ran for a long time. I want to just use igraph's own version (in part to avoid problems like #1441) but I do not want to put up with the performance hit.

----

Here are results (timings in seconds) from three runs for `igraph_vector_sort` and `igraph_vector_int_sort`:

```
real c++:   0.798846
real igraph: 1.65977
int c++:   0.470059
int igraph: 0.882164

real c++:   0.808043
real igraph: 1.665
int c++:   0.467664
int igraph: 0.866757

real c++:   0.824847
real igraph: 1.65978
int c++:   0.489454
int igraph: 0.883628
```

----

Test program:

```c++

#include <igraph.h>
#include <iostream>
#include <algorithm>
#include <chrono>
#include <random>

const long N = 10000000;

int main() {
    std::mt19937 rng(42 /* seed */);

    // real vectors:

    igraph_vector_t vec1, vec2;

    std::uniform_real_distribution<igraph_real_t> runif(0, 1);

    igraph_vector_init(&vec1, N);
    for (long i=0; i < N; ++i) {
        VECTOR(vec1)[i] = runif(rng);
    }

    igraph_vector_copy(&vec2, &vec1);

    {
        auto t1 = std::chrono::high_resolution_clock::now();
        std::sort(&VECTOR(vec1)[0], &VECTOR(vec1)[N-1]);
        auto t2 = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration<double>(t2 - t1);
        std::cout << "real c++:   " << duration.count() << std::endl;
    }

    {
        auto t1 = std::chrono::high_resolution_clock::now();
        igraph_vector_sort(&vec2);
        auto t2 = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration<double>(t2 - t1);
        std::cout << "real igraph: " << duration.count() << std::endl;
    }

    igraph_vector_destroy(&vec1);
    igraph_vector_destroy(&vec2);

    // integer vectors:

    igraph_vector_int_t ivec1, ivec2;

    std::uniform_int_distribution<igraph_integer_t> iunif(0, 10000);

    igraph_vector_int_init(&ivec1, N);
    for (long i=0; i < N; ++i) {
        VECTOR(ivec1)[i] = iunif(rng);
    }

    igraph_vector_int_copy(&ivec2, &ivec1);

    {
        auto t1 = std::chrono::high_resolution_clock::now();
        std::sort(&VECTOR(ivec1)[0], &VECTOR(ivec1)[N-1]);
        auto t2 = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration<double>(t2 - t1);
        std::cout << "int c++:   " << duration.count() << std::endl;
    }

    {
        auto t1 = std::chrono::high_resolution_clock::now();
        igraph_vector_int_sort(&ivec2);
        auto t2 = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration<double>(t2 - t1);
        std::cout << "int igraph: " << duration.count() << std::endl;
    }

    igraph_vector_int_destroy(&ivec1);
    igraph_vector_int_destroy(&ivec2);

    return 0;
}
```

**Comment by ntamas** [comment]
Okay, how about adding an `igraph_vector_sort_fast()` variant that does not use a comparison function? Do you know any GPL or MIT-licensed sort implementations for C that we could use here? I was thinking about a [timsort](https://hackernoon.com/timsort-the-fastest-sorting-algorithm-youve-never-heard-of-36b28417f399) implementation if there is one.

**Comment by szhorvat** [comment]
> Do you know any GPL or MIT-licensed sort implementations for C that we could use here?

No, haven't done the research yet.

> I was thinking about a [timsort](https://hackernoon.com/timsort-the-fastest-sorting-algorithm-youve-never-heard-of-36b28417f399) implementation if there is one.

Sounds very interesting!

I'll try to benchmark it, and will let you know. Might send a PR if I find an implementation with a good license, and can get it done quickly.

**Comment by szhorvat** [comment]
After some research, this is the best I could find: https://github.com/swenson/sort/  It is claimed to perform very well, it is templated (so hopefully we can easily adapt it), and it seems to be a mature implementation (10 yrs old, last commit this year), which hopefully means a low risk of bugs.

**Comment by szhorvat** [comment]
While I am interested in this, I am not going to work on it for a while. First I need to complete the degree sequence stuff. Thus, if anyone else wants to take it, feel free to do so (just post a note here).

**Comment by szhorvat** [comment]
> Original motivation: graphicality tests.

Since this issue was opened, I changed some of the graphicality tests to use counting sort. Some of the remaining ones can also be moved to counting sort. I am not sure if there are any other parts of igraph where sorting makes up a significant fraction of the runtime. Therefore, while this improvement would be nice, it makes sense to deprioritize it from this point.
