### ISSUE TITLE
\experimental and \deprecated for the documentation

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1444]
This is a request to add features to the documentation system that makes it easy to mark a function as *experimental* (i.e. API stability not guaranteed yet) or as *deprecated*. We discussed this here: https://igraph.discourse.group/t/a-proposal-for-api-stability-marking-functions-as-experimental/248

One possible way to do this is to create the commands `\experimental` and `\deprecated` which will insert a pre-determined explanatory text (possibly with styling) in the docs.

With `\deprecated` we would usually want to add some extra information, e.g. the standard text could be "This symbol is deprecated.", followed by the custom text "Use `foo` or `bar` instead."

I'm not sure what's the best implementation is, but I hope the *intent* is clear from this issue :-)

**Comment by ntamas** [comment]
I decided to add three new directives:

* `\deprecated VERSION` simply marks a symbol as deprecated in the given version, without suggesting a replacement.
* `\deprecated-by SYMBOL VERSION` marks a symbol as deprecated in the given version, suggesting a replacement.
* `\experimental` marks a symbol as experimental and prints an appropriate warning in the generated docs.

I'll commit my changes soon(ish).

**Comment by ntamas** [comment]
Feel free to change the wording of the warning generated by these directives; you need to poke around in `doc/c-docbook.re`.
