### ISSUE TITLE
Crashes in graph generators due to integer overflow

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1446]
The following crashes were reported here: https://github.com/igraph/rigraph/issues/405

----

`igraph_star`:

The cause is integer overflow in the calculation of the size of the `edges` vector here:

https://github.com/igraph/igraph/blob/master/src/structure_generators.c#L715

    if (mode != IGRAPH_STAR_MUTUAL) {
        IGRAPH_VECTOR_INIT_FINALLY(&edges, (n - 1) * 2);
    } else {
        IGRAPH_VECTOR_INIT_FINALLY(&edges, (n - 1) * 2 * 2);
    }

`(n - 1) * 2` or `(n - 1) * 2 * 2` may not fit in an `igraph_integer_t`.

----

A similar crash is present in `igraph_full_citation`.

https://github.com/igraph/igraph/blob/master/src/structure_generators.c#L1138

    IGRAPH_VECTOR_INIT_FINALLY(&edges, n * (n - 1));

`n * (n-1)` does not always fit in the same integer type as `n`.

----

Perhaps fixing these is best left until the usage of all integer types (`igraph_integer_t`, `long` and `size_t`) is put in order in the entire library. Casting to a `long` or a `size_t` is not a general solution: `long` is still 32-bit on 64-bit Windows and `size_t` is 32-bit on 32-bit systems.

**Comment by szhorvat** [comment]
@iosonofabio You've been looking into integer overflow stuff before. Any opinions on this one? It would seem that reliably detecting overflow is not quite a trivial matter.

**Comment by vtraag** [comment]
Wouldn't a trick like `a * b <= a` work here (assuming `a > 0` and `b > 0`)? This will default to the used integer representation I believe (whether 32 or 64 bits).

**Comment by szhorvat** [comment]
I have not looked into how overflow is normally handled, but I do not think that this check is sufficient.

Counterexample: Assume that we work on 5 bits, and the top bit signifies the sign. Let `a = 01011` and `b = 00010` (i.e. four) in binary. Then `a*b = 01100` (multiplying by four shift twice to the left), which is greater than `a`.

**Comment by vtraag** [comment]
Yes, that's true of course (not sure if multiplication is by definition the same as bit-shifting in all implementations though). I think that this should work generally: `(a * b) / a != b` (assuming that `a != 0` of course).

**Comment by ntamas** [comment]
As far as I know the only sure-fire way of detecting overflow that works across compilers and optimization settings is to check whether overflow would occur _before_ performing the actual operation - once the operation is performed, the compiler is free to do anything according to the C standard. You cannot rely on some predictable overflow pattern (e.g., modulo 2^N arithmetic). See also the [CERT C Secure Coding Standards](https://wiki.sei.cmu.edu/confluence/display/seccode/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow).

**Comment by vtraag** [comment]
Good reference, nice to see there are some available templates for catching overflows. This looks rather challenging! The code for safe addition is quite reasonable, the code for safe multiplication is a bit more involved. We could probably add these standards in (and perhaps add some compilation flag `SAFE_INTEGER` or something)? This should also be useful in PR https://github.com/igraph/igraph/pull/1436.

**Comment by szhorvat** [comment]
Closing in favour of #51. Issues from the top post are already solved.
