### ISSUE TITLE
Parallel algorithms for community detection

### ISSUE THREAD

**Issue by remysucre** [igraph/igraph#1458]
There are a handful parallel algorithms for community detection, for example [this paper](https://www.cc.gatech.edu/dimacs10/papers/[15]-dimacs10-community-detection.pdf) and [this paper](https://ieeexplore.ieee.org/document/7377794). Are there plans to implement any? 

Please **do not** use the issue tracker for personal support requests -- use our
[Discourse group](https://igraph.discourse.group) instead.

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by szhorvat** [comment]
The bug tracker is meant for bug reports and specific feature requests. At this point, this is more of a discussion starter. Please use the forum for discussion: https://igraph.discourse.group/

**Comment by szhorvat** [comment]
Don't get me wrong, discussion on such topics is very welcome. But please use the forum for discussions (I was hoping you'd transfer this one to there). Once the request is properly fleshed out, a feature request issue can be opened.

At the moment, there are not really common plans for _any_ new features (as opposed to infrastructural improvements) in igraph. Instead, people contribute what they can and what they want to, individually. We have members who work on community detection—I do not know their personal plans. If you'd like to contribute such a method, of course you are very welcome to do so.

**Comment by remysucre** [comment]
Thank you, I meant to post there but stopped at account registration, then forgot about it. I just made an account and open a topic.
