### ISSUE TITLE
sh: cannot open IGRAPH_VERSION: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [igraph/igraph#1459]
configuration fails with the error from the subject.

Is the file ```IGRAPH_VERSION``` missing?

**Comment by szhorvat** [comment]
We'd like to reserve the GitHub issue tracker for actual bugs and feature requests. For support questions like this, please use the forum: https://igraph.discourse.group/

If you cloned the git repo, you must run `./bootstrap.sh` before `./configure`
