### ISSUE TITLE
eigenvector_centrality: incorrect result

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1470]
Take the following graph:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/93588065-242eeb80-f9ab-11ea-8149-1cf1152b46bd.png">

The result I get is all-ones in Mathematica and Python, and `0.7822195 0.7822195 1.0000000 0.7139747 0.3133648 0.3133648` in R. These are all wrong. The correct result is `(1, 1, 1, 0, 0, 0)` (or the same multiplied by a constant). 

The exact eigenvalues (in red) and eigenvectors (black) are as follows:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/1212871/93588435-b20ad680-f9ab-11ea-9247-a934ebfc4149.png">

Note that all eigenvalues have absolute value 1.

---

Code:

```
In[123]:= IGEigenvectorCentrality@IGShorthand["1->2->3->1,3->4->5,4->6"]
Out[123]= {1., 1., 1., 1., 1., 1.}
```

```
g=Graph([(0,1), (1,2), (2,0), (2,3), (3,4), (3,5)],directed=True)
g.eigenvector_centrality()
```

```
g<-make_graph(c(1,2, 2,3, 3,1, 3,4, 4,5, 4,6))
eigen_centrality(g)
```

**Comment by szhorvat** [comment]
It appears that igraph considers the eigenvalues/vectors not of the adjacency matrix, but of its transpose. In that case, the result is correct.

**Comment by ntamas** [comment]
Or that igraph returns the left eigenvector while it should return the right eigenvector (or vice versa). It depends on how you treat the semantics of the edges. For instance, consider a large directed tree where the edges are oriented outwards from the root, and another one where the edges are oriented towards the root. In which case should the root node be the one with the highest eigenvector centrality?

**Comment by ntamas** [comment]
It could also be the case that the R interface sidesteps this problem by default and treats all graphs as undirected when it comes to eigenvector centrality.

**Comment by szhorvat** [comment]
> Or that igraph returns the left eigenvector while it should return the right eigenvector (or vice versa).

Yes, I have to look at that carefully, make a choice (maybe keep the old choice) and document it.

Here's Newman's opinion on the topic, from his textbook:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1212871/93597523-7972f900-f9bb-11ea-8cf6-15288b89da6c.png">

**Comment by ntamas** [comment]
On the other hand, if you think about [control networks](https://www.nature.com/articles/nature10011) (which came a few years after Newman's textbook), it totally makes sense to consider nodes as highly central when they have lots of outbound edges. The same might apply to gene regulatory networks. So IMHO it's highly dependent on the context, and if we decide to pick one over the other, we should provide a function in igraph that simply allows the user to flip the edge directions in-place.

**Comment by szhorvat** [comment]
Mathematica's function allows choosing the direction: https://reference.wolfram.com/language/ref/EigenvectorCentrality.html (but it's buggy).

So, here's the plan: update the documentation for 0.8.3, but don't change what it does.

For 0.9, introduce a new argument to select in- vs out-directions.

**Comment by szhorvat** [comment]
> It could also be the case that the R interface sidesteps this problem by default and treats all graphs as undirected when it comes to eigenvector centrality.

You are correct.

**Comment by ntamas** [comment]
@szhorvat Did you manage to track down whether igraph returns the left or the right eigenvector? I'll be happy to update the docs once this is settled.

**Comment by szhorvat** [comment]
> @szhorvat Did you manage to track down whether igraph returns the left or the right eigenvector? I'll be happy to update the docs once this is settled.

The left one, i.e. `v.A = λ v`

**Comment by szhorvat** [comment]
@ntamas I updated the C/igraph docs. Please make sure that the Python ones are consistent with it.
