### ISSUE TITLE
eigenvector_centrality: incorrect result with weighted case

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1473]
Consider this graph: `1-2-3-4-1, 5`. The leading eigenvector of the adjacency matrix is (1, 1, 1, 1, 0). `eigenvector_centrality` correctly returns this in the unweighted case. However, if we set weight 1 for all edges, it returns (1, 1, 1, 1, 0.5), which is wrong.

Reported here:

https://igraph.discourse.group/t/eivenvector-centralities-question/454/12

Removing this line appears to fix it, but more investigation is needed: 

https://github.com/igraph/igraph/blob/master/src/centrality.c#L255

**Comment by ntamas** [comment]
Fun fact: it converges to (1, 1, 1, 1, 0.33333, ...) on my machine (macOS, internal ARPACK), for any number of isolated vertices.

**Comment by ntamas** [comment]
Apparently, `igraph_inclist_remove_duplicate()` has a bug as it creates a dummy element in the incidence list of vertices with no incident edges.

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/igraph/commit/5f41b4f43503b896b8ae63388195e3be0948fe31 ; tested with the Python interface.
