### ISSUE TITLE
Different outputs between igraph.community_leiden and leidenalg with self loops

### ISSUE THREAD

**Issue by Puumanamana** [igraph/igraph#1475]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Hi,
I have recently discovered that the leiden clustering algorithm was included in python-igraph, and this is very helpful for me. It mostly produces very similar results as the `leidenalg` package. However, there seems to be a systematic difference between the 2 packages when vertices have self-edges. Here's an example:

```python
import igraph # v0.8.2
import leidenalg #  v0.8.2


def get_graph():
    g = igraph.Graph()
    g.add_vertices(['V0', 'V1', 'V2', 'V3'])
    g.add_edges([('V0', 'V1'), ('V2', 'V3')])

    return g

def print_igraph_clusters(g):
    clusters = g.community_leiden('CPM', resolution_parameter=0.1)
    print([cluster for cluster in clusters])

def print_leiden_clusters(g):
    clusters = leidenalg.find_partition(
        g, leidenalg.CPMVertexPartition, resolution_parameter=0.1
    )
    print([cluster for cluster in clusters])

> g = get_graph()
# same output for both
> print_igraph_clusters(g)
[[0, 1], [2, 3]]
> print_leiden_clusters(g)
[[0, 1], [2, 3]]

> g.add_edges([(f'V{i}', f'V{i}') for i in range(4)])
# igraph produces singleton clusters while leiden produce the same output as before 
> print_igraph_clusters(g)
[[0], [1], [2], [3]]
> print_leiden_clusters(g)
[[0, 1], [2, 3]]
```

**Comment by vtraag** [comment]
I've pushed the simple alternative already in PR #1476, because this is at least for now the simplest solution. I can confirm that this also solves the reported issue and that both implementations now report the correct partition: `[[0, 1], [2, 3]]`.
