### ISSUE TITLE
Wishlist: Reverse the direction of edges while preserving attributes

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1477]
There should be a function that takes a directed graph and reverses the direction of each edge while preserving all graph attributes.

**Comment by Gomango999** [comment]
Hello!

Is anyone working on this? I'm new to open source and contributing, but I think this would be a great first project to start on!

**Comment by GroteGnoom** [comment]
No one is assigned, so it seems fine 🙂 I'm not 100% sure how hard this one is, it seems clear and relatively simple, but our attribute system needs some getting used to.

We've noticed that everything goes smoother if you do this in small chunks, and let us check if you're going in the right direction. So if you for example start with a function which only works for an empty graph, and a test that tests it, that would be great 🙂 

If you have any questions don't hesitate to ask.

**Comment by Gomango999** [comment]
Awesome! I'll get started on it tomorrow, and get that draft PR in :)

**Comment by szhorvat** [comment]
@Gomango999 :

I do not think that this is a good first issue for the following reason. There is potential for doing this modification efficiently in-place. That involves touching the core data structure, and making the function a part of the core graph API. This is a sensitive thing to do. Do you agree @ntamas @vtraag ?

We could do a trivial function that does not do in-place modification, but I do not think that is what we want to have in the long term.

If you are looking for a way to get start, I would suggest implementing a graph constructor for circulant graphs, as I mentioned here: https://github.com/igraph/igraph/pull/1844#issuecomment-972959559 This task would be very similar to #1819 and would let you get familiar with the basics of the library (memory management, error handling) without being distracted by other things. Once you are familiar with the basics, you can move on to more involved tasks.

How comfortable are you with C programming?

**Comment by GroteGnoom** [comment]
> This is a sensitive thing to do.

What do you mean by this exactly? It needs to be done correctly of course, but do you mean it's harder?

**Comment by szhorvat** [comment]
This is definitely not for a first-time contributor because:

 - IMO it should be done in the core (type_indexededgelist). We want to keep the core as small as possible. Changes to the core API may limit what we will be able do in the future (e.g. swap the graph data structure). Such changes should be discussed by the team before going ahead. I would certainly not go ahead with this task before discussing the approach first.
 - Whichever way it's done (in the core or not), it requires familiarity with more than typical igraph tasks (either an understanding of the core data structure, or attribute handling). It's better for a beginner to become familiar with the more commonly used parts of the library first. There is no reason not to complete a simpler task first before getting started with something like this (even disregarding what I said about touching the core).

**Comment by ntamas** [comment]
My two cents: I don't think that this operation belongs to the core C API that has access to the internals of `igraph_t`, especially if our aim is to keep the core API as small as possible. Sure, if the implementation is not allowed to touch the internals of `igraph_t`, then our best bet is to create a function that constructs a new graph with the same set of attributes but a modified edge list where each edge is reversed (but their order is kept) - but I wonder how often such a function would be used by the end users. I don't really see that it would be such a common operation that warrants a place for it in the core C API.

@szhorvat Do you have any particular use-cases in mind where it would be a common task to reverse the direction of edges on a graph and where you cannot get around with simply having two copies of the graph (one with the "normal" direction of edges and one with the "reversed" direction)?

**Comment by szhorvat** [comment]
Considering edges in a reverse direction is an essential operation, and must be supported _efficiently_ in some way. Right now, most igraph functions which are sensitive to edge direction have a `mode` argument with a choice of `IN`/`OUT`. This is essentially reversing edges. We should either make sure that this is universally supported (difficult: there might be surprises we didn't think of), or we should have a _fast_ way to reverse a graph in-place.

With the current data structure, the reversal can be done in O(1) time. It seems to me that it's sufficient to swap `from`/`to`, `oi`/`ii` and `os`/`is`, and we're done.

Now the question is:
 1. Are there cases where the `mode` argument is missing?
 2. Are there use cases which can't be solved with the `mode` argument, yet still need to be fast?
 3. What disadvantages are there to making this part of the core?

I don't know the answer to 1. Probably it's "no". If any function misses the feature, it should probably be corrected. Note that the situation is a bit complicated, and some functions might need two `mode` parameters (e.g. `knn`).

As for 2, there _are_ use cases, but the ones I can think of are not performance-critical. For example, we want to plot with reverse arrow directions. Or we imported a graph from a file, and the directions are not "natural", for whatever reason we want reverse.

For 3, _with the current representation_, I do not see real disadvantages. The O(1) performance is of much greater value in my eyes than the addition of a single function to the core. It _is_ a fundamental operation, after all. The question is: if we choose an alternative representation, will that make it impossible to support an O(1) reversal? I suspect not, because whatever representation we might choose, it will need to support both the `IN` and the `OUT` modes with equal efficiency. E.g. we couldn't just use a unidirectional adjacency list, it would have to be a pair of adjlists for each directions. [@vtraag's proposal is also bidirectional.](https://igraph.discourse.group/t/new-graph-data-structure-proposal/420?u=szhorvat)

----

Overall, I would vote to make this part of the core and make it O(1). There is no question that reversal is needed, we just need to decide how to support it: `mode` (current), in-place reversal, or both. Why not go for both, for peace of mind and flexibility? 

The problem with using `mode` only is that it's implemented separately for each function, so we'll never be sure if there's some use case that's missed. To make up an artificial example, what if for some application we need to check isomorphism of many graphs with both edge directions? `mode` won't be part of isomorphism functions. In-place reversal is a universal solution.

**Comment by szhorvat** [comment]
@ntamas Here we had the opposite opinions about in-place modification ;-) @1830

**Comment by ntamas** [comment]
Just to clarify: I'm not arguing against in-place modifications general, I'm simply arguing against making this operation part of the core C API that is allowed to touch the internals of `igraph_t`, simply because I don't think it occurs frequently enough to warrant the inclusion in the core C API. If there would be a way to implement this operation in a way that modifies the graph in-place but does _not_ touch the internals of `igraph_t`, I would have no objections against it.

Anyhow, I'll read your longer comment and think about this over the weekend. But right now I'm of the opinion that the fact that it can be done easily and efficiently with the current data structure does not mean that it oculd be done in a similarly efficient way with other data structures (if we ever decide to change the internals of `igraph_t`), and the larger we make the API surface of the C core, the harder it will be to try out alternative data structures in the future.

**Comment by szhorvat** [comment]
> If there would be a way to implement this operation in a way that modifies the graph in-place but does _not_ touch the internals of `igraph_t`, I would have no objections against it.

This is impossible almost by definition. If the core data structure can't be touched, then any "in place" modification will be an illusion (create a new graph, overwrite the original `igraph_t` with it, just like with `contract_vertices`), and therefore pointless to try to do in-place. The only way true in-place modification would be possible _without_ touching `igraph_t` internals if it can be done in terms of some simpler mutating operations that they themselves are a part of the core. But what is simpler than reversal?

> Anyhow, I'll read your longer comment and think about this over the weekend. But right now I'm of the opinion that the fact that it can be done easily and efficiently with the current data structure does not mean that it oculd be done in a similarly efficient way with other data structures (if we ever decide to change the internals of `igraph_t`)

The reason why I think it will be possible with other data structures is that any data structure must support bidirectionality just so we can have the `mode` arguments. Of course it's possible I'm missing something.

**Comment by szhorvat** [comment]
Here's a different thought: It might be nice to have a function that flips the direction of only some edges, while preserving attributes. Such a function couldn't be part of the core. We can start with implementing this.

**Comment by vtraag** [comment]
Just my two cents for now: the fact that we are having this discussion is exactly the reason why I think @szhorvat 's argument is correct that this is not a good first issue for anyone starting with igraph. Only when we have clarity on this ourselves can we "solve" it. The implementation should not be too difficult, but the repercussions might be broader than initially thought, and for that reason it's good to have this discussion. I'll also have to think about it further.

**Comment by iosonofabio** [comment]
Hi Kevin!

... Ahem, welcome to igraph! I see that the locals have already given you an "igraphug" of welcome.

I have sinned in telling you this might be a good first issue, why don't you try out the circulant graph constructor @szhorvat mentioned?

😉🙏

**Comment by Gomango999** [comment]
Yep definitely sounds like I'm in over my head for this one! The circulant graph constructor looks alot nicer, so I'll switch over :)

**Comment by szhorvat** [comment]
People are requesting this feature on the forum:

https://igraph.discourse.group/t/create-tranpose-edge-reversed-of-graph/1219?u=szhorvat

I still think that this should be part of the small core because it is a fundamental operation that cannot be reasonably reduced into more fundamental ones while achieving good performance. We don't have to give a guarantee that this will stay an O(1) operation forever (even with other graph representations), but it'd be a shame not to support it with the current graph representation.  Also, if we commit to supporting both the OUT and IN modes with equal efficiency, even with different future alternative graph representations, there will definitely be a way to do efficient reversal (i.e. faster than O(E))

**Comment by szhorvat** [comment]
Implementing this in the small core is trivial. Why don't we just do it now?

**Comment by ntamas** [comment]
Go ahead, I don't have any objections :)

**Comment by szhorvat** [comment]
So do you mean to keep the core API function private, and not expose it directly? Just to make sure I understand.

**Comment by szhorvat** [comment]
We can do the full functionality now:

Full graph reversal will be done through a fast internal function of the core API.

Per-edge reversal will be done by a dumb conversion to edge list and back. Luckily we have a function to copy over attributes unmodified (even if we don't have functions to set attributes one by one).

**Comment by ntamas** [comment]
Even better :)

**Comment by szhorvat** [comment]
There's `graph/neighbors.h`. I'd like to rename this and make it a generic header for internal core API functions. Then we can put the internal edge reversal function in there as well. 

I'm mentioning this here because I know you are working on updating `igraph_neighbors()` and I don't want us to step on each others' toes.

I won't be able to do this today but I'll let you know when I start.

**Comment by ntamas** [comment]
Just go ahead whenever it's convenient for you, I'll take care of merging stuff in my branch. Just commit often :)

**Comment by clpippel** [comment]
Very useful to have. You might name it as **transpose(g)** for graph g. See: https://en.wikipedia.org/wiki/Transpose_graph.
