### ISSUE TITLE
is_separator incorrect result

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1480]
`is_separator`'s documentation [says](https://igraph.org/c/doc/igraph-Separators.html#igraph_is_separator):

> Decides whether the removal of a set of vertices disconnects the graph

But what should this function do if the graph is already disconnected?

Consider this disconnected graph:

    g<-make_graph(c(1,2, 2,3, 3,4, 4,1, 5,6, 6,7, 7,8, 8,5), directed = F)

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1212871/95086309-a1cf5700-0720-11eb-94c8-04b4360276b2.png">

The function returns true for any vertex set, even the empty set:

```
> is_separator(g, c(1,3))
[1] TRUE
> is_separator(g, c(1))
[1] TRUE
> is_separator(g, c())
[1] TRUE
```

Presumably this is because the graph is already disconnected. This is not necessarily wrong, but I wonder if disconnected graphs could be handled better. We could use the definition: 

 - A vertex set is a separator if its removal increases the number of components.

----

What I wrote above is not an outright bug, but there is a different, incorrect behaviour:

Consider a graph with two connected components one of which is an isolated vertex:

    g<-make_graph(c(1,2), n=3, directed=FALSE)

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1212871/95086611-fbd01c80-0720-11eb-9ece-6da18fa120f9.png">

```
> is_separator(g, c(2))
[1] TRUE
> is_separator(g, c(3))
[1] FALSE
```

Why the FALSE response for the set {3}?

It seems to me that the function does a very naïve check: 

 - After removing a set of vertices, is the graph connected or not?

After removing vertex 3, what remains is a connected graph. Here's another example confirming this:

```
> is_separator(make_graph(c(1,2, 3,4), directed=F), c(3,4))
[1] FALSE
```

After removing 3 and 4, what remains is a connected graph, even through the original graph was not connected.

This behaviour is plainly incorrect, regardless of which specific definition of "separator" we use.

**Comment by ntamas** [comment]
One other possible definition is to say that a vertex set is a separator w.r.t. a vertex pair _u_ and _v_ (where _u_ and _v_ are not in the set that is being removed) if it disconnects _u_ from _v_, and a vertex set is a separator "in general" if there is at least one such _u_-_v_ pair. I think this is consistent with both results, although I agree that it is a bit counterintuitive.

**Comment by szhorvat** [comment]
Yes that is a reasonable definition, but the results are not consistent with it.

In the second example, there is no u-v pair that is connected in the graph, but will become disconnected by removing vertex `2`. Yet the set {2} is claimed to the a separator by the function.

The results should also be consistent with the articulation points function: each articulation point is a size-1 vertex separator.

I think the simplest way to deal with both `is_separator`, as well as the functions which *find* separators, is to decompose the graph into connected components and run the algorithm on each. This is the simplest way (the quick-fix), not the efficient way ...

**Comment by ntamas** [comment]
Okay, let's try to sort this out in 0.9.

**Comment by szhorvat** [comment]
Any fix to this must consider that this function is used internally in `igraph_minimum_size_separators`. We must not break that function (and we must verify whether it is already broken due to this).

**Comment by szhorvat** [comment]
Proposal for the definition:

A vertex set $S$ is a separator in a graph $G$ if there are some vertices $u, v \notin S$ that become separated when removing $S$. In other words, $u$ is reachable from $v$ in $G$, but not in $G - S$.

Proposal for the algorithm:

We contract the vertices in $S$. This can be done efficiently through a special treatment of the adjacency list: all these vertex IDs are treated equivalently and as having a common neighbour list that is pre-computed.

Let's do a DFS through the first incident edge of the contracted vertex. If all other incident edges are traversed by this DFS, and we were able to reach other vertices, then $S$ is a separator.

**Comment by szhorvat** [comment]
We had a discussion with Tamás about a potential algorithm to use here. I will implement this eventually.
