### ISSUE TITLE
windows install fails: igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory

### ISSUE THREAD

**Issue by AndreMikulec** [igraph/igraph#1483]
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
. . .
> update.packages()
igraph :
 Version 1.2.5 installed in W:/R-4.0._/R_LIBS_USER_4.0._
 Version 1.2.6 available at http://cran.rstudio.com
Update? (Yes/no/cancel) y

  There is a binary version available but the source version is later:
       binary source needs_compilation
igraph  1.2.5  1.2.6              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package 'igraph'

trying URL 'http://cran.rstudio.com/src/contrib/igraph_1.2.6.tar.gz'
Content type 'application/x-gzip' length 2715500 bytes (2.6 MB)
downloaded 2.6 MB

* installing *source* package 'igraph' ...
** package 'igraph' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
. . . 
"W:/RTools40/mingw32/bin/"gcc  -I"W:/R-40~1._/App/R-PORT~1/include" -DNDEBUG -I/include/libxml2 -I/include -DLIBXML_STATIC -DUSING_R -DHAVE_FMEMOPEN=0 -DHAVE_OPEN_MEMSTREAM=0 -DHAVE_RINTF -DWin32 -DHAVE_LIBXML -Wall -DPACKAGE_VERSION=\"1.2.6\" -DHAVE_FMIN=1 -DHAVE_LOG2=1 -DHAVE_SNPRINTF -Ics -I/include -DHAVE_GLPK=1 -Iplfit -Iprpack -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -I. -Iinclude -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -I/include      -DINTERNAL_ARPACK -I. -I/include -DHAVE_GFORTRAN   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c fast_community.c -o fast_community.o
"W:/RTools40/mingw32/bin/"gcc  -I"W:/R-40~1._/App/R-PORT~1/include" -DNDEBUG -I/include/libxml2 -I/include -DLIBXML_STATIC -DUSING_R -DHAVE_FMEMOPEN=0 -DHAVE_OPEN_MEMSTREAM=0 -DHAVE_RINTF -DWin32 -DHAVE_LIBXML -Wall -DPACKAGE_VERSION=\"1.2.6\" -DHAVE_FMIN=1 -DHAVE_LOG2=1 -DHAVE_SNPRINTF -Ics -I/include -DHAVE_GLPK=1 -Iplfit -Iprpack -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -I. -Iinclude -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -I/include      -DINTERNAL_ARPACK -I. -I/include -DHAVE_GFORTRAN   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c feedback_arc_set.c -o feedback_arc_set.o
In file included from feedback_arc_set.c:31:
igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
          ^~~~~~~~
compilation terminated.
make: *** [W:/R-40~1._/App/R-PORT~1/etc/i386/Makeconf:222: feedback_arc_set.o] Error 1
ERROR: compilation failed for package 'igraph'
* removing 'W:/R-4.0._/R_LIBS_USER_4.0._/igraph'
* restoring previous 'W:/R-4.0._/R_LIBS_USER_4.0._/igraph'

The downloaded source packages are in
        'W:\R-4.0._\R_USER_4.0.__R_STUDIO\AppData\Local\Temp\RtmpigksDl\downloaded_packages'
Warning message:
In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package 'igraph' had non-zero exit status

> devtools::session_info()
- Session info ---------------------------------------------------------------
 setting  value
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/Chicago
 date     2020-10-08

- Packages -------------------------------------------------------------------
 package              * version date       lib source
 assertthat             0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports              1.1.10  2020-09-15 [1] CRAN (R 4.0.2)
 callr                  3.4.4   2020-09-07 [1] CRAN (R 4.0.2)
 cli                    2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
 codetools              0.2-16  2018-12-24 [2] CRAN (R 4.0.2)
 crayon                 1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 desc                   1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
 devtools               2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
 digest                 0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
 doParallel             1.0.15  2019-08-02 [1] CRAN (R 4.0.0)
 ellipsis               0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
 fansi                  0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 foreach                1.5.0   2020-03-30 [1] CRAN (R 4.0.0)
 fs                     1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 glue                   1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 iterators              1.0.12  2019-07-26 [1] CRAN (R 4.0.0)
 lattice                0.20-41 2020-04-02 [2] CRAN (R 4.0.2)
 magrittr             * 1.5     2014-11-22 [1] CRAN (R 4.0.0)
 memoise                1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
 PerformanceAnalytics   2.0.4   2020-02-06 [1] CRAN (R 4.0.0)
 pkgbuild               1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
 pkgload                1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
 prettyunits            1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
 processx               3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
 ps                     1.4.0   2020-10-07 [1] CRAN (R 4.0.2)
 quadprog               1.5-8   2019-11-20 [1] CRAN (R 4.0.0)
 R6                     2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 remotes                2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 rlang                  0.4.8   2020-10-08 [1] CRAN (R 4.0.2)
 rprojroot              1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
 sessioninfo            1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
 testthat               2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
 usethis                1.6.3   2020-09-17 [1] CRAN (R 4.0.2)
 withr                  2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xts                    0.12.1  2020-09-09 [1] CRAN (R 4.0.2)
 zoo                    1.8-8   2020-05-02 [1] CRAN (R 4.0.0)

**Comment by szhorvat** [comment]
This issue tracker is for the C core of igraph, not for the R interface. Also, we would like to keep it reserved for bug reports and feature requests. For support questions please use the forum: https://igraph.discourse.group/

**Comment by szhorvat** [comment]
When a new R/igraph version is released, it takes a while until binaries become available on CRAN. You can explicitly install the previous version from CRAN, or you can wait a couple of days until the binaries become available.

I would not recommend that you try to compile it on your on, especially on Windows, unless you know what you are doing. If you really want to do this, you will need to have GLPK installed first.

**Comment by Rangaraj-baskar** [comment]
I am still facing the same issue; what can I do ?

**Comment by szhorvat** [comment]
@Rangaraj-baskar Are you using igraph from R or from C? This is the issue tracker from C.

If you are using R, what I wrote above still applies. Wait for a binary. See also [here](https://github.com/igraph/rigraph/issues/489#issuecomment-964337011).

If you are using C, please open a new issue and describe in details what you did so we can try to reproduce the problem.
