### ISSUE TITLE
CMake with external BLAS/LAPACK libraries on Windows

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1491]
I thought it would be more convenient to keep track of the separate issues for the CMake build, and only keep the overview of all CMake related issues in #1490. This issue is to keep track of the CMake build using external BLAS/LAPACK libraries.

It seems that a more recent release (0.3.10) of OpenBLAS has solved the issues that I encountered with an earlier version (hanging on `openblas.dll!blas_lock` as reported earlier in https://github.com/igraph/igraph/issues/1490#issuecomment-715383082). It now builds correctly and no tests seem to hang anymore. The current configuration is built using `vcpkg` as a shared library. Since `LAPACK` is built using `gfortran` from `mingw`, it can only be used as a shared library, because according to the [`portfile.cmake`](https://github.com/microsoft/vcpkg/blob/70f380e802852fc09c929dead9d8b8659d394181/ports/lapack-reference/portfile.cmake#L53) for `LAPACK`

```
# If openblas has been built with static crt linkage we cannot use it with gfortran!
```

The alternative is to build with Anaconda. The benefit of this is that these are pre-compiled binaries, which should make it easier to link against these libraries. This is also important in the CI, since installing the packages with `vcpkg` takes over half an hour, because they are all built from source. Possibly, some caching might be done, but this might still be more complicated. Note that a more recent version of OpenBLAS (0.3.11) is not recommended. Unfortunately, this version did seem to make its way into `conda-forge` in Anaconda, so it might be necessary to explicitly request version 0.3.10.

However, there are unfortunately three tests that fail with these external libraries:

```
99% tests passed, 3 tests failed out of 234

Total Test time (real) =  76.32 sec

The following tests FAILED:
         10 - igraph_sparsemat5 (Failed)
        197 - igraph_arpack_rnsolve (Failed)
        218 - igraph_scg_grouping (Failed)
```

Diffs:
<details>
<summary><code>10 - igraph_sparsemat5</code></summary>

```
Comparing files C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_sparsemat5.out and C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_SPARSEMAT5.OUT
***** C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_sparsemat5.out
2.61264 0
...
--
***** C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_SPARSEMAT5.OUT
2.61264 0
...
--
*****
```

I don't really understand this difference 🤔 

</details>

<details>
<summary><code>197 - igraph_arpack_rnsolve</code></summary>

```
Comparing files C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_arpack_rnsolve.out and C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_ARPACK_RNSOLVE.OUT
***** C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_arpack_rnsolve.out
***** C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_ARPACK_RNSOLVE.OUT
LM #1: vector corresponding to eigenvalue (22.0483 + 0.0000*i) is not an eigenvector, coordinate 0 differs by 0.0469 + 0.0000*i
...
---
*****
```

</details>

<details>
<summary><code>218 - igraph_scg_grouping</code></summary>

```
Comparing files C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_scg_grouping.out and C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_SCG_GROUPING.OUT
***** C:\USERS\TRAAGVA1\SRC\IGRAPH\EXAMPLES\SIMPLE\igraph_scg_grouping.out
0 1 2 3 4 4 2 5 2 2 5 0 2 0 5 1 1 0 0 4 0 4 4 1 4 4 5 0 4 0 1 1 1 0 4 5 5 2 1 5 2 5 1 4 1 4 5 1 2 0 4 4 4 5 5 4 5 1 0 1 1 4 5 3
...
 2 3 2 0 4 4 2 2 0 2 4 0 4 5 1 2 4 1 3 0 3 2 2 4 3 4 2 1 4 1 1 1 1 4 4 3 3 1 1 1 4 0 1 1 1 1 4
***** C:\USERS\TRAAGVA1\BUILD\IGRAPH-SHARED\TESTS\TEST_IGRAPH_SCG_GROUPING.OUT
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
...
 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 2 3 0
*****
```

</details>

**Comment by ntamas** [comment]
> Possibly, some caching might be done, but this might still be more complicated.

Appveyor seems to [support build caches](https://www.appveyor.com/docs/build-cache/).

**Comment by szhorvat** [comment]
> Since `LAPACK` is built using `gfortran` from `mingw`, it can only be used as a shared library, because according to the [`portfile.cmake`](https://github.com/microsoft/vcpkg/blob/70f380e802852fc09c929dead9d8b8659d394181/ports/lapack-reference/portfile.cmake#L53) for `LAPACK`

OpenBLAS provides a LAPACK API. If OpenBLAS is installed, it is not necessary to install the netlib LAPACK.

BLAS and LAPACK are a bit confusing: what is needed is not usually a library called "blas" or "lapack" by your package manager. Instead, there are multiple, differently named libraries that provide the necessary APIs. Some of them provide only a BLAS API, some provide both a BLAS and a LAPACK API. OpenBLAS provides both.

**Comment by szhorvat** [comment]
> However, there are unfortunately three tests that fail with these external libraries:

It's a bit unclear to me which libraries, or which library versions, this refers to. Can you clarify?

On MSYS2 and on Linux, only some SCG tests fail for me when I use OpenBLAS both for BLAS and LAPACK: #1499

**Comment by vtraag** [comment]
I just retried to compiling with OpenBLAS  (version 0.3.10) from `vcpkg` using the latest development commit (bbd39f37ea55adb1f390eedc71a0a737f646fc9a). This results still in the previously identified test errors

```
  The following tests FAILED:
          6 - example::igraph_sparsemat5 (Failed)
         52 - test::edge_selectors (Failed)
        273 - test::igraph_arpack_rnsolve (Failed)
        296 - example::igraph_scg_grouping (Failed)
```

However, there is one additional error however for the `edge_selector`, namely that `v_to` is being used without being initialized (I assume the same will hold for `v_from`). This should be easy to fix.

**Comment by szhorvat** [comment]
> However, there is one additional error however for the `edge_selector`, namely that `v_to` is being used without being initialized (I assume the same will hold for `v_from`). This should be easy to fix.

This is a warning, not an error. Since the function where they're used is unimplemented, it's really just a placeholder for a future test.

> 52 - test::edge_selectors (Failed)

But why does it fail at runtime? Is there any additional output? This cannot be related to the uninitiailzed variables.

**Comment by vtraag** [comment]
> This is a warning, not an error. Since the function where they're used is unimplemented, it's really just a placeholder for a future test.

It is really raised as an error, not a warning. I don't know why it is treated as an error on my system, and not on the CI. It might have to do with differences in VS version or defaults or something, not sure. I know the function is not implemented (that is what the test checks), but it would not be a problem to fix it by initialising `v_to` and `v_from`, would it?

**Comment by vtraag** [comment]
> Does it fail only when using OpenBLAS? This test does not use OpenBLAS at all.

You are right, it is not related to this, it just happened to come up here as I was testing this.

**Comment by szhorvat** [comment]
I could just reproduce it here, in *release* mode even. This is a weird run-time check to do in release mode ...

**Comment by vtraag** [comment]
Yup.

**Comment by szhorvat** [comment]
I mean it would require serious instrumentation to even detect such a thing at runtime ... Anyway, we can init them to zero, easy fix as you said.

**Comment by szhorvat** [comment]
@vtraag CI didn't detect it because it was running in Release mode. In Debug mode, the Infomap test was timing out. I'll fix this and switch the CI over to Debug mode on Windows.

**Comment by vtraag** [comment]
> EDIT: I was wrong. I was accidentally running it in Debug mode.

Hmm, perhaps I should double check as well then. I specifically reran, because I thought it ran in Release mode.

**Comment by szhorvat** [comment]
Which generator are you using?

**Comment by szhorvat** [comment]
With a multi-config generator, it should not print `Setting build type to 'Release'`. This is the responsible code:

https://github.com/igraph/igraph/blob/develop/etc/cmake/BuildType.cmake#L6

`CMAKE_CONFIGURATION_TYPES` should have a value with multi-config generators, so this code should never run.

**Comment by vtraag** [comment]
Using VS 16, 2019. Nope, `CMAKE_CONFIGURATION_TYPES` is not set, just double checked. We probably need to check it in some other way: [`GENERATOR_IS_MULTI_CONFIG`](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) seems to be the way to go here?

**Comment by szhorvat** [comment]
I did think of that when I was looking at this code, and I _thought_ I checked that `CMAKE_CONFIGURATION_TYPES` was set here. I'll double-check tomorrow.

The CMake code, as we use it now, came directly from a CMake blog post, so I assumed they knew what they were doing ...

**Comment by szhorvat** [comment]
I wonder if `CMAKE_CONFIGURATION_TYPES` gets set only _after_ the `project` line ... that was ultimately the change I made, move this stuff before the `project` line to avoid `CMAKE_BUILD_TYPE` being set to `Debug` on Windows

**Comment by vtraag** [comment]
Yes, it probably has something to do with that. `GENERATOR_IS_MULTI_CONFIG` also does not get set in `BuildType.cmake`.

**Comment by szhorvat** [comment]
@vtraag Fixed: 6eef2e7ca93bbf9a43ede59aaf40fba0343b363e

**Comment by szhorvat** [comment]
Regarding the "being used without being initialized" runtime error:

This is cause by the `\RTC` flag which CMake adds to the Debug build by default. [See the MSVC docs](https://docs.microsoft.com/en-us/cpp/build/reference/rtc-run-time-error-checks?view=msvc-160) 

I enabled Debug mode on the CI, only for the static build, to see how it would fail. Well, it seems to effectively hang, without any indication of what is happening. It very likely throws up that modal dialog window, which we can't see from here.

It would appear that disabling this window (and making the program print to the terminal) would require modifying the program itself, [see here on SO](https://stackoverflow.com/q/1938715/695132) and [MSVC docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-abort-behavior).  If we don't do this, then these runtime checks are absolutely un-useful.

Here's what I suggest:

 - For now let's just set it back to Release mode (or RelWithDebInfo, which at least doesn't define `NDEBUG`).
 - I will set a low default timeout for all tests on the CI so that if something like this happens, we don't have to wait for 30 min for them to finish.
 - We *should* keep at least one of the Windows builds in Release mode even if in the future we manage to add that `_set_abort_behavior` call. It has happened that some things failed only in Release mode, and we _need_ Release mode to work, as it is what would normally be used. MSVC crashed on some code more than once when compiling in Release mode (the infamous C1001).

**Comment by szhorvat** [comment]
OK, I'm setting the Windows build with RelWithDebInfo mode, as apparently that will just print errors to the terminal, while Debug mode will keep popping up dialog windows: https://github.com/dotnet/llilc/issues/584#issuecomment-103956713

**Comment by szhorvat** [comment]
`igraph_sparsemat5` and `igraph_arpack_rnsolve` shouldn't even be using BLAC/LAPACK (should they?) so why do they fail?

**Comment by szhorvat** [comment]
@vtraag I rewrote the sparsemat5 test so we can actually see what is happening, please pull the latest version. It seems that the eigenvector returned by `igraph_sparsemat_arpack_rnsolve` is twice larger than what is "expected". I.e., it is correct, as constant factors don't matter, but I don't know why it would get multiplied by 2, and I don't know if `rnsolve` is supposed to give any guarantees about normalization. On other platforms the norm of the result is 1, on Windows with OpenBLAS it is 2.

CMake uses the `fd` tool to compare files on Windows. The output is different from diff's and CMake seems to pass a flag to this tool which asks it to limit the output length. That is why we see only `...`. Here's a diff screenshot:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1212871/107882395-59ebe800-6ee9-11eb-84b2-cf0c5d9c8451.png">

**Comment by ntamas** [comment]
ARPACK itself usually offers no guarantees about normalization as far as I know, so we should either normalize the vector in the test case, or add normalization to `igraph_sparsemat_arpack_rnsolve()` instead.

**Comment by szhorvat** [comment]
> ARPACK itself usually offers no guarantees about normalization as far as I know, so we should either normalize the vector in the test case, or add normalization to `igraph_sparsemat_arpack_rnsolve()` instead.

I would be careful here.

I tested with the internal ARPACK, so it is not ARPACK itself that was responsible for the change. This ARPACK function seems to use BLAS in some minor ways, so it is understandable that changing the BLAS changed the result. But this happens only on Windows. It does not happen on macOS/Linux (used the same OpenBLAS version on macOS). Something is fishy here.

**Comment by szhorvat** [comment]
Here's an update on this:

VS 16.9.4, OpenBLAS from vcpkg, as of today.

Configuration:

```
-- Version number from Git: 0.9.2-72-gd21e4d7e9
-- Could NOT find ARPACK (missing: ARPACK_LIBRARY)
-- Could NOT find GMP (missing: GMP_LIBRARY GMP_INCLUDE_DIR)
--
-- -----[ Build configuration ]----
-- Version:     0.9.2-72-gd21e4d7e9
-- CMake build type:        Release
-- Library type:             shared
--
-- ----------[ Features ]----------
-- GLPK for optimization:       yes
-- Reading GraphML files:       yes
-- Thread-local storage:         no
-- Link-time optimization:       no
--
-- --------[ Dependencies ]--------
-- ARPACK:                 vendored
-- BISON:                       yes
-- BLAS:                        yes
-- CXSparse:               vendored
-- FLEX:                        yes
-- GLPK:                   vendored
-- GMP:                    vendored
-- LAPACK:                 vendored
-- LibXml2:                     yes
-- OpenMP:                       no
--
-- -----------[ Testing ]----------
-- Diff tool:                  diff
-- Sanitizers:                 none
-- Code coverage:                no
-- Verify 'finally' stack:       no
--
-- --------[ Documentation ]-------
-- HTML:                         no
-- PDF:                          no
```

Notice external BLAS, internal LAPACK.

Failures:

```
  19 - test::igraph_sparsemat5 (Failed)
 332 - test::igraph_arpack_rnsolve (Failed)
 357 - example::igraph_scg_grouping (Failed)
```

**test::igraph_arpack_rnsolve**

```
  1/390 Test #332: test::igraph_arpack_rnsolve........................***Failed    0.24 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- C:/Users/daetwyler/source/repos/igraph/tests/unit/igraph_arpack_rnsolve.out 2021-02-16 16:33:28.630474400 +0100
+++ C:/Users/daetwyler/source/repos/igraph/build/tests/test_igraph_arpack_rnsolve.out   2021-05-03 16:22:24.481782700 +0
200
@@ -9,3 +9,78 @@
 -9 1 -6 -1 7 10 9 9 8 -2
 -7 1 9 -7 10 -1 -2 -5 7 6
 ===
+LM #1: vector corresponding to eigenvalue (22.0483 + 0.0000*i) is not an eigenvector, coordinate 0 differs by 0.0469 +
0.0000*i
+LM #1: vector corresponding to eigenvalue (-3.0074 + 19.2957*i) is not an eigenvector, coordinate 0 differs by -0.1156
+ -0.5803*i
+LM #1: vector corresponding to eigenvalue (-3.0074 + -19.2957*i) is not an eigenvector, coordinate 0 differs by -0.1156
 + 0.5803*i
+---
+22.0483 0
+-21.3281 0
+-3.00735 19.2957
+-3.00735 -19.2957
+---
+-0.743186 0.453391 0.0537775 0.0695675
+0.64638 -0.592157 0.437528 0.0503712
+-1.03917 -0.0922279 0.45149 -0.0857291
+-0.44602 0.716044 -0.93745 -0.114392
+-0.503134 -1.23675 -0.54948 0.224174
+0.796987 0.552517 -0.154566 0.201522
+-0.608837 0.393427 0.259957 0.162963
+-0.247019 0.355988 0.846744 -0.0224521
+0.602211 0.102521 -0.723023 -0.105184
+0.119882 0.892027 0.446938 -0.158134
+---
+LM #2: vector corresponding to eigenvalue (22.0483 + 0.0000*i) is not an eigenvector, coordinate 0 differs by -0.0469 +
 0.0000*i
+LM #2: vector corresponding to eigenvalue (-3.0074 + 19.2957*i) is not an eigenvector, coordinate 0 differs by 0.5803 +
 -0.1156*i
+---
+22.0483 0
+-21.3281 0
+-3.00735 19.2957
+---
+0.743186 0.453391 -0.0695675 0.0537775
+-0.64638 -0.592157 -0.0503712 0.437528
+1.03917 -0.0922279 0.0857291 0.45149
+0.44602 0.716044 0.114392 -0.93745
+0.503134 -1.23675 -0.224174 -0.54948
+-0.796987 0.552517 -0.201522 -0.154566
+0.608837 0.393427 -0.162963 0.259957
+0.247019 0.355988 0.0224521 0.846744
+-0.602211 0.102521 0.105184 -0.723023
+-0.119882 0.892027 0.158134 0.446938
+---
+SR: vector corresponding to eigenvalue (-12.4527 + 0.0000*i) is not an eigenvector, coordinate 0 differs by 0.0777 + 0.
0000*i
+SR: vector corresponding to eigenvalue (-3.0074 + 19.2957*i) is not an eigenvector, coordinate 0 differs by -0.5803 + 0
.1156*i
+---
+-21.3281 0
+-12.4527 0
+-3.00735 19.2957
+---
+-0.453391 1.3824 0.0695675 -0.0537775
+0.592157 0.492527 0.0503712 -0.437528
+0.0922279 0.231028 -0.0857291 -0.45149
+-0.716044 -0.308104 -0.114392 0.93745
+1.23675 -0.364076 0.224174 0.54948
+-0.552517 0.31952 0.201522 0.154566
+-0.393427 0.253665 0.162963 -0.259957
+-0.355988 -0.269917 -0.0224521 -0.846744
+-0.102521 0.620863 -0.105184 0.723023
+-0.892027 0.54492 -0.158134 -0.446938
+---
+LI: vector corresponding to eigenvalue (-3.0074 + 19.2957*i) is not an eigenvector, coordinate 0 differs by -0.3015 + -
0.5145*i
+LI: vector corresponding to eigenvalue (-3.0074 + -19.2957*i) is not an eigenvector, coordinate 0 differs by -0.3015 +
0.5145*i
+LI: vector corresponding to eigenvalue (12.1099 + 6.2729*i) is not an eigenvector, coordinate 0 differs by -0.1951 + 0.
2036*i
+---
+-3.00735 19.2957
+-3.00735 -19.2957
+12.1099 6.27293
+---
+0.175472 0.116284 -0.347475 -0.161174
+0.336982 -0.0420092 0.846454 -0.153036
+0.375793 -0.106461 -0.323846 0.0250233
+-0.831573 0.0173379 0.0138754 0.0487804
+-0.654204 0.076077 -0.713786 -0.0144191
+0.0609818 0.256637 0.57645 -0.0687288
+0.412592 0.186578 -0.587316 0.178403
+0.87835 -0.0094175 -0.622455 -0.272439
+-0.736589 -0.0564429 -0.410591 0.0788155
+0.522821 -0.0535315 -0.592325 -0.177516
+---
-- -------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
```                 

```
  2/390 Test  #19: test::igraph_sparsemat5............................***Failed    0.49 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- C:/Users/daetwyler/source/repos/igraph/tests/unit/igraph_sparsemat5.out     2021-02-16 16:33:28.777482800 +0100
+++ C:/Users/daetwyler/source/repos/igraph/build/tests/test_igraph_sparsemat5.out       2021-05-03 16:22:24.503784000 +0
200
@@ -55,16 +55,16 @@
 Eigenvalues:
 [  2.61264        0 ]
 Eigenvectors:
-[ 0.467245
-  0.571573
-  0.427081
-  0.335532
-  0.263456
-  0.130696
-  0.0780048
-  0.0731022
-  0.112985
-  0.222086 ]
+[ 0.934489
+   1.14315
+  0.854161
+  0.671064
+  0.526911
+  0.261392
+   0.15601
+  0.146204
+   0.22597
+  0.444172 ]

 == A small test graph ==

@@ -72,17 +72,17 @@
 Eigenvalues:
 [  1.35971        0 ]
 Eigenvectors:
-[ 0.352334
-  0.479071
-  0.190574
-  0.525509
-  0.140158
-   0.10308
-  0.455414
-  0.0680917
-  0.125888
-  0.0925848
-  0.259125 ]
+[ 0.704668
+  0.958143
+  0.381148
+   1.05102
+  0.280316
+  0.206159
+  0.910827
+  0.136183
+  0.251776
+   0.18517
+   0.51825 ]

 == Testing the special case solver for 1x1 matrices ==
 rnsolve:
-- -------------------------------------------------------
```

**Comment by szhorvat** [comment]
Note: `diff` is not available by default on Windows. This is why the output in the original post above is not very informative. I installed `diffutils` with chocolatey to get diff and a readable output.

In case of the `igraph_arpack_rnsolve` tests, the eigenVALUES are correct, but the eigenVECTORS appear to be completely wrong.

**Comment by szhorvat** [comment]
This should be at least checked before 0.10 is out, to see if anything improved with more recent OpenBLAS. Adding to 0.10 milestone so we won't forget. Fixing it is not necessary, just checking if anything changed.

**Comment by szhorvat** [comment]
@vtraag Unless I made a mistake, the test suite now passed with igraph 0.9.8 and newer OpenBLAS in vcpkg. Can you double-check this please?

**Comment by vtraag** [comment]
I'll check it, I'll get back to it latest early next week.

**Comment by vtraag** [comment]
Sorry, it took a bit longer to get back to this. I can confirm that when building a shared library with OpenBLAS 0.3.20 from `vcpkg` all tests pass. 

Should we perhaps also add the possibility to build in the CI with external libraries for Windows, to continue to monitor this?

**Comment by szhorvat** [comment]
Thanks Vincent!

> Should we perhaps also add the possibility to build in the CI with external libraries for Windows, to continue to monitor this?

Up to you, but keep the two existing CI tests on Windows.

**Comment by vtraag** [comment]
Let's keep the existing CI then, I believe there are only 10 parallel builds possible in Azure, and we already all use them.

**Comment by vtraag** [comment]
I've also removed this problem from the installation page.
