### ISSUE TITLE
CMake with external SuiteSparse on Windows

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1492]
I thought it would be more convenient to keep track of the separate issues for the CMake build, and only keep the overview of all CMake related issues in #1490. This issue is to keep track of the CMake build using external SuiteSparse libraries.

It is currently possible to build with the external SuiteSparse provided by `vcpkg`. However, there is one strange problem: for some reason, `libcxsparse.dll` is not copied to the `src\Debug` directory, as is the case for other settings. I am not sure why this is not done. After copying `libcxsparse.dll` over manually, almost all tests pass except `igraph_sparsemat8`.

![image](https://user-images.githubusercontent.com/6057804/97050508-c8451d00-157d-11eb-941c-c2f0eb671a10.png)

The problem arise at 

https://github.com/igraph/igraph/blob/0ea2c8ddebd34d9f910d7b4e18568181209f48ee/examples/simple/igraph_sparsemat8.c#L193

I don't understand what happens however when debugging the problem. Before it enters `igraph_sparsemat_add_cols`, `spmat.cs` exists, but after it enters `A->cs` does not exists, only `A->cs_di` exists. It then crashes on this line:

https://github.com/igraph/igraph/blob/0ea2c8ddebd34d9f910d7b4e18568181209f48ee/src/sparsemat.c#L2737

The memory addresses of `spmat.cs` and `A->cs_di` are identical. I have no idea what is happening here.

**Comment by vtraag** [comment]
I think that the problem might be that `realloc` is reallocating memory (`A->cs->p`) that is previously allocated by `cxsparse`. In principle, both libraries should be using the same runtime, so that the memory can be reallocated across libraries. It does make it a bit fragile however if there is some mismatch in runtimes. Is there some way to let the `realloc` be invocated by `cxsparse` instead of by `igraph` (I couldn't find much documentation of `cxsparse`)? I will keep looking into what exactly creates the (presumable) mismatch in runtimes.

**Comment by vtraag** [comment]
Actually, the problem was that I copied the incorrect DLL, namely the one that was not built with debug symbols (`/MD` instead of `/MDd`), hence the mismatch in runtimes. Nonetheless, I think that switching to `cs_realloc`, as proposed in #1500 will be an improvement. Generally, I think it would be good to not mix free/alloc calls across libraries.

**Comment by vtraag** [comment]
The problem is that the relevant DLL is not copied originates in `vcpkg`. It seems that this is normally done in a post-build event that invokes the `applocal.ps1` script. For some reason this script does not copy over the correct `libcxsparsed.dll`, I am not sure why. I will open an issue for this on `vcpkg`.

**Comment by vtraag** [comment]
With the merging of #1500, after the issue of copying the correct DLL has been solved, we can essentially build on all platforms against external libraries. Could we perhaps then get rid of the vendored library?

**Comment by szhorvat** [comment]
I think it's way too early for that ... Let's see if we can build all interfaces without too much trouble, in such a way that everything is linked in, and no external shared libraries are referenced. This is a must for me for the Mathematica interface.

The bundled libraries make it much easier to build igraph. Let's not hurry too much in getting rid of them, unless they explicitly cause some trouble. I wouldn't get rid of them in the next release unless there is a very good reason to. Maybe in the release after that ...

**Comment by vtraag** [comment]
Of course we must make sure that everything works before getting rid of it entirely. But if an external library is available on all platforms, this at least opens that opportunity.

I think that if external libraries work as expected, just the sake of easier building is not enough to keep the vendored library I think. Vendoring the library also comes with the added cost of updating it (which is now rarely done). Without updating we might run into bugs that have already been solved in a new release of the external library. So I would turn it around: unless there is a good reason to keep it, we should get rid of it.

**Comment by vtraag** [comment]
One note regarding the random aspect in [`cs_randperm.c`](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/430586d0b796d1a377172f21c3e1bc572878a61a/CXSparse/Source/cs_randperm.c) is that it simply requests a seed number. It does not generate random number itself, so as long as we set a seed (drawn potentially from igraph's RNG) this aspect is not problematic. We just need to make sure that that is also done (I have not checked whether that is the case).

**Comment by vtraag** [comment]
@szhorvat , I checked again building the current `develop` branch against the latest version of `suitesparse` from `vcpkg`, but I again run into the problem that the `.dll` is not copied to the build directory (when building a shared library obviously). You said that you did not run into this problem. Might that perhaps have been because you have been building a static library? If not, we will have to dig deeper.

**Comment by szhorvat** [comment]
> Might that perhaps have been because you have been building a static library?

That's probable. I'll try again and will let you know.

**Comment by szhorvat** [comment]
Yes, I used the static library.

**Comment by vtraag** [comment]
I believe I solved the problem in `vcpkg`, I just pushed a PR: https://github.com/microsoft/vcpkg/pull/16210. Once it gets merged, this issue can also be closed.

**Comment by ntamas** [comment]
Okay, that's great. I'll remove this issue from the 0.9.0 milestone so we can close the milestone after the release.
