### ISSUE TITLE
CMake: use -DMSDOS with MSYS2/MinGW-w64

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1495]
When using MSYS2, `-DMSDOS` should be added to the preprocessor flags when compiling F2C. This is needed only for F2C.

**Comment by ntamas** [comment]
We have a stanza like this in `src/f2c/CMakeLists.txt`; note that this is restricted to `MSVC` at the moment:

```
if (MSVC)
   target_compile_definitions(f2c_vendored PRIVATE MSDOS)
   target_include_directories(
     f2c_vendored
     PUBLIC
     ${CMAKE_SOURCE_DIR}/msvc/include
   )
endif()
```

Unfortunately there is no `MSYS` or `MSYS2` builtin in `CMakeLists.txt`, but we can probably use `if (WIN32)` instead of `if (MSVC)`. @szhorvat can you try this?

**Comment by szhorvat** [comment]
For now, I added 

```
if (MINGW) 
    target_compile_definitions(f2c_vendored PRIVATE MSDOS)
endif()
```

Additionally, I had to do what is described here: https://github.com/igraph/igraph/issues/1494#issuecomment-715902602

This works.

**Comment by szhorvat** [comment]
Google tells me that cmake won't define WIN32 with Cygwin, so probably the best solution is:

```
if (WIN32)
   target_compile_definitions(f2c_vendored PRIVATE MSDOS)
endif()

if (MSVC)
   target_include_directories(
     f2c_vendored
     PUBLIC
     ${CMAKE_SOURCE_DIR}/msvc/include
   )
endif()
```

@vtraag Do you know why adding `mscv/include` was needed here?

**Comment by ntamas** [comment]
>  Do you know why adding mscv/include was needed here?

Some `f2c` files try to include `unistd.h` (unless you specify some extra flags), which is not present on Windows by default. We provide the missing header in `msvc/include`. Might not be needed for MSYS / Cygwin if they properly provide such a header.

**Comment by vtraag** [comment]
There might also be some other places which are conditional on `MSVC` not on `WIN32`, we might also want to check whether that should actually be`WIN32`. I mostly didn't do this, because I assumed `WIN32` would also be defined in `msys2` and in `cygwin` when compiling with `mingw`/`gcc`, and then many `MSVC` flags are not necessary.

**Comment by szhorvat** [comment]
> I mostly didn't do this, because I assumed `WIN32` would also be defined in `msys2`

That's correct.

> and in `cygwin`

That is **not** correct (looked it up earlier today, but lost the link).

----

So things that are usually needed for Windows should use `WIN32`, things that are needed only for MSVC, but not for MinGW, should use `MSVC`. 

Cygwin is pretending to be Unix, so I assume it can be considered to be Unix.

**Comment by szhorvat** [comment]
@vtraag Made the one change I discussed above, https://github.com/igraph/igraph/commit/2ebd82a1bd6555cd72079a844672ea01f890ef8c, but leaving this open in case you want to make more changes elsewhere.

**Comment by ntamas** [comment]
@vtraag Is this working now, can we close this?

**Comment by vtraag** [comment]
No not yet, there is probably still an issue with building static libraries on MinGW, I will check that out next.
