### ISSUE TITLE
igraph_is_neginf is misimplemented

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1496]
When compiling with MSYS2, I got this error:

```
C:/msys64/home/username/Repos/igraph/src/math.c: In function 'igraph_is_neginf':
C:/msys64/home/username/Repos/igraph/src/math.c:261:21: error: comparison of constant '-1' with boolean expression is always false [-Werror=bool-compare]
  261 |     return isinf(x) == -1;
      |                     ^~
```

The function tries to check for a negative infinity using `isinf(x) == -1`.

This is incorrect, see https://en.cppreference.com/w/c/numeric/math/isinf

The phrasing there can be misleading, but this function effectively returns a true or a false, and cannot distinguish between positive and negative infinity.

We need to:

 - Figure out where this came from. `isinf` is a C99-only. There may have been some non-standard `isinf` which behaved differently.

 - Why this results in a compilation error at all. If this were C++, I'd understand. I'm confused about how the compiler is even able to detect that the result should be a bool with plain C.

**Comment by szhorvat** [comment]
At least GNU libc is indeed documented to return -1: https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html That answers where this comes from.

**Comment by szhorvat** [comment]
The answer to the second is that MinGW currently uses the following implementation: `#define isinf(x) (fpclassify(x) == FP_INFINITE)`, which is a Boolean expression. On macOS/Linux, we have different implementations (through intrinsics) and the result is probably an `int`.

**Comment by szhorvat** [comment]
Eventually, we should start requiring a certain amount of C99 support (MSVC has _some_, but not all), and deprecate these inf/nan-checking functions in igraph.

**Comment by ntamas** [comment]
> The answer to the second is that MinGW currently uses the following implementation: #define isinf(x) (fpclassify(x) == FP_INFINITE), which is a Boolean expression.

Furthermore, we use ` #define isinf(x) (!_finite(x) && !_isnan(x))` for MSVC (see the same file). I'll push a simple fix to the `master` branch and then we can merge it into all the other branches.
