### ISSUE TITLE
CMake: Write new installation/compilation instructions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1497]
Now is the time to write new installation/compilation instructions for the cmake build system for all platforms, before we forget the details.

There are some non-trivial issues such as https://github.com/igraph/igraph/issues/1494#issuecomment-715902602

**Comment by szhorvat** [comment]
MSYS2 notes:

Required packages:

```
mingw-w64-x86_64-toolchain
mingw-w64-x86_64-cmake
bison 
flex
```

Optional dependencies:

```
mingw-w64-x86_64-gmp
mingw-w64-x86_64-libxml2
```

Optional external libraries:

```
mingw-w64-x86_64-openblas-0.3.10-2  
mingw-w64-x86_64-suitesparse-5.7.2-1
mingw-w64-x86_64-arpack
mingw-w64-x86_64-glpk
```

It is critical to use the `mingw-w64-x86_64-cmake` package and not the `cmake` one. The latter won't work. `cmake` must be run as `cmake .. -G"Unix Makefiles"`.

Then open `CMakeCache.txt` with a text editor and adjust the `IGRAPH_...` settings, then re-run `cmake ..`, finally compile with `make`. Use `make check` to run the tests.

**Comment by vtraag** [comment]
Is there any specific reason to pick `"Unix Makefiles" over "MinGW Makefiles" @szhorvat? I don't immediately notice any difference though.

**Comment by szhorvat** [comment]
I haven't tried any other generators. The point I was making was that one _must_ explicitly set a generator, as the default for `mingw-w64-x86_64-cmake` is a VS project file (and if left at that setting, it will even fail).  It cannot be left at the default.

----

I just looked up "MinGW Makefiles" and it seems clear that we don't want that: https://cmake.org/cmake/help/latest/generator/MinGW%20Makefiles.html

>  The generated makefiles use cmd.exe as the shell to launch build rules. They are not compatible with MSYS or a unix shell.

----

There is also "MSYS Makefiles". That will probably work. It's unclear if it has any advantages or disadvantages compared to "Unix Makefiles". We should certainly try it.

https://public.kitware.com/pipermail/cmake-developers/2015-July/025801.html

**Comment by vtraag** [comment]
> the default for mingw-w64-x86_64-cmake is a VS project file (and if left at that setting, it will even fail).

Perhaps this was because the `mingw64/bin` directory was not on your Windows path?

> I just looked up "MinGW Makefiles" and it seems clear that we don't want that

I am not sure why, for me this works just as well as "Unix Makefiles". I understand it uses `cmd.exe`, but that is not necessarily a problem. It seems that `ctest` also invokes `cmd.exe` also when building with "Unix Makefiles".

**Comment by szhorvat** [comment]
> I am not sure why, for me this works just as well as "Unix Makefiles".

I have not actually tried it because the cmake docs gave me the impression that it wouldn't work. If it works with no problems, we can include that too. I assume it doesn't solve the problem with running the tests, right? The "MSYS Makefile" generator doesn't (I tried that).

**Comment by szhorvat** [comment]
In the new compilation / installation instructions, we should document the meaning of each option. With autotools, `./configure --help` could at least give a one-line description. With `cmake`, we don't have this. 

Both enabling thread-local storage, and the verify-finally-stack debugging option came up on the forum recently. Users should be able to learn about these, and use them when necessary.

**Comment by ntamas** [comment]
We can add a new target named `help` that prints a short summary of the options; ideally we should simply put the options in a text file and then let CMake print that.

Also note that the CMake options actually have help strings, and those are visible on the CMake GUI.

**Comment by szhorvat** [comment]
> Also note that the CMake options actually have help strings, and those are visible on the CMake GUI.

Where can I see the help strings in the GUI?

<img width="832" alt="image" src="https://user-images.githubusercontent.com/1212871/97182775-3f0c3100-179d-11eb-9f62-ddc2e427539b.png">

**Comment by ntamas** [comment]
Hmmm, it's in the bottom status bar in the `ncurses` GUI, which I am using from the command line on macOS. I didn't know that the "real" GUI omitted this and it's a pity if it did :(

**Comment by ntamas** [comment]
Also, it looks like the "real" GUI is grouping options based on the prefix of the option name before the first underscore, which I also didn't know -- it's good to keep that in mind when coming up with new option names. Preferably all our options should be prefixed with `IGRAPH_` to ensure that they are grouped in the same place.

**Comment by szhorvat** [comment]
Ah, I see now! They're the same descriptions which are included as `//`-comments in CMakeCache.txt

**Comment by szhorvat** [comment]
Turns out that the messages are in the tooltips:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1212871/97184204-f5bce100-179e-11eb-8515-d5d68fdb3a5e.png">

There's no doubt `ccmake` is more convenient.

**Comment by szhorvat** [comment]
This should be linked from the instructions: https://cmake.org/cmake/help/latest/guide/user-interaction/index.html

**Comment by vtraag** [comment]
The difference between `MinGW Makefiles` and `Unix Makefiles` is that the former uses `mingw32-make` and the latter uses `make`.  According to the [MinGW website](http://mingw.org/wiki/FAQ) the difference between the two is:
> - What's the difference between make and mingw32-make?
> The "native" (i.e.: MSVCRT dependent) port of make is lacking in some functionality and has modified functionality due to the lack of POSIX on Win32. There also exists a version of make in the MSYS distribution that is dependent on the MSYS runtime. This port operates more as make was intended to operate and gives less headaches during execution. Based on this, the MinGW developers/maintainers/packagers decided it would be best to rename the native version so that both the "native" version and the MSYS version could be present at the same time without file name collision.

The description is actually really bad, it is not exactly clear whether they refer to `make` or `mingw32-make` at various places in this description. It is not exactly clear to me what further differences this entails.

By the way: don't let the naming fool you: it is installed using ` mingw-w64-x86_64-make`.

**Comment by szhorvat** [comment]
The draft is here: https://igraph.discourse.group/t/draft-document-for-installation-with-cmake/504

**Comment by szhorvat** [comment]
This is basically complete, it just needs to be put on the website.

Currently, the `INSTALL` file points to the website. Therefore, we should archive the pre-0.9 instructions instead of completely removing them. In fact, it might not be a bad idea to have everything in the `INSTALL` file after all, just in case someone needs to come back to the old instructions 10 years from now ...

**Comment by ntamas** [comment]
I will put these on the website when 0.9 is released.

The only part that seems to be missing from the installation instructions is the MSVC part. Can anyone take the responsibility of writing that up? I still don't have a Windows machine that I could test on, although it would probably be time to get one...

**Comment by szhorvat** [comment]
I think the only difficulties are installing bison/flex, which will not be needed for the release package anyway. Otherwise the instructions should be the same. I'll take a look at this later.

**Comment by szhorvat** [comment]
Any opinions on also putting the instructions in `INSTALL`?  

Motivation: At some point in the future someone might want to compile an old igraph version to reproduce something. The instructions from the website will be gone by then. It would be good to bundle the instructions with the release.

**Comment by ntamas** [comment]
They used to be there and then we moved them to the website :) But you are right, ideally the release should contain the installation instructions. One problem right now is that we need to duplicate the instructions in both places, but since hopefully we won't change them once the migration to CMake is complete, I'm okay with this one-time duplication.

**Comment by ntamas** [comment]
As agreed in this morning's dev talk: most of the instructions will be moved to the user manual and the website will have a short "for the impatient" section only, with a link to the corresponding section of the HTML docs.

I'll convert the instructions to DocBook format.

**Comment by ntamas** [comment]
Installation instructions are moved to the manual; website updated, waiting for deployment. I consider this issue as done now.
