### ISSUE TITLE
CMake: compatibility with Intel compiler

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1498]
We need to add the following options for the Intel compiler: `-wd279 -wd188 -wd592 -wd161`

We need to remove: `-Wno-varargs`

Tested with:

```
> icc --version
icc (ICC) 15.0.2 20150121
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.
```

To use the intel compiler, set `CC=icc` and `CXX=icpc` before running `cmake`.

**Comment by szhorvat** [comment]
@ntamas I need help here, as I'm not comfortable with cmake.

Here's my suggestion for the `use_all_warnings` macro:

```cmake
macro(use_all_warnings TARGET_NAME)
  if(MSVC)
    target_compile_options(${TARGET_NAME} PRIVATE /W4)
  else()
    target_compile_options(${TARGET_NAME} PRIVATE 
      -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -Wno-sign-compare
      $<$<C_COMPILER_ID:GNU,Clang,AppleClang>:-Wno-varargs>
      $<$<C_COMPILER_ID:Intel>:-wd279 -wd188 -wd592 -wd161>
    )
  endif()
endmacro()
```

Here's the list of compiler IDs: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html

I checked only the `C_COMPILER_ID` here, but in reality we have both a C and a C++ compiler, which may be different. E.g. one could set `CC=clang CXX=g++` for whatever reason ... I guess there is no need to let people do that, so we can check only the C compiler.

Other things we can do: 

 - Instead of adding `-Wno-varargs` only for gcc, clang and Apple clang, we can choose to add it when the compiler is NOT Intel. 

 - We could choose to use `-Werror` only with gcc, clang, Apple clang, and let other compilers show warnings without aborting compilation.

**Comment by szhorvat** [comment]
Note: The `if(MSVC)` should not be changed a `COMPILE_ID` check [because `MSVC` is set for any compiler that acts like MSVC](https://cmake.org/cmake/help/latest/variable/MSVC.html), even if it is not actually MSVC. I believe this is how the Intel compiler behaves on Windows, but I have no access to it to test it.

**Comment by ntamas** [comment]
Seems okay to me!

As for `-Werror`, I'd rather keep it unconditionally and just turn off specific warnings if they are too annoying (but let's try to use such exceptions sparingly). Also, let's keep `-Wno-varargs` by default and exclude it only for the `Intel` compiler.

**Comment by szhorvat** [comment]
Fixed by https://github.com/igraph/igraph/commit/d5431e840def6263df2524e76e0b823ae87031a1
