### ISSUE TITLE
CMake fails when git is not installed

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1503]
At the moment, CMake fails when `git` is not installed, without a clear warning that `git` could not be found. Perhaps we can call [`FindGit`](https://cmake.org/cmake/help/v3.19/module/FindGit.html?highlight=findgit) and report a proper error when `git` is not installed? This if of course only necessary when installing from the `git` repository. From a packaged version (which should contain a fixed version), `git` should not be necessary.

**Comment by ntamas** [comment]
The commit referenced above should fix this issue -- please test and let me know if it doesn't.

**Comment by vtraag** [comment]
Yes, that works, thanks! However, it is now not clear that `git` is missing. Perhaps we should also issue a warning that `git` was not found?

**Comment by ntamas** [comment]
Done in 31188f05
