### ISSUE TITLE
CMake: error from "variables set to NOTFOUND"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1505]
I regularly encounter the following:

 - I run `cmake ..` in `build`
 - Configuration fails because of some missing dependencies, e.g. GLPK
 - I either run `ccmake` or edit CMakeCache.txt and set it to use internal GLPK

At this point, running `cmake ..` again results in the following error:

```
-- igraph configured successfully.
--  
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/Users/szhorvat/Repos/igraph-main/igraph/src/GLPK_INCLUDE_DIR
   used as include directory in directory /Users/szhorvat/Repos/igraph-main/igraph/src

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Now I can manually remove `GLPK_INCLUDE_DIR`, and then not only the configure step, but also the generation step will succeed. @ntamas: I wonder if there is a way to improve this and make it more user friendly.

For some reason, when I use `ccmake` or `cmake-gui`, it still show the warning above, but the generation step doesn't actually fail. Perhaps there's an option to ignore the NOTFOUND variable if it's not used anyway? Still, this is a user experience issue. We should expect that many/most users of igraph have little to no experience with cmake.

**Comment by szhorvat** [comment]
This happens specifically with GLPK, not with other things that are also not found, such as ARPACK or CXSparse

**Comment by ntamas** [comment]
I have pushed a patch that is supposed to fix it; please test.

**Comment by szhorvat** [comment]
Yes, fixed.

**Comment by szhorvat** [comment]
There is a very similar failure when GMP is not present. Can you please take a look @ntamas ?

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/Users/szhorvat/Repos/igraph-main/igraph/src/bliss/GMP_INCLUDE_DIR
   used as include directory in directory /Users/szhorvat/Repos/igraph-main/igraph/src/bliss

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by szhorvat** [comment]
I think this fixes it, re-closing, https://github.com/igraph/igraph/commit/d992263b9a18327d38e8dbad6070efbba5fef9a7

Take a quick look @ntamas and let me know if it looks wrong
