### ISSUE TITLE
0.8.3 (but not 0.8.2) build fails on RHEL 7 (bliss/graph.cc)

### ISSUE THREAD

**Issue by galaxyrise** [igraph/igraph#1513]
It appears the changes in 0.8.3 to bliss/graph.cc result in the error below on my system:

* bliss/graph.cc: In constructor ‘bliss::AbstractGraph::AbstractGraph()’:
* bliss/graph.cc:72:13: error: ‘stdout’ was not declared in this scope

**Comment by ntamas** [comment]
I think this has recently been fixed in https://github.com/igraph/igraph/commit/6d6b996e65953430274f50921df45c4ff6c75a13 . Which compiler were you using?

**Comment by galaxyrise** [comment]
Great, thanks.  I'm using gcc 4.8.5.

**Comment by szhorvat** [comment]
@galaxyrise Can you confirm that the current `master` branch from GitHub compiles on your system? Please verify this if you can.
