### ISSUE TITLE
Warnings on Linux

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1520]
I will list a few warnings that stood out to me when compiling on Linux with various compilers. Most can probably be ignored, but some we may want to look into. I don't have time to examine each one in detail, so I am recording them here. Feel free to fix some of these if you think they're relevant.

PGI compiler version 2020:

**(suggestion by Sz: don't fix)**
```
"/home/szhorvat/Repos/igraph/src/f2c.h", line 165: warning: incompatible
          redefinition of macro "abs" (declared at line 332 of
          "/usr/local/pgi/linux86-64-llvm/20.1/include/math.h")
  #define abs(x) ((x) >= 0 ? (x) : -(x))
          ^
```

```
"/home/szhorvat/Repos/igraph/src/igraph_math.h", line 71: warning: incompatible
          redefinition of macro "fmin" (declared at line 404 of
          "/usr/local/pgi/linux86-64-llvm/20.1/include/math.h")
      #define fmin(a,b) igraph_fmin((a),(b))
              ^
```

**(fixed)** Is a return missing here? -->
```
"/home/szhorvat/Repos/igraph/src/math.c", line 84: warning: expression has no
          effect
          IGRAPH_NAN;
          ^
```

**(fixed)**
```
"/home/szhorvat/Repos/igraph/examples/simple/biguint.c", line 44: warning:
          integer conversion resulted in a change of sign
      igraph_biguint_set_limb(&A, UINT_MAX);
```

GCC 10.2:

**(suggestion by Sz: don't fix)**
```
/home/szhorvat/Repos/igraph/src/f2c/signal_.c: In function ‘signal_’:
/home/szhorvat/Repos/igraph/src/f2c/signal_.c:17:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   17 |  return (ftnint)signal(sig, proc);
      |         ^
```

```
/home/szhorvat/Repos/igraph/src/f2c/uninit.c: In function ‘ieee0’:
/home/szhorvat/Repos/igraph/src/f2c/uninit.c:264:9: warning: implicit declaration of function ‘fedisableexcept’; did you mean ‘feraiseexcept’? [-Wimplicit-function-declaration]
  264 |     if (fedisableexcept(FE_ALL_EXCEPT)==-1)
      |         ^~~~~~~~~~~~~~~
      |         feraiseexcept
/home/szhorvat/Repos/igraph/src/f2c/uninit.c:266:9: warning: implicit declaration of function ‘feenableexcept’; did you mean ‘feraiseexcept’? [-Wimplicit-function-declaratio]
  266 |     if (feenableexcept(FE_DIVBYZERO|FE_INVALID|FE_OVERFLOW)==-1)
      |         ^~~~~~~~~~~~~~
      |         feraiseexcept
```

**Comment by szhorvat** [comment]
Fixed the one in `math.c`: https://github.com/igraph/igraph/commit/4463d2c1ebc5b55a20afaa2b3514767a4af98147

@gaborcsardi Can you confirm that you left out the `return` by accident and not on purpose? The code seems to come from R, https://github.com/wch/r-source/blob/f8d4d7d48051860cc695b99db9be9cf439aee743/src/nmath/chebyshev.c#L74

**Comment by gaborcsardi** [comment]
Sure.

**Comment by szhorvat** [comment]
Regarding the "cast from pointer to integer of different size" in f2c:

As far as I can tell, Fortran does not have pointers, so it represents them with an `integer` of the size size as the system's pointer type. `signal` returns a pointer, but in Fortran this becomes and integer. In this case, somehow we end up with an integer type that does not match the size of the pointer type (`ftnint` in f2c.h). If I look at various versions of f2c on the internet, sometimes `ftnint` is an `int`, sometimes a `long`, sometimes conditionally an `int` even on 64-bit systems. We have it defined as an `int`.

Luckily, `signal_` is not used anywhere in our codebase.

I don't want to mess with things I don't understand, and given that this issue is with an unused function anyway, I'd rather not try to fix this warning.

**Comment by ntamas** [comment]
Fixed the problems in `src/f2c/uninit.c` and `examples/simple/biguint.c`; at least I think as I cannot test it with the compilers you mentioned.

**Comment by szhorvat** [comment]
@ntamas The one in `uninit.c` was a bit more complicated. It is fixed now.
