### ISSUE TITLE
Eliminate duplicated function prototypes

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1521]
All duplicated function prototypes should be eliminated in favour of proper internal headers. Some tests repeat the prototype of some internal functions so that they can be tested. The danger is that once a function is changed, we may forget to update its prototype in multiple places.

Instances of such duplication should be listed in this issue, so we won't forget to take care of them.

Note: Recent GCC versions are good at detecting such issues when link-time optimization is enabled.

### Incomplete list:

 - [x] `igraph_i_all_st_cuts_pivot` in `st-cuts.c` and the test `igraph_all_st_cuts.c`
 - [x] Two functions in the test `igraph_i_layout_sphere`
 - [x] `igraph_i_rewire` (formerly `igraph_rewire_core`) in the test `igraph_rewire.c` (b168868192cc5609ed282d59852cdd47a377a81e)
 - [x] `igraph_i_layout_merge_dla` in the test `igraph_layout_merge.c`

**Comment by szhorvat** [comment]
I just fixed a mismatched prototype in https://github.com/igraph/igraph/commit/6644740d8e4830da029a7d25ec0877aa34d1afbf

**Comment by ntamas** [comment]
Fixed all the function prototypes explicitly listed in the issue description. @szhorvat can you think of a structured way to find more of these prototypes before we close the issue?

**Comment by szhorvat** [comment]
I manually  checked all the tests that were marked as "internal". If any other than these used non-public functions, they would fail with the DLL build on Windows. Thus I am sure that there are no others.

I think this can be closed.

However, there are several *public* functions with `_i_` naming, and we should make a decision about what to do with those before 0.9.

**Comment by ntamas** [comment]
Moved the discussion about the `_i_` functions to Slack and closing this.
