### ISSUE TITLE
CMake: Error and warning messages contain the full path

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1524]
[cmake passes absolute paths to the compiler.](https://stackoverflow.com/a/45859872) The consequence is that igraph's error and warning messages will contain the full path to source files. It will even include your username.

This was discussed here for the Python interface: https://github.com/igraph/python-igraph/issues/293  Now it affects the Mathematica interface as well (due to using cmake), and of course R too. This issue is to brainstorm about solutions that can be implemented fully or partially within the C core.

**Comment by szhorvat** [comment]
One potential solution is to strip the unnecessary part at runtime. I had some creative ideas, but ultimately this would be an ugly hack because we don't even know if all compilers use the full path (I am almost certain that some won't). It would be hard to make it portable.

Another, better solution was suggested by Vincent in chat: This [SE answer](https://stackoverflow.com/a/27990434) shows a solution to define a `FILE_BASENAME` macro dynamically for each compiled file. In fact, gcc has such a builtiin macro ([__BASE_FILE__](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html#Common-Predefined-Macros)), but the cmake solution should work with all compilers.

**Comment by ntamas** [comment]
The SO solution looks good; one thing that I don't really like about this, though, is that we would need to expose `FILE_BASENAME` in `igraph_error.h` (since this is where `IGRAPH_ERROR` is defined). What do you think? Shouldn't we at least prefix `FILE_BASENAME` with `_IGRAPH_` or something similar to indicate that it is an internal thing? Also, the `IGRAPH_ERROR` macro should probably be defined in terms of `__FILE__` if `_IGRAPH_FILE_BASENAME` is not defined, at least if we keep it in the public `igraph_error.h` header.

**Comment by szhorvat** [comment]
Yes, good point, `igraph_error.h` is a public header that gets installed on the user's machine. 

We can also have

```
#ifndef IGRAPH_FILE_BASENAME
#define IGRAPH_FILE_BASENAME __FILE__
#endif
```

in `igraph_error.h`

**Comment by ntamas** [comment]
This is now fixed in https://github.com/igraph/igraph/commit/6535c4f6019a5d5ba29509f51f2840ab4ee563cd . I have left a few occurrences of `__FILE__` in vendored code, though. Let me know what you think and feel free to close this if you think it's good enough.

**Comment by szhorvat** [comment]
I'm not sure if you saw my message in chat (it's getting a bit chaotic in there), so I'll repeat here.

Technically, anything starting with `__` is reserved, https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers Although anything with IGRAPH in the name is unlikely to conflict (unless the compiler takes an existing thing with IGRAPH in the name and sticks some `__`s on it)

Opinions @ntamas ?

**Comment by vtraag** [comment]
Personally I think it might be better then to remove the underscores, and simply use `IGRAPH_FILE_BASENAME`, that way we are sure to comply with given standards.

**Comment by szhorvat** [comment]
@vtraag Already done!

**Comment by vtraag** [comment]
@szhorvat, there's one last point I wanted to discuss (see https://github.com/igraph/igraph/commit/6535c4f6019a5d5ba29509f51f2840ab4ee563cd#r43904027).

**Comment by ntamas** [comment]
This is now fixed but I don't know whether my solution works on Windows as well so let's wait for the CI checks to finish.
