### ISSUE TITLE
converting a neo4j graph into a graph object that igraph accepts

### ISSUE THREAD

**Issue by AprilSong0323** [igraph/igraph#1533]
Hello,

My project requires analyzing graphs stored in Neo4j. I can import a neo4j graph into R using "neo4r" package.

I am writing to ask if there is a function that I could convert a neo4j graph into a graph object that igraph accepts?

Thanks in advance

**Comment by szhorvat** [comment]
As noted in the issue template, we prefer to reserve the issue tracker for bug reports and feature requests. Furthermore, this is the issue tracker for the C library, not its R interface. Please use the forum for support questions: https://igraph.discourse.group/
