### ISSUE TITLE
CMake: ctest should show the output upon failure

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1535]
This is how a failure is currently reported:

https://travis-ci.org/github/igraph/igraph/jobs/741864231#L1369

There should be more information, such as the diff between the expected outputs, and the return code.

Also, this line seems to be obsolete: https://github.com/igraph/igraph/blob/feature/cmake-build/.travis.yml#L52

**Comment by vtraag** [comment]
To be clear, the `diff`s are available from the directory in which the tests were run. Nonetheless, I agree that it would be helpful to also print the diffs immediately to standard output.

**Comment by szhorvat** [comment]
@vtraag Do you know of a way to see the diffs with Travis?

**Comment by ntamas** [comment]
Added a suggestion on our Slack channel in the relevant thread.

**Comment by ntamas** [comment]
This is now implemented so closing.
