### ISSUE TITLE
CMake: generated pkg-config file has wrong information

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1537]
I compiled igraph on macOS with:

 1. GMP
 2. external GLPK
 3. external BLAS/LAPACK using Apple's vecLib

This is what pkg-config tells me about how to link to igraph:

```
$ pkg-config --static --libs igraph
-L/Users/szhorvat/local/lib -ligraph -lm -lgmp
```

This is wrong.

 1. It has `-lgmp`
 2. It **does not** have `-lglpk`, which is needed
 3. It **does not** have `-framework Accelerate`, which is also needed for vecLib

**Comment by szhorvat** [comment]
I never checked if the pkg-config file was correct with autotools, BTW. However, with cmake, it is definitely not correct.

**Comment by szhorvat** [comment]
One problem appears to be that when some variables are set to `AUTO` then lines such as these don't work:

```
if(NOT IGRAPH_USE_INTERNAL_BLAS)
```

It works as it should if `IGRAPH_USE_INTERNAL_BLAS` is `ON` or `OFF` but not if it is `AUTO`.

----

I also tried to include the _actual_ libraries instead of using hard-coded ones, and ended up with this not-yet-working code:

```
set(PKGCONFIG_LIBS_PRIVATE "-lm")
if(IGRAPH_GRAPHML_SUPPORT)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${LIBXML2_LIBRARIES})
endif()
if(IGRAPH_GMP_SUPPORT)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${GMP_LIBRARY})
endif()
if(NOT IGRAPH_USE_INTERNAL_BLAS)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${BLAS_LIBRARIES})
endif()
if(NOT IGRAPH_USE_INTERNAL_CXSPARSE)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${CXSPARSE_LIBRARIES})
endif()
if(IGRAPH_GLPK_SUPPORT AND NOT IGRAPH_USE_INTERNAL_GLPK)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${GLPK_LIBRARIES})
endif()
if(NOT IGRAPH_USE_INTERNAL_LAPACK)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${LAPACK_LIBRARIES})
endif()
if(NOT IGRAPH_USE_INTERNAL_ARPACK)
  list(APPEND PKGCONFIG_LIBS_PRIVATE ${ARPACK_LIBRARIES})
endif()
list(REMOVE_DUPLICATES PKGCONFIG_LIBS_PRIVATE)
configure_file(${CMAKE_SOURCE_DIR}/igraph.pc.cmake.in ${CMAKE_BINARY_DIR}/igraph.pc @ONLY)
```

Remaining problems here (other than not handling AUTO): 
 - `-lm` should not be hard-coded
 - now that `PKGCONFIG_LIBS_PRIVATE` is a list, I am not sure what is the best way to convert it to a space-separated string.

**Comment by szhorvat** [comment]
Additionally, we need to link to the C++ standard library as some functions in igraph are implemented in C++.  I _think_, but I am not sure, that if we do so, we do not need to explicitly link to the math library (`-lm`).

Now a question is: how to find the correct linker flag in a platform independent way? Even if we don't consider Windows, there are two commonly used variants: libc++ and libstdc++.

**Comment by vtraag** [comment]
I would imagine that we would translate the `AUTO` value into something that is changed `OFF`, if the external libraries are found, and set to `ON` otherwise. If we let it be `AUTO` we would have to consider this in every statement, which is quite inconvenient.

**Comment by ntamas** [comment]
> `-lm` should not be hard-coded

This is trickier than it seems; the obvious choice would be to use `${MATH_LIBRARY}`, which we populate with `find_library(MATH_LIBRARY m)`, but this gives the full path of the library on macOS, i.e. something like `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libm.tbd`. Not nice at all.

**Comment by vtraag** [comment]
Is it necessary to link to the math library explicitly? From what I read online it seems as though it is already contained in the system C library on macOS, and is not in a separate library. I don't have Mac, so I'm not sure if that is correct though.

**Comment by szhorvat** [comment]
A bigger issue is how to specify that one needs to link to the C++ standard library.

It appears that cmake sidesteps the issue by using the C++ compiler command to link all the test programs. That implicitly includes the relevant options without needing to spell them out. However, if one uses the C compiler for linking, it is necessary to explicitly include the same C++ standard library that igraph was compiled with.

**Comment by ntamas** [comment]
> Is it necessary to link to the math library explicitly?

It is platform-dependent. I remember having bitten earlier by not including `-lm` -- igraph then failed on some Linux flavours and not on others. I know for sure that it is not linked to automatically in Ubuntu 16.06, which is not that far in the past. We would either need to test igraph thoroughly in all relevant distributions to ensure that we don't need to link to it, or just put up with it and add `-lm` unconditionally. The good news is that the `pkg-config` file is used mostly on Linux and, to a lesser extent, on macOS, and the math library is called `m` in both platforms, so we are probably okay with hardcoding `-lm`. Unless you guys know that `pkg-config` has already been adopted on Windows, which I wouldn't find too surprising now that we even have Windows Subsystem for Linux :)

**Comment by ntamas** [comment]
> A bigger issue is how to specify that one needs to link to the C++ standard library

If I remember correctly, `libstdc++` is the one that ships with `gcc` / `g++`, and `libc++` is a newer one. There's also Apache `libstdcxx`. Furthermore, the licenses of these libraries are not interchangeable; for instance, mainline `libstdc++` is now GPLv3, while `libc++` is MIT/UIUC (dual-licensed), so even if the `pkg-config` file specifies one, you might prefer another one for licensing reasong (assuming that they are ABI-compatible).

**Comment by szhorvat** [comment]
I believe they are not ABI-compatible. So one must link to whatever igraph was originally compiled with.

libstdc++ usually comes with gcc, but it can also be used with clang. Software targeting older macOS uses libstdc++ by default. On macOS, the new default is libc++.

This seems so complicated to get right that I wonder if it's even worth trying to get a _correct_ pkg-config file ... Would it be better to get a semi-correct one as a starting point (not auto-installed) and write instructions for Linux distro maintainers on how to fix it up and make it fully correct? If targeting one specific system, it is easy to write a correct one. What is difficult is to auto-generate one that is correct on any platform.

**Comment by ntamas** [comment]
@szhorvat

> It does not have -lglpk, which is needed

I believe this should now be fixed with my latest commit; please check and report back.

> It does not have -framework Accelerate, which is also needed for vecLib

After applying my latest fix, the library list now includes `-lblas` if you use a vendored BLAS. On macOS this seems to be enough.

Test file (`test.c`):

```
#include <igraph.h>

int main(int argc, char** argv) {
    igraph_matrix_t a;
	igraph_vector_t x, y;

	igraph_blas_dgemv(0, 1, &a, &x, 0, &y);

	return 0;
}
```

Command line to compile it, invoked from the CMake build folder:

```
$ gcc -o test test.c -I../include -Iinclude -Lsrc -ligraph -lblas
```

This seems to indicate that `-framework Accelerate` is not needed, and the resulting executable links to `blas` in the `Accelerate` framework:

```
$ otool -L test
test:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by szhorvat** [comment]
> I believe this should now be fixed with my latest commit; please check and report back.

Yes, works.

**Comment by szhorvat** [comment]
To test that everything works, please try a static build, then compile `igraph_realize_degree_sequence.c` from the test suite.

I need to use the following for linking to succeed:

```
cc igraph_realize_degree_sequence.c -I$HOME/local/include/igraph $HOME/local/lib/libigraph.a -lblas -llapack -lc++
```

So I confirm that `-lblas` works on macOS, but `-llapack` is also necessary, and there's the issue of `-lc++`.

Alternatively, I can do:

```
cc -c igraph_realize_degree_sequence.c -I$HOME/local/include/igraph
c++ igraph_realize_degree_sequence.o $HOME/local/lib/libigraph.a -lblas -llapack
```

Notice that I compiled with the C compiler, linked with the C++ one, and omitted the `-lc++`.

**Comment by ntamas** [comment]
> This seems so complicated to get right that I wonder if it's even worth trying to get a correct pkg-config file ... Would it be better to get a semi-correct one as a starting point (not auto-installed) and write instructions for Linux distro maintainers on how to fix it up and make it fully correct?

I, for one, kinda like the fact that I can just run `make install` and I automatically get a `pkg-config` file on my system that I can then use in other projects with `pkg-config --cflags --libs igraph`, so I'd keep it auto-installed and deal with the bug reports until we cover most of the use-cases out there.

As for the `libc++` vs `libstdc++` issue, I would try to test for these two cases explicitly with CMake's own `find_library()` (if we can force it to use the _C_ linker), and not bother with the more arcane stuff. People who use custom, non-default C++ implementations probably know what they are doing and they can fix the `pkg-config` file as well if needed.

**Comment by szhorvat** [comment]
Sounds good.

**Comment by ntamas** [comment]
As we agreed on Slack: we just use `-lstdc++` or `-lc++` in the generated `igraph.pc`, depending on whether we are on macOS or not.
