### ISSUE TITLE
igraph_diameter() mishandles null graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1538]
`igraph_diameter()` mishandles null graph, and returns 0 as diameter. It should return infinity.

**Comment by ntamas** [comment]
Is this also related to the broader discussion about null graphs in #1539? I understand that several graph-theoretic measures are ill-defined for null graphs, so maybe it would be better not to take sides here (in terms of zero vs infinity) and just return `NaN` instead (now that the diameter function uses `double`s, we can do that easily).

**Comment by vtraag** [comment]
I haven't looked in detail either, but I like the neutral point of view. That way, people can (or even have to) make a conscious decision about how to take them into account. There might be some problem how to deal with these values in other calculations (i.e. some averages of some functions might involve `NaN`s then), but I'm sure that we can also find a workable definition.

**Comment by ntamas** [comment]
Well, the obvious way of forcing the user to make a conscious decision about how to handle the diameter of the null graph is to throw an error -- but even that might go unnoticed in C where lazy programmers notoriously "forget" to check return values for error codes. NaN is similar in that sense as it can also go unnoticed easily and then blow up later.

If our goal is to force the user to make a conscious decision, I think either is sufficient but it will cause headaches for some when they don't think about null graphs and then it blows up in their faces later. If we want to make sure that things don't "blow up", we should choose a sensible default instead as @szhorvat proposed.

After having read #1539, I also feel that treating null graphs as disconnected is more logical than treating it as connected. However, treating it as disconnected implies that its diameter is infinite.

**Comment by szhorvat** [comment]
This issue is specific to diameter(). I'll submit a PR so you can take a look before merging. I'll return NaN for the null graph.

**Comment by szhorvat** [comment]
> However, treating it as disconnected implies that its diameter is infinite.

Yes, that is why I originally wanted to return infinity. 

I think that achieving **full** consistency is not realistic, but we should still try to stay reasonable.  We can do:

 1. return NaN
 2. return +Inf
 3. return NaN if unconnected=true, otherwise return +Inf

I'm fine with any of these.  I'll go with 1. unless someone suggests another solution.

----

One example to show why full consistency is not even convenient all the time: It is much more reasonable to return Inf for the girth of acyclic graphs than zero. `igraph_girth` returns 0.  But it returns an `igraph_integer_t`, so it doesn't have the option to return infinity ... I wouldn't change it in this case, it's just not worth it. However, I did change it in the Mathematica interface, where I catch the zeros and translate them to infinity.

**Comment by ntamas** [comment]
Thanks for the PR!

Can you explain why you changed your mind and return NaN instead of infinity? I did not find my arguments conclusive or particularly convincing, that's why I'm interested.

**Comment by szhorvat** [comment]
I don't have a definitive answer to whether it should be NaN or Infinity. If someone does, I am happy to change it.

Here are some arguments in favour of NaN:

The case of the null graph is qualitatively different from all the rest. We can say that the diameter is the largest entry in (maximum of) the distance matrix (the matrix of pairwise node-to-node distances). We consider the diagonal of the matrix (self-distances, all zeros) as well, as this is convenient for the singleton graph. This gives a pretty uncontroversial Infinity for non-connected graphs with at least _some_ vertices.

But if we have no vertices at all, the distance matrix is empty. It is a zero-by-zero matrix, which in itself is a controversial concept. What is the maximum of the empty matrix?  We can say it's -Infinity (commonly used as the minimum of empty sets), or we can just say, "What's the diameter of the null graph?" is a bad question anyway, so we communicate this to the user by returning NaN. So now we have yet another potential answer, `-Infinity` :-) 

We have the same situation with `igraph_radius`, which is the minimum eccentricity. What if there are no eccentricities? We can return -Infinity, or just NaN. Currently, the function returns NaN. At least now `igraph_radius` and `igraph_diameter` would be consistent in how they handle this.

**Comment by szhorvat** [comment]
These are just _some arguments_ on favour of NaN, but me personally arguing in favour of NaN.

**Comment by szhorvat** [comment]
The messy thing about writing graph theory software vs writing a graph theory book, is that we cannot easily ignore the edge cases. A book can just not talk about them, as "uninteresting", "pointless", or "let's not waste time defining this". When writing software, we _have_ to make a decision, even if that decision is to throw an error.

**Comment by szhorvat** [comment]
BTW: I don't think it's worth making `igraph_girth` return a `double` just to support infinities, but I'll note in the documentation that acyclic graphs are often considered to have girth infinity. They can be seen as the limit reached through graphs with larger and larger cycles (what is called locally tree-like).

**Comment by ntamas** [comment]
Okay, in this case I consider this discussion as having reached a conclusion (let's use NaN because the null graph is pathological). Please add a link in your PR to this discussion because it's comprehensive enough and documents our decision for the future, so in case someone starts complaining about igraph's behaviour, we can always redirect them here and ask them to come up with counterarguments.
