### ISSUE TITLE
When compiling with MSVC, igraph_edge_betweenness test leads to "C1001: Internal compiler error"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1543]
When compiling the `igraph_edge_betweenness.c` test with MSVC in Release mode, I get "C1001: Internal compiler error".

![image](https://user-images.githubusercontent.com/1212871/98674979-e9698400-2359-11eb-850e-59f8fd5fc45c.png)

Configuration:

 - Using GMP, all other libraries internal
 - Building with MSBuild
 - Build command: `cmake --build . --target build_tests --config Release`

There is no problem when compiling in the Debug configuration.

System:

 - Windows 7
 - Visual Studio 2019 command line tools version 16.7.7

@vtraag Let me know if you can reproduce.

----

Relevant resources:

 - https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?view=msvc-160
 - https://stackoverflow.com/a/29673384/695132

**Comment by vtraag** [comment]
I can confirm the problem, using Windows 10, Visual Studio 2019, MSBuild version 16.7.0, using the all internal libraries option (without GMP support).
