### ISSUE TITLE
igraph::modularity() implementation is wrong/highly problematic

### ISSUE THREAD

**Issue by timonelmer** [igraph/igraph#1550]
Recently, I have discovered a default setting in the modularity function, that I find problematic. The function “assumes” that nodes can also have self-ties. I know this might be sometimes the case, but for networks where modularity is applied on (e.g., Karate data) self-ties are often not possible and actually dont make sense (a community can only be between people and not within people). Because the diagonal in a “same group” matrix is 1, whereas it should be 0, the returned modularity score is biased. Here is some R-Code that demostrates this:

```
library(igraph)
library(igraphdata)

data(karate)

# Define the modularity function
Q <- function(x, group, diag = T){
  m <- length(E(x)) # n ties
  
  same.group <- outer(group, group, "==") 
  if(!diag) diag(same.group) <- 0 
  
  a <- as.matrix(as_adjacency_matrix(x))
  p <- outer(rowSums(a),rowSums(a),"*")/(2*m)
  
  # the formula
  q <- (1/(2*m))*sum(same.group*(a-p), na.rm = T)
  return(q)
}

# if each node is in its own community, the modularity should be zero, but it is not:
modularity(karate, 1:length(V(karate)))
Q(karate, 1:length(V(karate)))
# now it is zero:
Q(karate, 1:length(V(karate)), diag = F)
```

Therefore, I would suggest to you and the igraph team to change this default and add an argument to control this. I think the community would profit from this reasonable default. What are your thoughts on this?

**Comment by szhorvat** [comment]
Since if this were implemented, it would have to be in the C core, I transferred the issue here.

> Therefore, I would suggest to you and the igraph team to change this default and **add an argument to control this**.

@vtraag What's your opinion on adding an argument for this?

**Comment by szhorvat** [comment]
> At any rate, the difference of (not) counting the diagonal in your suggestion is a constant (i.e. it does not depend on the partition), so you can simply always add that difference yourself.

Since it is easy to make a correction and get the non-standard modularity OP was looking for, it is not worth adding an option to control this. (At least not until this alternative modularity definitions starts to see widespread use.)

Thus, closing.
