### ISSUE TITLE
Betweenness calculation should be faster for a subset of vertices

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1551]
**What is the feature or improvement you would like to see?**

`igraph_betweenness` can calculate betweenness for a subset of vertices only. However, under a hood it always computes it for all vertices, then simply subsets the result. This is true both for the unweighted and weighted implementations and is noted in the docs, under "Time complexity".

https://igraph.org/c/doc/igraph-Structural.html#igraph_betweenness

It should be investigated if this function can be made faster when doing the computation only for a subset. networkx has this through [betweenness_centrality_subset](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.betweenness_centrality_subset.html).

**Use cases for the feature**

 - Working with large graphs
 - High-level parallelization, see e.g. here: https://github.com/igraph/rigraph/issues/315#issuecomment-731806342

**Comment by ntamas** [comment]
Not sure if I understand how this would work for a subset of vertices without calculating all the shortest paths. For instance, suppose that we graph that looks like this: `A --> B --> C, A --> D --> C, A --> E --> C, A --> F --> C, ... A --> Z --> C`, and I want the betweenness centrality of node `B`. There are 24 shortest paths from `A` to `C`, one that passes through `B` and 23 that do not; however, in order to know that the path from A to C that goes through B counts only as 1/24 (because there are 23 alternate shortest paths), I would need to calculate all the shortest paths anyway. Am I missing something?

**Comment by szhorvat** [comment]
I had the very same thought, but I times the networkx functions and they are indeed faster for a subset.

**Comment by ntamas** [comment]
Okay, so it looks like the signature of the function in NetworkX is actually `betweenness_centrality_subset(G, sources, targets)` -- so what happens is that the algorithm then calculates only those shortest paths that originate from `sources` and terminates in `targets`, but the result still contains a value for all the vertices, only that the result is based on a fraction of the shortest paths only. I guess that you can then recover the betwenness centralities of the vertices by aggregating the individual results.

This is not identical to what the title of this issue implies as NetworkX is not calculating the result for a subset of _vertices_ but for a subset of _shortest paths_.

**Comment by ntamas** [comment]
I was thinking about it a bit more and I am pretty convinced that you cannot simply calculate betweenness for "a subset of vertices" without calculating all the shortest paths, assuming that your goal is to get the accurate betweenness of a given vertex _i_. What you _can_ do is to calculate a betweenness-like measure for each vertex based only on paths that satisfy a certain condition, for instance, that all such paths must originate from a given vertex set, terminate in a given vertex set, or both. But the result of this is _not_ a betweenness vector, it's more like a "partial betweenness vector", and summing up several partial betweenness vectors (element-wise), partitioned by the source vertex of the paths will give you the whole betwenness vector in the end.

So, I guess we have to ask ourselves why a particular user would want to calculate the betweenness of a vertex subset only. Is he interested in the _exact_ betweenness of these vertices but nothing else? In that case, he is out of luck -- all paths are needed for an exact betweenness reading; the best we can hope for is to find a clever condition that allows us to terminate the shortest path search earlier if all the _remaining_ shortest paths that we haven't found cannot affect the betweenness of the vertices of interest. One way this can happen is if the graph has multiple components, and all the vertices of interest are in one particular component only; in this case, we can skip searching in any of the other components. But I don't know whether there are any similar low-hanging fruits in more complex cases.

However, there might be _another_ goal in the user's mind -- maybe he just wants to parallelize the computation and thinks that partitioning the computation by vertices is the way to do it. It is not, but if the goal is parallelization, we simply need to distribute single-source-shortest-path (SSSP) calculations to the available CPU cores, calculate a "partial betweenness vector" for each source vertex, and then add them up in a final post-processing step. This can easily be done with OpenMP pragmas: we can distribute the SSSP loops to individual CPU cores. Each SSSP loop will only ever read the graph and will have a private thread-level data structure to keep track of the state of the shortest path search, and another vector where the partial betweenness vector is computed. At the end of the SSSP loop, the partial betweenness vector is handed over to a non-parallelizable aggregation step.

**Comment by szhorvat** [comment]
Of course you're right that computing betweenness for a subset of vertices is not going to be any faster. I agree, my suggested was flawed.

Now the question is if there are any uses for only taking shortest paths among a subset of vertices, as you describe. As you point out, one use is parallelization, but it's a rather weak motivation to implement this (and we have another issue already for parallelization).

However, I think that there are still potential uses for it, and I would not immediately dismiss implementing this. That said, this thread has become too confusing, so I suggest we close it, and I open a new issue for taking paths only in a subset of vertices when I find a good need for it.
