### ISSUE TITLE
degree_sequence_game: using a non-graphical degree sequence with the VL method results in too many errors

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1555]
**Describe the bug**

Passing a non-graphical degree sequence to `degree_sequence_game` results in two errors instead of one:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1212871/100523208-f63a0480-31ae-11eb-84af-a92ec3a8e143.png">

The first one (the only one shown by R, see https://github.com/igraph/rigraph/issues/88) is an `EINTERNAL` which is misleading: it says "Internal error, likely a bug in igraph". There is no bug here.

**To reproduce**

```mathematica
IGDegreeSequenceGame[{1, 2, 3}, Method -> "VigerLatapy"]
```

or

```R
degree.sequence.game(c(1,2,3), method='vl')
```

**Comment by ntamas** [comment]
An easy fix would be simply to check for graphicality before calling the original VL method. Would that work?

**Comment by szhorvat** [comment]
Yes, I think so, haven't looked in detail yet ... we have an exceptionally efficient graphicality checker, the extra computational time spent on this is very likely negligible. :-)
