### ISSUE TITLE
will Graph.get_shortest_paths() support bellman_ford algorithm

### ISSUE THREAD

**Issue by chenzhiw** [igraph/igraph#1569]
Graph.get_shortest_paths() also supports edge weights (**only Dijkstra's algorithm yet**)
Will it support bellman_ford algorithm for negative weights in the future?
I have to convert it to SciPy CSR matrix first, and traceback myself now.

**Comment by ntamas** [comment]
There are no immediate plans to implement `igraph_get_shortest_paths_bellman_ford()` yet; pull requests are welcome. I have added this to the wishlist.

**Comment by ayanginet** [comment]
I am a bit confused. Isn't it already implemented?
https://github.com/igraph/igraph/blob/520ee0c550cf7f9b4d6dd379e6f20f8000c03792/src/structural_properties.c#L5396-L5401

**Comment by ntamas** [comment]
That function will only give you the _lengths_ of the shortest paths, not the paths themselves. `get_shortest_paths_bellman_ford()` should give you the paths as well.

**Comment by szhorvat** [comment]
Indeed, this has been implemented by @guyroznb
