### ISSUE TITLE
adjlist and inclist constructors should have option to control duplicating self-loops

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1571]
adjlist and inclist constructors should have a new parameter that controls whether self-loops are included once or twice in the result. 

The functions which were used to remove such duplicates (e.g. `igraph_(inclist|adjlist)_remove_duplicate`) can then be deprecated.

**Comment by ntamas** [comment]
@szhorvat Do you see any occurrences where `igraph_(inclist|adjlist)_remove_duplicate` are being called? I can't find a single place in the codebase where they are being called now.

**Comment by szhorvat** [comment]
My IDE says that they are not used. But I still think that this capability should be added.

They used to be used, but they had problems, so we changed the functions that used them so that they would not call `remove_duplicates` anymore. As I remember, this was the eigenvector centrality. Generally, with spectral-style measures, as well as in some other cases, we need to decide which kind of adjacency matrix definition we are going to use: the one where each self-loop adds 1 to the diagonal, or where it adds 2. Now we use the one which adds 2.

Which is "best" is unclear. Some other systems use 1. We should keep the flexibility to use either one, which is why I'd like to add a parameter to adjlist/inclist constructors.

**Comment by vtraag** [comment]
Whatever we settle on should also become a standard for other functions, one suggestion made here: https://github.com/igraph/igraph/issues/1193.

**Comment by szhorvat** [comment]
There is no one correct choice for duplicating or not duplicating entries. It is application-dependent. Previously, igraph's approach was to:

 - Always duplicate self-loops
 - Provide functions to remove duplicates

The problem is that duplicates cannot be removed from the adjlist. Just from an adjlist, one cannot tell if a vertex is self-adjacent twice because a self-loop was duplicated or because there were multiple self-loops. With inclists, which use edge indices, it is certainly possible to remove duplicate edges, but doing so is slow. Thus it's better to control how the adjlist/inclist is created in its constructor: it's faster and simpler.

**Comment by ntamas** [comment]
> Just from an adjlist, one cannot tell if a vertex is self-adjacent twice because a self-loop was duplicated or because there were multiple self-loops.

Note that there are two things that you can still do:

1. If you _know_ that self-loops are always present twice, and that you haven't removed them already, then you can simply remove every second occurrence of a node in its own adjacency list and you are done.

2. `igraph_adjlist_remove_duplicate()` receives the whole graph as its argument so you can still decide even if you don't know whether self-loops have already been removed or not. (We don't use the `graph` argument at the moment, but we could if we wanted to).

But anyway, I agree that it is slower to do it after the adjacency list has been constructed so I'm okay with moving stuff to the constructor. And it's good that @vtraag has brought my attention to #1193 because this is exactly how I was thinking about the new argument to be added to the constructor. Does anyone have any objections against adopting the enum proposed in #1193?

**Comment by szhorvat** [comment]
> Does anyone have any objections against adopting the enum proposed in #1193?

No. I'm fine with whatever for as long as we get the possibility to control loop duplication in the constructor.

Just a reminder that this applies only in the undirected case. 

Then for the lazy case, would you have two arguments, one controlling loops and one controlling multi-edges?

**Comment by ntamas** [comment]
The only problem is that we apparently have an unused enum in the public interface named `igraph_i_loops_t`, defined like this:

```
typedef enum { IGRAPH_NO_LOOPS = 0, IGRAPH_LOOPS = 1 } igraph_i_loops_t;
```

The enum itself is not used anywhere as a type, but its constants (i.e. `IGRAPH_NO_LOOPS` and `IGRAPH_LOOPS`) are. To make it consistent with @vtraag's proposal, we could rename `igraph_i_loops_t` to `igraph_loops_t` and define it like this:

```
typedef enum { IGRAPH_NO_LOOPS = 0, IGRAPH_LOOPS = 1, IGRAPH_LOOPS_1 = 1, IGRAPH_LOOPS_2 = 2 } igraph_i_loops_t;
```

Code that is not concerned with the multiplicity of loop edges can then use `igraph_i_loops_t` as a boolean (i.e. zero = no loops, nonzero = loops), while code that is interested in the multiplicity of loop edges can use the numeric value of the enum.

**Comment by szhorvat** [comment]
@ntamas I'm going offline now. If you do that, test with C++ (not C!) if the compiler freaks out about the duplicated value in the enum list.

**Comment by ntamas** [comment]
> Then for the lazy case, would you have two arguments, one controlling loops and one controlling multi-edges?

Either that, or to leave the current simplification argument as is, and when it is set to `IGRAPH_SIMPLIFY`, then we ignore the loop argument.

**Comment by szhorvat** [comment]
There are many good applications for simple-loopy graphs, i.e. one self-loop allowed, multi-edges not allowed. Thus it's useful to control multi-edges separately. (I don't have an immediate example for adjlist/inclist. I made this distinction in the degseq functions though.)

**Comment by ntamas** [comment]
> If you do that, test with C++ (not C!) if the compiler freaks out about the duplicated value in the enum list.

Will do, but I'm pretty sure it will work. I have routinely used code like this in other C++ projects before:

```
typedef enum {
    CATEGORY_INFO = 0,
    INFO_1 = 0,
    INFO_2,
    INFO_3,
    ...,
    CATEGORY_WARNING = 64,
    WARNING_1 = 64,
    ...,
    CATEGORY_ERROR = 128,
    ERROR_1 = 128,
    ...
} message_t;
```

the idea being that you can test the severity of a message by comparing it with the `CATEGORY_` placeholders (or by taking the two MSBs).

**Comment by ntamas** [comment]
This was implemented in the `feature/adjlist-inclist-loop-handling` branch, which is now merged.
