### ISSUE TITLE
Ensure all tests have VERIFY_FINALLY_STACK

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1572]
All tests should call `VERIFY_FINALLY_STACK()` at the end.

#1574 should be completed before starting with this.

**Comment by szhorvat** [comment]
All tests in `tests/unit` that needed this now have this. This issue should be revisited when more tests are moved to `tests/unit` (#1574 and #1585). I'm done with it for now, so anyone else feel free to continue.

**Comment by szhorvat** [comment]
Easy way to check which files do not have `VERIFY_FINALLY_STACK` using bash:

```
cd tests/unit
comm -3 <(ls *.c | sort) <(grep -l VERIFY_FINALLY_STACK *.c | sort)
```

**Comment by szhorvat** [comment]
Currently, these do not have it and do not need it:

```
error_macros.c
fatal_handler.c
heap.c
igraph_rng_get_exp.c
lineendings.c
mt.c
rng_reproducibility.c
tls1.c
```

**Comment by szhorvat** [comment]
You are right. Feel free to change some of these without opening a PR if you come across them.

**Comment by szhorvat** [comment]
This is something I check before each release, and I often find a few tests which are missing it. But I agree it can be closed.

**Comment by ntamas** [comment]
We could write a pre-commit hook for it; basically it would need to find all `*.c` files in `tests/unit` that do not have `VERIFY_FINALLY_STACK()` in it. For tests that do _not_ need `VERIFY_FINALLY_STACK()`, we could have a comment saying `/* This test does not need VERIFY_FINALLY_STACK() */`, which would satisfy the pre-commit hook.
