### ISSUE TITLE
Break up large files

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1575]
Look for any files named `src/<something>/<something>_other.c` and break them up into smaller chunks of manageable size.  Figure out how to do this without losing git history.

Checklist:

- [x] `centrality/centrality_other.c`
- [x] `community/community_other.c`
- [x] `constructors/constructors_other.c`
- [x] `games/games_other.c`
- [x] `io/io_other.c`
- [x] `isomorphism/isomorphism_other.c`
- [x] `layout/layout_other.c`
- [x] `operators/operators.c`
- [x] `properties/properties_other.c`

**Comment by szhorvat** [comment]
One way to break up a large file into smaller pieces by preserving git history is this two step method:

 1. Make multiple copies of the file, but do not change their contents. Make a commit. This ensures that git sees that the files are the same.
 2. Remove the unwanted parts of each copy. Make the second commit.

**Comment by ntamas** [comment]
Phew! I think it's done; the structure is much better now.
