### ISSUE TITLE
Write tests for igraph_heap_ functions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1577]
There are no tests for the `igraph_heap_` functions.

https://github.com/igraph/igraph/blob/develop/tests/unit/heap.c#L28

These functions are part of the public API, and generally useful for graph algorithms. They should have tests.

**Comment by RamySaied1** [comment]
I would like to work on this

**Comment by szhorvat** [comment]
Welcome! You will find guidance for getting started in the wiki: https://github.com/igraph/igraph/wiki Be sure to work on the `develop` branch. The first step is to learn [to build igraph](https://igraph.discourse.group/t/draft-document-for-installation-with-cmake/504). For general questions, you can use the forum at https://igraph.discourse.group/  As you go, please also verify that the documentation of these function is correct and complete.

These functions are part of the public API, so it's good to have tests for them. But it's good to note that they are not currently used at all internally, therefore fixing this task is of low priority. We are currently preparing for a release, so any PRs will likely be reviewed with 1-2 weeks of delay from now.
