### ISSUE TITLE
Fix incomplete tests/examples

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1582]
The following tests and examples have missing parts or other issues that need to be fixed. We should not have un-useful examples included in the docs.

 - [x] `examples/simple/igraph_write_graph_lgl.c` is all commented out (#1601).
 - [x] `examples/simple/igraph_star.c` is empty (24509484b72ed057c71a3361dbf2191e71cb79de)
 - [x] `examples/simple/igraph_rewire.c` uses internal functions yet it is included as a doc example (d97c61aba4dc8dcac903373d9d0cbe76f7366439).
 - [x] `examples/simple/igraph_all_st_cuts.c` uses internal functions yet it is included as a doc example (d97c61aba4dc8dcac903373d9d0cbe76f7366439).
 - [x] `examples/simple/igraph_sparsemat2.c` uses internal functions yet it is included as a doc example (d97c61aba4dc8dcac903373d9d0cbe76f7366439).
 - [x] `examples/simple/igraph_bfs.c` uses internal functions yet it is included as a doc example (13c2ed6a5 and d0c1db691)
 - [x] `examples/simple/cattributes4.c` has a TODO item, incomplete function (d395d8e1a)
 - [x] `examples/simple/scg2.c` uses `test_utilities.inc` while being included in the docs(4ec9a50bd1e0eb78469f75c2f48fa56ab44fb181).
 - [x] `examples/simple/scg3.c` uses `test_utilities.inc` while being included in the docs (4ec9a50bd1e0eb78469f75c2f48fa56ab44fb181).
 - Please edit this issue and add more problem files as you discover them.

**Comment by jgmbenoit** [comment]
Let continue discussion [#1580 ](https://github.com/igraph/igraph/pull/1580) here. Please note that my point is not meant to be Debian centric. Here I am regular user centric. If I am a user who want to use the igraph library and who want to try some examples provided in the  manual, I want to be able to play with the them without diging in the the source code: I just want to use related packages distributed by my favourite distribution or the material install by the superuser of my computer. So basically, I want be able to put the examples in a folder and to build them against the library. Period. Now, as package maintainer, I can use these examples for automatic checks of my packages. And I want to check them as well. I follow this scheme in my last packaging of  igraph (0.8.5+ds-3): it rocks well (see [CI Debian amd64 test](https://ci.debian.net/packages/i/igraph/unstable/amd64/)).

**Comment by szhorvat** [comment]
@jgmbenoit:

>  ... So basically, I want be able to put the examples in a folder and to build them against the library. Period.

As for your first point, I fully agree. Over time, examples have become more like unit tests than actually useful examples. For 0.9 we're trying to separate those programs which are purely tests from those that may be useful as examples. It would also be nice to write better educational examples, but as usual, there is little time for that ... I just created a new "good first issue" in #1585. Perhaps writing examples is a good way to get started with igraph for those who are interested.

> Now, as package maintainer, I can use these examples for automatic checks of my packages.

You should be aware that all examples are run as tests (i.e. they appears in `tests/CMakeLists.txt` on the `develop` branch). Therefore, in order to run all examples, all you need to do is run the tests.

@jgmbenoit, do not hesitate to let us know about any special needs you have as a package maintainer. If we know what you are doing exactly, perhaps we can do some small things on our side to make the process more streamlined.

**Comment by jgmbenoit** [comment]
"You should be aware that all examples are run as tests". I am. There are tests a building time, and periodic tests to check that every is fine within the distribution (libraries, compilers, ...).

**Comment by szhorvat** [comment]
> "You should be aware that all examples are run as tests".

This was not actually true. I fixed that now and made sure that all examples are run with the tests.

**Comment by szhorvat** [comment]
@jgmbenoit A release candidate of 0.9 is planned not for next week, but for the week after. We're pretty close. It would be really great if you could test it and let us know about any problems Debian might have, or changes Debian might need. Since the build system has changed, there's a risk of things going wrong.

**Comment by ntamas** [comment]
`examples/simple/igraph_bfs_simple.c` was added to show a usage example for the newly exposed `igraph_bfs_simple()`. The former tests for `igraph_i_bfs()` were moved to `tests/unit/igraph_bfs_simple.c`. `examples/simple/igraph_bfs.c` will be sorted out soon to be more like an example and not a unit test.

**Comment by ntamas** [comment]
I have no idea what the `TODO` comment meant in `examples/simple/cattributes4.c`, but the entire function was unused. It was probably copied accidentally from `examples/simple/cattributes3.c` before it was completed there. Anyway, I've removed the entire function.
