### ISSUE TITLE
Cmake target check fails on @VERSION@

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1593]
**Describe the bug**
After 
```cmake --build . --target check```
Cmake fails with:

(dot)
```
-/* Created by igraph @VERSION@ */
+/* Created by igraph 0.8.5-post+86bf26507 */
```

(gml)
```
-Creator "igraph version @VERSION@ test suite"
+Creator "igraph version 0.8.5-post+86bf26507 test suite"
```

(cattributes2)
```
-Creator "igraph version @VERSION@ "
+Creator "igraph version 0.8.5-post+86bf26507 "
```

```
The following tests FAILED:
	150 - dot (Failed)
	152 - gml (Failed)
	223 - cattributes2 (Failed)
```

**To reproduce**
Follow the instructions here:
https://igraph.discourse.group/t/draft-document-for-installation-with-cmake/504

**Version information**
48886a514eb424c333d21cdf860be6d41a11094
The current develop version.
cmake version 3.16.3

**Comment by szhorvat** [comment]
I can't reproduce this on macOS with CMake 3.19.2.  Are you sure you are using a clean source tree? Please try a `git clean -fdx`. That 0.8.5 doesn't look right: it should be showing `0.9.0-dev+48886a51` in the `cmake .. ` output.

**Comment by GroteGnoom** [comment]
Yes, `git clean -fdx` on the igraph root fixed it.
