### ISSUE TITLE
igraph_is_same_graph: a function that checks if two graphs are the same

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1599]
**What is the feature or improvement you would like to see?**

Detect if two graphs are the same, i.e. have the same vertex and edge sets. This is not the same as isomorphism.

`1-2-3` and `1-3-2` are isomorphic but not the same (edge sets differ).

`1-2-3` has potentially multiple representations, e.g. `1-2, 2-3` or `2-3, 1-2` (different edge order). The function should detect that these are the same graph.

**Use cases for the feature**

It is especially useful for verification (e.g. writing tests)

Ref: https://igraph.discourse.group/t/is-the-order-of-print-graph-guarateed-to-be-the-same/587

**Comment by iosonofabio** [comment]
I'd be happy to implement this, it seems easy enough. It is a little more tricky is you also want to check all vertex and edge attributes, but still should be doable.

**Comment by szhorvat** [comment]
Thanks @iosonofabio.  Can you first please write a purely topological version that ignores any attributes? This is what I was looking for. 

Additionally, it would be useful to have a function that canonicalizes the representation (i.e. makes it possible to directly compare two instances after both were canonicalized). Let me know if you want to tackle this related problem at the same time or leave it for later.

----

Comparing attributes is useful, but it's a somewhat different operation. IMO it's best done in the high-level interfaces and not the C core. Note that the C core doesn't know how to compare two attribute values. We couldn't just use `==`, as attributes can be (and in practice are) non-trivial data structures. I see two options: 

 1. We'd either need to allow for a custom comparison function, passed in as an extra argument by the user, which allows the C core to test the equality of two attribute values
 2. Or we will have a canonicalization function (which I'd like anyway) that is used as a basis of an attribute-comparing implementation in a high-level interface. The high-level interface knows how to compare objects in its host language.

One argument for doing the attribute comparing version in the high-level interface is the following: What does it mean that two graphs are the same? Their vertex sets and edge sets must be the same.  In the C core, vertices don't have names, only indices, thus "same vertex set" and "same edge set" are a different concept than if vertex names were possible.

As you can see the version with attributes is quite a bit more complicated. Let's leave that for later.

**Comment by iosonofabio** [comment]
Ok no attributes for now. Just to make sure, all we have got to do is:

- check the number of vertices and edges is the same
- check both graphs are directed/undirected
- for loop over edges and check that source/target of each is the same

If all pass return true, else false

That correct?

**Comment by szhorvat** [comment]
> That correct?

Yes, having that as a simple first function would be really great!

**Comment by szhorvat** [comment]
> That correct?

Sorry, scratch what I wrote.

This is not correct.

If we compare the edge lists, they need to be sorted first. That's the main point. But that is not the only possible way (and not necessarily the most efficient way—but I wouldn't worry about that for now).

If we have two graphs, one with edge list `1-2, 2-3`, the other with `2-3, 1-2`, they are the same graph, but we can't just loop over edges and compare one by one.

**Comment by iosonofabio** [comment]
That was my question. But I guess if the main goal of this function is tests, e.g. two functions giving the same graph, we might actually want the order of edges to be exactly the same. In other words, same edge id requires same source and target.

So it sounds like we need two functions, one for topological equivalence and one for additional equivalence for every edge id. Each test can use either function depending on what's being tested.

Does that sound reasonable?

**Comment by szhorvat** [comment]
Testing that the *representations* are the same is trivial. In tests, one can often just print the graph. IMO there is no need to have a function for this.

The challenge is to test that two graphs are the same even if they don't have the same representation. This is what we need a function for.

**Comment by vtraag** [comment]
Note that the edges are already sorted internally in the current representation of `igraph_t`. If we consider this `igraph_is_same_graph` to be an "internal" function, i.e. which is part of the `igraph_t` API, we can easily check this by looking at this sorted order (i.e. `oi` and `ii`). Alternatively, you can simply check all the neighbours of each node (which amounts to using `oi` and `ii` internally). If the `igraph_t` representation changes, and possibly no longer uses a sorted structure, this functionality would also have to change with it. This is why it should be considered "internal" to the `igraph_t` API. It should then be implemented in `type_indexededgelist.c`.

**Comment by szhorvat** [comment]
Fixed by #1604.
