### ISSUE TITLE
Centralization, a'la Freeman

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#160]
Continued from http://code.google.com/p/igraph/issues/detail?id=127

---

Imported from Launchpad using lp2gh.
- date created: 2009-04-16T19:33:57Z
- owner: gabor.csardi
- assignee: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/362517

**Comment by JanSchulz** [comment]
constraint and page rank are there, not sure about the rest.
