### ISSUE TITLE
Cannot copy code from examples in online documentation

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1602]
**Describe the bug**
When I try to copy code from the examples provided in the documentation, the block containing the example code folds back in again. This prevents me from copying example code.

**To reproduce**
Open any documentation page that contains an example (e.g. https://igraph.org/c/doc/igraph-Basic.html). Open the example (e.g. Example 4.1) by clicking on it. Now when trying to copy code, it will close the example again.

**Comment by ntamas** [comment]
This is now fixed :)
