### ISSUE TITLE
Broken link to PDF documentation of version 0.8.5

### ISSUE THREAD

**Issue by pacalet** [igraph/igraph#1619]
**Describe the bug**
The [https://igraph.org/c/doc/igraph-docs.pdf](https://igraph.org/c/doc/igraph-docs.pdf) link to the PDF documentation for C/igraph 0.8.5 is broken.

**To reproduce**
Click on [https://igraph.org/c/doc/igraph-docs.pdf](https://igraph.org/c/doc/igraph-docs.pdf).

**Version information**
C/igraph 0.8.5, no need to obtain it.

**Comment by ntamas** [comment]
Thanks for the heads up. I have updated the homepage and it should be there now, but for some reason I'm still getting a 404 from Github Pages when visiting via the browser (but it works when I download it from the command line with `wget`). Maybe we just need to wait a bit more for the updates to propagate everywhere.

**Comment by ntamas** [comment]
In the meantime you can get the docs from [here](https://github.com/igraph/igraph.org/raw/master/docs/c/doc/igraph-docs.pdf).

**Comment by ntamas** [comment]
Seems to be okay now.
