### ISSUE TITLE
Redundant parameters in some random graph generators

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1620]
`callaway_traits_game`, `establishment_game`, `preference_game` all have both a `types` (number of vertex types) and `type_dist` (distribution of types) parameter. It is necessary that `types == igraph_vector_size(type_dist)`. Therefore, `types` is redundant—the number of types is already defined by the type distribution vector.

`asymmetric_preference_game` is similar, but it has a `type_dist_matrix` instead of a `type_dist` vector.

Since we're trying to clean up the API a bit for 0.9, shall we remove the redundant `types` parameter?

----

My guess for the existence of `types` is that originally it was intended that `type_dist` can be omitted and in that case it would be auto-generated as all-ones. This is what the R interface does: https://igraph.org/r/doc/sample_traits_callaway.html However, it does it in R, not in C. I don't think there's a reason to do it in C.

**Comment by szhorvat** [comment]
Also, in the case of `asymmetric_preference_game`, it is unclear to me why it is enforced that the number of in-types and out-types be the same. In principle they could be different.

**Comment by szhorvat** [comment]
Regarding `igraph_preference_game` with `fixed_sizes` set, isn't this exactly the same as a stochastic block model?

**Comment by szhorvat** [comment]
`preference_game` does in fact allow for `type_dist` to be `NULL`, in which case it takes the distribution to be uniform. `callaway_traits_game`, `establishment_game` do not currently allow this in the C interface (only in R).

**Comment by vtraag** [comment]
> Since we're trying to clean up the API a bit for 0.9, shall we remove the redundant `types` parameter?

Yes, that makes a lot of sense to me.

> Regarding `igraph_preference_game` with `fixed_sizes` set, isn't this exactly the same as a stochastic block model?

Yes, I agree.

**Comment by GroteGnoom** [comment]
> Regarding `igraph_preference_game` with `fixed_sizes` set, isn't this exactly the same as a stochastic block model?

It also seems to me like the callaway_traits_game is equal to the establishment_game (except for error handling).

**Comment by szhorvat** [comment]
> It also seems to me like the callaway_traits_game is equal to the establishment_game (except for error handling).

There are three types of games based on "traits":

 - `callaway_traits`: In each step, add 1 vertex, then try adding edges between existing vertices `k` times (succeeding with probability based on their types).
 - `establishment`: In each step, add 1 vertex, then try adding edges between the just-added vertex and another ones (succeeding with probability based on their types).
 - `preference`: First add all vertices, then for all vertex pairs add an edge with probability determined by their types.

This is based on the documentation. We need to verify that this is indeed what the code does, and if there are any additional subtleties, they should be added to the documentation. I just checked `establishment_game`, and it looks like first it puts down `k` vertices, and only then does it start adding edges. This is not obvious from the documentation. An alternative possibility would be to put down 1, 2, ..., k vertices, adding at most 1, 2, ..., k edges in each case. Once there are at least `k` vertices, add at most `k` edges in each step.

In all three, the edge probability depends on the vertex types.

**Comment by szhorvat** [comment]
Here are the changes I want to make to these functions:

----

I would like to make `callaway_traits_game`, `establishment_game`, and `preference_game` more consistent with each other in how they use the `types` (no. of types) and `type_dist` argument. There are two reasonable choices:

 1. Remove the `types` argument since the number of types is already communicated by the length of `type_dist`.
 2. Keep `types` and `type_dist`, but make `type_dist` optional: if passing a `NULL` pointer, it is assumed to be a vector of ones of length `types`. Note that `preference_game` already does this.

@vtraag @ntamas @gaborcsardi which solution do you vote for? I vote for (1) because it's simple and uncluttered and makes it simpler to deal with `asymmetric_preference` (see last point in this message).

----

I would like to change `callaway_traits` and `establishment` so that they return the generated vertex types, just like `preference` does.

----

In `preference`, the `fixed_sizes` argument is more or less pointless as it's completely equivalent to a stochastic block model. The function would be cleaner without this option, which also changes the interpretation of the other arguments. However, I am a bit reluctant to remove this functionality: it is exposed in the R interface (and only there) and people may have used it in the past for some papers. It would make their work harder to reproduce.

Any opinions on this?

----

I would like to improve the documentation and ensure that all small details are included.  Additionally, I'd like to make the function names consistent and include references, if there are any.

@gaborcsardi Where did these models, and their names come from? "Callaway" doesn't tell me anything, and I can only guess at "establishment" too. Are there any references, or did you come up with these models? Any suggestions for clearer names that also communicate that these models are closely related?

I only realized today that the name must be referring to the first author of this paper: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.64.041902 

----

In `asymmetric_preference`, I would like to allow for a different number of in-types and out-types, which is useful. There seems to be no reason not to allow this. Furthermore, I would like to enforce that the size of the `type_dist_matrix` matrix should (no. of out-types) * (no. of in-types). Right now only a minimum size is enforced—it's not clear to me why.

**Comment by ntamas** [comment]
Going from top to bottom :)

> My guess for the existence of types is that originally it was intended that `type_dist` can be omitted and in that case it would be auto-generated as all-ones.

Yes, that was the intention and I think it's pretty convenient if you can just pass in `NULL` as the `type_dist` and igraph creates an all-ones vector on its own. No need to allocate and initialize a vector and destroy it afterwards (or forget to destroy it and introduce a memory leak).

(This also implies that I would vote for option (2) in your comment).

> Also, in the case of asymmetric_preference_game, it is unclear to me why it is enforced that the number of in-types and out-types be the same. In principle they could be different.

Indeed.

> Regarding `igraph_preference_game` with fixed_sizes set, isn't this exactly the same as a stochastic block model?

Yes it is. But the whole stochastic block model machinery was added much later and `igraph_preference_game()` was there already so we kept it that way for sake of API compatibility. As for removing the `fixed_sizes` argument, I'm against it, for exactly the reasons that you have mentioned. I know that we are about to release a version that breaks the API in several cases, but this particular change would affect the R interface as well, so if we do break things here, we should add a workaround in the R interface that ensures that old research codes still keep on working with newer versions.

> In asymmetric_preference, I would like to allow for a different number of in-types and out-types, which is useful. 

I am in favour of that.

**Comment by szhorvat** [comment]
The remaining question is then: Where do these models come from? What is a more reasonable naming for high-level interfaces? What references should we include?

**Comment by ntamas** [comment]
You have found the correct reference for the Callaway traits game. As for the establishment game; I have no idea :(

**Comment by szhorvat** [comment]
In the latest version of the R interface, `establishment` is called `sample_traits` and `callaway_traits` is called `sample_traits_callaway`.
