### ISSUE TITLE
Randomize the Louvain algorithm

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1633]
**What is the feature or improvement you would like to see?**
At the moment, the Louvain algorithm (`igraph_community_multilevel`) is deterministic. Currently, all nodes are considered in the algorithm simply in the order of the node indices. However, it makes sense that this is randomized. At the moment, one always gets the same result for any graph, perhaps leading people to erroneously believe that this is the only "correct" partition of the Louvain algorithm. The randomization of the node order was also explicitly suggested by the original authors [1].

**Use cases for the feature**
Randomizing the node order allows to determine the stability of any particular resulting partition with regards to different runs, which can also be helpful to produce consensus clusterings [2]. 

**References**
[1] Blondel, V. D., Guillaume, J.-L., Lambiotte, R., & Lefebvre, E. (2008). Fast unfolding of communities in large networks. Journal of Statistical Mechanics: Theory and Experiment, 10008(10), 6. https://doi.org/10.1088/1742-5468/2008/10/P10008
[2] Lancichinetti, A., & Fortunato, S. (2012). Consensus clustering in complex networks. [Physics and Society; Information Retrieval]. Scientific Reports, 2, 336. https://doi.org/10.1038/srep00336

**Comment by szhorvat** [comment]
We have `igraph_permute_vertices` to change the node order and `igraph_vector_shuffle` and `igraph_vector_init_seq` to generate a random permutation, so it's easy to do it at least in a naive way (probably there's a better/faster way to achieve the same outcome by changing the internal workings of `igraph_community_multilevel`).

**Comment by vtraag** [comment]
The implementation is straightforward, I just don't have time to do it now, so I created the issue instead.

**Comment by ntamas** [comment]
Worth to mention that the label propagation algorithm already uses randomization.

It might also be helpful to provide a function that simply takes a list of clusterings for the same graph and attempts to provide a consensus clustering.

**Comment by szhorvat** [comment]
> takes a list of clusterings for the same graph and attempts to provide a consensus clustering.

This is an interesting reading regarding that: https://www.nature.com/articles/s41598-019-50739-3
