### ISSUE TITLE
Several tests fail on Windows because of MSVC printf bug

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1634]
Several test fail on Windows, in short because of this printf bug: https://stackoverflow.com/q/65900619/695132

In short, `printf("%#g\n", 0.0)` prints one more digit with MSVC than other compilers. Note that this is almost certainly dependent not on the compiler, but the standard library.

Problem comes from here, we will likely need to change the testing code:

https://github.com/igraph/igraph/blob/develop/tests/unit/test_utilities.inc#L38

https://github.com/igraph/igraph/blob/develop/tests/unit/test_utilities.inc#L73

I tested this with VS 2019 version 16.8.4 (latest) on Windows 7 and I see the problem both in Debug and Release mode. Big question: why do we not see it on Azure Pipelines? @vtraag if you can, please do a local test on your end.

**Comment by szhorvat** [comment]
I'll post a list of failing tests when I get access to a Windows machine later.

**Comment by ntamas** [comment]
Damn, I accidentally assigned this to myself and now I can't de-assign myself for some reason.
