### ISSUE TITLE
The packaged version cannot be built because of missing documentation source files

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1650]
**Describe the bug**
The packaged version ("`make dist`") cannot be configured / built because of missing documentation source files.

**To reproduce**

For completeness, I'm doing this on macOS with the Ninja generator.

In `build`,

```
cmake ..
cmake --build . --target dist
tar xf igraph-0.9.0.tar.gz 
cd igraph-0.9.0/
mkdir build && cd build
cmake ..
```

There are a bunch of errors about missing XML files such as

```
CMake Error: File /Users/szhorvat/Repos/igraph-main/igraph/build/igraph-0.9.0/doc/fdl.xml does not exist.
CMake Error at doc/CMakeLists.txt:130 (configure_file):
  configure_file Problem configuring file
```

These seem not to be included in the package.

**Comment by szhorvat** [comment]
@ntamas Would it be feasible (i.e. how much work would it be) to include the _already built_ HTML documentation into the source package? Since doc building requires lots of tools, this would actually be more useful than just copying over the missing xml files.

**Comment by ntamas** [comment]
Yes, I guess it's possible. What about the PDF documentation then, shall we also include that?

One thing that we should watch out for then is to prevent building a source tarball if `DOC_BUILD_SUPPORTED`, `HTML_DOC_BUILD_SUPPORTED` or `PDF_DOC_BUILD_SUPPORTED` is falsey in `doc/CMakeLists.txt`.

I'm wondering why `fdl.xml` is not copied into the source tarball. `etc/cmake/packaging.cmake` declares the entire `doc` folder in the source tree to be copied into the tarball.

**Comment by szhorvat** [comment]
It's not just `fdl.xml`, but _all_ `.xml` files. I only showed one of the error messages.

**Comment by ntamas** [comment]
HTML docs are now in the tarball.
