### ISSUE TITLE
Incorrect solib installation path

### ISSUE THREAD

**Issue by limburgher** [igraph/igraph#1672]
I maintain the Fedora igraph package. I'm attempting to upgrade to 0.9.0, which means changing to the cmake build system. This seems mostly to work, except that libigraph.so and libigraph.so.0 are being placed in /usr/lib, rather than /usr/lib64. I've tried passing -DLIBDIR to no avail. Is there a bug or am I doing it wrong? :)

**Comment by ntamas** [comment]
Hmmm, good question. Ultimately it is CMake's job to know where the libraries should go, and it seems like it defaults to putting them in `${CMAKE_INSTALL_PREFIX}/lib`, where `${CMAKE_INSTALL_PREFIX}` is `/usr`.

Try passing `-DLIB_SUFFIX=64` and/or `-DLIB_INSTALL_DIR=/usr/lib64` to the initial call to `cmake` and see whether it helps. I'll also try to check it on my machine to see what can be done.

**Comment by ntamas** [comment]
Some more info: we use the `GNUInstallDirs` CMake module to tell CMake how to figure out where to install things. The documentation of that module, along with the configuration variables that it supports, is [here](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html). This is the place you need to poke around if you want to override the defaults.

**Comment by limburgher** [comment]
Hmm, not working for me. I'm using our %cmake macro, and it results in this line:
 /usr/bin/cmake -S . -B x86_64-redhat-linux-gnu -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_LIBDIR=lib64

**Comment by ntamas** [comment]
Which version of CMake are you working with? (Mine is CMake 3.19.5). Is it complaining about any unused manually-specified variables after the initial `cmake` step? On my machine, I get this:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
```

**Comment by limburgher** [comment]
3.18.4. Yes, exactly your list. Additionally, I've patched out include(version), so that it doesn't try to determine it's version from git, which fails on the rpm build environment.

**Comment by szhorvat** [comment]
> so that it doesn't try to determine it's version from git, which fails on the rpm build environment.

Are you running it within a (subdirectory of a) git repo?

**Comment by limburgher** [comment]
Yes. The fedora packaging infrastructure uses git, one repo per package.

**Comment by szhorvat** [comment]
@ntamas It'd be good if we could sort out failures from running it within git repos ... It's bound to fail for someone else too.

**Comment by szhorvat** [comment]
@ntamas Should this `bin` and `lib` be `${CMAKE_INSTALL_LIBDIR}` and `${CMAKE_INSTALL_BINDIR}` instead?

https://github.com/igraph/igraph/blob/master/src/CMakeLists.txt#L444

**Comment by ntamas** [comment]
> It'd be good if we could sort out failures from running it within git repos...

Well, we could make the presence of an `IGRAPH_VERSION` file in the root folder beat the presence of a `.git` folder so we would always use the version from `IGRAPH_VERSION` instead of trying to determine it from Git. Would that work for you @limburgher ?

> Should this bin and lib be ${CMAKE_INSTALL_BINDIR} and ${CMAKE_INSTALL_LIBDIR} instead?

Hmmm, yes, that's entirely possible. Let me test.

**Comment by szhorvat** [comment]
@limburgher Looking at your command line, I would strongly recommend specifying the configuration options explicitly instead of leaving them up to auto-detection. See [here](https://igraph.org/c/doc/igraph-Installation.html#igraph-Installation-notes-for-package-maintainers). I would also recommend building the shared library with link-time optimization enabled.

For reference, [these are the options](https://github.com/macports/macports-ports/blob/master/math/igraph/Portfile#L38) I used for the MacPorts version.

**Comment by ntamas** [comment]
> Should this bin and lib be ${CMAKE_INSTALL_BINDIR} and ${CMAKE_INSTALL_LIBDIR} instead?

It worked! For what it's worth, the original version worked with static builds but not with shared ones for some reason, I'm not sure why. Anyhow, @limburgher, the [suggestion from @szhorvat](https://github.com/igraph/igraph/issues/1672#issuecomment-780745949) seems to work so you could go ahead and try that in your patch.

We are waiting for more feedback from package maintainers and then we will probably release a 0.9.1 shortly to work around these issues.

**Comment by szhorvat** [comment]
@limburgher Another thing I noticed is the use of `-DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG`. Don't do this—it will replace the default compilation flags and thus disable all optimization and make the library slow ... I'd suggest leaving it at the default value, which is `-O3 -NDEBUG`.

**Comment by limburgher** [comment]
Looks like the above change worked, and I'll take a look at tuning the flags we pass. Thank you!
