### ISSUE TITLE
community_to_membership dereferences possibly NULL membership argument

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1677]
**Describe the bug**
`igraph_community_to_membership` dereferences its `membership` argument when `membership == NULL` and `csize != NULL`. This will lead to a crash.

https://github.com/igraph/igraph/blob/develop/src/community/misc.c#L187

**Version information**
0.9.0

**Comment by szhorvat** [comment]
I see two ways to fix:

 1. When `csize != NULL` and `membership == NULL`, internally allocate a membership vector and use that
 2. Simply disallow this combination, i.e. throw an error when `csize` is requested but `membership` is not.

I prefer 2.

**Comment by vtraag** [comment]
There is also option 3: remove the `csize` argument from this function. Frankly, I would think that getting the sizes of the communities of the `membership` vector should be a separate function, e.g. `igraph_membership_csize`, which might be useful anyway. The funtion `igraph_community_membership` is primarily used to retrieve the actual membership from a dendogram, the `csize` is something that is not necessarily relevant for this.

**Comment by ntamas** [comment]
If we want to fix this in 0.9.1, this would be an API breakage. But in general I agree with @vtraag -- getting the cluster sizes should be a separate function that can be applied to any membership vector. I can hardly imagine a community detection function where one can determine the cluster sizes efficiently without maintaining a membership vector in parallel, so there's pretty much zero overhead to requiring a membership vector first.

**Comment by vtraag** [comment]
Yes, indeed, depending on our choice here it would be for 0.9.1 or for 0.10.

**Comment by vtraag** [comment]
I am re-opening this to still fix it by removing the `csize` argument in 0.10.

**Comment by szhorvat** [comment]
That's really a different issue though. The title is very misleading now.

**Comment by szhorvat** [comment]
Continued in #1684.
