### ISSUE TITLE
Build fails with newer flex/bison versions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1682]
**Describe the bug**
With the flex/bison versions included with macOS 10.14, the build succeeds. But if I install newer versions, then it fails because of the unused `yy_fatal_error` function.

For example:

```
/src/io/parsers/pajek-lexer.c:2374:24: error: unused function 'yy_fatal_error' [-Werror,-Wunused-function]
static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
```

**To reproduce**
Build igraph with these or later versions:

```
$ flex --version
flex 2.6.4
$ bison --version
bison (GNU Bison) 3.7.5
```

**Comment by szhorvat** [comment]
Treating unused static functions as error has been bothering me for a while (and I had to comment out potentially useful internal functions because of this). 

Any objection to disabling this warning globally @ntamas @vtraag ?  If you don't want to do this, then I disable it for the parsers.

**Comment by ntamas** [comment]
Well, we definitely need to turn these warnings off for generated code -- we cannot take responsibility for whatever code the generator puts there, so I'm okay with that.

As for turning off the warning in full -- I'm not so happy about that. For me it's just like the "unused import" warnings in higher-level languages like Python or JS, they warn me about potential extra stuff that used to be useful in the past but is not needed any more. I'd rather not have functions lying around in the codebase just for the vague reason that they _might_ be useful again at some point in the future. If we do want to have such functions, I'd rather put them in a separate file that is not linked into the codebase -- this way we can still keep these functions in the repo if we really want to, but they will not trigger warnings.

**Comment by szhorvat** [comment]
> Well, we definitely need to turn these warnings off for generated code -- we cannot take responsibility for whatever code the generator puts there, so I'm okay with that.

Can you please fix this? Using `target_compile_options` on `parsersources` gives ` target_compile_options called with non-compilable target type`. We need something like:

```
$<$<C_COMPILER_ID:GCC,Clang,AppleClang,Intel>:
    -Wno-unused-function
  >
```

----

> If we do want to have such functions, I'd rather put them in a separate file

In most cases these functions make sense in context. Try this to see some of them:

```
grep 'emporarily disabled' -R src
```

Commenting (`#if 0 ... #endif`) if probably better.

> that is not linked into the codebase

Not sure in what sense you use "linked", just noting that the compiler wouldn't emit code for these anyway: this is what the warning says.

**Comment by ntamas** [comment]
@szhorvat this is your lucky day :) I have spent quite a bit of time trying to limit the warning to the generated parser sources only, but the amount of CMake code I had to write to achieve that was too big a price to pay for this. So I'll just turn off the warning globally.
