### ISSUE TITLE
Add limited cross-compilation support, in order to better support Apple Silicon

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1683]
With Apple's transition from Intel to Arm, and their encouragement to build "universal binaries", there is going to be increased demand for cross-compilation. Whenever building a universal binary on macOS, we are effectively cross-compiling. Several package repositories will also want to cross-compile for Arm Macs (Anaconda does this, MacPorts does not—it natively compiles arm64 packages on Arm systems—, Homebrew I do not know).

Full cross-compilation support is difficult and fragile, so we should not attempt it. But there should be enough to make the most relevant use case, i.e. cross compilation between Intel and Arm macOS, feasible.

The primary obstacle to cross-compilation is `f2c`, which compiles _and runs_ an `arithchk` program to detect how the system handles floating-point numbers, and produce and `arith.h` header When cross-compiling, `arithchk` cannot be run on the current system.

The solution we tentatively agreed on in chat was to make it possible for the user to provide a pre-generated `arith.h` file.

Luckily, the same `arith.h` can be used for both arm64 and x86_64 on macOS (note that on 32-bit platforms, as well as on Windows, it's different!)  Here it is:

```
#define IEEE_8087
#define Arith_Kind_ASL 1
#define Long int
#define Intcast (int)(long)
#define Double_Align
#define X64_bit_pointers
#define NANCHECK
#define QNaN0 0x0
#define QNaN1 0x7ff80000
```

Thus, a pre-generated file can be used to build universal binaries on macOS.

**Comment by szhorvat** [comment]
I looked briefly into whether we could generate `arith.h` using CMake's facilities instead, but it seems that CMake also determines the relevant information (such as [endianness](https://cmake.org/cmake/help/latest/module/TestBigEndian.html)) by running (not just compiling) an executable on the current system. 

[It looks like CMake is receiving improvements regarding this in the upcoming version](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_BYTE_ORDER.html), precisely because of Apple Silicon.

**Comment by ntamas** [comment]
Implemented support for providing an external `arith.h` file in 1077368

Is there anything else in the scope of this issue for the time being?

**Comment by szhorvat** [comment]
No, let's close it.

@vtraag Can you please try if cross-compilation for Apple Silicon works on Anaconda with this approach?

**Comment by vtraag** [comment]
> @vtraag Can you please try if cross-compilation for Apple Silicon works on Anaconda with this approach?

@szhorvat, I can confirm it works.
