### ISSUE TITLE
Test fail for shared library on Windows

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1686]
**Describe the bug**
After successfully building `igraph` using CMake, all tests fail, presumably because the library cannot be found. This problem only appears on Anaconda. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=280259&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f for a log of the failure.

**To reproduce**
I am still investigating what the underlying problem is. The problem is easily reproducible in the Anaconda environment (see https://github.com/conda-forge/igraph-feedstock/pull/25 for the PR), but I have not been able to identify and replicate the problem locally. Presumably this is due to some paths that are being set in Anaconda, I am looking into this.

**Version information**
The released version 0.9.0 source tarball.

**Comment by szhorvat** [comment]
Can this be closed now?
