### ISSUE TITLE
Lexicographic comparison of igraph_vector_t

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1706]
**What is the feature or improvement you would like to see?**
Two `qsort`-compatible functions that can do lexicographic comparison of `igraph_vector_(whatever)_t` objects. One should do it the standard way, the other should effectively consider the reverse of each vector.

**Use cases for the feature**
Canonicalizing the output of some functions, canonicalizing results in unit tests.

Why the reverse lexicographic version as well? Some functions sort the output by the last element of vectors, which is useful to preserve (e.g. `get_all_shortest_paths_dijkstra`)

**Comment by GroteGnoom** [comment]
I would like to work on this, can I be assigned?

**Comment by szhorvat** [comment]
I assigned you, not sure if GitHub sent a notification. You know why this is useful for tests, so please go ahead. This should go on the `develop` branch as it's a new public function.
