### ISSUE TITLE
igraph_average_path_length() outputs unexpected values for directed graphs

### ISSUE THREAD

**Issue by heavywatal** [igraph/igraph#1721]
**Describe the bug**
`igraph_average_path_length()` outputs unexpected values for directed graphs. See the following minimal reprex.

**To reproduce**

```c++
// reprex.cpp
#include <igraph/igraph.h>
#include <iostream>

int main() {
  igraph_t graph;
  igraph_vector_t v;
  igraph_real_t edges[] = {
    0, 1,
    0, 2
  };
  igraph_vector_view(&v, edges, sizeof(edges) / sizeof(double));
  igraph_create(&graph, &v, 0, true);

  igraph_real_t res;
  igraph_average_path_length(&graph, &res, nullptr, true, true);
  std::cout << res << std::endl;
  return 0;
}
```
```
% clang++ -I$HOME/local/include -L$HOME/local/lib reprex.cpp -ligraph && ./a.out
1.33333
```

The average path length of the smallest bifurcating tree (two edges with length 1) should be 1 if I understand correctly.

**Version information**
`0.9.0` and `master`

**Comment by szhorvat** [comment]
Can you double-check this please? I am unable to reproduce this on my machine. The output is 1.

**Comment by heavywatal** [comment]
Oops, now it works correctly after cleaning my `~/local/` and reinstalling new igraph. Maybe my lazy update left some old headers or library, which played a little trick. Sorry for bothering, thank you again.

**Comment by szhorvat** [comment]
No problem, I'm glad it's not broken.

Added tests for this in 4019b1f299777605d2d8721f8e86a141244a0fb3 and b38239e988b630bf3bee83653fe141841a697402
