### ISSUE TITLE
min member of igraph_rng_type_t is never used

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1722]
`igraph_rng_type_t` has a `min` member, but it is never used, except in `igraph_rng_min()`.  All other functions, such as `igraph_rng_get_unif01`, implicitly assume that `min == 0`.

What shall we do with this?  The functions could be updated to take `min` into account, but this seems pointless. I would be surprised to see an RNG the lowest value of which is not 0.   Perhaps it would be better to deprecate this member, as well as `igraph_rng_min()`.

**Comment by szhorvat** [comment]
For now I added a comment noting that `min` is required to be zero, just in case someone would try to implement a new generator with `min != 0`.

**Comment by ntamas** [comment]
Yes, and let's also mark it as deprecated. I don't see much point in it either.

**Comment by ntamas** [comment]
Fixed in c57d4d4d0
