### ISSUE TITLE
Build fails with older clang versions due to unsupported -Wno-varargs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1727]
**Describe the bug**
The build fails with older clang versions due to the use of `-Wno-varargs`.

You can see a build log from MacPorts / OS X 10.7 here:

https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/45964/steps/install-port/logs/stdio

There are many errors like these:

```
clang: error: unknown warning option '-Wno-varargs'
```

We need to find out if we can make clang more tolerant of these.

On the other hand, I am not sure if the clang included in OS X 10.7 even supports C++11, which we now require. So it may not be worth the trouble.

**Version information**
0.9.0 release tarball

**Comment by szhorvat** [comment]
I believe this will be `-Wno-unknown-warning-option`, but maybe we don't want this in the main distribution. However, it is a useful workaround for package managers.

**Comment by ntamas** [comment]
An alternative is to check for `-Wno-varargs` support explicitly with [this CMake macro](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html).

**Comment by szhorvat** [comment]
Yes, that's probably better. It can also be used to eliminate the exceptions for the Intel compiler.
