### ISSUE TITLE
Make it compile with PGI

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#173]
Michael Bommarito kindly provided a diff.

---

Imported from Launchpad using lp2gh.
- date created: 2009-08-12T14:53:53Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/412566

**Comment by szhorvat** [comment]
@gaborcsardi It's been 7 years, but I thought you might be happy to hear that the dev version (with CMake build system) now works perfectly with the PGI compiler (tested with PGI 2020 on our HPC cluster).
