### ISSUE TITLE
Implement weighted pseudo-diameter computation

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1733]
This is a feature request to implement a weighted pseudo-diameter computation as `igraph_pseudo_diameter_dijkstra`.

Ref: #1223 and #1728

**Comment by szhorvat** [comment]
@GroteGnoom Would you like to be assigned to this?

**Comment by GroteGnoom** [comment]
Sure!

**Comment by GroteGnoom** [comment]
should this have the same interface as diameter_dijkstra, but with a starting vertex added? So including vertex_path and edge_path?

**Comment by szhorvat** [comment]
I would use the same interface as `pseudo_diameter` but with weights. The `diameter` functions at the moment just call `get_shortest_path` to compute the actual path. They are not faster to use than first computing the starting points and then separately getting the path. While theoretically they _could_ be made faster, at the moment I am inclined to keep things simple, and not add the path arguments.

Since this will go into the next version only (0.10 or 1.0), there will still be time to make changes, if we decide to.

However, I _would_ add the `directed` argument, which I failed to pay attention to when reviewing the `pseudo_diameter` PR. I think we should have that both for the weighted and unweighted versions. We can add it to the unweighted version in a followup PR.

**Comment by szhorvat** [comment]
This is completed.
