### ISSUE TITLE
neighbors() and incident() should allow controlling loop inclusion

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1737]
**What is the feature or improvement you would like to see?**
Similar to `adjlist_init()` and `inclist_init()`, `neighbors()` and `incident()` should allow controlling whether self-loops are included: not at all; once; or twice.

**Use cases for the feature**
The use case is the same as for `adjlist_init` and `inclist_init`. For many graph algorithms, it is necessary to have this control. `neighbors()` and `incident()` are sometimes used in place of `adjlist_init()` or `inclist_init()` because there is no need to keep the entire adjlist/inclist in memory. Recently, while implementing cycle basis calculations, I found myself using an inclist instead of `incident()` just because `icident()` did not have the necessary `IGRAPH_LOOPS_ONCE`. I suspect that the VF2 algorithm could be adapted to loopy graphs relatively easily if we had this feature. The need keeps coming up repeatedly.

I consider this a high-priority issue, but I don't mind if this is implemented in` neighbors()` itself or an additional function.

**Comment by GroteGnoom** [comment]
(There was also a bit of discussion here: https://igraph.discourse.group/t/the-unit-tests-thread/597/50)
If nobody disagrees, I'll change neighbors to take two more parameters, and then change (almost) all current C calls to igraph_neighbors(..., ..., IGRAPH_LOOPS_ONCE, IGRAPH_MULTIPLE).

**Comment by vtraag** [comment]
For more information, there were some previous discussions about this in https://github.com/igraph/igraph/pull/1652.

**Comment by ntamas** [comment]
I'm a bit reluctant about changing the currently relatively friendly interface of `igraph_neighbors()` by adding two more arguments that people don't need to care about in 90% of the cases (or even more). These nits are relevant only if the user is routinely dealing with non-simple graphs. How about adding an `igraph_neighbors_advanced()` instead, keeping `igraph_neighbors()` as is, and then changing `igraph_neighbors()`'s internals to call `igraph_neighbors_advanced()`?

(The name of the new function is subject to debate, just like the entire proposal).

**Comment by szhorvat** [comment]
I don't mind about the name at all, but I think we do need this functionality. 

`igraph_neighbors` is sometimes an alternative to `adjlist` and `lazy_adjlist`. They do the same thing, the only difference is in when the neighbour list is generated, and for how long its kept.  Therefore, `neighbors` (or another "advanced" function) should have the same features.  It is clear that `adjlist` needed this feature: several functions use it, and several functions could be improved or generalized when adjlist gained this feature. If `neighbors` gains it, several more functions can be improved (maybe VF2 can be fixed for non-simple graphs).

**Comment by szhorvat** [comment]
It's something that must be done with extreme case though, as it touches on the core graph API. Functions in the core API often depend on peculiarities of the graph representation, and must sometimes respect not very well documented properties of their output, such as the order in which the neighbours are listed (!).  It is very easy to inadvertently break things.

Right now, `adjlist_init` calls `igraph_neighbors`, then filters its output according to the loops/multi options. I always though it would be better (= more efficient, = easier to maintain) if `neighbors` could avoid generating loops/multi edges from the beginning.

It was @ntamas who last touched this functionality.

**Comment by GroteGnoom** [comment]
I really couldn't think of a better name 🙂 

Allright, I leave the igraph_neighbors interface the same, let it call igraph_neighbors_advanced(), which takes the two extra parameters. Once the advanced version exists we can use it to fix (igraph_dyad_census) or improve (adjlist_init) existing functions.

Is that ok with everybody?

**Comment by vtraag** [comment]
Could we perhaps keep the advanced function internal for now? This discussion ties in with larger discussions about the graph structure and the long-term API. An unnecessary proliferation of these two additional argument in many places, as @ntamas points out, is probably also not desirable.

**Comment by szhorvat** [comment]
I have no problem with keeping it internal, but I disagree that these are unnecessary. I asked for the feature because I keep finding a need again and again. @GroteGnoom offered to work on it because he also needed it (see the link to the discourse forum).

**Comment by vtraag** [comment]
I am not saying the functionality is not required. Rather, as @ntamas pointed out, by having only a single function, you would get a proliferation of these argument everywhere, even if they are not needed. Hence, the separate function would be warranted I think. By keeping it internal, we could more easily change things around in the future, if we so decide. We could hence have `igraph_i_neighbors` with the two additional argument and `igraph_neighbors`, which could call `igraph_i_neighbors` with the "default" arguments.

**Comment by szhorvat** [comment]
> have `igraph_i_neighbors` with the two additional argument

I like this naming better than `advanced`.

**Comment by GroteGnoom** [comment]
I was wondering why this wasn't closed automatically, since #1774 is merged, but https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue mentions:

> please note that the pull request must be on the default branch

and of course it's merged to develop, which means this needs to be closed manually.
