### ISSUE TITLE
inclusion of Centrality measures from R

### ISSUE THREAD

**Issue by BrandonKMLee** [igraph/igraph#1741]
**What is the feature or improvement you would like to see?**
The inclusion of other centrality measures from certain R libraries that seems "dead" e.g. CentiServer http://www.centiserver.org/
(Also integration with Python for usability purposes.)

From CentiServe in https://rdrr.io/cran/centiserve/man/:
- [ ] averagedis | Find the average distance of a node
- [ ] barycenter | Find the barycenter centrality score
- [ ] bottleneck | Find the BottleNeck centrality score
- [ ] centroid | Find the centroid value of graph vertices
- [ ] closeness.currentflow | Find current-flow closeness centrality
- [ ] closeness.freeman | Find the closeness centrality in a strongly connected graph
- [ ] closeness.latora | Find the variant (Latora) closeness centrality in a...
- [ ] closeness.residual | Find the residual closeness centrality
- [ ] closeness.vitality | Find the closeness vitality centrality in a strongly...
- [ ] clusterrank | Find the ClusterRank ranks in a graph
- [ ] communibet | Find the communicability betweenness centrality
- [ ] communitycent | Find the community-based node centrality
- [ ] crossclique | Find the cross-clique connectivity (centrality)
- [ ] decay | Find the decay centrality of a given vertex
- [ ] diffusion.degree | Find the variant (Latora) closeness centrality in a...
- [ ] dmnc | Find the density of maximum neighborhood component (DMNC) in...
- [ ] entropy | Find the entropy centrality in a graph
- [ ] epc | Find the edge percolated component (EPC) in a graph
- [ ] geokpath | Find the geodesic k-path centrality
- [ ] hubbell | Find the Hubbell centrality or the Hubbell Index
- [ ] katzcent | Find the Katz centrality (Katz Status Index)
- [ ] laplacian | Find the laplacian centrality
- [ ] leaderrank | Find the LeaderRank in a directed graph
- [ ] leverage | Find the leverage centrality
- [ ] lincent | Find the lin centrality in a graph
- [ ] lobby | Find the lobby index (centrality)
- [ ] markovcent | Find the markov centrality score
- [ ] mnc | Find the maximum neighborhood component (MNC)
- [ ] pairwisedis | Find the pairwise disconnectivity index
- [ ] radiality | Find the radiality centrality in a graph
- [ ] salsa | Find the SALSA as 'hub' or 'authority' score
- [ ] semilocal | Find the semi local centrality (or local centrality)
- [ ] topocoefficient | Find the topological coefficient of a node in a undirected...

According to NetRankr
- [ ] residual closeness (Dangalchev,2006)
- [ ] generalized closeness (Agneessens et al.,2017)
- [ ] decay centrality (Jackson, 2010)
- [ ] integration centrality (Valente & Foreman, 1998)
- [ ] subgraph centrality
- [ ] communicability centrality
- [ ] odd/even subgraph centrality
- [ ] katz status

**References**
- https://rdrr.io/cran/centiserve/
- https://www.rdocumentation.org/packages/tidygraph/versions/1.2.0/topics/centrality with reference to https://rdrr.io/cran/netrankr/man/netrankr.html
- http://cran.nexr.com/web/packages/CINNA/vignettes/CINNA.html#various-types-of-centralities-computation

With callbacks from https://github.com/GiulioRossetti/cdlib/issues/148

**Comment by iosonofabio** [comment]
Thank you @BrandonKMLee for the useful wishlist.

Integration with R and Python is pretty easy for these things, but implementing all those algorithms in C would take forever. Would you be willing to make a few PRs to implement the ones you need?

**Comment by BrandonKMLee** [comment]
Currently looking at:
- Degree Centrality replacements: Hub Centrality, PageRank Centrality, and Leverage Centrality
- Betweenness Centrality replacements: Eigenvector Centrality, Information Centrality, and Laplacian Centrality
- Betweenness Centrality replacements: Bridging Centrality
