### ISSUE TITLE
igraph cannot be used as subproject

### ISSUE THREAD

**Issue by monellz** [igraph/igraph#1746]
**Describe the bug**
I try to use igraph as my subproject, but it gives me Error like

>CMake Error: File /${MY_PROJECT_SOURCE_DIR}/igraph.pc.in does not exist.

CMakeLists.txt in igraph use CMAKE_SOURCE_DIR to get its location, which is wrong when it is used as subdirectory.

**To reproduce**
```add_subdirectory``` for igraph

**Version information**
0.9.1

**Comment by ntamas** [comment]
I'll try replaceing occurrences of `${CMAKE_SOURCE_DIR}` with `${PROJECT_SOURCE_DIR}` and see how it goes.

**Comment by ntamas** [comment]
See https://github.com/igraph/igraph/commit/7996a15ea3757a71463231086de5df35064f7deb -- this seems to have done the trick for me; I was able to build a small test project that depends on igraph as a subproject with the following `CMakeLists.txt` file:

```
cmake_minimum_required(VERSION 3.16)

project(igraph_as_subproj C CXX)

add_subdirectory(../igraph igraph)

add_executable(test test.c)
target_link_libraries(test igraph)
```

Let me know if you are still running into issues.

**Comment by monellz** [comment]
It works well with my own project now.

Thanks a lot~
