### ISSUE TITLE
0.9.1: error: '_Generic' is a C11 extension

### ISSUE THREAD

**Issue by yurivict** [igraph/igraph#1748]
clang-10 fails to compile it on FreeBSD 12.2:
```
/usr/ports/math/igraph/work/igraph-0.9.1/src/math/utils.c:41:12: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
    return isfinite(x);
           ^
/usr/include/math.h:111:21: note: expanded from macro 'isfinite'
#define isfinite(x) __fp_type_select(x, __isfinitef, __isfinite, __isfinitel)
                    ^
/usr/include/math.h:82:39: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                      ^
/usr/ports/math/igraph/work/igraph-0.9.1/src/math/utils.c:241:12: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
    return isnan(x);
           ^
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
        __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
        ^
```

**Comment by szhorvat** [comment]
Can you try to compile this short C program, using the `-std=gnu99` option, and post the complete output?

```c
#include <math.h>

int main() { return !isfinite(1.0); }
```

----

From the error you posted, it appears that `isfinite` only works in C11 mode on this platform. I don't know why this would be the case, as igraph explicitly requests C99 through CMake (which should translate to `-std=gnu99`), and [`isfinite`](https://en.cppreference.com/w/c/numeric/math/isfinite) is a standard C99 feature.

I have no problem compiling igraph wit clang 10.0.1 on macOS:


```
$ clang-mp-10 --version
clang version 10.0.1 
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-10/bin
```

It might also be useful to see the full output from CMake (so we can see lines such as `-- The C compiler identification is Clang 10.0.1` and `-- Looking for isfinite - found`). If you can try to compile it locally (instead of on a build server), it would be useful to see the compiler invocation. You can compile in single-threaded mode and request verbose output. With make, `make -j1 VERBOSE=1`, or with ninja, `ninja -j1 -v`.

**Comment by szhorvat** [comment]
Here's a similar complaint, albeit with no details. https://github.com/redis/redis/issues/2562

**Comment by yurivict** [comment]
> Can you try to compile this short C program, using the -std=gnu99 option, and post the complete output?

It succeeds without warnings.

**Comment by szhorvat** [comment]
In that case it would be really great to see:

 - full output from CMake
 - actual compiler invocation for the offending file (compile with `-j1` and verbose mode, wait until fails, copy the command here)

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/igraph.log

**Comment by yurivict** [comment]
```
cmake \
-DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -GNinja
```

**Comment by szhorvat** [comment]
Thanks @yurivict .

I'm stumped. Here's the full compiler invocation:

```
[58/459] /usr/bin/cc -DIGRAPH_STATIC -DIGRAPH_VERIFY_FINALLY_STACK=0 -DNCOMPLEX -DPRPACK_IGRAPH_SUPPORT=1 -DIGRAPH_FILE_BASENAME=\"src/math/utils.c\" -I/usr/ports/math/igraph/work/igraph-0.9.1/include -Iinclude -Isrc -I/usr/ports/math/igraph/work/igraph-0.9.1/src -I/usr/ports/math/igraph/work/igraph-0.9.1/vendor -I/usr/local/include/suitesparse -I/usr/local/include -I/usr/ports/math/igraph/work/igraph-0.9.1/src/usr/local/include/libxml2 -I/usr/local/include/libxml2 -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -pedantic -Werror -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-varargs -std=gnu99 -MD -MT src/CMakeFiles/igraph.dir/math/utils.c.o -MF src/CMakeFiles/igraph.dir/math/utils.c.o.d -o src/CMakeFiles/igraph.dir/math/utils.c.o -c /usr/ports/math/igraph/work/igraph-0.9.1/src/math/utils.c
```

I see nothing relevant here.

Can you please try to compile the small test program from above, but using all warning options this time?

```
-Wall -Wextra -pedantic -std=gnu99
```

If that still shows no warnings, can you add all the options from the above command, even though I see no reason why they should matter?

```
-fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -O2 -Wall -Wextra -pedantic -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-varargs -std=gnu99
```

----

Are you aware of any ready-to-go FreeBSD virtualbox images that would make it easy for me to try this on my own? Otherwise I guess I'd have to install it from scratch ... (can't do that today)

----

I should note that the problem is really just a warning, not an error. It causes compilation to fail because of `-Werror`. If you patch that out, it _should_ build fine. However, I would not want to apply such drastic measures without at least understanding why the warning is triggered, and where the real problem lies (in igraph's build system or FreeBSD's compiler setup).

**Comment by szhorvat** [comment]
Note: the `-Werror` is in `igraph/etc/cmake/compilers.cmake`.

**Comment by szhorvat** [comment]
There are some more hits here, and `-pedantic` seems to be a common theme:

https://www.google.com/search?q="'_Generic'+is+a+C11+extension"+freebsd

Is it possible that the problem is with FreeBSD's `math.h` header in that it uses C11 features even in C99 mode?

**Comment by yurivict** [comment]
```
$ cc -Wall -Wextra -pedantic -std=gnu99 -c x.c
x.c:4:22: warning: '_Generic' is a C11 extension [-Wc11-extensions]
int main() { return !isfinite(1.0); }
                     ^
/usr/include/math.h:111:21: note: expanded from macro 'isfinite'
#define isfinite(x) __fp_type_select(x, __isfinitef, __isfinite, __isfinitel)
                    ^
/usr/include/math.h:82:39: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                      ^
1 warning generated.
```

**Comment by yurivict** [comment]
Here are VM images: https://download.freebsd.org/ftp/releases/VM-IMAGES/12.2-RELEASE/amd64/Latest/

**Comment by szhorvat** [comment]
@yurivict It seems to me that this is a problem with the `math.h` header on FreeBSD. There should not be a warning with these flags. Could you please take it up with whoever is in charge of clang on FreeBSD?

For now, I would recommend patching igraph 0.9.1 in FreeBSD and removing `-Werror` from `etc/cmake/compilers.cmake`.

After Easter, we will discuss this within igraph as see if anything should be done about this for igraph 0.9.2. An explanation of why the `math.h` header is like this on FreeBSD would be useful. Right now, it seems to me that the problem should be fixed there.

**Comment by yurivict** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254714

**Comment by szhorvat** [comment]
> https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254714

What are the hopes for a response? This truly is an issue with the header in FreeBSD, and would be nice to have it fixed there. From the google link I posted above, it is clear that it also affects other packages.

**Comment by yurivict** [comment]
It's a warning in most cases, so it didn't attract much attention.

I'll see if this can be forwarded to somebody who can fix it.

**Comment by yurivict** [comment]
I filed the FreeBSD port update request for approval: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254873

This takes this issue off your plate.

Thank you for your help!
Yuri

**Comment by szhorvat** [comment]
@yurivict , from the above link:

> Do you test the patch for R-cran-igraph and py-python-igraph ?

R/igraph is self-contained and does not link (cannot link) to a separate igraph.

python-igraph 0.9.x will by default link to a bundled igraph. If you want to link it to a separate igraph, be sure to use the latest version of both.

**Comment by yurivict** [comment]
@szhorvat 

The original problem in math.h is now fixed. It'll take time for the fix to propagate and all releases will have it only in 1+ years. The port patch would have to stay for this reason.

------

py-igraph uses the same library as external dependency and now fails:
```
  if (igraph_is_graphical(&out_deg, is_directed ? &in_deg : 0, IGRAPH_LOOPS_SW | IGRAPH_MULTI_SW, &result)) {
      ^
src/_igraph/igraphmodule.c:433:64: error: use of undeclared identifier 'IGRAPH_LOOPS_SW'; did you mean 'IGRAPH_LOOPS'?
  if (igraph_is_graphical(&out_deg, is_directed ? &in_deg : 0, IGRAPH_LOOPS_SW | IGRAPH_MULTI_SW, &result)) {
                                                               ^~~~~~~~~~~~~~~
                                                               IGRAPH_LOOPS
/usr/local/include/igraph/igraph_constants.h:39:37: note: 'IGRAPH_LOOPS' declared here
typedef enum { IGRAPH_NO_LOOPS = 0, IGRAPH_LOOPS = 1 } igraph_i_loops_t;
                                    ^
src/_igraph/igraphmodule.c:433:82: error: use of undeclared identifier 'IGRAPH_MULTI_SW'; did you mean 'IGRAPH_MULTIPLE'?
  if (igraph_is_graphical(&out_deg, is_directed ? &in_deg : 0, IGRAPH_LOOPS_SW | IGRAPH_MULTI_SW, &result)) {
                                                                                 ^~~~~~~~~~~~~~~
                                                                                 IGRAPH_MULTIPLE
```

-----

R-cran-igraph-1.2.6 doesn't depend on igraph and its port is at the latest version.

**Comment by szhorvat** [comment]
> I filed the FreeBSD port update request for approval: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254873

@yurivict A few minor comments:

`bison` is not a dependency for building from the release tarball (it's only needed when building from the git repo directly). `libtool` should not be needed either.

There's a comment: `BROKEN_sparc64=		fails to compile: uses x86 asm`. The is no assembly code in igraph.

`arpack-ng` should be a dependency too (if not present, igraph uses a bundled f2c'd version, but an external and newer version is recommended).

Pre-built documentation is available in the release tarball, in `doc/html`, and you can install it somewhere (e.g. `share/doc/igraph`) if you like.
