### ISSUE TITLE
Jaccard and Dice similarity functions should accept a from_vs and a to_vs instead of just a single vs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#175]
This would allow one to calculate, say, the histogram of the similarity values of large graphs when the whole similarity matrix does not fit into memory but a single row of the matrix does.

---

Imported from Launchpad using lp2gh.
- date created: 2009-09-23T10:01:52Z
- owner: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/435155

**Comment by GroteGnoom** [comment]
Fixed in #2346 on develop.
