### ISSUE TITLE
Windows build does not install correctly using MSVC generator

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1755]
**Describe the bug**
When building using `cmake` >= 3.19.8 on Windows, with MSVC generator, `cmake --build . --parallel --config Release` incorrectly builds a Debug build, while `cmake --install` tries to install a Release build, which naturally fails. 

**To reproduce**
```bash
mkdir build && cd build
cmake ..
cmake --build . --parallel --config Release  # Not respected, Debug is build instead
cmake --install                              # Fails, because it tries to install Release build
```

**Version information**
Version 0.9.1 and most recent `master` version.

**Workaround**
Use `cmake --build . --config Release`, i.e. remove the `--parallel` option.

**Comment by vtraag** [comment]
Please note that this is connected to the current default build setup that is used in `python-igraph`. I am currently correcting this for `python-igraph`, and will push a PR shortly (presumably tomorrow).

**Comment by vtraag** [comment]
I have reported the issue [upstream](https://gitlab.kitware.com/cmake/cmake/-/issues/22048), as I think this is a bug in CMake.

**Comment by ntamas** [comment]
I was wondering whether this could be reproduced with a simpler `CMakeLists.txt` file on Windows, i.e. something like this:

```
cmake_minimum_required(VERSION 3.19)

project(test C)

add_executable(test test.c)
```

I'd try it because this will be the first thing that upstream asks you to do anyway, and it could exclude the possibility that we are doing something wrong by messing around with `CMAKE_BUILD_TYPE` in `etc/cmake/BuildType.cmake` (although that shouldn't be a problem because MSVC is a multi-config generator and we do not touch those).

**Comment by vtraag** [comment]
Yes, this is presumably something that I should do indeed at one point. I have not yet found the time to do so yet, but I thought it would make sense to report it upstream already anyway. Let me first wait for a first response there, perhaps the issue is simple enough to understand as is, since it is already quite specifically traced to a specific version and specific combination of flags.

**Comment by vtraag** [comment]
I can't reproduce the issue locally anymore. For the life of me, I don't understand. I reproduced the problem last week locally, testing it and nailing it down to a change in CMake since 3.19.8. Now, with the exact same version, I don't have this problem. Perhaps this problem only surfaces in combination with a particular VS version, which might have updated in the meantime, I am not sure.

For reference, the problem really did appear, see [here](https://github.com/vtraag/python-igraph/runs/2291253797?check_suite_focus=true#step:8:227) the log file of building `python-igraph`, which runs the exact code as stated above.

**Comment by ntamas** [comment]
Shall we close this issue then and go ahead with 0.9.2? My plans are to finish the release tomorrow or the day after.

**Comment by vtraag** [comment]
Yep, let's do that...

**Comment by szhorvat** [comment]
It looks like you're getting responses from upstream.
