### ISSUE TITLE
Move raytracer to R interface

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1757]
**What improvement would you like to see?**
The code in `vendor/simpleraytracer` should be moved to the R interface.

**Use cases for the feature**
There is no need for this code in the C core.

**References**
https://github.com/igraph/igraph/issues/1651#issuecomment-817860968

**Comment by ntamas** [comment]
https://github.com/igraph/rigraph/commit/b708a61d79b14591e555b11b503d21f03a6b6088 moves the `simpleraytracer` folder to the R interface. It can now be removed from the C core if the CI passes.
