### ISSUE TITLE
Add configuration option to toggle OpenMP

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1764]
igraph now compiles PRPACK with OpenMP enabled, if OpenMP is available. This is not always desired, so there should be a switch to toggle OpenMP on or off (perhaps with an auto setting).

Disadvantages of OpenMP:

 - It requires linking to additional libraries (libomp), which are linked dynamically by default. This makes it inconvenient to create self-contained igraph binary distributions.
 - While PageRank calculation will be faster with OpenMP, it comes at a great cost of CPU usage. In a benchmark, I see this:  
   ```
       OMP: 13 PageRank weighted, DeBruijn(7,7), PRPACK, 1x                                   1.23s   4.78s  0.134s
    no OMP: 13 PageRank weighted, DeBruijn(7,7), PRPACK, 1x                                   1.88s   1.78s  0.096s
    ```
    This is a speedup of 1.5 at the cost of 2.7x more total CPU usage. Depending on application, it may make sense to build igraph without OpenMP instead of always disabling OpenMP at runtime using environment variables.

**Comment by ntamas** [comment]
> This is a speedup of 1.5 at the cost of 2.7x more total CPU usage. 

It probably depends on the size of the graph, though. It might be the case that the test graph is too small for parallelization to have any reasonable effect (the cost of aggregating the results outweighs the benefit of parallelization).

Nevertheless, I'll add a flag for OpenMP.

**Comment by szhorvat** [comment]
Just noting that this is the biggest graph in the benchmarks I wrote, 823,543 vertices, 5,764,801 edges.

**Comment by ntamas** [comment]
> Just noting that this is the biggest graph in the benchmarks I wrote, 823,543 vertices, 5,764,801 edges.

Another guess: PRPACK might use OpenMP parallelization to calculate Pagerank independently for each strongly connected component, so if your graph consist of one giant strongly connected component and only a few additional vertices, then there is not much to gain with parallelization.
