### ISSUE TITLE
Tests fail on 0.9.2 in Gentoo

### ISSUE THREAD

**Issue by epsilon-0** [igraph/igraph#1775]
**Describe the bug**
Four tests are failing, summary:
```
The following tests FAILED:
        196 - test::igraph_layout_kamada_kawai_3d_bug_1462 (Failed)
        287 - test::igraph_community_infomap (Failed)
        355 - example::igraph_scg_grouping3 (Failed)
        358 - example::igraph_scg_semiprojectors2 (Failed)
```

**To reproduce**
configured with
```
cmake -C /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DUSE_CCACHE=OFF -DIGRAPH_GLPK_SUPPORT
=ON -DIGRAPH_GRAPHML_SUPPORT=ON -DIGRAPH_USE_INTERNAL_ARPACK=OFF -DIGRAPH_USE_INTERNAL_BLAS=OFF -DIGRAPH_USE_INTERNAL_CXSPARSE=OFF -DIGRAPH_USE_INTERNAL_GLPK=OFF -DIGRAPH_USE
_INTERNAL_GMP=OFF -DIGRAPH_USE_INTERNAL_LAPACK=OFF -DIGRAPH_ENABLE_TLS=yes -DBUILD_TESTING=yes -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-libs/igra
ph-0.9.2/work/igraph-0.9.2_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2
```
full build log - https://bsd.ac/r/igraph-build.log

**Version information**
0.9.2 from github releases.

**Comment by szhorvat** [comment]
Picking out the relevant parts of the log.

Many floating point optimizations flags are used. I think the failures are likely to be due to numerical precision issues, triggered by these flags.

```
CFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=8 -fuse-linker-plugin -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -falign-functions=32 -pipe -Wl,-O1 -Wl,--as-needed'
```

I have never seem the following two failures before. If you have time, @epsilon-0, can you find out which specific option combination causes them?

I should note that these failures almost certainly don't indicate a real problem (i.e. the result is not "incorrect" just different).

```
286/386 Test #287: test::igraph_community_infomap
[K287/386 Test #287: test::igraph_community_infomap.....................***Failed    0.57 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/tests/unit/igraph_community_infomap.out	2021-02-16 09:59:34.000000000 -0500
+++ /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2_build/tests/test_igraph_community_infomap.out	2021-04-23 05:50:07.554945628 -0400
@@ -18,4 +18,4 @@
 Membership: 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 4 3 3 
 # Wiktionary english verbs (synonymy 2008)
 |V|=7339 |E|=8293 directed=0
-Codelength OK.
+Codelength was 5.70902, expected 5.70800
-- -------------------------------------------------------
CMake Error at /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```

```
[K196/386 Test #196: test::igraph_layout_kamada_kawai_3d_bug_1462.......***Failed    0.01 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/tests/regression/igraph_layout_kamada_kawai_3d_bug_1462.out	2021-03-29 14:49:25.000000000 -0400
+++ /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2_build/tests/test_igraph_layout_kamada_kawai_3d_bug_1462.out	2021-04-23 05:50:04.714860109 -0400
@@ -1,2 +1,2 @@
-0.00 0.00 -0.41
-0.00 0.00 1.00
+-0.15 0.00 -0.41
+0.01 0.00 1.00
-- -------------------------------------------------------
CMake Error at /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```

We are aware that the following two are problematic. I would recommend disabling the tests. See e.g. #1694  There is no one who understand the SCG method and code deeply, or would have the significant amount of time needed to deal with it and figure out if this failure even indicates a real problem (probably it does not). Since this is a niche method, it will very likely be split to a separate library for igraph 0.10.

```
[K355/386 Test #355: example::igraph_scg_grouping3......................***Failed    0.01 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/examples/simple/igraph_scg_grouping3.out	2021-02-16 09:59:33.000000000 -0500
+++ /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2_build/tests/example_igraph_scg_grouping3.out	2021-04-23 05:50:09.611674226 -0400
@@ -1,4 +1,4 @@
-0 0 0 1 0 1 0 2 2 2
+0 0 1 1 0 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 2 3 4 5 6 7 8 9
-- -------------------------------------------------------
CMake Error at /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```

```
[K358/386 Test #358: example::igraph_scg_semiprojectors2................***Failed    0.01 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/examples/simple/igraph_scg_semiprojectors2.out	2021-02-16 09:59:33.000000000 -0500
+++ /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2_build/tests/example_igraph_scg_semiprojectors2.out	2021-04-23 05:50:09.641675130 -0400
@@ -1,11 +1,11 @@
 ----------------------
-0.222222 0.222222 0.111111 0 0.222222 0 0.222222 0 0 0
-0 0 0 0.333333 0 0.666667 0 0 0 0
-0 0 0 0 0 0 0 0.166667 0.333333 0.5
+0.181818 0.181818 0 0 0.181818 0 0.181818 0 0 0.272727
+0 0 0.25 0.25 0 0.5 0 0 0 0
+0 0 0 0 0 0 0 0.333333 0.666667 0
 ---
-1 1 1 0 1 0 1 0 0 0
-0 0 0 1 0 1 0 0 0 0
-0 0 0 0 0 0 0 1 1 1
+1 1 0 0 1 0 1 0 0 1
+0 0 1 1 0 1 0 0 0 0
+0 0 0 0 0 0 0 1 1 0
 ---
 ----------------------
 0.285714 0 0 0 0 0 0.285714 0 0 0.428571
-- -------------------------------------------------------
CMake Error at /var/tmp/portage/dev-libs/igraph-0.9.2/work/igraph-0.9.2/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```

**Comment by szhorvat** [comment]
I can reproduce the first two with gcc 10.3 on macOS and

```
-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -falign-functions=32
```

**Comment by epsilon-0** [comment]
@szhorvat 
Thanks for the quick reply.
I can dig more into this tonight!
Then I can find out the exact flags.

**Comment by szhorvat** [comment]
> EDIT: To address one of the comments, I am using the netlib reference BLAS/LAPACK, so I don't think that should be the issue (probably).

It seems you link to an external ARPACK. Is it possible that this external version of ARPACK links to OpenBLAS?

**Comment by szhorvat** [comment]
The `layout_kamada_kawai_3d_bug_1462` failure is caused by `-freciprocal-math -march=native` on my system.

The GCC manual says:

> -freciprocal-math
>
>    Allow the reciprocal of a value to be used instead of dividing by the value if this enables optimizations. For example x / y can be replaced with x * (1/y), which is useful if (1/y) is subject to common subexpression elimination. Note that this loses precision and increases the number of flops operating on the value.
>
>   The default is -fno-reciprocal-math.

**Comment by szhorvat** [comment]
The `igraph_community_infomap` failure is caused by `-fno-signed-zeros -fno-trapping-math -fassociative-math -march=native` where `-fassociative-math` is the critical option and `-fno-signed-zeros -fno-trapping-math` are required to be able to turn it on.

> -fassociative-math
>
>    Allow re-association of operands in series of floating-point operations. This violates the ISO C and C++ language standard by possibly changing computation result. NOTE: re-ordering may change the sign of zero **as well as ignore NaNs and inhibit or create underflow or overflow** (and thus cannot be used on code that relies on rounding behavior like (x + 2**52) - 2**52. May also reorder floating-point comparisons and thus may not be used when ordered comparisons are required. This option requires that both -fno-signed-zeros and -fno-trapping-math be in effect. Moreover, it doesn’t make much sense with -frounding-math. For Fortran the option is automatically enabled when both -fno-signed-zeros and -fno-trapping-math are in effect.
>
>    The default is -fno-associative-math.

This sounds dangerous to me because of the bit I highlighted.

**Comment by epsilon-0** [comment]
Oh, wow thanks for the analysis!
Yes, after removing these flags, the first two tests are passing too.
I've disabled the two scg examples for gentoo, so everything is OK now!
