### ISSUE TITLE
igraph does not link correctly when building on MSYS2 / MinGW

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1776]
@szhorvat I am sitting on a `cmake` issue when building the static library (for `MINGW32/64`) which is not able to resolve all symbols `igraph_...` or `IGRAPH_...` due to a subtle `cmake` bug. The following script does reveal which symbols are not resolvable by `libigraph.a`

```
nm libigraph.a | awk '
# Detect in the static library 'libigraph.a' unresolved symbols with name
# beginning with 'igraph_' or 'IGRAPH_'.
# sample call: nm libigraph.a | awk -f <thisscript>
# NB: The script is POSIX-compliant and should work with any output structure of 'nm'.
NF >= 2 {
  symb = ""
  type = ""
  for(i=1;i<=NF;i++) {
    if($i ~ /^[a-zA-Z]$/)
      type = $i
    else if ( $i ~ /^(igraph|IGRAPH)_/)
      symb = $i
  }
  if(symb && type) {
    if(type ~ /^U$/ ) {
      aUndef[symb]++
      n_undef++
    } else if (type ~ /^[ABDT]$/ ) {
      aDef[symb]++
      n_def++
    }
  }
}

END{
  # Report an error unless defined and undefined symbols are detected.
  if(!n_def || !n_undef) {
    print "Could not detect defined and/or undefined symbols in static library." > "/dev/stderr"
    exit(2)
  }
  n=0
  for(u in aUndef) {
    if(!(u in aDef)) {
      if(!n) print "Unresolved symbols:"
      print u
      n++
    }
  }
  exit(!!n)
}
'
```
The reason is that 
* the igraph repo contains c(pp)-files with **same** basenames in different folders
* `cmake` 's link statement calls `ar` multiple times where object files with same basename are **replaced** (cf. the file `link.txt` generated by `cmake`)

Workaround: Avoid c(pp)-files with same basenames throughout the repo by, e.g., renaming them.

Xref: [cmake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/21988) I, unfortunately, did not have the time to follow-up with.

_Originally posted by @jannick0 in https://github.com/igraph/igraph/issues/1651#issuecomment-821860312_

**Comment by szhorvat** [comment]
@jannick0 Let us move the conversation about the MSYS2 linking issue to here, and try to fix it before 0.9.3.  Can you try and see if the problem is present with version 0.9.2 as well?

**Comment by szhorvat** [comment]
From: https://github.com/igraph/igraph/issues/1651#issuecomment-821961367

@jannick0 Here's a complete list of commands I used, that revealed no problems. What do you do differently? I used MinGW 64-bit, fully updated MSYS2 as of today, Windows 7.

```shell
wget https://github.com/igraph/igraph/releases/download/0.9.2/igraph-0.9.2.tar.gz
tar xf igraph-0.9.2.tar.gz
cd igraph-0.9.2
mkdir build && cd build
cmake .. -G'MSYS Makefiles' -DIGRAPH_USE_INTERNAL_ARPACK=ON -DIGRAPH_USE_INTERNAL_BLAS=ON -DIGRAPH_USE_INTERNAL_LAPACK=ON -DIGRAPH_USE_INTERNAL_CXSPARSE=ON -DIGRAPH_USE_INTERNAL_GLPK=ON -DIGRAPH_USE_INTERNAL_GMP=ON -DIGRAPH_GRAPHML_SUPPORT=ON
make -j4
make -j4 check
cd src
nm libigraph.a | awk '
# Detect in the static library 'libigraph.a' unresolved symbols with name
# beginning with 'igraph_' or 'IGRAPH_'.
# sample call: nm libigraph.a | awk -f <thisscript>
# NB: The script is POSIX-compliant and should work with any output structure of 'nm'.
NF >= 2 {
  symb = ""
  type = ""
  for(i=1;i<=NF;i++) {
    if($i ~ /^[a-zA-Z]$/)
      type = $i
    else if ( $i ~ /^(igraph|IGRAPH)_/)
      symb = $i
  }
  if(symb && type) {
    if(type ~ /^U$/ ) {
      aUndef[symb]++
      n_undef++
    } else if (type ~ /^[ABDTR]$/ ) {
      aDef[symb]++
      n_def++
    }
  }
}

END{
  # Report an error unless defined and undefined symbols are detected.
  if(!n_def || !n_undef) {
    print "Could not detect defined and/or undefined symbols in static library." > "/dev/stderr"
    exit(2)
  }
  n=0
  for(u in aUndef) {
    if(!(u in aDef)) {
      if(!n) print "Unresolved symbols:"
      print u
      n++
    }
  }
  exit(!!n)
}
'
```

**Comment by szhorvat** [comment]
@jannick0 Unfortunately, I do not have on-demand access to a Windows computer. My option are remote access (when not used by others) or a super-slow VM. Therefore, before I answer [your questions](https://github.com/igraph/igraph/issues/1651#issuecomment-822000754) in detail, can you clarify if the above steps reproduce the problem for you? This was not clear to me from your response.

**Comment by ntamas** [comment]
@jannick0 It appears that the original CMake bug that you refer to has been fixed seven years ago:

https://gitlab.kitware.com/cmake/cmake/-/commit/1ec6485c6a16c230bf29696ab8fd48eb5edbb78a

Could it be the case that MinGW somehow overrides `CMAKE_C_ARCHIVE_CREATE` and/or `CMAKE_C_ARCHIVE_APPEND` in a toolchain file or something similar, and the overrides still use the old `ar` invocation (maybe because the overrides were created before the commit referenced above)?

**Comment by szhorvat** [comment]
@jannick0 Here are the answers to your questions about which versions of tools I used:

```

MINGW64 ~
$ which make
/usr/bin/make

MINGW64 ~
$ make --version
GNU Make 4.3
Built for x86_64-pc-msys
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

MINGW64 ~
$ which cmake
/mingw64/bin/cmake

MINGW64 ~
$ cmake --version
cmake version 3.20.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

MINGW64 ~
$ which nm
/mingw64/bin/nm

MINGW64 ~
$ nm --version
GNU nm (GNU Binutils) 2.36.1
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

Are you using the same? 

Can you reproduce the problem with igraph 0.9.2?

**Comment by szhorvat** [comment]
Following the leads in the recent discussion in the CMake issue, the problem will appear if LTO is enabled:

```
-DIGRAPH_ENABLE_LTO=ON
```

I can reproduce it with this setting.

Furthermore, it only appears when using `make` (not when using `ninja`) and only with MSYS (not with Linux).

**Comment by ntamas** [comment]
We have added a workaround in igraph as it seems like CMake will fix it in 3.21 only and we want to support earlier versions (most Linux distros are around CMake 3.16 or so).

**Comment by szhorvat** [comment]
> (most Linux distros are around CMake 3.16 or so).

I am certainly in favour of the workaround, but Linux does not appear to be affected. MSYS tends to have the latest CMake.

**Comment by ntamas** [comment]
How about cross-compiling for MinGW/MSYS on Linux? (E.g., something like [this](https://blog.svgames.pl/article/cross-compiling-c-programs-for-ms-windows-using-mingw) )

**Comment by szhorvat** [comment]
Not something I'm willing to give a try 😆

**Comment by szhorvat** [comment]
I tested it with a fully updated MSYS2 and LTO enabled. No more undefined symbols in `libigraph.a` and the test suite passes. Let's close this now. Thanks for the report @jannick0 ! 0.9.3 should be out soon, then you can update igraph in MSYS2.

**Comment by ntamas** [comment]
@jannick0 igraph 0.9.3 is out and it should fix this problem by renaming the affected files. Let me know if you are still having issues!
