### ISSUE TITLE
igraph_maximal_cliques_subset macro

### ISSUE THREAD

**Issue by iosonofabio** [igraph/igraph#1780]
**Describe the bug**
There are a few functions to compute maximal cliques, count them, restrict to a subset of vertices, get histograms, etc.

They are all `#define`-macro-ed in `src/cliques/maximal_cliques_template.h`, which makes it a little hard to debug. Perhaps that's why, while I was trying to expose `igraph_maximal_cliques_subset` to Python, I ran into a bug whereby the one more variable is freed from the stack compared to the ones present (9 vs 8), which happens at line 406 of that file:

https://github.com/igraph/igraph/blob/a636b68b8a04ba875621608efcfae977168c67a6/src/cliques/maximal_cliques_template.h#L406

Now the source of the problem seems to be in the definition of `FINALLY` and `CLEANUP` in that file:

https://github.com/igraph/igraph/blob/a636b68b8a04ba875621608efcfae977168c67a6/src/cliques/maximal_cliques_template.h#L91-L98

As you can see, the first macro has an `if(res)` that adds something on the stack is a list of cliques is requested in the output. However, the second macro cleans up `res` no matter what, leading to an inconsistent stack.

So I propose to add an `if(res)` in the cleanup macro and that's that. Shall I just make a PR?

**Comment by ntamas** [comment]
Nice catch! Yes, that would be the correct fix. Feel free to just commit to `master`. Thanks!

**Comment by iosonofabio** [comment]
yay, closing
