### ISSUE TITLE
vector_lex_cmp should take vector_t ** and not vector_t as argument

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1781]
**Describe the bug**

`igraph_vector_lex_cmp` and `igraph_vector_colex_cmp` take `void *` as arguments:

```
int igraph_vector_lex_cmp(const void *a, const void *b);
```

But of course, there is an assumed type of these pointers. Currently, it is assumed that they are `igraph_vector_t *`.

However, this makes them unusable with an `igraph_vector_ptr_t`. To be usable with `vector_ptr`s, they should be `igraph_vector_t **`. I.e., both `a` and `b` must point to a pointer to a `vector_t`, as it is these pointers to `vector_t` that will be reshuffled by `qsort`.

**To reproduce**

This should work, but it does not:

```
igraph_vector_ptr_t list;

/* init and fill up list */

igraph_qsort(VECTOR(list), igraph_vector_ptr_size(&list), sizeof(igraph_vector_t *), igraph_vector_lex_cmp);
```

**Proposed fix**

 - Make the assumed type be `igraph_vector_t **`
 - Explain this issue in the documentation
 - Write an example program so users will not be confused

**Version information**
Current `master`.

**Comment by szhorvat** [comment]
See also ecab5377f1e04c0ee24b594108d37d88cf1fd23c

@GroteGnoom @ntamas I went ahead and changed this on `master` with the reasoning that the original intention was to sort the results of functions, which are almost always returned in a `vector_ptr_t`. Therefore, the current behaviour could be considered a bug, and this change may be viewed as a bugfix rather than API breaking.

Let me know if you disagree and we can make these changes `develop`-only.

The comparison functions were not currently used, except in the tests.

**Comment by ntamas** [comment]
You are right, and indeed it is a bugfix, not an API breakage. Can you add an item about it in the changelog as well (if you haven't done so already)?
