### ISSUE TITLE
Inconsistency of Community Detection Algorithm handling DiGraphs vs Graphs

### ISSUE THREAD

**Issue by BrandonKMLee** [igraph/igraph#1795]
**Describe the bug**
https://github.com/GiulioRossetti/cdlib/issues/167#issuecomment-845596774

Most algorithms only allow for undirected graphs to work, however, Eigenvector simply throws an error ("This method was developed for undirected graphs") and proceeds to run anyways.
https://github.com/igraph/igraph/blob/cf684b5ce44ac41732a7f61884b390e24172047a/src/community/leading_eigenvector.c#L530

If this is available for Eigenvector, why could it not be available for others?

**Version information**
python-igraph 0.9.1 and cdlib 0.2.0

**Comment by szhorvat** [comment]
I am going to rephrase this a bit and say:

All community detection methods should make it very clear:

 - Do they take edge directions into account?
 - If not, they should issue a clear warning when run on a directed graph.'
 - Do they consider edge multiplicities in multigraphs, and if yes, how?
 - Note: Algorithms that take edge multiplicities into account cannot safely ignore edge directions, as reciprocal edges would be interpreted as multi-edges, and this would be confusing. It is better to refuse to run on directed graphs in this case.
 - Do they take self-loops into account?
 - Do they use weights, and if yes, how? (Do large weight values indicate strong or weak coupling?)

All this should be clearly and concisely communicated by the documentation and error messages.

----

Looking at the code, it appears that `igraph_community_leading_eigenvector` simply ignores edge directions. The warning `This method was developed for undirected graphs` does not communicate this very well, and IMO should be changed. We need to investigate how edge multiplicities are handled, and if they affect the result, disable running on directed graphs.

**Comment by szhorvat** [comment]
@BrandonKMLee If you'd like to help with this project, the following would be very useful:

Write a complete list of currently available community detection, and for each one note down: 1. How does it currently behave with directed graphs? 2. How does it behave with multigraphs? 3. Anything that is relevant in relation to the list I wrote in the previous message.

This is easy to do, and does not require programming knowledge, but it is time consuming.

**Comment by ntamas** [comment]
To put things into context: the leading eigenvector method was originally conceived for undirected graphs, and the [original manuscript](https://arxiv.org/pdf/physics/0605087.pdf) was not really concerned with directed graphs, but it never excluded the possibility that the algorithm could be useful for directed graphs. In fact, [another paper](https://arxiv.org/abs/0709.4500) extended the leading eigenvector method a few years later to directed graphs, although I haven't checked what the gist of the extension was and whether it would be easy to implement it in igraph. But that's why the leading eigenvector method simply prints a warning and then proceeds anyway.

**Comment by szhorvat** [comment]
My original suspicion was that it just goes ahead with the directed adjacency matrix. But that is not what it does. It uses `IGRAPH_ALL` when constructing the adjlist, and it uses `rssolve` (not `rnsolve`, which would be necessary for non-symmetric matrices). The modularity calculations are also fully undirected. I didn't test it, only looked briefly at the code, but it appears to me that it fully ignores edge directions.

For methods which are generalizable to the directed case, but do not yet support it, we should open issues. (At least when the method is fully implemented in igraph, such as this one. I wouldn't bother with those methods which use borrowed code.)

**Comment by ntamas** [comment]
> Write a complete list of igraph's currently available community detection methods, and for each one note down: 1. How does it currently behave with directed graphs? 2. How does it behave with multigraphs? 3. Anything that is relevant in relation to the list I wrote in the previous message.

Would it be useful to crowdsource this in a wiki page until we have information about all the methods, and then move it into the documentation later?

**Comment by BrandonKMLee** [comment]
@ntamas most definitely. Some of these have to be addressed, including non-directional algorithms with directional extensions, and weighting variations.
