### ISSUE TITLE
unfold_tree Does Not Clone Successors of a Cloned Vertex

### ISSUE THREAD

**Issue by fwitter** [igraph/igraph#1800]
## Bug Description
I am working with `python-igraph`. Given a DAG, `Graph.unfold_tree` (or `igraph_unfold_tree` in C respectively) does not copy the substructure succeeding a vertex that has been cloned due to unfolding.

## How to Reproduce
Minimal example:
```python
dag = Graph(edges=[(0, 1), (0, 2), (1, 3), (2, 3), (3, 4), (3, 5)], directed=True)
dag.vs['label'] = range(dag.vcount())
tree, v_map = dag.unfold_tree([0])
tree.vs['label'] = dag.vs[v_map]['label']
```
Original DAG:
![tree_test_dag](https://user-images.githubusercontent.com/10985458/123256962-d757e280-d4f1-11eb-83dc-f5a7bd46ccae.png)
Observed result of `unfold_tree`:
![tree_test_wrong](https://user-images.githubusercontent.com/10985458/123256971-da52d300-d4f1-11eb-8c00-780209fe3380.png)
Expected result:
![tree_test_correct](https://user-images.githubusercontent.com/10985458/123256940-d2932e80-d4f1-11eb-91e0-296904766fa1.png)

## Version Information
```
python-igraph 0.9.6 (PyPI)
python 3.8.8
Ubuntu 20.04.2 LTS
```

**Comment by fwitter** [comment]
I am not sure whether the described behavior of `unfold_tree` is intended and correct in certain use cases. However, for my use case, I require the substructures to be cloned. And since I needed a quick fix for my problem, I implemented my own algorithm for graph unfolding in Python which is not based on BFS / DFS.
The idea is to repeatedly iterate over the graph and clone vertices that have more than one parent vertex, i.e. that violate the tree definition, until the graph is a tree. The algorithm has the following properties:
- It is restricted to DAGs, although loop handling can be added
- It does not require root nodes to be defined
- It can unfold multiple disconnected components which has already been under discussion in #1146 for `unfold_tree`
- It preserves vertex and edge attributes
- It is slower than the search-based implementation in C which might be partially Python's fault

Given the properties of my implementation, I am wondering if both algorithms should exist in parallel since each of them seems to cover slightly different problems. Below is the Python code of my algorithm. Feel free to reuse it, e.g. translating it into C.

```python
from collections import ChainMap

def unfold_tree(g: Graph, mode: str = 'out', inplace: bool = False) -> Graph:
    assert g.is_dag()
    assert mode in ['in', 'out']
    if not inplace:
        g = g.copy()
    inv_mode = 'in' if mode == 'out' else 'out'
    non_tree_roots = list(sorted(g.vs.select(lambda v: v.degree(mode=inv_mode) > 1)))
    while non_tree_roots:  # repeat until g is a tree
        rem_edges = []
        add_edges = []
        add_edges_attr = []
        for ntr in non_tree_roots:
            preds = list(g.es.select(sorted(g.incident(ntr, mode=inv_mode))))
            succs = list(g.es.select(sorted(g.incident(ntr, mode=mode))))
            ntr_attr = ntr.attributes()
            num_clones = len(preds) - 1
            # ntr_clones = g.add_vertices(num_clones, {k: [v] * num_clones for k, v in ntr_attr.items()})
            ntr_clones = [g.add_vertex(**ntr_attr) for _ in range(num_clones)]
            for i in range(num_clones):
                ntr_clone = ntr_clones[i]
                pred_e = preds[i + 1]
                if mode == 'out':
                    # Create new edges from clone to all successors of ntr
                    add_e = [(ntr_clone, e.target) for e in succs]
                    # Create new edge from predecessor of ntr to clone
                    add_e.append((pred_e.source, ntr_clone))
                else:
                    # Same for inverse direction
                    add_e = [(e.source, ntr_clone) for e in succs]
                    add_e.append((ntr_clone, pred_e.target))
                # Collect edge attributes
                add_e_attr = list(map(lambda e: e.attributes(), succs))
                add_e_attr.append(pred_e.attributes())
                add_edges += add_e
                add_edges_attr += add_e_attr
            rem_edges += preds[1:]
        g.delete_edges(rem_edges)
        g.add_edges(add_edges, ChainMap(*add_edges_attr))
        non_tree_roots = list(sorted(g.vs.select(lambda v: v.degree(mode=inv_mode) > 1)))
    return g
```

**Comment by szhorvat** [comment]
This behaviour is as intended: the output is a tree representing the BFS.

What you are asking for might be a reasonable new feature, but it is a distinct operation from what `unforld_tree` does.

**Comment by fwitter** [comment]
Thank you. I see, BFS uses each edge only once. What I require is more like a DFS which visits all reachable vertices that are not on the current path regardless of if they have already been visited from another path.

**Comment by szhorvat** [comment]
Neither BFS, nor DFS do that, but of course it can be done. Feature requests are welcome, but it would be good to explain what applications the feature is useful, and to include references. These help prioritize the request.

**Comment by fwitter** [comment]
Yes, DFS needs to be adapted to consider only vertices on the current path as visited.
