### ISSUE TITLE
gomory_hu_tree() appears to compute only equivalent flow tree instead of cut tree

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1810]
**Describe the bug**

A Gomory-Hu tree of a graph G has the same vertices as G and has the following properties:

 1. The smallest weight in the unique path between `s` and `t` in the tree gives the value of the s-t cut in G (_equivalent flow tree property_)
 2. Removing the corresponding edge from the tree partitions its vertices into two components the same way as a minimum cut would for G

It seems that the result of `igraph_gomory_hu_tree` satisfies property 1 but not property 2.

See https://igraph.discourse.group/t/issue-with-gomory-hu-tree/841/

**To reproduce**

Run the function on the 4-vertex complete graph. Example in Mathematica:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1212871/132132162-6248c15b-9b65-4ea3-b877-1a26bff59250.png">

This tree suggests that the cut between 2 and 3 will result in the partitions (1,2) and (3,4). However, such a partitioning requires cutting 4 edges in the graph, not 3, thus it is not a minimum cut. 

The expected result is a star graph.

**Version information**
Current latest `master` (or close enough).

**Comment by szhorvat** [comment]
The igraph documentation cites Gusfield 1990. This paper contains multiple algorithms. "Algorithm EQ" (section 2) computes only an equivalent flow tree, which may not also be a cut tree. Section 3.4 discusses the full algorithm to obtain a cut tree, and contains section "Relation with Algorithm EQ" which discusses how to modify "Algorithm EQ" to get a cut tree.

We need to carefully verify which is implemented in igraph.

**Comment by szhorvat** [comment]
For reference, here is Algorithm EQ:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1212871/132132814-02bf65e6-f0f0-4c83-85b5-600466d83cdc.png">

And here is how to modify it to get a GH cut tree:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1212871/132132893-00ea2a20-a011-4fd0-adf4-1896139a9f2a.png">

I checked that what is currently implemented in igraph is in fact the unmodified Algorithm EQ. Notice in particular this line:

https://github.com/igraph/igraph/blob/master/src/flow/flow.c#L2497

`if (mid > source && ...`, i.e. is considers those vertices `i` from the `s`-side partition which are `i > s`. This is the original step 4. The modified step 4 must consider all vertices on the `s`-side partition other than `s`.

Luckily, this should be an easy fix, but I won't have time for it this week. If anyone wants to take it, please go ahead.

**Comment by ntamas** [comment]
@szhorvat I started fixing this on `master`, but I have a question regarding property 2):

> Removing the corresponding edge from the tree partitions its vertices into two components the same way as a minimum cut would for G

We have a `validate_tree()` function in the unit test that explicitly validates property 1 but not property 2. When validating property 2, do I only need to test it for every _edge_ in the Gomory-Hu tree or for every _vertex pair_ (even if they are some distance apart in the tree)?

**Comment by szhorvat** [comment]
Both properties refer to vertex pairs, not to edges. So if not too time consuming, it's nice to test for all pairs, or at least for some non-adjacent pairs.

So, 

 - take a pair s,t
 - find the unique path between them in the tree
 - find the smallest weight on this path and its corresponding edge (not necessarily unique)
 - that weight must be the same as the cut value
 - removing that edge partitions the tree into two vertex sets—these must be the same as the partitions returned by the maxflow function

Now what happens if the graph is not connected, especially if it has three components? I see the function returns a connected tree, but some weights are zeros. I'm not sure if something can go wrong. E.g. there are 3 components, C1, C2, C3. s is in C1, t is in C3. Now the two partitions can either be (C1,C2) and C3 or C1 and (C2,C3). Is it possible that the maxflow function returns one, but the tree cut induces a different one? I presume no, but I didn't think about this much, and I'm not very familiar with flow problems in general. This is just a warning to you to pay attention to edge cases!

**Comment by ntamas** [comment]
> Now what happens if the graph is not connected, especially if it has three components? I see the function returns a connected tree, but some weights are zeros.

I was wondering whether this is desired or not (and it is not covered by the unit tests at the moment). The reason why it works this way is because internally, the algorithm uses two vectors for generating the tree: a "neighbors" vector (where the i-th element is one neighbor of vertex i in the tree, and for i=0 it is equal to zero and is ignored later during the tree construction process), and a "weight" vector (where the i-th element is the weight of the edge between i and `neighbors[i]`; again, first element is ignored). If the original graph was disconnected, some elements simply remain zero in the "weight" vector. Strictly speaking, this is not incorrect; the maximum flow between two vertices that are not in the same connected component is zero. On the other hand, removing all zero-weight edges would avoid the corner case that you mentioned; the Gomory-Hu tree would be partitioned in the same way the original graph is partitioned.

**Comment by ntamas** [comment]
I decided to keep things the way they are, at least for the next release (0.9.5). We can break things in 0.10.0 if we want to :)
