### ISSUE TITLE
Identify widest paths

### ISSUE THREAD

**Issue by mcmahanp** [igraph/igraph#1817]
*What is the feature or improvement you would like to see?*

It would be great to implement a [widest paths](https://en.wikipedia.org/wiki/Widest_path_problem) algorithm in igraph. The 'width' of a path in a weighted graph is the minimum weight of the edges in that path, and the widest path between two points is the path with the greatest width between them. 

*Use cases for the feature*

The widest path has applications in various flow-type networks (e.g. traffic, networking, metabolic networks, …), and in the [Schulze method](https://en.wikipedia.org/wiki/Schulze_method) of identifying a winner in ranked-choice voting. It's [currently  possible brute force this](https://stackoverflow.com/questions/57522871/how-to-calculate-a-maximum-bottleneck-path-with-igraph) in igraph by enumerating all simple paths and calculating the minimax over the edge weights, but this is very inefficient (especially for networks with any sort of density).

*References*

Based on a cursory read, it looks like the best algorithm for this depend on whether the graph is directed or undirected and on the overall density of the network. However there are general purpose algorithms as well.

The [Wikipedia page on widest paths](https://en.wikipedia.org/wiki/Widest_path_problem) cites a number of algorithms, and the page on the [Schulze method](https://en.wikipedia.org/wiki/Schulze_method#Implementation) lists a simple algorithm.

**Comment by iosonofabio** [comment]
If this isn't too hard my new intern could take this

**Comment by mcmahanp** [comment]
> Can you please elaborate a bit more on _actual_ use cases, so we can make a better judgement about what the most common needs are, and what to implement?

Great point. In my case, I'm only interested in the Schulze method specifically. For this specific use case the networks will tend to be small, dense, and directed.

But I know that the single-source, single-target solution is also useful for other applications. E.g. When trying to find the highest-bandwidth path through a computer network you would want to specify the source and target in an *undirected* network. Also, for ecological and metabolic networks (like the one asked about in [this stackoverflow question](https://stackoverflow.com/questions/57522871/how-to-calculate-a-maximum-bottleneck-path-with-igraph) it is common to need the widest path from a single source to a single target in a *directed* network. So an ideal igraph function would choose its algorith based on the type of network.

Incidentally, the modified Floyd-Warshall algorithm laid out in the [Shulze method wikipedia page](https://en.wikipedia.org/wiki/Schulze_method#Implementation) is very simple to implement for the all-pairs version -- though I suspect there are more efficient algorithms as well.

**Comment by Gomango999** [comment]
Hello! If people are okay with it, could I take this as my next contribution?

**Comment by szhorvat** [comment]
@Gomango999  Sure, go ahead. As usual, it's best to work in a public draft PR, and to write a very brief summary of your plan (including the proposed function signature).

I won't have time to review this but I'm sure someone else will.

**Comment by vtraag** [comment]
Closed by PR #1893.
