### ISSUE TITLE
Wishlist: Generalized Petersen graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1819]
_This is a good starting point for new igraph contributors._

**What is the feature or improvement you would like to see?**

A graph generator for the generalized Petersen graph.

The construction for `G(n,k)` is as follows:

 - Create a cycle graph on `n` vertices. Name these vertices as `u_0, ..., u_(n-1)`.
 - Create `n` more vertices, `v_0, ..., v_(n-1)` and connect each `u_i` to its corresponding `v_i`.
 - Connect each `v_i` to `v_(i + k mod n)`.

The standard Petersen graph is then `G(5,2)`.

**Use cases for the feature**

This is a well-known graph construction in graph theory.

**References**

 - https://en.wikipedia.org/wiki/Generalized_Petersen_graph

**Comment by alexsyou** [comment]
Hello! I was wondering if this feature is already implemented, and if not could I work on this feature? It would be my first issue but I think I could complete it after looking at the code.

**Comment by szhorvat** [comment]
@fazal452 Are you still working on this / are you planning to complete it?

**Comment by szhorvat** [comment]
@alexsyou Since now it's the weekend, let us wait until Tuesday and see if @fazal452 responds. If not, you can go ahead.

**Comment by fazal452** [comment]
Hey sorry for the late reply. Unfortunately I was not able to complete this project due to my preparation for finals. In the time I allocated I wasn’t able to understand the program well enough.

@alexsyou Feel free to takeover and Good Luck!!
