### ISSUE TITLE
Build with clang-13 fails

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1821]
**Describe the bug**
Clang 13 was released about a month ago, but it triggers some errors, because some warnings are treated as errors.

```

src/igraph/src/community/spinglass/pottsmodel_2.cpp:123:12: error: variable 'av_k_squared' set but not used [-Werror,-Wunused-but-set-variable]
    double av_k_squared = 0.0;
           ^
src/igraph/src/community/spinglass/pottsmodel_2.cpp:124:12: error: variable 'av_k' set but not used [-Werror,-Wunused-but-set-variable]
    double av_k_squared = 0.0;
           ^

src/igraph/src/misc/matching.c:555:19: error: variable 'dual' set but not used [-Werror,-Wunused-but-set-variable]
    igraph_real_t dual;               /* solution of the dual problem */
                  ^

src/igraph/src/misc/motifs.c:201:14: error: variable 'motifs' set but not used [-Werror,-Wunused-but-set-variable]
    long int motifs = 0;
             ^
src/igraph/src/internal/qsort.c:128:9: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
loop:   SWAPINIT(a, es);
        ^~~~~~~~~~~~~~~
src/igraph/src/internal/qsort.c:77:47: note: expanded from macro 'SWAPINIT'
#define SWAPINIT(a, es) swaptype = ((char *)a - (char *)0) % sizeof(long) || \
                                              ^ ~~~~~~~~~
```  

**To reproduce**
After installing `clang-13` and making sure it is on the PATH somewhere:
```
cmake .. -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang-13
cmake --build . --target igraph
```

**Version information**
Latest `master` branch.

**Comment by szhorvat** [comment]
> Be careful, because some of the "unnecessary" code may actually be used by disabled debug features (either used by commented out debug stuff, or debug stuff that was disabled with macros). I haven't checked if this is the case with anything that was removed in your PR, just warning you that it _could_ be the case.

I am seeing exactly this happen. I get this error:

```
src/games/degree_sequence_vl/gengraph_graph_molloy_optimized.cpp:1800:13: error: variable 'sum' set but not used [-Werror,-Wunused-but-set-variable]
```

The code that triggers it looks like this:

```
        int sum = 0;
        for (i = 0; i < n; i++) {
            sum += deg[i];
        }
        assert(sum == a);
```

The only place where `sum` is used is in an `assert()`, i.e. a debug feature. What we want here is precisely that the computation of `sum` should be omitted by the compiled when the `assert` is disabled. Therefore, `IGRAPH_UNUSED` is not appropriate here.

What do you suggest we do here @vtraag @ntamas ? I'm not so sure that leaving this warning on is a good idea. These warnings are getting into linter territory: sure, it's useful. But it's a warning, and not an error, for a reason: often, there's nothing wrong with the code.

If you still want to keep the warning on, I'll fence that piece of code with an `#ifndef NDEBUG`.

**Comment by szhorvat** [comment]
Here's the fix I made, so that we can make progress: 1c789400e75fb49317e2bb00468ee25074661172

**Comment by vtraag** [comment]
Thanks @szhorvat , this was exactly the error that was reported in https://github.com/vtraag/leidenalg/issues/88 as said earlier. Just out of curiousity, how did you trigger the error? I didn't encounter it. At any rate, good to see it's resolved.

**Comment by szhorvat** [comment]
@vtraag It triggers only if `NDEBUG` is defined, and thus all the `assert`s are effectively absent. This is the default for `Release` mode, I think.
