### ISSUE TITLE
Does the qsort code need a revamp?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1824]
Clang started issuing warnings about our qsort implementation (specifically the SWAPINIT macro) since Clang 13. This was solved by disabling the warning with an ugly Clang-specific pragma. See #1822. This in turn caused other annoyances, see [here](https://github.com/igraph/igraph/pull/1822#issuecomment-955665148).

However, I wondered if there was a merit to this warning, so I looked how others solved this issue. This qsort code comes from BSD and a variant of it survives in FreeBSD. Here's the history of the file:

https://svnweb.freebsd.org/base/head/lib/libc/stdlib/qsort.c

Notice that they removed SWAPINIT entirely, with this note:

> libc qsort(3): stop aliasing.
>
> Qsort swap code aliases the sorted array elements to ints and longs in
order to do swap by machine words.  Unfortunately this breaks with the
full code optimization, e.g. LTO.
>
> See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83201 which seems to
reference code directly copied from libc/stdlib/qsort.c.

I am wondering if we shouldn't update our code to match with FreeBSD's, and avoid the problems mentioned there. It sounds like this code is dangerous, and won't work as intended when using certain optimization options in GCC. It's not clear to me if the fix they used in FreeBSD will reduce performance. But if it was good enough for FreeBSD, it should work for us too?

I don't have the time to look into this anymore today or next week, so I opened this issue. Could you please look into it and make a decision about what to do, before 0.9.5 comes out, @ntamas and @vtraag ?

**Comment by vtraag** [comment]
I've tried to look into this, and I believe it is not too difficult to update `qsort`. See PR #1825 for specifics.

**Comment by ntamas** [comment]
Let's continue in #1825 so we don't have to look at two threads at the same time :)
