### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [igraph/igraph#1826]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [reorder_duplicate](https://github.com/igraph/igraph/blob/d2ece480ba024312a3a30b799ee633e2ebdd5460/src/cliques/cliquer/reorder.c#L93)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [igraph_i_graphml_add_attribute_key](https://github.com/igraph/igraph/blob/298c0ac9777869090de2b3bca94a4d17cd5564fa/src/io/graphml.c#L674)

**Comment by szhorvat** [comment]
It's not quite clear what you mean. Can you elaborate please?  

Cliquer in particular (whose source you reference on the first line) does not support error handling very well.

**Comment by szhorvat** [comment]
I guess you mean catching the case when `malloc` or `strdup` return null, and trying to handle it gracefully. This is generally a good thing to do, but it's not always possible or easy.  

igraph has an error handling mechanism that relies on returning error codes. All "normal" igraph functions will return error codes, so error handling is possible, including freeing resources. However, the first example you link to is in Cliquer, i.e. not original igraph code. Cliquer does not have a similar mechanism. Without significant modification, I don't know what reasonable thing we could do here when `malloc` returns 0.

`igraph_i_graphml_add_attribute_key` also does not return an error code for some reason. I am not so familiar with the GraphML reader, so I cannot immediately tell why this is. However, fixing this _properly_ would take more effort than it's worth. Creating a fix also has risks. Thus I would suggest not spending time on it.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
:thought_balloon: Would you like to detect every error situation as early as possible?

**Comment by szhorvat** [comment]
@elfring If you find problems of this type in functions that return an `igraph_error_t` on the latest `develop` branch, let us know.  Searching for this kind of problem in other functions is not very useful for us at the moment.

**Comment by elfring** [comment]
:thought_balloon: There are the usual possibilities to consider for more complete error reporting.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:

**Comment by iosonofabio** [comment]
@elfring thanks. Broad ideas like static code analysis and profiling are useful, but exactly how useful depends on what you find 😉

So if you have time sure, why not.
