### ISSUE TITLE
igraph_random_sample_real() needs docs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1829]
`igraph_random_sample_real()` was added by @GroteGnoom as a public function on the `develop` branch, but I don't know the reason for it. Can you please confirm that we need it as a public function, and if yes, can add documentation?

**Comment by GroteGnoom** [comment]
It was added to support large graphs in igraph_erdos_renyi_game for 32-bit systems. It doesn't necessarily need to be public. I'll put it in a non-public header.

**Comment by szhorvat** [comment]
> It was added to support large graphs in igraph_erdos_renyi_game for 32-bit systems. It doesn't necessarily need to be public. I'll put it in a non-public header.

Whatever you think is best—I wasn't following these changes. I found it when making the list for #1828.

**Comment by szhorvat** [comment]
(If you decide to make it an internal function, please do add a comment about the purpose.)

**Comment by GroteGnoom** [comment]
Fixed in #1833
