### ISSUE TITLE
docs for igraph_attribute_combination_t * parameters should indicate NULL option

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1834]
**Describe the bug**
igraph_to_undirected takes a `const igraph_attribute_combination_t *edge_comb` as its third parameter. Figuring out how edge combinators work is a lot of work. From the igraph_to_undirected simple example it seems like NULL is also an option, but it's not clear what it does from the edge combinator documentation. We should make it easy for users to use default options for edge combinators and indicate that NULL can be passed in, and what the result is.

**Comment by ntamas** [comment]
The current behaviour is now documented, although note that it is a bit inconsistent: edge attributes are lost if the mode is not `IGRAPH_TO_UNDIRECTED_EACH` but they are copied over if the mode is `IGRAPH_TO_UNDIRECTED_EACH`. I think we should be consistent here and either delete the attributes also when the mode is `IGRAPH_TO_UNDIRECTED_EACH`, or provide a sensible default that keeps the attributes of exactly one edge when multiple edges are merged into a single one during conversion.

This is a candidate for inclusion in our list of [planned API changes for 0.10](https://github.com/igraph/igraph/wiki/Planned-API-changes-for-0.10) -- what do you think?

**Comment by GroteGnoom** [comment]
I should've searched immediately, but igraph_simplify() and igraph_contract_vertices() also need their docs fixed. For contract_vertices it's a vertex combinator.

> This is a candidate for inclusion in our list of planned API changes for 0.10 -- what do you think?

Yes, that would be nice to fix 🙂

**Comment by ntamas** [comment]
Thanks for the heads up, documentation updated again.
