### ISSUE TITLE
igraph_attribute_combination() needs docs

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1835]
igraph_attribute_combination() seems like the easiest way to create an attribute combination, but it isn't documented.

**Comment by ntamas** [comment]
It would be great to squeeze this in to 0.9.5 so I'm willing to wait a few hours until you manage to send a PR :) I still want to tidy up a few bits in `functions.yaml` anyway.

**Comment by GroteGnoom** [comment]
Btw: `stale bot commented 17 days ago`: `It will be closed in 14 days if no further activity occurs.`. But it's not closed yet. Weird.

**Comment by szhorvat** [comment]
@ntamas Can you look into why stalebot is not doing its thing? I think you set it up originally.

**Comment by ntamas** [comment]
I don't know how the bot works, but it has recently closed other issues so I'm pretty sure it's working.
