### ISSUE TITLE
Create graph based on `igraph_sparsemat_t`

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1838]
**What is the feature or improvement you would like to see?**
Construct a graph based on a `sparsemat_t`. This could simply mimic existing functions `igraph_adjacency` and `igraph_weighted_adjacency`, but then `igraph_sparse_adjacency` and `igraph_sparse_weighted_adjacency`.

**Use cases for the feature**
Create graphs based on sparse matrix results from other `igraph` functions.

**Comment by szhorvat** [comment]
I'm a bit shocked that this does not already exist ...

**Comment by GroteGnoom** [comment]
There are currently functions with this functionality:
igraph_sparsemat
https://github.com/igraph/igraph/blob/e06b3b0a37f76b10715ee93b072acda4398296d9/src/core/sparsemat.c#L1230
and  igraph_weighted_sparsemat
https://github.com/igraph/igraph/blob/e06b3b0a37f76b10715ee93b072acda4398296d9/src/core/sparsemat.c#L1295
They don't behave exactly the same as igraph_adjacency, for example, they don't take an igraph_adjacency_t, so you can choose between IGRAPH_ADJ_MAX and IGRAPH_ADJ_UPPER, etc. They just make an edge for a non-zero value.

**Comment by ntamas** [comment]
We should probably deprecate these and add `igraph_sparse_adjacency()` and `igraph_sparse_weighted_adjacency()` for sake of consistency. I'll give it a go later this week unless someone wants to take over.

**Comment by szhorvat** [comment]
I'm a bit puzzled by igraph_adjacency_t. I don't see many practical uses for it, especially min and max which are completely arbitrary.

If someone wants an undirected graph, they should just pass in a symmetric matrix. IMO the solution that supports users best, especially inexperienced ones, is to throw an error when the matrix is not symmetric, and let them figure out why that is the case and fix it appropriately.

**Comment by ntamas** [comment]
I think `igraph_adjacency_t` exists mainly for the C use-case where it is easier to let igraph take care of the reshaping of the matrix if needed. Implementing this in higher-level interfaces is mostly a one-liner in most languages; however, note that if we remove it from here, chances are that it would have to be re-implemented for each higher level interface individually, so considering that we already have an implementation in C, I'd rather not break it and generate extra work for us both there (with the removal) and in the higher level interfaces (by adding the functionality that restores it).

**Comment by ntamas** [comment]
#2072 is now merged so closing this.
