### ISSUE TITLE
Attempting to compile and build igraph on windows using WSL causes an issue 

### ISSUE THREAD

**Issue by alexsyou** [igraph/igraph#1839]
**Describe the bug**
After downloading and installing igraph using the instructions given in https://igraph.org/c/html/0.9.5/igraph-Installation.html, attempting to build igraph using 
`$ cmake --build .`
produces the following error:
`win_flex.exe: could not create /mnt/c/Alex/Projects/igraph/igraph/build/src/io/parsers/pajek-lexer.c
make[2]: *** [src/CMakeFiles/igraph.dir/build.make:125: src/io/parsers/pajek-lexer.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:1850: src/CMakeFiles/igraph.dir/all] Error 2
make: *** [Makefile:163: all] Error 2`

**To reproduce**
Follow steps given in https://igraph.org/c/html/0.9.5/igraph-Installation.html. Download `winflexbison3` using Chocolatey. Change CMakeCache.txt `BISON_EXECUTABLE:FILEPATH=/mnt/c/.../win_bison.exe` and `FLEX_EXECUTABLE:FILEPATH=/mnt/c/.../win_flex.exe`. Attempt to build using `$ cmake --build .` after `cmake ..` describes a successful configuration. 

**Version information**
Develop branch of igraph, obtained by forking the github repo and cloning as described in https://github.com/igraph/igraph/blob/master/CONTRIBUTING.md.

**Comment by szhorvat** [comment]
You are saying that you are using WSL. That is effectively Linux. `win_flex.exe` is a Windows executable and does not run on Linux. 

Install Flex/Bison into your Linux system (WSL) and do not specify their locations manually. CMake can detect them.

**Comment by szhorvat** [comment]
Regarding using the `develop` branch, be aware that it is in flux, and not suitable for production use. Things _will_ change without notice, including the API and the behaviour. Normally one would only use `develop` only when contributing to igraph. Otherwise, use `master` or a released version.
