### ISSUE TITLE
Create tree or forest from list of parents

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1840]
_Implementing this is a good way to get started with contributing to igraph._

**What is the feature or improvement you would like to see?**

A function that takes a "parent vector" (as returned by `igraph_bfs/dfs`) and creates an undirected or directed tree or forest from it.

The input will be a vector `p`, where `p[i]` is the index of the parent of vertex `i` in the tree. If `p[i] < 0` then `i` has no parent. It is to be decided what to do when `p[i] == i`.  The output will be the corresponding tree or forest.

**Use cases for the feature**

 - Create a tree from the output of graph traversal functions such as `igraph_bfs/dfs`
 - This is a general and intuitive way to create any tree/forest.

**Comment by pradkrish** [comment]
Hello, I am new to igraph and I would love to try working on this. Is this still open?

**Comment by GroteGnoom** [comment]
Yes! I've assigned you to it.

If you have any questions, please don't hesitate to ask, including about quickly building and testing your code. An initial build should be simple (https://igraph.org/c/html/0.9.5/igraph-Installation.html), and subsequent builds should be quick (https://github.com/igraph/igraph/issues/1851#issuecomment-974618427)

You can use #1856 and its corresponding issue #1851 as an example of a successful recent PR.

It's usually nice if you start a minimal draft quickly, so we can more easily check your work, and guide you in the right direction.

**Comment by pradkrish** [comment]
Some initial thoughts. Currently `igraph_tree(igraph_integer_t n, igraph_integer_t children, igraph_tree_mode_t type)` takes in number of nodes and edges as arguments. Could it be that I may have to introduce another signature like this `igraph_tree(igraph_vector_int_t*, igraph_tree_mode_t)` to create a tree from parents vector coming from `igraph_bfs` or `dfs`?

**Comment by szhorvat** [comment]
igraph is a C library, not C++. In C, it is not possible to overload functions. This will need to be a separate function, with a different name.

**Comment by GroteGnoom** [comment]
I'm not sure I understand your question completely. igraph is written in C, so you can't overload functions, so we'll have to think of a new name. Maybe something like `igraph_tree_from_parent_vector` or something. I think the signature makes sense (with the result `igraph *graph` of course, but maybe someone thinks of more parameters for optional tweaking of the function.

**Comment by pradkrish** [comment]
From the description of the issue above

 `If p[i] < 0 then i has no parent...`

If a node does not have a parent, will it not result in a graph that is not connected?  In that case, strictly speaking, can it be called a tree if there are isolated vertices?

**Comment by szhorvat** [comment]
Then it is a forest.

**Comment by pradkrish** [comment]
In that case, calling it `igraph_tree_from_parent_vector` may not be appropriate. How about `igraph_from_parent_vector`?

**Comment by szhorvat** [comment]
The vision is to be able to convert the output of graph traversal functions such as BFS/DFS to trees/forests. The concern is not that the graph is a forest, but that this representation may introduce cycles. Consider the input `2, 0, 1`. However, BFS/DFS cannot create cycles—the result is always a tree/forest. Thus, IMO this function should verify that there would be no cycles, and show an error otherwise.

As for the name, we can think about it more when everything else is working. However, I do not think that naming it "tree" is a problem. There are other igraph functions with "tree" in the name that can also generate forests (spanning tree functions). The major property we are looking for is to not have cycles.

**Comment by szhorvat** [comment]
Can you come up with a linear-time algorithm to verify that the graph would be cycle-free, using the parent vector? Let us know if you need help with this.

**Comment by pradkrish** [comment]
Thanks for the explanation. It's more clear now.

**Comment by szhorvat** [comment]
Unfortunately I have not fully appreciated the situation with cycles when I wrote the original feature request. It's good that you brought up these concerns, as now the picture has become clearer.

> It is to be decided what to do when `p[i] == i`.

Now it's also clear what to do here: this is simply representing a 1-cycle which should be forbidden.

**Comment by pradkrish** [comment]
> Can you come up with a linear-time algorithm to verify that the graph would be cycle-free, using the parent vector?

I don't have much experience with graph theory except from data structures and algorithms course centuries ago :) I wouldn't mind some help with this.

**Comment by szhorvat** [comment]
Start at some vertex, and walk "up" the graph, moving from each vertex to its parent. If there are no cycles, eventually you will end up at a root, and you can stop. If, instead, you encounter a vertex that you have already walked through one, then you found a cycle.

Thus, we start at a vertex. We do this walk, following the parents, and mark each vertex we encounter on the way. You can use a vector to mark visited vertices. If you encounter an already visited vertex, then you found a cycle.  If you reach a root, then we know that none of the vertices we've visited are part of any cycle. Thus, we can now mark them as "already processed".

We want to do this for all vertices, one by one, but we want to keep the algorithm efficient and linear time. Thus, we will use a `visited` vector, with the same number of elements as the vertices. We will also use a `counter`, starting at `1` and incremented after processing each vertex. We interpret `visited` like so:

 - If `visited[i] == 0` then vertex `i` has never been seen before
 - If `visited[i] == counter` then vertex `i` has been seen during currently proceeding walk.
 - Since `counter` is incremented after completing a walk from each vertex, `0 < visited[i] < counter` means that vertex `i` was visited in some past walk, and therefore is not part of any cycle.

Thus, during each walk, you need to check whether:
 - You encounter a root. Then you're done with the walk.
 - You encounter a vertex which is not part of any cycle (i.e. `0 < visited[i] < counter`). Then you're done with the walk.
 - You encounter a vertex which has already been seen during the current walk, i.e. `visited[i] == counter`. Then you found a cycle, and you can throw an error, terminating the function.

**Comment by szhorvat** [comment]
@pradkrish Let us know if you have any questions. It would be great to see this project completed.

**Comment by pradkrish** [comment]
> @pradkrish Let us know if you have any questions. It would be great to see this project completed.

@szhorvat Apologies, I will try to allocate some time this week, thanks.

**Comment by szhorvat** [comment]
👍 No rush, just checking whether you're still working on it. There is no deadline on this issue.

**Comment by szhorvat** [comment]
This is just a reminder for myself that we should mark this function "experimental" when done (by adding `\experimental` to the docs). This is because we will need to review the API of functions that returns data in the "parent list" format and would need to ensure that everything interoperates smoothly. Marking the function as "experimental" signals that its API may change in the future without a major version bump.

**Comment by pradkrish** [comment]
@szhorvat I just started going through your suggested algorithm, thanks for that. A quick question, `counter` is incremented after processing each vertex but how/when to increment `visited[i]`? Apologies if it's there but I didn't pick up on it. Thanks.

**Comment by szhorvat** [comment]
Let's make sure you understand the basic idea for detecting cycles. It's not a good idea to translate a description to code without a full understanding. 

The idea is that you start at an arbitrary vertex, and start walking towards the (presumed) root of the tree by moving from each vertex to its parent. Do you see how if the graph is a tree, you will never encounter the same vertex twice?

 - First, implement walking towards the root for a single starting vertex.
 - The perform this walk from each and every vertex, checking that we don't encounter cycles for any of them.
 - Once this is done, we can think about how to make the algorithm linear-time.

It's best to do this in a public draft PR.

**Comment by pradkrish** [comment]
@szhorvat I agree, I am currently working on the first implementation and will be able to submit a draft PR soon. We can take the rest of the discussion once I submit a draft PR but just a quick question, how to extract root vertex from parents? If we define it based upon `child_vertex == parent_vertex` then vertices with self-loop also end up being root vertices. Could it be that root vertex user given input? Thanks.

**Comment by szhorvat** [comment]
> I am currently working on the first implementation

Sounds great!

> and will be able to submit a draft PR soon

I would suggest submitting a PR as soon as you have a skeleton of the function. It doesn't need to be even close to complete. If you work in the open, we can provide feedback early, and it's also easier for you to ask question.


> If we define it based upon `child_vertex == parent_vertex` then vertices with self-loop also end up being root vertices. Could it be that root vertex a user given input?

I think a good interpretation of the input is that if `parent[v] >= 0` then it is a vertex ID and if `parent[v] < 0` then `v` is a root. There are multiple roots in a forest. If `parent[v] == v` that is indeed a self-loop, i.e. a cycle, and should be disallowed.

**Comment by Nivig1310** [comment]
Hello, I would like to contribute to this

**Comment by Nivig1310** [comment]
@szhorvat I am familiar with graphs and feel I can implement this. The only thing concerning me is that I am unfamiliar with igraph and may need some guidance on that

**Comment by Nivig1310** [comment]
@szhorvat @GroteGnoom I am currently trying to install and compile igraph. When I run cmake .. in the build folder in terminal I get this error:
---------------------------------------------------------------------------------------------
-- Configuring done
CMake Error at CMakeLists.txt:6 (add_executable):
  Cannot find source file:

    igraph_test.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:6 (add_executable):
  No SOURCES given to target: igraph_test
---------------------------------------------------------------------------------------------------
Any suggestions on how to fix this? I am on MacOS

**Comment by ntamas** [comment]
I think this question belongs to the [support forum](https://igraph.discourse.group) and not here. I guess you are following the [tutorial](https://igraph.org/c/doc/igraph-Tutorial.html#tut-lesson-1-compiling-with-cmake), and the problem is that you have forgotten to create a file named `igraph_test.c` with the contents of the test file right at the top of the section. Or, if you _did_ create it, you put it in a different folder and not where `CMakeLists.txt` is. They should be in the same folder because `CMakeLists.txt` refers to `igraph_test.c` with a relative path.

If this does not solve your problem, let's continue the thread in the [discussion forum](https://igraph.discourse.group) until the compilation error is resolved to keep this issue focused.

**Comment by szhorvat** [comment]
I'm away for a few days, and will respond when I'm back. I agree that the forum is a better communication channel.

**Comment by szhorvat** [comment]
@Nivig1310 You will find information to get started here: https://github.com/igraph/igraph/wiki/Quickstart-for-new-contributors

The goal here is to implement a _linear-time_ function that verifies that a vector represents a tree of forest (i.e. graph with no cycles) and construct that tree or forest. You will find tips on how to implement this [in this comment](https://github.com/igraph/igraph/issues/1840#issuecomment-982014785).

Let me know if you plan to continue with this and I will assign you to this issue.

**Comment by szhorvat** [comment]
@Nivig1310 Are you still planning to work on this?
