### ISSUE TITLE
Create a triangular grid graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1842]
_This is a good first issue to work on for a new contributor interested in math._

**What is the feature or improvement you would like to see?**

Functionality to create various kinds of triangle grid graphs. Since we have a clean slate to work with, we should take the opportunity to think about how we can create a more general and nicer triangle grid generator than what is available on other libraries. I would like igraph to be able to generate at least the following graphs:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1212871/141675218-9c73bf6d-a90b-41aa-931b-4b83f52aa658.png">

Part of this task is to think about the best way to accomplish this. What interface would be both simple and general? We should think about this in terms of igraph's flexible higher-level interfaces, and then decide on an appropriate C interface late.

----

The following proposal is meant as a starting point for a discussion.

The function will be able to operate in three modes, taking either a single number, a pair of numbers or a triplet as input. The result will be a triangle shape, a rectangle shape or a general hexagon shape, respectively.

For the input `(5)` we get:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/141675472-cf137ea2-23a8-4cd5-a0e0-8c81bb957176.png">

(5 vertices on each side.)

For `(4, 6)` we get:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/141675499-d4bb994a-b7b8-4bc8-a1ca-d3542f220ecd.png">

(The rectangle is 6 vertices wide and 4 vertices tall.)

For `(5, 4, 3)` we get:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/141675528-0fa7cb49-6304-4a7f-b409-1a5ae3bca3a0.png">

(The three sides of the hexagon are 5, 4 and 3 vertices in length.)

For `(4, 4, 4)`:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/141675546-535ad789-943e-4721-8f46-c9e995d7fbed.png">

(All sides of the hexagon have 4 vertices along them.)

**Vertex coordinates**

The function should also be able to compute vertex coordinates for producing nice graph layouts, as in the illustrations above.

**Use cases for the feature**

Triangle grids are commonly used, and are provided by many other graph libraries. igraph should have them too.

**See also**

 - #1843 for hexagonal grids.

**Comment by GroteGnoom** [comment]
Are the way the triplets are interpreted a common way of describing the general hexagon shapes? For the singlet and doublet you can interpret the first number as a height, and the second as a width, so wouldn't it be nicer to describe the last two figures with (6, 5, 3) and (7, 4, 4)?

**Comment by szhorvat** [comment]
> Are the way the triplets are interpreted a common way of describing the general hexagon shapes?

I actually don't know. It just seemed intuitive to me, as the numbers can be thought of as the size lengths of the triangle, rectangle, and hexagon (to be precise: the number of vertices along each side). Part of the task here is to come up with a nice, general, but also intuitive way to describe various common shapes. So this should definitely be discussed.

> wouldn't it be nicer to describe the last two figures with (6, 5, 3) and (7, 4, 4)?

Can you explain the proposed meaning here? The first one is height in number of vertices. What about the second two? I realize that I didn't explain the meaning in the original post either, so I will correct that now.

**Comment by GroteGnoom** [comment]
The second was supposed to be the top width, and the third the top left side. Now that understand your system a bit better, I think it makes more sense, because the numbers are all side lengths, whereas mine is a mix of things.

**Comment by ntamas** [comment]
Also note that layout-wise there are two types of hexagonal grids: the "flat topped" and the "pointy topped" variant. I'm not sure that's relevant, but since the intention is to provide coordinates as vertex attributes in the output, maybe it's worth being aware about this distinction.

[This page](https://www.redblobgames.com/grids/hexagons/) contains more than you ever wanted to know about hexagonal grids.

**Comment by szhorvat** [comment]
> Also note that layout-wise there are two types of hexagonal grids: the "flat topped" and the "pointy topped" variant.

Yes, concerns only the layout (vertex coordinates). The graph is the same. It's a simple question of a 90 degree rotation. High-level interfaces should have easy ways to do coordinate transformations on already stored layouts. In IGraph/M, I can do:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/1212871/141758188-bbb741d9-2781-44b3-bdce-048f8ebdf036.png">

`IGVertexMap` simply maps a function over whatever vertex attribute, in this case the map a rotation transform function over the list of vertex coordinates. (Yes, I already have triangle grid implemented there, but only for the triangular and rectangular shapes, not hexagonal.)

To make such operations easy, perhaps it's not a bad idea to store vertex coordinates in a single attribute in python-igraph as well? That of course would make exporting to certain formats more complicated.  Or perhaps the C interface should support vector-valued attributes (right now it only does scalars)? That's a discussion for another thread though.


> [This page](https://www.redblobgames.com/grids/hexagons/) contains more than you ever wanted to know about hexagonal grids.

That's a good resource!

**Comment by oneamanish** [comment]
see my pull req.

**Comment by rfulekjames** [comment]
Hi all, I would be happy to implement this and possibly also #1843 as a first time contributor.  
It seems that this could be added to `/src/constructors/regular.c`.
I have an idea how to proceed but am also happy to discuss this in case you have some particular ideas as for how this should be implemented also in light of the following comment from the above:

> think about how we can create a more general and nicer triangle grid generator than what is available on other libraries. I would like igraph to be able to generate at least the following graphs:

cc: @szhorvat

**Comment by szhorvat** [comment]
That file has grown quite large, so please start a new file instead.

Take a look at the quickstart notes before beginning: https://github.com/igraph/igraph/wiki/Quickstart-for-new-contributors It's important to open a PR as soon as possible.

I'll assign you to this issue now. If you decide not to do it after all, that fine, but please do let us know.
