### ISSUE TITLE
Calculate localized clustering coefficient complement-based degree centrality

### ISSUE THREAD

**Issue by softrebel** [igraph/igraph#1857]
**What is the feature or improvement you would like to see?**
Hi, Please implement a method to calculate localized clustering coefficient complement-based degree centrality (LCC'DC) for each node.

**Use cases for the feature**
Its for research and develop purpose at current time.

**References**
[Article Paper](https://www.researchgate.net/publication/304065361_A_computationally_lightweight_and_localized_centrality_metric_in_lieu_of_betweenness_centrality_for_complex_network_analysis)

**Comment by szhorvat** [comment]
Can you please edit the text of the issue, and make sure that:

 - The concept is not just named, but also defined and explained in full. If possible, also explain how it can be computed.
 - Under "use cases", can you elaborate on what purpose this concept is used for? Is it of interest to igraph's audience? Is it commonly used in the network science community? (References?)

**Comment by vtraag** [comment]
From the paper's abstract I read "we define the local clustering coefficient-based degree centrality (LCCDC) for a node as the product of the degree centrality of the node and one minus the local clustering coefficient of the node. " To me this suggests it's a simple combination of two existing `igraph` functions. This can be easily done, either in C or any higher level interface. Is there any specific reason why this should be imemented separately in `igraph`?
