### ISSUE TITLE
igraph_error_t should be an enum

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1867]
`igraph_error_t` should be an enum, now it's a typedef for an `int`.

Be sure to test with C++.

**Comment by GroteGnoom** [comment]
> Be sure to test with C++.

It should just pass all our tests, right? Or do you think extra tests are required?

**Comment by szhorvat** [comment]
Thinking about it, I think the C++ parts of igraph itself should be sufficient to test it. If the library compiled, we're fine.

**Comment by GroteGnoom** [comment]
igraph_warning takes an igraph_error_t as one of its arguments, but that argument is 0 in one place in the source code, and -1 everywhere else (like in IGRAPH_WARNING). -1 is of course not allowed if igraph_error_t is an enum. Should we just remove the parameter?

**Comment by szhorvat** [comment]
I was always of the opinion that this parameter should be removed.

Ping @ntamas @vtraag for input.

**Comment by ntamas** [comment]
Yes, this can be removed (in igraph 0.10). Please either do it in the `develop` branch now or add it to the list of breaking changes in the wiki so we don't forget it.

**Comment by GroteGnoom** [comment]
Fixed in https://github.com/igraph/igraph/pull/1948
