### ISSUE TITLE
igraph_bfs_simple() argument names should be consistent with igraph_bfs()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1871]
The argument names in `igraph_bfs_simple()` should be made consistent with `igraph_bfs()`.

E.g., use `order` instead of `vids`, use `root` instead of `vid`, etc.

**Comment by GroteGnoom** [comment]
Fixed in edbb4530de1fc57ee165dd8f84cdcf1a26ff3a2b and b84c58544f2b00b5acf5b7d192d1e190406c8030
