### ISSUE TITLE
Check if a graph is a forest

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1873]
**What is the feature or improvement you would like to see?**

A function to check if a graph is a forest. It can mimic the interface of `igraph_is_tree()`.

Unlike `igraph_is_tree(), it should return true for the null graph.

_This is an easy task, but it's slightly more involved than other issues labelled as "good first issue". Look at `igraph_is_tree()` for inspiration._

**Use cases for the feature**

This is a generally useful basic check for a common graph type. This function will have better performance than decomposing a graph into components and calling `igraph_is_tree()` on each.

**Comment by rohitt28** [comment]
Hey I would like to work on this. I have compiled the development version of igraph and read about some basics from the tutorial.

Basic Implementation: -
I think a static function graph_is_forest_visitor() will be required which is similar to the one made for tree but this takes the visited vector. Only checking the ecount < vcount-1 might not work as there may be some components with only 1 vertex.
So, the Forest can have both directed and undirected graphs. 

- In case of undirected graphs, I will make a root vector and add each vertex to it and call the function for each unvisited root, check if there is a loop at any vertex.
- For directed ones, will there be only 1 type of trees in the forest (in tree or out tree)?
   1. If yes, then I can add each vertex with degree 0 to the root vector and follow the same approach as in undirected graphs. I will change the result to 0 if the current node is already visited or if total visited vertices not equal to vcount.
   2. If no, then we can’t get roots by finding vertices with degree 0. I am not sure about how to proceed in this case.

Is this approach fine?

**Comment by szhorvat** [comment]
Welcome! I assigned you to this issue, and we are looking forward to the implementation.

Generally, it works best if you open a draft PR early, so that we can see what you are doing and give tips as you go.

Your approach sounds good. 

In the undirected case, we only need to check that there are no cycles. Just in case I misunderstood your proposal: we want to end up with a `roots` vector that contains precisely one vertex from each connected component. So we can take an arbitrary vertex, add it to `roots`, then when we are done with the traversal, take the next unvisited vertex, add that to `roots`, and so one.

> * For directed ones, will there be only 1 type of trees in the forest (in tree or out tree)?

Only one type, as specified in the function's `mode` argument.



> Is this approach fine?

Sounds great!

Along the way, we can look for small opportunities to immediately discover that the graph is not a forest and return. For example, if `ecount > vcount - 1`, then it is certainly not a forest, and there is no need to look further.

**Comment by szhorvat** [comment]
Thanks again for implementing this @rohitt28 !
