### ISSUE TITLE
Generator for wheel graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1874]
**What is the feature or improvement you would like to see?**

A wheel graph is a union of a star graph and a cycle graph. There is a central graph which is connected to all vertices of a cycle. Illustration of a wheel graph on `n=6` vertices:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/1212871/144928899-7023f9c4-b8c8-471f-b1ce-d1615b76658d.png">

_The main purpose of this issue is to provide an easy way for would-be contributors to familiarize themselves with igraph._

**Use cases for the feature**

It is a simple but common graph type, comparable to start graphs, which are already implemented.

**References**

 - SageMath: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_generators.html#sage.graphs.graph_generators.GraphGenerators.WheelGraph

**Comment by kwofach** [comment]
HI, I'm a beginner. May I know if this issue wants to have a new function "igraph_wheel" which implements something like the following?
...
igraph_star(graph, n, mode, center); // create a star; and then
igraph_add_edges(graph, &edges, 0); // add edges to make it a wheel
...

**Comment by GroteGnoom** [comment]
Yes, that could be a way to implement it :)
There's a few references in https://github.com/igraph/igraph/issues/1840#issuecomment-980638705 that can get you up and running easily. If you have any questions, or if you need help making your workflow a little easier, please don't hesitate to ask.

**Comment by kwofach** [comment]
Thanks for your advice. I've tried to follow those references in #1840 but cannot fully understand the details. Hence, would like to list out a plan to see if the direction is correct:
1) for coding style, refer to the existing function igraph_star in src/constructors/regular.c
2) for code works
2.1) add codes and comments to src/constructors/regular.c;
2.2) add a new item to include/igraph_constructors.h;
2.3) add a new typedef to include/igraph_constants.h;
2.4) add a new entry to interfaces/functions.yaml;
2.5) add a new "WHEELMODE" to interfaces/types.yaml;
2.6) add an example igraph_wheel.c to examples/simple folder;
2.7) add igraph_wheel to doc/tutorial.xml
3) for testing, may I know if anything should be added to the tests/unit folder?

**Comment by GroteGnoom** [comment]
That is almost completely correct.

>        2.7) add igraph_wheel to doc/tutorial.xml
I think you should add it only to generators.xxml.

>     3. for testing, may I know if anything should be added to the tests/unit folder?
Yes, please add tests to tests/unit/igraph_wheel.c. You can let it print out results, and add the expected output to tests/unit/igraph_wheel.out
You should then also add igraph_wheel to tests/CMakeLists.txt

You already figured out a lot of stuff, some of which we sometimes forget ourselves, so that's great :D

**Comment by ntamas** [comment]
The `build` subdirectory has to be created at the top level (i.e. on the same level as `src`, `tests` etc). CMake will create subfolders within `build` as needed. We'll clarify this in the documentation for the next version.

**Comment by szhorvat** [comment]
Before looking at the tutorial, be sure to look at the installation instructions: https://igraph.org/c/html/latest/igraph-Installation.html You will not need to install igraph to make changes to it, but you will need to build it. How to do this is covered in the installation instructions.

**Comment by kwofach** [comment]
Don't know how to keep using this line, another line (pull request) has been made: https://github.com/igraph/igraph/pull/1938
