### ISSUE TITLE
Generator for Turán graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1875]
**What is the feature or improvement you would like to see?**

Implement a generator for Turán graphs.

A Turán graph `T(n,r)` has `r` partitions, with `n` vertices divided as equally as possible between them. Two vertices are connected precisely when they are in different partitions. A Turán graph is a special case of a complete multipartite graph. See Wikipedia for a more precise definition.

Consider implementing a general complete multipartite generator first, then implement the Turán graph as a special case.

_The main purpose of this issue is to provide an easy way for would-be contributors to familiarize themselves with igraph._

**Use cases for the feature**

Turán graphs are a well studied graph type in graph theory, with applications to graph colouring.

**References**

 - https://en.wikipedia.org/wiki/Tur%C3%A1n_graph
 - SageMath: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_generators.html#sage.graphs.graph_generators.GraphGenerators.TuranGraph

**Comment by pradkrish** [comment]
While the other PR is ongoing, I would like to start thinking and preparing for this. Is it okay to assign this to me?

**Comment by szhorvat** [comment]
Let's please finish one task before starting on the next one. Mark the other PR as ready for review when it's complete, or ask us if you need any help before you can complete it.

**Comment by szhorvat** [comment]
The idea of first creating a general function for complete multipartite graphs sounds good.

Let's name if `igraph_full_multipartite()`, in analogy with `igraph_full()` and `igraph_full_bipartite()`. I know this isn't standard terminology, but it's like this for historical reasons. Let's keep things consistent.

Instead of making it a variadic function, it should take a vector. The reason is that this way it will be easier to integrate it into high-level interfaces, and also easier to hook it up to an `igraph_turan()` function eventually. 

Let's also think about whether we could add a `directed` argument, and what the best way would be to interpret it. I'd suggest doing something similar to `igraph_full_bipartite()`, i.e. having a mode argument, and with `mode=OUT` having edges point from lower-index parts to higher-index ones. This is what Mathematica does as well (except it doesn't have a `mode` argument to optionally create reciprocal edges):

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1212871/171490805-0f1257e6-c3f5-4761-a7b0-9283d90e2d1b.png">

Alternative suggestions for handling directed graphs are welcome too.

Again in analogy with `igraph_full_bipartite()`, it may be useful to add an optional `types` integer vector output argument as well where the partition of each vertex would be stored.

**Comment by pradkrish** [comment]
is [this](https://math.stackexchange.com/questions/808060/what-is-the-maximum-number-of-edges-in-a-complete-multipartite-graph) the formula for calculating the total number of edges in a complete multipartite graph?

**Comment by pradkrish** [comment]
I have a first implementation now and I would like to open a draft PR. A couple of questions, where to put the function `igraph_full_multipartite()` and where to put the corresponding tests?

**Comment by ntamas** [comment]
Put the function in `src/constructors/full.c` (does not exist yet, need to be added to `src/CMakeLists.txt` as well) and add a new test in `tests/unit/full_multipartite.c`. If the test has an expected output on stdout, put that in `tests/unit/full_multipartite.out`.

**Comment by pradkrish** [comment]
Thanks, although `src/constructors/full.c` already exists in the develop branch at least. It makes sense to put it there.

**Comment by ntamas** [comment]
Yup, sorry, initially I wanted to propose a different (non-existent) file but then I changed mine.

**Comment by szhorvat** [comment]
> is [this](https://math.stackexchange.com/questions/808060/what-is-the-maximum-number-of-edges-in-a-complete-multipartite-graph) the formula for calculating the total number of edges in a complete multipartite graph? It does gives the correct value, just wondering whether there is a better formula out there.

Instead of googling for formulas, figure it out yourself. We need to do the calculation in an overflow-safe manner, using the functions from `math/safe_intop.h`.

Suppose partition $i$ has $n_i$ vertices. The total number of vertices is $n = n_1 + n_2 + \dots$  The $n_i$ vertices in partition $i$ will connect to $n - n_i$ vertices in the other partitions, contributing $n_i (n - n_i)$ edges. Summing these up for all $i$ gives not once, but _twice_ the number of undirected edges, as each edge is counted twice, once for each endpoint. Thus the number of edges is $m = \frac{1}{2} \sum_i n_i (n - n_i)$.

This manner of calculation is almost overflow-safe, as we add up positive quantities, always increasing, never decreasing the result. There is one exception: the division by two. It is possible that the sum gives a non-representable number even when half of it is representable.

However, we are in fact interested precisely in twice the number of edges when reserving memory (see `igraph_create()`), so it's fine to throw an error as soon as $2m$ overflows.

**Comment by szhorvat** [comment]
Of course, just press "ready for review" when done.
