### ISSUE TITLE
misdetection of math library functions

### ISSUE THREAD

**Issue by marcespie** [igraph/igraph#1878]
**Describe the bug**
Most Unix vendors have math functions like `expm1` in the math library, and `check_symbol_exists()` actually runs the linker

**To reproduce**
Run `cmake` on (for instance) OpenBSD, and see `expm1` not get detected.

I fixed it by adding

`set(CMAKE_REQUIRED_LIBRARIES "m")`
to CMakeList.txt, but I have zero idea how portable this would be.

**Version information**
release tarball for 0.9.5.

**Comment by szhorvat** [comment]
Are you working on including igraph in OpenBSD? If yes, perhaps we can coordinate and try to include all necessary fixes into a 0.9.6 release, so that you would not need to add any downstream patches.

**Comment by ntamas** [comment]
Actually, we try to figure out whether linking to the math library is necessary; see `etc/cmake/dependencies.cmake` and search for `NEED_LINKING_AGAINST_LIBM`. Can you check whether `NEED_LINKING_AGAINST_LIBM` is set to `TRUE` in the CMake cache or not?

If it is, then we should probably wrap all our `check_symbol_exists()` checks so that they are conditional on `NEED_LINKING_AGAINST_LIBM`.

**Comment by marcespie** [comment]
It's not enough: NEED_LINKING_AGAINST_LIBM is set to TRUE, but the check_symbol_exists do fail without setting CMAKE_REQUIRED_LIBRARIES.

Looking at your cmake glue in dependencies, I notice that you play a shell game with CMAKE_REQUIRED_LIBRARIES: you indeed try to link with libm. But once the test is passed, you reset CMAKE_REQUIRED_LIBRARIES to the saved value.

I think you need to take action on NEED_LINKING_AGAINST_LIBM to actually append libm in the correct location.

**Comment by marcespie** [comment]
@szhorvat thanks for the offer, but 0.9.5 already hit our ports tree a few hours ago.  Having one or two patches is no biggie. It's enough for me that this is properly fixed upstream so that I can remove the patch during the next release.

**Comment by marcespie** [comment]
As I suspected, the following one line addition is all that's needed to correctly detect math libraries, and it is indeed necessary for us.

[dependencies.txt](https://github.com/igraph/igraph/files/7676104/dependencies.txt)

**Comment by ntamas** [comment]
I'm a bit reluctant to add `m` to `CMAKE_REQUIRED_LIBRARIES` because it will then affect all compilation targets, which is problematic if igraph's `CMakeLists.txt` is used as a subproject in a larger CMake-based project. I'll check the CMake docs to see if there is a less intrusive option.
