### ISSUE TITLE
cmake does not check the glpk version

### ISSUE THREAD

**Issue by marcespie** [igraph/igraph#1879]
**Describe the bug**
I had an older version of glpk. configuration for igraph detected it and tried to use it, with lots of failures.

The test for glpk should actually, once detected, include glpk.h and verify the major/minor versions are okay, since unfortunately there is no pkgconfig file.

**To reproduce**
Install glpk < 5.0.

**Version information**
release tarball for 0.9.5

**Comment by szhorvat** [comment]
Which version of GLPK did you use?

**Comment by marcespie** [comment]
we were still on 4.55, and igraph build crashed with a glpk symbol missing in igraph compile.  I'll admit 4.55 is one year old.

I've updated to 5.0, and it works. But somehow, you don't work with 4.55.

**Comment by szhorvat** [comment]
> I'll admit 4.55 is one year old.

In fact, 4.55 is over 7 years old.

> we were still on 4.55

Thanks, this is a useful starting point. I'll figure out what the oldest supported version is and will add a check for it. 4.60 works fine, I'll bisect the range to 4.55. I expect that missing symbol will be `glp_at_error`.

**Comment by szhorvat** [comment]
I verified that GLPK 4.57 (released 2015 November) works, and I know that earlier versions will not (they lack `glp_on_error()`). So that's out minimum version.

**Comment by marcespie** [comment]
> > I'll admit 4.55 is one year old.
> 
> In fact, 4.55 is over 7 years old.
> 
Oops, I did not check beyond the last date our port got changed ;) I've updated it this morning.

Indeed it was full of cobwebs.  It's probably a good idea to have a minimal version check though, just in case you ever want to use newer features ;)

**Comment by szhorvat** [comment]
@marcespie I would recommend explicitly enabling external dependencies here:

https://github.com/openbsd/ports/blob/master/math/igraph/Makefile#L34

See here for more info:

https://igraph.org/c/html/latest/igraph-Installation.html#igraph-Installation-notes-for-package-maintainers

I have now added a version check for GLPK. With this feature, if it does not find a compatible GLPK version, it will simply use the bundled GLPK. While this is convenient, maybe you want more predictability as a package maintainer. If you explicitly set `-DIGRAPH_GLPK_SUPPORT=ON` and `-DIGRAPH_USE_INTERNAL_GLPK=OFF` then if it does not find an _external_ GLPK library, it will simply error.
