### ISSUE TITLE
random_walk() should take weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1882]
`igraph_random_edge_walk()` takes weights, but `igraph_random_walk()` does not. `igraph_random_walk()` should also be extended to take a `weights` argument. 

The underlying weighted implementation of `random_walk()` can mirror `random_edge_walk()` but it should be separate from the unweighted one. This is because the unweighted one uses an adjlist, while the weighted one needs an inclist. At this time, inclist-based traversal is slower (see benchmarks in #1823).

Notes:

 - We have a benchmark for random walks, keep an eye on it when implementing this.
 - Discussed here before: https://github.com/igraph/igraph/pull/1046#issuecomment-355291543

----

_While this is marked as a "good first issue", it is a bit more involved than other such issues. If you decide to work on this, mirror the implementation in `igraph_random_edge_walk()`, which already supports weights._

**Comment by mp0963** [comment]
Hello, I am new to igraph and I would love to try working on this. Is this still open?

**Comment by meetpatel0963** [comment]
Hello, I am new to igraph and I would love to try working on this. Is this still open?

**Comment by szhorvat** [comment]
Yes, it is open, but note the last comment in italics. If you feel confident, go ahead and open a PR.  There's some info on getting started here: https://github.com/igraph/igraph/wiki/Quickstart-for-new-contributors

**Comment by szhorvat** [comment]
`IGRAPH_OTHER` is slower than `IGRAPH_TO`/`IGRAPH_FROM`, so it's better to use the correct version.  Note that `IGRAPH_OTHER` contains an unpredictable conditional, which can potentially affect performance (see https://stackoverflow.com/q/11227809/695132 for an example).

Now, performance is a complicated topic, and it's unclear how great the practical performance difference will be. But I prefer that you keep the switch here, both for performance and clarity.

**Comment by meetpatel0963** [comment]
oh, got it. I'll do the same in `igraph_random_walk()`. Also, Thank you for sharing this example. It was an amazing piece of info 🙌.

**Comment by szhorvat** [comment]
See #2013.
