### ISSUE TITLE
Why is computing the mean distance much faster than computing the distance matrix?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1889]
When tested through the Python interface, the `igraph_average_path_length()` function appears to be much faster than the `igraph_shortest_paths()` one. This issue is to write a benchmark for the C core, determine if the difference is present in the C layer as well, and if yes, investigate why, and how we may speed up `igraph_shortest_paths()`.

Example code in Python:

```
import igraph as ig
import random
import time

random.seed(123)
g = ig.Graph.Lattice([15, 15, 15])
g.rewire(100)

s = time.time()
g.average_path_length()
e = time.time()
e-s

# typical timing is 0.35 s

s = time.time()
g.shortest_paths()
e = time.time()
e-s

# typical timing is 0.93 s
```

**Comment by szhorvat** [comment]
@GroteGnoom Are you interested in looking into this, since this might be related to #1823?

**Comment by ntamas** [comment]
I think it's the overhead of creating a Python list-of-lists data structure to hold the result.

**Comment by szhorvat** [comment]
If the overhead is really this large (still needs to be confirmed!), would it make sense to use a numpy array? I understand that we want to avoid a dependence on numpy, but in this case the conversion to a list-of-lists seems to take longer than the actual shortest path computation.

**Comment by ntamas** [comment]
NumPy is much more common nowadays than it was ~10-15 years ago so I don't mind if the next version of the Python interface of igraph (the one to be based mostly on generated code and small disjoint functions instead of a monolithic Graph class) started using NumPy matrices where it makes sense. I just don't want to put too much effort into refactoring the existing codebase to NumPy matrices now that we want to redesign the whole Python interface anyway.

**Comment by szhorvat** [comment]
I have investigated this a little bit in the C core (benchmark is incoming). There is some difference, though not huge, and I do not yet know where most of it is coming from. But do you know where a noticeable portion of it came from? This (bad) pattern:

```
for (i=0; i < igraph_vector_size(vec); ++i)
```

This is why I keep saying never to call `vector_size` in a loop. It has a significant performance impact if LTO is not enabled. 

Here's the fix for this one case: 618c2491f663a1a005b37f49652ea033cf0e40ef

And here are before/after benchmarks. Before the fix:


```
|> Benchmark file: /Users/szhorvat/Repos/igraph-main/igraph/tests/benchmarks/igraph_average_path_length.c
|  1 Kautz(4, 5) average_path_length directed                                      0.448s  0.446s  0.001s
|  2 Kautz(4, 5) shortest_paths directed                                           0.834s  0.772s   0.06s
|  3 Kautz(4, 5) average_path_length undirected                                    0.781s  0.776s  0.002s
|  4 Kautz(4, 5) shortest_paths undirected                                          1.34s   1.33s  0.004s
|  5 Rewired 15x15x15 lattice average_path_length                                  0.354s  0.352s  0.001s
|  6 Rewired 15x15x15 lattice shortest_paths undirected                            0.489s  0.487s  0.001s
|  7 Erdos-Renyi n=10000 m=12000 average_path_length directed                      0.331s  0.328s  0.001s
|  8 Erdos-Renyi n=10000 m=12000 shortest_paths directed                           0.639s  0.497s   0.14s
|  9 Erdos-Renyi n=10000 m=12000 average_path_length undirected                     3.22s   3.21s  0.006s
| 10 Erdos-Renyi n=10000 m=12000 shortest_paths undirected                          4.06s   4.02s  0.015s
```

After the fix:

```
|> Benchmark file: /Users/szhorvat/Repos/igraph-main/igraph/tests/benchmarks/igraph_average_path_length.c
|  1 Kautz(4, 5) average_path_length directed                                      0.425s  0.422s  0.001s
|  2 Kautz(4, 5) shortest_paths directed                                           0.669s  0.615s  0.051s
|  3 Kautz(4, 5) average_path_length undirected                                    0.689s  0.687s  0.001s
|  4 Kautz(4, 5) shortest_paths undirected                                         0.847s  0.844s  0.002s
|  5 Rewired 15x15x15 lattice average_path_length                                  0.384s  0.381s  0.001s
|  6 Rewired 15x15x15 lattice shortest_paths undirected                            0.417s  0.414s  0.001s
|  7 Erdos-Renyi n=10000 m=12000 average_path_length directed                       0.33s  0.329s  0.001s
|  8 Erdos-Renyi n=10000 m=12000 shortest_paths directed                           0.637s  0.494s  0.141s
|  9 Erdos-Renyi n=10000 m=12000 average_path_length undirected                     3.38s   3.35s  0.008s
| 10 Erdos-Renyi n=10000 m=12000 shortest_paths undirected                          3.55s   3.52s  0.008s
```

**Comment by ntamas** [comment]
Nice catch!

FWIW I just ripgrepped `src` for similar patterns and it looks like there are quite a few other places where we could improve things in a similar vein. Try running `rg "for.*;.*_size\("` from the `src` folder.

**Comment by szhorvat** [comment]
I've already done the same, made some fixes on master, but merging into develop was such a pain that I threw that away. Instead, I re-did some of the work on develop separately.

**Comment by szhorvat** [comment]
An interesting observation is that `develop` (with proper usage of `igraph_integer_t`) is not faster than `master` when compiled without LTO. But _with_ LTO there is a noticeable performance gain on `develop` in these benchmarks. Not sure why, but I'm happy.
