### ISSUE TITLE
minimum_size_separators() questionable result on complete graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1910]
**Describe the bug**

`igraph_minimum_size_separators()` returns questionable results on complete graphs. It returns all size-`(n-1)` vertex subsets.

In Mathematica:

```
In[114]:= IGMinimumSeparators[CompleteGraph[3]]
Out[114]= {{2, 3}, {1, 3}, {1, 2}}

In[115]:= IGMinimumSeparators[CompleteGraph[4]]
Out[115]= {{2, 3, 4}, {1, 3, 4}, {1, 2, 4}, {1, 2, 3}}
```

I would not consider these separators and indeed `igraph_all_minimal_st_separators()` does not return them. I would expect the result of `igraph_minimum_size_separators()` to be a subset of that of `igraph_all_minimal_st_separators()`.

Thus a good result would be empty. However, the result returned here is consistent with that of `igraph_vertex_connectivity()`

Opinions @vtraag?

Before starting to work on this issue, be sure to get familiar with #1480.

**Version information**
Tested with `master` through the Mathematica interface.

**Comment by rfulekjames** [comment]
> Thus a good result would be empty. However, the result returned here is consistent with that of igraph_vertex_connectivity()

For what its worth, the reason behind the result not being empty is the specialized behaviour of `igraph_minimum_size_separators()` for complete graphs. In particular, this [if-condition](https://github.com/igraph/igraph/blob/7915de3e7fc357cd97af2c9811190cf1d0aeee26/src/connectivity/separators.c#L680) evaluates to `true` if and only if the graph is complete I think (for the connectivity is less than  `no_of_nodes - 1` iff there exists a pair of vertices not joined by an edge). 
Then the block entered if the if-condition is `true` just sets all vertex subsets of size `no_of_nodes - 1` as separators.

cc @szhorvat

**Comment by szhorvat** [comment]
Thank you for pointing that out @rfulekjames.

So it seems that this was deliberately special-cased. I'm thinking of removing this behaviour for version 1.0. What do you think @ntamas @vtraag ?

**Comment by ntamas** [comment]
Seems OK to me.

**Comment by szhorvat** [comment]
Do we wait for 1.0 or we do it for 0.10.11?

**Comment by ntamas** [comment]
I'd say 1.0. That's what the original proposal was, wasn't it?
