### ISSUE TITLE
GraphML reader prints to the terminal

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1915]
**Describe the bug**

igraph functions should never print to the terminal (except through the error handlers), but in some situations, `igraph_read_graph_graphml()` does anyway.

The message comes from libxml2, which also should not print except through handlers. Are we not setting some of the error handlers for libxml2?

**To reproduce**

Invalid GraphML file that triggers printing:

[783599aa67c78c06a361494befcd2f7c1f00e1b1.zip](https://github.com/igraph/igraph/files/7814263/783599aa67c78c06a361494befcd2f7c1f00e1b1.zip)

The message is:

```
encoding error : input conversion failed due to input error, bytes 0xA0 0x72 0x2E 0x74
encoding error : input conversion failed due to input error, bytes 0xA0 0x72 0x2E 0x74
```

**Version information**
Current `master` and `develop`

**Comment by ntamas** [comment]
For future reference: `libxml2` prints this particular message using `xmlGenericError()` (see [source code](https://github.com/GNOME/libxml2/blob/master/encoding.c#L2090). There seem to be two functions in the `libxml2` API (`xmlThrDefSetGenericErrorFunc()` and `xmlThrDefSetStructuredErrorFunc()`) that could do the trick, but neither of these seem to be documented. Plus, I was wondering whether it's right to mess around with the global state of the `libxml2` library; in theory, `igraph` could be part of an app that also uses `libxml2` on its own, in which case we would be stepping on the toes of the host app if the host app also manipulates the error handlers in `libxml2`.

The right way would be to set up our error handlers for `libxml2` before entering the parser and to restore them after exiting the parser, but `libxml2` does not seem to provide a way to get a pointer to the old handler.

**Comment by szhorvat** [comment]
Maybe (xmlGetGlobalState)[http://www.xmlsoft.org/html/libxml-threads.html#xmlGetGlobalState] can be used to retrieve the current error handler?

**Comment by ntamas** [comment]
It took a bit more coding than I had anticipated, but it looks like it's working now. See above.

**Comment by szhorvat** [comment]
I still get a lot of this:

```
encoding error : input conversion failed due to input error, bytes 0xFA 0x00 0x00 0x00
encoding error : input conversion failed due to input error, bytes 0xB6 0x6E 0x67 0x22
```

But since the fuzzer doesn't stop on such events, I don't quite have any reproducible examples yet.

**Comment by szhorvat** [comment]
Here's an example:

[encerr.zip](https://github.com/igraph/igraph/files/7828358/encerr.zip)

**Comment by ntamas** [comment]
It turns out that we prematurely loaded and parsed the first 4K of the input file to detect the encoding, and this part was not guarded by our error handlers. Now it should be okay.

**Comment by szhorvat** [comment]
Verified fixed.
