### ISSUE TITLE
GraphML: unintuitive error message for empty file

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1916]
**Describe the bug**
When a 0-byte file is read as GraphML, the error is the following:

```
Error at src/io/graphml.c:1424 : Extra content at the end of the document
 - Parse error.
```

This is unintuitive. Of course, there is no extra content.

Needless to say, this is a low-priority bug.

**Version information**
`master`

**Comment by ntamas** [comment]
I think that this error message comes straight from `libxml2` (at least the phrase "Extra content" does not appear anywhere in our codebase) so there's not much we can do about it, apart from replacing the text of all error messages from `libxml2` with a generic placeholder.

**Comment by szhorvat** [comment]
Closing then.
