### ISSUE TITLE
Add an example for igraph_assortativity

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1931]
Start from the `develop` branch and add to examples/simple:
- igraph_assortativity.c, which calls the function igraph_assortativity (in /src/misc/mixing.c) with some graph and prints out the result,
- igraph_assortativity.out which contains the correct printed result.

Then, add the example to tests/CMakeLists.txt and to the docs of the function in /src/misc/mixing.c 

For an example of a simple example program: see examples/simple/igraph_small.c

The same should done for igraph_assortativity_nominal and igraph_assortativity_degree

- [ ] igraph_assortativity
- [ ] igraph_assortativity_nominal
- [x] igraph_assortativity_degree (https://github.com/igraph/igraph/pull/1946)

This issue is meant specifically for newcomers, and we'll gladly guide you through the process if you need any help :slightly_smiling_face:

Here's some more info about assortativity: http://networksciencebook.com/chapter/7#introduction7

----

Note: This is a part of #1585.

**Comment by valdaarhun** [comment]
Hi. I am new to igraph and would like to work on this.

**Comment by GroteGnoom** [comment]
Great! Are you already able to build and test quickly? That's probably a good first step :)

**Comment by valdaarhun** [comment]
Yeah, I followed the instructions in the reference manual and now I am able to build and test programs quickly. :)

**Comment by szhorvat** [comment]
I quickly wrote up a quickstart for new contributors. @GroteGnoom, please edit it as you see fit. https://github.com/igraph/igraph/wiki/Quickstart-for-new-contributors

**Comment by valdaarhun** [comment]
Hi. I have a question related to the `igraph_lattice` function in the [documentation](https://igraph.org/c/html/latest/igraph-Generators.html#igraph_lattice). According to the doc, the argument `nei` gives the distance (number of steps) within which two vertices are connected. Will `nei=0` and `nei=1` give the same graph?

I have gone through the implementation of the function [here](https://github.com/igraph/igraph/blob/8c263a594ee2cabb1dcf8dc30da5dcb73bcc8ae3/src/constructors/regular.c#L179) and it doesn't seem like the graph for `nei=0` and `nei=1` will be different. Have I overlooked something?

**Comment by GroteGnoom** [comment]
I don't think you've overlooked anything. For `nei<2` it will just ignore it. Else it calls `igraph_connect_neighborhood`, which would have given a warning for `nei=0` or `nei=1` and an error for negative numbers.

**Comment by valdaarhun** [comment]
Hi. I am sorry I haven't been active of late. I was very busy with college work but now the pressure has reduced and I would like to continue working on this issue. I am planning to start with `igraph_assortativity_nominal()` and go about it as explained in this [comment](https://github.com/igraph/igraph/pull/1946#issuecomment-1035977240).

I was going through the documentation on `igraph_preference_game` and I had a few questions.

Q1. Does types refer to the number of vertex groups or the number of buckets in which vertexes are distributed? For eg, if `types = 9`, does that mean each vertex will have a type that lies between 0 and 8?

Q2. The [documentation](https://igraph.org/c/html/develop/igraph-Generators.html#igraph_preference_game) says:

> if fixed_sizes is true and type_dist is NULL, then the function tries to make vertex groups of the same size. If this is not possible, then some groups will have an extra vertex.

Does this mean for `types = 9, fixed_sizes = true, type_dist = NULL`, each type (0-8) should have at least one vertex?

**Comment by valdaarhun** [comment]
I wrote a program that generates a graph with 50 nodes and 9 vertex types.

```
#include <igraph.h>
#include <stdio.h>

int main(){
    igraph_t g;
    igraph_integer_t nodes = 50, types = 9;
    igraph_vector_int_t node_type_vec;

    igraph_matrix_t pref_matrix;
    igraph_matrix_init(&pref_matrix, types, types);

    igraph_rng_seed(igraph_rng_default(), 42);

    for(igraph_integer_t i = 0; i < types; i++){
        for(igraph_integer_t j = i; j < types; j++){
            MATRIX(pref_matrix, i, j) = igraph_rng_get_unif(igraph_rng_default(), 0, 1);
            MATRIX(pref_matrix, j, i) = MATRIX(pref_matrix, i, j);
        }
    }
    for(igraph_integer_t i = 0; i < types; i++){
        for(igraph_integer_t j = 0; j < types; j++){
            printf("%f ", MATRIX(pref_matrix, i, j));
        }
        printf("\n");
    }

    igraph_vector_int_init(&node_type_vec, nodes);

    igraph_preference_game(&g, nodes, types, NULL, 1, &pref_matrix, &node_type_vec, IGRAPH_UNDIRECTED, IGRAPH_LOOPS);
    for(igraph_integer_t i = 0; i < nodes; i++){
        printf("%d ", VECTOR(node_type_vec)[i]);
    }
    printf("\n");

    igraph_destroy(&g);
    igraph_vector_int_destroy(&node_type_vec);

    igraph_matrix_destroy(&pref_matrix);
}

```

The output of the `node_type_vec` vector, however, only has vertex types in the 0-4 range. I didn't understand why there aren't vertices with more vertex types.

**Comment by ntamas** [comment]
Congratulations, you have found a bug in `igraph_preference_game()` :) The bug happens when `fixed_sizes` is true and there is no type distribution vector provided. I'll submit a patch soon.

**Comment by ntamas** [comment]
`igraph_preference_game()` bug is now fixed both in `develop` and in `master`.

**Comment by valdaarhun** [comment]
> _Edit_: by the way, you can use `igraph_vector_int_print()` and `igraph_matrix_print()` to print vectors and matrices, no need to roll your own loops.

That's nice. I'll keep this in mind. Thanks!
