### ISSUE TITLE
Convenience function to check if a graph is acyclic

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1932]
**What is the feature or improvement you would like to see?**

A function to check if a graph is acyclic.

This is simple to implement: check if the graph is directed and a DAG (`igraph_is_dag()`) or if it is undirected and a forest (`igraph_is_forest()`).

_This issue is targeted at beginners. See [the wiki](https://github.com/igraph/igraph/wiki) on how to get started._

**Use cases for the feature**

Checking if a graph is acyclic is a common operation, so it is useful to have a single convenience function for it.

**Comment by borsgeorgica** [comment]
could I work on this ?

**Comment by GroteGnoom** [comment]
Sure!

**Comment by szhorvat** [comment]
I would also like to bring to your attention these two issues: #1931 and #1585. They may be easier to get started with, and they also give you more freedom in doing things your own way. Unlike library code, examples do not need to be perfect.

If you still prefer to work on this issue though, you are welcome to do so.

**Comment by szhorvat** [comment]
@borsgeorgica Let us know if you decided to go ahead with this issue.

Useful resources to look at before getting started:

 - Installation and Tutorial sections in the docs: https://igraph.org/c/html/latest/
 - Several beginner focused sections of the wiki: https://github.com/igraph/igraph/wiki

**Comment by borsgeorgica** [comment]
@szhorvat thanks for linking the resources! sorry, I didn't get a chance to start on the issue yet but will do soon. I also looked at the other issues you suggested, I will give this a go first and maybe try the other ones if this is too challenging to start with.

**Comment by borsgeorgica** [comment]
@szhorvat you mentioned `igraph_is_forest()`, is that something that's already implemented in `igraph` ? I looked in the manual and code but couldn't find it. I could see only `igraph_is_dag()`.

**Comment by GroteGnoom** [comment]
It was added here: https://github.com/igraph/igraph/pull/1888 to the develop branch.
