### ISSUE TITLE
Implement overflow-safe arithmetic

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1933]
This issue is to discuss the implementation of overflow-safe integer arithmetic for `igraph_integer_t`. This is necessary to be able to avoid crashes when trying to create too-large data structures, such as: https://github.com/igraph/rigraph/issues/405 https://github.com/igraph/rigraph/issues/348

### Where do we need this?

These safe arithmetic operations would usually be used only at the very beginning of some functions, when computing vertex counts, edge counts, or whatever data structure size. Performance is thus not critical. 

### API

I propose the following API for _internal_ functions:

```
igraph_error_t igraph_add(igraph_integer_t a, igraph_integer_t *b, igraph_integer_t *res);
igraph_error_t igraph_mult(igraph_integer_t a, igraph_integer_t *b, igraph_integer_t *res);
...
```

with matching macro versions which raise error automatically (no need for `IGRAPH_CHECK`). Otherwise it gets very tedious to write code using these. I suggest that the function is a wrapper for the macro and not the other way around, for slightly better performance.

We will occasionally need safe exponentiation as well, notably for `igraph_kautz()` and `igraph_de_bruijn()`. We can make use of GMP for that.

#### SEI CERT C Coding Standard

This is a useful document that explains the problems with integer overflow, and gives code snippets in C showing how to do various checks.

https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152052

#### GCC built-ins

GCC has built-ins for safe integer operations. These may be used for better performance,

https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html

#### safe_iop.h

https://code.google.com/archive/p/safe-iop/wikis/README.wiki

This is a header-only C library (not C++), and is part of Android. Latest version is here: https://android.googlesource.com/platform/external/safe-iop/+/refs/heads/master

It is in the public domain, so we can re-use code from it. It comes with a test suite, which will be useful even if we go with another solution.

One concern is that it is stated that [it was designed specifically for GCC](https://code.google.com/archive/p/safe-iop/wikis/Compatibility.wiki) and not tested with other compilers. This may be a deal breaker.

#### SafeInt

The SafeInt library is promoted by Microsoft: https://docs.microsoft.com/en-us/cpp/safeint/safeint-library?view=msvc-170

It appears to be standards compliant (?) and it is specifically tested (and compiles without warnings) with GCC, Clang and MSVC. However, this is a C++ library, not C.

#### Undefined Behaviour Sanitizer

UBSan may be useful for testing. It detects integer overflow. A good implementation of safe arithmetic (like the ones above) can detect overflow _before_ it would happen and thus does not trigger UBSan.

**Comment by szhorvat** [comment]
Which solution shall we go with? I think we have three reasonable options:

 1. safe_iop
 2. SafeInt
 3. roll our own

While (1) seemed the most reasonable at first, relying on a library that explicitly does not support anything except GCC does not seem like a good idea. I think we should go with either (2) SafeInt or (3) our own. 

SafeInt is less work and likely performs better than whatever we would create. But it is C++ (uses exceptions!), and might not support exponentiation, which we need.

I think rolling our own is not such a bad choice because there are good resources that provide ready-to-use code snippets, performance is probably not critical for us, and we can implement exponentiation through GMP.

Opinions?

**Comment by ntamas** [comment]
I've taken a look at SafeInt and it seems like it's basically a header-only C++ library. On one hand that's nice because everything would probably get inlined; on the other hand, it seems to be class-based, so basically we can't have `igraph_integer_t` any more, we would need to have `SafeInt<igraph_integer_t>` all around the code, right?

**Comment by szhorvat** [comment]
> Or would we keep `igraph_integer_t` and implement `igraph_add()` such that it converts the integers momentarily to `SafeInt`, performs the operation, catches all errors raised from the C++ part of the code, and converts them back to igraph error codes?

I think if we use SafeInt, that's the only way to go.

However, I would still rather use our own implementation. It seems to me that the major benefit both of these libraries (SafeInt and safe_iop) provide is (1) convenience of use (2) performance and (3) generality across types (signed and unsigned). The actual implementation is not that difficult, and much code can be borrowed from the SEI CERT C Coding Standards. For the majority of tasks we only need two functions: addition and multiplication. Exponentiation would be separate, and is so far needed in only two graph generators. Subtraction is nice, but can be done in terms of addition.  My hunch is that performance is not important for us (these would never be used in a bottleneck).

I'll look into creating our own implementation maybe next week, if all goes well.

**Comment by szhorvat** [comment]
Branch is here: https://github.com/igraph/igraph/tree/feat/overflow-checks

I noticed that  `igraph_matrix_view(&matrix, data, nrow, ncol)` can technically fail through overflow, but it does not return an `igraph_error_t`, so it cannot handle errors. I think this is fine, and we don't need to fix it through an API-breaking change. It is the user's (programmer's) responsibility to ensure that the size of `data` matches `nrow*ncol`, which implies that `nrow*ncol` cannot overflow.

**Comment by szhorvat** [comment]
@ntamas Have a look at the concept on the above branch before I continue. I'm thinking that the output argument of the macros should required to be a pointer, just for readability: make it abundantly clear that this is an output argument.

**Comment by szhorvat** [comment]
The `feat/overflow-checks` branch is now merged.
