### ISSUE TITLE
Add CMake config option to sync line numbers with Bison/Flex files

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1934]
Currently, Bison is run with `--no-lines` and Flex with `--noline`. This is to prevent including `#line` preprocessor directives which may have the absolute pathname of some files, and thus can potentially leak some private information of the person creating the release tarball on their machine (i.e. @ntamas :)

This is a request to add a CMake configuration option to disable adding these command line options. The purpose of these `#line` directives is so that various debugging tools can refer to the original Flex/Bison `.l`/`.y` files in their error messages, instead of referring to the C files generated by Flex/Bison. The generated C files, and thus their line numbers, tend to be different depending on the version of Flex/Bison. Referring back to the original Flex/Bison files is useful when looking at error messages produces on CI or by OSS-fuzz. OSS-fuzz in particular is mainly used for testing exactly these Bison-based parsers.

**Comment by szhorvat** [comment]
@ntamas Can you please help with this, since you are experienced with adding new options to the CMake build system? The option can stay "advanced" (i.e. hidden) if you like, and should be off by default. If turned on, the `--noline` and `--no-lines` options should not be used here:  https://github.com/igraph/igraph/blob/develop/src/CMakeLists.txt#L22 I would fine this very helpful when dealing with OSS-fuzz.

**Comment by ntamas** [comment]
Added `FLEX_KEEP_LINE_NUMBERS` as a CMake option; setting this option to `YES` will remove the `--noline` and `--no-lines` flags.

**Comment by szhorvat** [comment]
Thanks!
