### ISSUE TITLE
igraph_laplacian() consistent API

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1936]
While we are making API-breaking changes, `igraph_laplacian()` should be revisited. Changes we might want to make:

 - Split it into a dense and sparse variant.
 - Rename to `get_laplacian` for consistency with `get_adjacency`?
 - Check if self-loop handling is reasonable. Since this matrix is closely tied to diffusion/random walks/flows, and also includes degrees, self-loops should be counted twice on the diagonal.

**Comment by szhorvat** [comment]
Assigned to @ntamas as it seems you're already working on this.

**Comment by ntamas** [comment]
Steps to do:

- [ ] Rename `igraph_laplacian()` to `igraph_get_laplacian()`
- [ ] Deprecate `igraph_laplacian()`
- [ ] Add `igraph_get_laplacian_sparse()`
- [ ] Figure out whether there's a sensible way to handle self-loops.

As for self-loop handling, the current implementation of `igraph_laplacian()` ignores loops. This sort-of makes sense. I guess the rule is that for each directed edge _i_ -> _j_ with weight _w_, you must add _w_ to the i-th diagonal entry and subtract _w_ from the (i, j)-th cell of the matrix. If you have a loop edge, this basically adds and removes _w_ to the same slot so nothing changes. For undirected graphs, you treat undirected edges as two directed ones, so the net result is the same again. @szhorvat does this make sense mathematically?

**Comment by ntamas** [comment]
@szhorvat One thing that's unclear to me yet is how loop edges are supposed to work with the _normalized_ Laplacian (which we support at the moment) - do the loop edges have any effect there?

**Comment by szhorvat** [comment]
`feat/laplacian` branch is now merged.
