### ISSUE TITLE
Bipartite modularity

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#194]
This means using another null model, in the general modularity formula. See 
Michael J Barber: Modularity and community detection in bipartite networks,
Phys Rev E 76 066102
http://pre.aps.org/abstract/PRE/v76/i6/e066102

---

Imported from Launchpad using lp2gh.
- date created: 2010-06-15T12:32:45Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/594581

**Comment by MattPM** [comment]
Hello, Is there currently support for bipartite graph modularity functions in igraph?

**Comment by vtraag** [comment]
@MattPM, I don't believe there is any support for bipartite modularity at the moment. However, you may be interested in the `leidenalg` package, which does provide that possibility, see the [documentation](https://leidenalg.readthedocs.io/en/latest/multiplex.html#bipartite) for an explanation.
