### ISSUE TITLE
Rename igraph_degseq_t enum values

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1952]
I would like to rename the enum values in `igraph_degseq_t` to make their naming clear, consistent, and intuitive. I am waiting for feedback on this before making the change.

To see why the current naming is not very good, first look at the namings, make a guess about what each option might do, then read the documentation.

```
typedef enum { IGRAPH_DEGSEQ_SIMPLE = 0,
               IGRAPH_DEGSEQ_VL,
               IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE,
               IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE_UNIFORM
             } igraph_degseq_t;
```

Here's what I would like to change it to.

<details><summary><strong>Proposed change</strong></summary>

```
typedef enum { 
               IGRAPH_DEGSEQ_CONFIGURATION = 0,    /* Configuration model, allowing non-simple graphs */
               IGRAPH_DEGSEQ_VL,                   /* Viger-Latapy */
               IGRAPH_DEGSEQ_HEUR1_SIMPLE,         /* Fast heuristic, generates simple graphs */
               IGRAPH_DEGSEQ_CONFIGURATION_SIMPLE, /* Configuration model, generates simple graphs */

               /* for backwards compatibility: */
               IGRAPH_DEGSEQ_SIMPLE = IGRAPH_DEGSEQ_CONFIGURATION,
               IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE = IGRAPH_DEGSEQ_HEUR1_SIMPLE,
               IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE_UNIFORM = IGRAPH_DEGSEQ_CONFIGURATION_SIMPLE
             } igraph_degseq_t;
```

`HEUR1` refers to "heuristic method 1", anticipating that we may have more of these ad-hoc methods the future. If you don't like this name, please propose a different one.

The suffix `_SIMPLE` indicates that the method generates simple graphs only.

The principle is to name the sampling method (e.g. "configuration model") an not the output (e.g. "uniform sampling of simple graphs"). This is because all currently known methods have significant tradeoffs. Thus, for the same outcome, one needs to consider carefully which method to choose.
</details>

Notes:
 - GCC can issue deprecation warnings for enum values: https://stackoverflow.com/a/33096368/695132
 - This is technically neither API nor ABI-breaking (the meaning of numeric values does not change and old symbolic names are kept, though deprecated)

**Comment by szhorvat** [comment]
Additionally, I would like to add a fifth method `IGRAPH_DEGSEQ_EDGE_SWITCHING /* edge switching MCMC */` which uses `igraph_realize_degree_sequence()` and `igraph_rewire()`.

**Comment by vtraag** [comment]
The proposed names sound good to me. The difference between `IGRAPH_DEGSEQ_EDGE_SWITCHING` and `IGRAPH_DEGSEQ_VL` would then be that the latter samples only undirected connected graphs (approximately uniformly), while the former samples simply all graphs (directed & undirected, but no guarantee on connectivity). Do I understand that correctly?

**Comment by szhorvat** [comment]
Yes, it's roughly that, although it has to be pointed out that there are multiple ways to keep the graph connected while rewiring, and the VL method is just one of these (I have an alternative idea which I would work on if I had the time).

If you prefer, we can include `MCMC` in the name.
