### ISSUE TITLE
lazy_adjlist/inclist_get() can fail—do we want to change the design?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1955]
`igraph_adjlist_get()` and `igraph_inclist_get()` return pointers directly instead of an error code. This is nice and convenient, and feasible, because these functions (actually: macros) can never fail.

However, `igraph_lazy_adjlist_get()` and `igraph_lazy_inclist_get()` _can_ fail because they allocate memory on demand. As far as I can tell, the only possible mode of failure is out-of-memory (though I may have missed something). When they fail, they return `NULL`. This was undocumented, so I amended the documentation. 

Note that their return value is never actually checked. Personally, I did not even realize that they can fail.

**Discussion point:** Do we want to change the API of these functions before 0.10?

Whatever we do, we should make sure that the lazy and non-lazy APIs are as similar as possible, to make experimentation and benchmarking easy.

**Comment by szhorvat** [comment]
I don't have a strong opinion on this. 

I think that out-of-memory errors are rare, and very difficult to guard against anyway. As @ntamas noted recently, in Linux `malloc()` may not even return 0 when there is not enough memory due to the kernel overcommitting. Then when you actually try to use that memory, the program crashes. So it would seem that our efforts to catch all OOM situations are in vain ... Thus, in my opinion, leaving these functions as they are, and effectively ignoring OOM conditions, is not a big deal.

However, there would not be a huge usability cost to making _both_ lazy and non-lazy `get()` functions return an error code, so why not?

**Comment by ntamas** [comment]
My two cents: I'd leave them as is:

1. Adding error codes to the non-lazy variants just to make them consistent with the lazy variants seems moot if the non-lazy variants cannot fail.
2. As you pointed out, the only way the lazy variant can fail is due to an out-of-memory condition, and these are hard to protect against anyway. It's not only Linux that overcommits memory; [macOS does that](https://stackoverflow.com/a/41402958/156771) as well. Windows does not overcommit memory as far as I know, but it will happily let you allocate large chunks of memory as long as there's enough hard drive space to use as swap space, and that's almost like allowing overcommit :)
3. We might do away with the explicit adjacency list representation in the future if we can finally start experimenting with more efficient graph representations.
4. We can always provide a `_get_safe()` function that uses a return code if the user wishes to be super pedantic about out-of-memory conditions.

**Comment by szhorvat** [comment]
> 4\. We can always provide a `_get_safe()` function that uses a return code if the user wishes to be super pedantic about out-of-memory conditions.

They can already be pedantic: just check if the return is `NULL`. We are sloppy and don't do this in the internal code, though.

----

I agree with your overall assessment @ntamas .

**Comment by szhorvat** [comment]
I removed the `igraph_error()` calls from these functions. The error check should be done on the return value of `lazy_adjlist/inclist_get()`.

f335e15eefc2515182928c294f85727559759753

**Comment by ntamas** [comment]
Okay, so what should be the proper way of doing this in our internal code? Shall we simply call `IGRAPH_ASSERT(return_value != NULL)`?

(And for what it's worth, I was wondeirng whether we should wrap the condition in `IGRAPH_UNLIKELY` in the definition of `IGRAPH_ASSERT` to let the compiler optimize for the common code path).

**Comment by szhorvat** [comment]
I haven't gotten around to it yet, but my plan was to treat these functions as we do with memory allocation functions. Just check if the return value is `NULL`, and if so, report an `IGRAPH_ENOMEM`. The advantage is that it'll still be easy to switch between the lazy and non-lazy versions: if we switch from lazy to non-lazy and retain that `NULL`-check, it won't be a problem.

I wanted to use the `IGRAPH_CHECK_ALLOC` macro proposed here: https://github.com/igraph/igraph/issues/2030

(Note: Let's leave the CALLOC_CHECK for later and skip the REALLOC_CHECK. It doesn't do much good to refactor things to us this now.)

**Comment by szhorvat** [comment]
We should not use `IGRAPH_ASSERT` for expected errors. A memory allocation failure is an expected error. `IGRAPH_ASSERT` should only trigger when there is a bug in the program: it's mostly for checking preconditions.

**Comment by szhorvat** [comment]
> (And for what it's worth, I was wondeirng whether we should wrap the condition in `IGRAPH_UNLIKELY` in the definition of `IGRAPH_ASSERT` to let the compiler optimize for the common code path).

Done.

**Comment by ntamas** [comment]
I ended up adding an `IGRAPH_CHECK_OOM(ptr, message)` macro for checking nullity of pointers after a memory allocation. Currently it is used only after `igraph_lazy_inclist_get()` and `igraph_lazy_adjlist_get()`. Feel free to rename or refactor if you don't like it :)
