### ISSUE TITLE
Containers: element retrieval methods are inconsistent

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1958]
Element retrieval methods are inconsistent between containers (vector, vector_ptr, vector_list, strvector).

There are two kinds of element retrieval methods, those that return values and those that return pointers. Here's a summary:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/1212871/153620774-6388dc47-289f-448a-9e45-b93f2170a9eb.png">

Suggestion:

 - Make namings consistent: either `e()` or `get()`, but not a mix. I vote for `get()`.
 - `strvector_get()` should use the return value instead of output argument.

**Comment by ntamas** [comment]
`_e()` and `_e_ptr()` have been renamed to `_get()` and `_get_ptr()` for vectors and matrices in d6193366d

**Comment by ntamas** [comment]
These are now implemented in d619336, 8dc43e1 and 2710617
