### ISSUE TITLE
Containers: push/pop methods are inconsistent

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1959]
Push/pop methods are inconsistent between containers (vector, vector_ptr, vector_list, strvector). Here's a summary:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/1212871/153621182-8175f1a0-1c19-408e-99ec-4adc98fd05b8.png">

Suggestions for changes:

 - strvector should use `push_back()` instead of `add()`
 - strvector should get a `pop_back()` method
 - `pop_back()` should be documented for `vector_ptr()`
 - In `vector_list`, `pop_back()` should use the return value instead of an output argument. This method cannot fail in any _unexpected_ way. The only possibility for failure is when the list is empty, and we try to pop an element. This should be a fatal error handled through `IGRAPH_ASSERT()`. Normally, we only need to use `IGRAPH_ERROR()` for errors which (1) can be triggered by the end user of a high-level interface, or (2) cannot be predicted, such as out-of-memory. In those cases, we want to report a user-friendly error. Calling `vector_list_pop_back()` on an empty list is a different kind of error: it is a programming error in C which should simply be fixed. It is the same kind of error as first destroying a vector then trying to access it again. That's also protected by an assertion, not by an `IGRAPH_ERROR()`.

**Comment by ntamas** [comment]
Commit 384f12274 changed `igraph_vector_list_pop_back()` to use its return value instead of an output argument. This was the last missing piece so closing.
