### ISSUE TITLE
Swap method is inconsistent between vector and vector_list

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1960]
For `vector`, the method that swaps two elements is called `swap_elements()`. The method that swaps two vectors is called `swap()`, but is is badly implemented (O(n) complexity instead of O(1) and requires vectors to have the same lengths).

For `vector_list`, the method that swaps two elements is called `swap()`. There is no method to swap two vector lists.

Suggestion:

 - The naming should be made consistent between `vector` and `vector_list`
 - The current `vector_swap()` function should either be removed (it's never used, performs badly, and is unnecessarily restrictive), or it should be made O(1) and should be provided both for `vector` and `vector_list`.

**Comment by ntamas** [comment]
Fixed in f9152e9
