### ISSUE TITLE
community/label_propagation.c stops even if there is a vertex violating the goal condition 

### ISSUE THREAD

**Issue by Katterrina** [igraph/igraph#1963]
According to the original paper [1] describing the label propagation algorithm (the paper is also mentioned in label_propagation.c comment), the iterative process of label propagation is performed until _every node in the network has a label to which the maximum number of its neighbors belongs_, but the implementation [label_propagation.c ](https://github.com/igraph/igraph/blob/master/src/community/label_propagation.c) sometimes stops even if there is a vertex which has a different label than the maximum number of its neighbors.

If I understand it correctly, the problem is on lines 294-301 in the code, especially in the condition `if (VECTOR(label_counters)[(long)VECTOR(*membership)[v1]] != max_count)`. There is an example of wrong behavior:

Let's have a triangle graph with vertices A, B, and C. A and C have "red" labels, B has a different "green" label.

![1](https://user-images.githubusercontent.com/31630249/153744834-b543a731-9b46-46b5-a33c-e2ddf9e6340b.png)

The currently processed vertex is A (`v1` on line 240). The number of green and red neighbors is the same. The condition `if (VECTOR(label_counters)[(long)VECTOR(*membership)[v1]] != max_count)` is false, because the number of neighbors with the same label as A (red) is equal to the maximum number of its neighbors with one label (both is 1), so `running` stays 0. The new label is chosen randomly because the number of green and red neighbors is the same. Let's say that green was chosen.

![2](https://user-images.githubusercontent.com/31630249/153744832-fcc9e932-b988-4f1d-a1b3-77baffd732e5.png)

Now, the currently processed vertex is B. The number of green and red neighbors is the same, so it works the same as for A. `running` stays 0, the new label is chosen randomly, let's say that red was chosen.

![3](https://user-images.githubusercontent.com/31630249/153744831-989f21b0-34e9-4cab-bcc2-ef6d9a70c7b0.png)

Now, the currently processed vertex is C. The number of green and red neighbors is the same again. `running` stays 0 again and the new label is chosen randomly. In the end, there are two vertices with the same labels and one vertex with another label. The problem is, that the iteration through all vertices (line 239) is done and `running==0`, so the function finishes, but there is a vertex that does not have a label to which the maximum number of its neighbors belongs.

In a pseudo-code of the algorithm in the original paper, the control if every node in the network has a label to which the maximum number of its neighbors belongs is performed in step (v), after the relabeling in step (iv). Here, these two steps are merged together.

**To reproduce**

```python
import igraph as ig

# 300 was enough for me to see the problem several times, but since the algorithm is randomized, so it might be necessary to run it more times
for i in range(300):     
    G = ig.Graph()
    G.add_vertices(3)
    G.add_edges([(0,1),(1,2),(2,0)])
    
    partition = G.community_label_propagation()
    ig.plot(partition, "labelprop"+str(i)+".png") 
```

**Version information**
I am using igraph 0.9.9 running inside Python 3.8.10 (default, Nov 26 2021, 20:14:08), but I think that this is a problem in the algorithm in C code, not in Python interface, that  is the reason why I am not opening an issue in igraph/python-igraph.

The line numbers I am referring to are from commit fb5b8bed7133d53ff1ce4e5033206cf4d4f2a80b.

[1]  Raghavan, U.N. and Albert, R. and Kumara, S.: Near linear time algorithm to detect community structures in large-scale networks. Phys Rev E 76, 036106. (2007). <https://doi.org/10.1103/PhysRevE.76.036106>

**Comment by iosonofabio** [comment]
Thanks for reporting. Are you willing to make a PR for this?

**Comment by Katterrina** [comment]
I can try it.

**Comment by szhorvat** [comment]
If you do, please work on the `develop` branch, not `master`. We can later backport the fix to `master` if that becomes necessary.

**Comment by ntamas** [comment]
Thank you @Katterrina , nice find! Let us know if you need help with the PR.

**Comment by Katterrina** [comment]
Thank you @szhorvat for the tutorial link, I went through it and it helped a lot. I can compile, run and test the code now.
