### ISSUE TITLE
Assertion failure in igraph_add_edges()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1970]
**Describe the bug**

There may be an assertion failure in `igraph_add_edges()` when `igraph_i_attribute_add_edges()` fails. Specifically, it happens when using an error handler that returns and an error occurs on this line:

https://github.com/igraph/igraph/blob/master/src/graph/type_indexededgelist.c#L313

This was found by OSS-fuzz, and is triggered when reading a GraphML file that has one attribute specified twice with different types.

It's unclear to me if this is ultimately a bug in the GraphML reader, the attribute handler, or `igraph_add_edges()` itself. It seem to me that it is the latter.

**To reproduce**

Use this C code to read the included GraphML file.

C code:

```c
#include <igraph.h>

int main(int argc, char *argv[]) {
    if (argc != 2)
        return 1;

    igraph_set_attribute_table(&igraph_cattribute_table);

    igraph_set_error_handler(igraph_error_handler_printignore);

    FILE *file;
    file = fopen(argv[1], "r");
    if (! file) {
        fprintf(stderr, "Failed to open file.");
        return 2;
    }

    igraph_t graph;
    igraph_error_t err = igraph_read_graph_graphml(&graph, file, 0);
    
    fclose(file);

    if (err != IGRAPH_SUCCESS) {
        fprintf(stderr, "Failed read.");
        return 3;
    }

    igraph_write_graph_graphml(&graph, stdout, 1);

    igraph_destroy(&graph);

    return 0;
}
```

GraphML file, as generated by OSS-fuzz:

```xml
<graphml><key id="" for="e" attr.type="d"/><key id="" for="e" attr.type=""></key><graph></graph></graphml>
```

Here's a "less invalid" GraphML input, which also has duplicate attributes of different types:

```xml
<graphml><key id="one" for="edge" attr.type="double"/><key id="one" for="edge" attr.type="string"></key><graph></graph></graphml>
```

If using an error handler that aborts, the output is (with address sanitizer for stack trace):

```
Error at src/graph/cattributes.c:1757 : Attribute types do not match - Invalid value.

Stack trace:
    #0 0x11038c467 in __sanitizer_print_stack_trace (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x6b467)
    #1 0x10ff4161a in igraph_abort error.c:69
    #2 0x10ff405b9 in igraph_error_handler_abort error.c:199
    #3 0x10ff40502 in igraph_error error.c:172
    #4 0x10ffc119d in igraph_i_cattribute_add_edges cattributes.c:1757
    #5 0x10ffb528d in igraph_i_attribute_add_edges attributes.c:97
    #6 0x10fff6d86 in igraph_add_edges type_indexededgelist.c:284
    #7 0x11000d688 in igraph_i_graphml_parser_state_finish_parsing graphml.c:526
    #8 0x11000947a in igraph_read_graph_graphml graphml.c:1501
    #9 0x10ff40240 in main read.c:18
    #10 0x7fff70e863d4 in start (libdyld.dylib:x86_64+0x163d4)
```

If the error handler returns, as in the above example, then:

```
Error at src/graph/cattributes.c:1757 : Attribute types do not match - Invalid value.
Fatal error at src/core/vector.c:1181 : Assertion failed: v->stor_begin != NULL

Stack trace:
    #0 0x1080d1467 in __sanitizer_print_stack_trace (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x6b467)
    #1 0x107c9061a in igraph_abort error.c:69
    #2 0x107c90558 in igraph_fatal_handler_abort error.c:360
    #3 0x107c905a9 in igraph_fatal error.c:369
    #4 0x107ca5b9c in igraph_vector_int_resize vector.pmt:1181
    #5 0x107d45dc6 in igraph_add_edges type_indexededgelist.c:287
    #6 0x107d5c688 in igraph_i_graphml_parser_state_finish_parsing graphml.c:526
    #7 0x107d5847a in igraph_read_graph_graphml graphml.c:1501
    #8 0x107c8f240 in main read.c:18
    #9 0x7fff70e863d4 in start (libdyld.dylib:x86_64+0x163d4)
```

**Version information**

Current `develop`.

**Comment by szhorvat** [comment]
I think the entire error handling concept in `igraph_add_edges()` is broken.

It tries to set the error handler to `igraph_error_handler_ignore()` temporarily, and then clean things up manually in an attempt to keep the graph in a consistent state. However, the graph itself may already be placed on the finally stack (to be destroyed). Even `igraph_error_handler_ignore()` will execute the destructor on the finally stack, not to mention that in some locations in `igraph_add_edges()` we switch back to the original error handler, which will definitely execute destructors. Thus the cleanup attempt may fail, as it tries to operate on an already destroyed graph.  This is precisely what seems to happen here.

**Comment by szhorvat** [comment]
This is a tough nut. I can’t come up with any solution that doesn’t have serious disadvantages or is not very complicated.

----

This again shows that we’d be much better off using proven error handling solutions such as C++ exceptions instead of inventing our own and then discovering all the things that are wrong with it.

One important difference between exceptions and igraph’s error handling is that exceptions can be caught and handled at any level. Destructors are only called up to the point where the exception is caught, not further up the call stack. So in a situation like this one here, we could catch the exception, restore the graph into a consistent state, then re-throw it.

In contrast to how exceptions work, igraph will call `FINALLY_FREE()` at the point where the error occurred, and this will potentially destroy data structures that would be used by functions up the call stack. At some point, when working with the GraphML reader, which uses callbacks, @ntamas even suggested that we might have to consider two error stacks: one before a call boundary (e.g. callbacks) and one after. This is so that some cleanup can be done inbetween the two. This is very similar to the situation we face here. Exceptions would make it easy to introduce such a boundary anywhere by just adding a `catch`.

Of course, we cannot use exceptions because we are using C, not C++. But we should seriously discuss moving to a subset of C++ at some point in the future (e.g. for a 2.0 release), not just because of this, but also several other badly re-invented things (looking at type-generic vectors).

**Comment by GroteGnoom** [comment]
> Of course, we cannot use exceptions because we are using C, not C++. But we should seriously discuss moving to a subset of C++ at some point in the future (e.g. for a 2.0 release), not just because of this, but also several other badly re-invented things (looking at type-generic vectors).

Maybe it wouldn't even be that hard, I think a lot of our code already compiles with a C++ compiler. We could have a gradual transition from `C` to `the intersection of C and C++` to `C++`

**Comment by szhorvat** [comment]
I think a proper solution to this problem will involve changing igraph's error handling somewhat. Here's a rough idea of how to do that with not too many changes:

Right now, destructors are pushed to the "finally stack", and they are executed directly from the error handler (the error handler typically calls `IGRAPH_FINALLY_FREE()`). The R interface relies on this way of calling destructors: its error handler effectively does a `longjmp` back to R instead of returning (like in Python and Mathematica). First, this would need to be changed: it should be mandatory for error handlers to return if proper resource cleanup is desired.

If that is ensured, then we can delay some of the cleanup by effectively inserting "barriers" into the finally stack, which will correspond to the positions of a rudimentary analog of a try/catch block. In practice, this would be implemented by annotating every destructor on the finally stack with a "level index". The imaginary barrier exists between different levels.

Then we can have an extended version of `IGRAPH_CHECK`, to be used when a boundary needs to be established. This will be an analog of try/catch. Let's call it `IGRAPH_TRY_CATCH`. It will increment the level index before calling a function, and will decrement it when done.

`IGRAPH_FINALLY_FREE()` will only execute destructors at the current (highest) level, and then stop. This means that only those destructors will be executed which were registered within the innermost `IGRAPH_TRY_CATCH` call. When execution returns to that `IGRAPH_TRY_CATCH` we have a chance to do some special manual cleanup (the "catch" code) before the level is decremented, so the execution of destructors can continue. Just like `IGRAPH_CHECK`, `IGRAPH_TRY_CATCH` will finish by calling `IGRAPH_ERROR` internally, which triggers additional calls to `IGRAPH_FINALLY_FREE()` and lets the destruction proceed.

----

This would require relatively few changes to the codebase. We could keep `IGRAPH_CHECK` almost everywhere. We only need the special `IGRAPH_TRY_CATCH` when the part of the finally stack needs to be isolated, such as in the fix for this issue, as well as for functions that use callbacks. We will only need to update some of the error handling code, and we'll need to change how R's error handler works.

----

After writing this up, I found the link to the the inspiration for igraph's error handling:

https://ldeniau.web.cern.ch/ldeniau/html/oopc/oopc.html#Exceptions

I have not read this yet, but we must look at it carefully before proceeding.
