### ISSUE TITLE
Error handling is disabled for part of community_leading_eigenvector()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1973]
`community_leading_eigenvector()` disables error handling for one call to `igraph_arpack_rssolve()`:

https://github.com/igraph/igraph/blob/master/src/community/leading_eigenvector.c#L701

According to the comment, this is done because ARPACK may fail depending on the starting point. However, all errors are indiscriminately discarded, whether they are a convergence failure or a memory allocation problem.

This behaviour was added here:

https://github.com/igraph/igraph/commit/4b646b2c1c7d8e557d7c56ace8a97f4fc74ae572

It is meant to fix this issue:

https://bugs.launchpad.net/igraph/+bug/1002140

Tasks for this issue:

 - [ ] Is this still a problem with recent ARPACK versions? What about the vendored ARPACK?
 - [ ] If this hack needs to be kept, do not discard errors indiscriminately. Distinguish between convergence failure and other errors.

**Comment by vtraag** [comment]
Note that this is also related to https://github.com/igraph/igraph/issues/1929 which discusses whether the approach taken in https://github.com/igraph/igraph/commit/4b646b2c1c7d8e557d7c56ace8a97f4fc74ae572 makes sense.

**Comment by ntamas** [comment]
I'm taking care of this; I'll whitelist `IGRAPH_ARPACK_MAXIT` and `IGRAPH_ARPACK_NOSHIFT` and handle the rest as proper errors.

**Comment by szhorvat** [comment]
@ntamas Anything else to do here? If not, please close.
