### ISSUE TITLE
Failure upon modification must not corrupt data structures

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1976]
Data structures must not get corrupted when an error occurs during their modification (e.g. out of memory).

This is especially important for `igraph_t`, as it is directly exposed in high-level interfaces, but we should also ensure it for other data structures. PR #1972 includes changes to make this work safely for adding edges to a graph. This issue is to check / ensure that failures during modification don't corrupt any of the other data structures either. If you have verified this for one data structure, check the box below.

 - [x] `igraph_t` (add/remove edges/vertices)
 - [ ] Attribute handlers in C, Python, R
    * [ ] #1999
    * [ ] https://github.com/igraph/python-igraph/issues/521
    * [ ] https://github.com/igraph/rigraph/issues/514
 - [x] `vector_t`
 - [x] `vector_list_t`
 - [x] `strvector_t`
 - [x] adjlist / inclist (both lazy and standard)
 - [x] `stack_t`
 - [x] `dqueue_t`
 - [x] `trie_t`

Above I only included the most common data structures. I expect that most of them are fine as they are. The priorities are:

 - Check all `igraph_t` modification functions
 - Check attribute handlers, e.g. that the length of the attribute vectors stays consistent. I am not sure that these are fine. We need to check all three attribute handler implementations.

**Comment by ntamas** [comment]
So I've also checked the vertex/edge addition/removal in `igraph_t` and I think we are okay in almost all places _but_ edge removal.

Vertex and edge addition were sorted out earlier. Vertex removal essentially constructs a new graph behind the scenes and then moves the vectors of the newly constructed graph back to the original graph so that one works as well. The only problematic part is the edge removal because of this line:

```c
    IGRAPH_CHECK(igraph_vector_int_pair_order(&newto, &newfrom, &graph->ii, no_of_nodes));
```

Here we are modifying `graph->ii` before we have reached the point of no-failures-possible-from-here-on. If any of the later operations fails, we are left with a graph where `graph->ii` is inconsistent. I'd appreciate a second pair of eyes here to make sure I'm not missing something.

**Comment by ntamas** [comment]
Here's a proposal for a patch that treats `graph->ii` in the same way as `graph->oi` (i.e. not modified in-place):

```patch
diff --git a/src/graph/type_indexededgelist.c b/src/graph/type_indexededgelist.c
index 650f35a52..fdf3fce3e 100644
--- a/src/graph/type_indexededgelist.c
+++ b/src/graph/type_indexededgelist.c
@@ -407,7 +407,7 @@ igraph_error_t igraph_delete_edges(igraph_t *graph, igraph_es_t edges) {
     igraph_eit_t eit;

     igraph_vector_int_t newfrom, newto;
-    igraph_vector_int_t newoi;
+    igraph_vector_int_t newoi, newii;

     igraph_bool_t *mark;
     igraph_integer_t i, j;
@@ -448,8 +448,9 @@ igraph_error_t igraph_delete_edges(igraph_t *graph, igraph_es_t edges) {

     /* Create index, this might require additional memory */
     IGRAPH_VECTOR_INT_INIT_FINALLY(&newoi, remaining_edges);
+    IGRAPH_VECTOR_INT_INIT_FINALLY(&newii, remaining_edges);
     IGRAPH_CHECK(igraph_vector_int_pair_order(&newfrom, &newto, &newoi, no_of_nodes));
-    IGRAPH_CHECK(igraph_vector_int_pair_order(&newto, &newfrom, &graph->ii, no_of_nodes));
+    IGRAPH_CHECK(igraph_vector_int_pair_order(&newto, &newfrom, &newii, no_of_nodes));

     /* Edge attributes, we need an index that gives the IDs of the
        original edges for every new edge.
@@ -471,10 +472,12 @@ igraph_error_t igraph_delete_edges(igraph_t *graph, igraph_es_t edges) {
     igraph_vector_int_destroy(&graph->from);
     igraph_vector_int_destroy(&graph->to);
     igraph_vector_int_destroy(&graph->oi);
+    igraph_vector_int_destroy(&graph->ii);
     graph->from = newfrom;
     graph->to = newto;
     graph->oi = newoi;
-    IGRAPH_FINALLY_CLEAN(3);
+    graph->ii = newii;
+    IGRAPH_FINALLY_CLEAN(4);

     IGRAPH_FREE(mark);
     IGRAPH_FINALLY_CLEAN(1);
```

**Comment by szhorvat** [comment]
Makes sense to me. Relative slowdown probably won't be too large.

**Comment by ntamas** [comment]
I checked `trie_t` carefully and it seemed okay to me.
