### ISSUE TITLE
weighted_adjacency() should work without attribute handler

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1978]
`igraph_weighted_adjacency()` requires an attribute handler. Almost all other igraph functions will work without an attribute handler, and I think this one should too. igraph aims to be simpler to use than other graph libraries, even from C, and a beginner should not need to bother with learning the attribute handling interface.

I propose a function which stores the weights in a separate vector that does not need to be an attribute. We can either have only one such function, or we can keep the current function and add an extra one that returns the weights in a vector.

This is a very easy change. I only need feedback before I proceed with it.

**Comment by GroteGnoom** [comment]
Fixed in #2067
