### ISSUE TITLE
Remove igraph_dnorm()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1980]
As far as I can tell, the _public_ function `igraph_dnorm()` is never used in the codebase, not even in the R interface. It is also strongly tied to R, notice this in `igraph_random.h`:

```
#ifdef USING_R

double Rf_dnorm4(double x, double mu, double sigma, int give_log);
#define igraph_dnorm Rf_dnorm4
```

Is there any reason to keep this function, or can we remove it for 0.10?

**Comment by ntamas** [comment]
I'll remove it from 0.10.
