### ISSUE TITLE
Random number generators should be moved to their own files

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1984]
We have now three implementations of random number generators all in `random.c`. Each of these should be moved to their own files for readability. `random.c` is difficult to navigate and too crowded as it is.

There should be no performance impact from preventing inlining because the relevant functions are always invoked through function pointers (hope I'm right).

**Comment by szhorvat** [comment]
I needed to move the default RNG to the file containing MT19937 as well. This is ugly, but I can't find a workaround, similar to how I can't make the default RNG thread-local without having some init function that is run on igraph startup.

**Comment by vtraag** [comment]
> similar to how I can't make the default RNG thread-local without having some init function that is run on igraph startup.

Why is this necessary? For C users, it certainly wouldn't come as a surprise that they'd have to initialize a RNG, right?

**Comment by szhorvat** [comment]
Well, right now igraph works without explicitly initializing the RNG. The `rand()` function from the standard C library also works without initialization. 

Seeding is of course recommended, but we are talking about a hard requirement on initialization, not merely seeding. Many "deterministic" functions still use the RNG in some hidden way, e.g. eigenvector centrality. If these failed with  crash for lack of initialization, that would at least be surprising.

I am not against adding a requirement for library initialization, but I think it would make igraph harder to use.

**Comment by vtraag** [comment]
Sure, fair enough.
