### ISSUE TITLE
Banish (long int) from random number generator interface

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1986]
We should eliminate `long int` from the igraph codebase as much as possible, including from the RNG interface. The size of `long int` is unpredictable and differs across platforms. If we want to use 32-bit integers in the RNG interface, we should use an explicitly 32-bit type.

(Using `long int` in specific RNG implementations may stay if necessary to ensure unchanged behaviour, but it should be banished from the general interface.)

**Comment by ntamas** [comment]
This is now done in the `feat/rng-refactoring` branch, which I'l submit for a round of reviews as a PR soon(ish).
