### ISSUE TITLE
Proposal for refactoring the RNG interface

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1988]
Here is a concrete proposal for refactoring the RNG interface, aiming for simplicity instead of for flexibility.

Currently, we have this low-level interface:

```c
typedef struct igraph_rng_type_t {
    const char *name;
    unsigned long int min; /* 'min' must always be set to 0 */
    unsigned long int max;
    igraph_error_t (*init)(void **state);
    void (*destroy)(void *state);
    igraph_error_t (*seed)(void *state, unsigned long int seed);
    unsigned long int (*get)(void *state);
    igraph_real_t (*get_real)(void *state);
    igraph_real_t (*get_norm)(void *state);
    igraph_real_t (*get_geom)(void *state, igraph_real_t p);
    igraph_real_t (*get_binom)(void *state, long int n, igraph_real_t p);
    igraph_real_t (*get_exp)(void *state, igraph_real_t rate);
    igraph_real_t (*get_gamma)(void *state, igraph_real_t shape,
                               igraph_real_t scale);
} igraph_rng_type_t;
```

This would be changed like so:

```c
typedef struct igraph_rng_type_t {
    const char *name;

    /* No minimum or maximum. Minimum is always 0, maximum is always 2^31-1. */

    /* Init and destroy */
    igraph_error_t (*init)(void **state);
    void (*destroy)(void *state);

    igraph_error_t (*seed)(void *state, unsigned long int seed);

    /* Fundamental generators: at least one of these two MUST be provided */
    int31_t (*get)(void *state); /* returns 32-bit signed integer */
    igraph_real_t (*get_real)(void *state);

    /* Optional generators: */
    igraph_real_t (*get_norm)(void *state);
    igraph_real_t (*get_geom)(void *state, igraph_real_t p);
    igraph_real_t (*get_binom)(void *state, long int n, igraph_real_t p);
    igraph_real_t (*get_exp)(void *state, igraph_real_t rate);
    igraph_real_t (*get_gamma)(void *state, igraph_real_t shape, igraph_real_t scale);
    igraph_real_t (*get_pois)(void *state, igraph_real_t lambda); /* newly added Poisson generator */
} igraph_rng_type_t;
```

Principles:

 - Either an integer or a real generator must be provided.
 - The integer one must produce non-negative 32-bit signed integers, i.e. 31 random bits. 
 - Therefore, there is no need for `min` and `max` methods as these are always 0 and `2^31 - 1`.

Mid-level interface:

 - `igraph_rng_get_int31()` will return the result of `igraph_rng_type_t::get()`, if `get()` was provided. If not, it is implemented in terms of `igraph_rng_type_t::get_real()`. We can think of this function as returning the native integer type of the RNG.
 - `igraph_rng_get_real()` will return the result of `igraph_rng_type_t::get_real()`, if `get_real()` was provided. If not, it is implemented in terms of _two_ calls to `igraph_rng_type_t::get()`, so that we can have a sufficient number of random bits.
 - `igraph_rng_get_integer(rng, l, h)` will return an `igraph_integer_t` between `l` and `h`. It will be implemented in terms of one or two calls to `igraph_rng_get_int31()`, depending on whether `h-l` is representable on 31 bits or not. 

    In the very rare case that the `h-l` difference requires more than 62 bits, we use three calls to `igraph_rng_get_int31()`. This is the simplest solution, simpler than not supporting this case (which I originally wanted) because `igraph_rng_get_integer()` has no means of reporting errors.

High-level interface:

 - All other `igraph_rng_get_` functions will be implemented in terms o f`igraph_rng_get_real()`, unless they are explicitly provided within `igraph_rng_type_t`. This is already the case.
 -  All other `igraph_rng_get_` functions will return NaN if their input is invalid (e.g. out-of-range parameters). This is already what they do, but this is not documented.

----

This proposal aims for simplicity rather than flexibility. We can produce an alternative proposal which supports RNGs that produce an arbitrary number of bits.

**Comment by szhorvat** [comment]
If we go with a solution like this, prioritizing simplicity above everything, I am not sure if we have a good reason to use 31-bit (signed) instead of 32-bit (unsigned) as the native type.

**Comment by ntamas** [comment]
`seed()` will also have to be optional. I think that in practice we will never call `seed()` from inside igraph because it would be bad practice to mess around with the state of the RNG behind the scenes. The R interface currently leaves `seed()` unimplemented (it returns an error code), and I don't know whether it's because getting access to the R RNG seed is complicated or because there was simply not enough time to implement it. The Python interface does not support it, although in theory it could be implemented.

We do call `seed()` from tests, though, so we cannot leave it unimplemented for the default RNG.

What shall we do with `igraph_rngtype_glibc2` and `igraph_rngtype_rand`? Shall we simply remove them?

**Comment by ntamas** [comment]
Also:

* I'd propose moving the Mersenne Twister _implementation_ to a separate file in `src/random` to separate RNG _interface_ and its related functions in `src/random/random.c` from concrete implementations.

* Maybe it's time to look around and see what other PRNGs are out there that might be worth implementing to boost RNG performance? I've heard that MT19937 has a very long period and is slow compared to more modern PRNGs, so if you don't absolutely need a long period, you might be better off using something else. Starting point: https://www.wikiwand.com/en/List_of_random_number_generators

**Comment by ntamas** [comment]
`feat/rng-refactoring` branch is soon ready for review and all these points are taken care of there.
