### ISSUE TITLE
RNG_INTEGER() returns a result outside of the requested bounds

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1989]
**Describe the bug**

`RNG_INTEGER(-5, -5)` returns -4 in some cases. According to the documentation, the lower and upper bounds are allowed to be equal.

**To reproduce**

Test is already added, fails here:

https://github.com/igraph/igraph/blob/develop/tests/unit/random_sampling.c#L22

**Version information**

Current `develop`.

**Comment by szhorvat** [comment]
This happens because of how rounding works when casting a real to an integer.

The integer is generated as `(r * (h - l + 1) + l)` where `r` is a random real in `[0, 1)`. Then it is cast to an integer.

The result would be correct through rounding down. But that's not what happens during casting. Effectively, the part after the decimal point is discarded. So `4.2` converts to `4` but `-4.2` converts to `-4` and not `-5` (which would be required for a correct result).

https://github.com/igraph/igraph/blob/master/src/random/random.c#L685

I need to leave now. If anyone else wants to fix it go ahead. Not sure about the performance impact of `floor()` ...

**Comment by vtraag** [comment]
Just noting this reference here that might be useful: https://arxiv.org/abs/1805.10941.

**Comment by szhorvat** [comment]
I went with `floor()` for now, just to fix this, even though `floor()` is supposed to be quite slow.

It turns out that this fix to the random integer generation affected several other tests, whose output needed to be updated. Now the `igraph_arpack_rnsolve` is unstable and producing different output depending details just as internal/external ARPACK or SSE vs x87 math ...

I'd appreciate some help with this.

**Comment by szhorvat** [comment]
It could be. But in the end, we cannot rely on simply casting a floating point value to an integer. We need to be explicit that we want a "floor" operation.

**Comment by vtraag** [comment]
Might it be easier (and faster) to first create the random integer in the interval [0, h - l] using casting and then add l to the integer to arrive at [l, h]?

**Comment by szhorvat** [comment]
One possibility is this:

```
long int fast_floor(double x) { long int z = x; return z - (z > x); }
```

This is from https://stackoverflow.com/a/15341154/695132 and relies on the fact that casting to an integer rounds _towards_ zero. I am not 100% sure that this is a behaviour mandated by the standard.

[Here are some more comments](https://stackoverflow.com/a/41560586), claiming that even this is not ideal because the conditional tends to kill performance. But this probably does not matter, as our random functions are already pretty slow. Even `floor()` may not matter.

**Comment by szhorvat** [comment]
Yes, rounding towards zero is mandated by the standard, see on this page:

https://en.cppreference.com/w/cpp/numeric/fenv/FE_round

> The current rounding mode does NOT affect the following:
>
> *  floating-point to integer implicit conversion and casts (**always towards zero**)

**Comment by vtraag** [comment]
So we could then simply do 
```c
(long int)(type->get_real(rng->state) * (h - l + 1)) + l;
```
instead of 
```c
floor(type->get_real(rng->state) * (h - l + 1) + l);
```
right?

**Comment by szhorvat** [comment]
> Might it be easier (and faster) to first create the random integer in the interval [0, h - l] using casting and then add l to the integer to arrive at [l, h]?

I'm sorry, I wasn't paying attention. That is a good idea. Feel free to go ahead with it!

**Comment by szhorvat** [comment]
But first we should think a bit about risks of overflows ...

**Comment by szhorvat** [comment]
Overflow issues can be fixed after we rewrite the RNG code according to some of the proposals I made in the issues opened today. For 0.9 this should be fine.

**Comment by vtraag** [comment]
Yes, let's do that indeed.

It might still be worth looking into the fast RNG for integers that I referenced, see also implementation at https://github.com/lemire/FastShuffleExperiments. Shall I open a separate issue for that?

**Comment by vtraag** [comment]
When tests pass on the CI, I'll backport to the `master` branch.

**Comment by szhorvat** [comment]
I'd say this should be part of https://github.com/igraph/igraph/issues/1987
