### ISSUE TITLE
Crash when reading invalid GraphML

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1992]
**Describe the bug**

`igraph_read_graph_graphml()` crashes when reading the attached invalid GraphML file. The crash happens in the ICU library, called from libxml2, which in turn is called from igraph. I am unsure where the bug is (igraph, libxml2 or ICU). However, the following libxml2 example program crashes as well, which suggests that it is either libxml2 or ICU: 

http://www.xmlsoft.org/examples/#parse1.c

This problem was found by OSS-fuzz: https://oss-fuzz.com/testcase-detail/4973533330014208

[icu.graphml.zip](https://github.com/igraph/igraph/files/8197559/icu.graphml.zip)

**To reproduce**

This is a C++ program:

```C++
#include "igraph.h"
#include <cstdlib>
#include <cstdio>

int main(int argc, char *argv[]) {

    if (argc != 2) {
        fprintf(stderr, "One argument expected!\n");
        exit(1);
    }

    igraph_set_error_handler(igraph_error_handler_printignore);

    // Turn on attribute handling
    igraph_set_attribute_table(&igraph_cattribute_table);

    // Read input file
    FILE *ifile;
    ifile = fopen(argv[1], "r");

    igraph_t g;
    if (igraph_read_graph_graphml(&g, ifile, 0) == IGRAPH_SUCCESS) {
        igraph_write_graph_graphml(&g, stdout, 0);
        igraph_destroy(&g);
    }

    // no need to call igraph_destroy() if igraph_read_graph_graphml() returns an
    // error code as we don't have a valid graph object in that case

    fclose(ifile);

    return 0;
}
```

Stack trace:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==24503==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x0001034ed9c9 bp 0x7ffeedca2ba0 sp 0x7ffeedca2b70 T0)
==24503==The signal is caused by a READ memory access.
==24503==Hint: address points to the zero page.
    #0 0x1034ed9c9 in ucnv_MBCSSimpleGetNextUChar_67+0x2c (libicuuc.67.dylib:x86_64+0x209c9)
    #1 0x1034f4ac1 in UConverter_toUnicode_ISO_2022_CN_OFFSETS_LOGIC(UConverterToUnicodeArgs*, UErrorCode*)+0x2f4 (libicuuc.67.dylib:x86_64+0x27ac1)
    #2 0x1034db21c in _toUnicodeWithCallback(UConverterToUnicodeArgs*, UErrorCode*)+0x1ae (libicuuc.67.dylib:x86_64+0xe21c)
    #3 0x1034dbec7 in ucnv_convertEx_67+0x405 (libicuuc.67.dylib:x86_64+0xeec7)
    #4 0x1023ae014 in xmlUconvWrapper+0xc2 (libxml2.2.dylib:x86_64+0x8014)
    #5 0x1023acd99 in xmlEncInputChunk+0x73 (libxml2.2.dylib:x86_64+0x6d99)
    #6 0x1023acebe in xmlCharEncFirstLineInput+0x105 (libxml2.2.dylib:x86_64+0x6ebe)
    #7 0x1023b0fa0 in xmlSwitchInputEncodingInt+0x1af (libxml2.2.dylib:x86_64+0xafa0)
    #8 0x1023b0db8 in xmlSwitchToEncodingInt+0x28 (libxml2.2.dylib:x86_64+0xadb8)
    #9 0x1023bc1c9 in xmlParseEncodingDecl+0x1ea (libxml2.2.dylib:x86_64+0x161c9)
    #10 0x1023bfc83 in xmlParseXMLDecl+0x14f (libxml2.2.dylib:x86_64+0x19c83)
    #11 0x1023c17b8 in xmlParseTryOrFinish+0xaa8 (libxml2.2.dylib:x86_64+0x1b7b8)
    #12 0x1023c09ec in xmlParseChunk+0x294 (libxml2.2.dylib:x86_64+0x1a9ec)
    #13 0x1020ae9f0 in igraph_read_graph_graphml graphml.c:1449
    #14 0x101f5e170 in main xx2.cpp:50
    #15 0x7fff77dfb3d4 in start+0x0 (libdyld.dylib:x86_64+0x163d4)
```

**Version information**
Current `develop`

**Comment by ntamas** [comment]
This is not an issue with a recent version of `libxml2` (tested with 2.9.12 from Homebrew, and 2.9.13 compiled from source). It is a problem only with the ancient version of `libxml2` that ships with macOS. I'm not sure what we could do about it, but it also begs the question: what version of `libxml2` is used by OSS-fuzz if it happens there?

**Comment by ntamas** [comment]
Bug report filed upstream: https://gitlab.gnome.org/GNOME/libxml2/-/issues/350

**Comment by szhorvat** [comment]
To be accurate, this was the stack trace from my local reproducing example, hence the sloppy file name `xx2.cpp`. However, the OSS-fuzz stack trace is identical in all details that matter.

**Comment by ntamas** [comment]
Issue forwarded by `libxml2` to ICU: https://unicode-org.atlassian.net/browse/ICU-21932

**Comment by szhorvat** [comment]
Closing, since this is now out of our hands, and on OSS-fuzz we now avoid this by building our own libxml2 without ICU support.
