### ISSUE TITLE
igraph_strvector_move_interval() should return an error code?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1993]
`igraph_strvector_move_interval()` does not return an error code. I think it should, and its usages (if any) should be checked. It contains `CALLOC` that is not checked for failure.

**Comment by ntamas** [comment]
We don't seem to use that function anywhere in the codebase and its semantics is also unclear to me. It seems like it is moving a slice of the vector to another place within the same vector, but the implementation seems incomplete; it does not handle the case when the "source" and the "target" interval overlaps, and indeed the error handling is missing. I vote for removal.

For what it's worth, there is also a `move_interval()` for vectors, which does not handle overlaps, but at least this is documented. There's also `move_interval2()`, which _does_ handle overlaps, and the only difference between the two is that the former calls `memcpy()` and the latter calls `memmove()`. I strongly suspect that any reasonable implementation of `memmove()` would just fall back to `memcpy()` in the no-overlap case so there's negligible benefit in having both versions. How about also removing `igraph_vector_move_interval2()` and just replacing `memcpy` with `memmove` in `igraph_vector_move_interval()` so it becomes usable even if the intervals overlap?

**Comment by szhorvat** [comment]
I'm fine with that.

I didn't actually look at this function in detail. I found this while trying to figure out where some of the OSS-fuzz crashes are coming from. The crashes appeared to be the result of an unchecked OOM condition (when `malloc` returns `0`). So I was looking for unchecked `IGRAPH_CALLOC`/`REALLOC`s.

**Comment by ntamas** [comment]
`igraph_strvector_move_interval()` removed, `igraph_vector_move_interval()` now handles overlaps correctly. See a39cd3206 and dd2d6d3c3
