### ISSUE TITLE
Remove igraph_transitivity_local_undirected() variants?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1994]
We have three special variants of `igraph_transitivity_local_undirected()`, numbered `1`, `2` and `4` (`3` is already removed). These are all public functions now. I believe the purpose of these is to be optimized for special use cases, such as computing the result for all instead of just some vertices.

They are already called from `igraph_transitivity_local_undirected()`, for special cases of the input.

These should either be removed from the public API, i.e. made private, (I prefer this) or they should be documented so people can decide when to use them (right now probably no one uses them because their purpose is unclear).

We need to check if these are directly used by the R or Python interfaces before removal.

**Comment by ntamas** [comment]
These were never meant to be exposed, the only valid entry point is `igraph_transitivity_local_undirected()`. Gábor was experimenting with multiple implementations and tried to gauge the performance of each of them. I'll hide the special variants in the `develop` branch. (None of these are used by the R or the Python interface).

**Comment by ntamas** [comment]
Solved by a23e20eaf
