### ISSUE TITLE
Wishlist: weighted eccentricity

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1995]
**What is the feature or improvement you would like to see?**

A weighted version of `igraph_eccentricity()`.

**Use cases for the feature**

Generally useful vertex measure. We already have an unweighted version, and internal functions which _may_ be useful for the weighted one (`igraph_i_eccentricity_dijkstra()`).

**Comment by GroteGnoom** [comment]
It's probably a good idea to wait for https://github.com/igraph/igraph/pull/1893, because it could reuse some code from src/paths/dijkstra.c

**Comment by szhorvat** [comment]
@GroteGnoom That PR was merged, want to give this a go?

**Comment by GroteGnoom** [comment]
Yes, this is probably nice to work on next 🙂
