### ISSUE TITLE
Transition int parameters to igraph_integer_t

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1998]
#### Here are some remaining cases where we might consider changing `int`s to `igraph_integer_t`s.

 - [x] `igraph_graph_atlas()`
 - [x] `igraph_read_graph_graphml()`
 - [x] elements of the `igraph_maxflow_stats_t` struct (70d8a24d3efca97e05aab95a1030264d1e6e31d0)

#### Things that can stay as `int`

 - BLAS/LAPACK/ARPACK interface functions
 - `igraph_version()`
 - all `qsort`-compatible comparison functions return an `int`
 - `line` parameter in error/warning/fatal handlers
 - members of `igraph_bliss_info_t` should stay as `unsigned long` as this type can actually be larger than `igraph_integer_t` under some circumstances

#### Not sure

There are several uses of `int` in `igraph_eigen.h`. I am not yet sure whether these are appropriate as the functions here are undocumented. However, I think that unless ARPACK is the _only_ method some eigenvector computation function can use, we should not be using ARPACK-specific types. In the future, such functions may use something else than ARPACK.

I would suggest leaving the cleanup of `igraph_eigen.h` until after 0.10, as doing this well will take time.

**Comment by szhorvat** [comment]
@ntamas Any objection to completing the last checkbox in the OP here? I want to close this issue (either do it, or decide not to).

**Comment by ntamas** [comment]
No objections, feel free to go ahead.
