### ISSUE TITLE
C attribute handler does not leave the attribute table in consistent state on failure

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2000]
Based on a reading of the C attribute handler code, the attribute table may not be left in a consistent state upon failure. This is based on my reading of the code only. Note that failure may happen not only due to OOM but also due to non-matching attribute types.

----

As an example, let us take the `add_vertices` function. All links below are to the latest commit on `develop` as of this writing.

https://github.com/igraph/igraph/blob/94ee1d6430c800cf8c0b0422e324d9037d68792a/src/graph/cattributes.c#L262

----

This section identifies which vertex attributes are not present yet, and saves their indices. Failure is harmless so far.

https://github.com/igraph/igraph/blob/94ee1d6430c800cf8c0b0422e324d9037d68792a/src/graph/cattributes.c#L273

----

This section will create these attribute for the existing vertices. Should a failure happen after this point, some new attributes will have been permanently added to the graph. Perhaps these should be removed upon failure. Note that the attribute table is still in a consistent state, it just gained some extra entries.

https://github.com/igraph/igraph/blob/94ee1d6430c800cf8c0b0422e324d9037d68792a/src/graph/cattributes.c#L293

----

This section will append new values (for the extra vertices) to attributes which are already present. Should a failure happen here, some of the attribute vectors will be longer than the number of vertices, leaving the attribute table in an inconsistent state.

It seems to me that in some cases this is not harmful: the entries at the end of the attribute vector will just not be accessed. But it could cause trouble whenever the length of the existing vector is taken into account, specifically when appending to it, e.g. [here](https://github.com/igraph/igraph/blob/94ee1d6430c800cf8c0b0422e324d9037d68792a/src/graph/cattributes.c#L373). Thus, it looks like this can cause genuine problems.

https://github.com/igraph/igraph/blob/94ee1d6430c800cf8c0b0422e324d9037d68792a/src/graph/cattributes.c#L343

----

Similar issues will apply to several other attribute handling functions, not just `add_vertices()`.

**Comment by szhorvat** [comment]
I am out of my comfort zone here, as I do not use the attribute handler for the Mathematica interface. Someone experienced with attributes should take a look (@ntamas?).

It seems to me that the correct approach here is to catch errors and undo modifications to the attribute table, at least making sure that all attribute vectors are of the original length.

Similar problems might or might not apply to the Python/R attribute handlers as well. This should be checked.

**Comment by szhorvat** [comment]
This is now fixed for the `add_edges` and `add_vertices` functions, but there may be issues in some of the others.

**Comment by ntamas** [comment]
Checklist:

- [ ] `igraph_i_cattribute_init()`
- [ ] `igraph_i_cattribute_destroy()`
- [ ] `igraph_i_cattribute_copy()`
- [ ] `igraph_i_cattribute_add_vertices()`
- [ ] `igraph_i_cattribute_permute_vertices()`
- [ ] `igraph_i_cattribute_combine_vertices()`
- [ ] `igraph_i_cattribute_add_edges()`
- [ ] `igraph_i_cattribute_permute_edges()`
- [ ] `igraph_i_cattribute_combine_edges()`

The rest are getters so they should not mess up the internals even if they fail.

**Comment by ntamas** [comment]
Documenting my findings here:

* `igraph_i_cattribute_permute_vertices()` has two branches, one for the in-place permutation and one for the case when the vertex attributes of one graph are permuted into the vertex attributes of another graph; in the latter case, it is assumed that the other graph has no vertex attributes yet, and this state is properly restored if an error happens during the permutation. For the in-place case, there is no such guarantee. However, there seems to be no place in the codebase where we would perform an in-place permutation, not even in `igraph_permute_vertices()`, which constructs a new graph.

@szhorvat I vaguely remember that there was a proposal to make `igraph_permute_vertices()` in-place. This has implications for the attribute handler, see above. Right now we could simply remove the in-place branch from `igraph_i_cattribute_permute_vertices()` and be done with it, but if we want to allow in-place permutations in the future, this is not the way to go.

**Comment by ntamas** [comment]
In-place permutation is not as easy as it initially seemed. The problem is in string vectors and the fact that string vectors "own" their strings and copy them all the time, so simply calling `igraph_strvector_index()` may fail if the string duplication fails, and it is hard to know in advance how much memory we will need for intermediate copies. Also, the current implementation is somewhat inefficient because _if_ the input does not map any vertex to more than two "slots" in the target, then we would not need to allocate extra memory for temporary strings (but we do now).

**Comment by szhorvat** [comment]
Sorry, I haven't had time to look at this yet properly. I'll answer next week.

**Comment by ntamas** [comment]
In-place permutations of vertex and edge attributes are now sorted out in cee6aed75 . This is a bit complex now; we first permute the string attributes in temporary string vectors owned by a "work area" until we are done with all of them. Once they are permuted, we release them from the work area and write them back to the attribute storage as the subsequent operations cannot fail any more. Then we permute the numeric and the boolean attributes.
