### ISSUE TITLE
igraph_vector_view() and zero-length data

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2003]
igraph vector functions have asserts checking that `stor_begin` is not `NULL`. This can occasionally be a problem when using `igraph_vector_view()` to construct views to existing data, but the existing data is of zero length, and potentially `NULL`.

It seems that I needed this workaround in IGraph/M to deal with some zero-length vectors created by Mathematica, which may have contained `NULL`. I do not recall the details.

https://github.com/szhorvat/IGraphM/blob/master/IGraphM/LibraryResources/Source/IGCommon.h#L34

It might make sense to incorporate this workaround into `igraph_vector_view()` itself. I.e., if the data length is zero, it should set `stor_begin` to a location that is guaranteed non-`NULL`. This may be a pointer to a static variable within the function.

Opinions?

**Comment by ntamas** [comment]
Sounds good to me.
