### ISSUE TITLE
trie functions cleanup

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2005]
trie functions should be cleaned up:

 - [x] Proper documentation
 - [x] Rename `igraph_trie_get2` to `igraph_trie_get_len` in accordance with the new strvector namings
 - [x] Refactoring needed for `igraph_trie_getkeys`? If not, it should return its result directly (no error code)
 - [x] There are casts of `igraph_trie_t` to `igraph_trie_node_t`, is this actually portable? Why not have a `igraph_trie_node_t` field in `igraph_trie_t` instead?
 - [ ] There is not function to remove entries from the trie.
 - ... ?

**Comment by szhorvat** [comment]
I didn't see your response. I already refactored that part ...

**Comment by szhorvat** [comment]
> whose performance impact is probably negligible

There should be zero performance impact. The binary representation of the struct should be the same. It's just the notation that we are changing, not how it works internally.

The refactoring might be useful in allowing the compiler (and also static analysers) to understand the code better. When using reinterpret casts, the compiler very likely assumes that all bets are off.

**Comment by ntamas** [comment]
> The binary representation of the struct should be the same. It's just the notation that we are changing, not how it works internally.

I was somehow under the impression that you wanted to introduce a _pointer_ to an `igraph_trie_node_t` in `igraph_trie_t`, hence my comment. If it's not a pointer then my comments are moot of course.

**Comment by szhorvat** [comment]
@ntamas Any opinion on `igraph_trie_getkeys()`? It has a bunch of "this is so ugly" comments.

https://github.com/igraph/igraph/blob/develop/src/core/trie.c#L421
https://github.com/igraph/igraph/blob/develop/src/io/lgl.c#L165
https://github.com/igraph/igraph/blob/develop/src/io/ncol.c#L190

**Comment by ntamas** [comment]
I didn't write those comments but I guess the original concern is that we are allowing direct access to the internals of the data structure from the outside and the caller could mess up the trie (in theory) by modifying the strvector. Also, if you destroy the trie in the meanwhile then you hold a pointer to a strvector that is not valid any more. A nicer solution would be to let the user pass in an initialized strvector and copy the contents over, at the expense of some performance loss.

I'd probably convert `igraph_trie_getkeys()` to an internal method and call it something like `igraph_i_trie_borrow_keys()`, making it clear that this is a borrowed reference that will not outlive the trie itself.

**Comment by ntamas** [comment]
`igraph_trie_getkeys()` is now `igraph_i_trie_borrow_keys()` and it simply returns the borrowed reference.

I don't think there's a need to support item removal from the trie now -- it is not necessary internally, and the data structure is not public. Closing this now as the remaining points were handled already.
