### ISSUE TITLE
Test suite issues with memory sanitizer

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2008]
I ran the test suite with [MemorySanitizer](https://clang.llvm.org/docs/MemorySanitizer.html). Doing this is complicated and painful because it requires [building libc++ with MemorySanitizer as well](https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo), and linking to it. Also, it seems to only work on Linux. Therefore, I am recording the results here.

There is one failure which _may_ not be a false positive:

```
 18/429 Test  #18: test::igraph_sparsemat5............................***Failed    0.07 sec
==2903761==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f30de955b4b in s_cmp /home/szhorvat/Repos/igraph/vendor/f2c/s_cmp.c:23:6
    #1 0x7f30de98d5dc in igraphdsortc_ /home/szhorvat/Repos/igraph/vendor/lapack/dsortc.c:122:9
    #2 0x7f30de3d6401 in igraph_arpack_rnsort /home/szhorvat/Repos/igraph/src/linalg/arpack.c:772:5
    #3 0x7f30de3de5b8 in igraph_arpack_rnsolve /home/szhorvat/Repos/igraph/src/linalg/arpack.c:1390:9
    #4 0x7f30de34927c in igraph_sparsemat_arpack_rnsolve /home/szhorvat/Repos/igraph/src/core/sparsemat.c:1707:12
    #5 0x49e74c in main /home/szhorvat/Repos/igraph/tests/unit/igraph_sparsemat5.c:321:5
    #6 0x7f30ddf0b0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #7 0x41e6ad in _start (/home/szhorvat/Repos/igraph/build/tests/test_igraph_sparsemat5+0x41e6ad)

  Uninitialized value was created by an allocation of 'sort' in the stack frame of function 'igraph_arpack_rnsort'
    #0 0x7f30de3d5ee0 in igraph_arpack_rnsort /home/szhorvat/Repos/igraph/src/linalg/arpack.c:738

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/szhorvat/Repos/igraph/vendor/f2c/s_cmp.c:23:6 in s_cmp
```

This may be worth looking into.

----

The rest are all false positives somehow related to very long variadic argument lists in functions such as `igraph_small()`. This is triggered for the following tests:

```
	158 - test::assortativity (Failed)
	160 - test::global_transitivity (Failed)
	162 - test::igraph_adjacent_triangles (Failed)
	191 - test::igraph_local_transitivity (Failed)
	315 - example::igraph_community_fastgreedy (Failed)
	322 - test::community_leiden (Failed)
	328 - test::igraph_community_infomap (Failed)
	387 - example::cohesive_blocks (Failed)
	391 - example::igraph_minimum_size_separators (Failed)
```

These could all be eliminated by shortening the argument list. This is not of great importance because we do not run MemorySanitizer often, and these do not affect any runs on OSS-fuzz.

**Comment by GroteGnoom** [comment]
What's the error message for the false positives?

**Comment by szhorvat** [comment]
Here is one example:

```
391/429 Test #391: example::igraph_minimum_size_separators............***Failed    0.07 sec
==2904674==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f2c4dfc7160 in igraph_vector_int_isininterval /home/szhorvat/Repos/igraph/src/core/vector.pmt:1834:27
    #1 0x7f2c4e0afa7b in igraph_create /home/szhorvat/Repos/igraph/src/constructors/basic_constructors.c:74:23
    #2 0x7f2c4e0b0454 in igraph_small /home/szhorvat/Repos/igraph/src/constructors/basic_constructors.c:149:5
    #3 0x49c2ae in main /home/szhorvat/Repos/igraph/examples/simple/igraph_minimum_size_separators.c:95:5
    #4 0x7f2c4db2f0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #5 0x41c2dd in _start (/home/szhorvat/Repos/igraph/build/tests/example_igraph_minimum_size_separators+0x41c2dd)

  Uninitialized value was stored to memory at
    #0 0x7f2c4dfc0ac4 in igraph_vector_int_push_back /home/szhorvat/Repos/igraph/src/core/vector.pmt:580:15
    #1 0x7f2c4e0b0393 in igraph_small /home/szhorvat/Repos/igraph/src/constructors/basic_constructors.c:145:9
    #2 0x49c2ae in main /home/szhorvat/Repos/igraph/examples/simple/igraph_minimum_size_separators.c:95:5
    #3 0x7f2c4db2f0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

  Uninitialized value was created
    <empty stack>

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/szhorvat/Repos/igraph/src/core/vector.pmt:1834:27 in igraph_vector_int_isininterval
```

I would not fix these, as they are not bugs. This is either a problem with MemorySanitizer, or MemorySanitizer must have some stack-depth related option that I have not discovered yet. One sets runtime options with the `MSAN_OPTIONS` envvar, but I don't know where this is documented.

**Comment by szhorvat** [comment]
The first failure is not a false positive. It turns out that none of the conditions in this list of `if/else`s matches, and the `sort` variable ends up being uninitialized.

https://github.com/igraph/igraph/blob/develop/src/linalg/arpack.c#L668

**Comment by szhorvat** [comment]
Here's the relevant ARPACK routine, `dsortc`:

https://github.com/opencollab/arpack-ng/blob/master/SRC/dsortc.f

It seems that valid `WHICH` inputs are those that are already handled in `igraph_arpack_rnsort()`. If the input is different, the function does not sort. It is not yet clear to me if it is fine to leave it like that (i.e. just add `XX` into `sort`) or not.

**Comment by ntamas** [comment]
Let's just handle the remaining cases and fill `sort` with `XX` to make MemorySanitizer happy. We will never hit that branch anyway.

**Comment by szhorvat** [comment]
That branch is hit in this very test. What's not completely clear to me is whether `XX` is valid here, indicating no sorting, or whether it is plainly invalid input that should be forbidden. However, since `rssort`/`rnsort` are called as the very last function, I think it's alright to accept this input as do no sort. There is no following code relying on a special sort. I'll add the extra branch now.

**Comment by szhorvat** [comment]
This is outside of our control. Issue was reported upstream. https://github.com/google/sanitizers/issues/1500 Closing.
