### ISSUE TITLE
Need a brief explanation of what igraph is

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2014]
Most Linux distros and package managers contain a short description for each of the packages they include. igraph's description is not always great. Examples:

https://src.fedoraproject.org/rpms/igraph/blob/rawhide/f/igraph.spec#_29
https://launchpad.net/ubuntu/+source/igraph
https://doc.sagemath.org/html/en/reference/spkg/igraph.html

We should write a better, clearer, more professional description and display it in a prominent part of the website, so that package maintainers can copy it from there.

**Comment by mdshahansha** [comment]
@szhorvat 
let me complete this explanation ,in well documented  form

**Comment by szhorvat** [comment]
Proposal based on the short info on the [homepage](https://igraph.org/), here's a one-liner that we can propose for Linux distros that currently have an unappealing description.

> igraph is a C library for complex network analysis and graph theory, with emphasis on efficiency, portability and ease of use.

**Comment by ntamas** [comment]
Looks good to me!

**Comment by ntamas** [comment]
I've updated the description in `doc/igraph.3` and `README.md`. I could not find any other places in the source repo where the original description is found verbatim; I was wondering what other actionable items we have here. E.g., shall we now reach out to distro maintainers and ask them to change the description? Does anyone know what's the official way to do that? For instance, Ubuntu might simply be using Debian packages so there's no point in approaching Ubuntu maintainers about this.
