### ISSUE TITLE
Clean up attribute types

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2015]
Currently, we have the following attribute types:

```
typedef enum { IGRAPH_ATTRIBUTE_DEFAULT = 0,
               IGRAPH_ATTRIBUTE_NUMERIC = 1,
               IGRAPH_ATTRIBUTE_BOOLEAN = 5,
               IGRAPH_ATTRIBUTE_STRING = 2,
               IGRAPH_ATTRIBUTE_R_OBJECT = 3,
               IGRAPH_ATTRIBUTE_PY_OBJECT = 4
             } igraph_attribute_type_t;
```

There are custom types for R and Python. Are these truly needed? C code should never encounter a situation where _both_ R and Python objects are present.

I suggest one of the following refactorings:

### Option 1

```
typedef enum { IGRAPH_ATTRIBUTE_DEFAULT = 0,
               IGRAPH_ATTRIBUTE_NUMERIC = 1,
               IGRAPH_ATTRIBUTE_BOOLEAN = 2,
               IGRAPH_ATTRIBUTE_STRING = 3,
               IGRAPH_ATTRIBUTE_CUSTOM = 128
             } igraph_attribute_type_t;
```

We renumber existing enum values from 0 to 3 (as ABI backwards compatibility for 0.10 is long out the window anyway).

We introduce `IGRAPH_ATTRIBUTE_CUSTOM = 128`, which each high-level interface can treat as they wish.

### Option 2

```
typedef enum { IGRAPH_ATTRIBUTE_DEFAULT = 0,
               IGRAPH_ATTRIBUTE_NUMERIC = 1,
               IGRAPH_ATTRIBUTE_BOOLEAN = 2,
               IGRAPH_ATTRIBUTE_STRING = 3
             } igraph_attribute_type_t;
```

We renumber existing enum values from 0 to 3 (as ABI backwards compatibility for 0.10 is long out the window anyway).

We document that values 0-127 are reserved for future use, but 128 onward can safely be used by high-level interfaces. We do not introduce a specific named value, but in C enum values are proper integers anyway, so it's safe for a high-level interface create their own

```
#define IGRAPH_ATTRIBUTE_PY_LIST 128
#define IGRAPH_ATTRIBUTE_PY_DICT 129
#define IGRAPH_ATTRIBUTE_PY_OBJECT 130
...
```

or whatever. This way high-level interfaces can conveniently handle multiple types without having to bundle them up under a single one.

**Comment by szhorvat** [comment]
Finally, what is `IGRAPH_ATTRIBUTE_DEFAULT` and can we remove it?

**Comment by ntamas** [comment]
`IGRAPH_ATTRIBUTE_DEFAULT` is the "null value"; I think it should have been called `IGRAPH_ATTRIBUTE_UNSPECIFIED` (and feel free to change it). It is used in this sense in the LEDA graph writer.

As for the higher level interfaces: I think `IGRAPH_ATTRIBUTE_R_OBJECT` and `IGRAPH_ATTRIBUTE_PY_OBJECT` can be consolidated into an `IGRAPH_ATTRIBUTE_POINTER` type because higher-level language objects are basically opaque pointers when viewed from the C side. At least this is the case with R (i.e. `SEXP`) and Python (i.e. `PyObject*`); not sure about Mathematica.

Furthermore, we can indicate that higher-level interfaces are free to use values >= 128 in any way they want, but personally I don't think I'd use it in the Python interface.

**Comment by szhorvat** [comment]
> `IGRAPH_ATTRIBUTE_DEFAULT` is the "null value"; I think it should have been called `IGRAPH_ATTRIBUTE_UNSPECIFIED` (and feel free to change it). It is used in this sense in the LEDA graph writer.

Perfect, that's exactly what I need for the GML reader.

> As for the higher level interfaces: I think `IGRAPH_ATTRIBUTE_R_OBJECT` and `IGRAPH_ATTRIBUTE_PY_OBJECT` can be consolidated into an `IGRAPH_ATTRIBUTE_POINTER` type

Well, they're all pointers, really. I would find it a bit confusing. Here are a few alternative suggestions. Do you like any of them? `IGRAPH_ATTRIBUTE_CUSTOM`, `IGRAPH_ATTRIBUTE_OBJECT`, `IGRAPH_ATTRIBUTE_FOREIGN`?

> not sure about Mathematica.

I do not use the attribute handler at this moment as Mathematica does not yet provide flexible handles to its native objects from C.

**Comment by ntamas** [comment]
`IGRAPH_ATTRIBUTE_OBJECT` was my other idea before settling on pointer, so I'd choose that.

**Comment by szhorvat** [comment]
This'll be fixed only after the GML PR has been merged. I'm assigning it to myself to prevent the change from happening until then.
