### ISSUE TITLE
What to do with igraph_hashtable_t?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2018]
We have a private `igraph_hashtable_t` data structure, which is not used anywhere, is slightly buggy. What do we do with it? Remove it? Keep it as it is? Or fix it up and expose it?

#### What does it do?

It maps strings to strings.

#### Issues

 - It is not technically a hash table. It does not use hashes. It uses `igraph_trie_t` to map strings to integers, which are then used to index into an `igraph_strvector_t`.
 - It is undocumented. It is unclear what the role of `defaults` is. It seems to keep a "default value" for each key, which must be provided whenever adding new elements. There is a function to reset all elements to their defaults. It looks like this data structure was created for a very specialized application.
 - When adding new elements, the data structure may be left in a dangerously inconsistent state. There is in fact [a comment](https://github.com/igraph/igraph/blob/develop/src/core/hashtable.c#L49) that states that this is not dangerous, but I do not think it is correct. If adding to the trie succeeds but adding to the strvector fails, then there will be more elements in the trie. This could lead to a future out-of-bounds indexing. A nice fix would involve implementing a function to remove elements from a `trie_t` (which we don't have yet). A less nice fix would first use `igraph_trie_check()`, then extend the strvectors, then extend the trie using `igraph_trie_get()`. This will almost halve the performance because `trie_check()` and `trie_get()` do mostly the same work internally.

**Comment by szhorvat** [comment]
It looks like this was used in the Pajek parser until about 2011, 6ee49bf9bfb4dc6d34fd4dc370dd356ff52ffebd

I am generally cautious about removing already implemented and tested functionality, even if it is not used, but in this case I vote for removal. This data structure is quite trivial. All the complex logic is in the trie functions. Also, it seems to have been created for a specialized use case, and not used for ~10 years.

**Comment by ntamas** [comment]
Let's remove it. I don't think it was tested rigorously, the only purpose of it was to aid in the implementation of the Pajek parser.

**Comment by ntamas** [comment]
Removed both from `master` and `develop`
