### ISSUE TITLE
Overflow checks for core data structures

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2020]
Core data structures need to be protected against overflow. For example, `push_back()` should not try to extend size beyond the maximum, or reserve more storage (by doubling) then the maximum.

Items marked with `*` are high priority.

Some of these may already be done, and only need verification.

 - [x] `vector_t`
 - [x] `matrix_t`, composed of `vector_t` but still prone to overflow
 - [x] `vector_list_t`, `matrix_list_t`
 - [x] `graph_list_t`
 - [x] `strvector_t`
 - [x] `stack_t`
 - [x] #2021
 - [x] `set_t`
 - [x] #2022
 - [x] `trie_t`
 - [x] `heap_t`
 - [x] `estack_t`, composed of `vector_t` and `stack_t`
 - [x] `cutheap_t`, composed of `vector_t`
 - [x] `buckets_t`, composed of `vector_t`
 - [x] `array3_t`, composed of `vector_t`, but still prone to overflow (like `matrix_t`)
 - [x] `fixed_vectorlist_t`, composed of `vector_list_t`
 - [x] `marked_queue_int_t`, composed of `dqueue_t` and `vector_t`
 - [x] `psumtree_t`, composed of `vector_t`

**Comment by szhorvat** [comment]
@ntamas I'll leave it to you to check off the `*_list_t` types. `push_back()` is fine in those, and there is probably no other way for them to fail with overflow.

**Comment by ntamas** [comment]
I'll tick off `vector_list_t`, `matrix_list_t` and `graph_list_t`. I think the only place to check there is the `expand_if_full` templated function, which correctly checks whether `old_size < IGRAPH_INTEGER_MAX / 2` before doubling it .
