### ISSUE TITLE
Check vector_order2 on zero-length vector

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2029]
Reminder to check if `igraph_vector_order2()` works on zero-length vectors, it might not.

**Comment by ntamas** [comment]
Added in a92eca18b; it seems like it's working.

**Comment by szhorvat** [comment]
Thanks, and sorry about the very brief description. `igraph_indheap_init_array()` will get a `len` of `0` in this case, and this is the _only_ way to create a zero-size `indheap`, hence my doubt.
