### ISSUE TITLE
Macros for checking memory allocation

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2030]
Almost every single `IGRAPH_CALLOC` and `IGRAPH_REALLOC` is immediately followed by a check of their return value, following this pattern:

```c
arr = IGRAPH_CALLOC(size, igraph_integer_t);
if (! arr) {
    IGRAPH_ERROR("Insufficient memory for foobar.", IGRAPH_ENOMEM); /* LCOV_EXCL_LINE */
}
```

Why don't we wrap this up into macros going forward?

```c
#define IGRAPH_CHECK_ALLOC(ptr, msg) \
    do { \
        if (! ptr) { \
            IGRAPH_ERROR("Insufficient memory for " msg ".", IGRAPH_ENOMEM); \
        } \
    } while (0)

#define IGRAPH_CALLOC_CHECK(n, t, res, msg) \
    do { \
        *res = IGRAPH_CALLOC(n, t); \
        IGRAPH_CHECK_ALLOC(*res, msg); \ 
    } while (0)

#define IGRAPH_REALLOC_CHECK(p, n, t, res, msg) \
    do { \
        *res = IGRAPH_REALLOC(p, n, t); \
        IGRAPH_CHECK_ALLOC(*res, msg); \ 
    } while (0)
```

Then we can use

```c
IGRAPH_CALLOC_CHECK(size, igraph_integer_t, &res, "foobar");
```

As a bonus, we don't need to worry about adding `/* LCOV_EXCL_LINE */` either.

Why a separate `CHECK_ALLOC` macro? If we go with [the lazy `adjlist`/`inclist` `get` functions returning `NULL` on failure](https://github.com/igraph/igraph/issues/1955), it will be useful to have a more compact way to perform the check.

Why a separate `res` and `p` for the realloc version? This is debatable and it might actually be better to consolidate these two arguments.

**Comment by ntamas** [comment]
Seems like a good idea to me. The syntax is a bit awkward; it would be better to do it as an assignment (i.e. `ptr = IGRAPH_CALLOC_CHECK(...)`) but I guess that's not possible with macros...

I'd just use a single variable for the realloc version, not two. I don't think we have any use-case for the two-variable version in our codebase.

**Comment by szhorvat** [comment]
I actually implemented a single-variable version of the realloc macro after writing this, but refactoring existing code to use it is not entirely straightforward. It's possible, but in the end I'd risk introducing mistakes, and what would we gain? To reduce the line count by 2? Realloc is rarely used, and used almost exclusively in the core data structures, so I'll simply skip the realloc version for the moment.

I'll add the calloc version (which is much more often needed), as well as a macro to check for NULL in general. I'll use the NULL-checker macro on the result of `igraph_lazy_adjlist/inclist_get()`. Sounds good without a separate PR?

**Comment by ntamas** [comment]
Sounds good to me!

**Comment by szhorvat** [comment]
@ntamas has now added `IGRAPH_CHECK_OOM()`, closing.
