### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2032]
There's code that is not used by any internal code (except maybe tests), and probably not useful for end users, for example because it's an undocumented data structure. Maybe sometimes these functions were added just in case functions were needed in the future, or they were once used internally, but they're not used anymore.

Removing the code lowers the maintenance burden, but it means that if we ever do need the code in the future we'll have to add it back in.

There's usually a few options on how to deal with dead code:
- Document it, test it, keep it, because it offers some useful functionality for end users.
- Keep it because we think it will be useful for us in the near future.
- Delete it.

This issue is to keep track of the decision about what to do with it dead code. Checkmarks are for when a decision has been made. The list will be expanded.

- [x] src/core/grid.c: igraph_2dgrid_dist, igraph_i_2dgrid_addvertices, igraph_2dgrid_neighbors. The 2dgrid is now used for the large_graph and fruchterman_reingold layouts.
- [x] array3 will be used for spatial networks (#2026)
- [ ] igraph_buckets_pop, igraph_dbuckets_popmax, igraph_dbuckets_empty
- [ ] src/centrality/prpack has prpack_preprocessed_gs_graph.cpp and prpack_preprocessed_schur_graph.cpp which are not used at all, and and lots of other unused functions in different files.
- [ ] src/cliques/cliquer also has lots of unused functions.
- [ ] ~src/graph/graph_list.c has unused, undocumented functions, including some static functions.~
- [x] src/math/bfgs.c seems unrelated to graphs and is hardly documented. 

This is also related to #1979, because once the code is removed it doesn't need documentation anymore :)

**Comment by ntamas** [comment]
I'd treat PRPACK and Cliquer differently; these are vendored pieces of code and it is easier to keep track of the changes we make to it (if needed) if we modify the vendored code only as needed. (The diff becomes too noisy if we start to remove code that is not used in igraph but is there in the original library).

`igraph_buckets_t` and `igraph_dbuckets_t` are used only for the maxflow implementation and it was never a goal to expose them publicly. If the functions you mentioned above are unused, I'm okay with removing them.

The same is true for `igraph_2dgrid_t` -- it was meant for layout algorithms so if there are functions that are unused, feel free to remove them. `igraph_2dgrid_t` is not meant to be exposed as part of the public API.

**Comment by szhorvat** [comment]
In case this is motivated by coverage:

Just a word of caution not to fall into the trap of using coverage metrics to gauge quality. Achieving high coverage is not a goal in itself. Coverage is just a tool to help us see where more testing may be worthwhile.

I generally have an uneasy feeling about removing parts of a _system_, even if those parts are unused. Sometimes seeing those parts makes it easier to understand how the system works (and all these data structures are undocumented). Sometimes using those part is a hair away: now they're unused, but they might be useful in future refactorings. But only if they're kept, otherwise we are much less likely to even realize the potential of that refactoring.

I'm not against removing stuff in general, just be cautious and understand what we truly gain from it ...

**Comment by GroteGnoom** [comment]
>I'd treat PRPACK and Cliquer differently; these are vendored pieces of code and it is easier to keep track of the changes we make to it (if needed) if we modify the vendored code only as needed. (The diff becomes too noisy if we start to remove code that is not used in igraph but is there in the original library).

If I looked it up correctly, the latest release of cliquer is 2010 (https://users.aalto.fi/~pat/cliquer.html) and the latest release of prpack is 2012? (https://github.com/DavidKurokawa/prpack). prpack is a little bit harder to check, because our prpack files don't have any license or copyright information.

I think we should start treating cliquer like it's igraph code. I remember that during the integer transition it was tough to deal with because it doesn't fit the rest of igraph. Let's make it fit.

Once we treat cliquer as our own piece of code we can let it use igraph_integer_t, so we don't have to give errors that a graph is too big for cliquer. It there anything in particular that makes cliquer hard to maintain ourselves? It seems very readable.

I don't know prpack that well, but I think the same goes there: document it, test it, change it so it fits igraph, and throw away the unused parts.
> In case this is motivated by coverage

Yes it is. Because I notice that coverage is important. By using coverage I immediately found multiple pieces of code with severe bugs in it (#2017, https://github.com/igraph/igraph/commit/a1c053a682f9861f1c749f025e6948fe7c9851ab)

> I generally have an uneasy feeling about removing parts of a system, even if those parts are unused. Sometimes seeing those parts makes it easier to understand how the system works (and all these data structures are undocumented). Sometimes using those part is a hair away: now they're unused, but they might be useful in future refactorings. But only if they're kept, otherwise we are much less likely to even realize the potential of that refactoring.

But they're not used by the system, so usually that doesn't help much for seeing how it works, because it's even more code that you have to spend reading. Unused code can also be detrimental to future refactorings because we think we have to maintain the functionality of it. I think we would be less worried about touching vendored code when there's less of it.

> I'm not against removing stuff in general, just be cautious and understand what we truly gain from it ...

The code is in the git history. We could also make a windows-like recycle bin of unused code just to be sure.
I think right now we are being too cautions, and it prevents us from making igraph a well-documented, well-tested library.

**Comment by szhorvat** [comment]
@ntamas What's the situation with unused `static` functions in `graph_list.c`? These are newly added. Can we remove them?

```c
static igraph_error_t igraph_i_graph_list_init_item(
    const igraph_graph_list_t* list, igraph_t* item
) {
    return igraph_empty(item, 0, list->directed);
}

static igraph_error_t igraph_i_graph_list_copy_item(
    igraph_t* dest, const igraph_t* source
) {
    return igraph_copy(dest, source);
}

static void igraph_i_graph_list_destroy_item(igraph_t* item) {
    igraph_destroy(item);
}
```

**Comment by ntamas** [comment]
They are not unused. They replace `static igraph_error_t INTERNAL_FUNCTION(init_item)` and friends from `typed_list.pmt` because `CUSTOM_INIT_DESTROY` is defined before including `typed_list.pmt`.

**Comment by ntamas** [comment]
> igraph_buckets_pop, igraph_dbuckets_popmax, igraph_dbuckets_empty

I decided to keep these as these are standard functions for a "buckets" data structure and the implementation would not be complete without them. (Ex: `igraph_dbuckets_empty()` happens not to be used right now, but `igraph_buckets_empty()` _is_ used; similarly, `igraph_buckets_pop()` is not used but `igraph_dbuckets_pop()` _is_ used, proving that both are useful in some context).

>src/centrality/prpack has prpack_preprocessed_gs_graph.cpp and prpack_preprocessed_schur_graph.cpp which are not used at all

PRPACK is vendored code and I'd rather not modify it unless there's a strong reason to do so. The compiler is smart enough to do dead code elimination, and we are not going to document these anyway so there's no harm in keeping them. The same applies to Cliquer.
