### ISSUE TITLE
nb_clusters parameter of community_leiden should be allowed to be NULL

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2045]
The `nb_clusters` parameter of `igraph_community_leiden` cannot be `NULL`. This is annoying and unexpected, and should be changed for 0.10.

**Comment by szhorvat** [comment]
@vtraag I made this change for `master`. I hope there was no special reason to enforce this parameter to be non-NULL.

**Comment by szhorvat** [comment]
Oops, wrong branch ... never mind, it'll be fixed when that branch is merged.

**Comment by vtraag** [comment]
Don't know why it was required, I don't remember, it makes sense to make it optional to me. Thanks @szhorvat !
