### ISSUE TITLE
igraph_i_dot_escape() not compliant to the DOT specs

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#2049]
**Describe the bug**

`igraph_i_dot_escape()` is not compliant to the DOT specs, which say:

> In quoted strings in DOT, the only escaped character is double-quote `"`. That is, in quoted strings, the dyad `\"` is converted to `"`; all other characters are left unchanged. In particular, `\\` remains `\\`.

[(source)](https://graphviz.org/doc/info/lang.html)

Note that neither newlines nor backslashes should be escaped; we do both now.

**Version information**
latest `develop`

**Comment by ntamas** [comment]
@GroteGnoom feel free to assign this back to me if you are short on time or you want to work on something else instead.

**Comment by szhorvat** [comment]
Continuing the discussion here.

The spec appears to say that only `"` can be escaped, nothing else, not even `\`. I said in the previous thread that `\` should not be escaped. That does not actually work:

 - How do you represent a string containing a single `\`? `"\"` will clearly lead to a syntax error.
 - If `\` cannot be escaped, then `"\\""` should be a valid string containing two characters, `\` and `"`. However, `dot` does not parse this (it throws a syntax error).

Thus I take back what I said, let's keep escaping `\`: it's better to produce a file which is interpreted slightly differently than it should be than to produce a corrupt file that cannot be read.

----

The main priority to fix here is quoting empty strings, which is a common use case.

**Comment by szhorvat** [comment]
If I actually try to create plots in which the labels have `\` in them, `\` appears to be interpreted as an escape sequence, contrary to the specs. `\x` renders as `x`. `\\` renders as `\`. `\n` is treated as a newline.

It seems that it's best to leave the code as it is, except for adding quotes to empty strings.

**Comment by szhorvat** [comment]
I fixed the empty string bug and backported it to `master`, along with the NaN fix.
