### ISSUE TITLE
get_adjaceny() and get_stochastic() should support weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2050]
**What is the feature or improvement you would like to see?**

`igraph_get_adjacency()` and `igraph_get_stochastic()` should support weights, just like `igraph_get_laplacian()` does. The same for the sparse versions.

Related: #1978

**Use cases for the feature**

This is a basic operation that all graph libraries should support.

**Comment by ntamas** [comment]
We might also need the usual `igraph_loops_t` argument to decide what to do with loop edges (summon @szhorvat). Right now the function behaves as if `IGRAPH_LOOPS_ONCE` was supplied, i.e. loop edges are counted once if the graph is undirected and the type is `IGRAPH_GET_ADJACENCY_BOTH` -- which means that it does not hold that the adjacency matrix obtained with `IGRAPH_GET_ADJACENCY_BOTH` is the sum of `IGRAPH_GET_ADJACENCY_UPPER` and `IGRAPH_GET_ADJACENCY_LOWER` in the undirected case.

**Comment by szhorvat** [comment]
> * for undirected graphs, loop edges are counted once, unless the matrix type is `IGRAPH_GET_ADJACENCY_BOTH`, in which case they are counted twice

I would not do this. We need a way to generate the most common type of adjacency matrix, which has both the upper and lower parts filled up and all elements (including the diagonals) are interpreted as edge counts.

There are good arguments for sometimes counting the diagonal twice, but this type of adjacency matrix is not as commonly used, and I believe is not what most people would expect.

The default needs to be filling both the upper and lower half and counting loops once. We could perhaps add a fourth mode which counts loops twice, but I would not use this fourth mode as the default in `functions.yaml`.

**Comment by szhorvat** [comment]
I'm going to do a quick survey of what other software does, although I am not saying that we should follow other software. However, the adj. mat. is a fundamental concept that most everyone who works with networks encounters. This does mean that what the majority of the software do becomes users' expectations.

Of course I can bring countless arguments for counting loops _twice_, but I do believe that this is _not_ what people expect.

Therefore I strongly suggest to support _both_ modes (counting once and twice) and I suggest (slightly less strongly) to make the default (in `functions.yaml`) count once.

**Comment by szhorvat** [comment]
Survey of some other software:

 - Mathematica: once
 - SageMath (which I respect greatly): once
 - Maple: once
 - networkx: once

These don't seem to have an option to count twice, even though that option would be quite useful for various reasons we discussed before.

**Comment by szhorvat** [comment]
Actually, graph-tools counts them twice. It's the only software I found that does this. https://graph-tool.skewed.de/static/doc/spectral.html#graph_tool.spectral.adjacency

**Comment by szhorvat** [comment]
https://twitter.com/szhorvat/status/1526686485746941952

**Comment by szhorvat** [comment]
Thinking a bit more aloud here:

 - I can't think of any good _mathematical_ reason to put 1s on the diagonal instead of 2s if we assume that loops contribute to the degree.
 - However, whatever we use as the default for the graph -> matrix conversion should be the same as what we use for the matrix -> graph conversion as well.
 - If we create half the number of diagonal entries during matrix -> graph conversion, then what do we do with odd numbers (e.g. 3)? I expect that most datasets in the wild will use 1s (not 2s) and we will need to handle this sort of data well.

**Comment by ntamas** [comment]
Note that there's another expectation: the row sums should be equal to the out-degrees and the column sums should be equal to the in-degrees. This naturally holds for directed graphs (with or without loop edges). For undirected graphs, it holds only if we count the loops twice in the diagonal because `igraph_degree()` also counts them twice, at least at the moment (because we only provide an `igraph_bool_t` for the `loops` argument of `igraph_degree()`).

So, this issue ties a bit into #2066 and #2065 -- if we provide fine-grained loop control there, we should also provide it for `igraph_get_adjacency()`. If we use a default, `igraph_get_adjacency()` should be consistent with that default instead.

**Comment by ntamas** [comment]
FWIW, Wikipedia says "loops may be counted either once (as a single edge) or twice (as two vertex-edge incidences), as long as a consistent convention is followed. Undirected graphs often use the latter convention of counting loops twice, whereas directed graphs typically use the former convention". Their illustrations count loop edges twice in undirected graphs:

> The convention followed here (for undirected graphs) is that each edge adds 1 to the appropriate cell in the matrix, and each loop adds 2.[[4]](https://www.wikiwand.com/en/Adjacency_matrix#citenote4) This allows the degree of a vertex to be easily found by taking the sum of the values in either its respective row or column in the adjacency matrix.

Basically, I think the question now boils down to this: do we want to switch to fine-grained loop control everywhere in igraph? If so, `igraph_get_adjacency()` must naturally follow suit. `igraph_get_stochastic()` is a bit more interesting: if we indeed switch to fine-grained loop control, we should probably give the user the choice to count loop edges once or twice there as well, but counting them once feels "wrong" to me in case of an undirected graph.

**Comment by ntamas** [comment]
Okay, so based on the dev talk today, I've added an `igraph_loops_t` option to `igraph_get_adjacency()`, which now allows a lossless roundtrip with `igraph_adjacency()` if we use `IGRAPH_LOOPS_ONCE`. I wonder whether we should also allow such an option for `igraph_adjacency()` and `igraph_weighted_adjacency()`. The latter is less problematic (we just need to halve the weights in the diagonal if loops are counted twice). As for the former, it should probably throw an error when `loops == IGRAPH_LOOPS_TWICE` and there is an odd number in the diagonal, right?

**Comment by szhorvat** [comment]
> I wonder whether we should also allow such an option for `igraph_adjacency()` and `igraph_weighted_adjacency()`

Yes, it would be useful.

> As for the former, it should probably throw an error when `loops == IGRAPH_LOOPS_TWICE` and there is an odd number in the diagonal, right?

I think that's the best.

**Comment by ntamas** [comment]
Nearly done, I just want to add more unit tests.

**Comment by ntamas** [comment]
Implemented in 18f82cccd
