### ISSUE TITLE
get_stochastic() can be optimized

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2051]
`igraph_get_stochastic()` loops over all elements of the matrix, which is naïve and slow. A better implementation will use `igraph_matrix_null()` to zero out all matrix elements very efficiently, then loop through edges and set matrix elements.

This is low priority but it may be convenient to do it at the same time with #2050. In analogy with the Laplacian calculation, a single function could be used to compute either the adjacency or the stochastic matrix, using the appropriate normalization for the stochastic case.

**Comment by ntamas** [comment]
Implemented in 05e5d55ac
