### ISSUE TITLE
File readers/writers are sensitive to the locale

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2053]
**Describe the bug**

Most file format readers/writers are sensitive to the locale, usually to decimal points vs commas. If the current numeric locale is not `"C"` (or rather: it is uses commas instead of points), both readers and writers will fail or produce incorrect output.

**To reproduce**

For example, in Python:

```python
import igraph
import locale

locale.setlocale(locale.LC_ALL, 'hu_HU')

# See that the decimal point is ","/
locale.localeconv()['decimal_point']

# Decimal commas are written to GML.
g = ig.Graph([(0,1)])
g.vs['w'] = [1.23, 4.56]
g.write_gml('foo.gml')

# Try to read a correct GML and check the result, assuming that
# the above graph was written _correctly_ (i.e. with points) into "correct.gml"
g = ig.Graph.Read_GML('correct.gml')

# In 0.10, I expect the above will error (untested).
# in 0.9 it truncates the parts of the numbers beyond the decimal point,
# since it expects commas.

g.vs['w']
# [1.0, 4.0]
```

**Possible solutions**

 1. Document that readers / writers will only work correctly in the `"C"` locale (or when the decimal point is set to `.`) and leave the rest to the host application.

 2. Temporarily set the locale to `"C"` using [`setlocale`](https://en.cppreference.com/w/c/locale/setlocale). This is what the GraphML writer does. See here: https://github.com/igraph/igraph/blob/master/src/io/graphml.c#L1505 
 
    The problem with this is that `setlocale` sets a global process state and is not quite safe to call from threads. While we do say that "igraph is not fully thread safe", this problem is a bit different. It's not about using igraph from multiple thread. It's enough to use it from a single thread, and it can still cause trouble in the other threads of the host application. The [`setlocale` docs](https://en.cppreference.com/w/c/locale/setlocale) even say that it should not be called while another thread may be executing some functions such as `printf`.

 3. There are platform-specific solutions to setting a thread-specific locale, such as `uselocale()`. We could have a pair of functions, `igraph_set_locale()`, `igraph_restore_locale()` that affect the current thread only and have appropriate implementations for several platforms.

Personally, I vote for option 1. because of the problems I mentioned in 2. This way, high-level interfaces can deal with the problem as appropriate. For example, if the Python process is single-threaded for practical purposes (is it?), then the Python interface can set/reset the locale before calling writers/readers as appropriate. This could even be done from Python code, which is easier than C.

**Notes — which interfaces are affected among C/R/Py/Mma?**

I tried to test if R is affected using `Sys.setlocale('LC_ALL', 'hu_HU')`, and interestingly, it does not change the decimal point:

```R
> Sys.getlocale()
[1] "hu_HU/hu_HU/hu_HU/C/hu_HU/en_US.UTF-8"
> Sys.localeconv()
    decimal_point     thousands_sep          grouping   int_curr_symbol 
              "."                ""                ""            "HUF " 
  currency_symbol mon_decimal_point mon_thousands_sep      mon_grouping 
             "Ft"               ","               " "        "\003\003" 
    positive_sign     negative_sign   int_frac_digits       frac_digits 
               ""               "-"               "2"               "2" 
    p_cs_precedes    p_sep_by_space     n_cs_precedes    n_sep_by_space 
              "1"               "2"               "1"               "2" 
      p_sign_posn       n_sign_posn 
              "4"               "4" 
```

If I try to force the matter, then R warns me that things will break:

```R
> Sys.setlocale('LC_NUMERIC', 'hu_HU')
[1] "hu_HU"
Warning message:
In Sys.setlocale("LC_NUMERIC", "hu_HU") :
  setting 'LC_NUMERIC' may cause R to function strangely
> 1.23
[1] 1,23
```

So we won't have problems with R.

----

This is only a problem when C/igraph is used from a host application that is likely to change the locale. Among the current high-level interfaces, only Python is affected.

The `setlocale()` docs state that on program startup, the locale is set to `"C"`. So this will not affect most people who use the C/igraph directly.

**Comment by szhorvat** [comment]
BTW this is another example of how using C (instead of C++) is limiting us. The C standard library doesn't fit modern applications very well. In C++, we could set the current output stream to use dots without affecting the rest of the system.

**Comment by ntamas** [comment]
Ths is now implemented in `develop` so closing.
