### ISSUE TITLE
Clean up GraphML reader

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2054]
This is a task to clean up the GraphML reader.

 - [x] Make sure that error codes from igraph functions are handled in all parts of the reader.
 - [x] Investigate whether finally stack ENTER/EXIT mechanism can simplify the code, and if so, make use of it.
 - [x] Prefer `igraph_i_parse_integer()/real()` instead of `sscanf()` for number parsing. These functions do range checking and are overflow-safe.

It would be nice to also check that the reported errors are actually informative and help users correct issues.

Also, perhaps investigate if a new reader function can be added that returns all graphs in the GraphML file as an `igraph_graph_list_t`, instead of just returning the `n`th graph.

**Comment by ntamas** [comment]
The cleanup tasks are now done. As for returning all graphs from the file, I'd rather leave that for later (if ever) as it's complicated. First of all, there can be nested graphs in that file; second, node / edge attribute declarations may be placed at the top level, in which case they apply to all graphs in the file.
