### ISSUE TITLE
GraphML reader does not tolerate space around Boolean values

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2056]
**Describe the bug**

When `true` has spaces around it in a GraphML file, igraph interprets it as "false".

It's unclear to me whether putting spaces around such a Boolean value is fine according to the spec, but _silently_ substituting a default "false" is not nice. Ideally there would be a warning when substitution occurs.

The relevant function is `igraph_i_graphml_parse_boolean()`.

**To reproduce**

The following has been created by minor editing of igraph's own output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
         http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<!-- Created by igraph -->
  <key id="v_foo" for="node" attr.name="foo" attr.type="boolean"/>
  <graph id="G" edgedefault="directed">
    <node id="n0">
      <data key="v_foo">
        true
      </data>
    </node>
    <node id="n1">
      <data key="v_foo">false</data>
    </node>
    <edge source="n0" target="n1">
    </edge>
  </graph>
</graphml>
```

If I read it using `g <- read_graph('g.graphml', 'graphml')` in R, I get `V(g)$foo` as `c(FALSE FALSE)`.

**Version information**

R/igraph 1.3.1 but probably the same on `develop` as well.

**Comment by szhorvat** [comment]
@ntamas Use this 70ac3ec94c943d76b7d2dc91a035e242018e8d6a

**Comment by ntamas** [comment]
c3149ba52 should fix this.
