### ISSUE TITLE
Matrix and vector equality with tolerance

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2060]
We now have a well-written and well-tested function for equality with tolerance, `igraph_almost_equals()` and `igraph_cmp_epsilon()`.

We also have some functions for vector, matrix, and complex number equality, but they are not consistent with the former.

  -`igraph_complex_eq_tol()` uses absolute tolerance instead of relative, which is not particularly useful.
 - `igraph_vector_e_tol()` also uses absolute tolerance, but it is not consistent in naming with `igraph_vector_all_e()`.
 - `igraph_matrix_all_e_tol()` is based on `igraph_vector_e_tol()` but its naming is inconsistent.

Proposal:

  - Deprecate all three of these. 
  - Provide `igraph_vector_all_almost_e()` and `igraph_matrix_all_almost_e()` with relative tolerance, based on `igraph_almost_equals()`.
  - Provide `igraph_complex_almost_equals()`, and vector and matrix versions as well.

**Comment by ntamas** [comment]
`feat/lenient-comparison` branch merged in d7aeb1d3e so closing.
