### ISSUE TITLE
Add vertex paths output argument to igraph_get_k_shortest_paths

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2061]
>Are we sure we don't want to add an output argument to return the vertex paths? All other path functions have this, except `igraph_get_all_simple_paths`, which needs a complete refactoring anyway.

>Note that the vertex paths can't be computed from the edge paths without also having at least the start vertex.

>It would be a useful convenience to be able to return the vertex paths.

_Originally posted by @szhorvat in https://github.com/igraph/igraph/issues/1763#issuecomment-1126537052_

**Comment by szhorvat** [comment]
Either we do this for 0.10 or we add an `\experimental` label.

**Comment by ntamas** [comment]
Can we have a convenience function that takes a sequence of edge IDs and a start vertex, and returns a corresponding sequence of vertex IDs? We could then call this from `igraph_get_k_shortest_paths()` to get the vertex paths (and all other functions that compute an edge path first could also do the same thing).

**Comment by ntamas** [comment]
We now have `igraph_convert_edge_to_vertex_paths()`, which takes a graph, a source vertex ID, a sequence of edge IDs, an `igraph_neimode_t` and produces another vector of vertex IDs while checking that the edge IDs indeed form a continuous path (and returns an error code if they don't). `igraph_get_k_shortest_paths()` also gained a `vertex_paths` argument. Let me know whether it's what you meant and then we can close this.

**Comment by szhorvat** [comment]
Most similar functions are named as `x_from_y` instead `convert_y_to_x`. What do you think?

**Comment by ntamas** [comment]
It's fine for me either way; I'll do the renaming and then close this issue if that's okay for you.

**Comment by ntamas** [comment]
Function renamed in 897ddade3

**Comment by szhorvat** [comment]
Fine for me either way too, I just warned you about it.
