### ISSUE TITLE
Replace `connect_neighborhood` by `graph_power`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2063]
The function `igraph_connect_neighborhood()` is somewhat naively named, and behaves naively as well.

This operation is better known as "graph power", and is well-defined for a power of 1. Currently, `connect_neighborhood` issues a warning when `order` is zero or one, and returns the unchanged graph in both cases. This warning message is not productive, and has already caused inconvenience to me.

I suggest adding a function named `igraph_graph_power()`:

 - It shows no warning for an input of one or zero.
 - For an input of one it returns the same graph.
 - For an input of zero is returns a graph with no edges. This is a reasonable generalization of the concept. In the graph raised to power `k`, vertices are connected if they are at a distance `<= k` in the original graph.
 - It produces a new graph instead of modifying the old one. **Discuss!**
 - Do we then deprecate `igraph_connect_neighborhood()` in favour of `igraph_graph_power()` or just keep both with slightly different behaviour? **Discuss!**
 - If we retain `igraph_connect_neighborhood()`, there would be room for weighted generalizations, such as connecting neighbours within a given weighted distance, which is a useful operation, but it is not necessarily appropriate to keep calling it "graph power".

I'd like to have some input about the last two points.

**Comment by ntamas** [comment]
> It produces a new graph instead of modifying the old one. 

This seems to be a recurring topic (I remember a similar discussion about vertex contraction). Here I wholeheartedly support returning a completely new graph as it is radically different from the old one in most cases (unlike with vertex contraction, where most of the graph can potentially untouched so there's more room for debate there). In my opinion this is similar to `igraph_linegraph()` where there is no debate whatsoever about returning a completely new graph.

We need to decide what to do with attributes after the operation, though.

As for keeping `igraph_connect_neighborhood()`, we will probably go through a deprecation cycle as usual, and during the cycle we are free to decide whether we want to keep the function around for a longer time than promised, in the hope of eventually implementing the weighted version as you described. All that matters during the transition is that we should aim to drive users towards the newly added `igraph_graph_power()` for cases when they are indeed looking for graph powers, and the deprecation does the job for that nicely.
