### ISSUE TITLE
Grid version of FR layout does not work properly with disconnected graphs

### ISSUE THREAD

**Issue by Vini2** [igraph/igraph#2068]
**Describe the bug**
The layout produced from `layout_fruchterman_reingold()` looks disordered when plotting large graphs with thousands of vertices.

**To reproduce**

Run the following code:

```python
from igraph import *

# Create graph
my_graph = Graph()

# Create list of edges
edge_list = [(10,3), (10,444), (8,4), (3,5), (5,4)]

# Add vertices
my_graph.add_vertices(2000)

# Add edges to the graph
my_graph.add_edges(edge_list)

# Set visual styles
visual_style = {}
visual_style["bbox"] = (3000,3000)
visual_style["margin"] = 30
visual_style["vertex_size"] = 30
visual_style["vertex_label_size"] = 12
visual_style["edge_curved"] = False

# Set the layout
visual_style["layout"] = my_graph.layout_fruchterman_reingold()

# Plot the graph
plot(my_graph, "testing.png", **visual_style)
```

Output graph `testing.png`:

![testing](https://user-images.githubusercontent.com/12206048/169202201-97c1a71e-c3ed-4615-a532-3655d92b06ce.png)

I am not sure where the issue is occurring or starting from which version.

**Version information**
I came across this issue with versions `0.9.10`, `0.9.9` and `0.9.8` from conda.

**Versions that worked correctly**
When I plot using `python-igraph` version `0.7.1.post7` from conda, I get the proper layout as shown below:

![testing_old](https://user-images.githubusercontent.com/12206048/169202293-18de5fbb-bb98-48c7-aa37-373826108e4e.png)

**Comment by szhorvat** [comment]
I made a fix that improves this, see f88495c853783cd3a38d03ea744c8e52dd9b3270 At least this will certainly make it into the next igraph version (likely a bugfix version in the 0.9 series). We'll look into more improvements later, but no promises about including them in the 0.9 series.

With 1000 iterations and 2000 isolated vertices, now I get the following:

With grid:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/169408499-a6f2f4f9-a086-4784-8bb4-1839e51f5dd9.png">



Without grid:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/169408424-60214fab-4b14-4e6c-a4ac-012a1b556c0b.png">

**Comment by Vini2** [comment]
> Use the `grid=False` option to the layout.

Thank you for the fix. For now I will use this option.

**Comment by szhorvat** [comment]
I made some additional improvements here: cbd51ae512b46b1daa78606a7836d4fc090f55a4

I check the FR paper and they state that the grid version does not need any special treatment of disconnected graphs. This, with the above fix, I am closing this.
