### ISSUE TITLE
Potential conflict with CXSparse

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2069]
igraph 0.10 brings its own embedded CXSparse, customized to use `igraph_integer_t` internally. However, the type names and the functions names of this internal CXSparse are the same as for the standard CXSparse.

igraph headers have `struct cs_dl_sparse` and the static library will have symbols such as `cs_dl_add()`. This means that igraph potentially conflicts with CXSparse itself. In what circumstances this conflict can manifest itself is unclear, but I expect that there may be trouble when both libraries are linked statically into an application. I don't expect problems with dynamic linking.

There is a high likelihood that CXSparse and igraph would be used together in some project.

There is also a high chance that distro maintainers would complain about the current situation. For example, vcpkg were concerned about igraph embedded its own BLAS. The embedded BLAS prefixes all symbol names with `igraph` so it can't cause conflict. We should do something similar with CXSparse.

CXSparse is already partially templated internally. All symbol names have the form of `cs_XX_something` where `XX` can be either `di` or `dl`. The _implementation_ is fully templated while the function prototypes are not.

I propose changing the embedded CXSparse to use a unique identifier in place of `XX`, for example, "igraph".

Obviously, this should be done before 0.10.

**Comment by szhorvat** [comment]
Note that the reason we went with using `dl` (and just changing the underlying type) was that this could be done with a very minimal modification of the sources. It is preferable to make as few changes as possible so that future updates are easy. Luckily, 

 - CXSparse receives very few updates
 - Changes are likely to be in the implementation part (not the headers/declaration), which we don't need to touch

Therefore providing our own copy of prototypes in headers is unlikely to being high maintenance costs.

I would also recommend _renaming_ the headers to reduce the chance of accidentally picking up external headers. Some Linux distros already have patches (even if unneeded!!) to use _only_ external CXSparse headers. These patches are guaranteed to mess up things for 0.10. Renaming headers would at least fix this and discourage "unbundling patches".

**Comment by vtraag** [comment]
I'm not exactly sure what you have in mind here? Are you perhaps thinking of something like the following?

We simply change the definition of `CS_NAME` here to (for instance) `cs_igraph`.

https://github.com/igraph/igraph/blob/8a348d247b983c0fcfe2d69c54f2641bf91abced/vendor/cs/cs.h#L623

And then also perform a replace and find of the `cs_dl_*` declarations in `cs.h` to change them into `cs_igraph_*`.

Or are you thinking of something else?

**Comment by szhorvat** [comment]
Yes, you understood it correctly.

**Comment by ntamas** [comment]
> Except that I wouldn't just do a find and replace on the existing part of the header, but add a full copy of the cs_igraph variant.

So, basically, do you suggest copying the existing `igraph/vendor/cs/cs.h` as `igraph/vendor/cs/cs_igraph.h`, do the modifications there and use that?

**Comment by szhorvat** [comment]
Yes.

**Comment by ntamas** [comment]
I don't think it's gonna work because all CXSparse source files start with `#include "cs.h"` so they won't pick up our custom modifications if we add them to a separate `cs_igraph.h` -- unless we replace all occurrences of `cs.h` witj `cs_igraph.h`. At this point I think it would be simpler to do the modifications in `cs.h` and document where the original `cs.h` came from.

We'd have two options:

1. Take `cs.h` and trim it down so it does not include any unnecessary fluff (int / complex variants of CXSparse), just the `cs_dl` variant that we actually use, renamed to `cs_igraph`.
2. Extend `cs.h` with sections guarded by a `CS_IGRAPH` macro, and we require `CS_IGRAPH` to be defined before including `cs.h`.

Since, as you said, CXSparse is not likely to change much (it is pretty much unchanged since 2017 even though SuiteSparse is regularly getting new releases), I don't see much risk in simply going for option 1. A branch with a trimmed-down `cs.h` is committed as `refactor/avoid-cxsparse-conflict` if you want to take a look.

**Comment by szhorvat** [comment]
There are two examples which include `cs.h`, and mess with the internals of `cs_igraph_sparse`: 

```
examples/simple/igraph_sparsemat3.c
examples/simple/igraph_sparsemat4.c
```

There is also one test:

```
tests/unit/igraph_sparsemat2.c
```

I have not looked at them in detail. If you have time, can you check if these can be easily refactored so that they would not access these internals, without compromising the effectiveness of the test? If not, the examples must be moved to tests, as examples cannot depend on internals.

**Comment by szhorvat** [comment]
I thought a bit more about renaming `cs.h`. I suggested this to provide a bit of extra protection against accidentally including an external `cs.h`, either because we make a mistake, or because a distro maintainer makes changes. However, igraph won't compile with an external `cs.h` as it won'y define `cs_igraph_sparse`. So we already have that protection. Renaming `cs.h` wouldn't provide any benefit.

**Comment by szhorvat** [comment]
Sounds good to me.

**Comment by ntamas** [comment]
Merged, thanks.
