### ISSUE TITLE
psumtree_search() returns element with zero weight

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2080]
**Describe the bug**

`igraph_psumtree_search()` will sometimes return elements of zero weights. This is problematic, since this function is used to sample from discrete probability distributions, and zero probability elements should never be produced.

This happens when the first element in the `psumtree` has weight zero and we pass a search value of zero to `psumtree_search()`.

Originally reported on the forum: https://igraph.discourse.group/t/question-about-the-functionality-of-partial-sum-trees/1229

**To reproduce**

```c
#include <igraph.h>
#include <stdio.h>

int main() {
    igraph_psumtree_t sumtree;
    long int i;
    
    igraph_psumtree_init(&sumtree, 100);
    igraph_psumtree_update(&sumtree, 44, 1.0);
    igraph_psumtree_update(&sumtree, 55, 1.0);
    igraph_psumtree_update(&sumtree, 66, 1.0);
    igraph_psumtree_search(&sumtree, &i, 0.0 /* <-- search value */);

    printf("Index: %ld\n", i);

    igraph_psumtree_destroy(&sumtree);

    return 0;
}
```

For a search value of 0.0, this returns index 0, which has weight 0.

For the intervals (0, 1], (1, 2], and (2, 3], it returns 44, 55 and 66, respectively. Notice that the intervals are closed from the right.

It would be more productive to use the intervals [0, 1), [1, 2) and [2, 3) instead, i.e. closed from the left. This is how standard real-valued RNGs work: they sample from [lo, hi), and it is a value from such an interval that will be passed to `psumtree_search()`.

**Version information**

Reproducer is for current `master`, but present on `develop` as well.

**Comment by szhorvat** [comment]
The fix for the psumtree functions is and easy one-liner, but it appears that we're using psumtrees with all-zero values, which is not okay.

**Comment by szhorvat** [comment]
It is practically useful to be able to sample from a distribution where all probabilities are set to zero, and treat it is as uniform. While seemingly mathematically nonsensical, when this situation occurs in algorithms, it is sometimes sensible in a sense of limits.

That said, this can't be implemented at the level of the psumtree in any reasonable way. Before fixing this issue, the psumtree would simply return the first element when all weights were zeros, while doing uniform sampling is what practical applications would require. Thus I'll be updating this code in the caller instead.

**Comment by szhorvat** [comment]
@ntamas Please have a look at the fix. I added the asserts so that if something goes wrong, we know what happened. Can you update R/igraph and py-igraph so that their test suites can be run with this fix please?

**Comment by ntamas** [comment]
Updated; tests are being executed now. If anything breaks I'll let you know. The fix looks good for me.

**Comment by szhorvat** [comment]
I changed the preferential attachments models so that if the all already added vertices have zero attractiveness for some reason, one is chosen uniformly to connect to. I didn't add a warning for this case, but we can do it if needed. This situation usually occurs when degenerate parameters are passed in, e.g. zero degree and age appeal for the aging version.

**Comment by szhorvat** [comment]
Looks good, so I'll merge into develop and update the changelog. There's a KK layout-related failure on the R side, no doubt due to the recent KK fix for path graphs. It should be fine to update the expected test output for those.
