### ISSUE TITLE
"igraph_assortativity_degree()" gives -nan as the result for a complete undirected graph

### ISSUE THREAD

**Issue by valdaarhun** [igraph/igraph#2089]
Hi. I found this issue while playing around with the assortativity functions.

**Describe the bug**
`igraph_assortativity_degree()` gives `-nan` instead of 1 as the assortativity for a complete graph with undirected edges.

**To reproduce**
The following code example can demonstrate the issue.
```
#include <igraph.h>
#include <stdio.h>

#define NUMBER_OF_NODES 5

int main() {
    igraph_integer_t nodes = NUMBER_OF_NODES;
    igraph_t g;
    igraph_vector_t res;
    igraph_vector_init(&res, nodes);

    igraph_full(&g, nodes, /* Undirected */ IGRAPH_UNDIRECTED, /* No loops */ IGRAPH_NO_LOOPS);
    igraph_degree(&g, &res, igraph_vss_all(), IGRAPH_ALL, /* No loops */ IGRAPH_NO_LOOPS);
    igraph_vector_print(&res);

    igraph_real_t assortativity;

    igraph_assortativity_degree(&g, &assortativity, /* undirected */ IGRAPH_UNDIRECTED);
    printf("Assortativity: %g\n", assortativity);

    igraph_vector_destroy(&res);
    igraph_destroy(&g);
}

```

The output I get is:
```
4 4 4 4 4
Assortativity: -nan
```

**Version information**
I built igraph from source using the latest master branch (`0.9.9` with `2f79050` being the latest commit).

**Other information**
I went through the implementation of the assortativity function and found that the denominator in [this line](https://github.com/igraph/igraph/blob/master/src/misc/mixing.c#L221) becomes zero for a complete undirected graph. I believe that's why `-nan` is returned as the result.

**Comment by valdaarhun** [comment]
I would like to work on resolving this issue.

**Comment by szhorvat** [comment]
Assortativity is the Pearson correlation of the degrees of edge endpoints. In a complete graph, all degrees are the same, so the correlation is not meaningful. The formula leads to 0/0, which is where the NaN comes from.

I think this is a reasonable result in this case.

Mathematica returns 0 for such cases, but I find this misleading. Generally, it is reasonable to think that making a small change to the graph will result in a small change in its degree assortativity. But by making a small change to a large regular graph, we can create basically any assortativity value.  I think that NaN is a good representation of this unpredictable behaviour.

**Comment by szhorvat** [comment]
I clarified the docs a bit and will close this issue now, but feel free to continue the conversation.

**Comment by valdaarhun** [comment]
> But by making a small change to a large regular graph, we can create basically any assortativity value (depending on what the change was). I think that NaN is a good representation of this unpredictable behaviour. In my mind, this situation is analogous to a limit which can take different values depending on which direction we approach it from (i.e. we can get any value depending on what small modification we make to a regular graph).

Ah, I have now understood what you mean. I think I initially got confused because while reading up on assortativity I had seen a statement in [this paper](https://www.nas.ewi.tudelft.nl/people/Piet/papers/JCN2015AssortativitySurveyRogier.pdf) (page 6) which stated that a complete graph is perfectly assortative.

> In a perfectly assortative network, all nodes are connected to other node(s) of the same type, e.g. same
degree. One example is a complete network, where all nodes are connected to all other nodes and all
nodes have degree d(i) = N - 1. For such network, degree assortativity is maximal, ρ(D) = 1.
