### ISSUE TITLE
Add 'mode' argument for eigenvector_centrality

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2095]
**What is the feature or improvement you would like to see?**

`eigenvector_centrality` computes the left eigenvector of the adjacency matrix. In order to have more control over its behaviour, the `directed` argument should be replaced with a `mode` argument.

**Use cases for the feature**

This is one of the few functions that takes edge directions into account yet cannot treat edges as "reversed".

**References**

 - https://github.com/igraph/igraph/issues/1470#issuecomment-694974841

**Comment by szhorvat** [comment]
I suggest that `mode=OUT` would refer to the current behaviour. One way to phrase this that the score of a vertex is proportional to the scores of vertices pointing to it (which appears to refer to incoming edges). However, another way is that the scores propagate along edge directions. In all other functions which can be phrased in terms of linear algebra, `OUT` means that we multiply the adjacency matrix from the left. It should be the same here.

**Comment by clpippel** [comment]
An alternative is to add an extra parameter eigen=left (the current behaviour) or eigen = right.

**Comment by GroteGnoom** [comment]
```
eigenvector_centrality computes the left eigenvector of the adjacency matrix. In order to have more control over its behaviour, the directed argument should be replaced with a mode argument.
```
So you want full `igraph_neimode_t` usage, including `IGRAPH_ALL` to treat the graph as undirected?

**Comment by szhorvat** [comment]
Yes. But I think this is very low priority.

**Comment by GroteGnoom** [comment]
> Yes. But I think this is very low priority.

It's one of the 0.11 milestones, so I thought this would have at least higher priority than non-milestoned issues.

**Comment by szhorvat** [comment]
Yes, it's a breaking change, so if we do it, it has to be done by 0.11. If you think it can be done very quickly, it would be nice.

**Comment by szhorvat** [comment]
Let's think a little bit.

Eigenvector centrality is not very useful for directed graphs, except under specific conditions (such as strongly connected graphs). Many people misuse it by applying it to directed graphs inappropriately. The usual alternatives for directed graphs are hub and authority score.

We already have an efficient way to reverse the graph in 0.10.

There is already a `directed` argument for eigenvector centrality.

Having to run this function for both directions on a very large graph is am extremely niche use case. Therefore I'd say this is a very low priority. If it happens before 0.11, nice, if not, it's perfectly fine not to have this feature.

**Comment by GroteGnoom** [comment]
Ah, I interpreted the 0.11 milestone as 'has priority over issues without a milstone, but lower priority than 0.10.x'.
I don't really know how to use 'if we do it, it has to be done by 0.11', because it means it can just as well be done before '0.12'.
Should I look at wishlist or todo labels? Or just treat issues with a 0.10.x milstone as important, and not conclude anything about priorities for the others?

**Comment by szhorvat** [comment]
Well, the hope was that there would not be a 0.12 but we go straight for 1.0 (although that's looking less likely). If we don't get this done for 1.0, then we have to drop it.

I should have indicated (and thought through) more clearly that this is low priority. But it's not pointless, so if you like, feel free to go ahead.

**Comment by szhorvat** [comment]
I consider this low-priority, re-targeting for 2.0.

**Comment by szhorvat** [comment]
This is done.
