### ISSUE TITLE
Confusing messages from eigenvector_centrality()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2096]
`igraph_eigenvector_centrality()` will issue a cryptic warning when the input is directed and weighted. [This is confusing to users](https://igraph.discourse.group/t/what-is-the-meaning-of-warning-c-348-in-eigen-centrality/1266) and it should be improved in some way.

The main issue with eigenvector centrality is that there may not be a unique non-negative solution for all graphs. The use of this measure is typically justified through [the Perron-Frobenius theorem](https://en.wikipedia.org/wiki/Perron–Frobenius_theorem), which gives sufficient (but not necessary) conditions for a unique non-negative solution.

The TODO list for this issue is:

 - Review mathematical results which are relevant for when eigenvector centrality is meaningful. Please add any references here.
 - Include the gist of it in the documentation, try to provide easy-to-follow guidance in the documentation.
 - Decide what warnings are useful, to protect inexperienced users from getting invalid results.

**Comment by szhorvat** [comment]
Here's what I could gather from the Wikipedia article. The relevant section is here: https://en.wikipedia.org/wiki/Perron%E2%80%93Frobenius_theorem#Non-negative_matrices

 - If the matrix entries are non-negative, there will be a non-negative real eigenvalue of largest magnitude, and a corresponding eigenvector with non-negative entries. However, it may not be unique.
 - If the graph is strongly connected, there will be a unique positive real eigenvalue of largest magnitude. There may be other eigenvalues of the same magnitude, but they will not be positive real. This way we can define a unique solution (and the current code obtains it, as it looks for the eigenvalue which has the largest real part, i.e. passes `LR` to ARPACK).

If the graph is undirected and disconnected, then I would not consider eigenvector centrality meaningless. The components are effectively independent of each other. Each one, when considered in isolation, would have its own largest eigenvalue. The largest eigenvalue of the entire graph is the largest of these (and may be degenerate when two components have the same eigenvalue). The other components will get all-zero centrality scores. Thus _even when there is a unique solution (which is not guaranteed)_ the result is not meaningful. This is already documented.

If the graph is directed, weakly connected, but not strongly connected, then the situation is more complicated. The largest positive real eigenvalue may or may not be degenerate. Furthermore, we can get all-zero eigenvalues, which happens for directed acyclic graphs. Suppose that there is a unique positive eigenvalue: does this mean that the result is meaningful and interpretable? Looking at the example of the undirected disconnected case, I am not confident that it is, although I do not have a clear understanding.

If any matrix entries are negative, then all bets are off and there may not even be real eigenvalues.

----

Based on all of this, it would make sense to show a warning (not error) when:

 1. some weights are negative
 2. graph is not strongly connected
 3. some weights are zero (as this makes it possible for the graph to be _effectively_ disconnected)

1 and 3 are easy checks, but 2 is time consuming. Perhaps one option is to have a boolean argument that can be used to disable check 2? High-level interfaces would do the check by default, but it could be disabled for performance, if needed. Somehow I don't like this idea very much: this means reducing performance by default to protect inexperienced users from mistakes.

**Comment by ntamas** [comment]
I'm not really in favour either of adding time-consuming checks in the C layer just to protect inexperienced people from mistakes. The other two checks seem to make sense and they have low computational cost (basically it's an `igraph_vector_min()` call and two comparisons).

**Comment by szhorvat** [comment]
Someone should benchmark how much time the strong connectedness check takes compared to the centrality computation. If it doesn't take much, we include it, otherwise we document caveats and that's that. I'm targeting this for 0.9.11 as there's minimal difference between 0.9 and 0.10 for this function, and this issue was triggered by a complaint about the R interface.

**Comment by szhorvat** [comment]
Here's a very rough benchmark in Python:

```
In [4]: g = ig.Graph.Erdos_Renyi(n=1000000,m=3000000, directed=False)
```

```
In [9]: %time g.is_connected()
CPU times: user 560 ms, sys: 2.6 ms, total: 563 ms
Wall time: 563 ms
Out[9]: False

In [10]: %time g.is_connected()
CPU times: user 394 ms, sys: 1.36 ms, total: 396 ms
Wall time: 396 ms
Out[10]: False

In [11]: %time g.is_connected()
CPU times: user 410 ms, sys: 2.32 ms, total: 413 ms
Wall time: 413 ms
Out[11]: False

In [12]: %time g.is_connected()
CPU times: user 398 ms, sys: 1.35 ms, total: 399 ms
Wall time: 399 ms
Out[12]: False

In [13]: %time ec=g.eigenvector_centrality();
CPU times: user 32.2 s, sys: 1.06 s, total: 33.3 s
Wall time: 5.03 s

In [14]: %time ec=g.eigenvector_centrality();
CPU times: user 32.3 s, sys: 1.1 s, total: 33.4 s
Wall time: 4.87 s

In [15]: %time ec=g.eigenvector_centrality();
CPU times: user 31.9 s, sys: 866 ms, total: 32.8 s
Wall time: 4.72 s
```

Directed case:

```
In [16]: g = ig.Graph.Erdos_Renyi(n=1000000,m=3000000, directed=True)

In [17]: %time g.is_connected()
CPU times: user 1.27 s, sys: 21.6 ms, total: 1.29 s
Wall time: 1.29 s
Out[17]: False

In [18]: %time g.is_connected()
CPU times: user 1.09 s, sys: 10.8 ms, total: 1.1 s
Wall time: 1.1 s
Out[18]: False

In [19]: %time g.is_connected()
CPU times: user 1.2 s, sys: 9.76 ms, total: 1.21 s
Wall time: 1.2 s
Out[19]: False

In [20]: %time g.is_connected()
CPU times: user 1.24 s, sys: 9.74 ms, total: 1.25 s
Wall time: 1.25 s
Out[20]: False

In [21]: %time g.is_connected()
CPU times: user 1.12 s, sys: 9.16 ms, total: 1.13 s
Wall time: 1.13 s
Out[21]: False

In [22]: %time ec=g.eigenvector_centrality();
CPU times: user 48.5 s, sys: 1.03 s, total: 49.6 s
Wall time: 6.87 s

In [23]: %time ec=g.eigenvector_centrality();
CPU times: user 47.7 s, sys: 1.15 s, total: 48.9 s
Wall time: 6.84 s

In [24]: %time ec=g.eigenvector_centrality();
CPU times: user 46.4 s, sys: 1.29 s, total: 47.7 s
Wall time: 6.69 s
```

This was with python-igraph 0.9.11 from conda on macOS. I think it uses a new ARPACK and probably OpenBLAS (??). Notice that the "user" time is much higher than the wall time.

I also tried with MacPort's version, which uses macOS's own BLAS/LAPACK (vecLib). The wall times are the same, but the user time is much lower: it consumes less resources. Example from the undirected case:

```
In [8]: %time ec=g.eigenvector_centrality();
CPU times: user 9.25 s, sys: 164 ms, total: 9.42 s
Wall time: 4.58 s
```

Anyway, overall the performance hit can be as bad as ~10% or so. I find that to be too much. I won't add a connectedness check.
