### ISSUE TITLE
Ensure that all functions are tolerant to bad input

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2099]
This issue is to make sure that all functions tolerate bad input, i.e. if the input it unsupported or invalid, igraph should not crash and should not produce invalid results. Instead, it should return with an error.  In particular, functions that do not support non-simple graphs should check for them.

We are very close to the finish line with this, thus adding to the 0.10 milestone. Being able to say that users don't need to worry about passing in bad input and getting bad results will be a major PR win, as many other libraries are much sloppier with this.

See the last paragraph of this doc section:

https://igraph.org/c/html/latest/igraph-Basic.html#igraph-data-model

I do not recall which exact functions do not check for non-simple graphs, but each of them should already have a note in their documentation. The most notable case if the VF2 algorithm, which can probably be fixed, but as I recall, the fix is blocked by #2066.

Of course #1219 is a blocker for this issue as well.

----

 - [x] `igraph_layout_lgl()` produces incorrect layouts for disconnected graphs
 - [x] VF2 functions do not work on non-simple graphs
 - [x] ~`isomorphic_small`, should check vertex count and directedness~ (not relevant any more, it is internal and the caller validates)

**Comment by szhorvat** [comment]
The following needs to be verified, but as I remember, VF2 might be fixable for _loops_ (not multi-edges) by counting loops once both in degrees and adjlists. Of course a better approach would be a read the VF2 paper and figure out if we can add proper multigraph support, but that takes a lot longer.

**Comment by ntamas** [comment]
I think this is going to be an "ongoing issue" as we can never claim that "now all functions are tolerant to bad input" if we keep on adding new stuff :) So let's decide what to do with the current ones before 0.10; if these are done, we can move this issue to the next milestone.

- [X] `igraph_layout_lgl()` does not crash on disconnected graphs, now it prints a warning and the requirement is documented, so it should be OK.
- [ ] VF2 should probably check for the presence of loop edges, and, if we can do a similar check for multiple edges in a reasonable amount of time, then it should also do so for multiple edges. Other than that, I wouldn't attempt to fix anything for 0.10 or to add loop edge support, that can be left for 0.11.

**Comment by szhorvat** [comment]
But checking only for loops is neither here nor there. If I see that a function complains about loops but not about multi-edges, it is entirely reasonable to assume that it supports multi-edges. In the end it's more confusing than it was.

**Comment by ntamas** [comment]
It is documented that the function supports simple graphs only. We are being polite to the user by checking whether the graph contains loop edges; in my opinion, it's not worse than before when we probably simply returned invalid results in the presence of loop edges.

So, looking from a different angle:

* if the user did not bother to read the documentation and used a graph with loop edges before, he probably received incorrect results; now he gets an error code, so that's a net win
* if the user did not bother to read the documentation and used a graph with multiple edges before, he probably received incorrect results. The same thing happens with this implementation as well, so there's no substantial gain but we didn't make the situation worse

**Comment by ntamas** [comment]
Now that we have caching for `igraph_has_multiple()`, would it make sense to reconsider and add a check in `igraph_i_perform_vf2_pre_checks()`?

**Comment by szhorvat** [comment]
I don't know. What is the most common usage scenario?  Test a single graph many times?  Or test a different graph each time?

Let me try to think up few scenarios:

 - Suppose we have a list of graphs and we want to remove isomorphic duplicates. VF2 is not a good choice because it would require doing pairwise comparisons, so it's O(n^2) in the list size. The way to go is to canonicalize with Bliss, which makes this O(n log n).

 - One good use case for VF2 is handling multigraphs through `simplify_and_colorize()`. We can make `simplify_and_colorize()` set the cache, so VF2 can make use of the cached info.

 - Another good use case is subgraph isomorphism, where it's common that the same pattern is search in multiple large graphs; or more likely, different patterns are searched for in the same large graph. The check for at least one would be saved.

Any other thoughts? No this does not answer your question, but it's at least a starting point.

**Comment by ntamas** [comment]
> it's common that the same pattern is search in multiple large graphs

I guess in that case we would not benefit much from caching because each large graph is tested only once, and the time required to find multi-edges in a large graph is significantly larger than the time we save by _not_ testing for multi-edges multiple times in the small (template) graph due to caching.

**Comment by szhorvat** [comment]
Personally, I encounter searching for several patterns in the same large graph more often. But that is just my personal experience. This is also what `igraph_is_perfect` does, although that function uses LAD internally, not VF2.
