### ISSUE TITLE
Support bipartite networks

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#21]
First I need to find a way to represent them. Basically you need to use attributes, there is no other way. But that means that at the C level they will look quite nasty, for every function that deals with bipartite networks, there will be an extra argument that gives the vertex types.

This is what is left:
- [ ] Bipartite warnings

Look over all functions and add warnings for the ones that should behave differently for bipartite graphs, but they don't. This is a huge task....
- [ ] Configure bipartite warnings

Add an option, to optionally suppress the warnings introduced in 1. It is not yet decided whether these warnings should be on by default or not.
- [ ] Bipartite layout algorithms #235 
- [ ] Bipartite modularity #194 
- [ ] Bipartite configuration model samples #341 
- [ ] Bipartite transitivity #344 
- [ ] Bipartite community detection

1 Module identification in bipartite and directed networks
Roger Guimerà, Marta Sales-Pardo, and Luís A. Nunes Amaral
http://www.pubmedcentral.nih.gov/articlerender.fcgi?tool=pubmed&pubmedid=17930301

2 Michael J Barber: Modularity and community detection in bipartite networks,
Phys Rev E 76 066102
http://pre.aps.org/abstract/PRE/v76/i6/e066102

---

Imported from Launchpad using lp2gh.
- date created: 2008-10-27T16:05:25Z
- owner: gabor.csardi
- assignee: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/289924

**Comment by CalmJerome** [comment]
Excuse me~ I have a question about the bipartite community detection. Is it possible to apply community_multilevel to a bipartite graph like
“ g = igraph.Graph.Incidence(data.tolist(), multiple=True)
   fc = igraph.Graph.community_multilevel(g) ”？

**Comment by vtraag** [comment]
@CalmJerome, yes, it is possible to apply `community_multilevel` to bipartite graphs. However, this method does not take into account that the graph is bipartite, so the null-model that is used in the modularity calculations may not be appropriate. See also [Barber (2007)](https://doi.org/10.1103/PhysRevE.76.066102).

For an approach that does consider properly whether a graph is bipartite or not, see https://leidenalg.readthedocs.io/en/latest/multiplex.html#bipartite.

P.S. Note that this is the issue tracker for `igraph`, not for `python-igraph`. Please use that [issue tracker](https://github.com/igraph/python-igraph/issues) to report issues. Also, this would be a support question, for which it may be better to use the [mailinglist](https://lists.nongnu.org/mailman/listinfo/igraph-help) or post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/igraph).

**Comment by CalmJerome** [comment]
@vtraag Thanks very much for answering! I will do it next time!

**Comment by BrandonKMLee** [comment]
@gaborcsardi
Just a note that CDLib/NetorkX may or may not have such features included
This is something similar to https://github.com/GiulioRossetti/cdlib/issues/178#issuecomment-937997820
