### ISSUE TITLE
interconnected_islands_game() produces multi edges

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2105]
**Describe the bug**

`interconnected_islands_game()` produces multi edges between islands. It is unclear if this was intended—probably not.

As a reminder, this function created identically-sized G(n,p) random graphs, then connected them with a given number of edges in a G(n,m) manner. Multi-edges may appear when connecting the islands together.

**To reproduce**

In R, run this a few times and note the multi-edges:

```
plot(interconnected.islands.game(3,3,0,5))
```

**Version information**

All versions up to current `develop`.

**Comment by ntamas** [comment]
Documentation added in 17250da25

**Comment by szhorvat** [comment]
Fixed on `develop` in b702036e68c73381f3fbccb8cd9df9ce51c7f738. Then this won't go on `master` @ntamas? I don't think it's necessary but make sure the fix is in the appropriate part of the changelog.

**Comment by ntamas** [comment]
Too much fuss to get this into `master` for too little gain; I expect 0.10 to be out soon.
