### ISSUE TITLE
Definition of metrics should be given in docs of compare_communities

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2106]
The precise definition of each metric should be given explicitly in the docs of `igraph_compare_communites()`. There are variations on these metrics, so it's important to be precise, even if there's a citation.

 - [x] variation of information
 - [x] normalized mutual information
 - [x] split-join distance
 - [ ] the Rand index
 - [ ] adjusted Rand index

If this is done before the 0.10 release, it should go on `master`.

**Comment by szhorvat** [comment]
The first three are done in 7dcf4b51727ca7785b4c37daa569202b9a1b788b

@vtraag Let me know if you're familiar with the Rand index and can do it without too much effort. I won't touch this until then.

**Comment by szhorvat** [comment]
Never mind, there's enough info in the comments. I'll do it.

**Comment by ntamas** [comment]
Docs about the Rand index are added in 3d2322076.
