### ISSUE TITLE
binsearch in empty vector is claimed to be buggy

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2108]
I found a comment in the sources next to a use of `vector_binsearch2()`:

> We don't search an empty vector, because vector_binsearch seems to have a bug with this.

https://github.com/igraph/igraph/blob/master/src/properties/multiplicity.c#L340

We should verify the behaviour of binsearch, and fix the function or update its documentation if necessary.

**Comment by szhorvat** [comment]
Thanks for checking! Yes please, do that and remove the commit.

**Comment by ntamas** [comment]
Fixed both in `master` and `develop`
