### ISSUE TITLE
Transition to ranges using exclusive endpoints

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2118]
All functions that operate with ranges should use exclusive endpoints, i.e. `[start, end)`. Currently, functions with `seq` in the name use inclusive endpoints `[from, to]`.

Targeting for 0.10, as suggested by @ntamas and @GroteGnoom in #2115.

The following `seq` functions will be deprecated and will be replaced by a `range` function that uses exclusive endpoints. Please add to this list if necessary.

 - [x] `igraph_vs_seq()`, `igraph_vss_seq()`
 - [x] `igraph_es_seq()`, `igraph_ess_seq()`
 - [x] `igraph_vector_init_seq()`.
 - [ ] Add `igraph_vector_range()`, an equivalent function that uses an initialized vector instead of allocating a new one?
 - ... ?

I suggest using a different parameter naming for the range endpoints: 

 - for closed ranges let's keep `[from, to]`
 - for right-open ranges let's use `[start, end)`

This will reduce confusion.

**Comment by ntamas** [comment]
Commit 86c8abbcc also references this issue

**Comment by szhorvat** [comment]
> Re the design of `igraph_vector_range()`, there is an open question: shall we use two parameters (`start` and `end`)

I prefer two parameters + resize. This is cleaner.

**Comment by szhorvat** [comment]
I skimmed through the commit, and it looks like the internal of `igraph_vs/es_t` are not refactored. They still use `from`/`to` instead of `start`/`end`. However, `igraph_vit/eit_t` uses `start`/`end`, so now there's  conversion from exclusive range to inclusive and back.

This disadvantage of this is that inclusive ranges cannot be empty. Depending on where the error checks are done, empty ranges may now be rejected with an error.

It would be great to also refactor the internals `vs/es_t` to use exclusive ranges. This way we don't lose anything (such as the maximum range length) as `vit/eit_t` already use exclusive ones.

**Comment by ntamas** [comment]
Absolutely, this is the next step, I will do it tomorrow.
