### ISSUE TITLE
Replace igraph_isomorphic_34() with isomorphic_small()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2124]
We have an isomorphism testing function `igraph_isomorphic_34()` which handles 3- and 4-vertex graphs.

Now everything is in place to also handle 5 and 6 vertex undirected graphs as the "isoclass" functionality has been implemented for these. But the naming of `igraph_isomorphic_34()` does not support these.

I suggest renaming `igraph_isomorphic_34()` to `igraph_isomorphic_small()` (through the usual deprecation route).

**Comment by ntamas** [comment]
Agreed. But the implementation is already correct, right? (I.e. it already works for undirected graphs with 5 or 6 vertices).

**Comment by szhorvat** [comment]
It should also be checked that the directedness is the same.

I think on high-level interfaces expose this function, so the lack of checks is not a big deal. But it's part of `functions.yaml` now so it should be well-behaved.

**Comment by ntamas** [comment]
I was wondering whether `igraph_isomorphic_small()` should be exposed at all. `igraph_isomorphic()` already takes care of 1) testing directedness, 2) looking for self-loops and 3) calling `igraph_isomorphic_small()` if the directedness and the graph size are both suitable. Do we need a separate entry point?

I'd rather say that `igraph_isomorphic_small()` is not exposed and documented, and we simply deprecate `igraph_isomorphic_34()`, pointing users at `igraph_isomorphic()` instead.

**Comment by szhorvat** [comment]
Yes, that makes sense, however, I would suggest _also_ pointing people to `igraph_isoclass()`. I.e., don't remove the docs, instead add guidance on how to update the functions.

**Comment by ntamas** [comment]
Done in 6494bbe571500b7c81dead2b5787228217fed490
