### ISSUE TITLE
adjlist_init() should make use of the cache

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2125]
As I recall, using `IGRAPH_NO_MULTIPLE` in `igraph_(lazy_)adjlist_init()` has a noticeable performance impact on some functions. Do you remember the details @GroteGnoom ?

This function is an excellent candidate for using the cached "multiedges" property. If there are no multi-edges, there is no need to run the multi-edge removal code.

Conversely, since `igraph_adjlist_init()` with `IGRAPH_NO_MULTIPLE` effectively checks for multi-edges, this is a good place to set the cache.

I suggest doing this in 0.10.x for x > 0 after the initial cache implementation has been battle tested.

**Comment by ntamas** [comment]
Removing stale label as we have a pending PR linked to this issue.
