### ISSUE TITLE
is_multiple() and is_mutual() should set cache

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2130]
`is_mutiple()` and `is_mutual()` perform the work of `has_multiple()` and `has_mutual()`, thus they should set the cache.

**Comment by ntamas** [comment]
It still feels like premature optimization for me. `igraph_is_multiple()` has additional arguments, so we should only mess with the cache if we know that `igraph_es_t` is an "all" selector; furthermore, if we add more arguments later for whatever purposes, those might still affect whether we want to update the cache or not.

**Comment by szhorvat** [comment]
Feel free to close this if you like.

There are much better candidates to set the cache from. These two functions are not the top priority.
