### ISSUE TITLE
Change igraph_bool_t to smaller type

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2131]
`igraph_bool_t` is now an `int`. It should be changed to a smaller, ideally 8-bit type, for efficiency. This will be done for 0.10.

 - [x] Decide on the type to use (decision: we use C99 `bool`).
 - [x] Does it require changing the `printf` format specifier? Will it continue to work with `%d`? If yes, docs need to be updated. (checked: `%d` is still okay, no need for a doc update)
 - [x] Make it possible to select the type at configure type, as we likely need to continue supporting `igraph_bool_t = int` for the R interface. R's native boolean is an `int`. (Decision: the R interface will override the bool type by providing a hand-crafted `igraph_config.h`, which we will need anyway due to the integer type and the complications of merging the CMake-based build with R's build system. We provide no official way in the CMake configuration to change the bool type to discourage people from changing it).
 - [x] Carry out the change, run unit tests (done, everything passes)
 - [x] Run static analysers and see if they find any new issues after the change.

Possible but non-urgent refactorings:

 - [ ] Change uses of raw `char` arrays which are meant as a space-saving Boolean vector to an actual `igraph_vector_bool_t`

**Comment by GroteGnoom** [comment]
Are we sure it's more efficient? And efficient in what way? See also: https://stackoverflow.com/questions/9521140/char-or-int-for-boolean-value-in-c

**Comment by ntamas** [comment]
Some benchmarks here (I haven’t had the time to read it thoroughly):

https://stackoverflow.com/questions/70366810/what-is-faster-bool-or-an-integer-type

I think that space savings is more important in our case than raw performance as we don’t really use bools in performance-critical code, do we?

T.

**Comment by szhorvat** [comment]
Something to think about is whether we should use the C99 native boolean type. This should bring benefits, such as compiler checks.

 - https://en.cppreference.com/w/c/types
 - https://en.cppreference.com/w/c/types/boolean

**Comment by szhorvat** [comment]
I tried changing `igrah_boolean_t` to C99 `bool`. Everything compiles after the above two fixes, but Sugiyama and bipartite layout tests fail.

**Comment by szhorvat** [comment]
@ntamas Have a look at the above commit. It looks like it was meant to be `(igraph_bool_t) (i/2)` but it was `( (igraph_bool_t) i ) / 2`.

**Comment by szhorvat** [comment]
No new warnings from Clang 14 / GCC 12, no new warnings from Clang Static Analyzer (with Clang 14).

**Comment by ntamas** [comment]
The fix in b874614 is correct. Also, I was thinking about changing `igraph_bool_t` to C99 `bool` all along now that we aim for C99 support only, and I simply trust the compiler to just Do The Right Thing when optimizing operations with `bool` types. It might even be the case that `igraph_bool_t` ends up _not_ being 1 byte long on some compilers (the C standard only declares that `bool` must be large enough to hold 0 or 1, nothing else).

**Comment by ntamas** [comment]
Clearing milestone; the only remaining check box to be ticked is not relevant for 0.10. (Alternatively, let's make that a separate issue and close this one).
