### ISSUE TITLE
CMake error: The version number detection failed with: HEAD-HASH-NOTFOUND

### ISSUE THREAD

**Issue by ahonorat** [igraph/igraph#2132]
Hello,

I have downloaded the source code of the last igraph version (0.9.9) from the assets of the last git release:
https://github.com/igraph/igraph/releases/tag/0.9.9
However, when trying to install thanks to this source code I got the following error (via cmake):
> The version number detection failed with: HEAD-HASH-NOTFOUND

The installation is working fine if using the main release asset (not the ones labelled "Source code"). But having the whole source code is good too.

I guess simple workarounds exist by manually setting some variables in the CMakeList file, but I did not tried.

-- edit:
Installation is successful with the main asset.

**Comment by szhorvat** [comment]
> The installation is working fine if using the main release asset (not the ones labelled "Source code"). But having the whole source code is good too.

This is working as intended. You need to use the main release asset, which is packaged up in a way that it is ready to use. It includes the entire igraph source code.

The "source code" archives are automatically generated snapshots of the git repo, and do not include everything you need to compile igraph. AFAIK it is not possible to turn off generating these snapshots. Just ignore them.
