### ISSUE TITLE
_umul128 support check may not work when cross-compiling

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2139]
Checking for `_umul128` supports uses `check_source_runs()`:

https://github.com/igraph/igraph/blob/develop/etc/cmake/uint128_support.cmake#L7

I expect this will cause trouble when cross-compiling. Note that the CI setup of vcpkg does cross-compile to ARM with MSVC. I do not have the resources to actually check this.

Can we not use `check_source_compiles()`, @ntamas ? It's C++ so it should not accept implicitly declared functions.

**Comment by ntamas** [comment]
Changed in 039991551
