### ISSUE TITLE
Fix code scanning alert - XML external entity expansion

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2144]
Tracking issue for:
- [ ] https://github.com/igraph/igraph/security/code-scanning/1046

**Comment by ntamas** [comment]
Fixed in 87ade081 and 6ce2353fa

**Comment by szhorvat** [comment]
Doesn't this disable entity substitution completely? Wouldn't we want to disable only the loading of external entities, but still substitute standard entities?

**Comment by ntamas** [comment]
> Doesn't this disable entity substitution completely?

No, that's why I added some tests for it in `develop` to make sure.

**Comment by szhorvat** [comment]
Can you update the changelog for 0.9?
