### ISSUE TITLE
Endianness test fails when cross-compiling to macOS arm64

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2146]
This branch attempts to add a CI run that cross-compiles for arm64 on macOS: https://github.com/igraph/igraph/tree/ci/macos-arm  However, cross-compilation fails due to the endianness test. The endianness test already tries to detect cross-compilation, but this does not seem to work here.

This CI run cross-compiles by setting `-DCMAKE_OSX_ARCHITECTURES=arm64`.

Related: [macOS: CMAKE_CROSSCOMPILING not set when building arm64 binaries on a x86_64](https://gitlab.kitware.com/cmake/cmake/-/issues/21885)

Failure: https://dev.azure.com/igraph-team/igraph/_build/results?buildId=3979&view=logs&j=f7e7b73f-4f78-55ba-0c68-9c010a229baf&t=cabb860d-e7f0-5fc7-82fb-1aff522f3167&l=63

Related: #2139 and #2112

**Comment by szhorvat** [comment]
The recommendation in the CMake bug tracker issue is to also set `-DCMAKE_SYSTEM_NAME=Darwin` explicitly. If we accept this as a solution, we must document it clearly. I will add this to the CI setup now.

**Comment by ntamas** [comment]
1. This is the solution indeed, I'm not eager to add workarounds in our CMakeLists.txt files for niche scenarios that are buggy due to an underlying CMake bug.
2. The issue with the endianness test when cross-compiling on an Intel Mac for ARM is already documented in f087f16c9c
