### ISSUE TITLE
Diameter calculation must be tested in edgeless graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2152]
We must add a test for the diameter calculation for graphs with zero edges but at least one vertex.

I introduced a bug for the `to`/`from` parameter for this case in `igraph_diameter()` and just fixed it in both `igraph_diameter()` and `igraph_diameter_dijkstra()`.

I did not have time to do a thorough check for these cases though, especially for result variables other than `to`/`from`. This is a todo item for that.

**Comment by ntamas** [comment]
Tests added in d8d55a271

**Comment by szhorvat** [comment]
Thanks so much! I was meaning to do this at some point.
