### ISSUE TITLE
igraph_bool_t / vs_start undefined behaviour

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2153]
In `graph/iterators.c`, I see four warnings like this:

```
/Users/szhorvat/Repos/igraph-main/igraph/src/graph/iterators.c:1335: warning: Passing an object that undergoes default argument promotion to 'va_start' has undefined behavior
```

This is from the change to `igraph_bool_t` and appears at:

```
va_start(ap, directed);
```

We need to investigate whether this can be an issue in practice.

TODO list:

 - [x] eliminate warning
 - [x] this warning should no longer be disabled (remove `-Wno-vararg`)

**Comment by szhorvat** [comment]
These warnings are suppressed using `-Wno-vararg`. I am not sure why, as right now these four are the only occurrences.

It seems to me that this is a real problem. The issue is that the naive implementation of `va_start` is a macro that just grabs the address of its argument and shifts it by its `sizeof`. However, due to default argument promotion, the size of a `igraph_bool_t = bool` will typically not be the same as the size used when passing it as a function argument. We may have a `bool` of size 1 which is passed as an `int` of size 4.

With some compilers, this might work, as `va_start` is not a naive macro but a special builtin. That does not mean that it works with all compilers.  I have not tested any so far.

The affected functions are `igraph_es_pairs_small()` and `igraph_es_path_small()`. These functions are just for convenience: they require a bit less typing than `igraph_es_pairs()` and `igraph_es_path()`. I suggest we do the following:

 - Check if they work correctly with GCC, Clang, MSVC, Intel. These are the only realistic compilers to use with igraph, as they are the only usable ones that support both C and C++. PGI is too buggy and discontinued and things like TinyC don't support C++.
 - If yes, just deprecate them and remove them in the next release. 
 - If not, remove them before 0.10.

**Comment by szhorvat** [comment]
This is a test program:

```c
#include <stdio.h>
#include <stdarg.h>
#include <stdbool.h>

void test(bool x, ...) {
    va_list args;
    va_start(args, x);
    double c = va_arg(args, double);
    printf("%g\n", c);
    va_end(args);
}

int main() {
    bool b = true;
    test(b, 1.2345e67);
    return 0;
}
```

It appears to work as expected with all Godbolt compilers I tested.

https://godbolt.org/z/PxWhG16r8

**Comment by ntamas** [comment]
According to the C standard, subclause 7.16.1.4, the behaviour is indeed undefined for `va_start()` if the type of the argument may undergo default argument promotion:

> If the parameter parmN is declared with the register storage class, with a function or array type, or with a type that is not compatible with the type that results after application of the default argument promotions, the behavior is undefined.

I've seen other projects bitten by stuff like this when the new Apple M1 CPUs came around (they handled out-of-range float-to-int casts differently than Intel CPUs and caused all sorts of unexpected crashes in projects that relied on the non-standardized Intel behaviour), so I'm somewhat leaning towards changing the argument type of `igraph_es_pairs_small` and `igraph_es_path_small` to an `int`.

**Comment by szhorvat** [comment]
Any reason not to deprecate these at the same time?

I would rather not use `int` for boolean arguments in random places. These functions are not critical. We already have functions for the convenient construction of small vectors, which can then be passed to `igraph_es_pairs`

**Comment by szhorvat** [comment]
Or if we really go with an `int`, we can at least `typedef` it to a more meaningful name ... we already have an `igraph_i_directed_t`, which is an enum. I'm not sure if default argument promotion applies to enum types. It probably does as I believe they are not guaranteed to be equivalent to an `int` (even though in practice they usually are).

**Comment by ntamas** [comment]
I was also thinking about potentially exposing `igraph_directed_t` as a public enum, but indeed enums are not suitable either.

On the other hand, I'd rather not remove these functions either because they clearly provide value; without these, you would need to declare a vector, fill it with `igraph_vector_int_small()`, and then destroy it later. There are at least three examples that use `igraph_es_pairs_small()` to make the example smaller and more readable.

How about doing this? Instead of:

```
igraph_error_t igraph_es_pairs_small(igraph_es_t *es, igraph_bool_t directed, ...)
```

we would declare it as:

```
igraph_error_t igraph_es_pairs_small(igraph_es_t *es, igraph_bool_t directed, igraph_integer_t first, ...)
```

and then we could call `va_start()` on `first`, which does not undergo default argument promotion.

**Comment by ntamas** [comment]
Let's see how this commit fares in CI.

**Comment by szhorvat** [comment]
Starting with an explicit `int` is the best idea so far.

**Comment by ntamas** [comment]
Which compiler did you get the warnings with? The CI seems to be fine with the changes.

**Comment by szhorvat** [comment]
Clang issues a warning if you remove the `-Wno-vararg` from the compiler flags. I noticed it while using my IDE, which uses Clang for code analysis. We should remove this flag.

**Comment by szhorvat** [comment]
Oops, looks like we have the same problem with `igraph_small()` which we would definitely not have deprecated.

**Comment by szhorvat** [comment]
https://stackoverflow.com/questions/73278375/do-enum-types-undergo-default-argument-promotion

**Comment by ntamas** [comment]
> Oops, looks like we have the same problem with `igraph_small()`

Strange, I tried to ripgrep for all occurrences of `igraph_bool_t.*\.\.\.` but this has slipped through the cracks somehow. Thanks!
