### ISSUE TITLE
Examples should not output to stderr when they succeed

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2160]
See #2157 for details.

**Comment by szhorvat** [comment]
@jgmbenoit This should be fixed for now, but no promises for the long term.

**Comment by jgmbenoit** [comment]
Thanks. I guess that in `examples/simple/setlocale.c` you forget to remove the `!` before the `strcmp`.

**Comment by szhorvat** [comment]
@jgmbenoit Thanks for pointing that out, it's fixed now. You can build a new release tarball using `make dist` if you need that for testing.
