### ISSUE TITLE
igraph_erdos_renyi_game_gnm() should support multi-edges

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2161]
**What is the feature or improvement you would like to see?**

`igraph_erdos_renyi_game_gnm()` should have a `multi` boolean argument which controls whether multi-edges can be generated.

**Use cases for the feature**

Generating such graphs with multi-edges is trivial to do in high-level languages. However, if the graph is very large (billions of edges), the generation takes significantly more resources than it would in C.

At the moment, we do not have a good way to generate huge graphs for testing purposes. `igraph_erdos_renyi_game_gnp()` only works up to about a hundred million vertices, as above that overflow issues make the generation inaccurate. In 0.10 this function errors for too many vertices. `igraph_erdos_renyi_game_gnm()` does not currently refuse to create large graphs, but it is dubious whether it works correctly at all for similar overflow reasons. In practice it is extremely slow.

For all these reasons, it would be useful to have a built-in function that can create random graphs with multi-edges.

**Notes**

The same feature does not make sense for `gnp()`. We have a common interface for `gnm()` and `gnp()` through `igraph_erdos_renyi_game()`. The Python interfaces exposes this. The R interface still exposes this for backwards compatibility, but it also has the separate and more modern `sample_gnm()` and `sample_gnp()`. I suggest that the Python interface should also separate these two cases. The Mathematica interface already does.

**Comment by VRajesh7649** [comment]
Hello, I am new to igraph, and I would love to try working on this? Is this still open?

**Comment by ntamas** [comment]
Yes, it's still open; if you start working on it, [the quickstart guide](https://github.com/igraph/igraph/wiki/Quickstart-for-new-contributors) is all that you need to get started.

It is advised to send us a draft PR early so we can give you feedback.
