### ISSUE TITLE
weighted, undirected local_scan_1_ecount is handled in 2 different functions, depending on where you start

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2163]
for the weighted, undirected case, when `igraph_local_scan_k_ecount` is called it with k=1 it will handle it itself, but when `igraph_local_scan_1_ecount` is called, it's passed on to `igraph_i_local_scan_1_sumweights`. They are now both tested, since 8d84c9f3a9f7526adc46520215b67a219a008f1e, and give the same results for a basic testcase. 

Either `igraph_i_local_scan_1_sumweights` is unnecessary and can be removed, or it is somehow better (faster?) than calling `igraph_local_scan_k_ecount`, and `igraph_local_scan_k_ecount` should redirect the weighted, undirected, k=1 case to `igraph_i_local_scan_1_sumweights`.

**Comment by GroteGnoom** [comment]
`igraph_i_local_scan_1_sumweights` is faster for dense graphs: 4 times as fast on a full graph. But is has a bug, it doesn't take loops into correctly. It counts them twice for the starting vertices, and 0 times for the neighbors.

**Comment by ntamas** [comment]
Thanks for figuring this out! Now the question is whether the function could be fixed while still keeping it faster than its counterpart.
