### ISSUE TITLE
Some tests cannot be run when cross-compiling

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2166]
When cross-compiling a project with CMake, one can set [`CMAKE_CROSSCOMPILING_EMULATOR`](https://cmake.org/cmake/help/latest/prop_tgt/CROSSCOMPILING_EMULATOR.html#prop_tgt:CROSSCOMPILING_EMULATOR) to be able to run cross-compiled executables. It will be used automatically for `add_test()` and `add_custom_command()`, both of which are used in igraph. However, tests that have an expected output are run indirectly using the `run_legacy_test.cmake` script, and do not automatically make use of `CROSSCOMPILING_EMULATOR`. It would be nice to make this work out of the box.

This is discussed here: https://github.com/igraph/python-igraph/issues/560#issuecomment-1214770834

**Comment by szhorvat** [comment]
Note to self: On macOS, one can set a dummy cross-compiling emulator as

```
cmake .. -DCMAKE_CROSSCOMPILING_EMULATOR="/bin/sh;-c" -DCMAKE_SYSTEM_NAME=Darwin
```

**Comment by ntamas** [comment]
Actually, it seems like this also resolves the problem with the generation of the `arithchk.h` header for `f2c`. When a cross-compiling emulator is set correctly, the header can be generated nicely. I'm trying cross-compilation to `aarch64` on an Intel Linux machine and it seems to work flawlessly.

**Comment by ntamas** [comment]
We are not quite there yet, something seems to go wrong with the evaluation of `CMAKE_CROSSCOMPILING_EMULATOR` when you need multiple arguments to the emulator. This is my setup:

```
 CMAKE_TOOLCHAIN_FILE=aarch64.cmake cmake -DTOOLCHAIN_PREFIX=/opt/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu -DTOOLCHAIN_TARGET_PLATFORM=aarch64-linux-gnu- -DCMAKE_CROSSCOMPILING_EMULATOR="qemu-aarch64;-L;/opt/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc" ..
```

The key point here is that I need to pass a custom ELF interpreter prefix to `qemu-aarch64` because that's the folder that contains `ld-linux-aarch64.so`. This does not get passed through correctly during the test invocation, though.

**Comment by ntamas** [comment]
Scratch that, it seems to work. I get four test failures, though, I'm investigating those.

**Comment by ntamas** [comment]
Okay, so it looks like on 64-bit ARM we somehow accept `invalid7.gml` as a valid GML file (with lots of warnings of course). Shall we worry about this?

**Comment by szhorvat** [comment]
> Shall we worry about this?

Probably yes. But I can't find `invalid7.gml`. They go only until 6. Where is it?

**Comment by ntamas** [comment]
It's in `tests/regression`

**Comment by szhorvat** [comment]
I really can't see it. Can you give me me a GitHub link please?

https://github.com/igraph/igraph/tree/develop/tests/regression

They go up to `6`, there is no `7`. Did you mean `6`?

**Comment by ntamas** [comment]
Damn! Sorry! I must be tired... this is all uncommitted stuff from the machine where I was testing things, and this test is not part of the main repo. So, all is good, and all tests pass when cross-compiling.

I guess the only thing we need to decide is whether we want to hide the warning about `arithchk.c` when cross-compiling _and_ a cross-compiler emulator is set.

**Comment by szhorvat** [comment]
I'm still learning parts of CMake, and I was a bit confused about how to do this. That's why I didn't implement this. If you can do it, go ahead.

The important bit seems to be the `CROSSCOMPILING_EMULATOR` _property_ (not variable) set on the given target. Technically, this is not necessarily the same as the `CMAKE_CROSSCOMPILING_EMULATOR` _variable_, whose value is used as the default for the property when the target is created.

**Comment by ntamas** [comment]
Cross-compilation warnings hidden in efa91da1a when an emulator is provided. I think this pretty much settles the issue now. I'm also updating the installation instructions to mention the emulator.
