### ISSUE TITLE
Does not compile on ARM64 Windows with MSVC

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2187]
**Describe the bug**

igraph 0.10 does not compile on ARM64 Windows with MSVC because this platform does not currently support [`_umul128`](https://docs.microsoft.com/en-us/cpp/intrinsics/umul128?view=msvc-170).

**To reproduce**

Try to cross-compile for ARM64 Windows, as the vcpkg CI does. Error:

```
D:\buildtrees\igraph\src\igraph-0-7986858a80.clean\src\random\random.c(484): fatal error C1189: #error:  "igraph requires __uint128_t or _umul128() in 64-bit mode"
```

**Version information**
0.10.0

**Comment by ntamas** [comment]
We try to check whether `_umul128()` is supported, see `etc/cmake/uint128_support.cmake`. We need to figure out why this check succeeds for ARM64 / MSVC if the compiler does not support this intrinsic.

**Comment by szhorvat** [comment]
It does not succeed:

```
-- Performing Test HAVE__UMUL128
-- Performing Test HAVE__UMUL128 - Failed
...
-- Check size of __uint128_t
-- Check size of __uint128_t - failed
```

The system is set up so that the error is issued during compilation, not configuration. I think this is fine, as the error message is very clear: "igraph requires __uint128_t or _umul128() in 64-bit mode".

I do not think we can fix this. It is up to Microsoft to implement `_umul128()` or an equivalent for that platform. I opened this issue only to document the situation, and to revisit it after a new version of MSVC comes out.

**Comment by szhorvat** [comment]
For reference, all arm64 are listed here and as of today there does not seem to be a suitable one:

https://docs.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics

**Comment by szhorvat** [comment]
This SO thread discusses implementing the needed operation from scratch:

https://stackoverflow.com/questions/28868367/getting-the-high-part-of-64-bit-integer-multiplication

**Comment by szhorvat** [comment]
Here's a starting point for fixing this. This is a program mostly copy-pasted form the above link, verified by comparing to `___uint128_t`:

```c

#include <stdint.h>
#include <stdio.h>

uint64_t igraph_i_umul128(uint64_t a, uint64_t b, uint64_t *hi) {

    uint64_t a_lo = (uint32_t) a;
    uint64_t a_hi = a >> 32;
    uint64_t b_lo = (uint32_t) b;
    uint64_t b_hi = b >> 32;

    uint64_t a_x_b_hi  = a_hi * b_hi;
    uint64_t a_x_b_mid = a_hi * b_lo;
    uint64_t b_x_a_mid = b_hi * a_lo;
    uint64_t a_x_b_lo  = a_lo * b_lo;

    uint64_t carry_bit = ((uint64_t) (uint32_t) a_x_b_mid +
                          (uint64_t) (uint32_t) b_x_a_mid +
                          (a_x_b_lo >> 32) ) >> 32;

    *hi = a_x_b_hi +
                     (a_x_b_mid >> 32) + (b_x_a_mid >> 32) +
                     carry_bit;

    return a*b;
}

int main() {
    uint64_t a = 18446744073709551604UL, b = 18446744073709551538UL;
    uint64_t lo, hi;
    lo = igraph_i_umul128(a, b, &hi);

    printf("%x%x\n", hi, lo);

    __uint128_t res = (__uint128_t) a * (__uint128_t) b;

    printf("%x%x\n", (uint64_t) (res >> 64), (uint64_t) res);

    return 0;
}
```

Can you take it from here @ntamas, if you think it's worth having a fallback?

**Comment by ntamas** [comment]
I'm not comfortable with adding extra code to work around a deficiency of the MSVC compiler on a niche platform (at least I am not aware of any significant uptake of Windows on ARM64). Plus, it seems like ARM64 Windows supports `__umulh` (see [here](https://stackoverflow.com/a/50958815/156771) ), so if we want to add support for MSVC on ARM64, I think we should investigate that direction instead.

**Comment by szhorvat** [comment]
- I agree that this is low priority, and I'm fine with letting it be for now.
 - The idea was not to fix this for arm64_windows specifically. As you said, that is a niche platform, and unlikely to be used to scientific computing. So I would not put effort into support _that single platform specifically_. The idea here was to provide a fallback for _any_ platform that does not have `__uint64_t` or `_umul128()`, just to ensure that igraph compiles on all 64-bit systems, even exotic ones we never thought of.

BTW `__umulh()` is available only for x64 according to the doc page you linked.

**Comment by ntamas** [comment]
> [MSVC also has a __umulh intrinsic](https://docs.microsoft.com/en-gb/cpp/intrinsics/umulh) for 64-bit high-half multiplication, but again it's only available on 64-bit platforms (and specifically x86-64 and AArch64.

So I guess it's available for AMD64 but it's not documented yet (or the documentation is not up-to-date).

**Comment by ntamas** [comment]
Do you have regular access to ARM64 Windows machines where we could test this?

**Comment by szhorvat** [comment]
I strongly suspect that this SO answer is wrong and `__umulh()` is not available for `arm64`.

I don't have an `arm64` Windows machine to test on, I don't even have any Windows machine at this moment. However, one can cross-compile to arm64 from an Intel Windows machine. This is what the vcpkg CI does.

I do not think we should implement a _custom_ solution for arm64 Windows, because, as you said, it's a niche platform where no one may want to use igraph anyway.

I suggest that if we do anything about this, we implement a _portable_ cross-platform fallback solution based on the function I posted above.

**Comment by szhorvat** [comment]
@ntamas I pushed a fix, see if you like it, if not just revert before 0.10.1 and we get back to this later.

**Comment by szhorvat** [comment]
Something is wrong here because our test program does compile with arm64 MSVC on Godbolt: https://godbolt.org/z/7WPca47hn

I don't understand why it fails on the vcpkg CI.
