### ISSUE TITLE
New algorithm for betweeness centrality

### ISSUE THREAD

**Issue by mbojan** [igraph/igraph#2188]
**What is the feature or improvement you would like to see?**

Perhaps somebody someday sometime: a faster parallel algorithm for betweeness centrality designed for large networks. An implementation seems to be here https://github.com/lxrzlyr/Betweenness-centrality

**Use cases for the feature**

Betweenness centrality. Doh.

**References**

https://arxiv.org/abs/2205.00162

**Comment by szhorvat** [comment]
Interesting. Have you studied the paper in detail or have you tried the code? After a _very_ quick skim, I noticed a few things that give me pause.

 - They compare CUDA code written in C and running on a GPU with Python code (NetworkX) running on the CPU. This is not a reasonable. See Table 2.
 - In section 3 they say: "DAWN adopts a GPU for computational acceleration and uses Openmp and CUDA/C++ to compile. This requires $\Theta(n^2)$ space and $\Theta(n^{2.387})$ time (approximate values in the limit state), where $n$ is the number of nodes in the network". A space complexity that is quadratic in the number of vertices is a deal-breaker, and practically limits the graph size to a few tends of thousands of nodes at most. Brandes's algorithm has time complexity of $O(EV)$. Typical real-world networks, such as social networks, are sparse, meaning that the edge count scales linearly with the vertex count. For such networks Brandes's algorithm will scale better. It seems to me that this algorithm would be useful only for very dense graphs of moderate sizes, which is precisely what the benchmarks have. Notice in Table 2 that even NetworkX (Python) outperforms DAWN for a $G(n,p)$ graph with $n=10000$ and $p=0.05$ (!!).

It seems to me that while this algorithm may be an interesting advance, it's applicability is very niche. It would not be useful for almost any real-world network dataset.

Am I missing something?

**Comment by mbojan** [comment]
> Am I missing something?

I doubt it. Perhaps indeed not worth the effort. It looked more attractive to me at a first glance.

**Comment by szhorvat** [comment]
It's always interesting to look at new algorithms, and it's a pity that it doesn't look very good. Thanks for bringing attention to this though. Since you agree that it might not be as good as it looked, I'll close this now.
