### ISSUE TITLE
test_igraph_power_law_fit fails on arm64 in Fedora

### ISSUE THREAD

**Issue by limburgher** [igraph/igraph#2189]
**Describe the bug**
Test fails that passes on multiple other architectures.

**To reproduce**
Run test suite

**Version information**
0.10.1: I'm the Fedora maintainer so this is a source build.

```
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /builddir/build/BUILD/igraph-0.10.1/tests/unit/igraph_power_law_fit.out	2022-09-08 14:10:23.000000000 +0000
+++ /builddir/build/BUILD/igraph-0.10.1/redhat-linux-build/tests/test_igraph_power_law_fit.out	2022-09-08 20:46:11.746576454 +0000
@@ -34,4 +34,4 @@
 L = -75.22503
 D = 0.70253
 ====================
-p = 0.00
+p = 0.08
-- -------------------------------------------------------
CMake Error at /builddir/build/BUILD/igraph-0.10.1/etc/cmake/run_legacy_test.cmake:67 (message):
  Exiting test.
```

**Comment by szhorvat** [comment]
I only have internet access on my phone so I can't take a closer look but I'm wondering if this could have something to do with the use of long doubles in the plfit code. @jgmbenoit @ntamas https://github.com/ntamas/plfit/issues/38

**Comment by szhorvat** [comment]
@limburgher can you let us know your GCC version and all compiler flags that you use on fedora? This failure is unusual. We treat with ppc64, s390 and arm64 on Travis. We also test manually on macOS arm64, an old PPC system as well as a variety of compilers. This test passed with all of these. We need to find what is different in your system.

@jgmbenoit did you see failures on arm64 Debian?

**Comment by szhorvat** [comment]
I assumed that 0.10.1 was the first release included in Fedora, but actually 0.10.0 was also included. Here are the build logs:

https://kojipkgs.fedoraproject.org//packages/igraph/0.10.0/1.fc38/data/logs/aarch64/build.log

This test passes 0.10.0. igraph is built with vendored plfit.

There have been no changes between 0.10.0 and 0.10.1 that could affect this functionality. Here is the list of modified files: https://github.com/igraph/igraph/compare/0.10.0...0.10.1

@limburgher Can you please verify that the failure is consistently reproducible?

**Comment by szhorvat** [comment]
I found the logs here: https://kojipkgs.fedoraproject.org//work/tasks/4071/91804071/build.log I didn't notice anything that looks relevant, except maybe that LTO is enabled.

**Comment by jgmbenoit** [comment]
> @jgmbenoit did you see failures on arm64 Debian?

I plan to package the last version this week-end. I will let  you know if any trouble occurs.
Meanwhile, so far I can remember, the arch `arm64` has not been a trouble maker for `igraph`.
Otherwise, the current `plfit` passes tests on this architecture. (I must find time to fix the `plfit' issue, sigh.)
Note that `igraph` is built against an external `plfit` on Debian.

**Comment by szhorvat** [comment]
Ah, it finally clicked. This might be OpenMP related. @ntamas How does plfit use OpenMP, can it introduce any non-determinism?

@limburgher I would suggest running the tests after setting the environment variable `OMP_NUM_THREADS=1`.

**Comment by szhorvat** [comment]
OK, I'll look into setting the test to use a single thread.

**Comment by szhorvat** [comment]
@limburgher There should be no more problems with the test in 0.10.2 and later. Until then the workaround is to set `OMP_NUM_THREADS=1` before running the test suite.

You should also remove this line as it is no longer needed: https://src.fedoraproject.org/rpms/igraph/blob/rawhide/f/igraph.spec#_51

**Comment by limburgher** [comment]
Thank you, applying the above commit did the trick.
