### ISSUE TITLE
Vector view passed to function that may modify vector

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2190]
In `igraph_i_st_vertex_connectivity_check_errors()`, a vector view is passed to a function that calls `resize()` on it:

https://github.com/igraph/igraph/blob/67d9908ec6c28ec10bf6c1ce5a6c49550d1ee09f/src/flow/flow.c#L1764-L1770

I understand that the vector is already of the correct size, so `resize()`  will return without doing anything, but this is a bad hack that may blow up some day. Vector views should only be passed to functions that take const vectors.

I did not immediately fix it as it was unclear how great the performance impact of the refactoring would be.

**Comment by ntamas** [comment]
I think the performance impact would be negligible; `igraph_i_st_vertex_connectivity_check_errors` is called only once at the beginning of `igraph_i_st_vertex_connectivity_undirected()` or íigraph_i_st_vertex_connectivity_directed()`. So, any performance impact would probably be non-negligible only if `igraph_st_vertex_connectivity()` is called multiple times in a tight loop. In that case, the cost of subsequent allocations and operations are very likely to dominate the overall runtime cost.

However, note that `igraph_st_vertex_connectivity()` _is_ called in a tight loop from `igraph_i_vertex_connectivity_directed()`, and we are essentially repeating the safety checks in `igraph_st_vertex_connectivity()` O(N^2) times. If we are looking for a place to optimize things, the easiest would be to introduce an `igraph_i_st_vertex_connectivity_unchecked()` function that would ensure that we are not repeating the checks so many times.

**Comment by szhorvat** [comment]
Since you've already looked into the problem, can you take this issue?

BTW this came from Coverity.

**Comment by ntamas** [comment]
Note to self: the error checks in `igraph_st_vertex_connectivity()` are not in vain when they are called O(N^2) times from `igraph_st_vertex_connectivity()` as we are always testing for different vertex pairs, so the checks cannot be lifted out from the `for` loop there.

**Comment by szhorvat** [comment]
See 0f76279635e0ce0115882d3e03ede839b2c330b0
