### ISSUE TITLE
Status and progress handlers convert errors to interruptions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2199]
`igraph_status()` and `igraph_progress()` convert non-success error codes to `IGRAPH_INTERRUPTION`. This choice is documented and clearly intentional, but its purpose is unclear to me.

If there is no reason that is still valid to do this, it should be changed for 0.11. The functions should pass through error codes unaltered.

**Comment by ntamas** [comment]
Good question. I think this is one of those historical artifacts again; back in the early days we didn't have a separate interruption handler and the status / progress handler was (ab)used for that. Basically the idea was that there would be a UI widget to stop the current calculation (like a button), and the status / progress handler would check for events coming from that widget regularly. I think it's not needed any more now that we have interruption handlers, so this can probably be fixed.

OTOH having separate interruption, status and progress handlers seem redundant, so these should probably be consolidated, probably at the same time when #1884 is implemented.

**Comment by szhorvat** [comment]
Sounds good for combining progress and status, but I would keep progress/status vs interruption separate.

**Comment by szhorvat** [comment]
Let's have a call about this sometime.

A proper refactoring of progress reporting is beyond the scope of 1.0. We have issues with nested progress reporting that is non-trivial to resolve./

**Comment by ntamas** [comment]
In that case I'm closing this issue as the original problem mentioned in the title is now resolved. Let's move the discussion to https://github.com/igraph/igraph/issues/1884
