### ISSUE TITLE
eulerian_cycle() should not error when no Eulerian cycle exists

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2201]
`igraph_eulerian_cycle()` / `igraph_eulerian_path()` throw an `IGRAPH_EINVAL` error when no such cycle or path exists.

It would be more productive if these functions could signal the non-existence of the cycle/path in a structured manner.

I propose that they should return an empty vector, and not throw an error.

The error cannot be reliably handled programmatically anyway because it's a generic `IGRAPH_EINVAL` that could occur for other reasons. Using errors to detect such conditions is not convenient in most languages from which igraph is used (Python may be the only exception, an this function isn't even exposed from Python).

**Comment by szhorvat** [comment]
@ntamas Are we fine with making this change for 0.10.2 or should it be postponed to 0.11?

**Comment by szhorvat** [comment]
Hm, actually this may not be a good idea as these functions return an empty vector for graphs with no edges.

**Comment by szhorvat** [comment]
I don't have a better idea about what can be done to improve this. We could perhaps introduce a new error code for this situation, similar to the very specific `IGRAPH_ENEGLOOP` (negative cycle in weight shortest path problem). But I am reluctant to add too many error codes. Closing this for now.

**Comment by ntamas** [comment]
I still think this issue deserves its own error code; something like `IGRAPH_ENOSOLUTION`, which could be used as a generic "no solution to this problem" error code for other algorithms so it won't be completely useless. If you want to keep the number of used error codes monotonously decreasing, we can deprecate `IGRAPH_EDRL` (which could be replaced with `IGRAPH_EINTERNAL` -- I haven't seen this error code in practice so far).

**Comment by iosonofabio** [comment]
Special error code is the way AFAICT. I'm ok having it somewhat generic as long as it's clear from the docs that the user didn't do anything wrong - which is the first thing they'll think when the error code is not zero.

**Comment by ntamas** [comment]
Fixed in 0ef45b54a

**Comment by szhorvat** [comment]
I just made that `EDRL` deprecation a bit harder. GCC/Clang will issue a warning for it now. e9d1843d160e9febcde45787f608dc2659145ae1
