### ISSUE TITLE
Generated pkg-config file incorrectly contains -lz

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2202]
This is the `igraph.pc` pkg-config file I get on my system:

```
prefix=/usr/local
exec_prefix=/usr/local
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libigraph
Description: A library for creating and manipulating graphs
Version: 0.10.1
URL: https://igraph.org
Libs: -L${libdir} -ligraph
Libs.private:  -lc++ -lxml2 -lz -lgmp -lblas -lglpk -llapack -larpack
Cflags: -I${includedir}/igraph
```

Notice that instead of just `-lxml2`, it contains `-lxml2 -lz`.  The `-lz` part is not necessary when linking to libxml2 dynamically, and not usually sufficient when linking to it statically (as libxml2 may, and usually does have several other dependencies, depending on configuration). Having `-lz` in there is incorrect.

The clean way to do this is to specify that actual dependencies instead of specifying linking flags. So we need this:

```
Libs.private:  -lc++ -lgmp -lblas -lglpk -llapack -larpack
Requires.private: libxml-2.0
```

Now I get this output:

```
$ pkg-config --libs igraph
-L/usr/local/lib -ligraph

$ pkg-config --libs --static igraph
-L/usr/local/lib -L/opt/local/lib -ligraph -lc++ -lgmp -lblas -lglpk -llapack -larpack -lxml2 -lz -llzma -lpthread -liconv -licui18n -licuuc -licudata
```

Notice that there are many other dependencies for libxml2 than just libz.

It might be temping to put other libraries into `Requires.private` as well. GMP and ARPACK-NG do support pkg-config. However, on some systems it will be MPIR that provides a GMP implementation, and from a quick search it seems that it may not support pkg-config yet. There are old versions of ARPACK which also don't. So I suggest we don't move these.

----

Finally, there is the issue of the Python interface, which parses the pkg-config file directly. Do you link to libxml2 statically when preparing PyPI binaries, @ntamas ? If yes, how do you handle al the transitive dependencies?  Generally, they can be determined by running `xml2-config --libs`.

Since libxml2's own dependencies are system-dependent, we should not include them in `igraph.pc`. Let us either go with simply `-lxml2` (and no `-lz`) if the Python interface requires this, or go with adding `libxml-2.0` in `Requires.private`. The Python interface can still detect this, and then use `xml2-config --libs` to get the necessary info, assuming it wants fully static linking.

I'm assigning this to you @ntamas as ultimately the decision depend on py-igraph, so it will be up to you.

**Comment by ntamas** [comment]
The Python interface tries to vendor everything that can be vendored, but links to non-vendored libraries dynamically (except on Windows I guess, where we link to everything statically) -- _but_ we have an option (an envvar named `IGRAPH_STATIC_EXTENSION`) that allows the user to specify that he wants a fully static library. It might not work for all cases / configurations (especially when `libxml2` needs additional stuff besides `z`), but let's start worrying about that when people start complaining about it. (I guess most people don't even use the `IGRAPH_STATIC_EXTENSION` option).

Having `Requires.private` in `igraph.pc` would prevent us from doing static compilation in the Python interface as I don't feel like implementing a full `.pc` parser in Python just so we can process the `Requires.private` section. (And we parse `igraph.pc` on our own because we don't want to force users to install `pkg-config` either). The alternatives would be to hardcode libxml2's transitive dependencies as a special case in the Python interface, or to get rid of the option of compiling the extension while linking statically to all dependencies.

I'm considering doing the latter because this is a niche option that was probably relevant in the past (when we did not have pre-compiled wheels) but not any more.

**Comment by szhorvat** [comment]
OK, so remove `-lz` and leave `-lxml2` then?

**Comment by ntamas** [comment]
Let's put the Python interface aside for a while. For the C core alone, the proper solution would probably be to use:

```
Libs: -ligraph
Libs.private: all the stuff we have now, sans -lxml2 and -lz
Requires.private: libxml-2.0
```

Am I correct here?

In the Python interface, this will bring in the issue that we cannot offer users the option to set `IGRAPH_STATIC_EXTENSION` and get a binary that has no dynamic dependencies apart from what would be needed by Python anyway (i.e. it needs to link dynamically to Python itself). I'm willing to let that go if needed.

Now to the suggestion: leaving `-lxml2` in `Libs.private` would not help with this as we would still not parse the `Requires.private` section and that would still leave us unable to figure out what _else_ we need to link to when linking to `libxml2` statically during the build stage of the Python interface. So there's no point in doing this; we should just implement the `Requires.private` stuff in the C core, as suggested above, and then fix up the build script of the Python interface and remove the option for fully static builds.

**Comment by ntamas** [comment]
@szhorvat take a look, is this what you had in mind?

**Comment by szhorvat** [comment]
> Am I correct here?

Well, this is the "more correct" solution in the sense that it supports static linking to libxml2. But having `-lxml2` in `Libs.private` (without `-lz`) is also correct. It just assumes that we link to libxml2 dynamically, which is going to be the case for most users.

There are, however, other dependencies, such as BLAS, LAPACK, ARPACK, GMP, GLPK, plfit. These also have their own transitive dependencies, which are also system-dependent.

So we cannot have a perfect pkg-config based solution where full-static linking works _automatically_ in all environments. If people want the most robust automatic solution, they should be using CMake. If they want to do things manually, it is unavoidable that at some point they will need to determine and include transitive dependencies on their own. python-igraph has `IGRAPH_EXTRA_LIBRARIES` for that, and notice one has to put quite a few libraries in there to make fully static linking work on Windows: https://github.com/igraph/python-igraph/#enabling-graphml

**Comment by szhorvat** [comment]
> @szhorvat take a look, is this what you had in mind?

Yes.

But as said above, this solution is still not perfect, and we can't hope to ever have a perfect solution. Therefore, if just using a plan `-lxml2` in `Libs.private` is more convenient for you with python-igraph, there is no good reason not to just go with that.

**Comment by ntamas** [comment]
Closing this issue then; I have bumped `python-igraph` to the latest master revision and the CI tests are running there so we'll see soon enough if we broke anything with the CI builds. Anything that became broken by this that does not pop up in CI is probably rare enough that we shouldn't need to worry about it now.

**Comment by ntamas** [comment]
So I just ended up handling `Requires.private` "manually" on the Python side; this is good enough for the CI.

**Comment by jgmbenoit** [comment]
My understanding is that `xml2-config` is deprecated. BTW is there any python tool that parse pc datafiles ? 
Otherwise note that `Requires.private` is involved when `pkg-config` is called with option `--cflags` so that `libxml-2.0.pc` (and the dev- distribution package that installed it) is now needed when we build a (simple) C source against `igraph` . This becomes a complication for the end user.

**Comment by szhorvat** [comment]
We are following pkgconfig's recommendations here, but unfortunately, pkgconfig is an imperfect system. Any solution will come with tradeoffs.  What would be your recommendation here?

We could just add `-lxml2` to `Libs.private` but then it would become more difficult for people to create a statically linked standalone igraph library. Note that libxml2 is the only dependency that is not bundled with igraph, and libxml2 can have many dependencies of its own, depending on its specific configuration.

The same issue is being discussed here:

https://github.com/mesonbuild/meson/issues/3970

Some people claim the `pkgconfig --cflags` behaviour to be a pkgconfig bug (and pkgconf, a semi-compatible competing project, is claimed to have some solution).

The reasoning for this pkgconfig behaviour is explained here:

https://bugs.freedesktop.org/show_bug.cgi?id=105572 (continued at https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/7)

They also point out that one needs to decide which tradeoff to make—there will always be a tradeoff. One solution (i.e. one possible tradeoff) that can be made on the Debian side is to make the `libigraph-dev` depend on `libxml2-dev`.  In fact, [someone in the thread claims](https://bugs.freedesktop.org/show_bug.cgi?id=105572#c16) that most non-Debian-based distros already include dependencies between dev packages with the reasoning that if you link one library statically, you want to links all its dependencies statically as well.

----

Personally I don't have strong feelings about that to do here. This is a huge mess, and no matter what we do, something will break. I would always recommend using CMake for anyone who writes programs that use igraph.

**Comment by szhorvat** [comment]
> My understanding is that `xml2-config` is deprecated.

Do you have a reference for this?

**Comment by jgmbenoit** [comment]
> > My understanding is that `xml2-config` is deprecated.
> 
> Do you have a reference for this?

Debian dev. were asked to not use `xml2-config`  and to use `pkg-config` instead (e.g., [#949087](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23949087)).

**Comment by jgmbenoit** [comment]
> Some people claim the `pkgconfig --cflags` behaviour to be a pkgconfig bug

I would be agree with this claim.

**Comment by jgmbenoit** [comment]
I will respect  your trade-off choice. That is I will render `libigraph-dev` depend on `libxml2-dev`.

**Comment by szhorvat** [comment]
Before you do that, let's see what @ntamas says. As I said, I have no strong preference for a particular solution.

**Comment by jgmbenoit** [comment]
I have just done it for the current package. It can be easily reversed. In any case, this kind of choice belongs to the upstream  team.
