### ISSUE TITLE
Make UMAP layout interruptible

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2211]
**What is the feature or improvement you would like to see?**
UMAP layout should be interruptible

**Use cases for the feature**
To make it easier for higher-level interfaces to stop the process.

**Comment by iosonofabio** [comment]
great idea, in fact I've made my fork interruptible

**Comment by GroteGnoom** [comment]
Does that mean you'll fix this one? 🙂  Or should I just do it separately?

**Comment by iosonofabio** [comment]
a little overwhelmed ATM... do you have time to do it?

**Comment by GroteGnoom** [comment]
I'll look into it!
