### ISSUE TITLE
Why does igraph_heap_t have a destroy field?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2214]
`igraph_heap_t` has a boolean `destroy` field. What is the purpose of this?

`igraph_heap_destroy()` will only free storage if `destroy == true`. As far as I can tell, there are two ways to create a heap, `igraph_heap_init()` and `igraph_heap_init_array()`. Both of these set `destroy = true`, thus this field appears to do nothing. The storage will always be freed.

I propose removing it in 0.11. We cannot remove it in 0.10 as that would break ABI.

**Comment by szhorvat** [comment]
The same applies to `igraph_indheap_t` and `igraph_d_indheap_t`.

**Comment by ntamas** [comment]
I think that's a remainder from some legacy code that was copied and pasted here and there. You can get rid of it for 0.11.
