### ISSUE TITLE
Docs should explain how Infomap uses vertex weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2228]
`igraph_community_infomap` has a `v_weights` parameter for vertex weights. It is not obvious how vertex weights would be used during community detection. This should be explained in the docs.

**Comment by szhorvat** [comment]
#504 is related.

**Comment by vtraag** [comment]
I just briefly looked into this, and the vertex weights are used for the teleportation. Presumably, higher vertex weights would lead to being sampled more frequently during the teleportation step (akin to the "personalization" in pagerank, I'd think). I haven't looked at it in sufficient detail, but that's the main gist of it.

**Comment by ntamas** [comment]
Fixed in 9654db91c
