### ISSUE TITLE
Proper weight support for igraph_community_edge_betweenness()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2229]
`igraph_community_edge_betweenness()` implements the Girvan-Newman algorithms which builds a dendrogram by iteratively removing the highest betweenness edges and checking how the graph falls to pieces. Then the dendrogram is cut so as to maximize modularity.

When weights are passed to this function, it uses these weights as _edge lengths_ during the betweenness calculation. Therefore, high-weight edges are interpreted as representing weaker connections. During the modularity calculation, high-weight edges are interpreted as stronger connections, which is contradictory. We have discussed this before, and the stopgap measure was that the function issues a warning when it is given some weights, and a membership vector is requested. In fact, it issues two warnings, which looks a bit sloppy.

https://github.com/igraph/igraph/blob/develop/src/community/edge_betweenness.c#L506-L516

----

This is a proposal for dealing with this problem. There are actually weighted generalizations of the method in the literature.

Section 5.1 of https://doi.org/10.1016/j.physrep.2009.11.002 says:

> The method can be simply extended to the case of weighted graphs, by suitably generalizing the edge betweenness. The betweenness of a weighted edge equals the betweenness of the edge in the corresponding unweighted graph, divided by the weight of the edge [159].

Ref [159] is https://doi.org/10.1103/PhysRevE.70.056131 and says:

> The resulting algorithm is identical to that for the integer case: betweennesses are simply divided by the weight of the edge and the edge with the highest resulting score removed from the network.

----

In order to preserve the existing functionality of igraph while also interpreting weights reasonably, I propose to change `igraph_community_edge_betweenness()` to take _two_ weight-type arguments:

```c
igraph_error_t igraph_community_edge_betweenness(const igraph_t *graph,
                                      igraph_vector_int_t *result,
                                      igraph_vector_t *edge_betweenness,
                                      igraph_matrix_int_t *merges,
                                      igraph_vector_int_t *bridges,
                                      igraph_vector_t *modularity,
                                      igraph_vector_int_t *membership,
                                      igraph_bool_t directed,
                                      const igraph_vector_t *weights,
                                      const igraph_vector_t *lengths);
```

Edge _weights_ and edge _lengths_ should be specified separately, and either can be omitted. _Lengths_ are used in the betweenness calculation as usual. _Weights_ are used to divide the betweenness scores (as in the quotes above) and are also used in the modularity calculation. This solution preserves the current functionality (which is interesting for experimentation) while introducing the proper weighted generalization from the above quotes.

Does this sound reasonable to everyone? @vtraag ?

----

See also #1040

**Comment by ntamas** [comment]
I'm not sure whether this weighted generalization makes sense in all contexts. I can't really formulate my concerns now (it's late), but the division seems quite arbitrary to me. I haven't read the cited papers in full, but I got the impression that the idea of dividing the betweenness scores by the weights makes sense only if the weights represent integers, for instance, occurrences of some kind of an event. In this case you can treat an edge with weight $w$ as $w$ parallel edges with weight 1, and a shortest path can go through either of them so it is reasonable to divide the betweenness score by $w$. But what happens if the weights are in the range [0; 1], as it is common in biology where the weights often represent correlations (after dropping negative correlations of course)?

**Comment by szhorvat** [comment]
I don't think there's a problem here.

First, we don't need to justify this approach. It's what the original author of the method proposed. Users can be referred to his paper for the justification.

Second, it is true that he justifies this approach by interpreting weights as edge multiplicities. But that does not mean that weights must be integers, or larger than one. Note that the result is invariant to a linear scaling of the weights. What this interpretation really implies is that weights are "parallel additive", i.e. that parallel edges can be replaced with a single edge after summing their weights. _This is exactly the same interpretation that the concept of modularity uses._ 

(Side note: an interpretation of weights as "edge lengths" implies that they are "series additive", i.e. that path lengths as sum of the constituent edge lengths are physically meaningful.)

Third, with _any_ type of community detection, the user has to choose the weights appropriately. None of the methods can be invariant to a non-linear transformation of weights. Suppose you observe that the weights are distributed log-normally—do you want to then use $\ln w$ instead of $w$? That choice is outside the scope of the community detection method. One needs to go back the physical/biological/etc. interpretation of the weights, and consider whether their choice makes any sense in the context of a given community detection method. E.g., do larger weights represent stronger or weaker connections? A more well founded justification for a certain choice can be based on considering invariants that the method respects, such as the "parallel additivity" or "series additivity" I referred to above, and looking whether your physical/biological/etc. weights also respect that.

----

What my proposal achieves:

 - Implements Newman's weighted version of the method
 - Does not take away prior functionality (even if that functionality was a bit ad-hoc, and its usability wasn't investigated)
 - It does take away the one bit of clearly wrong behaviour, i.e. the contrary interpretation of weights in the betweenness and modularity calculation steps. But if one were dead-set on reproducing the old behaviour, it would still be possible by setting `weights = lengths`.

**Comment by szhorvat** [comment]
This is breaking and should go in 1.0. I'd like to have this, and will try to do it myself. It's not difficult.
