### ISSUE TITLE
test::igraph_complex fails on x86 musl

### ISSUE THREAD

**Issue by txgk** [igraph/igraph#2231]
**Describe the bug**
test::igraph_complex aborts during the package build, you can find log [here](https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/864158)

**To reproduce**
try running tests on x86 machine with musl libc (igraph was built according to [this](https://gitlab.alpinelinux.org/alpine/aports/-/blob/9502a488c0f78cc47e7891e006bab9d4f81c08a9/testing/igraph/APKBUILD) recipe)

**Version information**
latest commit: d0adecef0d25f7b88d6bf472f506a969281883ef

**Comment by szhorvat** [comment]
Let's copy the error message here:

```
Fatal error at /builds/grikir02/aports/testing/igraph/src/igraph-d0adecef0d25f7b88d6bf472f506a969281883ef/tests/unit/igraph_complex.c:122 : Assertion failed: igraph_complex_abs(a) == igraph_complex_mod(a)
```

and also point out that this is 32-bit, so it likely uses x87 math.

**Comment by txgk** [comment]
the most likely cause of the problem is the big use of a stack, since glibc distributions with x86 support don't seem to have the problem

**Comment by szhorvat** [comment]
No, this has almost certainly nothing to do with the stack. It is most likely a numerical precision issue due to combination of musl and x87. I'll look into it, but I will likely need your help as I don't have easy access to this platform.

**Comment by txgk** [comment]
i don't have easy access too, but let me ask those who have :)

**Comment by txgk** [comment]
before i start bothering people with access to build machines, can i somehow set cmake to a very verbose debug mode myself to make logs more useful? maybe i need to install some sanitizer and set debug flag?

**Comment by szhorvat** [comment]
@ntamas Do you know why we have both `igraph_complex_mod()` and `igraph_complex_abs()` with identical functionality? Can we deprecate and remove the `mod` version, as that notation is less common in programming?

It is very strange that this test fails. I copy the implementation of the two functions here:

```c
igraph_real_t igraph_complex_mod(igraph_complex_t z) {
    igraph_real_t x = IGRAPH_REAL(z);
    igraph_real_t y = IGRAPH_IMAG(z);
    return hypot(x, y);
}


igraph_real_t igraph_complex_abs(igraph_complex_t z) {
    /* hypot() avoids overflow at intermediate stages of the calculation */
    return hypot(IGRAPH_REAL(z), IGRAPH_IMAG(z));
}
```

This test simply checks that they return the same thing.

**Comment by szhorvat** [comment]
> before i start bothering people with access to build machines, can i somehow set cmake to a very verbose debug mode myself to make logs more useful? maybe i need to install some sanitizer and set debug flag?

This is an assertion failure so there's no need to more verbosity or sanitizers. You can see the test output in the logs you linked. I copied in into [this comment](https://github.com/igraph/igraph/issues/2231#issuecomment-1270620282).

**Comment by szhorvat** [comment]
@txgk I don't know what to say here. As you can say, the test that fails is checking that two basically identical functions return the same thing. Can you check that the failure is repeatable? Can you re-run the tests and see if it fails again?

**Comment by txgk** [comment]
error persists :(

https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/864048
https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/864065
https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/864165
https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/864168

**Comment by szhorvat** [comment]
I can reproduce it in a docker container. I'll look at it tomorrow. I have to say that I can't see how this can be an igraph issue.

**Comment by szhorvat** [comment]
Until then, some comments on the recipe you linked:

 - SuiteSparse is no longer a dependency of igraph since version 0.10. You can remove it from the recipe.
 - I see that you are picking a specific commit and manually marking the version as "0.10.1". Please do not create packages which claim a version that is different from what they are. Adding hand-picked bugfix patches on top of a released version is fine, but the commit you have here is significantly different from 0.10.1 and shouldn't be called that. I would recommend using the release tarballs instead of building from the git repo, i.e. use this source archive: https://github.com/igraph/igraph/releases/download/0.10.1/igraph-0.10.1.tar.gz In that case you can also drop the bison and flex dependencies.

**Comment by txgk** [comment]
oh my... tests run fine when program is compiled with clang...

**Comment by txgk** [comment]
i guess gcc's to blame

**Comment by txgk** [comment]
> Until then, some comments on the recipe you linked:
> 
> * SuiteSparse is no longer a dependency of igraph since version 0.10. You can remove it from the recipe.
> * I see that you are picking a specific commit and manually marking the version as "0.10.1". Please do not create packages which claim a version that is different from what they are. Adding hand-picked bugfix patches on top of a released version is fine, but the commit you have here is significantly different from 0.10.1 and shouldn't be called that to avoid user confusion. I would recommend using the release tarballs instead of building from the git repo, i.e. use this source archive: https://github.com/igraph/igraph/releases/download/0.10.1/igraph-0.10.1.tar.gz In that case you can also drop the bison and flex dependencies.

okay, thank you :)

**Comment by szhorvat** [comment]
Here's an almost minimal reproducer:

```
#include <math.h>
#include <stdio.h>

typedef struct igraph_complex_t {
    double dat[2];
} igraph_complex_t;

#define IGRAPH_REAL(x) ((x).dat[0])
#define IGRAPH_IMAG(x) ((x).dat[1])

double igraph_complex_abs(igraph_complex_t z) {
    /* hypot() avoids overflow at intermediate stages of the calculation */
    return hypot(IGRAPH_REAL(z), IGRAPH_IMAG(z));
}

double igraph_complex_mod(igraph_complex_t z) {
    double x = IGRAPH_REAL(z);
    double y = IGRAPH_IMAG(z);
    return hypot(x, y);
}

int main(void) {
    igraph_complex_t a;
    a.dat[0] = 4; a.dat[1] = 5;

    printf("%d\n", (igraph_complex_abs(a) == igraph_complex_mod(a)));

    double m1 = igraph_complex_abs(a);
    double m2 = igraph_complex_mod(a);
    printf("%d\n", (m1 == m2));

    return 0;
}
```

The output is:

```
0
1
```

It's the weirdest thing ever.

**Comment by ntamas** [comment]
> Do you know why we have both igraph_complex_mod() and igraph_complex_abs() with identical functionality?

No idea; probably historical cruft. Maybe someone needed an `abs()` function and did not realize from the name that `mod()` was doing the same thing? :) Feel free to get rid of one of them.

**Comment by szhorvat** [comment]
If I try this, I can observe the difference:

```c
printf("%g\n", igraph_complex_abs(a) - igraph_complex_mod(a));
```

```
-1.55258e-16
```

BTW this is a slightly older Alpine Linux with:

```
gcc --version
gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219
```

In the end, it's good to note that while the test fails and the compiler behaviour is extremely strange, this issue is harmless.

**Comment by szhorvat** [comment]
> No idea; probably historical cruft. Maybe someone needed an `abs()` function and did not realize from the name that `mod()` was doing the same thing? :) Feel free to get rid of one of them.

Deprecate or remove right away?

**Comment by ntamas** [comment]
Well, since none of the `igraph_complex_...` functions were documented officially, I'd say just remove it.

**Comment by szhorvat** [comment]
@txgk It seems to me that this test failure is completely harmless and can be safely ignored. I just pushed a commit which essentially removes the offending test case (as well as the unnecessary duplicate function).

**Comment by txgk** [comment]
thank you guys for very prompt help, now with https://github.com/igraph/igraph/commit/e233027da8e8392330c2abda7617b46d13f62c5e everthing builds fine!

**Comment by szhorvat** [comment]
I tried to better understand what happened here. I noticed that the `-ffloat-store` option eliminates the difference in behaviour between the two functions. My hypothesis is the following:

The problem happens on a platform where very likely x87 instructions are being used (instead of SSE). This means that the arithmetic is done in 80-bit `long double`s, giving higher precision than 64-bit `double`s would. There cannot possibly be any precision-related issues when passing arguments to `hypot()`, but there can be when handling its return value. If the code that compares the two results first copies only one of them from an 80-bit register to a 64-bit storage area, that will cause rounding in only one of the two results, introducing a tiny difference.

Notice that the difference between the two values, `1.55258e-16`, is smaller than a `double` epsilon, `2.22045e-16`, even though the result from `hypot()` is greater than 1. This is only possible if the difference was calculated with a precision higher than what `double` supports.

**Comment by szhorvat** [comment]
Here is a truly minimal example:

```c
#include <math.h>
#include <stdio.h>

double abs1(double x, double y) {
    return hypot(x, y);
}

int main(void) {

    printf("%g\n", abs1(4,5) - abs1(4,5));

    return 0;
}
```

The output is:

```
-1.55258e-16
```

😆

**Comment by szhorvat** [comment]
@txgk FYI igraph 0.10.2 is now released, so you can also update it in Apline to a stable (unpatched) release if you want to.

**Comment by txgk** [comment]
I will certainly do, cheers :)
