### ISSUE TITLE
Set up CI run with Clang 15

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2236]
Clang 15 has introduced many new warnings which broke compilation with the default of `IGRAPH_WARNINGS_AS_ERROR=ON`. I fixed these, but the risk of re-introducing problems is high, at least until we pick up some new habits such as using `int main(void)` instead of `int main()`. Therefore, there should be a CI run with Clang 15.

Ideally this should have ASan enabled and should replace the existing Clang run on Azure.

One possibility is https://apt.llvm.org/ but there should be some caching to avoid continual re-downloads.

Note:

 - CRAN now does checks with Clang 15
 - We already had a user point out Clang 15 warnings.

**Comment by szhorvat** [comment]
Here's the software available on runners:

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

Simplest might be to use Linuxbrew. Pay attention to the note that says that it's not in the path by default.

Can you have a look at this @ntamas, since I don't use Homebrew myself, and it's not entirely clear how to ensure that the newly installed Clang would be in the path (even without the path issue mentioned above)?

**Comment by ntamas** [comment]
I don't know what the connection is between Homebrew and Linuxbrew so I can't connect on that. One thing that's for sure is that Homebrew never installs alternative versions of OS-level tools such as `clang` into the system PATH; if you install it, it is stored in a versioned folder in `/opt/homebrew/Cellar`, and you need to add it to your PATH manually if you want to use it.

Homebrew prints this when installing `llvm`, which gives you a hint about how to put it on the PATH:

```
llvm is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
```

I don't know how this translates to Linuxbrew (if at all).

**Comment by vtraag** [comment]
> Here's the software available on runners:
> 
> https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> 
> Simplest might be to use Linuxbrew. Pay attention to the note that says that it's not in the path by default.

I'm probably missing something, but I don't see Linuxbrew on that page anywhere?

Wouldn't it be simpler to use Ubuntu and install using `apt` (which I think can also be cached) instead of Linuxbrew?
