### ISSUE TITLE
Deprecate functions dealing with non-finite quantitites

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2237]
igraph has the following set of functions:

```
int igraph_finite(double x) {
    return isfinite(x);
}

int igraph_is_nan(double x) {
    return isnan(x);
}

int igraph_is_inf(double x) {
    return isinf(x) != 0;
}

int igraph_is_posinf(double x) {
    return isinf(x) && x > 0;
}

int igraph_is_neginf(double x) {
    return isinf(x) && x < 0;
}
```

They should be deprecated and eventually removed. There are (mostly) standard versions of these functions, so having them in igraph makes no sense.

We explicitly require C99, and effectively require a reasonable level of IEEE-754 support (including usable `NAN` and `INFINITY` constants), meaning that we already effectively require standard versions of these functions.

----

One of the benefits of this change is that most compilers will inline `isnan()` and `isfinite()` calls, something they cannot do with `igraph_finite()` or `igraph_is_nan()`.

----

The question is: Do we deprecate in 0.10.2 and remove in 0.11 or do we deprecate only in 0.11?

----

We may also discuss doing the same with the `IGRAPH_NAN`, `IGRAPH_INFINITY`, `IGRAPH_POSINFINITY` and `IGRAPH_NEGINFINITY` constants. However, I should note that the standard `NAN` and `INFINITY` constants have type `float`. I recently changed `IGRAPH_NAN` and `IGRAPH_INFINITY` to have type `igraph_real_t` (i.e., `double`). This consistency in types is useful when enabling certain compiler warnings that would otherwise be triggered. For this reason, I vote for keeping these constants.

**Comment by ntamas** [comment]
Deprecating in 0.10.2 and removing in 0.11 sounds fine for me.

**Comment by szhorvat** [comment]
There is also an undocumented `IGRAPH_FINITE()` macro, defined to `igraph_finite()`. Unless I hear objections, I am going to remove this without any prior deprecation.

**Comment by szhorvat** [comment]
I left in `IGRAPH_FINITE()`, as it triggers the deprecation warning by being defined to `igraph_finite()`. The rest is done.
