### ISSUE TITLE
Error in convex_hull(data) function of R igraph

### ISSUE THREAD

**Issue by arian-code** [igraph/igraph#2251]
I tried convex_hull(data) of R igraph for various problems. The convex graph generated for eil51.tsp from TSPLIB had an error.

I have attached the convex hull generated. eil51.tsp file is available at https://github.com/thorehusfeldt/algdes-labs/blob/master/closest-points/data/eil51-tsp.txt

Kindly let me know if I can contribute towards debugging in any way
![my_convex_eil51](https://user-images.githubusercontent.com/43011995/45111538-d4ce4780-b162-11e8-96bc-edeb5acd070c.png)

**Comment by ntamas** [comment]
If there's an issue with this function,  I'm pretty sure it's in the C core, and not in the R interface, although we still need to check whether it is indeed a problem now. Transferring to the C core.

**Comment by ntamas** [comment]
This has actually been fixed a while ago, `test_bug_1115` explicitly tests this case in `tests/unit/igraph_convex_hull.c`.
