### ISSUE TITLE
Add DSatur as a graph coloring algorithm 

### ISSUE THREAD

**Issue by professorcode1** [igraph/igraph#2253]
DSatur is different from greedy coloring in the sense that it chooses the node which maximizes the number of colors used to color its neighbors. 

It will be useful when implementing the Ant-colony graph coloring algorithm since the coloring procedure it uses is a variation of DSatur, so DSatur needs to implemented for it anyways.   

@szhorvat

**Comment by szhorvat** [comment]
Note that Brélaz's dsatur algorithm _is_ a greedy colouring. Colours are assigned sequentially, and once a colour has been assigned, it is never changed. That is what greedy means. Be careful with Wikipedia, as there are many sloppy articles. 

Therefore, this feature should be added as a new heuristic to `igraph_vertex_coloring_greedy()`.

**Comment by professorcode1** [comment]
[#2283](https://github.com/igraph/igraph/pull/2283) I have done as asked and it also an improvement. The greedy method took 11 colors to color the graph in examples/simple/igraph_coloring.c and with d-satur it takes 7. Also sorry it took so long to make this simple pull request. I got busy with university work.

**Comment by professorcode1** [comment]
Sorry there are some error. Some memory leaks and unused variable. Ignore last comment let me fix them.

**Comment by professorcode1** [comment]
[#2284](https://github.com/igraph/igraph/pull/2284) fixed the memory leak. All good now. Please review and merge. Once you merge I will begin coding the metaheuristic algorithm.

**Comment by szhorvat** [comment]
It is not necessary to close old PRs and open new ones to fix issues. Please simply continue pushing commits to the same PR (i.e. #2284 from now on).

**Comment by professorcode1** [comment]
I will not create new PR anymore. I didn't know it was possible to commit once a pull request was made. Anyways, please review my code. I don't have anymore changes I want to make.
