### ISSUE TITLE
t/b/igraph_distances.c builds but fails

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/igraph#2259]
igraph version 0.10.2

The test tests/benchmarks/igraph_distances.c  fails  (on Debian/Sid (amd64 arch)).
It builds well but fails; the output reads

```
|> Benchmark file: igraph_distances.c
|  1 vcount=100, p=0.5, Unweighted, 200x                                           0.145s  0.142s  0.002s
|  2 vcount=100, p=0.5, Dijkstra, 200x                                              1.03s   1.03s      0s
|  3 vcount=100, p=0.5, Unweighted Floyd-Warshall, 200x                            0.225s  0.225s      0s
|  4 vcount=100, p=0.5, Floyd-Warshall, 200x                                       0.302s  0.302s      0s
Error at src/paths/bellman_ford.c:158 : Negative loop in graph while calculating distances with Bellman-Ford algorithm. - Negative loop detected while calculating shortest paths.
Aborted
```
hth

**Comment by szhorvat** [comment]
Thanks for the report! 

Strangely, I can reproduce this when using GCC (tested versions 7 and 12) but not with Clang (tested Apple Clang 11 and Clang 15). When I wrote that benchmark, I only tried it with Clang.

**Comment by szhorvat** [comment]
Interestingly, with GCC, all of Bellman-Ford, Johnson, and Floyd-Warshall report a negative loop. Johnson uses Bellman-Ford internally, but Floyd-Warshall is an entirely separate implementation. Thus the graph does truly appear to have a negative loop.

The question is: How is it possible that this happens with one compiler but not another one?

The graph is generated randomly, and there is a chance of creating negative loops. This benchmark does set a seed.  When I wrote the benchmark, I simply played with the graph generation parameters and the random seed to avoid negative loops.

**Comment by szhorvat** [comment]
It was an evaluation order issue. Evaluation order to RNG calls was different between GCC and Clang which lead to different random weights with the two compilers.

The good news is that this was an issue with the benchmark, not the library. Thanks again for reporting!

**Comment by jgmbenoit** [comment]
Perfect.
