### ISSUE TITLE
PageRank claims to replace negative weights with zeros, but behaviour is different

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2260]
`igraph_pagerank()` with the ARPACK methods claims to replace negative weights with exact zeros. However, the function behaves differently when passing in a negative weight vs a zero weight for the same graph.

Example:

```
In[2]:= g = 
  Graph[{1 -> 2, 2 -> 3, 3 -> 1, 2 -> 1}, EdgeWeight -> {1, 2, 3, 0}];

In[3]:= IGPageRank[g, Method -> "Arnoldi"]

Out[3]= {0.333333, 0.333333, 0.333333}

In[4]:= g = 
  Graph[{1 -> 2, 2 -> 3, 3 -> 1, 2 -> 1}, EdgeWeight -> {1, 2, 3, -1}];

In[5]:= IGPageRank[g, Method -> "Arnoldi"]

During evaluation of In[5]:= IGraphM::warning: src/centrality/pagerank.c:656 - Replacing negative weights with zeros during PageRank calculation.

During evaluation of In[5]:= IGraphM::warning: The PageRank eigenvalue should be 1, actual eigenvalue is 0.858257571836022. Possible convergence problem.

Out[5]= {0.277928, 0.333512, 0.38856}
```

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1212871/203079684-d0833bdc-5287-49c7-938e-155597ed8cd2.png">

----

We should also think about whether simply ignoring negative values is useful behaviour. Why not throw an error instead? Note that the PRPACK method does not even show a warning.  One possible situation where this is useful is if someone produced weights which turned out to be negative only due to numerical roundoff error (e.g. `1e-15`) but they should be exact zeros.

Personally I would favour throwing an error whenever there are negative weights. Even if these are the result of roundoff errors, it should be the user's responsibility to recognize this situation and clip at zero, not igraph's. Silently accepting negative weights (as the PRPACK method does) is even dangerous, as users may not realize that they are passing in incorrect data.

**Comment by szhorvat** [comment]
`igraph_i_personalized_pagerank_arpack()` replaces negative weights with zeros when calculating vertex strengths, but not in other parts of the calculation. Notable, `igraph_i_pagerank2()`, i.e. the callback function used by ARPACK, does not do the same replacement. This inconsistency is the cause of the issue.

My recommendation is to change both the ARPACK and PRPACK methods to:

 - Throw an error on negative weights
 - Throw an error on NaN weights

Any objection?

**Comment by GroteGnoom** [comment]
Yes, we should throw an error.

**Comment by szhorvat** [comment]
Warning for negative weights was added in https://github.com/igraph/igraph/commit/d37574198a3782becc1019571d0873c1a610c7e2. If there are no comments by @ntamas I'll go ahead with the proposed fix.

**Comment by szhorvat** [comment]
Regarding not negative, but exact zero weights:

It seems that when we have a source node (no incoming connections), and set all its outgoing weights to zero, ARPACK fails to converge. If we _remove_ all outgoing edges, making this node isolated, then ARPACK works fine. I did not dig into the mathematics of the problem to understand why.

Example:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1212871/203094521-2b17bf0a-af0f-4a0f-8998-175311c1fa81.png">


Set `4 -> 1` weight to zero:

```
In[35]:= IGPageRank[
 Graph[{1, 2, 3, 4}, {1 -> 2, 2 -> 3, 3 -> 1, 4 -> 1}, 
  EdgeWeight -> {1, 1, 1, 0}],
 Method -> "Arnoldi"
 ]

During evaluation of In[35]:= IGraphM::warning: src/linalg/arpack.c:890 - ARPACK solver failed to converge (3001 iterations, 0/1 eigenvectors converged).

During evaluation of In[35]:= IGraphM::error: src/linalg/arpack.c:1368 - ARPACK error.

During evaluation of In[35]:= IGraphM::error: igraph returned with error: Maximum number of iterations reached.

Out[35]= $Failed
```

Remove `4 -> 1` entirely:

```
In[36]:= IGPageRank[
 Graph[{1, 2, 3, 4}, {1 -> 2, 2 -> 3, 3 -> 1}, 
  EdgeWeight -> {1, 1, 1}],
 Method -> "Arnoldi"
 ]

Out[36]= {0.31746, 0.31746, 0.31746, 0.047619}
```

**Comment by szhorvat** [comment]
Issue from above comment is fixed.
