### ISSUE TITLE
Some code relies on ajdlist_init() returning sorted results

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2263]
We appear to have some code which assumes that adjlists are returned in sorted order:

https://github.com/igraph/igraph/blob/master/src/misc/cocitation.c#L271

https://github.com/igraph/igraph/blob/master/src/misc/cocitation.c#L361

We should either document that this is what `igraph_adjlist_init()` does (at least internally!) or we should rewrite this code to perform the sorting explicitly. If we leave things as the are, eventually we may modify adjlist functions to return non-sorted results, which will invisibly break things. @ntamas, when you added the self-loop and multi-edge simplification features to the adjlist functions, did you ensure that the result stays sorted?

The code I linked above computes intersections of neighbour sets. This is a generally useful operation. I also wrote rather similar code recently, but since I assumed that I shouldn't rely on the adjlist being sorted, I set up some macros to sort it:

https://github.com/igraph/igraph/blob/master/src/properties/ecc.c#L50

**Comment by szhorvat** [comment]
It's good to note that when one needs to compute the size of neighbour set intersections, there are algorithms that do not rely on sorting. For example, we may use an integer "mark vector" of length `vcount` and mark elements from the first neighbour set. Then check how many from the second were marked. Incrementing the mark in each iteration ensures that the vector does not need to be zeroed (slow) every time.

However, I suspect that this will be considerably slower than the current approach as soon as the mark vector no longer fits in the cache.

**Comment by szhorvat** [comment]
OK, never mind:

It is documented for `igraph_neighbors` that:

> Starting from igraph version 0.4 this vector is always sorted, the vertex IDs are in increasing order.

This should be documented for `igraph_adjlist_init()` and `igraph_lazy_adjlist_init()` as well.

----

If we ever want to move away from these vectors being sorted, we might introduce additional sorted versions of `igraph_neighbors()`, `igraph_adjlist_init()` and `igraph_lazy_adjlist_init()`, and make use of them wherever it matters. After that we can drop the sorting promise from the standard versions.

----

I will go ahead now and:

 - [ ] Document sorting for adjlist functions.
 - [ ] Refactor `igraph_ecc()` to not do unnecessary sorting.

Comments on all of the above would still be welcome, @ntamas .

**Comment by ntamas** [comment]
Confirmed that the intention and implicit assumption was that the adjacency lists are sorted, and I think that right now it does not have significant performance drawbacks.

Sorted set intersection / union routines might be refactored to separate internal functions if you see that they keep on popping up all around the place.

**Comment by szhorvat** [comment]
@ntamas Can you also confirm that you did not break sorting when you implemented removing self-loops and multi-edges from the adjlist?

I will then go ahead and document sorting.

**Comment by ntamas** [comment]
> Can you also confirm that you did not break sorting when you implemented removing self-loops and multi-edges from the adjlist?

Confirmed. See the implementations in `igraph_i_simplify_sorted_int_adjacency_vector_in_place()`; it always goes like this:

```
for (i = 0, j = 0; i < n; i++) {
    if (some_condition) {
        VECTOR(v)[p] = VECTOR(v)[i];
        p++;
    }
}
```

so it is order-preserving.

**Comment by szhorvat** [comment]
TODO: We need to check if `adjlist_init_complementer()` also returns sorted lists. There is a danger that an `adjlist_init()` somewhere gets replaced by an `adjlist_init_complementer()` and that breaks an implicit (or not sufficiently clearly spelt out) assumption of neighbour lists being sorted.

In fact, I am wondering if we should have `adjlist_init_complementer()` at all. Arguments against:

 - It is not entirely consistent in its interface with `adjlist_init()`.
 - It is only used in the independent vertex set finding code. IIRC (which I may not) this uses the old and slow clique finder code which should probably be replaced with the current better implementations we have: (1) Cliquer when searching for all independent vertex sets (2) Our maximum clique finder when looking for maximal independent vertex sets.

**Comment by szhorvat** [comment]
`adjlist_init_complementer()` also produces a sorted order.

**Comment by szhorvat** [comment]
I chose not to make intersection size calculations common at this moment as we would need to consider how to handle duplicate entries very carefully.

**Comment by ntamas** [comment]
FYI, I confirmed that `igraph_adjlist_init_complementer()` returns vertex IDs in sorted order. This was a question above.
