### ISSUE TITLE
Warnings/errors that should be assertions, dubious uses of "defensive programming"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2274]
This issue collects some dubious consistency checks and mitigations in igraph. Most of these should probably be fully understood and then replaced with proper assertions.

----

 - [x] In the independent vertex set finder:

    https://github.com/igraph/igraph/blob/master/src/cliques/cliques.c#L81

            /* Now, if l == size-1, the two vectors are totally equal.
            This is a bug */
            if (l == size - 1) {
                IGRAPH_WARNING("possible bug in igraph_independent_vertex_sets");
                m = n;
            } else {

 - [x] In `is_dag`:

    https://github.com/igraph/igraph/blob/master/src/properties/dag.c#L201

        if (vertices_left < 0) {
            IGRAPH_WARNING("vertices_left < 0 in igraph_is_dag, possible bug");
        }

 - [x] In `community_fastgreedy`:

    https://github.com/igraph/igraph/blob/master/src/community/fast_modularity.c#L412

        /* Did we find it? We should have -- otherwise it's a bug */
        if (i >= n) {
            IGRAPH_WARNING("changed_pair not found in neighbor vector while re-sorting "
                           "the neighbors of a community; this is probably a bug. Falling back to "
                           "full sort instead."
                          );
        } else {

 - [x] In `community_mulitlevel`:

    https://github.com/igraph/igraph/blob/master/src/community/louvain.c#L273

    ```
    /* TODO: should this be an assertion instead? */
    if (igraph_vector_int_size(membership) < no_of_nodes) {
        IGRAPH_ERROR("Cannot shrink graph, membership vector too short.",
                     IGRAPH_EINVAL);
    }
    ```

**Comment by ntamas** [comment]
independent set finder instance replaced with an assertion in d0044d8cf

**Comment by ntamas** [comment]
Fixed those that I'm familiar with as I wrote the code a long time ago. I'm not sure about the Louvain method but I'll take a look at it nevertheless.

**Comment by ntamas** [comment]
Okay, I've replaced the one in the Louvain method as well; it seemed pretty trivial.
Anything else you want to add here or shall we close this?

**Comment by szhorvat** [comment]
If you're confident that the changes are fine, let's close it.
