### ISSUE TITLE
A function to find edges contained within an induced subgraph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2277]
**What is the feature or improvement you would like to see?**

A function that returns the edge IDs contained within a subgraph induced by some vertices.

```
igraph_error_t igraph_induced_subgraph_edges(const igraph_t *graph, igraph_vs_t vids, igraph_vector_int_t *edges);
```

The `edges` output parameter will contain the IDs of edges whose both endpoints are within `vids`. In other words, it returns the edges in the subgraph induced by `vids`.

**Use cases for the feature**

 - Faster than `igraph_induced_subgraph()`, and sometimes we don't need a new graph, only its edges.
 - Existing functions don't give easy access to the edges in a subgraph. If we construct a new graph using `igraph_induced_subgraph(_map)`, the edges IDs in that graph do not relate to the edge IDs in the original graph.
 - See discussion at https://github.com/igraph/python-igraph/issues/507#issuecomment-1339407988
 - Suppose we need to compute statistics on edge attributes of a subgraph. E.g., what is the total edge weight contained within a community?

**Notes**

 - The name `igraph_induced_subgraph_edges()` is very close to `igraph_subgraph_edges()`, which is not ideal. Personally I do not like the name `igraph_subgraph_edges()` as it sounds as if it produced edges as _output_. In fact it takes edges as input, so I'd find the name `igraph_edge_subgraph()` more intuitive.
 - It might make sense to provide multiple implementations with different performance characteristics, just the `impl` parameter of `igraph_induces_subgraph()`. The function could work like this:

        for v in vids:
            for e in incident_edges(v):
                if other(e, v) in vids:
                    result.push_back(e)

    Now the question is how to test for membership in `vids`. One way is to allocate a boolean array of `vcount` size and mark each vertex from `vids` in it. Then we have an O(1) time, but O(vcount) memory solution.  Another way is to use the existing set data structure, which has worse time performance but much better memory performance.  We should support taking tiny subgraphs out of very large graphs.

    My preference is to _not_ have an `impl` argument, and instead use the set implementation. We can add a marker-vector implementation for the case of large subgraphs later, if benchmarking indicates a need.

**Comment by ntamas** [comment]
> The name igraph_induced_subgraph_edges() is very close to igraph_subgraph_edges(), which is not ideal.

Alternative proposal: `igraph_get_edges_of_induced_subgraph()`. People seem to be very wary of using prepositions in function names, but I don't know why. Maybe this comes from the old days when we haven't had good IDEs with autocompletion, but nowadays I don't really mind if the name of a function is long if it makes the intention clear.

The renaming of `igraph_subgraph_edges()` is discussed in #2278; there I've proposed `igraph_subgraph_from_edges()` along the same lines (i.e. use prepositions to make the intention clear).

As for the `impl` argument, I'd also prefer not to have one if we can choose from multiple implementation automatically using some heuristics.

**Comment by szhorvat** [comment]
I don't love `igraph_get_edges_of_induced_subgraph()`. It's very long.

At this point it would make sense to come up with a consistent naming scheme and apply it everywhere. That helps with predictability. I would support anything that is motivated by consistency, even if it's long.
