### ISSUE TITLE
Rename igraph_subgraph_edges()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2278]
In #2277 I explained why I think that the naming of the `igraph_subgraph_edges()` function is not ideal. I propose renaming it to `igraph_edge_subgraph()`, which better indicates that this function produces a _(sub)graph_ based on some _edges_. It does not produce some _edges_ based on a _subgraph_, as its name would suggest to me. Please see the **Notes** section of #2277 for more details.

This issue is for discussion, so people can indicate their agreement / disagreement.

Any renaming should go through the usual gradual add new function / deprecate old function / remove old function route.

**Comment by ntamas** [comment]
How about `igraph_subgraph_from_edges()`. This would then be analogous to `igraph_matrix_view_from_vector`, `igraph_tree_from_parent_vector` and `igraph_from_prufer` and it would make it clear that it's creating a subgraph _from_ edges. IMHO `igraph_edge_subgraph()` is just as ambiguous as we have `igraph_edge()` for an entirely different purpose.

**Comment by szhorvat** [comment]
`igraph_subgraph_from_edges()` sounds good to me.
