### ISSUE TITLE
igraph_i_neigbors() and igraph_i_inclist() incorrecly remove multi-self-loops

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2281]
**Describe the bug**
`igraph_i_neigbors()` and `igraph_i_inclist()` incorrectly remove multi-self-loops from undirected graphs when using `IGRAPH_LOOPS_ONCE`.

**To reproduce**

See `tests/unit/adj.c`which I just added.

**Version information**
Current `master`, likely present in 0.9 as well, where these functions were exposed to R/igraph recently.

**Comment by szhorvat** [comment]
@ntamas Would you have time to take this, since you implemented the current version of these? I would suggest a complete refactoring, see #2280.

**Comment by szhorvat** [comment]
The current code seems to take the approach of _removing_ the duplicate pair of each self-loop, but it cannot distinguish a duplicate pair of a self-loop for an entirely separate self-loop on the same vertex. It may be better to avoid generating the duplicate pair in the first place instead of removing it after it's already been generated.  The duplicate pairs come from considering the loop both in the "IN" and the "OUT" direction, handled in two conditional. It should only be generated in one of the two directions.

**Comment by ntamas** [comment]
I think this is now fixed in 884199727, at least it passes all the tests that you have added in `tests/unit/adj.c`.
