### ISSUE TITLE
Implement a generic heap

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2285]
This issue provides a space for the discussing the implementation of a generic heap which can store more than just numbers.

Requirements:

 - Should be able to store arbitrary [plain old data](https://en.wikipedia.org/wiki/Passive_data_structure) objects.
 - Takes a custom comparison function instead of using `<`.
 - Since this will be used to store objects associated with graph vertices, it should have the two-way functionality of `2wheap`, i.e. (1) it should store indices in addition to values (2) value lookup should be possible based on indices.

There are several way to implement this. A simple way is to based it on pointers to objects. However, this requires allocating each and every object with `malloc()`, which will have bad performance when the number of objects is the same as the number of vertices. Therefore I suggest an interface similar to `qsort()`: store objects directly instead of just pointers to objects; as parameter, take the object size.

----

My suggestion for the API is the following:

The comparison function will have the same signature as in the case of `qsort()`:

```
typedef int cmp_t(const void *, const void *);
```

The constructor is

```
igraph_error_t igraph_genheap_init(igraph_genheap_t *h, igraph_integer_t size, size_t objsize, cmp_t cmp);
```

It saves the object size `objsize` and the comparison function `cmp`.  This will be a heap with a fixed maximum size, just like `igraph_2wheap_t`.

The API generally mimics `2wheap_t`, except that it takes `void *` instead of integers.

**Comment by ntamas** [comment]
Sounds good! And if someone needs pointers to objects, it's entirely possible to store `void*` pointers in the generic heap and then it's the user's responsibility to take care of calling `malloc()` and `free()` as needed; the heap will never own the objects in it.

**Comment by szhorvat** [comment]
The https://github.com/igraph/igraph/tree/feat/genheap branch contains the beginnings of an implementation. So far it's mostly a modified copy of 2wheap.

TODO:

 - [ ] Do not allocate storage for all elements right at the start.
 - [ ] Add header
 - [ ] Add tests

**Comment by szhorvat** [comment]
@ntamas I think this is good enough for a review at this point. We can fix up the memory allocation a bit later.

**Comment by ntamas** [comment]
Checked the code in the branch and it looks good to me. (I guess it was adapted from the existing two-way heap code). We need copyright headers in all the newly added files, otherwise it's good to go.

**Comment by szhorvat** [comment]
This is now merged into `master`, so it can be used in #2284. We can continue making improvements in the meantime. @ntamas What do you think about retaining the "deactivation" feature? Do we want that, or should it be removed?

**Comment by ntamas** [comment]
Well, there was at least one algorithm in the past where the deactivation feature was used, although not with the generic heap. Plus, the code is already there. I would not put efforts towards removing it at this point.

**Comment by szhorvat** [comment]
@ntamas The first checkbox here is not yet done: https://github.com/igraph/igraph/issues/2285#issuecomment-1367235554 Do we want to bother at all ... ?

**Comment by ntamas** [comment]
I'd say let's fix this when it becomes a blocker for something or someone.

**Comment by szhorvat** [comment]
I added a TODO note in the sources, otherwise this will be forgotten completely.
