### ISSUE TITLE
Kamada-Kawai implementation in v0.10.3 produces a bad layout

### ISSUE THREAD

**Issue by empet** [igraph/igraph#2292]
It seems that between python-igraph v0.7.1 and v0.10.3 (or maybe on C version) some  changes have been performed on
the kamada-kawai layout, that now lead  to  wrong  node connections.
A few years ago I compared kk layout appearence, using igraph, (py)graphviz and networkx. 
The igraph kk-layout worked excellent both on connected and disconnected graphs as  can be seen
in the notebooks posted here [https://github.com/empet/Networks](https://github.com/empet/Networks) (click on the links in README, to see the two notebooks in nbviewer).
This is a disconnected  graph, defined by igraph v0.7.1 from the file, `Data/netscience.gml`,
![netsci-kk-igraph071](https://user-images.githubusercontent.com/3627253/211918852-5be15c0e-ea8f-4289-82b9-e30290beb71d.png)

and with the same code, from the corresponding notebook,  the graph defined by the version 0.10.3
is this one  :(
![netsci-kk-igraph0103](https://user-images.githubusercontent.com/3627253/211919006-78167054-bd97-447b-a39b-262e747e3edf.png)
    
    
Here,  [https://nbviewer.org/github/empet/Networks/blob/master/kk-layout-in-3-packages-zika.ipynb](https://nbviewer.org/github/empet/Networks/blob/master/kk-layout-in-3-packages-zika.ipynb) is a nice unrooted tree with kk-layout, v0. 7.1 ( `Data/zika.gml`), and this one, the same tree with v0.10.3:
![connected-ig-0103](https://user-images.githubusercontent.com/3627253/211919440-6a9bcb56-5a8a-4410-be01-c9d6d4faa8e2.png)

**Comment by szhorvat** [comment]
This is related to https://github.com/igraph/igraph/issues/963

I changed the initial condition of the KK layout, along with making several fixes, which improved the situation for most graphs, but may have made it worse for a few. It seems the graphs that you have are unlucky. Setting initial point manually will certainly help. I'll look into this later.

**Comment by empet** [comment]
Thank you both for the suggestion. I'll check today all versions, 0.9.x.

**Comment by empet** [comment]
I started with a random version, 0.9.8, and the two graphs (netsci and zika) look way better that those generated by 0.10.3, but far from  those with 0.7.1:
![netsci-098](https://user-images.githubusercontent.com/3627253/212036661-f2d2afb1-ba56-49f6-bdf0-3d214947edf4.png)

![zika-098](https://user-images.githubusercontent.com/3627253/212036728-a15f06ba-def7-4255-aab3-932ec2986c6c.png)

Unfortunately any version below 0.9.8 is not available, via pip:
```
(igraphs) C:\Users\empet>pip install igraph==0.9.6
ERROR: Could not find a version that satisfies the requirement igraph==0.9.6
(from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10,
 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.10.0, 0.10.1, 0.10.2, 0.10.3)
ERROR: No matching distribution found for igraph==0.9.6
```
I also tried to look for, and install versions before 0.9.8 from Gohlke's pythonlibs   [https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.lfd.uci.edu/~gohlke/pythonlibs/),  as I installed all python-igraph,  versions <= 0.7.1, but its certificate expired 4 days ago. An attempt to access the above link throws the error:
```
Your connection is not private
Attackers might be trying to steal your information from www.lfd.uci.edu (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
```
Is there any other option to get installed a python version,  in  the interval [0.9, 0.9.11], on windows?

**Comment by szhorvat** [comment]
I also look into this in the meantime, though I mostly used the Mathematica interface of igraph to experiment (for lack of time).

At some point, the KK and FR layouts were completely rewritten to match the original papers. It is possible that py-igraph 0.7.1 still uses the old implementation, which is no longer available. I believe that this old implementation was devised independently and it wasn't quite fair to call them KK and FR.

The current implementation follows the original paper of Kamada and Kawai closely. However, the implementation was buggy until C/igraph 0.9.8 and prone to numerical instability. This is fixed form 0.9.9 onwards, see the [changelog](https://github.com/igraph/igraph/blob/master/CHANGELOG.md#099---2022-06-04). Note that these are version numbers for C/igraph, and I do not recall how they correspond to py-igraph's versions.

Before going further, I should not that python-igraph appears to use a fixed number of iterations for KK, which is incorrect. I opened an issue for this: https://github.com/igraph/python-igraph/issues/627  I suggest you set `maxiter` to 50 times the vertex count. This fixes the problem with `zika.gml`, but not with `netscience.gml`.

The fixes I made for 0.9.9 eliminated issues of the kind you show here in many cases. But in the end, the KK algorithm is quite naive, and it won't perform well for all networks. Sometimes the system gets effectively stuck in a local energy minimum, which is what seems to be happening here. This can usually be resolved by using different initial vertex coordinates. The pre-0.9.9 behaviour can often be approximated by using the output of `layout_circle` as the initial coordinates. Alternatively, you can rescale the weights (e.g. double or halve them).

Unfortunately, based on my experience, it won't be possible to improve the situation much here. There will always be pathological cases where the algorithm gets stuck in a local minimum. This is a limitation of the naive KK algorithm. The way forward here is to implement more advanced optimization techniques such as those described by Yifan Hu in http://yifanhu.net/PUB/graph_draw_small.pdf But that would be a different layout function, and a lot of work to implement.

----

A final note is that the KK layout is not very suitable for this graph. First, larger weights in this graph indicate stronger connections. However, KK interprets large weights as distances, and pushes vertices connected with a large-weight (i.e. long) edge far apart. Second, there are a very large number of connected components. Most layout algorithms, including KK, are designed for connected graphs. Ideally, each component would be laid out separately and then the layouts would be merged together. igraph's KK implementation uses a hack to handle disconnected graphs, but this is not ideal. See https://github.com/igraph/igraph/commit/2263bbc0d1db906e78c93f6688961a31fcd5f459

----

Anyway, let's leave this issue open for a while to see if someone comes up with a better idea about how to handle this, or a better heuristic for choosing the initial coordinates.

**Comment by empet** [comment]
I wonder if in the meantime someone took care of solving this issue so that KK is an acceptable layout regardless of the graph type. The initial answer given by  @szhorvat  that my graphs are unlucky is not the expected answer and solution.

**Comment by iosonofabio** [comment]
Was @szhorvat's answer wrong or just unexpected?

**Comment by szhorvat** [comment]
The realistic answer here is that this will almost certainly not be improved.

A more straightforward summary of what I wrote above is:

 - `igraph_layout_kamada_kawai()` follows closely the paper of Kamada and Kawai, which describes a rather naive algorithm that simply won't work well on every input. In the 30 years since that paper, much better algorithms have been proposed. I pointed to Yifan Hu's work above, which I wanted to see implemented in igraph for a long time, but we don't have the spare capacity at the moment. As always, contributions are very welcome.
 - There are some choices made in the implementation of the KK algorithm which affect the result, such as the choice of the initial coordinates. I would be open to changing this choice, but no single choice will work well for all graphs with any kind of weight. Any change we implement should be tested to make sure that it leads to improvements on a majority of common use cases.  Doing this testing is difficult and time consuming. Once again, you are welcome to do this work, but my opinion is that this is likely not a good use of time. The real solution here is to implement better layout methods.

**Comment by empet** [comment]
I saved the version 0.7.1 that worked with Python 3.7 and will keep that version in an environment. For years KK-layout was very good and appreciated, and now it doesn't work for all graphs. :(

**Comment by szhorvat** [comment]
If you want the old layouts from 0.7 back, this is the issue to vote for: #2024

**Comment by iosonofabio** [comment]
@empet could you contribute a PR with either the old FR/KK algos or newer ones as proposed by @szhorvat ? That would definitely help, since we are overwhelmed by work ATM.

**Comment by szhorvat** [comment]
The undesirable output is a result of the method, not the implementation. I don't see any realistic way to improve on this, so closing. A more productive use of time is implementing methods that don't suffer from such issues (see #2331).
