### ISSUE TITLE
"Error in try_fetch(utils::getFromNamespace(algorithm, "igraph"), error = function(cnd) { : could not find function "try_fetch" "

### ISSUE THREAD

**Issue by MANZHAOHUI** [igraph/igraph#2298]
**Describe the bug**
when I was using clustree, I constantly got this error despite my reinstalling igraph. 

**To reproduce**
cluster_tree <- clustree(combined.int.clustree,prefix = "integrated_snn_res.") combined.int.clustree is a seurat single cell RNA object.

**Version information**
 ‘1.2.6’

**Comment by ntamas** [comment]
This has nothing to do with igraph; it is complaining about a function named `try_fetch`, which is supposed to be in the `rlang` package. Try installing `rlang`.

**Comment by MANZHAOHUI** [comment]
thank you. Already reinstalled rlang, but it didn't work.
