### ISSUE TITLE
Rename igraph_automorphisms() to igraph_count_automorphisms()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2299]
We should rename `igraph_automorphisms()` to `igraph_count_automorphisms()`. This reduces confusion and is consistent with `igraph_count_isomorphisms_vf2()`.

Other options are to put `_count()` at the end (in analogy with `igraph_vcount()`); or to add `_bliss()` to the end, since most isomorphism functions indicate the algorithm in their name.

**Comment by ntamas** [comment]
`count_automorphisms()` is okay for me, with the usual deprecation warning.
