### ISSUE TITLE
Hub and authority scores mishandle self-loops in undirected graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2301]
This issue is for discussing how to handle hub and authority scores in undirected graphs.

First of all, these scores are meant to be used in directed graphs, and are pointless to calculate in undirected graphs. However, if we do, we should at least be consistent.

The hub and authority scores are the leading eigenvectors of $AA^T$ and $A^T A$, respectively, where $A$ is the adjacency matrix. When the graph is undirected, $A$ is symmetric, thus $AA^T = A^TA = A^2$, and the eigenvectors of $A^2$ are of course the same as that of $A$. Thus, hub and authority scores are both equal to the eigenvector centrality.

As usual, there is a subtlety with self-loops: when the graph is undirected, $A$ should contain _twice_ the number of self-loops on the diagonal, as this corresponds to interpreting each edge bidirectionally. This is what we do in all other cases in igraph.  However, the current implementation of `igraph_hub_and_authority_scores()` counts self-loops only once in undirected graphs, making it inconsistent with the rest of the system, as well as with `igraph_eigenvector_centrality()`.

TODO:

 - [ ] Fix self-loops counting
 - [ ] Point out in docs that these are meant for directed graphs only, and are otherwise equal to eigenvector centrality
 - [ ] Point out in eigenvector centrality docs that it's meant for undirected graphs, look at hub/authority scores if you want directed graphs
 - [ ] Point out relations to bibcoupling and cocitation matrices. Note that these matrices have zero diagonals.

**Comment by szhorvat** [comment]
@GroteGnoom Would you have time and interest to take the first TODO item?

**Comment by szhorvat** [comment]
Never mind, this is a simple enough fix.

**Comment by szhorvat** [comment]
Never mind, this is a simple enough fix.

**Comment by szhorvat** [comment]
@ntamas @krlmlr I suggest backporting this to 0.9 and including it in R/igraph 1.3.6. If we do that, revdepchecks need to be re-run. Shall I go ahead?

**Comment by ntamas** [comment]
Feel free to go ahead with the backport, but we might not include it in igraph 1.3.6; there's a pending deadline for us to fix the _extremely serious_ and _dangerous_ [warnings in the CRAN checks](https://cran.r-project.org/web/checks/check_results_igraph.html) by Feb 6, otherwise igraph will be removed from CRAN :) Ultimately I'd leave it to @krlmlr to decide whether there's time to re-run the revdepchecks or we should just roll with what we have now.

**Comment by szhorvat** [comment]
Fix is backported. @krlmlr, the risk of packages breaking due to this fix is low as hub and authority scores shouldn't be used for undirected graphs in the first place. If you include this, and find a broken dependent package, let me know and I'll explain them what they need to do to adapt.

**Comment by szhorvat** [comment]
@ntamas @krlmlr I was trying to test this locally with R/igraph, and I noticed that these bugfixes are not currently included: 

https://github.com/igraph/igraph/commit/688cde1db1eca1d524fa643898db09d75dae37a8
https://github.com/igraph/igraph/commit/ab3b0b623d399a35c6b066eef281d54dc01d2991

They really _should_ be included, as 1.3.6 would be the first release to use `igraph_i_incident()`, and it shouldn't be relying on a buggy version!

**Comment by ntamas** [comment]
Updated the C core to the head of `release/0.9`, FYI.

**Comment by szhorvat** [comment]
@ntamas You'll need to adapt the code in `rinterface.c` as the signature of `igraph_i_incident()` has changed.

**Comment by ntamas** [comment]
It was done already.
