### ISSUE TITLE
delete_vertices_idx() and induced_subgraph_map() have inconsistent names

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2310]
`igraph_delete_vertices_idx()` and `igraph_induced_subgraph_map()` perform comparable operations: they subset the graph's vertices, and output a mapping and inverse mapping between the old and new vertex IDs. However, their names are confusingly inconsistent.

I propose renaming `igraph_delete_vertices_idx()` to `igraph_delete_vertices_map()` on 0.11 only.

Note that on `develop`, the behaviour of these functions [has already been changed](https://github.com/igraph/igraph/blob/develop/CHANGELOG.md) (now the mapping uses 0-based indexing). So let's not do the renaming/deprecation on `master`.

@vtraag and @ntamas, any objections?

**Comment by ntamas** [comment]
Implemented in the commit above; CI failures are unrelated (related to a merge from `master` back into `develop`).
