### ISSUE TITLE
tests using ARPACK should set random seed

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2312]
Most (all?) igraph functions that use ARPACK now use a randomized starting vector. Thus the unit tests for ARPACK-using functions should set a random seed.

This includes at least:

 - eigenvector centrality
 - hub/authority scores
 - pagerank
 - ...?

Just grep for `rnsolve` / `rssolve` to find affected functions.

It's probably best to deal with #2311 before fixing this issue.

**Comment by ntamas** [comment]
Exactly my thoughts. :+1:
