### ISSUE TITLE
Make ARPACK interruptible

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2317]
`igraph_arpack_rssolve()` and `igraph_arpack_rnsolve()` should be interruptible. This is trivial thanks to ARPACK's reverse communication interface: we call ARPACK in a loop until it indicates that it's finished.

Could someone please test if ARPACK-reliant functions (eigenvector centrality, PageRank with ARPACK method) interrupt correctly at the moment when run on large problems? @vtraag @ntamas @GroteGnoom

**Comment by ntamas** [comment]
Support for interruption added in 47c76b691

**Comment by szhorvat** [comment]
Now why did this seem to interrupt fine in Mathematica even before the patch? I have to check that Mathematica is not doing anything fishy behind my back ...

**Comment by szhorvat** [comment]
> I'll add interruption support to `igraph_arpack_rssolve()` and `igraph_arpack_rnsolve()`, which should hopefully take care of all ARPACK invocations (I think we don't use ARPACK directly elsewhere).

Correct.

**Comment by szhorvat** [comment]
This is now backported to 0.9.
