### ISSUE TITLE
How to read .lgl file with igraph's Python API?

### ISSUE THREAD

**Issue by mgao97** [igraph/igraph#2325]
**What is the feature or improvement you would like to see?**
A concise but mathematically precise description of the requested feature.

**Use cases for the feature**
Explain when and for what purpose the feature would be useful.

**References**
List any relevant references (papers or books describing relevant algorithms).

**Comment by ntamas** [comment]
https://python.igraph.org/en/latest/api/igraph.GraphBase.html#Read_Lgl

Please ask support questions in our [https://igraph.discourse.group/](Discourse group); the issue tracker is reserved for bug reports and feature requests.
