### ISSUE TITLE
Deprecate the name get_incidence()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2326]
`igraph_get_incidence()` produces a bipartite incidence matrix.  A more common use of the term "incidence matrix" is [the edge-vertex incidence matrix](https://en.wikipedia.org/wiki/Incidence_matrix). I propose deprecating the `igraph_get_incidence()` name in 0.11, and renaming this function to something else, so that in 1.0 we can re-use the name for the edge-vertex incidence matrix.

I proposed a more flexible way to get the bipartite incidence matrix in #2196.

There is still room for a function that uses a boolean vector, like `igraph_get_incidence()`  does, but I would rather name this something else, e.g. `igraph_get_bipartite_incidence()`, or better: `igraph_get_bipartite_adjacency()` (in line with describing vertex-vertex relations as "adjacency" and improving consistency) or even `igaph_get_biadjacency()` (shorter is better, we already have `igraph_bigraphical()` in a similar spirit).

**Comment by szhorvat** [comment]
@krlmlr What I wrote here also applies to R/igraph 2.0.

**Comment by ntamas** [comment]
Note that this would also imply the renaming of `igraph_incidence()` to `igraph_biadjacency()` to keep things consistent.
