### ISSUE TITLE
test command `make test` fails (now)

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/igraph#2328]
**Describe the bug**
The `cmake` machinery generates a Makefile  that contains a `test` target which fails in version 0.10.4
(while it does not fails in version 0.10.2). Unfortunately the debian machinery ( `dh_auto_test(1)` more precisely) looks for a `test` or a `check` target  in the present Makefile and process the first one here (`test`) so that the debian machinery fails. I guess that this change of behaviour of the target `test` is not expected.

**To reproduce**
Minimal steps to reproduce the problem:

```
$ cd <SOURCE FOLDER>
$ mkdir BUILD
$ cd BUILD
$ cmake .
$ cmake --build .
$ make test
```

**Version information**
version 0.10.4 grabbed from github.

**Comment by szhorvat** [comment]
> I guess that this change of behaviour of the target `test` is not expected.

This is an intentional change, it's noted in the changelog.  `test` will only run the test but not build them.  This is in fact the de facto standard behaviour of the `test` target with CMake. Even CMake's own build system works this way, with _building_ the tests being controlled by other means.

See #2290

**Comment by jgmbenoit** [comment]
Okay thanks for the update. So it is a debian issue.

**Comment by jgmbenoit** [comment]
Actually the issue was reported a few years ago ([debian bug report #924052](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924052)). I have just given it a ping with a link [#2290](https://github.com/igraph/igraph/issues/2290).
