### ISSUE TITLE
Move igraph_strength() to igraph_interface.h

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2332]
This is a suggestion to move `igraph_strength()` to the same header where `igraph_degree()` lives, i.e. `igraph_interface.h`, and thus reduce the uses of the heavyweight `igraph_structural.h`.

We often use `igraph_strength()` as the real-valued equivalent of the integer `igraph_degree()`.

**Comment by ntamas** [comment]
Not sure about this, but I'm open for discussions. I think that right now `igraph_interface.h` contains only those igraph functions that are "permitted" to access the internals of an `igraph_t`. `igraph_strength()` can be implemented without looking at the internals of `igraph_t` so that's why it is in `igraph_structural.h`. Which is indeed heavyweight, but if it's a problem, then it's probably time to split it up according to topics.

**Comment by szhorvat** [comment]
How about splitting up `igraph_structural.h` by separating lightweight and common functions into a separate header?  I would split these off:

```
igraph_are_connected
igraph_count_multiple
igraph_count_multiple_1
igraph_has_loop
igraph_has_multiple
igraph_is_loop
igraph_is_multiple
igraph_is_mutual
igraph_has_mutual
igraph_is_simple

igraph_maxdegree
igraph_strength
```

And _maybe_ these:

```
igraph_density
igraph_reciprocity

igraph_is_tree
igraph_is_acyclic
igraph_is_forest
```

The rest are non-trivial heavyweight functions.

----

Additionally, I would rename `igraph_topology.h` to `igraph_isomorphism.h` and put the following somewhere else:

```
igraph_topological_sorting
igraph_is_dag
igraph_transitive_closure_dag
```

These are the only three non-isomorphism-related functions in that header.

**Comment by ntamas** [comment]
Sounds OK, but these are technically breaking changes in C because users of the library might have to adapt the included headers in case a function they were using was moved (and they weren't simply including the top-level `igraph.h`). So this must go on `develop` only.

**Comment by szhorvat** [comment]
My understanding was always that the only valid use of igraph is to include `igraph.h`. The sub-headers are an implementation detail, and no promises are made about them. There is absolutely no point for a user to include sub-headers instead of `igraph.h`. As I recall, we did shuffle around functions before.

**Comment by ntamas** [comment]
Good pointl; if this is indeed the case then it should be spelt out explicitly. I was routinely including more specific headers in my igraph projects in a never-quite-measured attempt to cut down on compilation times by including smaller headers only so the compiler does not have to work so much on parsing stuff that it won't need.

**Comment by szhorvat** [comment]
Regarding the main request here, it's not very important, to I'm fine with closing this issue.

Regarding the following:


@szhorvat :
> My understanding was always that the only valid use of igraph is to include `igraph.h`.

@ntamas :
> Good pointl; if this is indeed the case then it should be spelt out explicitly. I was routinely including more specific headers in my igraph projects in a never-quite-measured attempt to cut down on compilation times by including smaller headers only so the compiler does not have to work so much on parsing stuff that it won't need.

I do think we should only support including `igraph.h`, and document this. To avoid complications, let's do it on `develop`.

I strongly suspect that including large headers or many headers does not have much of a performance impact in C. (C++ headers are may be different as they contain implementations.) The real savings by reducing the number of headers are not for projects that use igraph, but for developing igraph itself: when we make a change to a header, it will invalidate the ccache of all files that use it.  Some headers effectively get modified after every commit, due to the commit hash being included in the version.  If igraph's own implementation files included `igraph.h` instead of more granular headers, then the ccache would get invalidated after every single commit.
