### ISSUE TITLE
When will this api（igraph_fundamental_cycles ） be stable? 

### ISSUE THREAD

**Issue by mollon650** [igraph/igraph#2344]
When will this api（igraph_fundamental_cycles ） be stable? 
now This function is experimental

**Comment by szhorvat** [comment]
We cannot give a certain answer. Likely not before version 0.11. I am working on a certain improvement to this function, so there may be changes before 0.11.  Any changes will be clearly noted in the changelog.

We intend to reserve the issue tracker for bugs and feature requests. Please post any future questions on the forum, https://igraph.discourse.group/
