### ISSUE TITLE
Does cmp_epislon() support infinities?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2348]
Does `igraph_cmp_epislon()` support infinities?

 - [x] Document the behaviour with infinities
 - [x] Add tests for infinities
 - [x] Investigate behaviour with NaNs

Naïvely, it makes sense to me that a positive infinity should compare larger than any finite value. A NaN, if supported, should compare unequal to any value, including NaN, just like with `==`.

Additionally: `eps` is normally positive and finite. Is `eps == 0` allowed here? Does it behave reasonably?

**Comment by ntamas** [comment]
I've added some tests in `tests/unit/cmp_epsilon.c` (see af926578b) that aims to establish the baseline behaviour w.r.t. infinities and NaNs. If you are okay with the tests I've added here, let me know and I'll document the behaviour explicitly.

Note that `igraph_cmp_epsilon()` is already tested quite thoroughly but indirectly via `igraph_almost_equals()`, for which we have quite an extensive test suite.

**Comment by szhorvat** [comment]
Yes, it looks great! Thanks for the quick reaction.

**Comment by ntamas** [comment]
Added documentation about the behaviour w.r.t. NaNs and infinities.

Open questions:

* How shall we treat `eps < 0`? There is no way to throw an error code so we must return _something_.
* How shall we treat `eps == 0`? It would be great if we could ensure that this is equivalent to a strict comparison without tolerance.

**Comment by ntamas** [comment]
The case of `eps == 0` is now tested in e10bad0dd

**Comment by szhorvat** [comment]
> How shall we treat `eps < 0`? There is no way to throw an error code so we must return _something_.

Declare it invalid in the docs.

This is not a function that is meant to be exposed to high-level interfaces, so it's reasonable to expect the programmer to be responsible for valid input. It's also a function which should ideally be fast, so let's not do extra error checking.



> * How shall we treat `eps == 0`? It would be great if we could ensure that this is equivalent to a strict comparison without tolerance.

Agreed.

**Comment by ntamas** [comment]
> Declare it invalid in the docs.

Done, see d92d82b4f
