### ISSUE TITLE
How to break up all simple paths calculation?

### ISSUE THREAD

**Issue by PaulineGnsr** [igraph/igraph#2354]
Hi igraph developers,

I am having an issue using _all_simple_path_ function.
I am working with not so big networks (<100 edges) but the calculation of all simple paths of all edges can take up to 10 hours.

Actually, I don't really need to compute all simple paths and I would like to divide the calculation and get all simple paths of a specific length, e.g. 3 vertices only, then 4 vertices only, then 5 vertices only, etc. 
However, the _cutoff_ argument of the function does not allow this since its value represents the maximum length of the alternative paths. So if I want to get alternative paths of e.g. 5 vertices, I will also have to compute alternative paths of 3 vertices and 4 vertices, and this adds time of calculation.

Is there a way to fix this problem? Did I miss something in igraph?

Thank you for your help,
Best,
Pauline

ps: the reason why I want to break up the computation of the simple paths would be a bit long to explain so I hope I was clear enough!

**Comment by szhorvat** [comment]
Hello Pauline,

Can you please transfer your question to the igraph forum? As indicated when you opened this issue, the issue tracker is meant for bug reports and feature requests only. Support questions should go to https://igraph.discourse.group/
