### ISSUE TITLE
source tarball 0.10.5 is polluted with ._* files

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/igraph#2368]
It appears that [igraph-0.10.5.tar.gz](https://github.com/igraph/igraph/releases/download/0.10.5/igraph-0.10.5.tar.gz) is polluted with ._*files.

**Comment by szhorvat** [comment]
I do not see these. Can you give an example of such a file?

Also, unrelated, but FYI: #2633.

**Comment by szhorvat** [comment]
Correction: I do see these if I extract the archive on Linux, but not if I extract it on macOS. Looks like a Mac-specific thing: https://apple.stackexchange.com/q/414947/31058

**Comment by ntamas** [comment]
These are resource forks, and I don't know why they ended up in the tarball now and did not end up there before (I always do the packaging on macOS). There must be some kind of solution to strip these from a tarball and I can integrate that into my build scripts for the next version.

@jgmbenoit Should I release a new tarball for 0.10.5 or can you deal with this in the current version and then we can fix it properly for 0.10.6 or 0.11.0? igraph 0.10.5 is already on Homebrew so replacing the tarball would also involve changing the Homebrew formula as they chech the SHA256 hash of the tarball.

**Comment by szhorvat** [comment]
Not just Homebrew, but several others package managers as well.

**Comment by jgmbenoit** [comment]
I can deal with them, but I would be more comfortable to deal with a clean tarball.

**Comment by ntamas** [comment]
I have added `xattr -rc .` to my build script so it removes all macOS-specific extended attributes from all files in the source tree before packaging. I'll also add a verification step after packaging to ensure that this does not happen again. That should do the trick.

**Comment by szhorvat** [comment]
If this is an issue, maybe there could be a 0.10.6 early next week? That's cleaner than re-uploading the release tarball.

**Comment by jgmbenoit** [comment]
Okay. I will wait for the 0.10.6 tarball.

**Comment by ntamas** [comment]
A new tarball with version number 0.10.6 is now released.
