### ISSUE TITLE
igraph_bipartite_game_gnm() should support multi-edges

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2374]
**What is the feature or improvement you would like to see?**

`igraph_bipartite_game_gnm()` should be capable of generating multi-edges. This is analogous to #2161.

**Use cases for the feature**

 - Analogy with `igraph_erdos_renyi_game_gnm()`
 - Ability to generate random bipartite multigraphs

**References**

 - #2161

**Comment by RohithS98** [comment]
Hi, I would like to try working on this issue if no one else is working on it.

**Comment by szhorvat** [comment]
You are welcome to start, but please note that currently we have very little capacity to guide newcomers and review contributions.

You will need to be comfortable with C and CMake.

To get started, see #2161, the link to the quick start guide within, and the associated (and completed) PR.  This project is completely analogous.

**Comment by szhorvat** [comment]
Implemented in #2375, thanks @RohithS98 !
