### ISSUE TITLE
Integer attribute larger than >= 1 million causes dot-format syntax error

### ISSUE THREAD

**Issue by RUrlus** [igraph/igraph#2384]
**Describe the bug**

Writing a graph with an integer attribute >= 1 million in the `dot` format results in an invalid dot specification that triggers an exception in Graphviz:`syntax ambiguity - badly delimited number '1e' in line ... of input splits into two tokens`

**MRE**

```Python3
from tempfile import NamedTemporaryFile
import igraph as ig

G = ig.Graph(directed=True)

G.add_vertex("A", idx=int(1e6) - 1)
G.add_vertex("B", idx=int(1e6))

G.add_edge("A", "B")

buffer = NamedTemporaryFile()
G.write_dot(buffer.name)

print(buffer.read().decode())
```
outputs
```
/* Created by igraph 0.10.6 */
digraph {
  0 [
    idx=999999
    name=A
  ];
  1 [
    idx=1e+06
    name=B
  ];

  0 -> 1;
}
```

**Version information**

`igraph 0.10.6`

**Comment by szhorvat** [comment]
Thanks for the report!

This must stem from the use of `"%g"` printf format specifier. We need to review all exporters and make sure that the same error does not occur in any of the other ones.

**Comment by szhorvat** [comment]
I looked into this and it seems that it's better to quote all attribute values.

Here's the format description:  https://graphviz.org/doc/info/lang.html An attribute specification looks like `ID=ID`, but an ID may not begin with a digit. However, 

> An ID is just a string; the lack of quote characters in the first two forms is just for simplicity. There is no semantic difference between abc_2 and "abc_2", or between 2.34 and "2.34". 

I have also confirmed that DOT will output `height="5.0e-1"` (quoted) as `height=0.5`, thus it does not mind quotes around numbers.

----

Here's what I believe we need to do:

 - [ ] Quote all attribute _values_ unconditionally. This does not hurt, but can save situations such as the present one.
 - [ ] Add code that determines whether attribute _names_ are valid in DOT, and if yes, check if they need quoting.
 - [ ] igraph only has a generic numerical attribute type, not separate integer and float ones. There's a hack in the DOT writer that attempts to write integral values as integers, but the approach is buggy, as it simply uses `%g`, leading to an `e`-notation and decimal points for large integers.  For example, `9876543` will be printed as `9.87654e+06`. Now, a question is: why is this hack even necessary? Under what circumstances does DOT require integral values to be shown as integers? Can you help researching this @RUrlus ?  Either way, I'll look into improving this, but I want to know why this hack is present (if at all), and I want it documented.

**Comment by RUrlus** [comment]
@szhorvat thanks for the quick response!

From what I've seen is that scientific notation breaks the DOT regexes when it's parsed as a number,
e.g. `"1e-4"` is fine whereas `1e-4` is not.
I think the parsing logic is:
1. anything between double quotes is treated as a string
2. everything else:
> Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits([0-9]), not beginning with a digit;
So `1e-4` is being parsed as a number that fails.

I don't think DOT requires integers to shown as such, although from a user perspective I would expect that integers stay are represented as integers.

**Comment by szhorvat** [comment]
With this fix, 

 - exactly representation integers are printed as such (not more `e` in integers)
 - quoting is done for `e`-notation numbers, but only as necessary

**Comment by RUrlus** [comment]
Thanks @szhorvat
