### ISSUE TITLE
CONTRIBUTORS.md is non-human-readable

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/igraph#2392]
The [CONTRIBUTORS.md](https://github.com/igraph/igraph/blob/master/CONTRIBUTORS.md) file looks great at GitHub, but it is non-human-readable otherwise. It would be great to put a human-readable version of it within the source balls.

**Comment by szhorvat** [comment]
Would it be an option for you to render the file to HTML to make it more easily readable?

This is created by https://allcontributors.org/ and I'm not sure if a plain text list is even possible with this system. The purpose is not just to have a list, but to show contributors in a visually prominent way that is directly viewable on GitHub. I wouldn't want to give this up. I think it motivates contributors because it makes their involvement more noticeable.

**Comment by szhorvat** [comment]
@jgmbenoit On an unrelated note, python-igraph is stuck on 0.10.2 in Debian. Do you happen to have a direct line to the people maintaining it? Quite a few fixes have been made since 0.10.2.

**Comment by ntamas** [comment]
Indeed, the `all-contributors` tooling does not care about generating a human-readable `CONTRIBUTORS.txt` file. However, the contributor list is there in JSON format in `.all-contributorsrc` so we can probably create a pre-commit or pre-release hook that converts that into a human-readable TXT file.

**Comment by jgmbenoit** [comment]
> @jgmbenoit On an unrelated note, python-igraph is stuck on 0.10.2 in Debian. Do you happen to have a direct line to the people maintaining it? Quite a few fixes have been made since 0.10.2.

It appears that one of the uploader is retired ([Debian bugreport #1050270](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050270)). I am taking over. Thanks for the notice. I hope that you have also noticed that igraph is now [backported](https://packages.debian.org/bookworm-backports/libigraph-dev).

**Comment by ntamas** [comment]
Now we have a `CONTRIBUTORS.txt` file that is updated by a pre-commit hook from `.all-contributorsrc`.

**Comment by jgmbenoit** [comment]
I have refreshed the packaging of `python-igraph` in Debian. I have a look on the related R package: can we actually build in principle the `rigraph` against an external version of the C `igraph` library ?

**Comment by szhorvat** [comment]
> can we actually build in principle the `rigraph` against an external version of the C `igraph` library

No, not at the moment. It's perhaps a long-term goal if @krlmlr decides to go that way. The R interface has specific adaptations necessitated by CRAN's requirements (such as no reference to `printf`, even if `printf` is never called).

**Comment by szhorvat** [comment]
@jgmbenoit I see that in Debian, igraph 0.10.11 is only in unstable. Will it make it into trixie? 0.10.11 has a particularly large number of bug fixes compared to 0.10.10, so it's very much worth using it.

**Comment by jgmbenoit** [comment]
Right now, package migrations from unstable to testing/trixie is a big mess. This is because Debian is between two stable releases. This is normal. In detail, igraph has been blocked by the Debian package dpkg, which is tricky to migrate because
it belongs to the Debian machinery. A lot of packages have been blocked, and a lot of maintainers are beginning to get impatient. The [tracker page for igraph](https://tracker.debian.org/pkg/igraph) shows the details: all is fine, and dpkg should hopefully migrate soon as it is blocked only by lintian (another big piece of the Debian machinery). Note that I cannot backport the package igraph because it has to be in testing first; once in testing/trixie, I will backport it to stable/bookworm.
