### ISSUE TITLE
Unnecessary zero-init of attributes before calling igraph_copy()

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2399]
In the implementation of `igraph_induced_subgraph()`, there are two instances of:

```
    /* must set res->attr to 0 before calling igraph_copy */
    res->attr = 0;         /* Why is this needed? TODO */
    IGRAPH_CHECK(igraph_copy(res, graph));
```

This seems to suggest that `igraph_copy()` cannot be called unless the `igraph_t` it is writing to has some fields set. If this is true, `igraph_copy()` needs fixing, otherwise the unnecessary zero-initialization should be removed.

CC @ntamas in case you remember what this is about.

**Comment by szhorvat** [comment]
I don't see any reason for those lines, but since the attribute handler is called, it'd be good to check that there's nothing from the py-igraph attribute handler either, @ntamas

**Comment by ntamas** [comment]
All seems good there, all unit tests pass. Thanks a lot!
