### ISSUE TITLE
Pajek parser is likely broken

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2400]
**Describe the bug**

The Pajek parser contains code that tries to control tokenization (i.e. the Flex part) by setting certain flags from Bison actions. This is likely broken, as Bison may read one token ahead in some situations. Thus this token is already parsed by Flex code before the Bison action had a chance to set the flag.

The flag is the `mode` field of the `context` object.

For example, the Flex code contains a line like this:

```flex
ic      { if (yyextra->mode==1) { return VP_IC; } else { return ALNUM; } }
```

`mode=1` is meant to indicate that we are looking for keywords indicating vertex properties. The keyword `ic` indicates that the next word(s) specify a vertex colour. `ic` should translate to the `VP_IC` token, but if the next word also happens to be `ic`, it should now translate to the generic `ALNUM` token instead, as it is a colour name.

This is attempted with the following Bison rule:

```bison
vpword:
     /* ... */
     | VP_IC { context->mode=3; } vpwordpar {
         context->mode=1;
         IGRAPH_YY_CHECK(igraph_i_pajek_add_string_vertex_attribute("color", $3.str, $3.len, context));
     }
```

Thus as soon as the parser sees a `VP_IC` token, it sets `mode=3`, indicating that the next word should be treated as an `ALNUM` (colour name). Once the colour name is read, we switch back to `mode=1` to look for keywords again.

The problem is that by the time Bison executes this code, it may have already have requested the next token from Flex (see [lookahead tokens](https://www.gnu.org/software/bison/manual/html_node/Lookahead.html)). Thus Flex read the next token before `mode` was changed. The `mode` flag is not serving its purpose.

**To reproduce**

To test whether Bison does indeed look ahead, I used `IGRAPH_ASSERT(yychar == YYEMPTY)` after setting `mode`. Yes, it does look ahead in some situations. (See [Bison docs](https://www.gnu.org/software/bison/manual/html_node/Action-Features.html).)

Alternatively, take `tests/unit/pajek5.net`, and change `ic Green` to `ic ic`. This causes an error with the test `test::pajek`:

```
Error at src/io/pajek.c:213 : Parse error in Pajek file, line 2 (syntax error, unexpected VP_IC, expecting number or ALNUM or QSTR) - Parse error.
```

Switching the mode was meant to prevent parsing as `VP_IC`, but it didn't work, as the switch couldn't happen in time.

**Practical consequences**

Unclear. Is `ic` even a valid colour name in Pajek? Unclear, as the format is not properly documented.

**Possible fixes**

I do not know if any reasonable fix is possible at all with Bison/Flex.

A proper fix would isolate setting the "mode" to Flex code only. In fact Flex has a feature for setting states, called [start conditions](https://westes.github.io/flex/manual/Start-Conditions.html#Start-Conditions), which could be used for this.

But to do so, we'd need the kind of information that Bison works with. For example, `ic` may be followed either by a single colour (`Blue`) or by three numbers (`0 0 1`, interpreted as RGB). Deciding this is Bison's job, and this kind of ambiguity is precisely why Bison needs to look ahead. Reimplementing this in Flex is not realistically feasible.

It seems to me that Pajek files just can't be parsed reliably with Flex/Bison.

**Version information**

Problem present in all versions up to today.

**Comment by ntamas** [comment]
#2401 is merged so closing; there's not much we can do about it in the short-term, and re-writing the parser without flex/bison seems to be out of scope for us now.
