### ISSUE TITLE
libglpk.so.40 error on HPC for high core counts

### ISSUE THREAD

**Issue by wrmartin** [igraph/igraph#2402]
I'm having an odd issue. I'm running my script on an HPC. Things work just fine with lower cpu core allocations (12 or fewer). However, when I allocate more, or a whole node, the "libglpk.so.40: cannot open shared object file: No such file or directory" error crops up. Is there any rationale for this occurring, and is there a solution? libglpk.so.40 is present in /lib64/ and is in my LD_LIBRARY_PATH.

**Comment by szhorvat** [comment]
We would like to reserve the issue tracker for bug reports, feature requests, and coordinating development. Please post support questions on the forum, https://igraph.discourse.group/

Chances are that some nodes in the cluster don't have GLPK installed, and which node your code runs on depends on how many CPUs you request.
