### ISSUE TITLE
functions.yaml has duplicate functions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2418]
In `functions.yaml`, these functions are duplicated, with differing descriptions:

 - [ ] `igraph_st_mincut`
 - [ ] `igraph_stochastic_imitation`

Can you have a look, @ntamas ?

**Comment by ntamas** [comment]
This should have been caught by the YAML parser, but apparently it [has a bug](https://github.com/yaml/pyyaml/issues/165), and it's [hard to fix without breaking other things](https://github.com/yaml/pyyaml/issues/165#issuecomment-525047100).

I'll fix this under the assumption that the current behaviour always overwrites earlier values with the later ones (which is the current PyYAML behaviour).

**Comment by ntamas** [comment]
Fixed in b853f65c2; ported to `develop` in 4a1425d34.
