### ISSUE TITLE
get_subisomorphisms_lad gives the wrong output if input graph has no vertices

### ISSUE THREAD

**Issue by dcartermath** [igraph/igraph#2429]
**Describe the bug**
If the `other` input to `get_subisomorphisms_lad` has no vertices, it returns `[]` instead of the correct `[[]]` (which indicates that there is one mapping from `other`'s vertices to `self`, namely the empty map). `get_subisomorphisms_vf2` does not have this issue.

**To reproduce**
See the following code example:
```
import igraph as ig
G = ig.Graph(1)
H = ig.Graph()
print(G.get_subisomorphisms_lad(H)) # []. This is incorrect, as it would imply that H is not a subgraph of G.
print(G.get_subisomorphisms_vf2(H)) # [[]]. This is the correct output.
```

**Version information**
0.11.2

**Comment by szhorvat** [comment]
It seems I actually worked around this case in the Mathematica interface a long time ago. I agree that this should be fixed in the C core.

**Comment by szhorvat** [comment]
The fix will be in a release coming later this week.
