### ISSUE TITLE
Add dispersion calculation between pairs of nodes in graphs

### ISSUE THREAD

**Issue by henryxu1997** [igraph/igraph#2430]
I propose adding a feature to the igraph library to calculate the dispersion between pairs of nodes, as described in the study by Lars Backstrom and Jon Kleinberg: "Romantic Partnerships and the Dispersion of Social Ties: A Network Analysis of Relationship Status on Facebook" ([arXiv Link](https://arxiv.org/pdf/1310.6753v1.pdf)). This feature would greatly enhance the library's capabilities for social network analysis.

I would like to take this on and implement it.

**Comment by szhorvat** [comment]
Before we continue, can you edit the top post and add the following information?

 - Give a concise but precise definition of "dispersion"
 - What is its interpretation and use?
 - Who uses it, what other packages implement it? Information to help judge its popularity.

Basically, can you help us save the time to read the paper in full?

**Comment by szhorvat** [comment]
@henryxu1997 Are you still interesting in completing this work?

**Comment by szhorvat** [comment]
> I am still interested in completing this work.

Great!

> Is there a deadline for adding these information?

No, there is no deadline. Take as much time as you need. I just wanted to know if you are interested.




> This is my first time with open-source contribution so I am still learning how things work

No worries. What you have is a very good start.  There's quite a bit more work to be done to finish it, but we can guide you on the way.  For now, do not spend time programming. Let us understand _what_ we want to implement, and when that is clear, we can start programming, and extending the PR you already submitted.

**Comment by henryxu1997** [comment]
Hi @szhorvat Thank you so much for your guidance! I will get back to you to make sure _what_ we want to implement is clear. I will let you know when that is ready. Have a great day!
