### ISSUE TITLE
`igraph_community_spinglass_single()` uses integer types for weight-sum variables

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2435]
**Describe the bug**

In `igraph_community_spinglass_single()`, the output parameters `inner_links` and `outer_links` should be of real type. According to the documentation, they will store the number of links within the community / leaving the community. But it seems to me that what the underlying implementation computes is really a sum of edge weights.

This function calls `FindCommunityFromStart`:

https://github.com/igraph/igraph/blob/16c36d036aeb818e9d20a2b5464f8d393b6d3cc2/src/community/spinglass/pottsmodel_2.cpp#L901-L918

That function has `double inner_links = 0, outer_links = 0`

These accumulate weights, e.g. 

https://github.com/igraph/igraph/blob/16c36d036aeb818e9d20a2b5464f8d393b6d3cc2/src/community/spinglass/pottsmodel_2.cpp#L1046

https://github.com/igraph/igraph/blob/16c36d036aeb818e9d20a2b5464f8d393b6d3cc2/src/community/spinglass/pottsmodel_2.cpp#L1038

**To reproduce**

—

**Version information**

The issue is present in both 0.9 and 0.10

**Comment by szhorvat** [comment]
@ntamas Any suggestion about what to do here? Changing the signature is breaking.

**Comment by ntamas** [comment]
Change the type for 0.11 and keep it as is for 0.10. If we've been running for this long with this issue present and no one complained, it probably means that it's not a big deal.
