### ISSUE TITLE
Crash When Using Invalid Vertex IDs with Similarity Functions

### ISSUE THREAD

**Issue by iany0** [igraph/igraph#2438]
Hello,
**Describe the bug**  
A kernel crash occurs when the `similarity_jaccard` or `similarity_dice` functions are called on a graph using pairs that include an invalid vertex ID. The expected behavior is to raise an `InternalError` due to the invalid vertex ID, but instead, the kernel crashes.

**To Reproduce**  
Steps to reproduce the behavior for `similarity_jaccard`:
```python
g = ig.Graph(
    6,
    [(0, 1), (0, 2), (1, 3), (2, 3), (2, 4), (3, 5), (4, 5), (6, 6)]
)
results = g.similarity_jaccard(pairs=[(0, 1), (1, 7)])
results
```

To reproduce the behavior for `similarity_dice`:
```python
g = ig.Graph(
    6,
    [(0, 1), (0, 2), (1, 3), (2, 3), (2, 4), (3, 5), (4, 5), (6, 6)]
)
results = g.similarity_dice(pairs=[(0, 1), (1, 7)])
results
```

**Expected Behavior**  
It would be more appropriate if, instead of resulting in a kernel crash, the function could raise an `InternalError`, thereby indicating the presence of an invalid vertex ID.

**Version Information**  
`python-igraph` version: 0.11.2

**Comment by szhorvat** [comment]
Thanks for the report!
