### ISSUE TITLE
How to find a longest cycle and a longest induced cycle in a graph?

### ISSUE THREAD

**Issue by lichengzhang1** [igraph/igraph#2456]
Do we have a function to find a longest cycle for a given graph? And an induced cycle is a cycle that is an induced subgraph of G; induced cycles are also called chordless cycles. Then do we have a function to find the longest induced cycle?

- https://en.wikipedia.org/wiki/Induced_path

**Comment by ntamas** [comment]
Please send support questions to https://igraph.discourse.group ; the issue tracker is reserved for bugs and feature requests.

As for the original question, I don't think there's a function for that. If your graph is not too large, you can try with subisomorphism, i.e. construct a cycle of length _k_, and check whether it is subisomoprhic to the entire graph. If it is, you have a cycle of length _k_. Start from _k_ = |V| and then decrease k by one for every failed search until you find the longest cycle. Note that this will only find cycles that contain each vertex only once.
