### ISSUE TITLE
Segfault in `cluster_fast_greedy()` when `merges = FALSE` and `membership = FALSE`

### ISSUE THREAD

**Issue by etiennebacher** [igraph/igraph#2459]
### What happens?

Hello, I don't know much about `igraph` (and about graphs in general), so the example below might be something completely nonsensical to do, but it shouldn't segfault.

``` r
packageVersion("igraph")
#> [1] '1.6.0.9023'
```

### To Reproduce

```r
reprex::reprex({
  library(igraph, warn.conflicts = FALSE)
  g <- make_full_graph(2) %du% make_full_graph(2)
  cluster_fast_greedy(g, merges = FALSE, membership = FALSE)
}, std_out_err = TRUE)
```
````
This reprex appears to crash R.
See standard output and standard error for more details.

#### Standard output and error

``` sh
-- nothing to show --
```
````

**Comment by szhorvat** [comment]
@krlmlr I'll look into fixing this next week (unless someone else gets to it first). I think you do not need to block the R/igraph 2.0.0 release on this, as it is a rare use case to only want modularity but not membership, and avoiding membership calculation doesn't have any advantages.

**Comment by Antonov548** [comment]
> @Antonov548 Would you be able to get an ASan stack trace on this?

Sorry, do you still need the ASan stack trace or think you found root cause?

**Comment by szhorvat** [comment]
No need

**Comment by ntamas** [comment]
Added a test for the C core in `master` in a7a60d49b but it works correctly there, so if this was ever a bug in the C core, then it has already been fixed.

**Comment by szhorvat** [comment]
I think it needs a disconnected graph to trigger.

**Comment by szhorvat** [comment]
This is fixed now. Can you please upgrade the C core in R/igraph, @Antonov548 @krlmlr ?

**Comment by szhorvat** [comment]
@etiennebacher I am curious how you found this bug. Was it a real use case or just an accident?

It is possible that other similar bugs exist, i.e. that things may go wrong when restricting the result to only some parts, especially parts which are "pointless" in some sense to compute in isolation. If you find any others, let us know.

**Comment by etiennebacher** [comment]
It was completely by accident. I used the package [`zoomerjoin`](https://github.com/beniaminogreen/zoomerjoin) for fuzzy matching of names, and one of the functions calls the old version of `cluster_fast_greedy()`:

https://github.com/beniaminogreen/zoomerjoin/blob/5577e0ecc71ec92ad0e8fa06483b54c899bac306/R/string_group.R#L68

I tried a few things to make the code faster and I saw that quite some time is spent on `cluster_fast_greedy()`, so I simply tried to apply some parameters to see if that changed anything (didn't really think so but I was just trying stuff). That's how this segfault occurred.

**Comment by szhorvat** [comment]
Thanks for the explanation! Yes, it is a reasonable assumption that if fewer results are requested, the calculation should be faster. This is often the case, but not with this specific function.

**Comment by krlmlr** [comment]
Can patrick write "simple and stupid" testthat code into a file? I've gone the route of meta-testing once with DBItest, not going there again.

https://mtlynch.io/good-developers-bad-tests/

**Comment by etiennebacher** [comment]
> Can patrick write "simple and stupid" testthat code into a file?

I don't think so, but I'm no expert on this package. I rarely use parameterized tests, I find them hard to read. But checking at least once that a certain parameter combination doesn't segfault sounds to me like a good thing to have, and testing all combinations is simply easier to do with parameterized tests.  

Here's an example in a package I contribute to, to check that a list of functions produce the same output as base R functions: https://github.com/pola-rs/r-polars/blob/3545ee2a8caba75fb01c0c6bb48c5ddb2f6dda13/tests/testthat/test-dataframe.R#L487-L511
