### ISSUE TITLE
Wishlist: Biconnectedness test

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2469]
**What is the feature or improvement you would like to see?**

A function to check if a graph is biconnected (i.e. 2-vertex-connected): `igraph_is_biconnected()`.

**Use cases for the feature**

Performance: While this is already possible using `igraph_biconnected_components()`, and checking the number of components, a specialized function that only verifies biconnectedness, without finding the components, can be considerably faster.

**Optimization opportunities**

 - Use the cache:
    * If the graph is not connected, it is not biconnected
    * If the graph is acyclic, it is not biconnected
 - As soon as an articulation point is found, the function can return with a negative answer

**References**
—

**Comment by ntamas** [comment]
Note that currently we define biconnectedness only for undirected graphs. (Internally, `igraph_biconnected_components()` traverses the graph using an incidence list constructed with `IGRAPH_ALL`, therefore directed graphs are treated as undirected). This means that this is not true:

> If the graph is acyclic, it is not biconnected

Consider `a -> b -> c, a -> d -> c`. This is acyclic, but if you ignore the edge directions then it is biconnected.

On the other hand, we can say that is a graph is a forest, then it is not biconnected.

I've started a PR in #2470 - let's continue the discussion there.

**Comment by szhorvat** [comment]
Oh wow, I didn't expect you'd do this so quickly.
