### ISSUE TITLE
layout_with_sugiyama() rounds numeric values of layers argument in new version

### ISSUE THREAD

**Issue by madelhorius** [igraph/igraph#2480]
### What happens?

In version 2.0.0.1, `layout_with_sugiyama()` rounds non-integer values in the `layer` argument. In the given example, the second column of the output matrix `lay` contains only integers (`lay[c(5, 6), 2] == c(2, 3)`), while in version 1.5.1 the layers remain as given to the function (`lay[c(5, 6), 2] == c(1.5, 2.5)` ).

### To Reproduce

``` r
ped_node <- data.frame(
  stringsAsFactors = FALSE,
  id = c("Delicious","McIntosh",
         "Spartan","Winesap","cross 1","cross 2"),
  gen = c(2, 2, 3, 1, 2.5, 1.5)
)

ped_edge <- data.frame(
  stringsAsFactors = FALSE,
  from = c("McIntosh", "Winesap", "Delicious", "cross 1", "cross 2"),
  to = c("cross 1", "cross 2", "cross 1", "Spartan", "Delicious"),
  sex = c("female", "female", "male", NA, NA)
)

# Create igraph object (only used to calculate layout_matrix)
g <- igraph::graph_from_data_frame(ped_edge, vertices = ped_node)

# Calculate layout matrix (minimize the number of edge_crossings)
lay <- igraph::layout_with_sugiyama(g,  maxiter = 1000, layers = ped_node$gen,
                                    attributes = "all", hgap = 20)$layout

print(lay)
#>      [,1] [,2]
#> [1,]   20    2
#> [2,]   60    2
#> [3,]   40    1
#> [4,]    0    3
#> [5,]   40    2
#> [6,]   20    3
```

<sup>Created on 2024-02-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by madelhorius** [comment]
Thanks for your answer! I am ploting pedigrees using the calculated layout matrix. 

Thanks to your explanation about `layers` I realized that I could just `ped_node$gen * 2` which makes my argument integer and works in older and newer versions of igaph.

An error or at least a warning when layer values are non-integer would be really appreciated, as simply rounding non-integer values is a strange behaviour.

**Comment by szhorvat** [comment]
> An error or at least a warning when layer values are non-integer would be really appreciated

Yes, this planned for the near future, it's just that there are a lot of functions to update for the new version of C/igraph, and we didn't get to all of them yet.

**Comment by szhorvat** [comment]
Closing, as there are no plans to support non-integer values. Feel free to open a feature request if you need non-integer layer values.

The issue with no warning being given when fractional values are provided is specific to the R interface and will be fixed there eventually when this function is moved to full auto-generation (CC @krlmlr)
