### ISSUE TITLE
Infinite loop leading to out of memory error while finding isomorphisms

### ISSUE THREAD

**Issue by wojnicki** [igraph/igraph#2485]
**Describe the bug**

I want to find all isomorphisms in a graph. For some graphs `get_isomorphisms_vf2()` function consumes all available memory after a while which leads to a crash.  

**To reproduce**
A minimal example with automorphism that leads to a out-of-memory is given below. It's in Python however the python API uses underlying library functions directly, as far as I can tell, that's why I'm reporting it here. I'm also attaching the gzipped edgelist file: 
[isomorph_graph_error_g1.edgelist.gz](https://github.com/igraph/igraph/files/14229369/isomorph_graph_error_g1.edgelist.gz)

``` python
import igraph as ig
g1 = ig.read('isomorph_graph_error_g1.edgelist')
g1.get_isomorphisms_vf2(g1) # this leaks memory and crashes
```

**Version information**
Python igraph version: 0.11.3

**Comment by szhorvat** [comment]
You used a multigraph, which is not supported, but also not checked for, as stated in the documentation:

https://igraph.org/c/html/latest/igraph-Isomorphism.html#vf2-algorithm

> Self-loops or multi-edges must not be present in the graphs. Currently, the VF2 functions do not check that the input graph is simple: it is the responsibility of the user to pass in valid input. 

I know that this is not ideal. Checking if the graph is simple would bring a non-negligible overhead, and no one so far had to the time to go through the implementation and update it for non-simple graphs.

**Comment by szhorvat** [comment]
@ntamas The Python interface documentation should have a note that multigraphs are not supported. Alternatively, it should have a multigraph check, if that's the tradeoff you prefer.

**Comment by wojnicki** [comment]
Thanks @szhorvat for your reply.  However, I think that the graph I attached is a simple directed graph,  with no loops or multiple edges which is confirmed by:
``` python
True in g1.is_loop(), True in g1.is_multiple()
```
``` python
(False, False)
```

**Comment by szhorvat** [comment]
I'm sorry, you are correct. This is a simple graph. I assumed that `ig.read()` would import it as undirected without actually checking.

Can you give more details about the issue? What do you mean by "crash"? What message do you see?

It is not surprising that this runs out of memory as this graph has a very large number of automorphisms. You can check this with `g1.count_automorphisms()`, which uses Bliss to perform the count efficiently. The result is 479 001 600. Ideally it shouldn't crash though. igraph should always check for OOM errors, but it's good to note that on some systems `malloc()` doesn't always indicate failure even if there's no enough memory ... then a crash happens when the memory is accessed.

**Comment by ntamas** [comment]
> The Python interface documentation should have a note that multigraphs are not supported

This is a thing that I'm constantly struggling with. Documenting all the restrictions in the Python interface is redundant, and even worse, if we ever decide to update the C implementation to start supporting multigraphs and then we forget to update the documentations of the higher level interfaces, then they would be claiming a restriction that does not exist any more. I think that the ideal solution would be to do the check in C and not mention the restrictions in the documentation of the higher level interface.

**Comment by szhorvat** [comment]
@ntamas I looked at how NetworkX supports multigraphs with its VF2 implementation.

https://github.com/networkx/networkx/blob/74ce63f222df0189c1c9ae425b5b7748111d17f9/networkx/algorithms/isomorphism/isomorphvf2.py#L409

My impression is that they basically do the same that we already recommend using `igraph_simplify_and_colorize()`, i.e. only match vertices with the same number of self-loops, and pairs with the same number of edges between them.

Maybe it's time to just add that multigraph check in the C core, as you say, and stop worrying about performance. It should be possible to detect both multi-edges and self-loops during graph construction in `add_edges()` and cache them, which would solve the performance worries once and for all.

I'm also working at a better and safer system to deduce more cachable properties whenever the cache is set,

**Comment by wojnicki** [comment]
Thanks,
You are right, I just wasn't aware, and didn't check, that there could be so many of them.

I reimplemented my code with `isomorphic_vf2()` with a callback, since I need to check if the isomorphisms comply with certain assumptions and I do not need to store them. Checking one at a time works fine. 

> It is not surprising that this runs out of memory as this graph has a very large number of automorphisms. You can check this with `g1.count_automorphisms()`, which uses Bliss to perform the count efficiently. The result is 479 001 600. Ideally it shouldn't crash though. igraph should always check for OOM errors, but it's good to note that on some systems `malloc()` doesn't always indicate failure even if there's no enough memory ... then a crash happens when the memory is accessed.
