### ISSUE TITLE
`igraph_disjoint_union()` should provide edge mapping information

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2493]
**What is the feature or improvement you would like to see?**

`igraph_disjoint_union()` should make it possible to obtain a mapping between the edge IDs of the input graphs and the output graph.

At this moment:

 - `eid` from graph 1 becomes `eid` in the result
 - `eid` from graph 2 becomes `eid + ecount(graph1)` in the result

It would be most convenient to document this, test it (by comparing edge attributes after #2490 is completed), and keep to it in the future.

**Use cases for the feature**

Preserving edge identities between the source and result graphs can be useful.

**References**
—

**Comment by szhorvat** [comment]
@ntamas @vtraag I expect doing this for vertex IDs is not controversial, so I did not open an issue. Any objections about doing it for edge IDs? For as long as igraph uses the concept of edge indices (i.e. graphs have an edge ordering) this should be feasible to implement. I don't think it will be a burden if we commit to maintaining the current behaviour in the future.

**Comment by vtraag** [comment]
Sounds reasonable, and useful indeed. Combining graphs with attributes would be rather challenging  without it also, wouldn't it?

**Comment by ntamas** [comment]
>  I don't think it will be a burden if we commit to maintaining the current behaviour in the future.

Yeah let's do that.

**Comment by szhorvat** [comment]
Docs have already been updated, but it'd be good to add a test, so leaving this open.
