### ISSUE TITLE
Wishlist: Graph join

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2494]
**What is the feature or improvement you would like to see?**

The _join_ of two graphs $G_1$ and $G_2$ is constructed by taking their disjoint union, then connecting all $V(G_1)$ vertices to all $V(G_2)$ vertices. 

**Use cases for the feature**
Useful for constructing certain graphs in graph theory.

**References**

 - https://mathworld.wolfram.com/GraphJoin.html
 - https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph.html#sage.graphs.graph.Graph.join
 - https://reference.wolfram.com/language/ref/GraphJoin.html

**Comment by GanzuraTheConsumer** [comment]
Hi, I have an interest in working on this feature. To clarify, what should be the expected behaviour with a directed graph?

**Comment by GanzuraTheConsumer** [comment]
Pull request opened [here](https://github.com/igraph/igraph/pull/2508).

**Comment by GanzuraTheConsumer** [comment]
PR marked as ready for review.
