### ISSUE TITLE
`write_graph_graphml()` is willing to write files that `read_graph_graphml()` cannot read back

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2503]
**Describe the bug**

`write_graph_graphml()` is willing to write files that `read_graph_graphml()` cannot read back.

This typically happens because of encoding issues. For example, take the following GML file, where the quoted character is non-ASCII and not valid UTF-8, for example character code 0xFF.

```
graph [e"�"]
```

[minimized-from-21e2a797ece6ecd938a9f4712c6c597201424753.gz](https://github.com/igraph/igraph/files/14320537/minimized-from-21e2a797ece6ecd938a9f4712c6c597201424753.gz)

Read this file, write the result to GraphML, then try to read it back. The error will be:

> Error at src/io/graphml.c:1687 : Line 9: Input is not proper UTF-8, indicate encoding !

**To reproduce**

Something like this:

```c
    if (igraph_read_graph_gml(&g, ifile) == IGRAPH_SUCCESS) {
        FILE *file;
        igraph_t g2;

        file = tmpfile();
        if (igraph_write_graph_graphml(&g, file, false) == IGRAPH_SUCCESS) {
            rewind(file);
            CHECK_ERR(igraph_read_graph_graphml(&g2, file, 0));
            igraph_destroy(&g2);
        }
        fclose(file);

        // Clean up
        igraph_destroy(&g);
    }
```

**Version information**
current `master`

**Comment by szhorvat** [comment]
I found this while trying to construct a fuzz target that reads a file, writes it in all formats, then reads all of these back.

@ntamas I'm guessing there's not much we can do about this, right? igraph does not know anything about encodings, so it cannot use the proper encoding when writing XML files.

**Comment by ntamas** [comment]
Yes. I'd say it's a wontfix. We _assume_ that the strings are UTF-8 and add that encoding in the output file. You can extend the docs to claim that attribute values have to be in UTF-8 encoding if you want to, and the results are undefined if they aren't.
