### ISSUE TITLE
`igraph_all_minimal_st_separators()` sometimes returns empty separators

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2517]
**Describe the bug**

`igraph_all_minimal_st_separators()` sometimes returns empty separators.

This isn't fixed by #2509.

**To reproduce**

This is correct:

```
> min_st_separators(make_graph(c(1,2), directed = F))
list()
```

But if we add an isolated vertex, it returns an (invalid) empty separator.

```
> min_st_separators(make_graph(c(1,2), n=3, directed = F))
[[1]]
+ 0/3 vertices, from 008ce82:
```

**Version information**
Current `master`

**Comment by ntamas** [comment]
b3e7184 fixes this but I think it's only a band-aid that prevents empty separators from appearing in the result. The underlying algorithm does not have a clear notion about how a separator is defined in a graph that is already disconnected, so if you throw disconnected graphs at it, it will return separators that are not consistent with how you are re-writing the separator function right now.
