### ISSUE TITLE
Should loop edges be considered self-adjacenct for the purpose of line-graph computation?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2524]
**Describe the bug**

When computing a line graph, directed loop edges seem to be considered self-adjacent, but undirected ones aren't. This seems inconsistent to me. Should this be changed?

**To reproduce**

In R,

```
> make_line_graph(make_graph(c(1,1), directed=T))
IGRAPH abae052 D--- 1 1 -- Line graph
+ attr: name (g/c)
+ edge from abae052:
[1] 1->1
> make_line_graph(make_graph(c(1,1), directed=F))
IGRAPH 478ec04 U--- 1 0 -- Line graph
+ attr: name (g/c)
+ edges from 478ec04:
```

According to igraph, the line graph of a singleton with a loop is:

 - A singleton with a loop if the graph was directed
 - A singleton with no edges if the graph was undirecred

**Version information**
Current `master`.

**Comment by szhorvat** [comment]
It would make sense to say that if edges $a$ and $b$ meet in $k$ vertices in $G$, then there will be $k$ connections between them in $L(G)$.

**Comment by szhorvat** [comment]
I can't think of any situation where the question of self-loops becomes interesting for line graphs.

**Comment by szhorvat** [comment]
In case you are wondering if an undirected self-loop should be self-adjacent once or twice, the answer is only once.

This is based on the principle of equivalence between undirected graphs and directed graphs with reciprocal edges.

Consider a single non-loop edge `a-b`. It is not self-adjacent. The directed equivalent is `a->b, b->a`. These two directed edges are adjacent, but by convention that does not make the undirected `a-b` self-adjacent. We obtain the undirected version of the line graph by contracting the directed reciprocal pair.

Now consider `a-a`. The directed versions is `a->a, a->a`. Let's call these two directed edges `1` and `2`. The line graph is then `1->1, 1->2, 2->1, 2->2`. To obtain the undirected version, we contract `1` and `2`. The loops induced by `1->2, 2->1` are discarded, as in the first example. What remains is the _two_ directed loops `1->1` and `2->2`. However, these two directed loops are equivalent to a _single_ undirected loop per the principle of equivalence.

**Comment by ntamas** [comment]
I'd argue that the behaviour with undirected graphs is buggy right now and we can change it easily to make it consistent with the directed case.

**Comment by szhorvat** [comment]
PR is in #2525
