### ISSUE TITLE
`igraph_all_st_mincuts` does not return only minimum cuts

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#2532]
**Describe the bug**
`igraph_all_st_mincuts` returns non-minimum cuts.

**To reproduce**

```C
igraph_t graph;

// create a graph
igraph_small(&graph, 20, IGRAPH_DIRECTED,
    1, 11,
    3, 13,
    4, 14,
    5, 15,
    6, 16,
    7, 17,
    8, 18,
    9, 19,
    0, 8,
    18, 0,
    0, 9,
    19, 0,
    2, 1,
    11, 2,
    14, 1,
    11, 4,
    2, 4,
    14, 2,
    2, 5,
    15, 2,
    14, 3,
    13, 4,
    18, 3,
    13, 8,
    16, 5,
    15, 6,
    17, 5,
    15, 7,
    19, 6,
    16, 9,
    18, 7,
    17, 8,
    -1
);

igraph_vector_int_list_t stcuts;

igraph_vector_int_list_init(&stcuts, 0);

igraph_all_st_mincuts(&graph, /*value=*/ NULL,
                        /*cuts=*/ &stcuts,
                        /*partition1s=*/ NULL,
                        /*source=*/ 2,
                        /*target=*/ 0,
                        /*capacity=*/ NULL);


// print out the vector
printf("st-cuts:\n");
for (int i = 0; i < igraph_vector_int_list_size(&stcuts); i++)
{
    igraph_vector_int_t* cut = igraph_vector_int_list_get_ptr(&stcuts, i);
    printf("total cut capacity (%ld): ", igraph_vector_int_size(cut));
    igraph_vector_int_print(cut);
}
printf("\n");

igraph_vector_int_list_destroy(&stcuts);
igraph_destroy(&graph);
```

In particular, this produces a number of cuts of 3 edges, while other cuts have 2 edges. Since all cuts have to be a minimal size, this obviously should not be possible.

**Version information**

Latest `develop`, 9695ba1659217da1c3ebc1d47642ae6666329cb6.

**Comment by vtraag** [comment]
There might be smaller graphs that produce this problem.

**Comment by szhorvat** [comment]
<img width="888" alt="image" src="https://github.com/igraph/igraph/assets/1212871/9b9cdc5c-7337-4a22-9562-e910a5052809">

Try this edge list, 6 vertices:

```
0, 1, 2, 0, 3, 0, 4, 0, 0, 5, 3, 1, 1, 4, 3, 2, 2, 5, 4, 3, 5, 3, 5, 4
```

I didn't have time to test much. Does the result depend on the edge / vertex ordering?

**Comment by szhorvat** [comment]
Smaller:

<img width="540" alt="image" src="https://github.com/igraph/igraph/assets/1212871/ff781875-cac0-43bc-af39-5e4ef8716dba">

```
0, 1, 0, 5, 1, 3, 4, 1, 2, 3, 5, 2, 3, 4, 5, 4
```

**Comment by szhorvat** [comment]
```
0, 2, 3, 0, 1, 2, 5, 1, 2, 4, 3, 5, 5, 4
```

`s=3, t=4`

**Comment by szhorvat** [comment]
The fuzzer on OSS-fuzz is not going to be good at identifying these IMO. I did this with Mma. I can't get it to smaller sizes, but that doesn't mean it's not possible. I only checked graphs without reciprocal edges (the random ones I generated with reciprocal edges didn't have the problem).

**Comment by vtraag** [comment]
Great work @szhorvat! That DAG should be enough to start digging.

**Comment by vtraag** [comment]
I believe there is a mistake in https://github.com/igraph/igraph/blob/9695ba1659217da1c3ebc1d47642ae6666329cb6/src/flow/st-cuts.c#L1291
This should be `if (!igraph_marked_queue_int_iselement(S, u)) {` instead. 

That is, in Provan & Shier (1996), Eq. 3.8b, $I(X, v)$ is defined as

$$I(X, v) = \\{u \in \bar{X} \mid u[\bar{X}]^*v\\}$$

where $\bar{X} = V - X$, with $V$ all nodes of the graph (in this case, the directed acyclic condensation of the residual graph). In more plain English, $I(S, v)$ should include all the nodes $u$ that can reach $v \not\in S$ through nodes not in $S$. @szhorvat , what do you think?

When correcting this (see https://github.com/vtraag/igraph/tree/vtraag/issue2532), we do indeed only get correct minimal cuts. However, they are listed multiple times, which I believe should not be the case. So, either this fix is not correct, or there are some other remaining problems still.
