### ISSUE TITLE
igraph_minimum_size_separators() produces vertex id's that are not in the graph

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2539]
**Describe the bug**
igraph_minimum_size_separators() sometimes produces vertices that are not in the graph.

**To reproduce**
Use this graph:
```
directed: false
vcount: 15
edges: {
8 7
6 2
12 2
14 0
5 2
9 3
10 4
13 5
10 7
11 6
11 8
11 4
9 4
12 1
13 6
13 12
1 0
14 3
}
```

This produces these vertex id lists, which includes '19', which is not in the graph.

```
1 14
3 19
1 9 14
3 9 19
1 4 14
4 19
1 4 11 14
1 11 12 14
4 11 19
11 12
1 6 12 14
6 12
0 12
9 14
4 14
9 11 14
0 9 11
4 11 14
0 11
0 6 9
0 6
9 11
3 11
6 9
3 6
8 10
4 8
10 11
4 11
4 6
7 11
3 4
4 7
0 3
2 13
```

**Version information**
commit 2b22f1eae60dc13ce0adb8a13f0921bd200a7c61
This bug seems to have been produced in d3bc59f9efaaaa1aa17d622d4a4ff1bedd6b1bc9

**Comment by szhorvat** [comment]
Thank you so much @GroteGnoom, this is really helpful!

**Comment by szhorvat** [comment]
There are now three crashes on OSS-fuzz which seems a bit different:

 - https://oss-fuzz.com/testcase-detail/5978937870057472
 - https://oss-fuzz.com/testcase-detail/4912335690989568
 - https://oss-fuzz.com/testcase-detail/5213632730300416

I verified that even though these look a bit different, all three appeared with commit d3bc59f9efaaaa1aa17d622d4a4ff1bedd6b1bc9. They are probably different manifestations of the same bug.
