### ISSUE TITLE
Investigate if strongly connected components are returned in topological order

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2544]
Investigate if strongly connected components are indexed in topological order, and if so, document and guarantee this. If not, try to adjust the implementation so that the topological order is guaranteed.

Specifically: If contracting SCCs to obtain the graph's condensation, and labelling each vertex in the condensation with the component index of the corresponding component, vertex labels should be in topological order.

**Comment by Tagl** [comment]
Yes, this is the case.
Iterating through components from $C-1$ to $0$ where $C$ is the number of components allows you to process the dependencies ($a \rightarrow b$ means $a$ depends on $b$) in a convenient way.
