### ISSUE TITLE
Move `igraph_diversity()` to centralities

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2551]
Move `igraph_diversity()` to the `centrality` directory, also updating headers.

This is for better organization, and to be able to find all centrality functions (which this effectively is) when browsing the code.

**Comment by ntamas** [comment]
Is it really a centrality measure? It is the normalized Shannon entropy of the weights of the incident edges - I'm not seeing immediately how this relates to centrality (but I haven't read the paper).

**Comment by szhorvat** [comment]
In my mind, I was thinking of all vertex-level measures as "centralities". But you are right: not all vertex-level measures indicate the importance or central position of vertices.

**Comment by ntamas** [comment]
In that case I guess it’s good to leave it where it is now.
