### ISSUE TITLE
Docs: Issues with stripping `IGRAPH_EXPORT` from declarations in the docs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2563]
When the doc system strips `IGRAPH_EXPORT`, it leaves in an extra space that should also have been stripped.

Example:

<img width="792" alt="image" src="https://github.com/igraph/igraph/assets/1212871/a21f5821-1e30-469c-8749-64428795c932">

https://igraph.org/c/html/latest/igraph-Error.html#igraph_set_fatal_handler

https://github.com/igraph/igraph/blob/13cd6cf8362709c4edb696ce434177a6b26de8dc/include/igraph_error.h#L1011

----

`IGRAPH_FUNCATTR...` macros should also be stripped along with `IGRAPH_EXPORT`. There are several of these, such as `IGRAPH_FUNCATTR_PRINTFLIKE`, `IGRAPH_FUNCATTR_PURE` and `IGRAPH_FUNCATTR_NORETURN` (the last one might not be bad to keep, but it's alright to strip it).

Here are some examples of non-stripped occurrences:

```
rg IGRAPH_FUNCATTR
doc/error.xml
628:IGRAPH_FUNCATTR_PRINTFLIKE(1,4)
955:IGRAPH_FUNCATTR_PRINTFLIKE(1,5)
1401: IGRAPH_FUNCATTR_NORETURN void igraph_fatal(const char *reason, const char *file, int line);
1432:IGRAPH_FUNCATTR_PRINTFLIKE(1,4)
1433:IGRAPH_EXPORT IGRAPH_FUNCATTR_NORETURN void igraph_fatalf(const char *reason, const char *file, int line, ...);

doc/html/igraph-Error.html
1018:IGRAPH_FUNCATTR_PRINTFLIKE(1,4)
1524:IGRAPH_FUNCATTR_PRINTFLIKE(1,5)
2170: IGRAPH_FUNCATTR_NORETURN void igraph_fatal(const char *reason, const char *file, int line);
2220:IGRAPH_FUNCATTR_PRINTFLIKE(1,4)
2221:IGRAPH_EXPORT IGRAPH_FUNCATTR_NORETURN void igraph_fatalf(const char *reason, const char *file, int line, ...);
```

https://igraph.org/c/html/latest/igraph-Error.html#igraph_errorf

----

Is it easy to deal with these @ntamas ?

**Comment by szhorvat** [comment]
One possible easy solution to the second issue is to move the documentation to the implementation file. I'm not even sure why it's in the header.

However, the `typedef` must remain in the header.

**Comment by ntamas** [comment]
Sorry, I'd rather not spend time on touching these. Extracting the function headers into the documentation is done with a horrible sequence of regexp-based replacements that are stored in `doc/c-docbook.re`. It is fragile and not sure what else I would break if I start messing around with these. If you feel like doing so, go ahead, but my feeling is that this would take a significant amount of time just to get rid of a space that no one is really concerned about in the docs.

**Comment by szhorvat** [comment]
Alright, let's leave the space alone. What about the other unstripped macros?

**Comment by szhorvat** [comment]
> Just move the comment blocks to the source files if that makes things easier.

That's where it really belongs, anyway.

**Comment by szhorvat** [comment]
The regex looks like `(IGRAPH_EXPORT )?`, so at first it seemed strange that it didn't take that space. I think the problem is not with the regex but with the segmentation of the `c-docbook.re` file. I suspect that space is being stripped out _before_ the regex is actually used. If so, this will affect more than regex in that file.

Simply replacing ` ` by `\s` fixes it ... So `(IGRAPH_EXPORT\s)?` works, and so does `(IGRAPH_EXPORT\s+)?`

**Comment by szhorvat** [comment]
@ntamas Can you please have a look at the changes I made (to make sure I didn't break anything), decide if you want to look into why that space was likely stripped _from the regex_, and finally close this issue if we don't want to do anything else?

**Comment by szhorvat** [comment]
@ntamas figured this out while we were on Zoom:

https://docs.python.org/3/library/re.html#re.VERBOSE

> Whitespace within the pattern is ignored, except when in a character class, or when preceded by an unescaped backslash, or within tokens like `*?`, `(?:` or `(?P<...>`.

We should write up the basics of who the doc system works in a wiki, as I won't be able to remember these details.

We should also review the regexes for more spaces and replace them with `\ ` or `\s` as appropriate.

**Comment by szhorvat** [comment]
Here's the start of a wiki page: https://github.com/igraph/igraph/wiki/The-documentation-system

I think nothing else is left to do here, closing.
