### ISSUE TITLE
High memory use and slow performance in GraphML reader

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2581]
OSS-Fuzz found a case of high memory use and slow performance in the GraphML reader. The affected fuzz target is `write_all_graphml`. The file contains a graph with just two vertices and an edge, yet it somehow seems to allocate over 3 GB of memory (which exceeds the set limit) and is very slow.

The time profiler indicates that most time is spent in `igraph_i_graphml_sax_handler_chars()`, more specifically in `igraph_i_graphml_append_to_data_char()`.

Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68131

**Comment by szhorvat** [comment]
This fuzz target reads a GraphML, writes it back as GraphML (as well as other formats) and reads it again. The issue occurs during the 2nd read.

Attached is an example of the original input ("1st") and the re-written one which actually causes the issue ("2nd"). The difference seems to be that the 2nd one contains a very large number of `&gt;` entities.

[test_cases.zip](https://github.com/igraph/igraph/files/15040778/test_cases.zip)

@ntamas Would you have time to investigate this a bit, and see if it's fixable without too much trouble? 

There's a large number of calls to `igraph_i_graphml_append_to_data_char()` with `len=1`, so it's tempting to just try to use a better allocation strategy (doubling the buffer size), but let's not do that before we're certain that's it's the true issue.

**Comment by ntamas** [comment]
We would effectively need a new igraph string data type. I guess that the parser passes each `%gt;` entity to `igraph_i_graphml_append_to_data_char()` one by one, leading to quadratic complexity. I'll take care of this.

**Comment by ntamas** [comment]
Pushed something that I think should fix the performance issues in 766e573ea but I don't have time to test it in the fuzzer now. If it works, we need to port this to `develop` as well.

**Comment by szhorvat** [comment]
No timeout with default settings, but runs out of memory.

Seems to be allocating about 3.4 GB to read `2nd.graphml`.  If increasing the memory limit, it finishes running in 10 seconds.

This is a big improvement over the previous performance. I'll investigate where the high memory usage comes from.

**Comment by szhorvat** [comment]
Most time is still spent in appending to this string (but as I said, much better than before).

<img width="749" alt="image" src="https://github.com/igraph/igraph/assets/1212871/d3af3a55-4ba4-4824-943e-1b600779cb68">

**Comment by szhorvat** [comment]
@ntamas It seems to me that `vector_append()` only allocates as much extra memory as strictly necessary (unlike `push_back` which doubles it).

A naive move to `push_back()` (without considering a potential size difference of `xmlChar` from `char`, which I don't think should happen anyway), brings the timing down from 10 s to 0.043 s.

The memory issue might not be real, perhaps it has to do with how the sanitizer works.

**Comment by szhorvat** [comment]
`xmlChar` is currently an `unsigned char`. The libxml docs are not very clear on this, but it seems they use an `unsigned char` as a "hack" to be able to distinguish between ASCII and UTF-8 (??)

https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xmlstring.html#xmlChar

Do we want to bother with checking `sizeof(xmlChar)` or shall we just put a static assertion to make sure it's the same as `sizeof(char)`?
