### ISSUE TITLE
fit_power_law does not return KS.p anymore

### ISSUE THREAD

**Issue by vvseva** [igraph/igraph#2582]
<s>**Describe the bug**
fit_power_law does not calculate the p-value of the Kolmogorov-Smirnov test anymore.  The function still runs KS test, but there is no way to access it

**To reproduce**
`g <- sample_pa(1000) # increase this number to have a better estimate
d <- degree(g, mode = "in")
fit1 <- fit_power_law(d + 1, 10)

fit1$KS.p # returns null
`

**Version information**
igraph_2.0.3 , but I believe that this issues appeared earlier
</s>

**Comment by vvseva** [comment]
OMG i was referring to the R implementation of the package.  I am so sorry please close the issue

**Comment by szhorvat** [comment]
This issue is tracked at https://github.com/igraph/rigraph/issues/1158. Please post a comment there and mention that you are affected too.
