### ISSUE TITLE
Clique percolation

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#261]
See http://code.google.com/p/igraph/issues/detail?id=61

Perhaps this is also relevant: http://arxiv.org/abs/0805.1449

---

Imported from Launchpad using lp2gh.
- date created: 2008-10-27T15:04:38Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/289890

**Comment by szhorvat** [comment]
@ntamas Do we want to close this and leave it as a good example of what can be implemented in a few lines in high-level interfaces? It's not a particularly popular method.
