### ISSUE TITLE
Rename `vector_qsort_ind()` to `vector_sort_ind()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2616]
We have a function named `igraph_vector_qsort_ind()`, see https://igraph.org/c/html/latest/igraph-Data-structures.html#igraph_vector_qsort_ind

The naming is inconsistent with [`igraph_vector_sort()`](https://igraph.org/c/html/latest/igraph-Data-structures.html#igraph_vector_sort) and implies a specific sorting algorithm. We discussed moving to timsort or [powersort](https://www.i-programmer.info/news/216-python/15954-python-now-uses-powersort.html).

Shall we rename this to `igraph_vector_sort_ind()`, @ntamas ?

**Comment by ntamas** [comment]
Yup, with the usual deprecation path (i.e. keep the original name as an alias).

**Comment by szhorvat** [comment]
Do we also split it into `igraph_vector_reverse_sort_ind()` and `igraph_vector_sort_ind()`, for consistency with `igraph_vector_reverse_sort()` and `igraph_vector_sort()`? Or do we keep the `igraph_order_t` parameter? I'd go with splitting for consistency, but not strong opinion from me.

**Comment by ntamas** [comment]
`igraph_order_t` was added in lieu of a boolean in 0.10.0. It's also used that way in `igraph_sort_vertex_ids_by_degree()`. If we really want to push this consistency thing to the extreme, then we should also split `igraph_sort_vertex_ids_by_degree()` into two functions, one for ascending and one for descending sort :) I'd rather not do that.

**Comment by szhorvat** [comment]
OK, then we neither split `vector_sort_ind` nor do we merge `vector_sort` + `vector_reverse_sort`.

We only rename `qsort` -> `sort`.

Are we on the same page?

**Comment by ntamas** [comment]
Yes, that's correct.
