### ISSUE TITLE
`adjlist_init()` mis-caches multi-edges when only multi-loops are present

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2626]
`igraph_adjlist_init()` incorrectly sets the `IGRAPH_PROP_HAS_MULTI` cache item to `false` when the only multi-edges are multi-loops. Multi-loop detection is tricky because loops occur twice in undirected neighbour lists.

I added a test to demonstrate: https://github.com/igraph/igraph/commit/d3fb4df735e149e24ea88680df2a27344264df26

This is on `develop`, but the issue should be present on `master` as well. 

Found accidentally by fuzzing.

**Comment by szhorvat** [comment]
The linked commit (on a separate branch, no PR yet) _might_ fix this, but I need a very careful review @ntamas.

I did not verify the modified test output (hard to read).

I did not verify carefully if the function behaves well in the IGRAPH_LOOPS_ONCE and IGRAPH_LOOPS_TWICE cases, but there seems to be code to handle multi-loops there.

**Comment by ntamas** [comment]
Well, these are exactly the kinds of hard-to-detect issues that I was afraid of when we started introducing caching.
I don't have time to think through this properly now but it's on my TODO list.

**Comment by szhorvat** [comment]
I have a PR open. I think that's good.

**Comment by szhorvat** [comment]
I must strictly stop looking at igraph for a  few days. @ntamas, after you fix this (either by merging this, or otherwise), can you please:

 1. Backport the fix to `master`
 2. _If you have time_, backport the (currently failing) test and fuzzers to `master` — this is useful since the fuzzer is run briefly in all PRs now
 3. Ask @krlmlr and @Antonov548 to include this fix in R/igraph 2.0.4.
