### ISSUE TITLE
Rationalize spanning tree API

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2628]
Generally, it is more useful to get a spanning tree in terms of edge IDs of the original graph than a separate graph object. The latter is easy to obtain from the former using `igraph_subgraph_from_edges()`, but the reverse transformation is not possible. At the moment we have a mishmash of both kinds of functions:

 1. `igraph_minimum_spanning_tree()` returns edges
 2. `igraph_random_spanning_tree()` returns edges
 3. `igraph_minimum_spanning_tree_unweighted()` returns a graph
 4. `igraph_minimum_spanning_tree_prim()` returns a graph

Proposal:

 - Standardize on functions that return edges, as this is more useful.
 - Drop functions that return tree graphs. What we have is not particularly useful because they lose the weights: there's no way to tell which edge in the tree objects has which weights. Indeed, the R function `mst()` drops all weights!
 - Just document that `igraph_subgraph_from_edges()` can generate a tree graph object if needed.
 - `igraph_minimum_spanning_tree()` should get a new `method` parameter which allows selecting between unweighted or Prim, and allows a later addition of Kruskal. It should have an "auto" option which will later try to auto-select the faster one from between Prim and Kruskal.

No need to worry about breaking the R interface, since it currently uses hand-written (not generated) code to call `igraph_minimum_spanning_tree_unweighted()` or `igraph_minimum_spanning_tree_prim()`, and this can be easily updated without breaking the R-side API. Non-API-breaking adaptations are possible in Python and Mathematica as well.

**Comment by ntamas** [comment]
Please go ahead if you have time to do so, the proposal sounds good to me. But I personally won't have time to do this myself in the near future.
