### ISSUE TITLE
Should we remove `igraph_array3_t` for 1.0?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2647]
Currently, `igraph_array3_t` has no use within igraph, and its API is very slightly different from that of vector/matrix (e.g. `igraph_array3_n()`). It has no documentation (other than a mention [here](https://igraph.org/c/html/latest/igraph-Data-structures.html#igraph-PMT)). I see no uses of it [in a GitHub search](https://github.com/search?q=igraph_array3+NOT+is%3Afork&type=code&p=2).

Should we remove it for 1.0?

Arguments for removing:

 - Reduced maintenance burden.
 - Freedom to start anew and produce a nicer 3D array when the need arises. Basically, we avoid committing to an imperfect implementation.

Arguments against removing:

 - Maybe there's a use of this out there, even if we didn't find it.
 - Significant work went into this functionality: there are tests, internal overflow checks, and conversion support to/from R in R/igraph.

**Comment by szhorvat** [comment]
We had the same discussion before 0.10. As I remember, @iosonofabio supported removal and I was against it. I do see value in a 3D array type, but with the experience of the past couple of years, now I think it's best to give ourselves the opportunity for a clean start.

**Comment by ntamas** [comment]
I vote for removal as well.
