### ISSUE TITLE
Remove `igraph_vector_is_equal()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2653]
Remove `igraph_vector_is_equal()` (with deprecation in 0.10.14) because it is just an alias of `igraph_vector_all_e()`.

Opinions, @ntamas ?

**Comment by ntamas** [comment]
OK.

**Comment by szhorvat** [comment]
I did a github search for this and it seems it's used by the igraphpp package.

https://github.com/ntamas/igraphpp/blob/790ddeb66e9655843e959c6a7ab9985e724cea9e/include/igraph/cpp/vector.h#L321-L324

I also seem to recall that last time this came up you preferred to keep it as an alias @ntamas.

I don't mind keeping an alias, just let me know. I'll keep this issue until later.

**Comment by szhorvat** [comment]
Decision: We keep this `is_equal()` as a more readable alias to `all_e()`.

**Comment by szhorvat** [comment]
Since we decided to keep it, I documented `vector_is_equal()` for 0.10.14.
