### ISSUE TITLE
Rename `vector_binsearch2()` to `vector_contains_sorted()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2658]
I propose renaming `igraph_vector_binsearch2()` (which I had to look up) to `igraph_vector_contains_sorted()` (a self-explanatory name).

The name `igraph_vector_contains_sorted()` is consistent with the existing `igraph_vector_contains()` (linear search) and `igraph_vector_intersection_sorted()` / `igraph_vector_intersection_size_sorted()`.

Opinions @ntamas ?

The route would be deprecation in 0.10.14 and renaming in 1.0.

----

There is also `igraph_vector_binsearch()`. I would keep that name as I find it consistent with `igraph_vector_search()`, which also exists.

**Comment by ntamas** [comment]
Sure, that's a good idea.
