### ISSUE TITLE
igraph is broken in all recent Debian/Ubuntu

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2663]
It seems that `libigraph-dev` is broken in all recent Debian/Ubuntu. The generated headers, such as `igraph_version.h`, are installed in a different location that the rest, which break `#include <igraph.h>`.

See here: https://packages.debian.org/sid/amd64/libigraph-dev/filelist

Excerpt:

```
/usr/include/igraph/igraph_vector_pmt.h
/usr/include/igraph/igraph_vector_ptr.h
/usr/include/igraph/igraph_vector_type.h
/usr/include/igraph/igraph_visitor.h
/usr/include/x86_64-linux-gnu/igraph/igraph_config.h
/usr/include/x86_64-linux-gnu/igraph/igraph_export.h
/usr/include/x86_64-linux-gnu/igraph/igraph_threading.h
/usr/include/x86_64-linux-gnu/igraph/igraph_version.h
```

Sadly, this affects Ubuntu 24.04 LTS, which has igraph 0.10.10.

If trying to compile a project that uses CMake ([see example](https://github.com/igraph/igraph-example)), it fails with

```
/usr/include/igraph/igraph.h:27:10: fatal error: igraph_version.h: No such file or directory
   27 | #include "igraph_version.h"
```

@jgmbenoit, could you please help figure out what is going wrong here?

**Comment by szhorvat** [comment]
Looks like Fedora is affected as well: https://koji.fedoraproject.org/koji/rpminfo?rpmID=39066815

**Comment by jgmbenoit** [comment]
The generated headers are assumed to be architecture depend. This is why they are under the architecture hierarchy.
So the  `libigraph-dev`  is **NOT** broken. I have just a look on these generated header on my `x86_64-linux-gnu` box. I would say that it is overdue for the headers `igraph_export.h`, `igraph_threading.h` and `igraph_version.h`, but is not for `igraph_config.h`.
For building, `pkg-config` gives an appropriate answer:

> $  pkg-config igraph --cflags

gives

> $ -I/usr/include/x86_64-linux-gnu/igraph -I/usr/include/igraph -I/usr/include/libxml2

So when autotools is used it should be okay.
For `cmake`, I am not so familiar with, but I guess you can check.
However, what I can say is that he package `python-igraph` builds well in concert with `libigraph-dev`.

If I remember well, we discussed this point some time ago.

I guess that you can make `igraph_config.h` ``softly'' architecture independent.
If you set igraph integer data type to be `size_t`  integer, the definition of  IGRAPH_INTEGER_SIZE becomes unnecessary.
Second, I guess that you can actually rely on the C version to define IGRAPH_BOOL_TYPE.

**Comment by szhorvat** [comment]
OK, I understand the motivation, but it seems that the CMake package files would need to be patched as well to account for this change.

Unfortunately, I'm also not very comfortable with CMake, but I think it's the `igraph-targets.cmake` file that needs attention. On macOS, I see this line in that file:

```cmake
set_target_properties(igraph::igraph PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/igraph;${_IMPORT_PREFIX}/include"
)
```

Would it be possible to patch this and add the extra location?

**Comment by jgmbenoit** [comment]
For Debian, the [debian/patches/upstream-fix-multiarch-file_conflict.patch](https://salsa.debian.org/med-team/igraph/-/blob/master/debian/patches/upstream-fix-multiarch-file_conflict.patch?ref_type=heads)  is applied.

**Comment by szhorvat** [comment]
Can you please try patching here as well?

https://github.com/igraph/igraph/blob/58517058c50c093bf1805086c7e6521a9f35ab3c/src/CMakeLists.txt#L356-L362

I think you need to add an additional `$<INSTALL_INTERFACE:...` line with the extra include dir.

**Comment by szhorvat** [comment]
@jgmbenoit Can you please consider adding the following at [this position](https://github.com/igraph/igraph/blob/58517058c50c093bf1805086c7e6521a9f35ab3c/src/CMakeLists.txt#L377), and updating the Debian package?

```cmake
if(CMAKE_LIBRARY_ARCHITECTURE)
  target_include_directories(
    igraph
    PUBLIC
    $<INSTALL_INTERFACE:include/${CMAKE_LIBRARY_ARCHITECTURE}/igraph>
  )
endif()
```

I tested this in Docker on trixie and it seems to fix the issue.

We generally recommend using CMake to build programs that use igraph. If this does not work on Debian, that is a serious issue that should be fixed.

**Comment by szhorvat** [comment]
Here's a question: since some headers are architecture-specific, is there any point at all on installing headers in `/usr/include`? Why not install _everything_ in `/usr/include/x86_64-linux-gnu/`, make sure that headers are kept together, and reduce the risk of problems?

**Comment by jgmbenoit** [comment]
The point is that most headers are not architecture specific, so that they can be shared on multi-arch systems. This can also reduce the overall size of the packages. Here only `igraph_config.h`  is architecture specific a priori. But, in its current state, I think it can be made softly architecture independent is igraph integers are of type `size_t` .

**Comment by jgmbenoit** [comment]
> Note that we do not support including sub-headers individually. Only `#include <igraph.h>` is supported. This will be made explicit from version 1.0. Therefore the set of headers should be treated as a unit.

This is transparent for the end-user provided that the `-I` options contains the `arch` hierarchy path.

**Comment by jgmbenoit** [comment]
> We generally recommend using CMake to build programs that use igraph. If this does not work on Debian, that is a serious issue that should be fixed.

I will try to patch the Debian by the end of the day.
The current Debian CI tests used simple `Makefile` files (e.g., [here](https://salsa.debian.org/med-team/igraph/-/blob/master/debian/adhoc/examples/benchmarks/Makefile?ref_type=heads)) that grabs compiler options via  `pkg-config`.
We can easily make the same test but via a `cmake` machinery.
What would be a simple `cmake` version of them ?

**Comment by jgmbenoit** [comment]
I will wait for the last package to reach testing as it would reset the counter otherwise.

**Comment by jgmbenoit** [comment]
I have just uploaded and pushed to Salsa the change.
However it appears that in the `cmake` chunk the order is not correct:
the compiler must visit the arch hierarchy first. Do you know how to change this order ?

Otherwise, it would be nice to have a basic `cmake` material in `<igraph>/examples`. 
This will allow to use Debian CI  to check the `cmake` material provided by `igraph`.

**Comment by szhorvat** [comment]
P.S. For setting up a barebones CMake-based project and test if things are working as they should, you can use this: https://github.com/igraph/igraph-example/tree/master/cmake-project
