### ISSUE TITLE
LGL layout has stopped working correctly

### ISSUE THREAD

**Issue by jdfoote** [igraph/igraph#2676]
### What happens, and what did you expect instead?

The LGL layout, instead of looking like other force-directed layouts, now appears to put the nodes into two corners of the figure, at least for all graphs that I have tried.

### To reproduce

``` r
## Create random network
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
```

``` r

set.seed(123)
G <- sample_pa(20)

layout <- layout_with_lgl(G)

plot(G, layout=layout)
```

![](https://i.imgur.com/AuvS6MH.png)

<sup>Created on 2024-09-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### System information

R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 24.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Indiana/Indianapolis
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_2.0.3

loaded via a namespace (and not attached):
[1] compiler_4.3.3  magrittr_2.0.3  cli_3.6.3       lifecycle_1.0.4
[5] pkgconfig_2.0.3 rlang_1.1.4

**Comment by szhorvat** [comment]
This is what I get with R/igraph 1.4.1:

<img width="529" alt="image" src="https://github.com/user-attachments/assets/beb9a9b6-2d53-489e-b64d-1751d00ed6cf">

This is what I get with the latest C core when selecting the first vertex as the root:

```
> set.seed(123)
> G <- sample_pa(20)
> 
> layout <- layout_with_lgl(G, root=1)
> 
> plot(G, layout=layout)
```

<img width="559" alt="image" src="https://github.com/user-attachments/assets/b9643ce6-39a9-4aa8-b259-db95e1d32659">

I'll look into why there is such a stark difference when I get the time. The recommendation to use something else still stands though.

**Comment by szhorvat** [comment]
Something is not right. The bad layout is already present in R/igraph 2.0.3, which was released in March. The change I referenced was made in June.

It seems that a problem was introduced much earlier.

We'll look into it.

**Comment by jdfoote** [comment]
For what it's worth, this is not something that I personally care deeply about. I have my students play around with different layouts, and noticed that this was borked. One possible solution may simply be just to remove it?

**Comment by maelle** [comment]
@szhorvat does this mean we should move towards deprecation? if so you can add the lifecycle label and assign the issue to me :innocent:

**Comment by szhorvat** [comment]
I'll be honest, I don't have a full understanding of what went wrong exactly, but I think this is now fixed, mainly through not upscaling initial coordinates to 10^6, but also by correcting the root vertex placement.

1f153e9ca1b7e03ae4387d2500b4ccf4d3bc2703

I'm getting this with your example @jdfoote, and other examples I tried are also relatively reasonable.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/a4a8c83b-63b1-42fb-a3ff-91fcb2c41709">

Let's not rush the deprecation yet. Perhaps my negative view of this function was because I mostly tried it in 0.10 where it was already misbehaving.

**Comment by szhorvat** [comment]
Some more examples:

```
g <- make_lattice(c(10,10))
plot(g, layout=layout_with_lgl(g))
```

<img width="525" alt="image" src="https://github.com/user-attachments/assets/d543396b-660a-41ad-849a-d9053e29e4c2">


```
library(igraphdata)
data('immuno')
plot(immuno, layout=layout_with_lgl(immuno, maxiter=1000), vertex.size=2, vertex.label=NA)
```

<img width="527" alt="image" src="https://github.com/user-attachments/assets/b610ef89-3494-4def-89ef-a9d2c917756c">
