### ISSUE TITLE
vcpkg build error

### ISSUE THREAD

**Issue by icyfox168168** [igraph/igraph#2680]
**Describe the bug**

**To reproduce**
Steps or minimal example code to reproduce the problem.

**Version information**
Which version of igraph are you using and where did you obtain it?

D:\temp23\igraph\src\igraph-0-2257b8cf49.clean\vendor\plfit\hzeta.c(105): error C2099: initializer is not a constant
D:\temp23\igraph\src\igraph-0-2257b8cf49.clean\vendor\plfit\hzeta.c(143): error C2099: initializer is not a constant

**Comment by szhorvat** [comment]
Please explain in plain language what the problem is, and will out the bug template in full.

We can't act on two lines of pasted error messages that don't have any context.

**Comment by szhorvat** [comment]
igraph compiles without error with vcpkg on Windows. See https://github.com/microsoft/vcpkg/pull/41568  We also test compiling on Windows in our standard CI runs.

Perhaps you used a flag that turns warnings into errors. The "initializer is not a constant" warning is expected, but it should be only a warning.

If this is not what happens, please give _complete_ instructions to reproduce the problem, including igraph version, compiler version, operating system, etc. and fill out the bug report form in full.
