### ISSUE TITLE
Tag 0.10.14 missing

### ISSUE THREAD

**Issue by dotlambda** [igraph/igraph#2689]
https://github.com/igraph/python-igraph/blob/main/CHANGELOG.md#0117---2024-10-24 claims there is a version 0.10.14 of igraph. However there is no such tag on https://github.com/igraph/igraph/tags.

**Comment by szhorvat** [comment]
I believe this was a mistake in the release notes. I suggest you either postpone the update in Nix until the release happens (hopefully relatively soon), or use the vendored C core sources when building python-igaph.
