### ISSUE TITLE
Undirected self-loops are sometimes not detected by the cycle finder

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2692]
@GenieTim, it looks like there's an issue I missed before merging the PR. Sometimes, self-loops are not detected.

This is fine, all 3 cycles are found:

```
        igraph_small(&g, 7, IGRAPH_UNDIRECTED,
                     0,1, 1,2, 2,0,
                     0,0,
                     0,3, 3,4, 4,5, 5,0,
                     -1);
```

But the self-loop is not found with this graph:

```
        igraph_small(&g, 7, IGRAPH_UNDIRECTED,
                     0,1, 1,2, 2,0,
                     1,1,
                     0,3, 3,4, 4,5, 5,0,
                     -1);
```

The only difference is putting the self-loop on vertex 1 instead of vertex 0.

Could you please have a look? This would require opening a new PR.

In the very worst case, we'll drop self-loops and do a separate pass to detect them. But hopefully, this can be fixed in the algorithm without special-casing.

UPDATE: This affects only undirected graphs. I updated the example code.

**Comment by szhorvat** [comment]
This might actually be a nice graph to test, both in `IGRAPH_OUT` mode (as directed) and `IGRAPH_ALL` mode (as undirected).

<img width="360" alt="image" src="https://github.com/user-attachments/assets/d91956f6-33b2-4a13-bbaa-53c86e3bbaff">

It has four cycles, one of size 1, size 2, size 3 and size 4.

The edge list:

```
0, 1, 1, 2, 2, 0, 0, 3, 3, 4, 4, 5, 5, 0, 1, 1, 5, 6, 6, 5
```

Mathematica code to create this, for reference:

```
g = IGShorthand["0->1->2->0->3->4->5->0,1->1,5<->6", 
  MultiEdges -> True, SelfLoops -> True, GraphStyle -> "DiagramGold", 
  VertexLabels -> Placed["Name", Center]]
```

**Comment by szhorvat** [comment]
@GenieTim There's also another issue: multi-self-loops are not all identified. Only one is returned (if at all). I made a crude fix in the above commit, so Tamás can go ahead with a release when he gets the time. The fix handles self-loops in advance, then ignores them later. If you find the cause of the issue, we should revert this and go with a proper fix. However, if you think the algorithm can't handle self-loops well, we might as well stick with this.

**Comment by olivier7121** [comment]
I implemented in C last year the Johnson's algorithm to extract elementary circuits. The default Johnson's algorithm indeed doesn't find each and every self-loop. I also had to pre-process the graph to first extract the self-loops and remove the related vertices from the links list, and then apply the classic Johnson's algorithm on the links list without self-loops.

**Comment by GenieTim** [comment]
@olivier7121 do you happen to still have examples from back then, where the self loops were not found, such that we can integrate those examples as tests here?

**Comment by olivier7121** [comment]
Yes, I still have them -- 7 different graphs in total.
For the first one, the default Johnson's algorithm only found 1 self-loop while there actually are 6 in total.
For the second one, the default Johnson's algorithm didn't find any self-loop while there actually are 9 in total.
The links lists are a bit long (100+ items), so I attached them as 
text files (format: 1st column 'from', 2nd column 'to').
These lists can certainly be pruned.
[Self-loops - Example 1 - Links.txt](https://github.com/user-attachments/files/17661005/Self-loops.-.Example.1.-.Links.txt)
[Self-loops - Example 2 - Links.txt](https://github.com/user-attachments/files/17661006/Self-loops.-.Example.2.-.Links.txt)

**Comment by szhorvat** [comment]
Both of these graphs work fine, it finds the 6 and 9 self-loops.

Cycle size histogram for the first graph:

```
<|1 -> 6, 2 -> 6, 3 -> 19, 4 -> 17, 5 -> 20, 6 -> 29, 7 -> 37,  8 -> 39, 9 -> 31, 10 -> 32, 11 -> 40, 12 -> 30, 13 -> 12|>
```

For the second graph:

```
<|1 -> 9, 3 -> 2, 4 -> 43, 5 -> 8, 6 -> 18, 7 -> 2, 8 -> 4|>
```

The format is `cycleSize -> cycleCount`.

**Comment by szhorvat** [comment]
Thanks again! Self-loop counts are all good, but graph 4 actually has 5 loops (it only has loops).

Performance on graph 7 is pretty bad, we might want to look into this at some point @GenieTim

**Comment by olivier7121** [comment]
> Self-loop counts are all good, but graph 4 actually has 5 loops (it only has loops).
There is a duplicate in graph 4, vertex 70 appears twice (because they are 2 different self-loops, with 2 different underlying transaction types).

**Comment by szhorvat** [comment]
Let me revise the claim about performance. Here's a performance comparison with Mathematica:

```
In[81]:= RepeatedTiming[IGSimpleCycles[gr];, 30]
Out[81]= {5.12986, Null}

In[82]:= sgr = SimpleGraph[gr];
RepeatedTiming[IGSimpleCycles[sgr];, 30]

Out[83]= {1.10667, Null}

In[84]:= RepeatedTiming[FindCycle[gr, Infinity, All];, 30]
Out[84]= {1.83131, Null}

In[91]:= RepeatedTiming[FindCycle[sgr, Infinity, All];, 30]
Out[91]= {1.19766, Null}
```

Mathematica appeared to be faster at first, but it turns out that it does not handle multi-edges correctly and returns buggy results for multigraphs. Our function is good.  If we simplify the graph, our function is also faster.

**Comment by szhorvat** [comment]
> There is a duplicate in graph 4, vertex 70 appears twice

Yep, we want to count both of those self-loops on vertex 70.
