### ISSUE TITLE
Eliminate all gcc warnings

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#297]
For the external code, we might need some patches....

---

Imported from Launchpad using lp2gh.
- date created: 2012-06-14T15:39:11Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/1013231

**Comment by ntamas** [comment]
igraph now compiles without warnings with recent `gcc` and `clang` versions, even with `-Wall -Wextra -pedantic -Werror`.
