### ISSUE TITLE
RFE: implement electrical resistance distance

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#298]
feature request: implement calculation of the electrical resistance distance on graph.
http://mathworld.wolfram.com/ResistanceDistance.html

---

Imported from Launchpad using lp2gh.
- date created: 2012-08-17T15:56:46Z
- owner: sds-gnu
- the launchpad url was https://bugs.launchpad.net/bugs/1038150

**Comment by szhorvat** [comment]
This only requires plain linear algebra. As Gábor notes, it's probably better done in the high-level languages, as they might have better linear algebra facilities than what C/igraph can afford to include (e.g. access to the MKL).

**Comment by szhorvat** [comment]
I have a list of references for this. I'll link it here as it might be useful to others as well: https://github.com/szhorvat/IGraphM/issues/88
