### ISSUE TITLE
Mean first passage time calculation

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#319]
http://www.datalab.uci.edu/papers/white_smyth.pdf can be used as a starting point.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-05-28T09:42:15Z
 * owner: gabor.csardi
 * the launchpad url was https://bugs.launchpad.net/bugs/381228

**Comment by barrpet** [comment]
This is a couple of years old now but I was wondering if there would still be interest in this. I've impletmented MFPT (for Markov Centrality) in a couple of my own projects and would love to get it into the core. It is inherently slow with the best known algorithms being O(n^3) but runs in reasonable time for |V| < 10^3.

**Comment by gaborcsardi** [comment]
You can submit a PR if you like. 

You can also put it in your own package, as igraph is already huge.
