### ISSUE TITLE
Geometric random graphs in n-D space (n > 2)

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#325]
It would be nice to extend igraph_grg_game to be able to work in n-dimensional spaces (where n > 2).

---

Imported from Launchpad using lp2gh.
- date created: 2010-04-04T16:55:52Z
- owner: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/555244

**Comment by szhorvat** [comment]
IMO this is a not a good fit for the C core. 

A geometric random graph based on a uniform random point distribution within a unit cube, and a basic distance cutoff, is not particularly useful. One would normally want to customize the point distribution, the distance metric, and the connection criterion (may not be a deterministic basic cutoff). At this point, this is better implemented in high-level languages.

**Comment by szhorvat** [comment]
Also, if we were to go this route, we would need a good foundation for geometric computing. The first step would be some sort of nearest neighbour search algorithm, such as k-D trees, which would allow an efficient implementation. I'm not sure if this should be within igraph's scope ...
