### ISSUE TITLE
Implement dyad-wise and  edge-wise shared partners

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#331]
and this is a definition I've found in the ergm package:

dsp(d):

Dyadwise shared partners: The d argument is a vector of distinct integers. This term adds one network statistic to the model for each element in d; the ith such statistic equals the number of dyads in the network with exactly d[i] shared partners. This term can be used with directed and undirected networks. For directed networks the count is over homogeneous shared partners only (i.e., only partners on a directed two-path connecting the nodes in the dyad).

---

Imported from Launchpad using lp2gh.
- date created: 2010-06-28T17:42:50Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/599471

**Comment by digitaldust** [comment]
@ntamas I am trying to port this on Python like this:

    def esp(g):
        '''
        Find edgewise shared partners distribution
        '''
        bib = np.array(igraph.GraphBase.bibcoupling(g))
        edg = igraph.GraphBase.get_edgelist(g)
        res = bib[np.array([x for x,y in edg]), np.array([y for x,y in edg])]
        return pd.Series(res).value_counts()

it is however very slow for a network with 5000 nodes, so I am trying to implement your suggestion for the dice similarity, but got stuck... is there any development on the ESP measure that you can share? Thanks

**Comment by ntamas** [comment]
You can get the Dice similarity metric for all connected pairs of edges with something like this:

```
edges = g.get_edgelist()
dice = g.similarity_dice(pairs=edges, loops=False)
```

The `loops=False` part is important; the Dice similarity metric assumes that every vertex is adjacent to itself by default, and we don't need that here.

Since the Dice similarity is twice the number of common neighbors, divided by the sum of the degrees of the vertices involved in the pair, you can now get the number of common neighbors back:

```
degrees = g.degree()
degree_sums = [degrees[i]+degrees[j] for i, j in edges]
num_common_neis = [value * degree_sum / 2 for value, degree_sum in zip(dice, degree_sums)]
```

Due to roundoff errors, `num_common_neis` will sometimes be close to but not exactly equal to an integer; just round it to the nearest integer and you'll be OK.

**Comment by digitaldust** [comment]
@ntamas thanks for this, it works like charm!

**Comment by 12yy88** [comment]
Is there a way to do it in R?

**Comment by szhorvat** [comment]
I do not think igraph should have these concepts implemented under these very specialized names, which are only used when dealing with certain exponential random graph models for social network analysis. 

"dyadwise shared partners" means: how many common neighbours do two vertices have? It's the same a `cocitation` and `bibcoupling`, already implemented in igraph. It's a trivial matrix operation that's easily implemented in any scientific computing system (including R): square the adjacency matrix and discard the diagonal.

"edgewise shard partners" means: how many common neighbours do two _connected_ vertices have? Thus the same and above, but mask the squared adjacency matrix with the original one.
