### ISSUE TITLE
Add support for hierarchical random graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#332]
GPL code (C++) is available at http://tuvalu.santafe.edu/%7Eaaronc/hierarchy/

---

Imported from Launchpad using lp2gh.
- date created: 2010-07-23T13:48:37Z
- owner: gabor.csardi
- assignee: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/609152

**Comment by szhorvat** [comment]
As mentioned above, this seems to be done for the C core (though I never used it).
