### ISSUE TITLE
R: Add weighted edge.betweenness.community

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#337]
Would allow edge weighting to be used in edge betweenness method of community detection. For algorithm see Newman, M.E.J. 2004. Analysis of weighted networks.  Physical Review E. vol. 70 (2), no5, pp. 056131.1-056131.9.

---

Imported from Launchpad using lp2gh.
- date created: 2010-09-14T15:57:30Z
- owner: aedelman
- assignee: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/638174

**Comment by axrodriguez1** [comment]
Hello everybody in this site
