### ISSUE TITLE
Arbitrary null models in community finding algorithms

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#352]
"Another possible solution would be to modify our implementation of the fast-greedy modularity algorithm. I think this could easily use any null model you want. It might involve a fair amount of work, though. 

The spinglass implementation might be specific to the two kinds of null models, but I am not sure, actually, so this would require some checking. "

---

Imported from Launchpad using lp2gh.
- date created: 2012-05-22T18:57:41Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/1003069

**Comment by szhorvat** [comment]
Related: #1845

**Comment by szhorvat** [comment]
@vtraag Is this feasible or should we just close it?

**Comment by ntamas** [comment]
Well, it's feasible, but not necessarily efficient. The perceived speed of the fast modularity optimization algorithm relies on the fact that not only we can calculate the modularity score w.r.t. the usual null model efficiently, but we can also calculate the _change_ in the modularity score after merging two communities, without having to recalculate the entire score from scratch.

So, if we wanted the user to be able to specify an arbitrary null model but not bother with figuring out how to calculate the deltas, we would need to fall back to an alternative implementation of the greedy modularity optimization that just calculates the new modularity score for every possible merge from scratch. This would work, but it won't nearly be as efficient as the current implementation. Or, we could require the user to not only provide the null model but also provide a function that receives the graph, the current membership vector and the indices of the communities being merged, and return the _change_ in modularity after the merge, which would remain efficient but then the burden is on the user to figure out the calculation for this.

**Comment by szhorvat** [comment]
I understand that, but it seems to me that this makes feasibility or non-feasibility specific to each community detection method.  It does not make sense to have a single issue for all methods.

 - Some don't use modularity at all, such as label propagation.
 - Some produce a dendrogram with a modularity-agnostic approach, then cut the dendrogram based on modularity. This requires only a few modularity computations at the end.
 - Some optimize modularity directly, and need to re-compute it after various types of mutations of the partitioning (e.g. merging, splitting, moving of single vertex, etc.) This means a potentially large number of recomputations. Whether these can be done fast depends not only on the modularity concept, but also the nature of the mutation.

There should be separate issues for each method where it makes sense to consider this, such as #1845. I don't see an actionable item in this issue.

**Comment by ntamas** [comment]
> I understand that, but it seems to me that this makes feasibility or non-feasibility specific to each community detection method.

Indeed it is. I was thinking about the "fast greedy" community detection method only, and I guess the original issue was also about that only.

For methods that do not optimize modularity at all, it makes no sense to expect the possibility to specify a null model. (Label propagation _does_ use modularity as far as I know when it decides which new community to move a given node to).

That being said, let's close this issue and we should open a new one _specifically_ for the fast greedy method (or the Leiden method) if we want to implement arbitrary null models for a specific method.

**Comment by szhorvat** [comment]
> (Label propagation _does_ use modularity as far as I know when it decides which new community to move a given node to).

Label propagation, as implemented in igraph, just updates labels repeatedly until the label of each vertex agrees with the majority label of its neighbours.  I think it's the Louvain method that moves vertices between partitions so as to improve modularity.

**Comment by ntamas** [comment]
Sorry, you are right, my bad.
