### ISSUE TITLE
crash when constructing graph from an LGL file and saving it to NCOL using the C attribute handlers

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#370]
A simple C program to reproduce the problem:

```
#include <igraph/igraph.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
    FILE* f=fopen("test.lgl", "r");
    igraph_t g;

    igraph_i_set_attribute_table(&igraph_cattribute_table);

    igraph_read_graph_lgl(&g, f, 1, 1);
    fclose(f);

    f=fopen("test.ncol", "w");
    igraph_write_graph_ncol(&g, f, "name", "weight");
    fclose(f);
}
```

The result is:
`Assertion failed: (sv->data[idx] != 0), function igraph_strvector_get, file ../../src/igraph_strvector.c, line 122.`

---

Imported from Launchpad using lp2gh.
- date created: 2008-10-26T19:04:24Z
- owner: ntamas
- assignee: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/289596

**Comment by EvanGrandfield1** [comment]
Currently using python_igraph-0.7.1 on Windows 10. When I try to call group_from_graph() I am running into the same issue. 
The error looks like this:
`Assertion failed: sv->data[idx] != 0, file src\igraph_strvector.c, line 128`

**Comment by ntamas** [comment]
`group_from_graph()` is not a function or method in `python-igraph` as far as I know. Please post a short, self-contained example on which I could try reproducing the problem on my machine.
