### ISSUE TITLE
Implement the heuristics of Wakita and Tsurumi for the fast greedy community detection

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#376]
See http://arxiv.org/abs/cs/0702048v1

---

Imported from Launchpad using lp2gh.
- date created: 2009-04-01T08:46:34Z
- owner: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/352963

**Comment by ntamas** [comment]
I think this has already been implemented years ago. Closes #376.

T.
