### ISSUE TITLE
Add function to find all cycles.

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#379]
Should not be hard, just BFS, but potentially there can be a lot of cycles.

---

Imported from Launchpad using lp2gh.
- date created: 2009-04-10T13:31:56Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/359069

**Comment by isidroc** [comment]
Has this been finally implemented? Thanks

**Comment by xiaozhi-alan-zhu** [comment]
Has this been finally implemented?  If not, is there any way to work around with cycle_basis? Thanks!

**Comment by szhorvat** [comment]
Closing in favour of #1398. Please continue the discussion there. The implementation of cycle basis calculations is currently underway in #1786.
