### ISSUE TITLE
Repeat calls to community_leading_eigenvector cause "Unknown ARPACK error" for some graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#399]
Code worked fine for the past few weeks running on Launchpad trunk from a month or two ago.
Updated today and the following example now crashes.

> > g=igraph.Graph([(2, 0), (3, 0), (4, 1), (4, 1), (5, 2), (6, 4), (7, 5), (7, 4), (8, 4), (8, 4), (9, 4), (9, 0), (10, 2), (11, 7), (12, 0), (13, 8), (13, 9), (13, 8), (15, 6), (16, 9), (16, 2), (16, 3), (17, 0), (17, 8), (17, 2), (17, 14), (18, 15)

In [24]: g.community_leading_eigenvector()
Out[24]: <igraph.clustering.VertexClustering object at 0x21f2610>
## In [25]: g.community_leading_eigenvector()

InternalError                             Traceback (most recent call last)

/home/mjbommar/Source/igraph/<ipython console> in <module>()

/usr/lib/python2.6/dist-packages/igraph/**init**.pyc in community_leading_eigenvector(self, clusters, return_merges)
    538         eigenvectors of matrices, arXiv:physics/0605087"""
    539         if clusters is None: clusters=-1
--> 540         cl, merges = GraphBase.community_leading_eigenvector(self, clusters, return_merges)
    541         if merges is None:
    542             return VertexClustering(self, cl)

InternalError: Error at community.c:1184: , Unknown ARPACK error

---

Imported from Launchpad using lp2gh.
- date created: 2009-07-24T18:43:57Z
- owner: mjbommar
- the launchpad url was https://bugs.launchpad.net/bugs/404256

**Comment by seralouk** [comment]
Dear all,

I have a graph represented by a 90x90 weighted adjacency matrix.

`comms = g.community_leading_eigenvector(weights = g.es["weight"])`

returns

InternalError: Error at arpack.c:944: ARPACK error, No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV

but

`comms = g.community_fastgreedy(weights = g.es["weight"])`

works fine.

Any idea how to solve my problem when using `community_leading_eigenvector`?

**Comment by szhorvat** [comment]
Directly attached data file mentioned in above message. Next time please attach the file here (to ensure it's preserved in the long term).

[A.npy.zip](https://github.com/igraph/igraph/files/3390085/A.npy.zip)

**Comment by seralouk** [comment]
I just found out that a NaN value was causing the problem in my case.
