### ISSUE TITLE
more options for multilevel.community

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#463]
feature requst: make multilevel.community accept parameters which tune the algorithm,
e.g., specify the epsilon (the min modularity improvements to continue).
also, the returned community structure should be hierarchical.
thanks!

---

Imported from Launchpad using lp2gh.
- date created: 2012-08-15T19:34:28Z
- owner: sds-gnu
- the launchpad url was https://bugs.launchpad.net/bugs/1037260

**Comment by LaurentGrima** [comment]
Hello guys !
Has there been any news on this topic since 2013 that would not be displayed here ? :)
Cheers

**Comment by ntamas** [comment]
No news here, sorry :( But we always welcome patches! ;)

**Comment by LaurentGrima** [comment]
Haha yes. But I am definitely not enough at ease in C to do that.
Anyway thanks for the reply !
