### ISSUE TITLE
Centrality and multiple and loop edges

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#469]
Make sure that centrality calculations have a sensible behavior for graphs with multiple and loop edges, and unconnected graphs. Degree should be fine, obviously. To check:

- [x] closeness
- [x] betweenness
- [x] edge betweenness
- [x] eigenvector centrality
- [x] constraint
- [x] hub_and_authority
- [x] coreness

---

Imported from Launchpad using lp2gh.
- date created: 2013-01-06T16:06:40Z
- owner: gabor.csardi
- assignee: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/1096617

**Comment by szhorvat** [comment]
Related: https://github.com/igraph/igraph/wiki/Checklist-for-new-(and-old)-functions

**Comment by szhorvat** [comment]
@ntamas I checked off betweenness in this, do you agree?

**Comment by ntamas** [comment]
Yup.

**Comment by szhorvat** [comment]
Eigenvector centrality and closeness centrality are also fine. We cleaned up eigenvector centrality a while ago and ensured that it considers self-loops twice. This is now clearly documented.

**Comment by szhorvat** [comment]
@GroteGnoom The last thing that's missing here is `constraint`. You've been working on this: does it behave with multi-edges and self-loops?

**Comment by GroteGnoom** [comment]
I think it does fine: https://github.com/igraph/igraph/pull/2103#issuecomment-1193275143

**Comment by szhorvat** [comment]
Thanks @GroteGnoom! Do you think we can close this now, or are there any other functions to verify?

**Comment by GroteGnoom** [comment]
Maybe hub_and_authority still needs to be checked? I see loops in the tests, but not mulit-edges. 

I'm also not sure about coreness. There's no direct tests.

**Comment by szhorvat** [comment]
I added these two to the top.

**Comment by ntamas** [comment]
I've added unit tests for `igraph_coreness()`, and one part of the unit test randomly adds loop and multiple edges to the Zachary karate club graph and then validates that the coreness vector seems valid, so I'm pretty sure that coreness handles multi- and loop edges correctly.

**Comment by szhorvat** [comment]
With #2301 done, this is now complete.
