### ISSUE TITLE
Kruskal's algorithm for minimum spanning tree

### ISSUE THREAD

**Issue by fr4nk3nst3in** [igraph/igraph#482]
Please add Kruskal's algorithm to the named function.

So it should be posible to compare both algorithms wich perform better. And then use better algorithm.

So i can use and plot in the same way as Prim's algorithm like this:

mst <- minimum.spanning.tree(g, algorithm = "prim")
plot(mst)

**Comment by szhorvat** [comment]
I have this implemented. It's being blocked by https://github.com/igraph/igraph/issues/2628

It still needs testing, and benchmarking.
