### ISSUE TITLE
Feature request: Arrow Sizes that Match Edge width in R interface

### ISSUE THREAD

**Issue by low-decarie** [igraph/igraph#490]
Thanks for the great work!
It would be great to have arrow sizes that match edge width in the R interface for igraph.

I have also posted a question for this on stack and was recommended to post the comment here:
http://stackoverflow.com/questions/16942553/a-hack-to-allow-arrows-size-in-r-igraph-to-match-edge-width/16943418?noredirect=1#16943418

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#10
