### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by Heliosmaster** [igraph/igraph#498]
I think it would be great also the mention in the [former website] (http://igraph.sourceforge.net/) that the development has moved to github.

Searching for "igraph" on Google does not give any result linked to GitHub, and I could find it only because was mentioned in the discussion of an issue.

Maybe the old website could be replicated at igraph.github.io (which as of now points to igraph.org and has a default jekyll-page).

**Comment by gaborcsardi** [comment]
This was done, actually, a long time ago, there are redirects in place, so all should be good.
