### ISSUE TITLE
ARPACK error, Maximum number of iterations reached when benchmarking modularity algorithms using microbenchmark

### ISSUE THREAD

**Issue by niedakh** [igraph/igraph#512]
I came across an interesting bug while running the following code:

```
microbenchmark(leading.eigenvector.community(graph),times=100)
```

It runs for some time without problems, repeatedly returning proper results, while at some point it just breaks with: 

```
Error in leading.eigenvector.community(graph) :
  At arpack.c:928 : ARPACK error, Maximum number of iterations reached
```

Setting igraph.arpack.default$maxiter to +Inf or to a huge number like 3e+120 still doesn't help. The graph has 983 nodes and 6935 edges. I can attach the Rdata image with the graph defined, but I'm pretty sure this must be some simple bug in the code not resetting arpack properly thus arpack not reseting the iteration counter properly.

I am running R 3.0.1 with igraph 0.6.5-2 and microbenchmark-1.3-0.

**Comment by Aditya-ks** [comment]
@ntamas thank you, increasing number of iterations worked for me too!

**Comment by DJMat23** [comment]
Use:
leading.eigenvector.community(G,options=list(maxiter=1000000))
