### ISSUE TITLE
Use subdir-objects for automake

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#524]
This is reported by the R package, but I guess it is also an issue for the C lib:

automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.

**Comment by ntamas** [comment]
Not relevant any more; in configure.ac, we are invoking `AM_INIT_AUTOMAKE([foreign subdir-objects])` now.
