### ISSUE TITLE
Support for DIMACS shortest path format

### ISSUE THREAD

**Issue by lesshaste** [igraph/igraph#539]
The DIMACS shortest path competition has an input format that is not currently supported by igraph. Example files can be found at

http://www.dis.uniroma1.it/challenge9/download.shtml

The main feature is that the edges are lines like

a 1 2 803

where 1 and 2 are vertex ids and 803 is the weight.

**Comment by PayasR** [comment]
It appears there are several DIMACS formats from different challenges over the years, but it is wrong to name the function read_dimacs() if the support is only for color format. We need overloaded functions to read different files. Is the support planned?

**Comment by ntamas** [comment]
As far as I know it's not planned.

**Comment by PayasR** [comment]
JGraphT supports a [couple](http://jgrapht.org/javadoc/org/jgrapht/ext/DIMACSFormat.html) of them. I had a look at the igraph code, it should take a few hours i guess.. PRs welcome?

**Comment by ntamas** [comment]
Yes, definitely - actually, that's probably the only way right now to get this implemented in igraph as I don't have too much time to dedicate to development on my own. I will be happy to review a pull request. Let me know if you have any questions.
