### ISSUE TITLE
ARPACK returns bad eigenvalues in weighted directed eigenvector centrality

### ISSUE THREAD

**Issue by kalenedrael** [igraph/igraph#544]
When calculating eigenvector centrality for a particular directed graph with weighted edges, igraph_eigenvector_centrality() unexpectedly returns a negative eigenvalue. It appears that ARPACK is not returning the largest eigenvalue as requested - the eigenvalue returned isn't even the one with the greatest magnitude. All edge weights are positive and there are no loop edges. Unfortunately I can't share the offending graph because it contains confidential data. I haven't been able to reproduce the issue with other graphs.

I did find that ARPACK returns different a different result if asked to calculate more than one. If a bipartite graph with 4 vertices is constructed with the following adjacency matrix, for instance:

```
0 0 0.803829 0.644412
0 0 0.385865 1.075488
0.380149 0.100474 0 0
0.164536 0.220675 0 0
```

then ARPACK correctly returns 0.787969 as the eigenvalue, but when two eigenvalues are computed (setting options->nev = 2 and initializing the result vector to 2 columns in igraph_eigenvector_centrality_directed()), it results in the two negative eigenvalues -0.258478 and -0.787969, of which the first is returned from igraph_eigenvector_centrality(). Conversely, for the original problematic graph, computing two eigenvalues causes the correct eigenvalue to be returned, but the default results in a negative eigenvalue.

The code for this example and the fuzzer used to find it are in this gist: https://gist.github.com/kalenedrael/7492873
I should clarify that running the fuzzer with an unmodified igraph hasn't yielded any negative eigenvalues - only when igraph is modified to compute two eigenvalues does it return negative.

**Comment by szhorvat** [comment]
I tried the test program, and I cannot reproduce the issue in the current version. I used the vendored ARPACK which is _less_ reliable than the latest ARPACK-NG.  I also tried the fuzzer, and ran it for a couple of minutes, but it did not find issues.

I am closing this for now, feel free to reopen if the issue resurfaces specifically for eigenvector centrality. We do know that in general ARPACK does not always converge, especially the vendored ARPACK, see #1641, #1990, #678.
