### ISSUE TITLE
Fix C test cases that fail on some platforms

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#548]
A bunch of tests are skipped non-OSX platforms, using code like

```
#ifdef __APPLE__
  return 0;
#else
  return 77;
#endif
```

These should be fixed to be platform independent, as they indicate that igraph itself is platform-dependent, even when using the same random seed.

**Comment by szhorvat** [comment]
The following files have this in `examples/simple`:


```
igraph_community_infomap.c
igraph_community_multilevel.c
igraph_hrg2.c
igraph_hrg3.c
igraph_layout_merge2.c
igraph_scg_grouping3.c
igraph_scg_grouping4.c
igraph_scg_semiprojectors2.c
igraph_scg_semiprojectors3.c
scg2.c
scg3.c
```

**Comment by szhorvat** [comment]
A return code of 77 signals a skipped test.

From here:

https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html

> When no test protocol is in use, an exit status of 0 from a test script will denote a success, an exit status of 77 a skipped test, an exit status of 99 an hard error, and any other exit status will denote a failure.
