### ISSUE TITLE
C: igraph uses vector of doubles as vector of integers

### ISSUE THREAD

**Issue by kalenedrael** [igraph/igraph#556]
I'm not sure this is a real issue but I don't know where else to bring it up. The C library uses igraph_vector_t, a vector of doubles, in many places where a vector of integers is called for. What's the rationale behind this? I believe there will be a general usability and performance improvement if igraph_vector_long_t or similar are used where semantically the vectors must hold integers.

**Comment by szhorvat** [comment]
>  I believe there will be a general usability and performance improvement

Surprisingly, this change does not seem to have resulted in a speedup.

**Comment by szhorvat** [comment]
This is basically done, closing.
