### ISSUE TITLE
R: cannot call igraph function in callbacks

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#571]
BEcause it frees all memory allocated by igraph.

**Comment by ludwikbukowski** [comment]
is it fixed? I got segmentation faults in simple scripts:
```
library('igraph')
g <- make_tree(10)
#g<- set_vertex_attr(g, "xx", value = 10:19)
f.in <- function(graph, data, extra) {
print(graph)
FALSE
}
tmp <- bfs(g, root=1, "out",callback=f.in)
```

**Comment by ntamas** [comment]
Most likely it is fixed; the latest R interface of igraph is version 1.1.2, released 2017-07-21, which is several years later than the date of the above commit. Please file a separate bug report for your issue in https://github.com/igraph/rigraph/issues

**Comment by ludwikbukowski** [comment]
Thank you for the response.
I just did it here: https://github.com/igraph/rigraph/issues/253
