### ISSUE TITLE
R: Implement GephiGraphStreamer

### ISSUE THREAD

**Issue by supersambo** [igraph/igraph#572]
as it's done for the python version http://igraph.sourceforge.net/doc/python/igraph.remote.gephi.GephiGraphStreamer-class.html

- [ ] Sending graphs to Gephi.
- [ ] Receiving graphs from Gephi.
- [ ] Manipulating graphs in Gephi.
- [ ] Connecting an R graph to a Gephi graph.

This last one is not straightforward, because R objects are immutable. But we can have an environment (or reference class) that contains an igraph graph.

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#15
