### ISSUE TITLE
Make 'make check' work on Cygwin and MSYS2

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#579]
`make check` does not work without extra setup in an MSYS2 terminal because the system cannot find the igraph `.dll`. The solution is to add the location of the igraph `.dll` to the `PATH`.

Since by default it is placed in `src/.libs`, one can e.g. do

```
export PATH=$PATH:`realpath src/.libs`
```

`make check` should do this automatically on this platform.

**Comment by szhorvat** [comment]
I hijacked this issue a bit (rewrote the description) based on my assumption about what it was originally about.

**Comment by szhorvat** [comment]
Closing in favour of #1501
