### ISSUE TITLE
Burt's constraint crashes

### ISSUE THREAD

**Issue by briatte** [igraph/igraph#580]
As discussed by email, [this commit](https://github.com/igraph/igraph/commit/ebc91f91) seems to crash the function to compute Burt's constraint (`constraint`). The crash is systematic when the `constraint` function is called from within another function.

**Comment by EmSyndio** [comment]
This Fix DOES NOT seem to be in the 0.7.1 release.
I just downloaded again and untar the tar.gz file and the lines 2575-2577 are still:
```
2575    /* add the indirect contributions, in-in, in-out, out-in, out-out */
2576    for (b=0; b<igraph_vector_size(&ineis_in); b++) {
2577      edge=(igraph_integer_t) VECTOR(ineis_out)[b];
```

**Comment by ntamas** [comment]
Indeed. Thanks for the heads up!

**Comment by EmSyndio** [comment]
could you cut a new release to include this change?
I'd just like to be able to pull and install from the official release and not have to git clone the source.

Thanks

**Comment by EmSyndio** [comment]
@ntamas @gaborcsardi 
any news about cutting a new release with the fixes?
I'd rather go from an official release than patch on build.
Thanks

**Comment by raldecoa** [comment]
@ntamas  @gaborcsardi 
Any updates on this?

**Comment by ntamas** [comment]
@raldecoa unfortunately neither I nor @gaborcsardi have too much spare time to spend on igraph any more -- I don't know about Gábor but I have moved on to other projects a few years ago and I wouldn't have the necessary permissions anyway to make a new release. I don't know what his plans are regarding the future of this project.

**Comment by szhorvat** [comment]
Closing as fixed in master. Release planned for the end of July.
