### ISSUE TITLE
R: exporter to D3.js

### ISSUE THREAD

**Issue by yrochat** [igraph/igraph#595]
I'd love to help implement an R function to do that http://coulmont.com/blog/2012/11/03/reseau-d3js/ I was wondering if it was worth it. And if you think it's the case, do you have advice, like: should I work on a C version (knowing that I haven't programmed in C for exactly 10 years) or work directly in R ?

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#17
