### ISSUE TITLE
igraph_random_sample error

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#596]
http://pave.igraph.org/job/igraph-c-test/label=osx/ws/build/igraph-0.8.0-pre+80.db14431/tests/testsuite.dir/230/testsuite.log

**Comment by szhorvat** [comment]
I wonder if this was similar to the mysterious nondeterministic failure we saw here: https://ci.appveyor.com/project/ntamas/igraph/builds/30228621/job/xxahc4hl3x81hb75

**Comment by ntamas** [comment]
Well, it was almost six years ago so it's hard to tell :)

**Comment by vtraag** [comment]
I can't even open the original link anymore, so indeed hard to tell :)

But @szhorvat has a point: sometimes there are some mysterious failures involving the random sampling, so perhaps good to keep this issue open to make sure we don't loose sight of it.
