### ISSUE TITLE
R:graph.difference does not work properly with self loops

### ISSUE THREAD

**Issue by rupea** [igraph/igraph#597]
In R (igraph_0.6.6), when calling graph.difference(g1,g2) if g1 has a self loop that is not present in g2, the self loop is added twice to the resulting graph.

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#18

**Comment by szhorvat** [comment]
Re-opening because the problem is in the C core, not the R interface.

**Comment by szhorvat** [comment]
@iosonofabio @ntamas If one of you has time, could you please look into this? I'd consider it a serious issue. Fabio, you were looking into Boolean graph operations for the Python interface (union, difference, etc.) so I thought it may be a good time.

**Comment by ntamas** [comment]
This is now fixed in the C core. The Python interface will be updated to refer to the fixed revision soon.
