### ISSUE TITLE
graph.dfs and graph.bfs in R package pass 0-based index to callback function

### ISSUE THREAD

**Issue by djhshih** [igraph/igraph#601]
In the R interface, graph.dfs and graph.bfs seem to be passing 0-based indices to the callback function instead of 1-based indices.
The results returned by the function uses 1-based indexing.

\> library(igraph)
\> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-unknown-linux-gnu (64-bit)
...
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] igraph_0.7.0

\> f <- function(graph, data, extra) print(data); 
\> g <- graph.tree(10);
\> tmp <- graph.dfs(g, root=1, "out", in.callback=f);
 vid dist 
   0    0
 vid dist
   1    1
 vid dist
   3    2
 vid dist
   7    3
 vid dist
   8    3
 vid dist
   4    2
 vid dist 
   9    3 
 vid dist 
   2    1 
 vid dist 
   5    2 
 vid dist
   6    2

\> tmp
...
$order
 [1]  1  2  4  8  9  5 10  3  6  7
...

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#19
