### ISSUE TITLE
`Graph.add_vertex()` should return created vertex object

### ISSUE THREAD

**Issue by aconrad** [igraph/igraph#602]
Why doesn't `Graph.add_vertex()` return the created vertex object? When I look at the source code it seems that there is a return statement but it always returns `None` for me.

It would be much nicer if I could do this:

```python
>>> import igraph
>>> g = igraph.Graph()
>>> v1 = g.add_vertex()
>>> v1
igraph.Vertex(<igraph.Graph object at 0x1591148>,0,{})
```

Rather than doing this crazy thing:

```python
>>> import igraph
>>> g = igraph.Graph()
>>> g.add_vertex()
>>> v1 = g.vs[g.vcount()-1]
```

The same should be done for `Graph.add_edge()` and their plural counter parts which would return a list of the created items, so:

```python
>>> import igraph
>>> g = igraph.Graph()
>>> v1, v2, v3 = g.add_verticies(3)
>>> v1
igraph.Vertex(<igraph.Graph object at 0x1f9e148>,0,{})
>>> v2
igraph.Vertex(<igraph.Graph object at 0x1f9e148>,1,{})
>>> v3
igraph.Vertex(<igraph.Graph object at 0x1f9e148>,2,{})
```

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/python-igraph#12

**Comment by geofurb** [comment]
This would be very nice to have. (And similar for edges- especially in multigraphs where you might otherwise run into a great deal of confusion.)
