### ISSUE TITLE
Adding vertices to graphs with vertex 'id' attribute causes corrupt GML files

### ISSUE THREAD

**Issue by alubbock** [igraph/igraph#604]
Quite an esoteric bug, but causes a few problems as it results in silently corrupted GML files. To reproduce, add at least two vertices to a graph which has a vertex 'id' attribute (as all graphs do when loading from GML). The new vertices have an 'id' of NA, which saves to an arbitrary integer. Try to load again from GML and an error occurs. I know that sounds pretty convoluted, so here's a minimal test case (verified with igraph 0.7.0):

```
# create any graph and save as gml
g <- graph.empty(3)
write.graph(g,file="/tmp/tmp.gml",format="gml")

# load the same graph - notice there's now a vertex id attribute
g <- read.graph(file="/tmp/tmp.gml",format="gml")

# add two new vertices
g <- g + vertex("abc") + vertex("def")
# notice the new vertices have NA for id attribute
V(g)$id

# save the graph as gml. In gml file, both new vertices have the same id
write.graph(g,file="/tmp/tmp.gml",format="gml")
# trying to reload this graph generates this error:
# Error in read.graph.gml(file, ...) : 
#  At foreign.c:1289 : Node 'id' not unique, Parse error
g2 <- read.graph(file="/tmp/tmp.gml",format="gml")
```

**Comment by szhorvat** [comment]
The GML writer will now skip using the `id` attribute if any of the values are NaN (NA is represented as a kind of NaN). Thus, it is no longer possible to _accidentally_ create an invalid ID vector in the manner described here.

However, the GML writer still does not check for duplicates, and therefore it is still possible that igraph would write an invalid GML file if duplicate `id` values were created deliberately.

Do we want to guard against duplicates? The procedure would be to make a copy of the `id` vector, sort it, and scan for consecutive duplicates. That's an O(V) memory overhead. I guess that's not too bad?

**Comment by szhorvat** [comment]
I just implemented the duplicate check.
