### ISSUE TITLE
Temporal graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#616]
From https://github.com/igraph/xdata-igraph/issues/11. See details here: https://github.com/igraph/igraph/wiki/Temporal-graphs
### Query operations
- [x] vcount &mdash; This should give the number of vertices at the given time point.
- [x] ecount &mdash; Number of edges at the given time point.
- [x] neighbors
- [x] is_directed
- [x] degree
- [x] edge
- [x] edges
- [x] incident
- [x] get_eid
- [x] get_eids
- [ ] get_eids_multi
### Graph creation and destruction
- [x] empty
- [x] empty_attrs
- [x] copy
- [ ] TODO: should copy consider `now`?
- [x] destroy
### Adding edges and vertices
- [x] add_vertices
- [ ] Should `add_vertices` consider `now` and add the vertices to the current time step?
- [x] add_edges
- [ ] Should `add_edges` consider `now` and add the edges to the current time step?
- [x] add_vertices_at
- [x] add_edges_at
- [x] handle attributes in add_vertices_at 
- [x] handle attributes in add_edges_at
### Delete operations:
- [x] delete_edges
- [x] delete_vertices
### Iterators

This will be tricky for the general case.
### Checks
- [ ] Checks in `igraph_create_temporal`
- [x] Checks in `igraph_add_vertices_at` are not needed, seemingly.
- [ ] Checks in `igraph_add_edges_at`
### Others
- [ ] History function, create a record of events from a temporal graph.
- [ ] The opposite, create a graph from a record of events.
- [ ] Write time labels to output files when saving the graph?
- [ ] Read time labels from output files when loading the graph?

**Comment by szhorvat** [comment]
Not planned at the moment. The work done so far is on https://github.com/igraph/igraph/tree/feature-temporal
