### ISSUE TITLE
Switch license to GPLv3

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#621]
Because we do have some code that is GPLv3......

**Comment by iosonofabio** [comment]
This one is more about decision making than coding, so let's bring it on.

Anyone knows what code we have that is GPL3?

Is anyone aware of non-GPL3 compatible projects using igraph?

**Comment by szhorvat** [comment]
There is no longer GPLv3 code that is always included. The only GPLv3-only piece is the bundled GLPK, which is optional and separated from the rest of the codbase. We are moving away from bundling GLPK towards linking to an external library. Thus, at this time, "GPLv2 or later" is fine.

However, some *binary* distributions may need to be GPLv3 if they have GLPK compiled in (e.g. Python wheels uploaded to PyPI).

**Comment by ntamas** [comment]
Guess we can close this then? Any objections?
