### ISSUE TITLE
Adding labels to vertices causes python crash

### ISSUE THREAD

**Issue by DSblizzard** [igraph/igraph#623]
This program crashes python 2.6:

def gr():
	from igraph import Graph
	res = Graph(0)
	res.add_vertices(1)
	res.vs["label"] = ['1']
	return res

def draw_graph():
	from igraph import plot
	gr1 = gr()
	layout = gr1.layout("fr")
	plot_ = plot(gr1, layout = layout)

draw_graph()

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/python-igraph#14
