### ISSUE TITLE
triad census overflow

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#625]
Like #497.

**Comment by iosonofabio** [comment]
I think this should be fine already as the triad census function uses floats throughout. The only exception I can see is possibly with the total number of total triplets, but even that case is casted as float early on. See `motifs.c`, line 1062 and thereabout:

```C
  total = ((igraph_real_t)vc) * (vc-1);
  total *= (vc-2);
  total /= 6;
```

Notice that this is different from the *dyad census* function, which uses and returns integers which can overflow. In theory, conversion to float might lose precision but I doubt this is an issue in practice.
