### ISSUE TITLE
igraph c tutorial bug

### ISSUE THREAD

**Issue by keisuke-nakata** [igraph/igraph#626]
I found a small bug on the igraph c tutorial (http://igraph.org/c/doc/igraph-tutorial.html).
A tutorial code on the lesson 3, it contains:

```
 igraph_closeness(&graph, &result, igraph_vss_all(), IGRAPH_ALL,
                      /*weights=*/ 0);
```

but the number of arguments is too few to function "igraph_closeness", 
so it should be:

```
 igraph_closeness(&graph, &result, igraph_vss_all(), IGRAPH_ALL,
                      /*weights=*/ 0, /*normalized=*/ 1);
```

**Comment by alexperrone** [comment]
Looks like it was fixed in doc/tutorial.xml, but I just ran across same problem when viewing http://igraph.org/c/doc/igraph-tutorial.html and http://igraph.org/c/doc/igraph-docs.pdf. So these need to be updated.
