### ISSUE TITLE
confusing error message after incorrect use of vertices

### ISSUE THREAD

**Issue by kasterma** [igraph/igraph#635]
I am fairly new to igraph (using it from R).  After quite a long debugging session yesterday I found the problem which is simplified in the below R session.

    > gg <- graph.empty() + vertices(c(1,2,3,4)) + edges(c("1","2","3","4"))
    > gg+gg
    Error in `+.igraph`(g, setdiff(uninames, V(g)$name)) : 
      Cannot add unknown type to igraph graph

Corrected session

    > gg <- graph.empty() + vertices(as.character(c(1,2,3,4))) + edges(c("1","2","3","4"))
    > gg + gg
    IGRAPH DN-- 4 2 -- 
    + attr: name (v/c)

Turns out vertices just wraps its arguments in a list with attribute class set to "igraph.vertex".  And then the fact that the vertex names are integers in stead of characters is only noticed later when doing the graph union (in the context I was working in there were more graphs adding to the space of things to examine for errors).

I am not familiar enough with the code to understand the impact, but would suggest adding an assertion or build in as.character to vertices.

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#24
