### ISSUE TITLE
Seg Fault When Importing scipy

### ISSUE THREAD

**Issue by Lab41PaulM** [igraph/igraph#638]
There appears to be an issue with importing scipy separately into projects that use igraph when scipy is imported after the igraph import.

The following code causes a seg fault:

```
import igraph
import scipy

f = "test.graphml"
G = igraph.Graph.Erdos_Renyi(n=20, m=30)
G.write_graphml(f)
G_ = igraph.Graph.Read_GraphML(f)
layout = G_.layout("fr") # Fruchterman-Reingold layout
igraph.plot(G_, layout=layout)
```

However, if you swap the import order it does not cause a seg fault.

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/python-igraph#15
