### ISSUE TITLE
Consider edge directions in graph.knn

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#643]
BEcause right now they are ignored.

**Comment by szhorvat** [comment]
Related: https://github.com/igraph/igraph/issues/987

**Comment by iosonofabio** [comment]
hmm... what function in the C code is this referring to? Or is it some R/Python interface, in which case we should move the issue to the other repo?

**Comment by szhorvat** [comment]
@iosonofabio `igraph_avg_nearest_neighbor_degree` I think.

**Comment by vtraag** [comment]
@iosonofabio, will you take this? If not, I'll take it.

**Comment by iosonofabio** [comment]
Please take it, these days are tough for me and I don't want to slow down the 0.8 deadline

**Comment by vtraag** [comment]
There are essentially two things to be done:

1. Implementation of the weighted version in `igraph_i_avg_nearest_neighbor_degree_weighted` to respect the definition provided by [Barrat et. al](10.1073/pnas.0400087101), Eq. (6).
2. Implementation of the directionality of the nearest neighbours.

I think point 1 should be clear. For point 2 I think we should allow to specify both which neighbours to consider (in- or out-neighbours) and which degree of the neighbours (in- or out-degree). This allows you, for example, to check the average in-degree of the out-neighbours. The same should of course apply to the weighted version. Do you agree with this approach?

**Comment by ntamas** [comment]
Sounds good to me!
