### ISSUE TITLE
Average Linkage Minimum Spanning Trees

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#648]
Bill Rea wrote:

> I'm writing to you because you are the author of the R package igraph. I've attached a recent paper on Average Linkage Minimum Spanning Trees (ALMST). These do not appear to be implemented in the current version of igraph, but I think they would make a useful addition if you are continuing work on the package.
> 
> SPANNING TREES AND BOOTSTRAP
> RELIABILITY ESTIMATION IN
> CORRELATION-BASED NETWORKS
> 
> MICHELE TUMMINELLO, CLAUDIA CORONNELLO,
> FABRIZIO LILLO∗,†, SALVATORE MICCICHE` † and
> ROSARIO N. MANTEGNA†
> 
> International Journal of Bifurcation and Chaos, Vol. 17, No. 7 (2007) 2319–2329

**Comment by A5403895** [comment]
Is there any package available for this method?
