### ISSUE TITLE
interpretation of hub/auth scores

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#649]
Matthew Galati matthew.galati@gmail.com   Mon, Dec 2, 2013 at 3:30 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
I am considering this small directed graph. 

The results score node 1 as the dominate hub and the rest of the nodes with value 0 (i.e., no' hubness'). This seems odd to me. For example, node 2, has outlinks to 3 different nodes (1,4, and 7). So, I would expect it to have some relative level of hubness.

> g <- graph.empty()
> 
> g <- g+vertices(1,2,3,4,5,6,7)
> 
> g <- g+edge("1","2")
> 
> g <- g+edge("1","3")
> 
> g <- g+edge("1","5")
> 
> g <- g+edge("1","6")
> 
> g <- g+edge("2","1")
> 
> g <- g+edge("2","4")
> 
> g <- g+edge("3","1")
> 
> g <- g+edge("5","1")
> 
> g <- g+edge("2","7")
> 
> E(g)

Edge sequence:

[1] 1 -> 2

[2] 1 -> 3

[3] 1 -> 5

[4] 1 -> 6

[5] 2 -> 1

[6] 2 -> 4

[7] 3 -> 1

[8] 5 -> 1

[9] 2 -> 7

> hub.score(g,scale=FALSE)$vector

```
    1         2         3         4         5         6         7 
```

0.5733822 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 

---

igraph-help mailing list
igraph-help@nongnu.org
https://lists.nongnu.org/mailman/listinfo/igraph-help

Tamás Nepusz ntamas@gmail.com    Mon, Dec 2, 2013 at 5:15 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Hi Matthew,

Yes, that’s odd indeed. Let me double-check our code; I suspect an ARPACK convergence problem here but I’m not sure (and I don’t know why there’s no warning if ARPACK indeed fails to converge).
## 

T.
[Quoted text hidden]

> ---
> 
> igraph-help mailing list
> igraph-help@nongnu.org (mailto:igraph-help@nongnu.org)
> https://lists.nongnu.org/mailman/listinfo/igraph-help

---

igraph-help mailing list
igraph-help@nongnu.org
https://lists.nongnu.org/mailman/listinfo/igraph-help
Tamás Nepusz ntamas@gmail.com    Mon, Dec 2, 2013 at 6:39 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Hi Matthew,

So, the whole story is as follows. igraph uses ARPACK to find the dominant eigenvalue of the A_A’ and A’_A matrices (where A is the adjacency matrix) and the corresponding eigenvectors in order to obtain the hub and authority scores. This works fine in most cases - however, in your case, igraph fails because the dominant eigenvalue (4 in your case) has two corresponding eigenvectors, one of which is the one you see and the other is the one you would expect intuitively. For what it’s worth, here are the two eigenvectors (normalized conveniently):

v1 = [1 0 0 0 0 0 0]
v2 = [0 2 1 0 1 0 0]

It is easy to confirm that both are valid eigenvectors, and it is also easy to confirm that both satisfy the HITS equations. Suppose you start out from v1 as the hub scores. The authority score of each vertex is then the sum of the hub scores of its predecessors, so we get:

w1 = [0 1 1 0 1 1 0]

since nodes 2, 3, 5 and 6 are successors of node 1 and node 1 is the only node with a nonzero hub score. Now, let us calculate the hub scores again from the authority scores we have obtained above. In order to do that, we have to take the sum of the authority scores of the successors for each node. The result is:

v1’ = [4 0 0 0 0 0 0]

This is indeed 4 times v1, so v1 is an eigenvector of A*A’ with a corresponding eigenvalue of 4. In other words, igraph is not “wrong”, it is just that your graph has a structure for which the hub and authority scores are not well-defined.
## 

T.
[Quoted text hidden]
Matthew Galati matthew.galati@gmail.com   Tue, Dec 3, 2013 at 6:58 AM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Cc: Help for igraph users igraph-help@nongnu.org
Yes. I have even reading up on this topic. I think the hub/auth scores assume a unique dominant eigenvalue - which is not true on this case (and many others I have seen). I am trying to see if anything can be done. I think that, by adding epsilon to all matrix coefficients, this will ensure that the eigenvalue is unique. This idea does lead to sensible results in the cases I have looked at. It forces the matrix to be positive, which implies a unique dominant eigenvalue. Unfortunately, this makes A fully dense - so, I am hoping there is a better way.

Sent from my iPhone
[Quoted text hidden]
Gábor Csárdi csardi.gabor@gmail.com Tue, Dec 3, 2013 at 7:09 AM
To: Help for igraph users igraph-help@nongnu.org
A dense matrix is not necessarily a problem. All we need is that the
matrix-matrix product and matrix-vector product operations are easy,
which holds if your matrix is sparse + constant.

However, I don't think this would work in practice. Yes, in theory the
eigenvalue is positive and unique, but in practice, if epsilon is
small, then the top two eigenvalues will be close, causing numerical
instabilities.

(I must admit, I had no time to follow through Tamas's argument, so
fixme. Thanks.)

Gabor
[Quoted text hidden]
Matthew Galati matthew.galati@gmail.com   Tue, Dec 3, 2013 at 9:20 AM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Yes. I imagine this might cause numeric instability. But, this is better than getting results that make no sense conceptually. I suggest only doing that if you find that the leading eigenvalue is non-unique (as a backup plan).
[Quoted text hidden]

---

igraph-help mailing list
igraph-help@nongnu.org
https://lists.nongnu.org/mailman/listinfo/igraph-help

Gábor Csárdi csardi.gabor@gmail.com Tue, Dec 3, 2013 at 9:29 AM
To: Help for igraph users igraph-help@nongnu.org
In your experiments aren't the new eigenvalues close to the old double
eigenvalue? I would think that the spectrum is a continuous function
of epsilon, and probably the new eigenvalue is close the old double
one. Maybe the eigenvectors are close, too.

To me it would probably make more sense to report that the results are
ill-defined, and just return them.

We can also try searching for literature about this, or ask Jon
Kleinberg what he thinks.

G.
[Quoted text hidden]
Matthew Galati matthew.galati@gmail.com   Tue, Dec 3, 2013 at 11:21 AM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Yes - the eigenvalues are close when adding epsilon, but you do now have a strictly dominant one. And, the resulting eigenvectors seem to make sense in the hub/auth context. I didn't find anything about this in the literature - except for the assumption that a unique dominant eigenvalue exists - which, obviously is not true in many cases. Making the matrix a 'positive matrix' forces this to be true. I am no linear algebra expert - so I might be doing some hand-waving here.
[Quoted text hidden]

---

igraph-help mailing list
igraph-help@nongnu.org
https://lists.nongnu.org/mailman/listinfo/igraph-help

Tamás Nepusz ntamas@gmail.com    Tue, Dec 3, 2013 at 2:43 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org

> Yes - the eigenvalues are close when adding epsilon, but you do now have a strictly dominant one.

Unfortunately there’s no easy way to detect whether the multiplicity of an eigenvalue is >1 due to numerical inaccuracies. In the case of your graph, it happened to be easy because the multiple eigenvalue was integer, but this is not true in the general case and it is hard to decide whether two eigenvalues are the same (but look different due to inaccuracies) or they are indeed different (but very close to each other).

That’s one thing.

The other thing is that as soon as you have an eigenvalue with multiplicity >1, then the eigenvectors corresponding to this eigenvalue define a subspace within which _any_ vector that is a linear combination of the eigenvector basis will also be an eigenvector. Suppose that you have an eigenvalue x and two corresponding eigenvectors: v1 and v2. By definition, it follows that A_v1 = x_v1 and A_v2 = x_v2. But then it also follows that any vector v3 = a_v1 + b_v2 is also an eigenvector since A_v3 = A_(a_v1 + b_v2) = a_A_v1 + b_A_v2 = a_x_v1 + b_x_v2 = x_(a_v1 + b_v2) = x_v3. Therefore, as soon as you have an eigenvalue with multiplicity > 1, you have an _infinite_ number of solutions; in other words, an infinite number of possible hub scores. Actually, I noticed that yesterday when I was testing your graph: I temporarily modified igraph’s code to use a random starting vector in the iteration that searches for the eigenvector (instead of the degree vector of the graph), and I noticed that the results were not consistent between runs - this was because the algorithm converged to a different eigenvector in the eigenspace spanned by the two bases.

> Making the matrix a 'positive matrix' forces this to be true. I am no linear algebra expert - so I might be doing some hand-waving here.

Actually, it is enough for the matrix to be a “primitive matrix”, which means that there exists some integer k for which A^k (A to the power of k) contains positive numbers only. Since the intersection of row i and column j in A^k simply counts the number of shortest paths from i to j, it basically means that your graph has to be strongly connected; in other words, you must be able to get from any point to any other point in a finite number of steps. This would ensure the uniqueness of the hub scores.

T.
[Quoted text hidden]
Gábor Csárdi csardi.gabor@gmail.com Tue, Dec 3, 2013 at 2:48 PM
To: Help for igraph users igraph-help@nongnu.org
Agreed. This said, adding a small (not epsilon, but rather 0.1 or
something like that) constant to the graph still makes sense, the same
way as it does for PageRank on graphs that are not strongly connected.
But then this would be a parameter, like for PR.

It is the small epsilon, added only if double eigenvalues are
detected, that I am against.

Gabor
[Quoted text hidden]
Matthew Galati matthew.galati@gmail.com   Tue, Dec 3, 2013 at 3:25 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org

Unfortunately there’s no easy way to detect whether the multiplicity of an eigenvalue is >1 due to numerical inaccuracies. In the case of your graph, it happened to be easy because the multiple eigenvalue was integer, but this is not true in the general case and it is hard to decide whether two eigenvalues are the same (but look different due to inaccuracies) or they are indeed different (but very close to each other).

I would just assume (heuristically) that if the first two eigenvalues are within epsilon (some tolerance, like e-8), then it has multiplicity>1 and you need to do something else. Heuristically, that seems to work for what I have tried.

The other thing is that as soon as you have an eigenvalue with multiplicity >1, then the eigenvectors corresponding to this eigenvalue define a subspace within which _any_ vector that is a linear combination of the eigenvector basis will also be an eigenvector. Suppose that you have an eigenvalue x and two corresponding eigenvectors: v1 and v2. By definition, it follows that A_v1 = x_v1 and A_v2 = x_v2. But then it also follows that any vector v3 = a_v1 + b_v2 is also an eigenvector since A_v3 = A_(a_v1 + b_v2) = a_A_v1 + b_A_v2 = a_x_v1 + b_x_v2 = x_(a_v1 + b_v2) = x_v3. Therefore, as soon as you have an eigenvalue with multiplicity > 1, you have an _infinite_ number of solutions; in other words, an infinite number of possible hub scores. Actually, I noticed that yesterday when I was testing your graph: I temporarily modified igraph’s code to use a random starting vector in the iteration that searches for the eigenvector (instead of the degree vector of the graph), and I noticed that the results were not consistent between runs - this was because the algorithm converged to a different eigenvector in the eigenspace spanned by the two bases.

Yes - understood. So, if we have multiplicity>1, we really need to do something else or the results won't make much sense.

> Making the matrix a 'positive matrix' forces this to be true. I am no linear algebra expert - so I might be doing some hand-waving here.

Actually, it is enough for the matrix to be a “primitive matrix”, which means that there exists some integer k for which A^k (A to the power of k) contains positive numbers only. Since the intersection of row i and column j in A^k simply counts the number of shortest paths from i to j, it basically means that your graph has to be strongly connected; in other words, you must be able to get from any point to any other point in a finite number of steps. This would ensure the uniqueness of the hub scores.

Yes - but you will hardly ever have a strongly connected graph. This was is not. 

The point of hub/auth is to produce a ranking - so adding some small constant should fix the multiplicity, give a valid ranking, and hopefully not cause any other numeric issues. It would need some experimentation to test this.

---

igraph-help mailing list
igraph-help@nongnu.org
https://lists.nongnu.org/mailman/listinfo/igraph-help

Matthew Galati matthew.galati@gmail.com   Tue, Dec 3, 2013 at 3:28 PM
Reply-To: Help for igraph users igraph-help@nongnu.org
To: Help for igraph users igraph-help@nongnu.org
Agreed. This said, adding a small (not epsilon, but rather 0.1 or
something like that) constant to the graph still makes sense, the same
way as it does for PageRank on graphs that are not strongly connected.
But then this would be a parameter, like for PR.

It is the small epsilon, added only if double eigenvalues are
detected, that I am against.

Gabor

Hmm. OK. That is also an option - to always add some constant. This whole thread might be a good topic for Prof Kleinberg to consider. I didn't see anything about this in the original paper - I might have missed something in the proofs.

**Comment by szhorvat** [comment]
I fully agree with Tamás's analysis, closing.
