### ISSUE TITLE
modularity() in the R interface does not warn about invalid community IDs

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#652]
Community IDs in the R interface start from 1, but igraph gives no warning if someone accidentally submits zero as a community ID. E.g. the following code yields `FALSE`:

```
library(igraph)
g <- graph.star(6, mode="undirected")
modularity(g, c(0,0,0,0,0,1)) == modularity(g, c(1,1,1,1,1,2))
```

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#27
