### ISSUE TITLE
as.undirected() has problems with multiple edges

### ISSUE THREAD

**Issue by g-chi** [igraph/igraph#667]
The graph is
a b 1
a b 2
b a 3
a a 4
a a 2

g = read.graph('this_file.ncol', format = 'ncol', directed = TRUE)
when I use the as.undirected(g,mode="collapse"), I get
a a 7
a b 5

What I expect is
a a 6
a b 6

So as.undirected() has problems with multiple edges.
http://stackoverflow.com/questions/25030345/what-is-the-mode-collapse-in-as-undirected-function

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#35
