### ISSUE TITLE
Using Cairocffi

### ISSUE THREAD

**Issue by remkoning** [igraph/igraph#669]
Installing cairocffi using pip is easy as pie but since it is called as "import cairocffi" it doesn't link up automatically with the plotting code which uses "import cairocffi" (drawing/**init**.py, drawing/graph.py, drawing/text.py).

Would be better if the code also tried a "import cairocffi as cairo" before returning plotting not available.

**Comment by Isaquedanielre** [comment]
Hi, I have trying to use igraph in anaconda python 3.4. 
After install and try to run a igraph tutorial I get the same message "TypeError: plotting not available".
My python has: 
pycairo 1.10.0
cairocffi 0.7.2
igraph 0.7.1    <module 'igraph' from 'C:\\Users\\B2046470858\\AppData\\Local\\Continuum\\Conda_343\\lib\\site-packages\\igraph\\__init__.py'>

Any suggestion?

**Comment by ntamas** [comment]
Try running `import cairo` from the Anaconda Python console. If the import fails, then you have not installed Cairo properly.
