### ISSUE TITLE
VertexDendrogram.as_clustering() sometimes fails?

### ISSUE THREAD

**Issue by nadesai** [igraph/igraph#675]
Most of the time `VertexDendrogram.as_clustering()` has worked fine for me, but I recently encountered a VertexDendrogram that persistently fails when I try to call `as_clustering()` on it. The traceback is 

```python
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-14-f8101bd3b52b> in <module>()
----> 1 dendrogram.as_clustering()

/usr/local/lib/python3.4/site-packages/igraph/clustering.py in as_clustering(self, n)
    957         idgen = UniqueIdGenerator()
    958         membership = community_to_membership(self._merges, num_elts, \
--> 959                                              num_elts - n)
    960         membership = [idgen[m] for m in membership]
    961         return VertexClustering(self._graph, membership,

InternalError: Error at community.c:769: `steps' to big or `merges' matrix too short, Invalid value
```

which comes from [src/community.c#L769](https://github.com/igraph/igraph/blob/master/src/community.c#L769).

The VertexDendrogram in question is the result of calling `community_edge_betweenness()` on the network science collaboration graph, available from the "Coauthorships in network science" dataset available at http://www-personal.umich.edu/~mejn/netdata/.

Is this failure behavior expected? Is is impossible to convert some VertexDendrograms into clusterings?

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/python-igraph#17
