### ISSUE TITLE
igraph_arpack_rnsolve.c test case sometimes fails when an external ARPACK library is used

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#678]
It is not really a failure; some ARPACK implementations (such as the one used in Debian Linux when compiling the igraph package from source) do not respect the `nev` setting; they will return _at least_ `nev` eigenvalues but they always seem to return both eigenvalues from a conjugate complex pair, so one may end up with more eigenvalues than what was requested. The test case does not account for this. (For what it's worth, the expected output of the test case anticipates that `nev` is respected for the number of eigenvalues but not for the number of eigenvectors).

There are two possible fixes that we could apply here: either we make `igraph_arpack_rnsolve` resize the result vector (and the matrix of eigenvectors as well) such that igraph does not return more than `nev` eigenvalues and/or eigenvectors even if ARPACK returned more, or we let this quirk of ARPACK leak through the abstraction and fix the test case instead.

Comments are appreciated (ping @gaborcsardi).

**Comment by orlitzky** [comment]
We're hitting this on Gentoo, too, where users can choose to run the test suite before installing a package. Currently we've "fixed" it by disabling the test suite entirely which works but is not optimal =)

**Comment by nullr0ute** [comment]
We see this on non x86 architectures on Fedora too (aarch64/ppc64/ppc64le/s390x)

**Comment by rdauria** [comment]
Hello, I am not sure if this is related but on a CentOS 6.10 I get:

```
Failed tests:
igraph 0.7.1 test suite: igraph test groups:

 NUM: FILE-NAME:LINE     TEST-GROUP-NAME
      KEYWORDS

  26: types.at:151       Sparse matrix, ARPACK eigensolver (igraph_sparsemat_t): 
      sparse matrix igraph_sparsemat_t arpack
 195: arpack.at:45       Solving linear systems with LU factorization (igraph_lapack_dgesv):
      lapack dgesv solve lu factorization
 198: arpack.at:63       Non-symmetric ARPACK solver (igraph_arpack_rnsolve):
      arpack eigenvalue eigenvector eigen eigenproblem non-symmetric
```
I have configure igraph with:

```.
/configure --with-external-blas=/u/local/compilers/intel/18.0.2/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so --with-external-lapack=/u/local/compilers/intel/18.0.2/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so --prefix=/u/local/apps/igraph/0.7.1/gcc-4.9.3
```
Suggestions?

**Comment by ntamas** [comment]
Can you post the contents of `testsuite.dir` for the failed test cases somewhere? In the best case, these are totally harmless - maybe the BLAS/LAPACK/ARPACK implementations that you are using return the eigenvalues or eigenvectors in a different order than what igraph expects, or there are small numeric errors in the output. In the worst case, this could be a genuine bug in either igraph or in the ARPACK implementation.

**Comment by rdauria** [comment]
Thanks for looking into this, I have attached the content of directory below:
[testsuite.dir.zip](https://github.com/igraph/igraph/files/3370209/testsuite.dir.zip)

Also, I noticed that when trying to use python-igraph over a remote jupyter notebook I get an error (see below) which I do not get if I run directly on the remote host (only during the plotting).

```
TypeErrorTraceback (most recent call last)
/u/local/apps/python/3.7.2/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/.local/lib/python3.7/site-packages/python_igraph-0.7.1.post6-py3.7-linux-x86_64.egg/igraph/drawing/__init__.py in _repr_svg_(self)
    350         # No idea why this is needed but python crashes without
    351         context.show_page()
--> 352         surface.finish()
    353         # Return the raw SVG representation
    354         return io.getvalue().encode("utf-8")

TypeError: a bytes-like object is required, not 'str'

<igraph.drawing.Plot at 0x2acf39112f28>
```

The code to reproduce the error is the example in:

https://louvain-igraph.readthedocs.io/en/latest/intro.html

This seems to be related to python3 strings are Unicode, but when transmitting on the network, the data needs to be bytes strings instead. Any idea of how to get around this? 

My apologies if this is not the correct forum to post python-igraph issues.

Thanks

**Comment by vtraag** [comment]
Regarding the latter problem, issue https://github.com/igraph/python-igraph/issues/102 is probably related. If not, and the proposed solution doesn't solve it, could you open another issue in the `python-igraph` issue tracker?

**Comment by ntamas** [comment]
Okay, I've checked the test logs. Test 198 seems to be okay - the test fails because some eigenvectors are returned with a multiplicative factor of -1 compared to the expected test output.

Regarding test 195: here we are intentionally trying to solve a linear system that is singular so the LU factorization step should fail. This is what the test case expects - but in practice, the factorization step does not fail and therefore the test fails. The input matrix A is obviously singular because we first fill it with random numbers and then copy one of its rows to another, but it could be the case that numeric inaccuracies prevent LAPACK from recognizing it.

Test 26 seems to be a clear failure, but here the test case is doing something that might not entirely be supported by all BLAS / LAPACK / ARPACK implementations: we are essentially reusing an `igraph_arpack_options_t` object between invocations of the ARPACK solver. It could be the case that the "official" implementation supports this but alternative implementations like Intel's don't.

@vtraag: do you guys have time to debug this a bit further? I'm a bit busy in the following days.

**Comment by vtraag** [comment]
@ntamas I can try to take a look next Friday.

**Comment by vtraag** [comment]
I finally got around to compiling `igraph` correctly with external libraries and running `make check`. It turned out that some previously compiled libraries were still in the source directory (check `find . -iname lib*.*a`). Removing the appropriate libraries (for which I wanted to use the external version) solved this.

The configuration is
```
./configure --enable-debug --prefix=$HOME --with-external-blas --with-external-lapack
```

With the current master (version `0.8.0-pre+ae368a00` from ae368a006f2aa9589569948da2a326708ebc501c) the following tests failed:

```
 128: layout.at:66       Merging layouts 2 (igraph_i_layout_merge):
      layout merge dla
 242: scg.at:36          Solving the SCG problem, stochastic matrix (igraph_scg_grouping) :
      scg spectral coarse graining grouping stochastic
 245: scg.at:54          SCG semi-projectors, stochastic (igraph_scg_semiprojectors) :
      scg spectral coarse graining semi-projectors stochastic
 248: scg.at:71          SCG of a graph, stochastic matrix (igraph_scg) :
      scg spectral coarse graining
 259: embedding.at:23    Adjacency spectral embedding (igraph_adjacency_spectral_embedding): 
      adjacency spectral embedding
```
See [testsuite.log](https://github.com/igraph/igraph/files/3576461/testsuite.log) for details.

This is using `lapack` and `blas` from `openblas 0.3.5+ds-2`. 

I have not yet looked at the problems in detail, I just wanted to report them for now.

**Comment by vtraag** [comment]
I have been looking into the failures that I mentioned previously (in https://github.com/igraph/igraph/issues/678#issuecomment-528084702) a bit more. 

In particular, I have looked into the `igraph_adjacency_spectral_embedding`. It seems that the differences are due to differences in returned matrices of the singular value decomposition. These are also not uniquely determined if I am not mistaken, so I am not sure why we would expect the tests to always return the same results. It might well be possible that different versions of `ARPACK` would return different results, right? Perhaps different platforms would also return different results (even for the same code)? Perhaps we should then update these tests to reflect this possible variation? Or is there some way to force identical results always?

I am not 100% sure if the other failures are due to the same problem, but glancing over them, they seem related.

**Comment by iosonofabio** [comment]
Maybe this is just a rounding error, but if not: SVD is not unique per se so people put up some convention to deal with these issues.

1. The order of singular values is usually reported highest to lowest (can't be less than 0) which fixes the order of columns in the U and V matrices of left and right singular vectors too
2. If two or more singular values are the same and > 0, linear combination of their left/right singular vectors are also singular vectors. This phenomenon (degeneracy) can lead to different results which are all equivalent. If the gap between two adjacent singular values is nonzero but very small, the same can happen in a computer of course. If memory serves, in fact this does tend to happen for large matrices once we reach the last bunch of "almost zero" singular values
3. Even though each non-degenerate singular value is unique, you can still change sign of a left singular vector and simultaneously of the right singular vector and things are fine. I'm not sure what convention is in place in ARPACK to deal with this, could be something like "the first coordinate of each left singular vector must be >= 0".

or maybe it's just a rounding error on different platform in the end...

**Comment by vtraag** [comment]
As far as I understand, even for the same order of singular values, the U and V matrices are not uniquely determined, and have some freedom of alternative representations, also beyond sign flipping it seems. Perhaps we could only check the singular values themselves, instead of the singular vectors.

**Comment by iosonofabio** [comment]
I had this problem before and gave up on the vectors like you are suggesting. However that was a small personal project while igraph should satisfy a higher standard so I'm debating. What other things can change except for a sign (or phase, if complex numbers) and degenerate subspaces?

**Comment by vtraag** [comment]
Sorry, I think you are right, I had in mind the degenerate subspaces. I'll try to see if that relates to the problem.

**Comment by vtraag** [comment]
Yes, indeed, the problem for `igraph_adjacency_spectral_embedding` relates to the degenerate subspaces. There are 4 columns requested, and the fourth singular value has a multiplicity of 4. The first 3 columns only have sign differences, but the fourth column contains quite different values. 

This will be difficult to correct I think. Regarding the sign, we could of course simply output the absolute values, but the problem with degenerate singular values seems much more difficult to address. It would require some canonical representation, but I think this would be pushing it too far. Simply checking the singular values themselves sounds more reasonable to me.

**Comment by iosonofabio** [comment]
Yep, agreed to check just the values then.

An easy fix would be to check directly whether the vectors proposed are singular by doing the matrix multiplications:

VM = US

But I think checking just the trace of S will be fine.

Cheers,
Fabio

**Comment by szhorvat** [comment]
The discussion here lost focus. Is there a clear remaining TODO item or issue here?

**Comment by ntamas** [comment]
I don't think there is so I'm closing the issue.
