### ISSUE TITLE
python-igraph fails to build due to -Werror=declaration-after-statement

### ISSUE THREAD

**Issue by nadesai** [igraph/igraph#679]
I'm inside Docker running debian jessie/sid and trying to build python-igraph, which is persistently failing with this error message:

```
  gcc -pthread -Wno-unused-result -Werror=declaration-after-statement -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iigraphcore/include -I../../build/include -I../../include -I/usr/local/include/igraph -I/usr/include/igraph -I/usr/local/include/python3.4m -c src/filehandle.c -o build/temp.linux-x86_64-3.4/src/filehandle.o
    src/filehandle.c: In function 'igraphmodule_filehandle_init':
    src/filehandle.c:38:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
         int fp;
         ^
    cc1: some warnings being treated as errors
    error: command 'gcc' failed with exit status 1
```

It seems the issue is at [src/filehandle.c#38](https://github.com/igraph/igraph/blob/master/interfaces/python/src/filehandle.c#L38), where the declaration occurs after the line `handle->need_close = 0;` which I believe is not C89-compliant and is thus getting flagged by `-Werror=declaration-after-statement`. Since this installation is occurring with pip I don't believe I can turn off this flag - is there any way to work around this or fix it?

**Comment by djuhaeri** [comment]
I have the same problem and it's for me still unclear how to tackle this problem.
Can some on pointed me out ?

**Comment by ntamas** [comment]
Sorry, I made a booboo in the source code for 0.7.1 so it did not compile in C90 mode. Please try downloading the source for 0.7.1-1 which I have just uploaded to PyPI.

**Comment by djuhaeri** [comment]
First of all I like to thank you Tamas, for a fast response. 
I still haven't succeed to get it compile. Yes I have a custom path for python and I have adjusted
the setup.py.  The error i got 

---
Cannot find the C core of igraph on this system using pkg-config.
We will now try to download and compile the C core from scratch.
Version number of the C core: 0.7.1-1

Version 0.7.1-1 of the C core of igraph is not found among the nightly builds.
Use the --c-core-version switch to try a different version.

Could not download and compile the C core of igraph.

WARNING: we were not able to detect where igraph is installed on
your machine (if it is installed at all). We will use the fallback
library and include pathss hardcoded in setup.py and hope that the
C core of igraph is installed there.

If the compilation fails and you are sure that igraph is installed
on your machine, adjust the following two variables in setup.py
accordingly and try again:

- LIBIGRAPH_FALLBACK_INCLUDE_DIRS
- LIBIGRAPH_FALLBACK_LIBRARY_DIRS

Build type: dynamic extension                                    
Include path: /public/public_linux/slc6_x64/python/include/python3.4m
Library path: /public/public_linux/slc6_x64/python/lib/python3.4/site-packages/igraph
Linked dynamic libraries: igraph
Linked static libraries: 
Extra compiler options: 
Extra linker options: 
building 'igraph._igraph' extension
creating build/temp.linux-x86_64-3.4
creating build/temp.linux-x86_64-3.4/src
gcc -pthread -Werror=declaration-after-statement -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/public/public_linux/slc6_x64/python/include/python3.4m -I../../build/include -I../../include -I/usr/local/include/igraph -I/usr/include/igraph -I/public/public_linux/slc6_x64/Python-3.4.1/Include -I/public/public_linux/slc6_x64/Python-3.4.1 -c src/attributes.c -o build/temp.linux-x86_64-3.4/src/attributes.o
In file included from src/attributes.c:24:
src/attributes.h:27:31: error: igraph_attributes.h: No such file or directory
src/attributes.h:28:29: error: igraph_datatype.h: No such file or directory
xxx
xxx

**Comment by djuhaeri** [comment]
It looks like that I missed the igraph_*.h files & indeed i can't find them.

**Comment by ntamas** [comment]
This is due to the fact that the Python installer has to download the source code of the C library (since you haven't compiled and installed the C core separately), but it cannot find a matching C library on the Internet. Unfortunately this happens because I was "forced" by PyPI to release a new version of the Pyhton interface with version number 0.7.1-1 (it did not allow me to "fix" the previous release), and of course there is not C core with version number 0.7.1-1.

The solution is to install the Python interface using pip as follows:

    pip install python-igraph --install-option="--c-core-version=0.7.1"

This will force the installer script of the Python interface to look for version 0.7.1 of the C core. I will probably fix this in an upcoming 0.7.1-2 release.

**Comment by djuhaeri** [comment]
It works & thanks a lot once again.

**Comment by ntamas** [comment]
For the record: python-igraph 0.7.1-2 is now out and it should not have this issue.

**Comment by eleftherioszisis** [comment]
I fail to install python-igraph due to the default treatment of warnings as errors. In this case it is ```Werror=format-security``` and ```printf``` that cancels the compilation of the c core.

I'm on RedHat/Santiago/6.9 using nix. In the past I had no difficulty pip installing the library.

``` 
pip install python-igraph==0.7.1-6
```

```
    make  all-recursive
    make[1]: Entering directory `/tmp/pip-build-aY9bg_/python-igraph/tmp/igraph.EDcZHF/igraph-0.7.1'
    Making all in src
    make[2]: Entering directory `/tmp/pip-build-aY9bg_/python-igraph/tmp/igraph.EDcZHF/igraph-0.7.1/src'
    gcc -fPIC -I/nix/store/xqn64vrns4ab2y9bq8nm3jib1mw9wm7h-libxml2-2.9.7-dev/include/libxml2 -DNO_FPINIT f2c/arithchk.c -lm -o f2c/arith || \
    	gcc -DNO_LONG_LONG -fPIC -I/nix/store/xqn64vrns4ab2y9bq8nm3jib1mw9wm7h-libxml2-2.9.7-dev/include/libxml2 -DNO_FPINIT f2c/arithchk.c \
    		-Wall -lm -o f2c/arith
    f2c/arithchk.c: In function 'ccheck':
    f2c/arithchk.c:125:2: error: format not a string literal and no format arguments [-Werror=format-security]
      Cray1 = printf(emptyfmt) < 0 ? 0 : 4617762;
      ^~~~~
    cc1: some warnings being treated as errors
    f2c/arithchk.c: In function 'ccheck':
    f2c/arithchk.c:125:2: error: format not a string literal and no format arguments [-Werror=format-security]
      Cray1 = printf(emptyfmt) < 0 ? 0 : 4617762;
      ^~~~~
    f2c/arithchk.c: In function 'need_nancheck':
    f2c/arithchk.c:158:9: warning: variable 't' set but not used [-Wunused-but-set-variable]
      double t;
             ^
    cc1: some warnings being treated as errors
    make[2]: *** [f2c/arith.h] Error 1
    make[2]: Leaving directory `/tmp/pip-build-aY9bg_/python-igraph/tmp/igraph.EDcZHF/igraph-0.7.1/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/tmp/pip-build-aY9bg_/python-igraph/tmp/igraph.EDcZHF/igraph-0.7.1'
    make: *** [all] Error 2
    Could not download and compile the C core of igraph.

```

**Comment by ntamas** [comment]
Discussion continues in https://github.com/igraph/igraph/issues/1069 .
