### ISSUE TITLE
Unable to install python-igraph 

### ISSUE THREAD

**Issue by sivaPalakurthi** [igraph/igraph#680]
ubuntu 14.04, python 2.7.6, installed build-essential and python-dev packages.
Also "pkg-config --libs --cflags igraph" gives
-I/usr/include/igraph  -ligraph 
When I try to install igraph using the command
"sudo pip install python-igraph"
i'm getting the following error. Can some help me? 

Downloading/unpacking python-igraph
  Downloading python-igraph-0.7.tar.gz (371kB): 371kB downloaded
  Running setup.py (path:/tmp/pip_build_root/python-igraph/setup.py) egg_info for package python-igraph

Installing collected packages: python-igraph
  Running setup.py install for python-igraph
    Build type: dynamic extension
    Include path: /usr/include/igraph
    Library path:
    Linked dynamic libraries: igraph
    Linked static libraries:
    Extra compiler options:
    Extra linker options:
    building 'igraph._igraph' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/igraph -I../../build/include -I../../include -I/usr/local/include/igraph -I/usr/include/igraph -I/usr/include/python2.7 -c src/vertexseqobject.c -o build/temp.linux-x86_64-2.7/src/vertexseqobject.o
    In file included from src/vertexseqobject.c:28:0:
    src/convert.h:64:59: error: unknown type name ‘igraph_pagerank_algo_t’
     int igraphmodule_PyObject_to_pagerank_algo_t(PyObject *o, igraph_pagerank_algo_t *result);
                                                               ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-sOHHDl-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/igraph

copying igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph

copying igraph/**init**.py -> build/lib.linux-x86_64-2.7/igraph

creating build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/separators.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/atlas.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/structural.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/foreign.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/indexing.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/bipartite.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/spectral.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/edgeseq.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/generators.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/rng.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/utils.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/homepage.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/attributes.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/vertexseq.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/isomorphism.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/decomposition.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/operators.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/flow.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/matching.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/games.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/cliques.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/conversion.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/layouts.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/basic.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/iterators.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/**init**.py -> build/lib.linux-x86_64-2.7/igraph/test

copying igraph/test/colortests.py -> build/lib.linux-x86_64-2.7/igraph/test

creating build/lib.linux-x86_64-2.7/igraph/app

copying igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app

copying igraph/app/**init**.py -> build/lib.linux-x86_64-2.7/igraph/app

creating build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing

copying igraph/drawing/**init**.py -> build/lib.linux-x86_64-2.7/igraph/drawing

creating build/lib.linux-x86_64-2.7/igraph/remote

copying igraph/remote/nexus.py -> build/lib.linux-x86_64-2.7/igraph/remote

copying igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote

copying igraph/remote/**init**.py -> build/lib.linux-x86_64-2.7/igraph/remote

creating build/lib.linux-x86_64-2.7/igraph/vendor

copying igraph/vendor/texttable.py -> build/lib.linux-x86_64-2.7/igraph/vendor

copying igraph/vendor/**init**.py -> build/lib.linux-x86_64-2.7/igraph/vendor

running build_ext

Build type: dynamic extension

Include path: /usr/include/igraph

Library path:

Linked dynamic libraries: igraph

Linked static libraries:

Extra compiler options:

Extra linker options:

building 'igraph._igraph' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/igraph -I../../build/include -I../../include -I/usr/local/include/igraph -I/usr/include/igraph -I/usr/include/python2.7 -c src/vertexseqobject.c -o build/temp.linux-x86_64-2.7/src/vertexseqobject.o

In file included from src/vertexseqobject.c:28:0:

src/convert.h:64:59: error: unknown type name ‘igraph_pagerank_algo_t’

 int igraphmodule_PyObject_to_pagerank_algo_t(PyObject *o, igraph_pagerank_algo_t *result);

```
                                                       ^
```

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-sOHHDl-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/python-igraph
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/**init**.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 50: ordinal not in range(128)

**Comment by ntamas** [comment]
The Python interface of igraph is a library which consists of a core written in C and a glue layer between Python and the C library (this is also written in C). When you simply try to install igraph via `pip` or `easy_install`, it will try to figure out whether the C core is installed already, and if not, it will simply download the most recent version of the C core and try to compile the C core and the Python interface together. The problem above was that an older version of the C core was already installed (so `setup.py` did not try to download a new version of the C core), but of course the linking failed because of this incompatibility between the version of the Python interface and the version of the C core.

Anyway, you can download the source code of the C core on its own from http://igraph.org/c and then you can compile and install it with the usual `./configure && make && sudo make install` dance. If you are running Linux, you might find that your distribution ships a pre-compiled version of igraph in the package repository (but check its version number). More info here: http://igraph.org/c/#cinstall

**Comment by swayson** [comment]
@ntamas Thank you for the detailed explanation. This has been helpful to me and clarified things.

**Comment by neocsbee** [comment]
@sivaPalakurthi : Thank you for posting the solution, it helped a lot. @ntamas Thanks a bunch for the explanation; the whole process made sense.

**Comment by ayushidalmia** [comment]
@ntamas I tried installing the source code of the C core. However, I get the following error:

/usr/bin/ld: cannot find -lxml2

What is the dependency I need to install here?

**Comment by swayson** [comment]
I imagine if there are some conda binaries, it would be much easier to avoid these package issues

**Comment by ntamas** [comment]
True, but unfortunately I cannot take resposibility for maintaining Conda binaries as I'm not using Anaconda Python myself. If anyone who is using Anaconda Python and igraph on a daily basis is willing to take the responsibility of generating binaries for all Anaconda Python versions that are currently in use, I'll be happy to provide hosting space for it.

**Comment by Yoln1** [comment]
@ntamas thank you for your help, but after having installed the C core using the ./configure | make | make install then tried to pip install python-igraph again, I still get the  `error: command 'x86_64-linux-gnu-gcc' failed with exit status 1` error.

Is there a specific location I should make the install to, or a specific location to specify to pip in order to find the C core? Would you have any other idea of what might go wrong here? (I am on a AWS EC2 machine, running Ubuntu 16.4 64, and I am using 3.5 version of Python)

Thank you.

**Comment by ntamas** [comment]
Please upload the full installation log somewhere and link it here so I can take a look at it. (Use `pip install --log pip.log python-igraph` if I remember correctly).

**Comment by Yoln1** [comment]
Thanks a lot @ntamas 

Here is the log file: [https://drive.google.com/open?id=0B4Z5tRCryZ14NXY4Vm01N0g1UW8](https://drive.google.com/open?id=0B4Z5tRCryZ14NXY4Vm01N0g1UW8)

**Comment by ntamas** [comment]
The development files of `zlib` (and most likely `libxml2` and `libiconv`) are not installed on the machine; the absence of the development files of `zlib` is shown by this error deep in the middle of the log:

```
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by Yoln1** [comment]
Thank you, I already had `libxml2`  ,  `libiconv`  and `zlib1g-dev` installed, but installing `lib32z1-dev` solved the problem.
