### ISSUE TITLE
edges between rectangular vertices may pass through vertex

### ISSUE THREAD

**Issue by bergsmat** [igraph/igraph#682]
```r

library(igraph)
m <- c(
-1.0,1.0,
-0.6,0.6,
-0.2,1.0,
-1.0,0.2,
-0.2,0.2,
-0.6,-0.2,
0.2,-0.2,
-0.2,-0.6,
0.6,-0.6,
0.2,-1.0,
1.0,-1.0
)
m <- matrix(m, nrow=11,byrow=TRUE)
g <- graph.empty() 
g <- add.vertices(g, nv = 11, shape='rectangle',color=NA,size = 20)
g <- add.edges(g, c(1,2,3,2,2,4,2,5,5,6,5,7,7,8,7,9,9,10,9,11))
g <- set.graph.attribute(g,'layout',m)
png()
plot(g)
dev.off()
```
![rplot001](https://cloud.githubusercontent.com/assets/5950242/4324882/b9f84eee-3f5e-11e4-948d-d100b518e193.png)

Note that several edges seem to originate at the edge of the vertex that is further from the destination vertex.  Effect seems more common for larger vertices larger graphs (more vertices).

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#38
