### ISSUE TITLE
diameter() gives inconsistent results with weighted and unweighted graphs

### ISSUE THREAD

**Issue by Manakins** [igraph/igraph#683]
## Test script to demonstrate bugs in iGraph 0.7 diameter() and farthest.nodes() functions

  # load packages
library(igraph)
library(Matrix)

  ## Import my "original" adjacency matrix "AdjMat156.csv" 
AdjFile <- file.choose()
AdjMatOrd  <- read.csv(AdjFile,header=TRUE,row.names=1,check.names=FALSE)  # inport adjacency matrix
  ## iGraph requires a matrix
AdjMatOrd <- as.matrix(AdjMatOrd)
Full156Ord <- graph.adjacency(AdjMatOrd,mode="undirected",weighted=T,diag=FALSE)

FullDiam <- diameter(Full156Ord, directed=F)  
   ## FullDiam = 8 (but get.diameter yields 6)
DiamPath <- get.diameter(Full156Ord, directed = F)
   ## But DiamPath (9-5-70-38-22-82) is only 5 links long
     ## Below we see that at least one geodesic has length 6
FarPair <- farthest.nodes(Full156Ord, directed=F)
   ## whereas an example of a farthest pair Node 9 to Node 82 has path length 8 
        ## (but a path  length 6 exists!)
TrialFarPairPath <- get.shortest.paths(Full156Ord,V(Full156Ord)[9],V(RandGraph)[82])
   ## this yields a path of length 5 for the farthest pair
GeodesicSet  <- get.all.shortest.paths(Full156Ord,V(Full156Ord)[17],V(RandGraph)[145])
AvgPath <- average.path.length(Full156Ord, directed =F)
path.length.hist(Full156Ord, directed=F) ## has 68 geodesics of length 6 but none longer

  ## Now import my adjacency matrix "AdjMatRand.csv" 
     ##  (same structure, just randomly reallocated weights)
AdjRandFile <- file.choose()
AdjMatRand  <- read.csv(AdjRandFile,header=TRUE,row.names=1,check.names=FALSE)  # inport adjacency matrix
  ## iGraph requires a matrix
AdjMatRand <- as.matrix(AdjMatRand)
RandGraph <- graph.adjacency(AdjMatRand,mode="undirected",weighted=T,diag=FALSE)

RandDiam <- diameter(RandGraph, directed=F)
  ## Now I get 6 (in my larger script, I get 22!)
RandDiamPath <- get.diameter(RandGraph, directed = F)
  ## Ok, this is 6, but note that path 17-5-70-91-63-59-78-106-145 has length 8
FarPairRand <- farthest.nodes(RandGraph, directed=F)

TrialPath <- get.shortest.paths(RandGraph,V(RandGraph)[17],V(RandGraph)[145])   ## length 6
TrialPath2 <- get.shortest.paths(RandGraph,V(RandGraph)[9],V(RandGraph)[82])    ## length 5
   ## Hmm, retrieves a path of length 6

**Comment by szhorvat** [comment]
It seems that this was due to a misunderstanding (?) and can be closed.  Manakins: please comment if you disagree.

**Comment by Manakins** [comment]
Gábor

Yes, thanks, that would seem to resolve the “diameter” issue, especially with just a one-sentence explanation that diameter(weighted g) is the sum of the weights (rather than anything to do with path lengths).

In case you are interested, I have published a paper with metrics for weighted graphs (derived from population genetics. (The ESM has R scripts for the functions, but I also attach them).

McDonald, D.B., and E.A. Hobson. 2018. Edge weight variance: population genetic metrics for social network analysis. Animal Behaviour 136: 239–50. https://doi.org/10.1016/j.anbehav.2017.11.017.

Cheers, Dave McDonald

*************************************************
David B. McDonald              dbmcd@uwyo.edu
Dept. Zoology & Physiology, Dept. 3166
1000 E. University Ave., Laramie, WY 82071
      On sabbatical in Ecuador 2017-2018
cell (307)-760-9360
Office: BioSci 415; Lab. BioSci 441
http://www.uwyo.edu/dbmcd/mcd.html
      Celular en Ecuador 097-964-5525
“Yo tengo una gran fortuna – la vida enamorada” Carlos Vives “Agua”
*************************************************
