### ISSUE TITLE
GraphML parser does not work if the GraphML tags are not in the default XML namespace

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#685]
Example:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<graphml xmlns:ns2="http://www.w3.org/1999/xlink"
    xmlns:ns3="http://graphml.graphdrawing.org/xmlns">
    <ns3:graph id="Barabasi-Albert-73751112" edgedefault="undirected">
        <ns3:node id="0"/>
        <ns3:node id="1"/>
        <ns3:node id="2"/>
        <ns3:edge id="0" source="1" target="0"/>
        <ns3:edge id="1" source="2" target="1"/>
    </ns3:graph>
</graphml>
```

**Comment by simonegabbriellini** [comment]
Hi, I am having issues with the 1.0.1 igraph version while importing a graphML file exported from NetLogo. The namespace is like this:

<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns/graphml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns/graphml">

can you confirm this is correct?

**Comment by ntamas** [comment]
Seems to be correct; please send me the graph (or upload it somewhere) if it doesn't work with igraph because it should.

**Comment by simonegabbriellini** [comment]
I cannot share the file at this moment, but changing that to:

<graphml xmlns="http://graphml.graphdrawing.org/xmlns"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
    http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">

did the trick... hope this helps anyway improving the reader...

**Comment by ntamas** [comment]
Hang on, so there was no `<graphml>` tag at all in the original file?

**Comment by simonegabbriellini** [comment]
check now, it was just not indented correctly

**Comment by ntamas** [comment]
Ah, okay. In that case, the namespace declaration of the original file was incorrect; the GraphML namespace is `http://graphml.graphdrawing.org/xmlns` (as far as I know) and not `http://graphml.graphdrawing.org/xmlns/graphml`.
