### ISSUE TITLE
Decompose graph failed: only 'IGRAPH_WEAK' is implemented

### ISSUE THREAD

**Issue by complexly** [igraph/igraph#718]
Environment: R 3.1.1, igraph 0.7.1, win7 x64

I was trying to decompose a directed network into strongly connected components:

decompose.graph(g, mode="strong")
Error in .Call("R_igraph_decompose", graph, as.numeric(mode), as.numeric(max.comps),  : 
  At components.c:469 : only 'IGRAPH_WEAK' is implemented, Invalid value

Since the "clusters" function has already provided the way to identify strong components, I'm just curious about the difficulty in this implementation...

**Comment by angadyuvraj** [comment]
Hi, I am facing similar issue using Python iGraph. 

g.decompose(mode=STRONG, maxcompno=None, minelements=1)

what's the way around for python graph ?

**Comment by ntamas** [comment]
Don't use `maxcompno=None` and it should work.

**Comment by angadyuvraj** [comment]
Tried: 
`g.decompose(mode=STRONG, minelements=1)`

But it is giving  "only 'IGRAPH_WEAK' is implemented" error.

using igraph on Python version is 2.7.15 , Mac High Sierra 10.13.4

**Comment by ntamas** [comment]
Ah, okay. Try something like:

```python
cl = g.clusters(mode=STRONG).subgraphs()
```

**Comment by angadyuvraj** [comment]
It worked. Gave me a Graph object which was useful. Thanks !

**Comment by ntamas** [comment]
Note to self: the problem here is that the C core does not implement `igraph_decompose()` for `mode=IGRAPH_STRONG`, even though it would not be too complicated. The next released version of the C core of igraph should fix this. I have no idea when that will happen given the lack of time to develop new features :(

**Comment by szhorvat** [comment]
Could probably be marked as "good first issue".

**Comment by iosonofabio** [comment]
I'll try and get this one if nobody objects

**Comment by jandraor** [comment]
Is decompose.graph(g, mode="strong") implemented in R igraph?

**Comment by szhorvat** [comment]
> Is decompose.graph(g, mode="strong") implemented in R igraph?

Not yet. You can try this out yourself. The R interface should pick up this functionality when it upgrades to the latest C core.
