### ISSUE TITLE
Wishlist: Distance cutoff for shortest path algorithms

### ISSUE THREAD

**Issue by dselivanov** [igraph/igraph#720]
It would be great to have `max_depth` parameter which restricts the maximum length of shortest path. I believe it is not too hard to add this feature to BFS, Dijkstra, Bellman-Ford algorithms.

**Comment by antongrau** [comment]
Essentially a +1 for this feature.
I calculate the weighted neighborhood size for each vertex - sometimes called "reach". My current approach only works on small weighted graphs:
rowSums(distances(g) <= order)

Another way of getting the reach measure could be through the neighbors and neighborhood.size. But they do take edge weights into account.

**Comment by gaborcsardi** [comment]
>  But they do not take edge weights into account.

You mean they do **not** take edge weights into account, right?

**Comment by antongrau** [comment]
Yes, sorry for the typo.

**Comment by szhorvat** [comment]
A cutoff is already implemented for betweenness/closeness/harmonic centrality. One may look there for guidance to implement this feature. PRs are welcome!

**Comment by szhorvat** [comment]
Adding to 0.10 milestone because it's probably most convenient to add the cutoff parameter to existing functions, which would be API-breaking.
