### ISSUE TITLE
Watts-Strogatz Game, Variation from Publication

### ISSUE THREAD

**Issue by joshua-a-becker** [igraph/igraph#754]
Hello,

It appears that the iGraph watts.strogatz.game function in R considers each link twice with probability p, such that the graph output does not match what might be standardized to the Watts/Strogatz 1998 publication.  Although this is mentioned in the comments of the source code (but without point out that it differs from the paper), it would be valuable to note this deviation in the documentation as well.  

If this is not by design, the quickest fix would be to simply convert the input p by taking the inverse of the sum of the binomial for k=1 and k=2, leaving the rewiring as is.  However, its possible that the proper algorithm is faster, since it requires fewer iterations.  (I'm not familiar with the igraph internals so I can't be sure.)  I'd be more than happy to help with this.

I would argue this is important because of the countless students (and academics?) out there using this function and then referencing the publication.  In the spirit of replicability, I would encourage this update.  (In fact, this issue came up when attempting to replicate a colleague's R model in Java.)

Thanks,
Joshua

**Comment by szhorvat** [comment]
I mentioned the difference in the docs and opened a feature request to implement the original version of the model, see #2383.
