### ISSUE TITLE
R: 0.8 pre version question

### ISSUE THREAD

**Issue by happyshows** [igraph/igraph#761]
Hi,

I'd like to deploy my R app on linux server needed 'get.all.simple.path' function in 0.8 pre. However I'm not able to install the igraph package on that because of the error in source tar.gz.
Is there any timeline to fix the current compilation error? Also, what's the target date to release 0.8 production version?

Thanks.

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#49
