### ISSUE TITLE
 Object type(s) 'text' not handled.

### ISSUE THREAD

**Issue by aaronmase** [igraph/igraph#763]
> rgl.open()
> g <- read.graph("path/to/1.graphml", "graphml")
> coords <- layout.fruchterman.reingold(g, dim=3)
> rglplot(g, layout = coords)
> writeSTL("path/to/somefile.stl")

Warning message:
In writeSTL("path/to/somefile.stl") :
  Object type(s) 'text' not handled.

How can I remove this warning message?

**Comment by gaborcsardi** [comment]
Closed until we get more info.
