### ISSUE TITLE
R: node attribute is list/vector, cannot export the graph in GraphML format

### ISSUE THREAD

**Issue by ggirelli** [igraph/igraph#764]
I have a graph where the nodes have, among others, a list attribute.
e.g.: ex=list(a=1,b=34,c=68,d=90)
The same happens with vector attributes:
e.g.: ex=c(1,34,68,90)
I am not able to write the graph in GraphML format...

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#50
