### ISSUE TITLE
Limit for all possible paths between two nodes [Feature Request]

### ISSUE THREAD

**Issue by mmeierer** [igraph/igraph#774]
Add command to return all possible path between two nodes (with an optional argument to set a limit for the maximum path length)

Related request here: http://lists.nongnu.org/archive/html/igraph-help/2013-11/msg00164.html

**Comment by youngser** [comment]
As the manual page says, the size of the output list (== memory) grows exponentially for large n!
So, can we have an argument, say "maxdist," so that it returns paths <= maxdist ??

**Comment by gaiazaff** [comment]
Any news on this feature? It would indeed be very useful to be able to set a limit

**Comment by PengNi** [comment]
It seems that the python version of igraph does not have this function, can anyone fix it?

**Comment by ntamas** [comment]
Added the "help needed" tag - I won't have time to implement this any time in the near future, but in theory it's not too complicated. Contributions (pull requests) are welcome - I'll review them.
