### ISSUE TITLE
Make local.scan() work on multigraphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#782]
From https://github.com/igraph/xdata-igraph/issues/53

**Comment by szhorvat** [comment]
We need to at least check if this is still a problem or already solved.

I believe it refers to https://igraph.org/c/doc/igraph-Structural.html#idm209411768240

See also https://github.com/igraph/igraph/wiki/Checklist-for-new-(and-old)-functions

**Comment by szhorvat** [comment]
@GroteGnoom Is this already fixed?

**Comment by GroteGnoom** [comment]
`igraph_local_scan_k_ecount`, `igraph_local_scan_k_ecount_them` and  `igraph_local_scan_subset_ecount` are tested for this, and they call all the other functions in src/misc/scan.c, so yes.
