### ISSUE TITLE
Adding expected force metric to igraph

### ISSUE THREAD

**Issue by glennlawyer** [igraph/igraph#791]
Hi,

We'd like to add the expected force metric to igraph. The expected force is a measure of node influence which shows high (>.90) correlations to epidemic outcomes. A preprint fully describing the metric is on arxiv (http://arxiv.org/abs/1405.6707), and we just received the reviewer's report from the journal, all very positive.

We've forked the devel branch repo, written the c code, written the python and R wrappers (along with test code), and hope to upload the results before the holidays.

**Comment by thomasp85** [comment]
Did this ever get a proper PR? I can't seem to find any in the archive...

**Comment by ntamas** [comment]
I don't remember having received a PR for this, but this was a long time ago so I might be wrong.

**Comment by glennlawyer** [comment]
No, it didn’t.

Long story— basically we had an issue with the package, and before we got it resolved we moved on to other things. 

Go ahead and close it out; I can submit a new pull if/when I get the package working.

+glenn
