### ISSUE TITLE
python-igraph 0.7.0 Graph.maximal_cliques is very memory-hungry

### ISSUE THREAD

**Issue by macks22** [igraph/igraph#801]
For a graph of 1,000 nodes and about 53,000 edges, the maximal_cliques method consumes about 15G of memory. I've attached output from the `valgrind` `massif` tool that tracked the code below. The issue does not seem to be one of memory leaks; the only unfreed blocks at the end were still reachable. Is there any way to reduce the space complexity without compromising time complexity?

    g = igraph.Graph.GRG(1000, 0.2)
    cliques = g.maximal_cliques(3)

![igraph-maximal-cliques-massif-out-v1000-e53000](https://cloud.githubusercontent.com/assets/3409997/5607171/7f71b5b2-941d-11e4-8b24-67747463171c.png)

**Comment by ntamas** [comment]
Is there anything special about this graph or is it simply a geometric random graph with 1000 nodes and a radius of 0.2? I tried this on a similar geometric random graph (1000 nodes, 52049 edges) and ran this:

```
clique_number = g.clique_number()
for i in xrange(clique_number, 2, -1):
    cl = g.maximal_cliques(min=i)
    print i, len(cl)
```

This went just fine - my machine has 8 GB of memory only but there is still no swap file on the disk so I'm pretty sure that the memory consumption did not go above 8 GB. (In fact, it stayed around 72 MB in `top`). I'm using the development version right now so it might be the case that this is something that we inadvertedly fixed some time after the release of 0.7.0. I'll do some more tests with earlier versions.

**Comment by macks22** [comment]
Sorry, I believe I posted the wrong test code. I was using that code to look for memory leaks. This one is problematic:

    g = igraph.Graph.GRG(10000, 0.25)
    cliques = g.maximal_cliques(3)

And yes, the one before and this one are both completely self-contained code-snippets. The only other thing I do is `import igraph`.

**Comment by macks22** [comment]
Ah, I see. The `igraph_maximal_cliques_file` method sounds exactly like what I was looking for. I suspected it might boil down to something like this. What goes into making a Python interface for a function? If you can point me towards some documentation, I'd be glad to give it a shot.

**Comment by ntamas** [comment]
I have added a keyword argument named `file` to `Graph.maximal_cliques` - this will call `igraph_maximal_cliques_file` behind the scenes; see:

https://github.com/igraph/igraph/commit/4c93c8ffaad9ef1d833730114ee18a0377f3b37c

**Comment by ntamas** [comment]
Closing this issue; feel free to reopen if it turns out that the memory usage is exceedingly high not simply because of the number of maximal cliques in your graph but due to some other reason.
