### ISSUE TITLE
igraph_clique_number and igraph_largest_cliques should use the new maximal clique implementation

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#804]
Right now they rely on the obsolete `igraph_i_maximal_cliques` function, which is slower than the new implementation. The net result is that it is usually slower to find the clique number of the graph than to find all the maximal cliques.

**Comment by iosonofabio** [comment]
Hi guys, this one is references in #1192 which itself ends with a reference to #1220, which is tagged 0.9. So is this 0.8 or 0.9?

**Comment by szhorvat** [comment]
I want to get in a _partial_ fix for 0.8 because I already use it in IGraph/M. I just need to clean up the naming of the functions (which is a bit of trouble because the names are assembled with macros). I'll deal with it.

**Comment by iosonofabio** [comment]
That was 3+ months ago and there has been no change since. I propose we move this to 0.9. I'm sorry if that means @szhorvat has to revert some changes in the mathematica interface.

**Comment by szhorvat** [comment]
@iosonofabio 

It cannot be reverted because the functionality is already released and people are using it. It needs to be in 0.8.

You have not seen any changes that happened because they are on my machine and not on this branch. When it is complete, it will be sent as a separate PR.

**Comment by szhorvat** [comment]
This should have been moved to the machinery in `maximal_cliques.c` and `maximal_cliques_template.c`, not to Cliquer.  I'd like to reopen temporarily, to at least check what's the best solution ...
