### ISSUE TITLE
Update plfit to version 0.7

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#808]
...because it contains a few improvements and also fixes the p-value calculation.

**Comment by chrisbodhi** [comment]
Hi, has this issue been resolved? From the Changelog, it looks like plfit is now at 0.8.1.

https://github.com/igraph/igraph/blob/master/CHANGELOG.md#changed-2

**Comment by ntamas** [comment]
Yes, `plfit` is at 0.8.1, this can be closed.
