### ISSUE TITLE
[0.7.1] gmp in non-standard path not found

### ISSUE THREAD

**Issue by wookietreiber** [igraph/igraph#809]
I have a lot of software installed in non-standard paths (working with [environment modules](http://modules.sourceforge.net/)). My CPPFLAGS includes all the correct -I directories:

```
echo $CPPFLAGS 
-I/usr/local/libxml2/2.9.2-1/include/libxml2 -I/usr/local/libxml2/2.9.2-1/include -I/usr/local/zlib/1.2.8-4/include -I/usr/local/gmp/6.0.0-1/include
```

These CPPFLAGS are not correctly picked up by configure, as you can see by this excerpt of my config.log:

```
configure:7202: checking gmp.h usability
configure:7219: /usr/local/gcc/4.9.2-1/bin/g++ -c -g -O2 -g -O2 -I/usr/local/libxml2/2.9.2-1/include/libxml2 conftest.cpp >&5
conftest.cpp:78:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
                 ^
compilation terminated.
```

As it seems, whatever you are doing (or not doing) with CPPFLAGS in configure.ac does not pick up my CPPFLAGS export.

**Comment by wookietreiber** [comment]
I have narrowed it down to be definitely in the libxml2/graphml_support part of configure.ac (I added AC_MSG_RESULT to output CPPFLAGS):

```
  AC_CHECK_LIB([xml2], [xmlSAXUserParseFile], [
    OLDCFLAGS=${CFLAGS}
    OLDCPPFLAGS="${CPPFLAGS}"

AC_MSG_RESULT([CPPFLAGS $CPPFLAGS])

    CFLAGS=${XML2_CFLAGS}
    CPPFLAGS="${XML2_CFLAGS}"
    AC_CHECK_HEADER([libxml/parser.h], [
      HAVE_LIBXML=1
      AC_DEFINE([HAVE_LIBXML], [1], [Define to 1 if you have the libxml2 libraries installed])
          CFLAGS="${OLDCFLAGS} ${XML2_CFLAGS}"
      CPPFLAGS="${OLDCFLAGS} ${XML2_CFLAGS}"
      AC_SUBST(XML2_LIBS)
      AC_SUBST(XML2_CFLAGS)
    ], [
      graphml_support=no
      CFLAGS=${OLDCFLAGS}
      CPPFLAGS="${OLDCPPFLAGS}"
    ])
  ], [
    graphml_support=no
  ])
fi

AC_MSG_RESULT([after xml2 CPPFLAGS $CPPFLAGS])
```

... which results in:

```
checking for xmlSAXUserParseFile in -lxml2... yes
CPPFLAGS -I/usr/local/libxml2/2.9.2-1/include/libxml2 -I/usr/local/libxml2/2.9.2-1/include -I/usr/local/zlib/1.2.8-4/include -I/usr/local/gmp/6.0.0-1/include
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
after xml2 CPPFLAGS -g -O2 -I/usr/local/libxml2/2.9.2-1/include/libxml2
```

**Comment by wookietreiber** [comment]
The bug is in [this line in configure.ac](https://github.com/igraph/igraph/blob/0.7.1/configure.ac#L149):

```
      CPPFLAGS="${OLDCFLAGS} ${XML2_CFLAGS}"
```

This is probably a typo as you're using **OLDCFLAGS** instead of **OLDCPPFLAGS**. As it seems, at least as of master branch, this is no longer an issue, since there is no more `OLD*FLAGS`.

I don't know, though, whether the master branch is the snapshot for upcoming 0.8 or maybe even 1.0, however, you might still want to hotfix this into a possible 0.7.2 release.

**Comment by ntamas** [comment]
Ah yes, the configure script was a bit of a mess there but we tried to fix it a while ago (see a1a333bb). The master branch is the snapshot for the next version (0.8) and I'm not sure whether there will be a 0.7.2 at all or not (summon @gaborcsardi), but either way, this will definitely be fixed in the next release.

**Comment by ntamas** [comment]
Related issue: #674

**Comment by gaborcsardi** [comment]
No 0.7.2 I guess, only 0.8.0.

**Comment by gaborcsardi** [comment]
So I can close this now, right?
