### ISSUE TITLE
tests fail because try to compile/link with CC instead of CXX

### ISSUE THREAD

**Issue by wookietreiber** [igraph/igraph#810]
I have lots of failed tests when running `make check`:

```
$ make check
...
   Subject: [igraph 0.7.1] testsuite: 46 53 54 55 56 57 59 63 64 69 70 71 73 74 75 76 85 86 87 89 91 96 97 108 110 111 112 113 114 115 116 117 118 121 122 123 126 128 153 163 164 173 174 176 177 178 179 188 189 190 197 200 201 208 209 210 
227 failed
...
```

When I look at `tests/testsuite.log` I see most if not all of these failed because of compile/link errors like the following:

```
+/tmp/build/igraph-0.7.1/src/gengraph_mr-connected.cpp:152: undefined reference to `operator new(unsigned long)'
+/tmp/build/igraph-0.7.1/src/gengraph_mr-connected.cpp:179: undefined reference to `operator delete(void*)'
```

A quick web search showed me, that this is due to the files being compiled/linked with CC rather than CXX (in my case gcc instead of g++). I guess, this is due to your [custom `AT_COMPILE_CHECK` that uses CC](https://github.com/igraph/igraph/blob/master/tests/testsuite.at#L26).

To verify this, I edited `tests/testsuite` and replaced `$CC` with `$CXX` at one of the failing tests and ran that again with `tests/testsuite <testnumber>` and the test was successful.

I think the problem does not occur if CC and CXX point to the same executable, however for gcc/g++ and possibly clang/clang++ these failures will keep occurring.

I suppose, the fix could be as easy as creating an `AT_COMPILE_CHECK_CXX` that uses `CXX` instead of `CC` and using this instead at all of the failing tests.

**Comment by wookietreiber** [comment]
I have sent the complete `testsuite.log` to @gaborcsardi for reference as described in the `make check` output.

**Comment by gaborcsardi** [comment]
I cannot reproduce this, I think it is a problem with your config.

**Comment by wookietreiber** [comment]
I feared as much. For full reproduction of my environment, this is how I compiled my gcc (may be time consuming to set this up):

```
../gcc-4.9.2/configure --prefix=/usr/local/gcc/4.9.2-1 --enable-languages=c,c++,fortran --disable-shared --enable-static --enable-threads=posix --enable-cloog-backend=isl --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --disable-multilib --disable-werror --enable-checking=release --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --with-gmp=/usr/local/gmp/6.0.0-2 --with-mpfr=/usr/local/mpfr/3.1.2-3 --with-mpc=/usr/local/mpc/1.0.2-1 --with-isl=/usr/local/isl/0.12.2-1 --with-cloog=/usr/local/cloog/0.18.1-1
```

All of its dependencies (gmp, mpfr, mpc, isl, cloog) are statically built as well (``--disable-shared --enable-static``). The versions are all included in the paths, the suffix `-number` are internal rebuilds.

**Comment by gaborcsardi** [comment]
Well, it's too much work for me to reproduce this, sorry. Do you really need all this custom config?

**Comment by wookietreiber** [comment]
Unfortunately, I do need all this customization (HPC cluster at work). I know it is much work to reproduce and I don't expect you to go through all of this. Since my build environment is most certainly a very special case, I think, you can close this issue if you like.

Still would be nice to see all of the tests pass - are you planning on travis CI integration?

**Comment by gaborcsardi** [comment]
https://travis-ci.org/igraph/igraph/builds/48811008
