### ISSUE TITLE
Link form igraph homepage to IGraphR Mathematica package

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#811]
Per [this message](http://lists.nongnu.org/archive/html/igraph-help/2015-01/msg00123.html) from the igraph-help mailing list, I'm opening this issue to place a link from the igraph homepage or README to the IGraphR Mathematica package.

The link should point to https://github.com/szhorvat/IGraphR

IGraphR is a Mathematica package for calling R/igraph functions from within Mathematica.  Its main function is to automatically translate between igraph graphs and Mathematica's Graph datatype.  It relies on Mathematica's [RLink](http://reference.wolfram.com/language/RLink/guide/RLink.html) package.

**Comment by szhorvat** [comment]
If this happens, the link should point to [IGraph/M](https://github.com/szhorvat/IGraphM) instead of IGraphR.

**Comment by szhorvat** [comment]
It would be lovely to have this ;-) http://szhorvat.net/mathematica/IGraphM

**Comment by ntamas** [comment]
Added in https://github.com/igraph/igraph.org/commit/c733dac31cd55dcf427a0396877dce22a113186a -- sorry for the delay! I am yet to figure out how to publish the changes to igraph.org so stay tuned :)
