### ISSUE TITLE
Creating a Network Graph using igraph in C#

### ISSUE THREAD

**Issue by LeMoussel** [igraph/igraph#813]
I need some help getting started using igraph in C#.I have a .csv file with 2 columns.
- the first column is a String that represents the "from" node,
- the second column is a String that represents the "to" node, and then 

My goal is to turn this .csv file into a network graph, but I'm not sure how to start.
There is source code for Microsoft Visual Studio (http://igraph.org/c/#downloads) but can use this C++ lib in C#? (eg: [Compiling programs using igraph](http://igraph.org/c/doc/igraph-tutorial.html) not in C++ but in C#)

**Comment by gaborcsardi** [comment]
Here is an example, although I have no idea if this works with igraph:
http://stackoverflow.com/questions/9407616/how-to-call-c-code-from-c-sharp
