### ISSUE TITLE
vf2 says two graphs are isomorphic when they are not

### ISSUE THREAD

**Issue by benruijl** [igraph/igraph#815]
The following example shows two non-simple graphs which are not isomorphic, yet vf2 says they are.

```
c = Graph(n=10)
c.add_edges([(0, 1), (1, 2), (1, 2), (1, 3), (2, 3), (2, 9), (2, 4), (3, 4), (3, 4)])
h = Graph(n=10)
h.add_edges([(0, 1), (1, 3), (1, 4), (1, 6), (1, 6), (3, 4), (3, 4), (3, 6), (4, 9)])
m = c.isomorphic_vf2(h, None, None, None, None, return_mapping_12=True)
print(m)
```

**Comment by ntamas** [comment]
I strongly suspect that VF2 does not support non-simple graphs while BLISS does, although I cannot confirm it because I did not implement either of them in igraph. (Maybe @gaborcsardi can chime in). But anyway, it's definitely a bug because `isomorphic_vf2` should throw an exception if it does not support non-simple graphs and you give it one.

**Comment by ntamas** [comment]
Just checked the VF2 code and indeed it seems to simplify the graph first; see the code around https://github.com/igraph/igraph/blob/master/src/topology.c#L1178 . Not sure whether this is an inherent limitation of the algorithm, though.

**Comment by benruijl** [comment]
Thanks. I don't think it is a limitation of the algorithm, since boost seems to support non-simple graphs with vf2: http://www.boost.org/doc/libs/1_57_0/libs/graph/doc/vf2_sub_graph_iso.html

**Comment by gaborcsardi** [comment]
I am fairly sure that the original VF2 did not handle multi-graphs. Anyway, one simple way to handle them is to use the multiplicity of the edges as labels or colors that are required to match. Or, to label the multi-edges individually and require them to match. This is somewhat less efficient, and seemingly this is what boost is doing.

A quick "fix" from our part would be to warn if VF2 is called with a multigraph. I guess that's not quite a solution, but a proper fix is slightly more difficult and I don't want to get into it right now.

**Comment by szhorvat** [comment]
VF2 not supporting non-simple graphs is now documented.

`igraph_simplify_and_colorize` makes it easy to implement a workaround.
