### ISSUE TITLE
can igraph be used in ios application?

### ISSUE THREAD

**Issue by IOSBabyBird** [igraph/igraph#823]
I try to use igraph in an ios single view app,butxcode give me an error message :building for ios simulator,but linking against dylib built for macosx file ,how can I deal with it

**Comment by ntamas** [comment]
As stated in the error message: you are building an app for iOS (which runs on an ARM architecture), but the copy of igraph that you are trying to link to was built for Mac OS X (which usually runs on Intel). Compile igraph for ARM first and then try to link to the ARM version of igraph.

Also, please note that this is not a support forum; the issue tracker is reserved for bugs and feature requests. Please send your queries to the igraph-help@nongnu.org mailing list.
