### ISSUE TITLE
Group Betweenness

### ISSUE THREAD

**Issue by ameyahate** [igraph/igraph#827]
I am interested in a modified version of betweenness centrality where nodes in graph belong to different groups. Consider the following very simple graph with three nodes:
 ![image of graph with no groups] (https://github.com/ameyahate/images/blob/master/NoGroup.png?raw=true)

For the general notion of betweenness, all of indicated geodesics (shortest paths) will be considered.
However if vertices of the graph are divided into groups and we want to find betweenness only in terms of nodes that lie between these groups then we have to consider only a subset of these shortest paths as shown below:
![Image of graph with groups](https://github.com/ameyahate/images/blob/master/Group.png?raw=true)

I am working on adding a new function that computes this type of betweenness.

I am new to contributing in open source projects and my C is a little rusty. I might need help with implementing this function. Any help is appreciated.

**Comment by ameyahate** [comment]
I have come up with an algorithm to calculate this group betweenness efficiently. I need to add a new function that very slightly modifies the ```igraph_i_betweenness_estimate_weighted()``` function in file ```centrality.c```.

The main difference is that I need to add a parameter in the function call that carries vertex attribute that indicates the group to which the vertex belongs. Can someone point me to an example where a function call has vertex attribute as a parameter?
Thanks!

**Comment by ntamas** [comment]
Attributes are simply passed as vectors in most functions; see, e.g., [`igraph_get_incidence`][1], where the vertex types of a bipartite graph are passed as an `igraph_vector_bool_t`.

  [1]: https://github.com/igraph/igraph/blob/master/src/bipartite.c#L694

**Comment by ameyahate** [comment]
Thanks ntamas. I have created the function definition in ```igraph_group_betweenness()``` in ```src/centrality.c``` and updated the ```include/igraph_centrality.h```. 
I then compiled and built the igraph with these changes and test the function. It works as designed. 

I now need to make an R interface for this C function. Are there any guidelines for doing so?

**Comment by ntamas** [comment]
The process that you described in the issue referenced above (#79) seems to be okay for me, but I'm not that familiar with the internals of the R interface so I cannot help you there. Closing this issue as issue #79 seems more relevant for any further discussion.

**Comment by ameyahate** [comment]
Thanks ntamas!
