### ISSUE TITLE
label.cex unrecognized in plot.communities

### ISSUE THREAD

**Issue by brooksambrose** [igraph/igraph#828]
I don't think any of the `igraph.plotting` params are working in the `plot.communities` method, e.g. `label.cex`:

```
> plot(edge.betweenness.community(g),g,label.cex=.5)
Error in i.parse.plot.params(graph, list(...)) : 
  Unknown plot parameters: label.cex
```

Or I'm not getting the syntax right!

**Comment by brooksambrose** [comment]
Ok, just a documentation issue, the argument is actually `vertex.label.cex` not `label.cex`. From the `igraph.plotting` help page:

```Vertex parameters first, note that the ‘vertex.’ prefix needs to be added if they are used as an argument or when setting via igraph.options.```

As a style comment, especially if users are skimming these quickly, it might be best to include the full name of the arguments instead of noting a necessary prefix (as if we'll read the entire article each time).

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#285
