### ISSUE TITLE
community_leading_eigenvector() returns incorrect results (sort of)

### ISSUE THREAD

**Issue by Pelonza** [igraph/igraph#831]
I'm running igraph version 0.7.1 on SageMathCloud.

When I ran the community detection algorithm using Newman's leading eigenvector method on the Political books network by Krebs, it produced a different result than the answer Newman published.

Figure 3 in "Modularity and community structure in networks" by Newman, 2006 in PNAS,
http://www.pnas.org/content/103/23/8577.full

This reports 4 communities (which the algorithm finds), but according to our checking, seems to report the wrong communities, and has a much lower modularity score than the paper reports.

A little more investigation finds that igraph has implemented Newman's "simple" algorithm (correct, based on the citation given in the documentation), however, in the citation above, he introduces a further refinement which improves modularity further (based on the Kernighan-Lin agorithm, possibly implemented elsewhere?). 

It may be a speed/complexity choice not to introduce the extra refinement method, however, it should probably be noted in the documentation that it does not include that refinement, so results may vary.

I checked this by running on the karate network. Newman reports that without his refinement, the leading eigenvector method reports Q=0.393, but with the refinement Q=0.419  (igraph's method on the karate indeed reports Q=0.393)

**Comment by gaborcsardi** [comment]
Sure, we can add to the docs, that this is not implemented.
