### ISSUE TITLE
[feature request] Add arrow with T-shaped head

### ISSUE THREAD

**Issue by zjf19870628** [igraph/igraph#832]
In bioinformatics, arrow with T-shaped head is often used to represent gene regulation. Advise to add this feature.

**Comment by ntamas** [comment]
Is this for the R or the Python interface of igraph? (The C core does not provide any plotting functionality).

**Comment by zjf19870628** [comment]
I am using R package "igraph". In R package "shape", I can use function
Arrows() to plot arrows with various arrowheads, including T-shaped head.
But "igraph" only provides one type “>”.

**Comment by ntamas** [comment]
Okay, then this is a duplicate of igraph/rigraph#4 - feel free to add a request for your particular arrow type there.
