### ISSUE TITLE
shortest.paths and get.shortest.paths return different results

### ISSUE THREAD

**Issue by chaosmaker** [igraph/igraph#834]
Hi there,

I came across this issue while calculating shortest paths between nodes within my graph. Within my graph I have about 16000 nodes as shown below:
```
> graph.net
IGRAPH DN-- 16755 116165 -- 
+ attr: name (v/c)
```

I calculated the shortest paths between all these nodes using:

```
graph.net.shortestPaths <- shortest.paths(graph.net)
```

Now I was specifically looking a particular pair that resulted from my down stream analysis and using the shortest.paths function I get the following output:

```
> shortest.paths(graph.net,v="2806",to="9476")
     9476
2806    4
```

Indicating a length of 4 as the shortest path between those nodes. When I now run get.shortest.paths to find the shortest possible linked paths I get: 

```
> get.shortest.paths(graph.net,from="2806",to="9476")
$vpath
$vpath[[1]]
numeric(0)


$epath
NULL

$predecessors
NULL

$inbound_edges
NULL

Warning message:
In .Call("R_igraph_get_shortest_paths", graph, as.igraph.vs(graph,  :
  At structural_properties.c:740 :Couldn't reach some vertices
```

That doesn't seem right to me, that one function says there is a connection by 4 while the other function says it couldn't reach between the nodes?

Am I doing something wrong?

Thanks

**Comment by gaborcsardi** [comment]
Hi, unfortunately the defaults are different for the two and by default one of them uses directed, the other undirected paths:

```r
> args(shortest.paths)
function (graph, v = V(graph), to = V(graph), mode = c("all", 
    "out", "in"), weights = NULL, algorithm = c("automatic", 
    "unweighted", "dijkstra", "bellman-ford", "johnson")) 
NULL
> args(get.shortest.paths)
function (graph, from, to = V(graph), mode = c("out", "all", 
    "in"), weights = NULL, output = c("vpath", "epath", "both"), 
    predecessors = FALSE, inbound.edges = FALSE) 
NULL
```

You need to set the `mode` argument.
