### ISSUE TITLE
cluster_fast_greedy() with argument 'modularity = FALSE' crashes R session

### ISSUE THREAD

**Issue by schmidtchristoph** [igraph/igraph#836]
Hi, 

for me changing the modularity argument of the cluster_fast_greedy() function crashes the R session. Following example reproduces this. Also happens with undirected weighted networks. 

A <- matrix(sample(c(0,1), 100, replace = TRUE), 10, 10)
diag(A) <- 0
g <- graph_from_adjacency_matrix(A, mode = "undirected")

this works:
cluster_fast_greedy(g)

this then crashes the R session:
cluster_fast_greedy(g, modularity = FALSE)

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#97

**Comment by ntamas** [comment]
Spoke to soon; it is not R-specific. The culprit is the following line:

https://github.com/igraph/igraph/blob/master/src/fast_community.c#L906

This line is hit when the user asks for a membership vector corresponding to the optimal modularity but does not provide space for the modularity vector.
