### ISSUE TITLE
NMF dependency

### ISSUE THREAD

**Issue by apford** [igraph/igraph#837]
I am unable to install the latest igraph because of the dependency on NMF which I am unable to install,
see https://github.com/renozao/NMF/issues/42 
Is NMF  required or could it be a recommended package ?

**Comment by gaborcsardi** [comment]
It is temporarily, because it brings in a lot of stuff. It is good that you say that it also breaks things. I'll try to remove or work around it soon.

**Comment by renozao** [comment]
@gaborcsardi what do you need in the NMF package. Maybe I can help with this (it's mine).

**Comment by nhlee** [comment]
I believe it is for some clustering routine, and it uses NMF package.  Looking at the error message, it sounds like it is an installation issue from user side? e.g., installation location is not specified correctly somehow?  if it makes things easier, then @gaborcsardi can suppress the routine that uses NMF for now as i am updating the routine.

**Comment by gaborcsardi** [comment]
Actually, this is a problem with the R package, so I am moving this over there.

**Comment by gaborcsardi** [comment]
Moved to https://github.com/igraph/rigraph/issues/93
