### ISSUE TITLE
Cloness on unconnected graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#838]
Document the current behavior, think about a better one.

**Comment by digicom71** [comment]
I use igraph in R for calculate graph measure, my graph make in a PIN that not Connected Graph and is Disconnected Graph. closeness method for connected graph is good and right calculate, and for Disconnected graph in not Good!

library(igraph)
# Create of Graph Matrix for Test Closeness Centrality
g <- read.table(text="A B 
  1 2
  3 4
  3 5", header=TRUE)
gadj <- get.adjacency(graph.edgelist(as.matrix(g), directed=FALSE))
igObject <- graph.adjacency(gadj) # convert adjacency matrix to igraph object
gCloseness <- closeness(igObject,weights = NULL) # Assign Closeness to Variable for print

[1] 0.06250000 0.06250000 0.08333333 0.07692308 0.07692308

 This output is Right ? and if right How to Calculate ?

**Comment by gaborcsardi** [comment]
What is the right closeness for unconnected graphs?

**Comment by digicom71** [comment]
I don't. But I ask in Stackoverflow and got answer that Closeness is not suitable in unconnected graph.

**Comment by szhorvat** [comment]
Probably should be closed https://github.com/igraph/igraph/issues/1053
