### ISSUE TITLE
weights argument not used in source code of layout_fr.c

### ISSUE THREAD

**Issue by Tixierae** [igraph/igraph#839]
Please see this SO [thread](http://stackoverflow.com/questions/31432176/r-potential-issue-with-igraph-1-0-0-layout-algorithms/31432717#31432717)

**Comment by ntamas** [comment]
The OP did not mention in the title of the issue but the same problem exists for the Kamada-Kawai layout as well.

**Comment by gaborcsardi** [comment]
@ntamas YEs. That seems harder to fix, at least I need to understand the algorithm again....

**Comment by gaborcsardi** [comment]
@ntamas Wait, the Kamada-Kawai layout actually uses edge weights. It uses them an opposite way than FR, but it does use them.

**Comment by ntamas** [comment]
Ah, okay, I have overlooked that then. Sorry.

**Comment by Tixierae** [comment]
Thanks for the very quick fix guys. If I just reinstall igraph from R, will this include the fix or should I download the package from a specific location?

**Comment by gaborcsardi** [comment]
You need to install from github: https://github.com/igraph/rigraph#installation

**Comment by Tixierae** [comment]
Thanks, but when I run `devtools::install_github("igraph/rigraph")`, I get a whole bunch of stuff and finally `fatal error: libxml/encoding.h: No such file or directory. compilation terminated. make: *** [foreign-graphml.o] Error 1. ERROR: compilation failed for package 'igraph'`. I tried to install an earlier version of igraph from source, but it also fails as shown [here](http://stackoverflow.com/questions/31432176/r-potential-issue-with-igraph-1-0-0-layout-algorithms/31432717#31432717). So I'm stuck. Thanks in advance for any help.

**Comment by gaborcsardi** [comment]
You need the libxml2 library when building from source.

**Comment by Tixierae** [comment]
Thanks. Now it tells me: `Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : namespace ‘pkgconfig’ 1.0.0 is being loaded, but >= 2.0.0 is required. ERROR: lazy loading failed for package ‘igraph’` I checked [online](https://cran.r-project.org/web/packages/pkgconfig/pkgconfig.pdf) and it seems that the most recent version of  `pkgconfig` is `1.0.0`. So how come igraph requires a version that does not exist yet?

**Comment by gaborcsardi** [comment]
Sorry, you also need 

```r
devtools::install_github("gaborcsardi/pkgconfig")
```

until I put the new version of `pkgconfig` on CRAN.

**Comment by Tixierae** [comment]
Thank you.

**Comment by fraba** [comment]
From R, as `layout_with_kk` the same problem?

**Comment by ntamas** [comment]
`layout_with_kk` should be okay, judging from the C source that clearly makes use of the `weights` parameter (by using it in Dijkstra's shortest path algorithm that determines the spring constants in the end):

https://github.com/igraph/igraph/blob/master/src/layout_kk.c
