### ISSUE TITLE
Failed compilation: libxml2 not available

### ISSUE THREAD

**Issue by nathanncohen** [igraph/igraph#842]
Hello everybody,

Michele Borassi is currently [2] linking igraph with Sage [1]. While testing his patch, compilation of igraph failed on my computer because of some library I miss. I only had to "apt-get install libxml2-dev" to sort it out, but I guess it should be checked by the 'configure' script instead of failing at compile time.

The log is available there, in case you might need it:
http://www.steinertriples.fr/ncohen/tmp/igraph-0.7.1.log

Thanks,

Nathann

[1] http://www.sagemath.org/
[2] http://trac.sagemath.org/ticket/18929

**Comment by gaborcsardi** [comment]
Thanks! configure does check for libxml2, so seemingly the check is broken.

**Comment by ntamas** [comment]
I think we use an "educated guess" for libxml2 if there is no `xml2-config` present on the user's system to allow igraph to compile on OS X (where libxml2 is installed by default but there is no `xml2-config` - at least it used to be this way years ago when we added this part to `configure.ac`).

**Comment by nathanncohen** [comment]
Thanks ! ;-)

**Comment by ntamas** [comment]
Wow, such a fast reply :)

**Comment by nathanncohen** [comment]
That's just how enthusiastic I am :-D
