### ISSUE TITLE
error in plotting a graph

### ISSUE THREAD

**Issue by zahraf** [igraph/igraph#845]
I 've written a new layout in igraph, but when I want to plot a graph using my new layout, I see this error:
*** caught segfault ***
address 0x8, cause 'memory not mapped'
Traceback:
 1: base::.Call(.NAME, ...)
 2: .Call("R_igraph_layout_Multilayer", graph, coords, niter, start.temp,     weights, minx, maxx, miny, maxy, PACKAGE = "igraph")
 3: layout_Multilayer(list(10, TRUE, c(1, 2, 3, 4, 5, 6, 7, 8, 9),     c(0, 1, 1, 2, 1, 1, 0, 6, 6), c(0, 1, 2, 3, 4, 5, 6, 7, 8    ), c(0, 6, 1, 2, 4, 5, 3, 7, 8), c(0, 0, 1, 2, 3, 4, 5, 6,     7, 8, 9), c(0, 2, 6, 7, 7, 7, 7, 9, 9, 9, 9), list(c(1, 0,     1), list(name = "Barabasi graph", power = 1, m = 1, zero.appeal = 1,         algorithm = "psumtree"), list(), list()), <environment>))
 4: eval(expr, envir, enclos)
 5: eval(call, .env)
 6: do_call(layout_Multilayer, .args = c(list(...), params))
 7: v(graph)
 8: ret()
 9: params("plot", "layout")
10: plot.igraph(g, layout = layout.multilayer)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
I used this function in my code: igraph_neighbors(graph,&neighbor,v,mode ). I think error should be related to this function. Can any one help me?

**Comment by ntamas** [comment]
Hard to tell what you did wrong without seeing your code. Please send a message to the [igraph-help][1] maling list along with a *short*, *self-contained* example that reproduces your problem.

  [1]: https://lists.nongnu.org/mailman/listinfo/igraph-help
