### ISSUE TITLE
`plot` is calling `text` without namespacing it (from graphics package) which can cause conflicts

### ISSUE THREAD

**Issue by daattali** [igraph/igraph#846]
The plot function is making a call to `text` from the `graphics` package.  I have a package ([shinyjs](https://github.com/daattali/shinyjs)) which defines a `text` function, and because the call in the plot function isn't namespaced, a conflict arises because the most recently attached `text` function is called instead of the intended `graphics::text`.

There is actually new guidlines in CRAN since June 29 that require any non-base function to be namespaced exactly for this reason.

Link to the CRAN news: http://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2015/06/29#n2015-06-29

I'm not asking to

**Comment by gaborcsardi** [comment]
This is fixed in the dev version: https://github.com/igraph/rigraph/blob/master/NAMESPACE#L888 

To be released soon.

**Comment by daattali** [comment]
I didn't realize it's your package -- I wouldn't have bothered opening issue if I knew :) Thanks for answer on Twitter a minute ago as well

**Comment by gaborcsardi** [comment]
> I wouldn't have bothered opening issue if I knew :)

I am not sure how to take this. :) Please do open issues if you have problems.

Btw. I was the one who started lobbying for this CRAN rule, and I am glad they accepted it. Even though CRAN people never actually replied to my email. :)

https://stat.ethz.ch/pipermail/r-devel/2015-April/071036.html

**Comment by gaborcsardi** [comment]
So I am closing this now. You can install the dev version via `install_github("igraph/rigraph")`.

**Comment by daattali** [comment]
I mean that I know you would make sure to fix such issues, whereas with some packages that are not very actively maintained I wouldn't be sure if this issue would ever be resolved.  I didn't know you suggested it, I honestly though this rule is one of the most useful CRAN checks, so thank you for that.

**Comment by gaborcsardi** [comment]
> I mean that I know you would make sure to fix such issues

Oh, that's kind, thanks, but please don't assume that. :)

**Comment by shobhitg11** [comment]
Hi Gabor,

Could you provide me an indication of timeline regarding when this update would be pushed onto CRAN. I am using this package in production code, so would like to use a CRAN version as opposed to the dev version.

Best Regards,
SG.

**Comment by manlius** [comment]
Hi Gabor,

I have the same issue and I am not even able to install the dev version of igraph to (temporary) solve it. I get
```
  clang: error: no such file or directory: '/usr/local/lib/libcairo.a'
  clang: error: no such file or directory: '/usr/local/lib/libpixman-1.a'
  clang: error: no such file or directory: '/usr/local/lib/libfreetype.a'
  clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
  clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
  clang: error: no such file or directory: '/usr/local/lib/libcairo.a'
  clang: error: no such file or directory: '/usr/local/lib/libpixman-1.a'
  clang: error: no such file or directory: '/usr/local/lib/libfreetype.a'
  clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
  clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
  clang: error: no such file or directory: '/usr/local/lib/libcairo.a'
  clang: error: no such file or directory: '/usr/local/lib/libpixman-1.a'
  clang: error: no such file or directory: '/usr/local/lib/libfreetype.a'
  clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
  clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
  make: *** [igraph.so] Error 1
  ERROR: compilation failed for package ‘igraph’
  * removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph’
  * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph’ 
  Errore: Command failed (1)
```
thus, I really need to install the updated igraph from CRAN. Any hint about when it will be available?

Thank you in advance for your great work.

Best,
M
