### ISSUE TITLE
node ids

### ISSUE THREAD

**Issue by zahraf** [igraph/igraph#847]
Hi all,
Does anyone know how nodes with the same labels can have different node ids?
In which function of C library of igraph graph is made from an adjacency matrix?
For example, I make a graph from a adjacency matrix by these commands in R:
dat=read.csv("")
g=graph.data.frame(dat,directed=FALSE)
Which igraph C function make graph?

**Comment by ntamas** [comment]
Please send igraph-related support questions to the igraph-help@nongnu.org mailing list. The issue tracker is for bug reports.
