### ISSUE TITLE
is_graphical_degree_sequence allows self loops and multiple edges in directed graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#851]
[According to the docs](http://igraph.org/c/doc/igraph-Structural.html#igraph_is_graphical_degree_sequence),

> `is_graphical_degree_sequence` Determines whether a sequence of integers can be a degree sequence of some **simple graph**.

Yet it returns true for the directed in- and out-degree sequence pair `{1}, {1}`.  The only solution is a graph with one node and one self loop.  It also returns true for `{2}, {2}` or `{2, 0}, {0, 2}`, i.e. it allows multi-edges.

**Comment by ntamas** [comment]
The problem is more complicated; the algorithm does not allow multi-edges or loops, but it incorrectly returns true when it gets stuck in a situation when there is only one vertex with a non-zero out-degree.
