### ISSUE TITLE
isomorphism testing functions that use Bliss must not allow different splitting heuristics for the two graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#853]
This applies equally to the C interface and the high level interfaces.

The [Bliss documentation](http://www.tcs.hut.fi/Software/bliss/doxy/classbliss_1_1Graph.html#08da370e34106cd7db479eca7c7375cc) states:

> The selected splitting heuristics affects the computed canonical labelings; therefore, if you want to compare whether two graphs are isomorphic by computing and comparing (for equality) their canonical versions, be sure to use the same splitting heuristics for both graphs.

The igraph isomorphism testing function takes *two* splitting heuristics arguments to be used for the two graphs.  This is the case both with the C and R interface.

This lets users shoot themselves in the foot.

The two-argument version of the function should probably be deprecated and it should start aborting with an error if differing splitting heuristics are provided.

**Comment by szhorvat** [comment]
Can you guys comment on what's the best resolution to this for the C interface?

Either the function signature could be changed to take a single splitting heuristic argument, breaking backwards compatibility.

Or the function could abort with an error if differing splitting heuristics are passed, keeping backwards compatibility, but preventing users from shooting themselves in the foot.

**Comment by ntamas** [comment]
I would vote for the second option for the time being.

**Comment by gaborcsardi** [comment]
YEs, giving an error is fine.

**Comment by ntamas** [comment]
Okay, I'll add this.
