### ISSUE TITLE
R interface: documentation should explain what "coloured graph isomoprhism" means

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#854]
http://igraph.org/r/doc/isomorphic.html

The R interface documentation should state that with coloured graph isomorphism two vertices can only match if their colour matches too.  The C interface documentation already states this.

This is important because an alternative interpretation of "coloured graph isomorphism" may allow relabelling of colours.  I.e. are `red -- red, blue` and `red, blue -- blue` isomorphic?  Not according to igraph's VF2 but yes if we allow colour renaming.

**Comment by gaborcsardi** [comment]
Well, I think colored isomorphism has a standard definition, and we just
use that. I am sure what you mean by relabeling the colors. Anyway, pull
requests are welcome for the clarification. :)
