### ISSUE TITLE
[Feature suggestion] Find automorphism group of graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#855]
igraph has functions for *counting* the number of automorphisms of a group, but it doesn't expose any functionality for actually retrieving the group.   Bliss (and possibly other libraries used?) [does have this functionality](http://www.tcs.hut.fi/Software/bliss/doxy/classbliss_1_1AbstractGraph.html#4d781026749d63e1c69f49633ec08f93).  It should be exposed in igraph.

Perhaps I'm missing some applications, but the automorphism count _alone_ doesn't seem to be that useful. 

----

Just as a clarification I would like to point out that Bliss will find the generators of the automorphism group.  This is not the same as the already existing functionality (through VF2) to list *all* isomorphisms.  The group may have only a few generators yet it may be too large to be able to handle/store each element.

**Comment by szhorvat** [comment]
https://github.com/igraph/igraph/pull/873 will fix this once merged.

**Comment by ntamas** [comment]
@gaborcsardi can we close this now that #873 is merged?

**Comment by szhorvat** [comment]
I think yes ... Fixed by #873
