### ISSUE TITLE
Test failure on Ubuntu: 196: Boolean graph attribute bug

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#856]
When I build igraph (from GitHub 6eb9b498940c860cf3bc746feddf0ff433f3feb2) on Linux (Ubuntu 15.04), then `make check`, I get one test failure

    196: Boolean graph attribute bug:                    FAILED (attributes.at:52)

On OS X there was no failure.

I used the default compiler, gcc 4.9.2, and a self-built GMP 6.0.0 (though I don't think that's related).

**Comment by ntamas** [comment]
Can you attach the `testsuite.log` file that was generated in the `tests` subdirectory? (Github does not allow attachments, but you can upload the log file to `gist.github.com` and then link it here).

**Comment by szhorvat** [comment]
This appears to be because I didn't enable GraphML support ... 

```
+Error at foreign-graphml.c:1354 :GraphML support is disabled, Unimplemented function call
```

Sorry about the false alarm.

**Comment by ntamas** [comment]
It's still a bug because the test case should have been skipped if there is no GraphML support but the test needs it.
