### ISSUE TITLE
igraph_feedback_arc_set will crash on some directed graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#858]
`igraph_feedback_arc_set` will crash on some directed graphs.  I found this from Mathematica, but I can reproduce it with the Python interface too.  Does the R interface not have this function?

I cannot reproduce it with *one* particular graph, as the crash simply may not happen when I use the same graph next time.  But running the function in a loop a few times will reliably crash.

#849 might be related.

Examples:

Mathematica: 

Generate a GNP directed random graph, run feedback arc set with the exact algorithm.  Repeat 100 times.  Those errors you see are coming from the error handler function.

```
Do[
 IGFeedbackArcSet@RandomGraph[BernoulliGraphDistribution[30, 0.05], DirectedEdges -> True], {100}
 ]

IGraphM::error: ../optional/glpk/glpapi01.c:359, glp_add_cols: ncs = 0; invalid number of columns

IGraphM::error: ../optional/glpk/glpapi01.c:253, glp_add_rows: nrs = 0; invalid number of rows

IGraphM::error: ../optional/glpk/glpapi09.c:427, glp_intopt: P = 0x7ffa49e155e0; invalid problem object

General::stop: Further output of IGraphM::error will be suppressed during this calculation. >>
```

Python:

```
In [12]: 
for i in range(100):
    g = igraph.Graph.Erdos_Renyi(n=30, p=0.05, directed=True)
    g.feedback_arc_set(method="exact")
   ....:     
Assertion failed: (v->stor_begin != NULL), function igraph_vector_size, file ./vector.pmt, line 479.
/Users/szhorvat/anaconda/envs/net/bin/python.app: line 3: 78746 Abort trap: 6           /Users/szhorvat/anaconda/envs/net/python.app/Contents/MacOS/python "$@"
```

**Comment by ntamas** [comment]
igraph gets in trouble with graphs that have lots of isolated vertices. Will push a fix soon.

**Comment by ntamas** [comment]
Fixed in 1f7c4ea

**Comment by szhorvat** [comment]
I can confirm it's working now.

![image](https://cloud.githubusercontent.com/assets/1212871/9714764/87f3edf0-555a-11e5-870a-4301e53aaf5d.png)

**Comment by trthhrtz** [comment]
Still this issue when generating FF graph, 

igraph_forest_fire_game(&g, 250000,
		0.37, 0.87, 1, 1);

igraph_simplify(&g, /*multiple=*/1, /*loops=*/0, /*edge_comb=*/ 0);

**Comment by szhorvat** [comment]
@trthhrtz Sorry, I do not understand. Are you saying that `igraph_feedback_arc_set` crashes for you on some graphs you generate this way?  If so, please show a complete reproducible example:

 - What version of igraph are you using?  This is fixed only in the development version.
 - If you use random graph models to generate the graph, provide a seed to make the example reproducible.

**Comment by trthhrtz** [comment]
Hi! Thanks for answering. 
Sorry. I was a bit unclear :) Issue is not with igraph_feedback_arc_set. However the error is the same Assertion failed: (v->stor_begin != NULL), function igraph_vector_size, file ./vector.pmt, line 479.

I am using Visual Studio 2015, igraph 0.7.1-msvc

Here is my code 

#include <stdio.h>
#include "igraph.h"
#include <iostream>
#include <fstream>
using namespace std;


int main(int argc, char* argv[])
{
	igraph_t g;
	FILE *outfile;
	int edgecount;

	igraph_forest_fire_game(&g, 250000,
		0.37, 0.87, 1, 1);
	
	igraph_simplify(&g, /*multiple=*/1, /*loops=*/0, /*edge_comb=*/ 0);
	outfile=fopen("outOneKek.txt", "w");
	igraph_write_graph_edgelist(&g, outfile);
	fclose(outfile);
	edgecount = igraph_ecount(&g);
	printf("%d\n", edgecount);
	igraph_destroy(&g);
        system("pause");

	return 0;
}

I suspect that the error is connected with lack of memory...

**Comment by ntamas** [comment]
Please try to figure out which step of your code is causing the crash, then we can proceed from there. Also, it would be better if you opened a separate issue for this as it is unrelated to `igraph_feedback_arc_set`.

**Comment by trthhrtz** [comment]
Ok, thanks)
