### ISSUE TITLE
LAD routines should be interruptible

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#860]
The LAD isomorphisms functions are not interruptible (`igraph_set_interruption_handler`).  However, they take a time limit argument, so at first sight it looks like it would be easy to make them interruptible by calling the interrupt handler here (line 1336 in lad.c):

```
  if ( (double)(end - *begin) / CLOCKS_PER_SEC >= timeLimit) {
    /* CPU time limit exceeded */
    IGRAPH_ERROR("LAD CPU time exceeded", IGRAPH_CPUTIME);
  }
```

Why is this not implemented?  Am I missing something here?

**Comment by ntamas** [comment]
No particular reason I think; pull requests are welcome as usual! :)

**Comment by szhorvat** [comment]
While trying to add and test it, I realized that I was wrong.  It is already interruptible:  7d970bd24506dcfc312b028a9936ecada5892d6c  It is not terribly responsive though, which is why I thought it wasn't.

It would make sense to also check for an interruption at the point where the time limit is checked, but given the location of the existing `IGRAPH_ALLOW_INTERRUPTION();` I think this is redundant.

The `cleanup:` label at the end of `igraph_i_lad_solve` did catch my eye though.  It's not clear to me whether this memory will be freed when the function exits with interruption (I don't yet understand `IGRAPH_FINALLY_FREE()`).  If it exits due to timeout, then the memory is not yet allocated, so this is not a problem.

**Comment by ntamas** [comment]
Probably we are not checking interruptions frequently enough then; maybe there is a better location in the code (i.e. one that is hit more often) to check for interruptions?

Re the `cleanup` label: the execution path won't hit the label when the function exits with an error, but these variables will be freed nevertheless. igraph basically maintains a stack of pointers that have to be freed whenever `IGRAPH_FINALLY_FREE()` is called, and `IGRAPH_FINALLY_FREE()` is called implicitly whenever we hit `IGRAPH_ERROR()`, so it's okay. `IGRAPH_FINALLY()` pushes pointers to this stack and `IGRAPH_FINALLY_CLEAN()` pops the pointers (without freeing them) - this is required when we free some of the pointers manually.
