### ISSUE TITLE
Error installing python-igraph using pip with pypy 2.6.1

### ISSUE THREAD

**Issue by afressancourt** [igraph/igraph#861]
Hello,

I am trying to install python-igraph using pip in a virtualenv wher the Python version used is pypy 2.6.1. After some time, I get an error trace, as presented in the following of my message. It states that pip "failed building wheel for python-igraph" 

Reading the trace a bit more in details, it looks like there is a problem with PyWeakref_Check.

Thanks in advance for your help !

I add the trace as a reference:

  Extracting igraph-0.7.1.tar.gz...
  Configuring igraph...
  Build type: static extension
  Include path: igraphcore/include
  Library path: igraphcore/lib /usr/local/lib /usr/lib /lib64 /lib
  Runtime library path:
  Linked dynamic libraries: xml2 z m stdc++
  Linked static libraries: igraphcore/lib/libigraph.a
  Extra compiler options:
  Extra linker options:
  building 'igraph._igraph' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/edgeseqobject.c -o build/temp.linux-x86_64-2.7/src/edgeseqobject.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/indexing.c -o build/temp.linux-x86_64-2.7/src/indexing.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/common.c -o build/temp.linux-x86_64-2.7/src/common.o
  src/common.c: In function ‘igraphmodule_resolve_graph_weakref’:
  src/common.c:58:3: warning: implicit declaration of function ‘PyWeakref_Check’ [-Wimplicit-function-declaration]
     if (!PyWeakref_Check(ref)) {
     ^
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/random.c -o build/temp.linux-x86_64-2.7/src/random.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/graphobject.c -o build/temp.linux-x86_64-2.7/src/graphobject.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/pyhelpers.c -o build/temp.linux-x86_64-2.7/src/pyhelpers.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/py2compat.c -o build/temp.linux-x86_64-2.7/src/py2compat.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/arpackobject.c -o build/temp.linux-x86_64-2.7/src/arpackobject.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/igraphmodule.c -o build/temp.linux-x86_64-2.7/src/igraphmodule.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/attributes.c -o build/temp.linux-x86_64-2.7/src/attributes.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/vertexseqobject.c -o build/temp.linux-x86_64-2.7/src/vertexseqobject.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/vertexobject.c -o build/temp.linux-x86_64-2.7/src/vertexobject.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/filehandle.c -o build/temp.linux-x86_64-2.7/src/filehandle.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/bfsiter.c -o build/temp.linux-x86_64-2.7/src/bfsiter.o
  cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/convert.c -o build/temp.linux-x86_64-2.7/src/convert.o
  src/convert.c: In function ‘igraphmodule_PyObject_to_real_t’:
  src/convert.c:776:5: warning: passing argument 1 of ‘PyPyInt_AS_LONG’ from incompatible pointer type [enabled by default]
       long l = PyInt_AS_LONG((PyIntObject*)object);
       ^
  In file included from /home/afressancourt/.virtualenvs/mypypy/include/Python.h:81:0,
                   from src/convert.c:25:
  /home/afressancourt/.virtualenvs/mypypy/include/pypy_macros.h:78:23: note: expected ‘struct PyObject *’ but argument is of type ‘struct PyIntObject *’
   #define PyInt_AS_LONG PyPyInt_AS_LONG
                         ^
  /home/afressancourt/.virtualenvs/mypypy/include/pypy_decl.h:170:20: note: in expansion of macro ‘PyInt_AS_LONG’
   PyAPI_FUNC(Signed) PyInt_AS_LONG(PyObject *arg0);
                      ^
  src/convert.c:781:35: error: ‘PyFloatObject’ undeclared (first use in this function)
       double d = PyFloat_AS_DOUBLE((PyFloatObject*)object);
                                     ^
  src/convert.c:781:35: note: each undeclared identifier is reported only once for each function it appears in
  src/convert.c:781:49: error: expected expression before ‘)’ token
       double d = PyFloat_AS_DOUBLE((PyFloatObject*)object);
                                                   ^
  src/convert.c:788:42: error: expected expression before ‘)’ token
       d = PyFloat_AS_DOUBLE((PyFloatObject*)i);
                                            ^
  error: command 'cc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-igraph
Failed to build python-igraph
Installing collected packages: python-igraph
  Running setup.py install for python-igraph
    Complete output from command /home/afressancourt/.virtualenvs/mypypy/bin/pypy -c "import setuptools, tokenize;__file__='/tmp/pip-build-uTp1rw/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vd55pQ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/afressancourt/.virtualenvs/mypypy/include/site/python2.7/python-igraph:
    running install
    running build
    running build_py
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    Build type: static extension
    Include path: igraphcore/include
    Library path: igraphcore/lib /usr/local/lib /usr/lib /lib64 /lib
    Runtime library path:
    Linked dynamic libraries: xml2 z m stdc++
    Linked static libraries: igraphcore/lib/libigraph.a
    Extra compiler options:
    Extra linker options:
    building 'igraph._igraph' extension
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/edgeseqobject.c -o build/temp.linux-x86_64-2.7/src/edgeseqobject.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/indexing.c -o build/temp.linux-x86_64-2.7/src/indexing.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/common.c -o build/temp.linux-x86_64-2.7/src/common.o
    src/common.c: In function ‘igraphmodule_resolve_graph_weakref’:
    src/common.c:58:3: warning: implicit declaration of function ‘PyWeakref_Check’ [-Wimplicit-function-declaration]
       if (!PyWeakref_Check(ref)) {
       ^
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/random.c -o build/temp.linux-x86_64-2.7/src/random.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/graphobject.c -o build/temp.linux-x86_64-2.7/src/graphobject.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/pyhelpers.c -o build/temp.linux-x86_64-2.7/src/pyhelpers.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/py2compat.c -o build/temp.linux-x86_64-2.7/src/py2compat.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/arpackobject.c -o build/temp.linux-x86_64-2.7/src/arpackobject.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/igraphmodule.c -o build/temp.linux-x86_64-2.7/src/igraphmodule.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/attributes.c -o build/temp.linux-x86_64-2.7/src/attributes.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/vertexseqobject.c -o build/temp.linux-x86_64-2.7/src/vertexseqobject.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/vertexobject.c -o build/temp.linux-x86_64-2.7/src/vertexobject.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/filehandle.c -o build/temp.linux-x86_64-2.7/src/filehandle.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/bfsiter.c -o build/temp.linux-x86_64-2.7/src/bfsiter.o
    cc -O2 -fPIC -Wimplicit -Iigraphcore/include -I/home/afressancourt/.virtualenvs/mypypy/include -c src/convert.c -o build/temp.linux-x86_64-2.7/src/convert.o
    src/convert.c: In function ‘igraphmodule_PyObject_to_real_t’:
    src/convert.c:776:5: warning: passing argument 1 of ‘PyPyInt_AS_LONG’ from incompatible pointer type [enabled by default]
         long l = PyInt_AS_LONG((PyIntObject*)object);
         ^
    In file included from /home/afressancourt/.virtualenvs/mypypy/include/Python.h:81:0,
                     from src/convert.c:25:
    /home/afressancourt/.virtualenvs/mypypy/include/pypy_macros.h:78:23: note: expected ‘struct PyObject *’ but argument is of type ‘struct PyIntObject *’
     #define PyInt_AS_LONG PyPyInt_AS_LONG
                           ^
    /home/afressancourt/.virtualenvs/mypypy/include/pypy_decl.h:170:20: note: in expansion of macro ‘PyInt_AS_LONG’
     PyAPI_FUNC(Signed) PyInt_AS_LONG(PyObject *arg0);
                        ^
    src/convert.c:781:35: error: ‘PyFloatObject’ undeclared (first use in this function)
         double d = PyFloat_AS_DOUBLE((PyFloatObject*)object);
                                       ^
    src/convert.c:781:35: note: each undeclared identifier is reported only once for each function it appears in
    src/convert.c:781:49: error: expected expression before ‘)’ token
         double d = PyFloat_AS_DOUBLE((PyFloatObject*)object);
                                                     ^
    src/convert.c:788:42: error: expected expression before ‘)’ token
         d = PyFloat_AS_DOUBLE((PyFloatObject*)i);
                                              ^
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/home/afressancourt/.virtualenvs/mypypy/bin/pypy -c "import setuptools, tokenize;__file__='/tmp/pip-build-uTp1rw/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vd55pQ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/afressancourt/.virtualenvs/mypypy/include/site/python2.7/python-igraph" failed with error code 1 in /tmp/pip-build-uTp1rw/python-igraph

**Comment by ntamas** [comment]
The Python interface of igraph does not support PyPy officially. I have never even used PyPy myself; it looks like there is some trickery going on during the compilation process that "transforms" the C source code of the Python interface to make it compatible with the PyPy API, but in some cases it fails to do so.

Since I don't use PyPy and have no plans to support PyPy in the near future, I'm closing this issue. If you managed to modify the source code of the Python interface to make it compile with PyPy, please send a pull request and then I'll try to merge the changes.

**Comment by afressancourt** [comment]
Hello Tamas,

Thank you for the quick answer. For my issue, I will try to convert the Graph I have in a structured dictionnary to perform my computation, as it is a walk with conditions along the graph. If I happen to dig into the compilation issue, I will keep you posted.

Best regards and thanks a lot for your work on this wonderful library,

Antoine
