### ISSUE TITLE
[Feature Request] Implement novel "collective influence" algorithm

### ISSUE THREAD

**Issue by ronammar** [igraph/igraph#862]
A recent publication in Nature by [*Morone & Makse*](http://www.nature.com/nature/journal/v524/n7563/full/nature14604.html) describes the concept of "collective influence", describing how many other nodes can be reached from a given node. Removing the nodes with the largest collective influence (the *influencers*) allows for efficient dismantling of networks (see figure below: B) removing 6 nodes with the highest degree leaves the network mostly intact, C) removing 4 top influencers leaves subgraphs that are smaller.)
![524038a-f1](https://cloud.githubusercontent.com/assets/5419280/9817951/e2b95a7e-5873-11e5-8480-1e09bce0f0d6.jpg)

Collective Influence (CI) is defined as:
CI = reduced degree of node x total reduced degree of all nodes at a distance d from node
(see equation 5 in [*Morone & Makse*](http://www.nature.com/nature/journal/v524/n7563/full/nature14604.html))

Can this algorithm be implemented in igraph? Thanks!

**Comment by ntamas** [comment]
This is probably easily implemented using the existing tools that igraph provides (see, in particular, the [`igraph_neighborhood`](http://igraph.org/c/doc/igraph-Structural.html#igraph_neighborhood) function, so I don't think that a separate function is required in the core of the library.

**Comment by ronammar** [comment]
Thanks! I've actually already achieved this, but it's quite slow. Is there a way to specify a specific depth to `neighborhood()` to only get vertices at a specific distance (ie. all nodes at distance 3, but not including those at distances 0,1,2)

**Comment by ntamas** [comment]
If you are using the R interface, you can use the `ego()` function, which has a `mindist` argument, although I'm not sure whether it's any faster - after all, in order to find the vertices at distance *k*, you have to find all the vertices at smaller distances anyway. Have you tried to profile your code to see where the bottleneck is?

**Comment by ronammar** [comment]
The `mindist` is exactly what I was looking for - thanks! I was getting exclusively distance 3 neighbours by subtracting order 2 from order 3 neighborhoods, which was computationally intensive and also unnecessary.

**Comment by WitzRed** [comment]
This a fantastic approach @ronammar  ! I've working with igraph to see if is there break a network faster, but all I got was hours of computation, even almost a day. Do you think of sharing your project here? It could be a great help. Thanks!

**Comment by ronammar** [comment]
@WitzRed I'll see if I can upload the code in the near future.

**Comment by ronammar** [comment]
@WitzRed Just uploaded and tested my code from 2015 here: https://github.com/ronammar/collective_influence
Hope this helps! :)

**Comment by WitzRed** [comment]
@ronammar WoW men! Thanks a lot dude ,I really appreciate! Last week I tried several approaches to break my network sets from histogram, standard deviation to k-shell but all them seem to be ta bit naive after all.  It's very nice you wrote it with parallel functions! Thanks again.
