### ISSUE TITLE
Test 159,  Maximum flow value (igraph_maxflow_value), doesn't compile on Windows

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#863]
Test 159, `flow.c`, does not compile on Windows because it includes `<sys/time.h>` and `<sys/resource.h>`. It uses these for a timing function. The result of the timing function is not actually used (it's commented out).  Consider removing these to allow the test to run on Windows.

https://github.com/igraph/igraph/blob/master/examples/simple/flow.c#L58

(Otherwise the test passes with the MinGW-w64 gcc 5.2.0 I used.)

**Comment by ntamas** [comment]
Can you please send us a pull request?
