### ISSUE TITLE
Tests 32 & 33 crash with MinGW-w64 (Windows)

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#864]
This refers to 3669421789674d7f47250fdea28ca7840d8dcc54

Tests 32 and 33 segfault when compiled with MinGW-w64.  These are `igraph_sparsemat_minmax.c` and `igraph_sparsemat_which_minmax.c`. In the first one the crash occurs at `rowfun(&A, &vec);` under the "Compressed diagonal matrix" section. I didn't investigate further, but I thought it's good to make a note.

I used gcc 5.2.0 and the SEH, winpthreads version of MinGW-w64, if this makes a difference.

igraph was configured like this in an msys2 shell:

```
export CFLAGS=-DMSDOS
./configure --disable-gmp
```

**Comment by ntamas** [comment]
Answering your question in the mailing list: these are probably unrelated to `f2c`, and probably have the same underlying root cause.

**Comment by szhorvat** [comment]
I tried to build igraph with clang's address sanitizer and `-O0` on OS X 10.11, and these two tests fail there as well.  The address sanitizer is not giving me any output, nor is the program. It exits without printing anything.

It seems that this is not a Windows-specific problem.

**Comment by ntamas** [comment]
Valgrind shows some memory access problems with these tests - will try to fix this soon.

**Comment by szhorvat** [comment]
Confirming that it's fixed on Windows/MinGW-w64.
