### ISSUE TITLE
[Feature Request] Bigint in Edge-betweenness

### ISSUE THREAD

**Issue by vlabatut** [igraph/igraph#865]
In the R version of igraph, both betweenness functions (exact and estimate) currently allow using the `nobigint=TRUE` option, in order to force the use of big integers and avoid integer overflow. 
However, it's not the case for the edge-betweenness functions. 
Would it be possible to have the same option in the edge-betweenness functions?
Thanks!

**Comment by szhorvat** [comment]
According to the [documentation](http://igraph.org/c/doc/igraph-Structural.html#igraph_betweenness), the  `nobigint` setting is ignored for vertex betweenness too when working with weighted graphs.

**Comment by szhorvat** [comment]
This will be solved not by adding bigint support but by eliminating the possibility of overflow through using floats to count paths.

**Comment by szhorvat** [comment]
Effectively solved by #1576.
