### ISSUE TITLE
LAD and VF2 subisomorphism functions inconsistent for empty graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#866]
LAD and VF2 disagree and whether an empty graph with no vertices is a subgraph of other graphs:

This example says it all:

```
> empty<-make_empty_graph(directed=F)
> tri <- make_full_graph(3)
> subgraph_isomorphic(empty, tri, method="vf2")
[1] TRUE
> subgraph_isomorphic(empty, tri, method="lad")
[1] FALSE
```

I believe LAD is wrong.  This is definitely wrong:

```
> subgraph_isomorphic(empty, empty, method="lad")
[1] FALSE
```

Perhaps we can have a check for an empty pattern at the beginning of the LAD routine (but only after directnedness checks, etc)

**Comment by gaborcsardi** [comment]
Agreed on both.

**Comment by ntamas** [comment]
255abd20f6bb0ed32fcce83336925f9859197c4f also fixes this.
