### ISSUE TITLE
LAD isomorphism checker should be better behaved with directed graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#868]
The LAD implementation in igraph seems to ignore directedness.

Thus, it should at least give a warning when it sees directed graphs and the behaviour should be documented.

The Bliss functions will additionally abort with an error when we try to compare a directed with an undirected graph. Gábor said this behaviour should be kept for Bliss, so perhaps it can be considered for LAD too for consistency.

Finally: [LAD version 2](http://liris.cnrs.fr/csolnon/LAD.html) does support directed graphs.  This is probably a lot of work to integrate though.

**Comment by gaborcsardi** [comment]
I think doing the same that we have for bliss is the best way to go for now.

**Comment by szhorvat** [comment]
This is extremely embarrassing, but I may have been wrong here.  I am still trying to figure out why I was convinced that directedness is ignored ... I apologize.

**Comment by ntamas** [comment]
Okay, so the LAD implementation in igraph does support directed graphs in the end? If so, let me know and I'll remove the warning (or just send another pull request).

**Comment by szhorvat** [comment]
I am going to send a pull request next week with several more tests.  I am
sorry about the mistake.

**Comment by ntamas** [comment]
No problem - looking forward to the pull request then. (I'm on the road now anyway so there's no need to hurry).

**Comment by szhorvat** [comment]
I'm a bit confused about this ... I did test LAD by counting directed 3- and 4-motifs, and it gives the same result as `igraph_motifs_randesu`. It does appear to handle directed graphs correctly. It does return different sets of isomorphisms for directed or undirected versions of the same graphs.

**But:**

`lad.c` has a comment:

> Unfortunately LAD seems to have no version numbers. The files were apparently last changed on the 29th of June, 2010.

This indicates that it's the old version from http://liris.cnrs.fr/csolnon/LAD.html, i.e. version 1.  Version 2 has time stamps from 2013 and 2014.

Also, while the code has been heavily modified for igraph, the `Tgraph` struct clearly matches with the one in version 1 of the original LAD code:

Original version 1:

```c
typedef struct{
	int nbVertices; // Number of vertices
	int* nbSucc;    // nbSucc[i] = number of successors of i
	int** succ;     // forall j in [0..nbSucc[i]-1], succ[i][j] = jth successor of i 
	bool** isEdge;   // isEdge[i][j] = true if (i,j) is an edge; false otherwise
} Tgraph;
```

igraph:

```c
typedef struct{
  long int nbVertices; /* Number of vertices */
  igraph_vector_t nbSucc;
  igraph_adjlist_t succ;
  igraph_matrix_char_t isEdge;
} Tgraph;
```

Original version 2:

```c
typedef struct{
	bool isDirected; // false iff for each edge (i,j), there exists an edge (j,i)
	bool isLabelled; // true if labels are associetd with vertices and edges
    bool* isLoop; // isLoop[i] = true if there is a loop on vertex i
	int nbVertices; // Number of vertices
	int* vertexLabel; // if isLabelled then vertexLabel[i] = label associated with vertex i
	int* nbAdj;    // nbAdj[i] = number of vertices j such that (i,j) or (j,i) is an edge
	int* nbPred;   // nbPred[i] = number of vertices j such that (j,i) is an edge and (i,j) is not an edge
	int* nbSucc;   // nbSucc[i] = number of vertices j such that (i,j) is an edge and (j,i) is not an edge
	int** adj;     // forall j in [0..nbAdj[i]-1], adj[i][j] = jth vertex adjacent to i 
	char** edgeDirection;	// if both (i,j) and (j,i) are edges then edgeDirection[i][j] = 3
							// else if (i,j) is an edge then edgeDirection[i][j] = 1
							// else if (j,i) is an edge then edgeDirection[i][j] = 2
							// else (neither (i,j) nor (j,i) is an edge) edgeDirection[i][j] = 0
	int** edgeLabel; // if isLabelled then edgeLabel[i][j] = label associated with edge (i,j)
} Tgraph;
```

The original LAD website clearly states that version 1 only works for undirected graphs and version 2 is for directed ones.

I don't understand what is going on.

**Comment by szhorvat** [comment]
I contacted Christine Solnon, and she confirmed that LAD v1 does indeed work both with directed and undirected graphs, however, it is not as efficient as LAD v2 for directed ones.  She wrote:

> LAD v1 can deal with directed graphs, and should output correct answers, but the filtering is not dedicated to directed graphs so that it is not very efficient. LAD v2 takes into account edge orientations when filtering so that it is more efficient than LAD v1 on directed graphs.
