### ISSUE TITLE
graphlets() crashes

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#869]
First I have to say that I am not familiar with graphlets yet, so I am very likely missing some points here (such as what weight values make sense).  I'll be showing the problem with the R interface, but it applies to the C interface as well.

First, `graphlets` will crash with any unweighted graph.  My understanding is that is requires weighted ones, but the R interface (not the C one) should never crash anyway.

Example:

```
g <- erdos.renyi.game(10,20,'gnm')
graphlets(g)
```

With C I get this:

```
Assertion failed: (v != NULL), function igraph_vector_size, file ./vector.pmt, line 481.
```

Second, depending on the weights passed, this will sooner or later crash or hang irrecoverably:

```
g<-erdos.renyi.game(10,20,'gnm')
graphlets(g, weights=runif(ecount(g)))
```

When this happens, and I'm calling the C interface from Mathematica, the Mathematica kernel prints this error, which might be helpful:

```
MathKernel(92230,0x7fff74b41300) malloc: *** error for object 0x7fcd43c2e328: incorrect checksum for freed object - object was probably modified after being freed.
```

**Comment by szhorvat** [comment]
Here's another example without random numbers that shows that the crash is in the projection step:

```
g <- graph_from_edgelist(matrix(c(1, 2, 1, 3, 1, 7, 1, 8, 1, 10, 2, 3, 2, 6, 2, 7, 2, 10, 3, 4, 3, 5, 3, 8, 3, 10, 4, 10, 5, 6, 5, 8, 5, 10, 6, 8, 6, 9, 7, 10), ncol=2, byrow=T), directed=F)

E(G)$weight <- c(2, 4, 3, 2, 2, 2, 5, 4, 3, 4, 2, 2, 3, 5, 2, 4, 3, 4, 4, 2)

gb <- graphlet_basis(g)

graphlet_proj(g, NULL, gb$cliques)
```

**Comment by szhorvat** [comment]
@gaborcsardi, could you check if this is a bug or am I just trying to use the function incorrectly?

**Comment by szhorvat** [comment]
Could someone please confirm this?  @gaborcsardi ?

**Comment by gaborcsardi** [comment]
Yes, it does crash.
