### ISSUE TITLE
triad_census returns bad output for undirected graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#872]
For an undirected graph, `triad_census` returns a meaningless result and issues a warning.  This is true both for C and R.  The result is meaningless partly because some of it comes from uninitialized memory and partly because the assignment to MAN labels is inconsistent.  This situation is not ideal.  I propose one of the following solutions:

 - Turn the warning into an error instead, do not return a bad result.
 - Return zeros for triads containing asymmetric dyads, assign correctly to 300, 201, 102 and 003.  This would be consistent with `dyad_census`, which does return a meaningful result.

I can send a pull request, just let me know which solution you prefer.

**Comment by ntamas** [comment]
+1. I prefer consistency so if `dyad_census` is already working correctly for undirected graphs, it would be great if `triad_census` did the same.

**Comment by szhorvat** [comment]
BTW is the a nice way to test that certain warnings are (or aren't) emitted?  I didn't want to test just for the warning test because that contains source file line numbers (which change easily).

**Comment by ntamas** [comment]
You could set up a custom warning handler using [`igraph_set_warning_handler`](http://igraph.org/c/doc/igraph-Error.html#igraph_set_warning_handler) that does not print the file and line numbers, and then just let the warning appear in the expected output if you want to ensure that the warning is emitted. [`igraph_warning_handler_print`](http://igraph.org/c/doc/igraph-Error.html#igraph_warning_handler_print) is probably a good starting point.
