### ISSUE TITLE
community_edge_betweenness: edge indices in 'bridges' off by one

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#878]
`community_edge_betweenness` returns a `bridges` result, which I understand to be the edge indices of the removed edges that resulted in a disconnection of the network.  These values are off by one.  They seem to be 1-based indices, not 0-based ones.  The problem propagates to the R interface as well.

In a network of `E` egdes, the `bridges` result always contains a number equal to `E` in C, or `E+1` in R.  In Python this values doesn't appear to be exposed (??).

I wanted some confirmation before touching the code though.

**Comment by ntamas** [comment]
I'm not sure - I think that the original intention in the C core was that you get the list of edges that were removed in the `edges` variable, and the `bridges` variable contains indices into the `edges` vector that tell you which of the removed edges actually caused two communities to separate. But I don't understand either why the C code increases the index by 1.

@gaborcsardi, do you happen to remember why it is done this way?

**Comment by gaborcsardi** [comment]
Hi guys, thanks for the issues and prs. I am travelling now with very minimal internet access, and will try to catch up next week.

**Comment by szhorvat** [comment]
A note, so I won't forget it;  `bridges` can be updated in one of two places, depending on how the functions are called:

 * https://github.com/igraph/igraph/blob/master/src/community.c#L136
 * https://github.com/igraph/igraph/blob/master/src/community.c#L272

I don't think it's being used anywhere in the C interface, but I may be wrong.

Instead of changing the offset, it might be simpler to just document what `bridges` is precisely.

**Comment by szhorvat** [comment]
I misunderstood what `bridges` was.  It does not contain edge indices.  Instead it shows after how many removals the graph split into more components.
