### ISSUE TITLE
3D DrL layout crashed on edgeless graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#881]
If I call `igraph_layout_drl_3d` on a graph with some vertices, but no edges, it crashes right after issuing this error:

> DensityGrid_3d.cpp:247, Exceeded density grid in DrL

For some reason the R interface does not crash, though it does show the error.
The Python interface does crash.

```python
g=Graph()
g.add_vertices(10)
g.layout_drl() # no crash
g.layout_drl(dim=3) # crash
```

**Comment by szhorvat** [comment]
Actually it seems any graph with isolated vertices triggers the problem.  A graph with three vertices `{1,2,3}` and one edges `1 <-> 2` is sufficient to trigger the problem.

**Comment by ntamas** [comment]
I suspect that the fact that the DrL layout does not crash for dim=2 is just a coincidence; the code for the 2D and 3D layouts is pretty similar and the cause of the crash is that the layout "diverges" for disconnected graphs.

The easiest solution is probably to say that the algorithm works for connected graphs only, and place a connectedness check before the layout algorithm is called.

**Comment by ntamas** [comment]
here's a temporary workaround: 708928c
