### ISSUE TITLE
Which isomorphism functions work with self-loops and multigraphs?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#882]
For each isomorphism algorithm, it should be clearly documented whether it supports self loops, multigraphs (multiple edges) and directed graphs.

Should the C functions check that the inputs are correct, and abort e.g. when they don't support multigraphs? Or should this be left to higher level interfaces instead?  `igraph_has_multiple` is not an O(1) function.

Task list:
- [x] Bliss
- [x] VF2
- [X] LAD doesn't support directed or multigraphs.

**Comment by ntamas** [comment]
Related: igraph/python-igraph#166

**Comment by ntamas** [comment]
BLISS does not support multigraphs and now it is documented that multiple edges between the same nodes will cause an incorrect result to be returned.
VF2 does not support multigraphs either, but it is not documented.
BLISS supports directed graphs, but it is not documented explicitly.
VF2 also supports directed graphs, and it is documented explicitly.

**Comment by ntamas** [comment]
Regarding checking whether the input has multiple edges or not: it definitely has some performance implications as `igraph_has_multiple()` is not an O(1) operation (as said above). However, it has caused quite a bit of confusion now so maybe we should probably add it in a future version.

One thing that I worry about (a bit) is that I don't know how people actually use the isomorphism functions. Do they call the function many times in a loop in a way that one of the graphs is always the same? In that case, it would be a waste of time to check whether the graph is the same.

**Comment by szhorvat** [comment]
It is correct that Bliss does not support multi-edges. As I remember, when I updated the Bliss library, I purposefully avoided adding this check because with the Mathematica interface there's a more efficient way to do it. I believe that Mathematica keeps track of whether a graph has multi-edges for its own data structure, thus this can be queried with O(1) complexity before the graph is converted to the igraph format.

**Comment by szhorvat** [comment]
As for LAD, when I'm done with the port of the new version (which ran into some difficulties, unfortunately ...) it should support self-loops, but *not* multi-edges.
