### ISSUE TITLE
Bug in fastgreedy.community (igraph for R)

### ISSUE THREAD

**Issue by LauraS2** [igraph/igraph#883]
Hi,

I just wanted to report a bug in the fastgreedy.community (igraph for R)
method.
If you run the method with edge weights and one (or more) of the edges has a
weight of 0, this causes R to crash completely with the message:
"R Session Aborted - R encountered a fatal error. The session was
terminated"

Yours,
Laura

**Comment by ntamas** [comment]
Can you post a small, self-contained example that crashes on your machine? The following code works just fine on my Mac:

```
> g <- grg.game(100, 0.2)
> E(g)$weight <- 0
> cl <- fastgreedy.community(g)
```

It also works if I only set a single edge weight to zero:

```
> E(g)$weight <- 1
> E(g)[1]$weight <- 0
> cl <- fastgreedy.community(g)
```

**Comment by LauraS2** [comment]
Hi,

somehow Github does not like my files, so I will just post the content here.
Below you can find an R script and a gml file that together cause the error in my system.
In the R script the '...' needs to be replaced with the path to the given gml file.  

My OS is Windows 7, 64 bit and I'm using R 3.0.2 and igraph 0.6.6

Yours,
Laura

-----------------------------------
library('igraph')
weightName <- 'topicSimilarity'
graph <- read.graph('...', 'gml')

sapply(labels, function(l) {  
  graphUndirected <- as.undirected(graph, mode="each")
  fc <- fastgreedy.community(graphUndirected, weights=get.edge.attribute(graphUndirected, weightName))    
})
-----------------------------------
graph [ 
	directed 1
	node [
		id 0
		label "0"
	]
	node [
		id 1
		label "1"
	]
	node [
		id 2
		label "2"
	]
	node [
		id 62
		label "64"
	]
	node [
		id 64
		label "66"
	]
	node [
		id 66
		label "68"
	]
	node [
		id 69
		label "71"
	]
	edge [
		source 0
		target 1
		id 4
		topicSimilarity 0.25417051763579995		
	]	
	edge [
		source 1
		target 2
		id 1
		topicSimilarity 0.9101556834114974		
	]
	edge [
		source 62
		target 0
		id 73
		topicSimilarity 0.5671641791044776		
	]
	edge [
		source 64
		target 66
		id 75
		topicSimilarity 0.42045454545454547		
	]
	edge [
		source 64
		target 69
		id 78
		topicSimilarity 0.0		
	]
]

**Comment by ntamas** [comment]
Sorry for the late reply, for some reason I haven't noticed that you posted your file here.
Anyway, it seems that you are using igraph 0.6.6 - that's almost two years old. Consider upgrading igraph to the newest version (1.0.1 on CRAN at the moment) and then try with the new version. Your code works just fine for me with igraph 1.0.1.
