### ISSUE TITLE
Tests 83, 84, 86 fail on Windows/MinGW-w64

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#886]
Tests 83, 84 and 86 fail on Windows/MinGW-w64 with gcc 5.2.0.  Currently these are the only tests that fail on this platform.

In the case of 83 and 84, the reason for failure is that the floating point results are not printed.  This is due to some weirdness with `printf` on this platform, which doesn't print anything with `%F`.  If we change it to `%f` (not `%3.0f`), then it prints this for the Dijkstra test:

```
0: 0.000000 0.000000 0.000000 1.000000 5.000000 2.000000 1.000000 13.000000 3.000000 5.000000
1: 1.#INF00 0.000000 0.000000 1.000000 5.000000 2.000000 1.000000 13.000000 3.000000 5.000000
2: 1.#INF00 1.000000 0.000000 1.000000 6.000000 3.000000 1.000000 14.000000 4.000000 6.000000
3: 1.#INF00 1.000000 0.000000 0.000000 6.000000 3.000000 1.000000 14.000000 4.000000 6.000000
4: 1.#INF00 5.000000 4.000000 5.000000 0.000000 2.000000 3.000000 8.000000 3.000000 5.000000
5: 1.#INF00 3.000000 2.000000 3.000000 8.000000 0.000000 1.000000 16.000000 1.000000 3.000000
6: 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 0.000000 1.#INF00 1.#INF00 1.#INF00
7: 1.#INF00 4.000000 3.000000 4.000000 9.000000 1.000000 2.000000 0.000000 1.000000 4.000000
8: 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 0.000000 4.000000
9: 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 1.#INF00 0.000000
```

The numbers are correct, but the printing of the infinities is weird. So it seems that the result is correct, unless there's something wrong with how infinities are represented (I haven't checked).  Using `%3.0f` will cause infinities to be printed as `1`, so it's not a solution.

I'm mentioning this so we know that the problem is not with igraph.

For 86, I haven't gone through the test code yet, but the output seems only reordered:

```
@@ -12,8 +12,8 @@
 0 9 8 7 6 5
 0 1
 0 1 2
-0 3
 0 1 2 3
+0 3
 0 1 4
 0 1 5
 4 4 12
```

**Comment by ntamas** [comment]
We could probably resolve tests 83 and 84 by printing the values with `igraph_real_fprintf_precise` from `types.c` (this is designed to give the same output on all platforms).

**Comment by szhorvat** [comment]
Actually I didn't file this as a bug to be fixed (though that might be useful).  I just wanted to document that this is really a "false failure".

**Comment by ntamas** [comment]
Nevertheless it should be fixed ;) I resolved tests 83 and 84; still have to check 86 though. It is indeed a reordering, but I don't know why it happens - Dijkstra should be more or less deterministic.

**Comment by szhorvat** [comment]
Fixed by https://github.com/igraph/igraph/commit/65937480df5398fe20f3de5597162a6714856728
