### ISSUE TITLE
igraph_cliques is slow

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#887]
Compared to other methods, `igraph_cliques` appears to be quite slow.

It is _much_ slower than the [Cliquer library](http://users.aalto.fi/~pat/cliquer.html) according to my benchmarks.  Surprisingly, in many cases it is also slower than finding maximal cliques (`igraph_maximal_cliques`), taking *all* their subgraphs, then filtering duplicates.  This was surprising to me.

As far as I can tell, the existing clique-related pull request does not touch `igraph_cliques`.

Benchmark results:

![image](https://cloud.githubusercontent.com/assets/1212871/10697569/db12e984-79ac-11e5-8c42-0584cf48c4af.png)

The third one is based on `igraph_maximal_cliques`, but it also uses high-level (and presumably slow) Mathematica operations.  Don't take the timing as an indicator of `igraph_maximal_cliques`'s performance.  It's only meant to show that *even this* is faster than `igraph_cliques`.

I really want to have this fixed.  What do you suggest?  A stopgap measure is integrating Cliquer (GPL license).  If we do, this I also want to have a function which computes a clique-size histogram without returning all cliques.

**Comment by ntamas** [comment]
`igraph_cliques` is based on a naive early implementation of mine (I just needed something quick-and-dirty at that time), so no wonder it's slow. Integrating Cliquer is definitely an option if its license is compatible with igraph's. However, I currently lack the necessary free time to do this on my own.

**Comment by szhorvat** [comment]
I've worked with Cliquer before and I can give it a go.  This is only for `igraph_cliques`.  `igraph_maximal_cliques` is faster than Cliquer.

**Comment by ntamas** [comment]
Okay, great, thanks! (See #888 - I'm closing this and let's continue the discussion there).
