### ISSUE TITLE
Provide docker support

### ISSUE THREAD

**Issue by nealmcb** [igraph/igraph#892]
Provide a Dockerfile so we can deploy and test igraph via [Docker](https://www.docker.com/).

Basing it `FROM jupyter/notebook` might make sense, at least as an option, and would conveniently provide a [Jupyter](http://jupyter.org/) web interface to igraph in an IPython notebook.  See [jupyter/notebook](https://github.com/jupyter/notebook)

**Comment by ntamas** [comment]
This issue was moved to igraph/python-igraph#48
