### ISSUE TITLE
`igraph_community_fastgreedy` requires merges and modularity arguments if membership argument is present

### ISSUE THREAD

**Issue by maurer** [igraph/igraph#895]
When calling `igraph_community_fastgreedy`, passing `NULL` for either `merges` or `modularity`, but a non-null value for `membership`, the function will either segfault or assert fail, depending on which you have set null.

It would be nice if either the documentation were updated to reflect this dependency (you must provide merges/modularity targets if you want community targets) or better yet remove the coupling by allocating/freeing a dummy matrix/vector within the function if NULL is passed in.

**Comment by ntamas** [comment]
Part of this issue was reported and fixed earlier (#836, 16624b0)
