### ISSUE TITLE
Smart generation of different shortest paths

### ISSUE THREAD

**Issue by otsaw** [igraph/igraph#896]
For route choice between two points on an actual road network, it would be useful to be able to generate a couple different alternative routes. To actually get different alternatives instead of e.g. a one block detour, some kind of a heuristic is needed. One popular method "link penalty" first finds the shortest path using Dijkstra's algorithm, then multiplies link weights along that path by a factor greater than one and then finds the shortest path on the altered network and so on until the desired amount of alternatives have been found.

I currently have and use an R implementation of the link penalty method and it works fine, except it's a bit slow, which is why I'd like to see it in igraph, implemented in C code.

For references, see e.g. the following.

Evaluation of choice set generation algorithms for route choice models
http://web.mit.edu/rama/Public/papers/paper7.pdf

Route choice modeling: past, present and future research directions
http://www.sciencedirect.com/science/article/pii/S1755534513700058

**Comment by ntamas** [comment]
Just out of curiosity: which part of the R implementation is the bottleneck in your case? I think that the hardest part is probably Dijkstra's algorithm, which you probably implement simply by calling down to the C layer of igraph, so even if we did a customized function for this in the C layer, it probably wouldn't speed things up too much because the hardest part is still Dijkstra's algorithm.

**Comment by otsaw** [comment]
Here's the relevant lines from Rprof:

```
                     total.time total.pct self.time self.pct
"get.shortest.paths"     699.84     79.82      0.32     0.04
".Call"                  585.20     66.75      0.16     0.02
"<Anonymous>"            583.78     66.59    583.62    66.57
"$"                      251.42     28.68      0.10     0.01
"$.igraph.es"            250.92     28.62      0.02     0.00
"get.edge.attribute"     250.84     28.61    151.18    17.24
"set.edge.attribute"     125.88     14.36      0.10     0.01
"as.igraph.es"            62.30      7.11      0.06     0.01
```

Most of the time is indeed spent in function `get.shortest.paths`. But, I'm wondering, is that all Dijkstra, or is there significant overhead to calling C from R -- type conversion or copying in memory of arguments or return values and that by moving the loop to C, i.e. making less calls in R would reduce the total overhead? I assume the actual Dijkstra part is something a bit less than that `.Call` amount, maybe around half of the total?

For context, I'm still on igraph 0.7.1. I generate these paths for tens or hundreds of thousands of pairs of points that have trips between them and then do stochastic choice and aggregate to get traffic volumes. I've been using 2-5 alternatives depending on the case.

Finding single shortest paths of trips works very fast. I just loop over the from ends of trips feeding all to ends as arguments to `get.shortest.paths` -- e.g. with 100 points, this would mean 100 calls. But to get three alternatives I need `100*100*3` calls (actually less, since not all pairs of points have trips between them). So, if there's overhead, it does accumulate.

**Comment by gaborcsardi** [comment]
Some points.

r/igraph 1.0.1 is very different than 0.7.1, so I would not consider new features based on benchmarks with 0.7.1.

There is no copying of arguments when calling C from R. There is **one** copying of results, and I would be very surprised if this was the bottleneck.

Do not call `get.shortest.paths` for every pairs, call it once for every source. A single pair of vertices, and all shortest paths from one source have the same time complexity.

**Comment by otsaw** [comment]
Thanks. I'll try 1.0.1 once I have time to review the differences and adjust my code. I take your word for the lack of overhead. Maybe the slowness is just an unavoidable problem with the link penalty method.

The link penalty method specifically requires that changes are made to the link weights to force a different route to be found and that modified network with bogus weights can only be used between a particular pair of points, once, to get one alternative, so calling once per source is not possible.

**Comment by gaborcsardi** [comment]
> I take your word for the lack of overhead. 

Well, I only said that there is no copying. Accessing attributes might be slow, OTOH, so I would really profile it.

**Comment by ntamas** [comment]
Also, parallelization might help if you have multiple CPU cores as igraph uses a single CPU core only for shortest path search. No idea how to do that in R, though - I'm not an R expert.

You also mentioned that this is a road network. Do you have exact coordinates for the intersections of the roads (assuming that the nodes represent intersections and not roads)? If so, it might be the case that the [A* search](https://www.wikiwand.com/en/A*_search_algorithm) would be faster than Dijkstra, provided that you can find a reasonable (i.e. admissible and monotonic) heuristic for the algorithm that never overestimates the path length from the source to any given node. (Geodesic distance could be okay if the edges are also weighted by geodesic distances in the first iteration).

**Comment by otsaw** [comment]
> Also, parallelization might help if you have multiple CPU cores as igraph uses a single CPU core only for shortest path search. No idea how to do that in R, though - I'm not an R expert.

I have 64 cores, so yes, I do already use parallelization -- `mclapply` in R.

> Do you have exact coordinates for the intersections of the roads (assuming that the nodes represent intersections and not roads)? If so, it might be the case that the A* search would be faster than Dijkstra.

Coordinates are known. A* does sound interesting, but hard to say how useful it would be considering how much speeds can vary, especially with something like public transport network, which means anything between walking speed and high speed train.

**Comment by otsaw** [comment]
I upgraded to igraph 1.0 and found my mistake. I was modifying weights in the network object with `set.edge.attribute`. I had not noticed the separate `weights` argument to `get.shortest.paths`/`shortest_paths`, which looking through the source code is passed separate right down to the C-level functions. Modifying the network seemed much faster to me in 0.7 than 1.0, but modifying just the `weights` vector much faster than both.
