### ISSUE TITLE
Is the temporal graph added?

### ISSUE THREAD

**Issue by ayushidalmia** [igraph/igraph#898]
Hi,

I am curious to know if the temporal graph generation feature discussed in the wiki, here, https://github.com/igraph/igraph/wiki/Temporal-graphs is added?

**Comment by ntamas** [comment]
I don't think that temporal graphs are supported; they are not mentioned in the [release notes](http://igraph.org/2015/06/24/igraph-1.0.0-r.html).

Please send support questions to the [igraph-help mailing list](https://lists.nongnu.org/mailman/listinfo/igraph-help) in the future; the issue tracker is reserved for bugs and feature requests.
