### ISSUE TITLE
'/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph/R/igraph.rdb' is corrupt

### ISSUE THREAD

**Issue by pjpan** [igraph/igraph#902]
'/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph/R/igraph.rdb' is corrupt

system:mac os 10.11.1

use：devtools::install_github("igraph/rigraph")
make: gfortran-4.8: No such file or directory
make: *** [AMD/Source/amd.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/igraph’

**Comment by gaborcsardi** [comment]
You need a fortran compiler, see the R docs on how to get one.
