### ISSUE TITLE
more robust power centrality (and alpha centrality)

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#904]
Hi everyone,

When computing the Bonacich centrality of a large, sparsely-connected network (1310 vertices with 6717 edges), i get the following error message:

Error in .local(a, b, ...) : 
  cs_lu(A) failed: near-singular A (or out of memory)

The graph is available via https://www.dropbox.com/s/9ba0l3i9ozm0axe/graph.txt?dl=1 (in graphml format).

What i have tried so far:
- using both igraphs' "power_centrality" function or the former  "bonpow" function provide the same error
- computed eigenvector centrality (no errors), alpha centrality (same error), computed Bonacich centrality in UCInet (no errors).
- increased memory to max (around 4GB)
- checked earlier posts and found one relevant, but unresolved thread about six years ago: http://lists.nongnu.org/archive/html/igraph-help/2009-04/msg00040.html 

Any help is highly appreciated, thanks in advance!

**Comment by minoo77777** [comment]
I have exactly the same problem. Could you find any solution? @gaborcsardi

**Comment by gaborcsardi** [comment]
I don't have a solution, sorry.

**Comment by szhorvat** [comment]
Data to reproduce is no longer available. Closing.
