### ISSUE TITLE
test case failure for igraph_density

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#906]
[testsuite (1).log.zip](https://github.com/igraph/igraph/files/55594/testsuite.1.log.zip)

**Comment by szhorvat** [comment]
This refers to 0.7.1, not the development version, right?

**Comment by gaborcsardi** [comment]
Yes, but I don't see any density related commits recently, so it is possibly still broken. Haven't tried, though.

**Comment by sodre** [comment]
@gaborcsardi, this issue should be closed if you cherry-pick b215195214abb8355121a8430c86df04e1f00eae into 0.7.1. 

The problem was that the unit-test was missing "return 0;" at the end of the main function.
