### ISSUE TITLE
igraph_transitivity_local_undirected may return wrong result for directed or multigraphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#907]
`igraph_transitivity_local_undirected` sometimes returns wrong results for multigraphs.  I suspect that this is because it counts the number of neighbours of a node as the degree of that node.  This is not true when multiple parallel edges are present.

Note that I only tested this for the case when the local clustering coefficient is computed for _all_ nodes.  The function seems to have several different code paths; I don't know if all are affected.

A more serious problem is that mutual edges in directed graphs are treated as two parallel undirected edges.  Thus the function also returns wrong results for directed graphs.  This is a more serious problem as people are more likely to apply the function to a directed graphs.

The documentation states that for directed graphs edge directions are ignored, so a fix should probably ensure that this is really the case.

Example code in R:

```
> g<-make_graph(c(1,2, 2,1, 2,3, 3,1))
> transitivity(g,"local")
[1] 0.3333333 0.3333333 1.0000000

> transitivity(as.undirected(g),"local")
[1] 1 1 1
```

Link to mailing list thread: http://lists.nongnu.org/archive/html/igraph-help/2015-12/msg00010.html

**Comment by yfiua** [comment]
The problem is still not solved. See https://github.com/igraph/igraph/issues/953
The result is to me so wrong, and I cannot imagine how this could not be done properly, because this is sort of a homework question for students.

**Comment by gaborcsardi** [comment]
As the name suggests, you are not expected to use this with directed or multigraphs.

**Comment by vtraag** [comment]
@szhorvat do you have a particular definition of transitivity in mind for graphs with parallel edges? I'm thinking about how to define it properly, but I don't have an immediate clear idea.

To me it seems most straightforward to ensure that the graph is simple and undirected.

**Comment by szhorvat** [comment]
For directed graphs, there are a few generalizations that I've seen.

For multigraphs, I would say the concept doesn't apply ... (One can always interpret edge multiplicities as edge weights, and look for weighted generalizations of the concept, but I would call that a change of concept ...)

----

Getting back to this specific function: What I would expect from this function is to ignore edge multiplicities and edge directions. Unfortunately, dealing with multigraphs sometimes has performance penalties. That is why I think it would be nice to cache whether a graph is a multigraph (to make the check effectively O(1)). However, that's a large, complicated and difficult project ...

**Comment by vtraag** [comment]
Yes, for directed graphs there are a few generalizations, but I think we should not try to include that for the 0.8.0 release, but leave that for the 0.9.0 release. Shall I open a separate issue for that?

Indeed, `igraph_is_simple` has a cost, but it is also called in a variety of other functions to check it. I don't see any alternative solution, do you? It would be even more costly to try to correct for possible edge multiplicities I think.

Perhaps we should also open a separate issue for caching whether a graph is simple or not? Again, that should probably be postponed for 0.9.0, so that would not be a viable solution for addressing this issue for 0.8.0.

**Comment by ntamas** [comment]
> I don't see any alternative solution, do you?
One potential solution would be to cache the result of `igraph_is_simple()` in `igraph_t` itself so the function returns the cached value if it has one. The cache will then have to be invalidated whenever we _suspect_ that some operation changes the simplicity of the graph. This is the tricky part. First, we would need to ensure that no igraph functions mess around with the internals of `igraph_t` except for the ones that we declared as the "basic interface" in the documentaiton, then we need to modify these functions carefully to update or invalidate the cached value (update if it is trivial to do so, invalidate if it would be costly to check what the new value should be). This is definitely for 0.9.0.

**Comment by szhorvat** [comment]
> One potential solution would be to cache the result of igraph_is_simple() in igraph_t itself so the function returns the cached value if it has one.

This is exactly what I was thinking.

>The cache will then have to be invalidated whenever we suspect that some operation changes the simplicity of the graph. **This is the tricky part.**

Exactly. Every single function that modifies graphs would need to be reviewed and updated. Every new function must take care to update this flag. It requires a lot of discipline.

> This is definitely for 0.9.0 or later.

Absolutely.

**Comment by szhorvat** [comment]
@vtraag 

> Yes, for directed graphs there are a few generalizations, but I think we should not try to include that for the 0.8.0 release, but leave that for the 0.9.0 release. 

Of course, I think it's quite clear at this point at only critical things go into 0.8.

> Shall I open a separate issue for that?

It's up to you. At this moment I do not see directed clustering as terribly interesting. I think (for 0.9) we should focus on functions that are clearly very useful or there's a clear demand. If you think this is a useful tool, sure, go ahead!

> I don't see any alternative solution, do you?

Something I wanted to mention:

Currently, the igraph philosophy seems to be to make C functions very high level and user-friendly. They check their input for correctness. They take care of everything. Then it's very easy to create a high-level interface for them.  I can certainly see the advantages of this approach.

If we go with this philosophy, this function should either check that the argument is undirected and simple, or make it undirected and simple before proceeding.

But this approach also has disadvantages. Another approach (which is a bit more appealing to me) is to keep C functions a bit lower level. Make it the user's responsibility to check that the input is simple and undirected. Do not waste time on doing this check for every single run of the function.

Then the higher-level interfaces might choose to do this check on their own. Thus they won't simply expose a C function as-is. They would add a wrapper which checks the input in a manner that is most reasonable for the high-level language in question.

**Comment by vtraag** [comment]
OK, let's call `igraph_is_simple` for now then, and postpone the rest until later. I'll create issues for that.

> Another approach (which is a bit more appealing to me) is to keep C functions a bit lower level. Make it the user's responsibility to check that the input is simple and undirected. Do not waste time on doing this check for every single run of the function.

Yes, indeed, this would have advantages. However, it has the disadvantage of making things more difficult to debug. We already discussed this earlier somewhere, but it might be good to make these types of checks optional (e.g. using `NDEBUG`). This would I think be the most reasonable compromise. We then wouldn't have to make a caching system, thereby complicating matters. But it would allow us to track things down more easily.
