### ISSUE TITLE
read.graph for graphml not working on cytoscape exported graphs

### ISSUE THREAD

**Issue by bedward1** [igraph/igraph#910]
Hi
I am trying to import .graphml files with igraph and receiving the error:
c= read.graph('~/ProjectsByDisease/RA/JURA/Network/cleancytographml.graphml', format='graphml')
Error in .Call("R_igraph_read_graph_graphml", file, as.numeric(index),  : 
  At foreign-graphml.c:1350 : Graph index was too large, Invalid value

The 'graphmlsample' file was pull from the web and works fine. If I import this to cytoscape, then export as graphml ('cleancytographml'), the format is different and not ok with igraph. I dont know what cytoscape is adding exactly adding. Can you please advise what is causing the error?
Thanks Bryan

[cleancytographml.zip](https://github.com/igraph/igraph/files/79220/cleancytographml.zip)

**Comment by ntamas** [comment]
Cytoscape's GraphML writer seems to be broken. There are multiple problems with `cleancytographml.graphml`):

* It is missing the GraphML namespace declaration from the root tag; the root tag should be `<graphml xmlns="http://graphml.graphdrawing.org/xmlns">`, not simply `<graphml>`.

* The `for` attribute of `<key>` tags is broken; it contains `node` even for edge and graph attributes. In particular, the first five `<key>` tags should have `for="node"` in your graph, the next seven should have `for="edge"` and the remaining ones should have `for="graph"`.

Fixing these in the GraphML file manually makes igraph load the GraphML file correctly, so I really think it's a bug in Cytoscape.

I'm attaching the [fixed GraphML file](https://github.com/igraph/igraph/files/79627/cleancytographml.zip) here.
