### ISSUE TITLE
igraph.par not found

### ISSUE THREAD

**Issue by petertu** [igraph/igraph#911]
Using igraph_1.0.1 and  R 3.2.3 on an OSX (El Capitan).

> igraph.par( "edge.arrow.size", 0.3 )
> Error: could not find function "igraph.par"

Thanks!

Peter

**Comment by gaborcsardi** [comment]
It seems that it was left out accidentally. See `igraph_options` and `igraph_opt` for a replacement.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#286
