### ISSUE TITLE
R Interface: graph.strength implementation does not match documentation

### ISSUE THREAD

**Issue by se4u** [igraph/igraph#913]
Hi
I am running igraph version 1 and I found that the graph.strength implementation is at odds with the documentation. The following code illustrated the problem:

    1> igraph.version()
        [1] "1.0.0"
    2> d = graph.strength(g, loops=FALSE)
        Error in .Call("R_igraph_strength", graph, vids - 1, mode, loops, weights,  :
        At structural_properties.c:5937 : Invalid weight vector length, Invalid value
    3> d <- graph.strength(g, vids=V(g), loops=FALSE)

Line 2 gives an error but line 3 passes. The documentation says that if `vids` is not provided then automatically `vids=V(g)` would be used.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#138
