### ISSUE TITLE
does not build under R-devel on windows; can't find libxml/encoding.h

### ISSUE THREAD

**Issue by dtenenba** [igraph/igraph#915]
I have libxml2 installed, both the i386 and x64 version), and i have set the LIB_XML variable to point to each of these in turn, for example:

    set LIB_XML=c:\libxml2\i386

However, in both cases, I cannot build igraph from source (and there is no binary available for R-devel), I get this error:

    ...
    foreign-graphml.c:38:29: fatal error: libxml/encoding.h: No such file or directory
    ...

Although that file does exist in
`%LIB_XML%\include\libxml2`.

I am also confused by the instructions at http://igraph.org/r/ ; in the section "Optional Requirements" (which sounds like a contradiction) it says that libxml2 is needed on Unix, but says nothing about it being needed on Windows, nor what the LIB_XML variable should be set to.

How can I build igraph under R-devel on windows?

```
> sessionInfo()
R Under development (unstable) (2015-12-15 r69777)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

**Comment by gaborcsardi** [comment]
> I am also confused by the instructions at http://igraph.org/r/ ; in the section "Optional Requirements"  (which sounds like a contradiction) it says that libxml2 is needed on Unix, but says nothing about it being needed on Windows, nor what the LIB_XML variable should be set to.

That page is about installing from CRAN. Anyway, sorry about the confusion. I'll just remove that section.

> How can I build igraph under R-devel on windows?

I think you need this libs: http://www.stats.ox.ac.uk/pub/Rtools/libs.html and setting LOCAL_SOFT.

**Comment by gaborcsardi** [comment]
Please reopen this issue if you still have problems.

**Comment by dtenenba** [comment]
To clarify, I **am** trying to install from CRAN. This is on the Bioconductor build machine where installation of dependencies is automated and there is no option to install packages from anywhere but CRAN or Bioconductor.

I downloaded http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local323.zip and unzipped it in c:\local323, then set `LOCAL_SOFT` to `c:\local323`, still get the same error. I also tried setting it to `c:\local323\include` with the same results, also `c:\local323\include\libxml2`. Can you clarify what I should be setting it to?

I don't seem to be able to reopen this issue either. Hopefully @gaborcsardi will still see it and be able to do so.

**Comment by gaborcsardi** [comment]
> To clarify, I am trying to install from CRAN.

Sorry, what I meant is installing **binaries** from CRAN.

> Can you clarify what I should be setting it to?

I can't, sorry. This is the CRAN build process and I am not familiar with it. 

If setting the LOCAL_SOFT macro in file src/gnuwin32/MkRules.local does not work, then I guess you can ask CRAN or Brian Ripley directly how local323.zip is supposed to be used.

**Comment by dtenenba** [comment]
I'm not sure where to find the file `src/gnuwin32/MkRules.local`. I am using a binary installation of R-devel from CRAN. Does this imply that I need to build R from source in order to take advantage of the libraries in local323.zip? 

We typically do not build R from source on our WIndows and Mac build machines, because we want to use the same R that the majority of our end users are using. 

I realize you may not know the answer to this if it is a CRAN thing, but surely you must have built igraph on windows before? How did you do it?

**Comment by dtenenba** [comment]
Oh wait, I see I can put it in `etc/{i386,x64}/Makeconf `. Will try that and get back to you.

**Comment by gaborcsardi** [comment]
> I'm not sure where to find the file src/gnuwin32/MkRules.local. I am using a binary installation of R-devel from CRAN. Does this imply that I need to build R from source in order to take advantage of the libraries in local323.zip?

Probably not, because I don't remember building R on windows.

> I realize you may not know the answer to this if it is a CRAN thing, but surely you must have built igraph on windows before? How did you do it?

Last time I did it has years ago, and I don't have access to that machine any more. I remember that I had to look up the correct location of the directory in the R source code, but the page I linked did not exist back then, and I assumed that that page contains the correct information.

So hopefully `Makeconf` will work. If not, try to find the default place for it.

**Comment by gaborcsardi** [comment]
Actually, r-appveyor uses that file, too, see:
https://github.com/krlmlr/r-portable/issues/3#issuecomment-72928971

**Comment by dtenenba** [comment]
That didn't work for me. That also implies that local323.zip is used **instead** of Rtools? If that is not the case I am curious why they unzipped it into a directory called `Rtools`.

Just FYI, Bioconductor does have a couple packages that use libxml2, the way they work is that the build machine has libxml installed in `c:\libxml2\i386` (32-bit version) and `c:\libxml\x64` (64-bit version). And the variable `LIB_XML2` is defined to point to `c:\libxml2`. 
Then in `Makevars.win` we refer to `LIB_XML2` as in the following example:

```
$ grep LIB_XML2 */src/Make*
flowWorkspace/src/Makevars.win:PKG_CPPFLAGS =-DROUT -I$(LIB_XML2)/$(R_ARCH)/include/libxml2 -Iboost_serialization -I$(LIB_PROTOBUF)/$(R_ARCH)/include -DLIBXML_STATIC
flowWorkspace/src/Makevars.win:PKG_LIBS += ${bs_objs} $(LIB_XML2)/$(R_ARCH)/lib/libxml2.a $(LIB_PROTOBUF)/$(R_ARCH)/lib/libprotobuf.a `${R_HOME}/bin/Rscript -e "flowCore:::LdFlags()"` -lws2_32
```

I wonder if that might be a better approach in the long term?

I am going to try and tweak the package so it will use a similar approach. If it works I will put it in our extra repository so it will get picked up by the build system, but that is not a long term solution.

Thanks.

**Comment by gaborcsardi** [comment]
> That didn't work for me. That also implies that local323.zip is used instead of Rtools? If that is not the case I am curious why they unzipped it into a directory called Rtools.

That was not the final solution there. Please read the rest of the comments. 

> Just FYI, Bioconductor does have a couple packages that use libxml2, the way they work is that the build machine has libxml installed in c:\libxml2\i386 (32-bit version) and c:\libxml\x64 (64-bit version). And the variable LIB_XML2 is defined to point to c:\libxml2. 

I copied the whole setup from the XML package, as CRAN told me to. I don't know it XML has changed it since, though.

**Comment by dtenenba** [comment]
OK, I did get igraph to build, by changing `${LIB_XML}` in lines 2 and 6 of `Makevars.win` to `$(LIB_XML2)/$(R_ARCH)`. Again, `LIB_XML2` resolves to `c:\libxml2` which contains an `i386` and an `x64` directory, each of which has a complete libxml2 installation for that sub-architecture.

It seems that you really need the `R_ARCH` bit on line 6 at least (where you link to the libxml2 dll) otherwise you won't be able to build for both sub-architectures.

**Comment by gaborcsardi** [comment]
Strange. AFAIK I have the same config as XML:
https://github.com/cran/XML/blob/master/src/Makevars.win#L1
How do you build XML? Or you don't build it?

And again, CRAN people told me to do it this way, so I am really reluctant to change it.

**Comment by dtenenba** [comment]
Apparently I can't build XML from source either.

I don't think you need to change igraph. I have gotten it to build and put it in our extra repos so that will solve my problem until CRAN starts building windows binaries for R-devel (interesting that they have a binary for XML but not for igraph, though they do have a check report for R-devel on windows at https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/igraph-00check.html ); do you know why there is no binary?

I will try and figure out how to build both these packages since it will be good for me to know, but I do think my issue is resolved for now. I guess I'll close it. Thanks.

**Comment by gaborcsardi** [comment]
The date in that check report is from 2014, so I don't think they build igraph for R-devel. It is also for an old igraph version. Don't ask me why it is there.

**Comment by wlandau-lilly** [comment]
Just now, I am getting the same compilation error on Windows R-devel. I do not know how to set environment variables like `LIB_XML` on Windows, so I am having trouble following this thread.

```r
> sessionInfo()
R Under development (unstable) (2017-09-23 r73342)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] pacman_0.4.6  rprojroot_1.2

loaded via a namespace (and not attached):
[1] compiler_3.5.0  backports_1.1.1
```

**Comment by wlandau-lilly** [comment]
I ended up solving my problem by manually copying over the libxml2 files from [local323.zip](http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local323.zip). Taking `R-devel` as the root of my installed development R, I copied:

- the whole `local323.zip/include/libxml2/libxml` folder to `R-devel/include/libxml`
- the files in `local323.zip/lib/i386` into `R-devel/lib/i386/`
- the files in `local323.zip/lib/x64` into `R-devel/lib/x64/`

I am not much of a Windows user, but this seemed to allow `igraph` to install.

**Comment by Sithara85** [comment]
HI, Did you mean to copy the i386 and x64 to respective folders in R bin?
