### ISSUE TITLE
iGraph 1.0.1 won't compile under R 3.2.3 and Mac 10.11.3

### ISSUE THREAD

**Issue by jeffPHE** [igraph/igraph#917]
I've tried to install the igraph package in R and the compile fails because of lots of errors in cholmod_check.c due to missing member print_function. I was able to install the R package fine under Linux, so I'm sure it has something to do with my environment, but I don't know where to look.

Log is attached. Any help would be greatly appreciated.

Thanks!

[igraph.txt](https://github.com/igraph/igraph/files/114265/igraph.txt)

**Comment by gaborcsardi** [comment]
Looks like you are using R from homebrew, which we do not support, sorry.

If you don't necessarily need the homebrew version of R, then try using the official one from www.r-project.org.

**Comment by jeffPHE** [comment]
Understood. Is this "we know it doesn't work and never will" unsupported or
just "you're on your own" unsupported?

Thanks,
Jeff

On Wed, Feb 3, 2016, 5:34 AM Gábor Csárdi <notifications@github.com> wrote:

> Looks like you are using R from homebrew, which we do not support, sorry.
>
> If you don't necessarily need the homebrew version of R, then try using
> the official one from www.r-project.org.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igraph/igraph/issues/917#issuecomment-179156545>.
>
-- 
----

Jeff Sullivan | Associate Director  | 310.984.7730
Precision Health Economics, a Precision for Medicine Company

**Comment by gaborcsardi** [comment]
You are on your own. 

It is not a priority, and there are several other things to fix. Also, it requires a big effort from us (=build R in homebrew). So most likely we'll never look at it. 

In general there are many problems with packages and homebrew R, so people are most often better off using the CRAN version.
