### ISSUE TITLE
igraph_diameter_dijkstra() crashes with weights=NULL and pres=NULL

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#921]
As the title says, calling `igraph_diameter_dijkstra()` (C interface) crashes when called with `weights=NULL` and `pres=NULL`.

The crash is due to this assignment:

https://github.com/igraph/igraph/blob/master/src/structural_properties.c#L6110

Sorry, didn't have time for a patch now, but wanted to report.

**Comment by ntamas** [comment]
Thanks, fixed now!
