### ISSUE TITLE
Feature request: call function for each maximal clique found

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#924]
It would be useful to have a function that invokes a callback function for each _maximal_ clique found.

There is already such a function, `igraph_i_maximal_cliques`, but it is not publicly exposed.  I don't know if it would be okay to expose this and how pull request #824 would affect it.

Pull request #888 adds such a function for _all_ (not just maximal cliques).  This feature request is specifically for maximal cliques.  The maximal clique implementation in Cliquer (#888) does not perform as well as the one currently in igraph, so the pull request doesn't add it (it's only for non-maximal cliques and weighted cliques).

**Comment by ntamas** [comment]
I'm okay with exposing this and pull request #824 does not seem to affect it. (However, we cannot merge #824 until it has some tests anyway, so if you feel like doing this at some point, just fork from `master` and ignore #824).

**Comment by szhorvat** [comment]
@ntamas Is it going to be sufficient to rename `igraph_i_maximal_cliques` to `igraph_maximal_cliques_callback` and make it public (and also `igraph_i_maximal_clique_func_t`)?  Or is there any reason why it would be better to keep it internal and add a public _wrapper_ instead?

**Comment by ntamas** [comment]
Renaming is okay I think. I believe the only reason for them being internal is because we did not want to commit exposing such a functionality in the public API for a long time, but I think it is safe to do so now.

**Comment by szhorvat** [comment]
Fixed by #1281
