### ISSUE TITLE
igraph_maximum_cardinality_search crashes when called with empty graph

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#925]
`igraph_maximum_cardinality_search(&graph, &res, NULL)` crashes if `graph` is empty, possibly due to a call to `free` with an invalid pointer (based on console messages).

I see the crash on Linux only so far.  I haven't gotten to the bottom of it yet.

**Comment by szhorvat** [comment]
The code doesn't appear to be written with empty graphs in mind, see e.g. here:

https://github.com/igraph/igraph/blob/master/src/decomposition.c#L104

    VECTOR(next)[no_of_nodes-1] = 0;

This doesn't look valid if `no_of_nodes` is `0`.

Would it be okay to just put a check for empty graphs at the beginning of the function instead of trying to find out where the crash comes from exactly?

**Comment by gaborcsardi** [comment]
@szhorvat Yes, just return early with the correct result for an empty graph, although I am not entirely sure what that would be.
