### ISSUE TITLE
LAD crashes with certain inputs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#927]
Here's the R version of the crash demo:

```
g<-make_lattice(c(4,8))
patt<-make_lattice(vcount(g))
subgraph_isomorphisms(patt,g,"lad")
```

This code attempts to find all Hamiltonian paths in a (4,8) grid graph.  For (4,7) it doesn't crash.  For (4,8) it does.

Mathematica version:

```
g = GridGraph[{4, 8}];
IGLADSubisomorphismCount[PathGraph@Range@VertexCount[g], g]
```

The crash is present in the current master branch version.

It would be reasonable to think that this is an out-of-memory crash.  But the (4,5), (4,6) and (4,7) grids have 2012, 7220 and 24020 Hamiltonian paths, respectively.  Thus it seems unlikely that the (4,8) one could run out of memory.

Do you have any hints on what may be going on before I test the original (unmodified) LAD code?

**Comment by szhorvat** [comment]
I tested the original (unmodified) [LAD v1 program](http://liris.cnrs.fr/csolnon/LAD.html) and it doesn't choke on the (4,8) grid graph.  It quickly returns 77968 as the number of solutions.

Thus the problem must be in the igraph adaptation of LAD.

The attachments are the same graphs as above written in a format that LAD can read directly.

[patt.txt](https://github.com/igraph/igraph/files/149813/patt.txt)
[g.txt](https://github.com/igraph/igraph/files/149814/g.txt)

**Comment by szhorvat** [comment]
It appears the crash may be coming form this line, but I am unable to understand how:

https://github.com/igraph/igraph/blob/master/src/lad.c#L1058

**Comment by szhorvat** [comment]
While the crash happens `ensureGACallDiff`, I think the bug is elsewhere and `ensureGACallDiff` simply receives a corrupted datastructure.  I spent a lot of time on this and couldn't figure out what is going wrong, but I am even more confident that there is a difference (bug) between the original and the igraph versions of LAD.  I think the following (laborious) method should work for finding the problem: 1. write a function to print the `Tdomain` data structure and sequentially label each printed item 2. print it in several functions which use it, both in the original and igraph LAD 3. try to figure out where they diverge and why.

I can sort of see where they diverge as the computation proceeds but not the root cause of it.

**Comment by szhorvat** [comment]
@ntamas Good news: 131f6e3e9bbb9b80fa1cc21d2367e574802bb317 *might* have fixed this.

**Comment by ntamas** [comment]
That's good news.

For the record, the original problem was that `igraph_i_lad_augmentingPath` and `igraph_i_lad_removeValue` set the value pointed to by the `result` argument to `true` in certain conditions but they never set it to `false`. Based on my limited understanding of this part of the code, these functions sort-of-assume that the initial value of `*result` is `false` and they only need to set it to `true` in certain conditions. However, this precondition did not necessary hold so I added that `result = false` statement at a location that seemed appropriate, without understanding exactly what's going on behind the scenes.

**Comment by szhorvat** [comment]
Here's a small example that triggers an out-of-bounds access:

```c
#include <igraph.h>
#include <stdio.h>

int main() {
    igraph_t pattern, target;
    igraph_bool_t iso;

    igraph_small(&target, 20, /* directed = */ 0,
                 0, 1, 0, 2, 0, 3, 0, 9, 0, 13, 0, 17, 1, 2, 1, 3, 1, 5, 1, 14, 1, 18,
                 2, 3, 2, 6, 2, 10, 2, 19, 3, 7, 3, 11, 3, 15, 4, 5, 4, 6, 4, 7, 4, 8,
                 4, 12, 4, 16, 5, 6, 5, 7, 5, 14, 5, 18, 6, 7, 6, 10, 6, 19, 7, 11, 7,
                 15, 8, 9, 8, 10, 8, 11, 8, 12, 8, 16, 9, 10, 9, 11, 9, 13, 9, 17, 10,
                 11, 10, 19, 11, 15, 12, 13, 12, 14, 12, 15, 12, 16, 13, 14, 13, 15,
                 13, 17, 14, 15, 14, 18, 16, 17, 16, 18, 16, 19, 17, 18, 17, 19, 18, 19,
                 -1);

    igraph_ring(&pattern, 15, 0, 0, 1);

    igraph_subisomorphic_lad(&pattern, &target, 0, &iso, 0, 0, /* induced= */ 1, 0);

    printf("Isomorphic: %d\n", iso);

    igraph_destroy(&pattern);
    igraph_destroy(&target);

    return 0;
}
```

The target is `GraphData[{"Arrangement", {5, 2}}]` from Mathematica. The pattern is a length-15 cycle graph. Only induced subgraphs are matched.  Compile with ASAN to see what's going wrong.

The original LADv1 does not have the same problem, but it may have been modified since the igraph port was made. https://perso.liris.cnrs.fr/christine.solnon/LAD

It crashes in `igraph_i_lad_ensureGACallDiff`, on this line

    if (numV[w]==false) {

Here `w` was taken from the `D->globalMatchingP` vector, which contained a `-1` value (hence the out-of-bounds). I think it should not contain a -1 at this point in the program. In the original LAD it never does.

**Comment by szhorvat** [comment]
@ntamas 

> For the record, the original problem was that `igraph_i_lad_augmentingPath` and `igraph_i_lad_removeValue` set the value pointed to by the result argument to `true` in certain conditions but they never set it to `false`. Based on my limited understanding of this part of the code, these functions sort-of-assume that the initial value of `*result` is `false` and they only need to set it to `true` in certain conditions.

This is not quite accurate.  In the original LAD code these functions _return_ true/false directly. The igraph was is to return through a pointer argument and use the return value for an error code instead. Thus now these functions return the result through their `*result` argument.  

My conclusion is that `removeValue` and `augmentedPath` should *always* set the value of `*result` before they exit and should never assume any incoming value.

@ntamas Do you happen to have an example that crashed before you made the fix, just so I can test it before I sent a pull request?

In the meantime, I still wasn't able to solve the main problem (see example program in previous message)

**Comment by szhorvat** [comment]
@ntamas Success (after all these years)!

The issue you tried to fix was indeed the source of crashes, but your fix was incorrect (and caused other crashes). The correct way to fix it is to ensure that `*result` is set in `augmentingPath` and remove the line you added.

Pull request coming soon.

**Comment by ntamas** [comment]
Wow, great, thanks for the great job!
Checking the PR right now.
