### ISSUE TITLE
igraph_write_graph_graphml() is locale dependent

### ISSUE THREAD

**Issue by Ariki** [igraph/igraph#930]
The function `igraph_write_graph_graphml()` writes floating point attribute values using locale dependent decimal separator. In locales that use comma as separator, this causes generation of locale dependent XML which can't be read back properly, even on the same system.The numbers containing a comma instead of a period are truncated when read back.

Here is a code example demonstrating the issue. This assumes that the locale using decimal comma (`"ru_RU.UTF-8"` in this example) presents in the system.

``` c
#include <locale.h>
#include <igraph.h>

int main(void) {
    igraph_t graph;
    igraph_i_set_attribute_table(&igraph_cattribute_table);
    igraph_full(&graph, 1, 0, 0);
    SETGAN(&graph, "myattr", 3.14);
    setlocale(LC_NUMERIC, "ru_RU.UTF-8"); // This locale uses decimal comma
    igraph_write_graph_graphml(&graph, stdout, 0); // The output contains "3,14"
    setlocale(LC_NUMERIC, "C");
    igraph_write_graph_graphml(&graph, stdout, 0); // The output contains "3.14"
    igraph_destroy(&graph);
    return 0;
}
```

**Comment by ntamas** [comment]
Note to self (for future testing and reproduction): ANSI C says that all programs start by default in the standard `C` locale, so this becomes a problem only if the user sets the locale using `setlocale()` first; it is not enough to set the `LANG`, `LC_ALL` or `LC_NUMERIC` environment variables.

**Comment by Ariki** [comment]
Yes, you are right. I've discovered the issue when using Python bindings from some exotic environment (ArcGIS ArcToolbox) which seems to set locale for me.

**Comment by ntamas** [comment]
Okay, you can then probably work around this from Python as follows:

```python
import locale
locale.setlocale(LC_NUMERIC, "C")
```

I'll commit a fix soon(ish).

**Comment by Ariki** [comment]
Yes, it works. Thank you.

**Comment by iosonofabio** [comment]
@ntamas I started PR #1203 for this. Not sure whether it was what you had in mind, so some advice would help.

**Comment by szhorvat** [comment]
Note: This has been reverted because it turns out that the fix was problematic.

 - It would leave the locale changed on failure.
 - `setlocale()` cannot be safely used in multithreaded programs (such as ArcGis).

It is now left to the user to ensure that the locale uses a decimal point (not a decimal comma) before calling any foreign format readers / writer.

This change will affect C/igraph 0.9.9 and python-igraph 0.9.11 and later. R already has mechanisms to prevent a decimal comma, so R/igraph is not affected.
