### ISSUE TITLE
sbm.game behavior for large n

### ISSUE THREAD

**Issue by youngser** [igraph/igraph#931]
I'm trying to generate a relatively large SBM using
```
B <- matrix(c(0.00045109, 0.00025452, 3.6314e-05, 2.0571e-05,
              0.00025452, 0.00054726, 2.0196e-05, 2.0525e-05,
              3.6314e-05, 2.0196e-05, 0.00046468, 0.00025912,
              2.0571e-05, 2.0525e-05, 0.00025912, 0.00056649),ncol=4,byrow=T)
bvec <- c(1.1826e+05,2.5675e+05,1.1258e+05,2.5228e+05)
set.seed(12345)
n <- sum(bvec)
g <- sbm.game(n,B,bvec)
#image(g[],lwd=2)
```
but A matrix of this graph doesn't look right.
When I scale this down, then it looks ok.
```
bvec2 <- floor(bvec/100)
g2 <- sbm.game(sum(bvec2),B,bvec2)
#image(g2[],lwd=2)
```
Is this a limitation of R?

I'm running this on R 3.2.2 on mac and
> igraph.version()
[1] "1.0.0"

**Comment by ntamas** [comment]
What do you mean by "doesn't look right"?

**Comment by youngser** [comment]
Pardon me for my brevity.
The latter shows a nice four block structure on the diagonal of the adjacency matrix, but the former doesn't.

**Comment by ntamas** [comment]
Is `bevy` in your first block of code equal to `bvec`?

**Comment by ntamas** [comment]
Okay, I can reproduce this, but I cannot decide yet whether it's the plot that is wrong or the graph itself.

**Comment by youngser** [comment]
Great!
I do know from the subsequent inference that the graph is indeed wrong, not the plot!

BTW, it still works up to `bvec2 <- floor(bvec/10)`

**Comment by ntamas** [comment]
Reproduced the bug in the C layer (without using the R interface) so it is not R-related at all.

**Comment by ntamas** [comment]
For the record: lines like this in `sbm.c` caused the bug:

```c
maxedges = fromsize * tosize
```

Even though `maxedges` was set to a `double` (to avoid overflows), `fromsize` and `tosize` were ordinary `int`s. Multiplication was thus performed on two `int`s, resulting in an overflow, and this invalid value was then cast into a `double`. The issue can be fixed by ensuring that `fromsize` and `tosize` are also `double`s.

**Comment by youngser** [comment]
Thanks for the fix!
Alas, I just reinstalled the dev version via `devtools::install_github("igraph/rigraph")`, but the problem still exists...
How can I apply the latest fix ??
Thanks in advance!

```
> igraph.version()
[1] "1.1.0"
```

**Comment by ntamas** [comment]
The igraph/rigraph repo is pinned to a specific revision of the igraph/igraph repo, so it does not automatically jump to the most recent revision of igraph/igraph (to avoid breaking igraph/rigraph with a backwards-incompatible change in igraph/igraph). I'm not that familiar with R so there might be an easier solution, but I would simply fork `igraph/rigraph`, change the submodule reference of `igraph/igraph` to point to the most recent revision, and then instruct R to compile the forked repo.

**Comment by szhorvat** [comment]
It may be necessary to make additional changes as some of the C interface
has changed slightly, in particular the Bliss isomorphism functions.  Now
there are arguments for vertex colours.
