### ISSUE TITLE
Memory error in iGraph Python when adding large number of edges

### ISSUE THREAD

**Issue by Yoln1** [igraph/igraph#934]
Regarding this thread : http://goo.gl/uEyFua

I am experiencing a quite similar issue with the following code, trying to import a large Graph :

```
for (edge_id) in cursorSQL:
 L.add((edge_id[2], str(edge_id[1])))

g = igraph.Graph.TupleList(L)
```

I get the following errors :

```
Traceback (most recent call last):


File "C.py", line 707, in __getitem__  return self._ids[item]
KeyError: '184840900'

During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
     g = igraph.Graph.TupleList(L)
  File "C:\Python34\lib\site-packages\igraph\__init__.py", line 2473, in TupleList

  edge_list.append((idgen[item[0]], idgen[item[1]]))

  File "C:\Python34\lib\site-packages\igraph\datatypes.py", line 709, in __getitem__
  self._ids[item] = next(self._generator)

     MemoryError
```

Just to make it clear. This code works perfectly until number of edges is too large (~4millions.)
Does anybody have any solution please ? 

Thanks.

**Comment by ntamas** [comment]
Cannot say much without seeing the file that causes the problem. I would not expect a graph with only 4 million edges to cause any problems, though.

**Comment by Yoln1** [comment]
Hi ntamas, Trying to send you the file made me figure out I had a system-memory issue. 

I then switched to python-64bits instead of 32 bits, and everything is working fine now. Problem was that I was reaching the 2GB limit per process when calling   `g = igraph.Graph.TupleList(L)`

**Comment by ntamas** [comment]
igraph should not reach that limit on its own, but `Graph.TupleList` uses auxiliary data structures to match the "names" of the vertices to numerical IDs while the graph is being built. It could have happened that this caused the memory usage to go above 2GB temporarily. (Note that Python's memory manager does not always return freed memory to the OS, so it could even happen that Python's memory usage appears greater than 2GB even after loading the graph - this is okay).

**Comment by marinobeach** [comment]
Hello,
I am having the same issue. I am not a professional programmer, just a student so I might have mistakes in my code. Let me attach it to you:
#!/usr/bin/python

from igraph import *

def main():
	file = open("follows.txt")
	seen_nodes = []

	g = Graph()
	for line in file:
		
		node_id = [int(x) for x in line.split(',') if x.strip()]
		key = node_id[0]
		
		if node_id[0] not in seen_nodes:					
			seen_nodes.append(node_id[0])			
			g.add_vertices(node_id[0])
			
			
		if node_id[1] not in seen_nodes:
			seen_nodes.append(node_id[1])		
			g.add_vertices(node_id[1])
						
		g.add_edge(node_id[0], node_id[1])
			
	layout = g.layout_kamada_kawai()	
	layout = g.layout("kk")
	plot(g, layout = layout)






if __name__ == "__main__":
    main()



I get the error of out of memory in the line g.add_edge(node_id[0], node_id[1]). My file just consists of about 60k lines with this style: 
1,2
1,5
1,8
9, 12
etc. Which means the node from the left is following the node from the right.
Thanks in advance for all the possible help
PD: Note that if I delete lots of nodes in my file the code works and I get the picture plotted.

**Comment by ntamas** [comment]
`g.add_vertices(node_id[0])` will not add a new node with ID = `node_id[0]`; it will add `node_id[0]` new nodes instead.

Either replace the commas in your file with spaces and then use `Graph.Read_NCOL()` (the IDs of the nodes will then be stored in the `name` vertex attribute), or use `Graph.Read_TupleList()` after parsing your file into tuples containing vertex IDs.

**Comment by marinobeach** [comment]
Thanks a lot for your help. In the end, because of you, I made it work. I finally used the belowing code:
#!/usr/bin/python

from igraph import *

def main():
	file = open("follows.txt")
	tupleMapping = []
	
	for line in file:
		
		node_id = [int(x) for x in line.split(',') if x.strip()]
		source = int(node_id[0])
		target = int(node_id[1])
    
		l = [node_id[0], node_id[1]]
		tupleMapping.append(tuple(l))
		#g.add_edge(node_id[0], node_id[1])
	g = Graph.TupleList(tupleMapping)
	#g = Graph()		
	layout = g.layout_kamada_kawai()
	layout = g.layout("kk")	
	plot(g, layout = layout)






if __name__ == "__main__":
    main()		



The problem is visual now, I got 9832 nodes, I need to make the image larger and wider and decrease the size of the nodes (if not the final image is not much visual, it is all aglomerated) ,which are represented by red balls. Do you know how can I make the nodes smaller and the image bigger? Thanks a lot again :)

**Comment by ntamas** [comment]
Please read the [relevant](https://pythonhosted.org/python-igraph/igraph.drawing-module.html#plot) [parts](https://pythonhosted.org/python-igraph/igraph.Graph-class.html#__plot__) of the documentation. If you still have questions, send them to the support mailing list at igraph-help@nongnu.org
