### ISSUE TITLE
delete used where delete [] needed

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#936]
Here:

https://github.com/igraph/igraph/blob/master/src/pottsmodel_2.cpp#L2099

`delete` should be `delete []`

Allocation is here:

https://github.com/igraph/igraph/blob/master/src/pottsmodel_2.cpp#L2055

Found using clang static analyser.

I didn't submit a pull request because this is an accidental find and didn't have time to test it or look in detail ...

**Comment by ntamas** [comment]
Good catch. Fixing it straight away.
