### ISSUE TITLE
problems with new windows toolchain

### ISSUE THREAD

**Issue by dtenenba** [igraph/igraph#937]
Hello,

This issue regards the `R` package `igraph`. I am filing it here (and not at https://github.com/igraph/rigraph) because the BugReports field in its DESCRIPTION file suggests filing here).

We're building Bioconductor on the [new Windows toolchain](https://github.com/rwinlib/r-base) which will be the one that R-3.3.0 will be released with, if all goes well. igraph actually installs just fine, but some of our packages are failing when they call `graph_from_graphnel()`. You can reproduce it like this, provided you are running on the new toolchain ([setup described here](https://github.com/Bioconductor/Bioconductor/blob/master/documentation/new-toolchain-setup.md)):

```
library(graph)
library(igraph)
g1 = randomEGraph(LETTERS[1:15], edges=100)
graph_from_graphnel(g1)
```

The output is:

```
Error in base::.Call("R_igraph_make_weak_ref", key, value, finalizer,  :
  "R_igraph_make_weak_ref" not available for .Call() for package "igraph"
```

`traceback()` and `sessionInfo()`:

```
> traceback()
5: base::.Call("R_igraph_make_weak_ref", key, value, finalizer,
       PACKAGE = "igraph")
4: make_weak_ref(ref, NULL)
3: add_vses_graph_ref(res, graph)
2: V(`*tmp*`)
1: graph_from_graphnel(g1)
> sessionInfo()
R version 3.3.0 alpha (2016-03-28 r70390)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] igraph_1.0.1        graph_1.49.1        BiocGenerics_0.17.3

loaded via a namespace (and not attached):
[1] magrittr_1.5 stats4_3.3.0
```

**Comment by dtenenba** [comment]
An easier way to reproduce it is:

```
library(igraph)
example(graph_from_graphnel, run.dontrun=TRUE)
```

If the `\dontrun` tag were removed from this example then it would helpfully fail `R CMD check` when built under the new toolchain. I'm not sure why this example is set to `\dontrun`, since `graph` is in the `Suggests:` field, so presumably available.

**Comment by dtenenba** [comment]
One more data point: this only seems to happen in the `x64` sub-architecture, not `i386`.

**Comment by ntamas** [comment]
As this issue is R-related, I'm moving it to igraph/rigraph so @gaborcsardi can take care of it there.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#148
