### ISSUE TITLE
is.bipartite return False for trees (R language)

### ISSUE THREAD

**Issue by mmiotk** [igraph/igraph#940]
When I run command: 
`g <- graph.tree(6,mode = "undirected")`
Then when I run this: 
`is.bipartite(g)`
return FALSE but every undirected tree is bipartite.

**Comment by ntamas** [comment]
This is not a bug; the documentation of `is.bipartite` says:

> ‘is_bipartite’ checks whether the graph is bipartite or not. It just checks whether the graph has a vertex attribute called ‘type’.
