### ISSUE TITLE
Edge betweenness based community detection: why not same result for reversed graph?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#942]
Suppose we are working with directed and edge-weighted graphs.  Reversing the direction of every edge in such a graph does not change the betweenness of edges.

Why does edge betweenness based community detection give different results then for the reversed graph relative to the original?  What am I missing here?

Example in R:

```
set.seed(42)
n <- 15
am <- matrix(rexp(n*n), ncol=n)
diag(am) <- 0
am[am < 1] <- 0
g1 <- graph.adjacency(am, weighted=T)
g2 <- graph.adjacency(t(am), weighted=T)
c1 <- edge.betweenness.community(g1)
c2 <- edge.betweenness.community(g2)
```

We get different communities:

```
> c1$membership
 [1] 1 2 1 3 4 5 1 6 7 1 8 1 1 1 1
> c2$membership
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
```

**Comment by szhorvat** [comment]
Is this only about breaking ties when two edges have the same betweenness?

**Comment by szhorvat** [comment]
Yes, it seems to be about the decision in which order to remove edges with the same betweenness, plus about the fact that in the transposed case all the modularity scores are negative so the graph is never broken into clusters.

**Comment by ntamas** [comment]
> Is this only about breaking ties when two edges have the same betweenness?
Yes, exactly, this is the reason.
