### ISSUE TITLE
cluster_spinglass crashes R when implementation='neg'

### ISSUE THREAD

**Issue by brooksambrose** [igraph/igraph#943]
Any command using the "negative" implementation of the spinglass community detection crashes R in RStudio, e.g. `cluster_spinglass(make_ring(10),implementation='neg')`.

I'm running:

`R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"  
Platform: x86_64-apple-darwin13.4.0 (64-bit)`

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#151
