### ISSUE TITLE
Write in Matrix Market format - R

### ISSUE THREAD

**Issue by smsaladi** [igraph/igraph#946]
Is it possible to write an graph manipulated with igraph in R in the Matrix Market format?

There seems to be several bits of [code part of the repo](https://github.com/igraph/igraph/search?utf8=✓&q=matrix+market) that may be involved with this, but I can't seem to figure out what the correct argument to [write.graph](http://www.inside-r.org/packages/cran/igraph/docs/write.graph) would be among the options:

```
format=c("edgelist", "pajek", "ncol", "lgl", "graphml", "dimacs", "gml", "dot", "leda")
```

**Comment by ntamas** [comment]
Please use the [mailing list](https://lists.nongnu.org/mailman/listinfo/igraph-help) for support questions.

The Matrix Market formats are not supported directly; it is probably easy to write an R function that prints `%%MatrixMarket matrix coordinate real general`, a newline, the number of vertices (twice) and the number of edges, another newline, and then the matrix obtained by `cbind(get.edgelist(graph, names=FALSE), E(graph)$weight` (assuming that the `weight` attribute contains the weights).

**Comment by szhorvat** [comment]
For reference, the standard `Matrix` package has `Matrix:writeMM` and `Matrix::readMM` for writing/reading MatrixMarket files.

**Comment by szhorvat** [comment]
I'm going to consider this as a feature request for reading/writing MatrixMatrix. IMO it's best _not_ to add this to the C core, for the following reasons:

All high-level languages that igraph currently has an interface to already have easy ways to read/write this format:

 - In R, `Matrix::writeMM` and `Matrix::readMM`
 - In Python, `scipy.io.writemm` and `scipy.io.readmm`
 - In Mathematica, the [MTX format](https://reference.wolfram.com/language/ref/format/MTX.html)

The MatrixMarket website provides programs for I/O in C: https://math.nist.gov/MatrixMarket/mmio-c.html

If igraph were to implement readers/writers for this format, we would need to deal with the interpretation of self-loops, which is non-trivial (count once or twice), and depends on whether the matrix is chosen to be interpreted as a directed or undirected graph. It is cleaner to leave this to the existing matrix/graph conversion functions.
