### ISSUE TITLE
multilevel.community

### ISSUE THREAD

**Issue by halves2005** [igraph/igraph#947]
Hi,
it´s possible to stop the "multilevel.community" function for the 1st Pass of the Louvain algorithm?
I´m interested to know the result of the "membership vector", at the end of 1st PASS and not at the end.

thanks,
Hélder

**Comment by ntamas** [comment]
It is not possible to stop the algorithm after the first pass, but you can ask it to return all the hierarchy levels using return.levels=TRUE - then you can check the first one and discard the rest.

T.

**Comment by halves2005** [comment]
Thanks a lot for your tip, Tamás.
