### ISSUE TITLE
multilevel community function on graph - hierarchy levels "return.levels=TRUE"

### ISSUE THREAD

**Issue by halves2005** [igraph/igraph#948]
Hello,
I´m trying to implement the instruction "return.levels=TRUE" to obtain the hierarchy levels of a community detection problem, using R, but I don´t know how to do it.
The idea is to know the membership vector using multilevel community function of graph.
Any suggestion or example?

Thanks

**Comment by ntamas** [comment]
Please use the [igraph-help](https://lists.nongnu.org/mailman/listinfo/igraph-help) mailing list for support questions; the issue tracker is reserved for bugs and feature enhancements only.

Anyway, I think I was the one who gave you that instruction, but apparently the argument works for the Python interface only; it is not implemented in the R interface.

**Comment by halves2005** [comment]
ok I will.

thanks!
