### ISSUE TITLE
Update python-igraph in ppa:repository

### ISSUE THREAD

**Issue by gerardogtn** [igraph/igraph#949]
I've been trying to install python-igraph on a vagrant virtual machine (ubuntu/trusty32) nonetheless, i keep getting a UnicodeError when running `pip install python-igraph`, the same as in [this](https://github.com/igraph/igraph/issues/680) issue. The only way to install python-igraph was to follow the instructions in the [igraph wiki](http://igraph.wikidot.com/installing-python-igraph-on-linux#toc0). That is, to run: 

```
sudo add-apt-repository ppa:igraph/ppa
sudo apt-get update
sudo apt-get install python-igraph
```

 However, the latest version in this repo is 0.6.5. I can now use python-igraph but would like to use some of the features in the 0.7.1 version, so it would be nice to update the ppa repo with the latest version.

**Comment by ntamas** [comment]
A decision has been made to drop support for packaging `python-igraph` on our end, so I'm gonna close this. Instead, we are striving to ensure that `pip install python-igraph` works nicely on Debian and Ubuntu.
