### ISSUE TITLE
Diameter calculation is slower than distance matrix calculation

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#952]
With the Dijkstra algorithm, diameter calculation for a graph is much slower than calculating the full distance matrix.

Illustration in Mathematica:

```mathematica
(* make connected weighted graph of ~4000 vertices *)

g = First@ConnectedGraphComponents@RandomGraph[BernoulliGraphDistribution[4000, 0.001]];
wg = SetProperty[g, EdgeWeight -> RandomReal[1, EdgeCount[g]]];

IGDiameter[wg] // AbsoluteTiming
{37.7989, 6.86788}

IGDistanceMatrix[wg, Method -> "Dijkstra"] // Max // AbsoluteTiming
{4.69898, 6.86788}
```

`IGDiameter` calls `igraph_diameter_dijkstra` and takes 38 seconds here.

`IGDistanceMatrix` calls `igraph_shortest_paths_dijkstra` and takes 4.7 seconds here.

As you can see, they return the same result, but the full distance matrix calculation is much faster (despite it having to transfer a huge result matrix to Mathematica, which does take quite a bit of time).

Let's try to reproduce in R:

```R
g<-erdos.renyi.game(4000,0.001,'gnp')
comps<-decompose.graph(g)
cg<-comps[[1]]
E(cg)$weight <- runif(ecount(cg))

system.time(diameter(cg)) # took 32 seconds

system.time(mat<-shortest.paths(cg, algorithm = 'dijkstra')) # took 3.7 seconds
```

I see the same problem.

What is going on?

**Comment by ntamas** [comment]
It's probably a bug in the C layer then; I'll need to create a small example that I can profile to see where the bottleneck is.

**Comment by ntamas** [comment]
Okay, so `igraph_diameter_dijkstra` uses an `igraph_indheap_t` while `igraph_shortest_paths_dijkstra` uses an `igraph_2wheap_t`. This probably explains the difference. I'll try to rewrite `igraph_diameter_dijkstra`.

**Comment by szhorvat** [comment]
As measured from Mathematica, I get 3.2 s now. This is with the same random seed (since it's tested on a random graph with random weights).

As a comparison, Mathematica's builtin gives 2.5 seconds (also Dijkstra).  So igraph is now competitive with it.

One thing to know about this measurement is that it includes the time to convert the Mathematica graph to an igraph graph, so the underlyng igraph function probably takes a bit less than 3.2 s.
