### ISSUE TITLE
transitivity gives negative value

### ISSUE THREAD

**Issue by yfiua** [igraph/igraph#953]
```
In [7]: G.is_directed()
Out[7]: False

In [8]: G.is_simple()
Out[8]: True

In [9]: lcc = G.transitivity_local_undirected()

In [10]: min(lcc)
Out[10]: -4.7709327191114426e-05
````

**Comment by ntamas** [comment]
Is `G` undirected? In an earlier version of your post, you've had this:

```
In [73]: G.as_undirected()
Out[73]: <igraph.Graph at 0x7f0bb22f9de0>
```

`as.undirected()` returns a _new_ graph and keeps the original intact, so `G` will still be directed after this.

**Comment by yfiua** [comment]
@ntamas, sorry for the confusion.
Please see my edited post. I removed the earlier line because `G` is undirected anyway.

**Comment by ntamas** [comment]
Most likely an overflow error in the C layer since the problematic node has 915499 neighbors.

**Comment by ntamas** [comment]
Indeed it was an overflow in the C layer; an expression like `(double) deg * (deg-1) / 2.0` where `deg` is an integer will upcast only the _result_ to a `double` after the overflow has already occurred. (The correct expression would have been `((double) deg) * (deg-1) / 2.0`. Decided to do it "the proper way" by not calculating the number of possible triangles per node explicitly.
