### ISSUE TITLE
R igraph arrow.mode plot parameter not working properly

### ISSUE THREAD

**Issue by fpbarthel** [igraph/igraph#954]
Hi!

I'm have data pairs that have variable direction (sometimes left to right, sometimes right to left and sometimes no direction) that I want to plot using igraph. I was searching for a way to implement this but did not succeed, but then I ran into the "arrow.mode" plot parameter that according to the manual ([found here](http://igraph.org/r/doc/plot.common.html)) should allow specification of variable arrows for each edge upon plotting.

However, trying to implement this for the following simple example fails with an error. Am I doing something wrong?

    library(igraph)
    df = data.frame(id1=c('A','B','C','Z','Z'), id2=c('B','C','D','Y','X'), direction = c(1,1,0,2,2))
    g = graph_from_data_frame(df, directed=T)
    plot(g, arrow.mode=df$direction)

    Error in i.parse.plot.params(graph, list(...))
    Unknown plot parameters: arrow.mode

I am using igraph_1.0.1 and R 3.3.1

**Comment by gaborcsardi** [comment]
From the cited manual page:

> Edge parameters require to add the ‘edge.’ prefix when used as arguments or set by igraph_options. The edge parameters:

So you need 
```r
library(igraph)
df = data.frame(id1 = c('A', 'B', 'C', 'Z', 'Z'), id2 = c('B', 'C', 'D', 'Y', 'X'), direction = c(1, 1, 0, 2, 2))
g = graph_from_data_frame(df, directed = TRUE)
plot(g, edge.arrow.mode = df$direction)
```

**Comment by fpbarthel** [comment]
Thanks! Good to know I was doing it wrong. I missed that part in the manual. I also saw that I can supply (unprefixed) arrow.mode as an attribute, which is perfect for my purpose.

I have a related feature request. For future versions, can it be made so the actual edge direction can be changed?

Eg.:

    df = data.frame(id1=c('A','B','C','Z','Z'), id2=c('B','C','D','Y','X'), arrow.mode = c(1,1,0,2,3))
    g = graph_from_data_frame(df, directed=T)
    plot(g) ## This plots correctly, however

   ## The edge directions themselves are still shown "wrong"
    g
    IGRAPH DN-- 7 5 -- 
    + attr: name (v/c), arrow.mode (e/n)
    + edges (vertex names):
    [1] A->B B->C C->D Z->Y Z->X
