### ISSUE TITLE
Build master with VS fails

### ISSUE THREAD

**Issue by abeham** [igraph/igraph#955]
I use VS2013. As noted in install.windows I installed cygwin, cloned the repository (btw the branch origin/develop mentioned there does not exist), ran bootstrap, configure and make msvc. Then I took the zip (strangely this was called 0.8.0-pre - I thought igraph was at 1.0?) that was generated, extracted it to a new folder and tried to compile it. Compilation worked for me with igraph-0.7.1-msvc which I downloaded from the website.

First, the vcproj could not be upgraded because it contains the following files:
"make[0]:"
"Entering"
"Leaving"
"directory"
"src/.../"

I cleaned the proj file of these entries and could get it to upgrade.

Second, I got compile errors when amd.h, amd_internal.h, cholmod*.h and colamd.h were not found. I copied them from their respective sub-directories into the include directory and added them to the project. Then SuiteSparse_config.h was not found. Finally, camd.h, ccolamd.h and metis.h are not be found. I could not locate these files anywhere. I don't know if copying them to include is a fix to this problem.

Third, layout_gem.c and layout_dh.c are missing M_PI and M_PI_2. They should probably include igraph_math.h, which defines M_PI, but not M_PI_2, which in turn is nowhere defined in the whole solution. I tried to grep it in the repository, but I only got the usage, but not the definition.

I was specifically looking for a recent version, because I tried igraph in R and layout_dh seemed to work very well for my purposes (layout_dh is not available in 0.7.1). Fruchterman-Reingold also did a good job, but testing with 0.7.1 it gave me entirely different results than the newer version in R. I wanted to check on the parameters used in R only to find out that there is a different interface altogether. Unfortunately, I wasn't able to build the current master as outlined above.

**Comment by ntamas** [comment]
Lots of work has been done recently by @janschulz recently to improve the build process of igraph in MSVC (the core developers don't use Windows so no testing is done regularly on MSVC). Please see his pull request and his branch for a version that would probably work with MSVC: https://github.com/igraph/igraph/pull/951

> Then I took the zip (strangely this was called 0.8.0-pre - I thought igraph was at 1.0?)
igraph's C core is at version 0.7.1 so the version number is correct (0.8.0 pre-release). The R interface of igraph has version 1.0.

**Comment by ntamas** [comment]
Merged #951 into master so it should be okay now. Feel free to reopen if the build fails for you.
