### ISSUE TITLE
Feature Request: Import/Export graph as JSON

### ISSUE THREAD

**Issue by geofurb** [igraph/igraph#957]
It would be nice if we could import and export graphs in JSON node-link format per:
http://bl.ocks.org/mbostock/4062045

**Comment by szhorvat** [comment]
The question is: What software uses this specific format?  Is it widely used?

It shouldn't be difficult to produce JSON form an igraph graph with any of the high-level interfaces.  With Mathematica [it was just a few lines](http://mathematica.stackexchange.com/a/23203/12) even 3 years ago and now it should be simpler still.

There are many different ways to encode a graph into JSON.  Does it make any sense to create an exporter just for one type of encoding unless it is widely used?

**Comment by geofurb** [comment]
This is the most flexible format for import/export in the very popular Python graph library, NetworkX.

**Comment by szhorvat** [comment]
Is it fully documented anywhere?  Is there any other software then NetworkX which uses this specific encoding into JSON?

**Comment by spth** [comment]
I'd also like to see support for reading json graphs.

In particular, my use case would be to read a graph representation of OpenStreetMap (OSM) data with igraph. Clearly parsing OSM data formats (.osm, or .o5m or .pbf) is beyond the scope of igraph.
But there is a tool for converting osm data to json graphs (https://github.com/rovaniemi/osm-graph-parser), so being able to read json graphs into igraph would help.

I think OSM is a rather important source for graph data, so others also might be interested in having this capability in igraph.

Philipp

**Comment by ntamas** [comment]
The JSON format that @spth refers to is completely different from the JSON format that NetworkX uses and that @geofurb refers to. The key problem here is that there is no standard representation of graphs in JSON format (as far as I know), so everyone makes up their own representation. Creating a _single_ JSON parser for graphs is simply not possible at this stage - if we already had one based on, say, the format that was shown on the page in @geofurb's comments, it could not have been used to parse JSON files in the format shown by @spth.

**Comment by aourednik** [comment]
D3.js is the most used js-based visualisation framework in my experience; i would vote for d3-js format(s). There are two of them : [non-hierarchical](https://bl.ocks.org/mbostock/4062045) and [tree](https://bl.ocks.org/mbostock/4339083). Cytoscape exports to both. There already seems to be an igraph_to_networkD3 function written in R: https://github.com/christophergandrud/networkD3/blob/master/R/utils.R 
Integrating both graph exports to D3 directly in igpraph would be great.

**Comment by szhorvat** [comment]
I vote for closing this issue, for the following reasons:

 - There are many possible representations of a graph as JSON. Is there a de-facto standard? Different systems seem to use different and incompatible representations. If there are some widely used JSON-based formats, a new feature request should be opened for those specifically.
 - All high-level languages to which igraph has interfaces have good JSON support, and as far as I can tell, implementing JSON-based exporters is almost trivial.  If this is not the case (implementation is not easy), and issue should be opened for the relevant high-level interface.

I'll let the stale bot close this if there is no further interaction.

**Comment by ntamas** [comment]
[`gravis`](https://github.com/robert-haas/gravis) also uses a different JSON format. I don't think that there will be a "standard" JSON graph format anywhere in the near-term.

**Comment by szhorvat** [comment]
Actually, I found http://jsongraphformat.info/ through `gravis`: it uses a sub-format of the JGF specification. But I'm not sure how feasible it is to create a parser that can read any sub-format. This should be researched. Anyway, this is not a priority. If we decide that we want the JSON reader after all, I suggest writing up "good first issues" for the high-level interfaces and implementing it there.
