### ISSUE TITLE
dot export: put reserved words in quote

### ISSUE THREAD

**Issue by flying-sheep** [igraph/igraph#959]
in [`igraph_i_dot_escape`](https://github.com/igraph/igraph/blob/19946d044c4b6ad7aa6f917d312453a83d8a7e6d/src/foreign.c#L2726-L2771) you have to check if the name is e.g. “graph” in which case it needs to be put in quotes as well

**Comment by gaborcsardi** [comment]
Can we just quote everything?

**Comment by flying-sheep** [comment]
or that, but then the whole escaping function is for naught. it should be rather easy to get a list of reserved words in the DOT language.

**Comment by ntamas** [comment]
From the [specs](http://www.graphviz.org/doc/info/lang.html) it seemed to me that the only keywords were `node`, `edge`, `graph`, `digraph`, `subgraph` and `strict` so now we are also escaping these. Thanks!
