### ISSUE TITLE
Problem with python 3.5 on Ubuntu

### ISSUE THREAD

**Issue by AngelRibeiro10** [igraph/igraph#961]
How to solve ? and what is the difference beetween this version and the one in the pypi  at
[https://pypi.python.org/pypi/igraph/0.1.11]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/venv3.5/lib/python3.5/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

**Comment by ntamas** [comment]
> what is the difference beetween this version and the one in the pypi 

That's a completely different package, not related to us. You probably need `python-igraph` on PyPI.
