### ISSUE TITLE
is_separator shouldn't give true when single node remains after vertex removal

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#962]
This refers to `igraph_is_separator` and `igraph_is_minimal_separator`.

http://igraph.org/c/doc/igraph-Separators.html#igraph_is_separator

The following result is incorrect:

```
input graph:  1 - 2
condidate separator set: {1}
result: true
```

Removing vertex 1 does not disconnect the graph `1 - 2`.

Generally, these functions return true for any candidate set whose removal leaves only a single node.  They seem to consider a graph with a single node disconnected.

Example in R:

    g <- make_graph(c(1,2), directed = F)
    is_separator(g, c(1))

    [1] TRUE

**EDIT:** Oops!  I didn't see your responses on the mailing list when I wrote this ...

**Comment by ntamas** [comment]
Fixed in f3b9f14, thanks!
