### ISSUE TITLE
Why does Kamada-Kawai fail on a Bethe lattice?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#963]
This refers to what's in the master branch of the C core, not the released version.  This is also what's included in the current R version, but not in Python.  R code is at the end.

Let's make a partial Bethe lattice.  In Mathematica,

```
links = {0 -> 1, 0 -> 2, 0 -> 3, 1 -> 4, 1 -> 5, 2 -> 6, 2 -> 7, 
   3 -> 8, 3 -> 9, 4 -> 10, 4 -> 11, 5 -> 12, 5 -> 13, 6 -> 14, 
   6 -> 15, 7 -> 16, 7 -> 17, 8 -> 18, 8 -> 19, 9 -> 20, 9 -> 21, 
   10 -> 22, 10 -> 23, 11 -> 24, 11 -> 25, 12 -> 26, 12 -> 27, 
   13 -> 28, 13 -> 29, 14 -> 30, 14 -> 31, 15 -> 32, 15 -> 33, 
   16 -> 34, 16 -> 35, 17 -> 36, 17 -> 37, 18 -> 38, 18 -> 39, 
   19 -> 40, 19 -> 41, 20 -> 42, 20 -> 43, 21 -> 44, 21 -> 45, 
   22 -> 46, 22 -> 47, 23 -> 48, 23 -> 49, 24 -> 50, 24 -> 51, 
   25 -> 52, 25 -> 53, 26 -> 54, 26 -> 55, 27 -> 56, 27 -> 57, 
   28 -> 58, 28 -> 59, 29 -> 60, 29 -> 61, 30 -> 62, 30 -> 63, 
   31 -> 64, 31 -> 65, 32 -> 66, 32 -> 67, 33 -> 68, 33 -> 69, 
   34 -> 70, 34 -> 71, 35 -> 72, 35 -> 73, 36 -> 74, 36 -> 75, 
   37 -> 76, 37 -> 77, 38 -> 78, 38 -> 79, 39 -> 80, 39 -> 81, 
   40 -> 82, 40 -> 83, 41 -> 84, 41 -> 85, 42 -> 86, 42 -> 87, 
   43 -> 88, 43 -> 89, 44 -> 90, 44 -> 91, 45 -> 92, 45 -> 93};

g = Graph[links]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432224/2a944348-78e1-11e6-99d4-ec895d519bfc.png)

Let's try to plot it with igraph's Kamada-Kawai layout:

```
<<IGraphM`
IGLayoutKamadaKawai[g]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432256/47cc4884-78e1-11e6-96db-c37007617745.png)

It looks quite awful.  Let's increase the number of iterations:

```
IGLayoutKamadaKawai[g, MaxIterations -> 100000]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432275/60f2939a-78e1-11e6-8d77-e8190227a395.png)

No change.  Note that the `epsilon` parameter is set to zero, so this many iterations are really carried out.

Let's compare with Mathematica's Kamada-Kawai-like layout:

```
Graph[links, GraphLayout -> "SpringEmbedding"]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432343/c0e301d6-78e1-11e6-9236-b44c9f64f954.png)

More iterations:

```
Graph[links, GraphLayout -> {"SpringEmbedding", "MaxIteration" -> 10000}]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432336/b8b91a54-78e1-11e6-8cd9-c6a3a03fe6f6.png)

Still not the best but better.

**Question:** Is there something wrong with igraph's Kamada-Kawai?  Why does it seems to be stuck?  Is this a problem _with the method_ or _with the implementation_?

I do realize that KK is just not the best for this graph, but some of the nodes appear to be stuck in their initial circular arrangement, which raises the suspicion of a bug.

---

R code for a basic KK layout:

```
library(igraph)

g<-make_graph(1+c(0, 1, 0, 2, 0, 3, 1, 4, 1, 5, 2, 6, 2, 7, 3, 8, 3, 9, 4, 10, 4, 11, 5, 12, 5, 13, 6, 14, 6, 15, 7, 16, 7, 17, 8, 18, 8, 19, 9, 20, 9, 21, 10, 22, 10, 23, 11, 24, 11, 25, 12, 26, 12, 27, 13, 28, 13, 29, 14, 30, 14, 31, 15, 32, 15, 33, 16, 34, 16, 35, 17, 36, 17, 37, 18, 38, 18, 39, 19, 40, 19, 41, 20, 42, 20, 43, 21, 44, 21, 45, 22, 46, 22, 47, 23, 48, 23, 49, 24, 50, 24, 51, 25, 52, 25, 53, 26, 54, 26, 55, 27, 56, 27, 57, 28, 58, 28, 59, 29, 60, 29, 61, 30, 62, 30, 63, 31, 64, 31, 65, 32, 66, 32, 67, 33, 68, 33, 69, 34, 70, 34, 71, 35, 72, 35, 73, 36, 74, 36, 75, 37, 76, 37, 77, 38, 78, 38, 79, 39, 80, 39, 81, 40, 82, 40, 83, 41, 84, 41, 85, 42, 86, 42, 87, 43, 88, 43, 89, 44, 90, 44, 91, 45, 92, 45, 93));

plot(g, layout=layout_with_kk)
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432398/064e05b8-78e2-11e6-822e-cf1d49474cd2.png)

---

Final note: The best way for such a graph is circular Reingold-Tilford:

```
IGLayoutReingoldTilfordCircular[Graph[links], DirectedEdges -> True]
```

![image](https://cloud.githubusercontent.com/assets/1212871/18432581/081335fc-78e3-11e6-9856-1d646fae2cc8.png)

**Comment by ntamas** [comment]
It could be something with the ordering of the nodes and the unfortunate fact that the igraph implementation of the Kamada-Kawai layout uses a circle as the initial configuration (unless parameters like `minx`, `miny`, `maxx` or `maxy` are given). You can even see the remainder of the circle in the middle of each layout that igraph produced. I guess that for this particular graph and this particular initial configuration, it takes way too may iterations for igraph to "disentangle" the edge crossings of the initial circular layout, and a random starting point works better. Maybe we start with a circle to stay close to the original publication (is that true, @gaborcsardi ?).

**Comment by gaborcsardi** [comment]
It indeed starts from a circle, but you can supply your own start positions as well.

**Comment by szhorvat** [comment]
I am re-opening this because it has also been reported for R/igraph, and because the problem does indeed seem to stem from starting with a circle.

**Comment by szhorvat** [comment]
Working in R, this exhibits the problem:

```
plot(g, layout=layout_with_kk(g, coords=layout_in_circle(g)))
```

But these do not:

```
plot(g, layout=layout_with_kk(g, coords=0.99*layout_in_circle(g)))
plot(g, layout=layout_with_kk(g, coords=1.01*layout_in_circle(g)))
```

I am wondering why the starting position is a circle at all. Should we change this?

**Comment by ntamas** [comment]
We use a circle to follow the original paper of Kamada and Kawai as close as possible. The paper reads:

> The experiments have shown that the initial positions do not have a great influence on the resultant pictures, except for the special cases: e.g., all particles lie on a single line. Now we are using a simple initialization by which the particles are placed on the nodes of the regular n-polygon circumscribed by a circle whose diameter is L<sub>0</sub> (as for L<sub>0</sub>, see (3)).

I guess a small bit of randomization probably wouldn't hurt.

**Comment by szhorvat** [comment]
> regular n-polygon circumscribed by a circle whose diameter is L_0

We actually use a diameter of 2 (i.e. radius of 1) and not L_0

**Comment by szhorvat** [comment]
Or are the equation rescaled so that this is still consistent with the paper?

**Comment by szhorvat** [comment]
@ntamas I generated cycle graphs of increasing sizes and measured the radius of the produced layout (a circle). It is about `0.36*L0` where `L0 = sqrt(vcount)`. I propose that we use this as the radius of the initial circle layout. Are you find with this?

**Comment by ntamas** [comment]
Absolutely.

**Comment by szhorvat** [comment]
OK, this is going on `master` then.
