### ISSUE TITLE
C core install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by Jessime** [igraph/igraph#968]
I'm trying to install the C core library, but most of the tests are failing.

I've downloaded http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz to my `/usr/local/src` directory and unpacked it. I then do:

```bash
cd igraph-0.7.1
./configure
make
```

Using `make` produces some warnings while running, but still finishes. Doing `make check`, however, informs me that:

```
ERROR: All 234 tests were run,
226 failed unexpectedly.
```

I've attached the `tests/testsuite.log` file (renamed for github)
[testsuite_log.txt](https://github.com/igraph/igraph/files/564466/testsuite_log.txt), but I'm not familiar enough with the output to know what to investigate. Any suggestions on how to proceed?

**Comment by ntamas** [comment]
Most likely you need the C++ development libraries on your machine; try installing `libstdc++-dev` if you don't have it.

**Comment by Jessime** [comment]
I just did:

    sudo apt-get install libstdc++6-4.7-dev

which installed successfully. I then re-ran  `make && make check`, but it looks like the same tests are failing. 

Is this the proper way of installing `libstdc++-dev`? It's suggested [here](http://packages.ubuntu.com/trusty/libstdc++-dev).

**Comment by ntamas** [comment]
Try `make distclean` followed by `make && make check` just to make sure that everything is recompiled properly.

**Comment by Jessime** [comment]
Running `make distclean` works, but then running `make` again give: 

    make: *** No targets specified and no makefile found.  Stop.

I tried removing the entire directory and starting over, but got the same result.

**Comment by ntamas** [comment]
Extract the source distribution again or run the bootstrap script (bootstrap.sh) first to get a Makefile.

**Comment by Jessime** [comment]
I'm not entirely sure what worked here but I'm passing all tests now. I re-installed `libxml2-dev` and restarted my computer to get things working. 

Unfortunately, I'm now running into errors with the `python-igraph` install. I'll start a new issue for that though. Thanks for your help!
