### ISSUE TITLE
Initially slow computations times for get.adjacency

### ISSUE THREAD

**Issue by alexperrone** [igraph/igraph#970]
This issue initially discovered in comments for #967 

@gaborcsardi I can now reliably reproduce slow `get.adjacency(g)` on fresh R session with igraph 1.0.1. On one machine (Mac), it tends to be about 0.6-0.7 seconds and on another (Linux) it tends to be about 0.9-1.1 seconds. 

Steps: I open up R from command-line, wait about 20 seconds to make sure that R is completely idle, then paste in commands and hit enter. To get full timing, I wrap `system.time` around every pretty much every command which you can inspect.

    ls()  # show that workspace is clear
    system.time(library(igraph))
    system.time(g <- sample_gnm(8, 14))
    system.time(A <- get.adjacency(g))
    system.time(A <- get.adjacency(g))

If there is garbage collection going on, it must be due to `get.adjacency(g)`. I get similar timings even if I wait some time after `g <- sample_gnm(8, 14)`, and then execute `get.adjacency(g)`. I also get similar timings if I insert other igraph commands before the call to `get.adjacency` (I tried `decompose` and `clusters`, they don't take long even initially, ~0.001 seconds on this `g`). Nor do I get long initial computation times on fresh R session when executing base R commands like creating a million-element vector and take the mean or something. 

So there definitely seems to be something up with `get.adjacency`. Please see screenshot for illustrative example. Note the 0.95 seconds for the first call to `get.adjacency(g)`. 

![screen-igraph](https://cloud.githubusercontent.com/assets/4990236/19940793/3a78f790-a104-11e6-8df3-e20aede95679.png)

**Comment by ntamas** [comment]
Could it be the case that the first call to `get.adjacency()` loads another R package? Maybe a sparse matrix package or something like that...

**Comment by alexperrone** [comment]
@ntamas Yes, Matrix pretty much accounts for it. When I load igraph, it loads magrittr. After running `get.adjacency`, also loaded are Matrix, grid, and lattice.

It takes a good while to load Matrix for some reason, about 0.7 seconds on one machine (Mac) and 0.9-1 second on another (Linux). The other packages grid and lattice don't take much time.

Pre-loading the package Matrix trims down the initial call to `get.adjacency` to almost as fast as second call to it. So it is indeed Matrix.

Now, unless igraph wants to load Matrix immediately, I don't think there is anything else to be done. 

    system.time(library(igraph))
    ## user  system elapsed
    ## 0.031   0.000   0.031
    system.time(library(Matrix))
    ## user  system elapsed
    ## 1.019   0.020   1.041
    system.time(library(grid))
    ## user  system elapsed
    ## 0.006   0.000   0.006
    system.time(library(lattice))
    ## user  system elapsed
    ## 0.007   0.000   0.007
    system.time(g <- sample_gnm(8, 14))
    ## user  system elapsed
    ## 0.001   0.000   0.001
    system.time(A <- get.adjacency(g))
    ## user  system elapsed
    ## 0.012   0.000   0.012
    system.time(A <- get.adjacency(g))
    ## user  system elapsed
    ## 0.005   0.000   0.005
