### ISSUE TITLE
Problem : using  igraph at VS C++ 2013

### ISSUE THREAD

**Issue by mahdibg** [igraph/igraph#971]
Hi
i have problem in installation at VS 2013.
I do following task to add igraph in C++ project (but don't work :( )
1- Create empty project in VS C++ 2013 (an Console Application Project)
http://s8.picofile.com/file/8275415484/1111.png

2-add include folder to my project
http://s8.picofile.com/file/8275415642/33333.png

3-copy and past code from sample in a project. but don't run
http://s8.picofile.com/file/8275415868/44444.png

how can i solve this error?
tanks a lot

**Comment by ntamas** [comment]
You need to add igraph to the list of libraries that your project links to. It's not enough to add the include folder.
