### ISSUE TITLE
PRPACK and ARPACK returns different results for undirected weighted graphs

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#972]
This is an example in R from Daniel Piacek, but it seems to be related to the C core. Sorry for the missing images, use your imagination ;)

> Hello to everyone,
> 
> First of all, I would like to thank the authors of these amazing package. I use it extensively in my > master thesis.
> I am sorry for duplicate if there already exists same thread.
> 
> I have a huge network with couple of millions of edges and would like to calculate personalized PageRank. My network is attributed and I would like to use edge weights to calculate PageRank. I can either consider my network as directed or undirected, but in both cases my network is multigraph. I have encountered several 'strange' results when calculating weighted PageRank.
> 
> Here I will try to present it on simple networks without 'personalization'.
> 
> 1a.) Example with directed symmetric network, with no multiple edges and no weights.
> 
>     A = matrix(c(0,1,1,1,0,0,1,0,0),byrow=T,nrow=3)
>     g = graph.adjacency(A)
> 
> Then I compute PageRank with page_rank function and get the same result for both "PRPACK" and "ARPACK" algo. I can also compute via matrix inverse as follows:
> 
>     D = diag(1/apply(A,1,sum),nrow(A)); Beta = (1-0.85)*rep(1/nrow(A),nrow(A))
>     (pr.in = Beta%*%solve(diag(1,nrow(A))-0.85*D%*%A))
> 
> And as expected I get the same PageRank score. In addition, if I consider network as undirected I get the same scores, as expected.
> 
> 1b.) The same example with edge weights:
> 
>     set.seed(1)
>     E(g)$weight = round(runif(ecount(g)),1)
> 
> And again, using page_rank I get the same scores for both algorithms. Or I can get the same scores with weight matrix W as:
> 
>     W = matrix(c(0,0.3,0.4,0.6,0,0,0.9,0,0),byrow=T,nrow=3)
>     D = diag(1/apply(W,1,sum),nrow(W)); Beta = (1-0.85)*rep(1/nrow(W),nrow(W))
>     (pr.in = Beta%*%solve(diag(1,nrow(W))-0.85*D%*%W))
> 
> However, if I consider this network being undirected, I get different scores, namely:
> 
>     g_UN = as.undirected(g,'each') # do not collapse
>     (prUn1 = page_rank(g,algo='PRPACK', directed = F)$vector)
>     (prUn2 = page_rank(g,algo='ARPACK', directed = F)$vector)
>     (prUn3 = page_rank(g_UN, algo='PRPACK')$vector)
>     (prUn4 = page_rank(g_UN, algo='ARPACK')$vector)
> 
> Here scores given by 'ARPACK' are different to those given by 'PRPACK'. Moreover, with 'ARPACK' I get same scores for both g_UN(undirected network) and for directed=F. However 'PRPACK' gives different scores.
> I can replicate results for 'ARPACK' with weight matrix, where I take sum/average of edge weights:
> 
>     W_UN = matrix(c(0,0.9,1.3,0.9,0,0,1.3,0,0),byrow=T,nrow=3)
>     D = diag(1/apply(W_UN,1,sum),nrow(W_UN))
>     (pr.in = Beta%*%solve(diag(1,nrow(W_UN))-0.85*D%*%W_UN))
> 
> 2a.) Example with directed multigraph.
> 
>     A2 = matrix(c(0,2,1,1,0,0,1,1,0),byrow=T,nrow=3)
>     g2 = graph.adjacency(A2)
> 
> Without considering edge weights both algorithms give the same scores, which can be also found as
> 
>      D = diag(1/apply(A2,1,sum),nrow(A2))
>      (pr.in = Beta%*%solve(diag(1,nrow(A2))-0.85*D%*%A2))
> 
> 2b.) Same graph as undirected.
> Here again both algorithms give the same score for both directed=F and as.undirected(g2,'each'), or:
> 
>     A2_UN = matrix(c(0,3,2,3,0,1,2,1,0),byrow=T,nrow=3)
>     D = diag(1/apply(A2_UN,1,sum),nrow(A2_UN))
>     (pr.in = Beta%*%solve(diag(1,nrow(A2_UN))-0.85*D%*%A2_UN))
> 
> gives the same scores.
> 
> 2c.) Same graph with edge weights-directed.
> 
>     set.seed(1)
>     E(g2)$weight = round(runif(ecount(g2)),1)
> 
> And again I get different scores
> 
>     page_rank(g2,algo='PRPACK')$vector
>     page_rank(g2,algo='ARPACK')$vector
> 
> Where 'ARPACK' gives the same scores as with weight matrix W where edge weights for multiple 
> edges(considering direction) are summed
> 
>     W2 = matrix(c(0,0.7,0.6,0.9,0,0,0.2,0.9,0),byrow=T,nrow=3)
>     D = diag(1/apply(W2,1,sum),nrow(W2))
>     (pr.in = Beta%*%solve(diag(1,nrow(W2))-0.85*D%*%W2))
> 
> 2d.) Same graph with edge weights-undirected.
> 
>     g2_UN = as.undirected(g2,'each') # do not collapse
> 
> Again, 'PRPACK' and 'ARPACK' give different scores. Moreover, 'PRPACK' differs for 
> 
>     (prUn1 = page_rank(g2,algo='PRPACK',directed = F)$vector)
>     (prUN2 = page_rank(g2_UN,algo='PRPACK')$vector)
> 
> while 'ARPACK' gives same scores for both. Or with weight matrix W I can replicate 'ARPACK' by summing edge weights:
> 
>     W2_UN = matrix(c(0,1.6,0.8,1.6,0,0.9,0.8,0.9,0),nrow=3,byrow = T)
>     D = diag(1/apply(W2_UN,1,sum),nrow(W2_UN))
>     (pr.in = Beta%*%solve(diag(1,nrow(W2_UN))-0.85*D%*%W2_UN))

**Comment by szhorvat** [comment]
Reproduced with Mathematica, confirming that it's in the C core.

But these are multigraphs (multiple undirected edges between the same vertices) and lots of things are shaky with multigraphs in igraph ...

**Comment by ntamas** [comment]
The strange thing is that I also tried this with `simplify(as.undirected(g2), edge.attr.comb="sum")` in R and the result seemed to be inconsistent as well - not sure why.

**Comment by szhorvat** [comment]
Isn't `simplify(as.undirected(g2), edge.attr.comb="sum")` the same as `as.undirected(g2)`?  `as.undirected` already sums the weights.  I cannot reproduce the problem with any simple graph, only with multigraphs.

**Comment by ntamas** [comment]
This is what I get now:

```
> A = matrix(c(0,1,1,1,0,0,1,0,0),byrow=T,nrow=3)
> g = graph.adjacency(A)
> set.seed(1)
> E(g)$weight = round(runif(ecount(g)),1)
> g_UN = simplify(as.undirected(g), edge.attr.comb="sum")
> is.simple(g_UN)
[1] TRUE
> page_rank(g,algo='PRPACK', directed = F)$vector
[1] 0.4870632 0.2470592 0.2658776
> page_rank(g,algo='ARPACK', directed = F)$vector
[1] 0.4864865 0.2191646 0.2943489
> page_rank(g_UN,algo='PRPACK', directed = F)$vector
[1] 0.4864865 0.2191646 0.2943489
> page_rank(g_UN,algo='ARPACK', directed = F)$vector
[1] 0.4864865 0.2191646 0.2943489
```

So, it seems like PRPACK seems to be doing something wrong if the original graph is simple and directed but it is instructed to treat it as undirected. I have an idea about what could be wrong; let me check.

**Comment by iosonofabio** [comment]
I'm looking at this one. In `src/prpack/prpack_igraph_igraph.cpp` there seems to be some fumbling about with undirected edges that might trip with multigraphs:

```C++
    const igraph_bool_t treat_as_directed = igraph_is_directed(g) && directed;
    ...
    // Get the number of vertices and edges. For undirected graphs, we add
    // an edge in both directions.
    num_es = igraph_ecount(g);
    if (!treat_as_directed) {
        num_es *= 2;
    }
```

In the examples above, there are 3 nodes and edges 0>1, 1<0, 0>2, 2<0. While the directed case is a simple graph, the undirected case becomes a multigraph because edges 0>1 and 1>0 are now indistinguishable (same for 0>2 and 2>0). It seems like we don't need to create *2 new* fake edges on top of the 2 already present between 0 and 1 (same for the 0-2). I'll dig a little deeper to see if the fake edges mess up the result.

**Comment by ntamas** [comment]
Thanks a lot for looking into this @iosonofabio , it is really appreciated; nowadays it's hard for me to carve out a single uninterrupted chunk of time to look into issues that require a deeper understanding of the underlying code. (This will probably stay like this until September).

**Comment by szhorvat** [comment]
To clarify, the issue here is simply that PRPACK does not seem to support multi-edges and the code that converts igraph graphs to PRPACK graphs should combine parallel edges and add up their weights.

There is no problem with undirected edges, and no problem with self-loops either in the undirected or directed case.

**Comment by szhorvat** [comment]
@ntamas Is it correct that currently `igraph_incident` returns edges such that parallel edges are always consecutive? You worked with this during the adjlist/inclist_init overhaul. 

But even if this is the case, it is just a consequence of an implementation detail that we do not guarantee, right?

Summing up the weights of parallel edges would be so much simpler, both for PageRank, as well as for `igraph_diversity` (see #1712) if this could be guaranteed.

**Comment by szhorvat** [comment]
It's interesting to note that PRPACK only returns a wrong result when:

 - using weights
 - we have a multigraph
 - we use the `ge` method (Gaussian elimination)

For graphs with at least 128 vertices, it switches to a different method, which does not seem to be affected. Maybe it's not the case that PRPACK doesn't support multigraphs, but that PRPACK is buggy.

**Comment by ntamas** [comment]
> Is it correct that currently `igraph_incident` returns edges such that parallel edges are always consecutive?

Yes. And yes, it's an implementation detail, I think we never promised that anywhere. But we can, if we want to, I just wonder how much it will restrict future implementations of alternative data structures.

**Comment by vtraag** [comment]
> 
> Yes. And yes, it's an implementation detail, I think we never promised that anywhere. But we can, if we want to, I just wonder how much it will restrict future implementations of alternative data structures.

I don't think we should promise this, it would indeed restrict our future possibilities too much.

**Comment by szhorvat** [comment]
@ntamas @vtraag Good news is that this was an easy fix after all.

> I don't think we should promise this, it would indeed restrict our future possibilities too much.

Agreed. It will be a problem if we use a graph representation that supports efficient modification.
