### ISSUE TITLE
MacOS 10.11 libsystem_symptoms.dylib

### ISSUE THREAD

**Issue by jpfrench81** [igraph/igraph#973]
Apparently libsystem_symptoms.dylib is not installed in the current version of MacOS 10.11 (El Capitan).  

When I try to install igraph in R I get the following error: 

ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [igraph.so] Error 1

I can install igraph through brew (though that doesn't help me with the R issue).

**Comment by ntamas** [comment]
This is a bug in XCode 8 and/or El Capitan; it has nothing to do with igraph itself. "This page":https://ianchen06.github.io/2016/11/01/how-to-fix-libsystem-symptoms-dylib-missing-in-xcode-8-on-mac-os-x-el-capitan.html seems to contain some kind of a fix (although I haven't tried it myself).

**Comment by ntamas** [comment]
The page above seems to be gone; rumor has it that the bug was fixed in OS X 10.12, but people who are stuck on El Capitan will still encounter this issue. The workaround is to invoke `xml2-config` with `--exec-prefix=/usr --libs` instead of just `--libs`. I'm trying to incorporate this into the `configure` script so it gets applied automatically when running on OS X 10.11.

**Comment by glennlawyer** [comment]
Hi, ntamas, thanks for your efforts to fix this, but I'm getting the same `libsystem_symptoms.dylib not found` error on my mac (OS Sierra 10.12.6, with xcode9), so (in my case) your fix isn't working.

I was able to "fix" it by copying xml2-config to an earlier point in my path and changing the prefix (see i.e. https://stat.ethz.ch/pipermail/r-sig-mac/2016-September/012046.html), though this is not nearly as elegant as incorporating a better invocation of xml2-config as you attempted.

However, the build then failed with the following:
```clang -I/usr/local/Cellar/r/3.4.1_2/lib/R/include -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include -g -O2 -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.1.1\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -g -O2  -c foreign-graphml.c -o foreign-graphml.o
foreign-graphml.c:1408:46: error: expected ')'
  ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                             ^
foreign-graphml.c:1408:14: note: to match this '('
  ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
             ^
foreign-graphml.c:1412:59: error: expected ')'
  ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPAC...
                                                          ^
foreign-graphml.c:1412:14: note: to match this '('
  ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPAC...
             ^
foreign-graphml.c:1414:38: error: expected ')'
  ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.x...
                                     ^
foreign-graphml.c:1414:14: note: to match this '('
  ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.x...
             ^
3 errors generated.
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/local/lib/R/3.4/site-library/igraph’
```

I'd love to get igraph up and running, I used it often in happier days when I had a Debian laptop.

**Comment by ntamas** [comment]
This is something that older compilers used to accept just fine but newer ones choke on it. [This commit](https://github.com/igraph/igraph/commit/0ddc7727381d69eb54a17fa27114554712f6f5d5#diff-64c87bb91123edcd9a56339f6db70ed2) shows how to fix it.

**Comment by nasagfunaro** [comment]
So how does one install r/igraph on a mac OS X 10.11.6 using Xcode 8.2.1?
