### ISSUE TITLE
Application of induced_subgraph function to DAG produces subgraph with reversed edge direction

### ISSUE THREAD

**Issue by HAMLETT-NEIL** [igraph/igraph#975]
The Edges are listed as 
IGRAPH DN-- 22 22 -- 
+ attr: name (v/c)
+ edges (vertex names):
 [1] 46675->46616 46677->46626 46677->46691
 [4] 46690->46616 46691->46616 46717->46656
 [7] 46719->46658 46724->46626 46739->46677
[10] 46762->46717 46764->46719 46793->46677
[13] 46793->46739 46815->46675 46815->46690
[16] 46815->46691 46816->46724 47264->46764
[19] 47285->46762 47285->46781 47287->46764
[22] 47289->46764

Alternatively, we find, within which the edge directions are reversed from above.
E(UNIT_MAP)[[]]
+ 22/22 edges (vertex names):
    tail  head tid hid
1  46616 46675   1   5
2  46626 46677   2   6
3  46691 46677   8   6
4  46616 46690   1   7
5  46616 46691   1   8
6  46656 46717   3   9
7  46658 46719   4  10
8  46626 46724   2  11
9  46677 46739   6  12
10 46717 46762   9  13
11 46719 46764  10  14
12 46677 46793   6  16
13 46739 46793  12  16
14 46675 46815   5  17
15 46690 46815   7  17
16 46691 46815   8  17
17 46724 46816  11  18
18 46764 47264  14  19
19 46762 47285  13  20
20 46781 47285  15  20
21 46764 47287  14  21
22 46764 47289  14  22

Moreover, when I export the edge list to a data frame I find, within which the edge list is again reversed.
> as_data_frame(x = UNIT_MAP,
+ 															what = "edges")
    from    to
1  46675 46616
2  46677 46626
3  46677 46691
4  46690 46616
5  46691 46616
6  46717 46656
7  46719 46658
8  46724 46626
9  46739 46677
10 46762 46717
11 46764 46719
12 46793 46677
13 46793 46739
14 46815 46675
15 46815 46690
16 46815 46691
17 46816 46724
18 47264 46764
19 47285 46762
20 47285 46781
21 47287 46764
22 47289 46764

**Comment by szhorvat** [comment]
Can you give a complete reproducible example please?  I.e. a complete set of commands, the output you get from them, and the output you expected instead.

**Comment by ntamas** [comment]
Closing due to inactiviy.
