### ISSUE TITLE
appveyor.yml fails

### ISSUE THREAD

**Issue by kozo2** [igraph/igraph#976]
See https://ci.appveyor.com/project/kozo2/igraph-o5p9i

**Comment by ntamas** [comment]
@janschulz, does it work for you or is there something wrong with `appveyor.yml`?

**Comment by janschulz** [comment]
Looks like a problem with msys64/mingw

https://ci.appveyor.com/project/kozo2/igraph-o5p9i/build/job/mshse1j2bmlm2jja

```
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: xz: installing liblzma (5.2.3-1) breaks dependency 'liblzma=5.2.2'
Command exited with code 1
echo zipping everything after a failure...
zipping everything after a failure...
```

My guess is that some dependency wasn't updated or that mingw is in the midle of a transition...?

In gron, simply waiting helped to sort this out. Not sure if that's an option here as well :-/

**Comment by kozo2** [comment]
I'm sorry, this appveyor.yml works now. https://ci.appveyor.com/project/kozo2/igraph-o5p9i
It seems this failure was due to the mingw side as you said.
Thanks.
