### ISSUE TITLE
Travis CI cannot compile igraph anymore due to -lgfortran

### ISSUE THREAD

**Issue by richelbilderbeek** [igraph/igraph#979]
From a [Travis CI build log](https://travis-ci.org/richelbilderbeek/Treesearcher#L4704), I copy:

```
/usr/bin/ld: cannot find -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [igraph.so] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/local/lib/R/site-library/igraph’
Error: Command failed (1)
Execution halted
```

The problem is caused by [an R script with the name install_r_packages.R](https://github.com/richelbilderbeek/Treesearcher/blob/master/install_r_packages.R), which reads:

```
install.packages("devtools", repos = "http://cran.uk.r-project.org")
install.packages("DAISIE", repos = "http://cran.uk.r-project.org")
```

It is the `DAISIE` package that installs the `igraph` package.

In the [.travis.yml](https://github.com/richelbilderbeek/Treesearcher/blob/master/.travis.yml) is called with `sudo Rscript install_r_packages.R`, so it has sudo rights.

This error suddenly popped up in all my repos checked by Travis CI, for around , but *only in those that use `cpp` as a language*. The GitHubs that have `language: r` do not suffer this problem

For example, in another GitHub:

 * [Build 2424](https://travis-ci.org/richelbilderbeek/pbdmms/builds/210950441) from commit [cc879f](https://github.com/richelbilderbeek/pbdmms/commit/cc879f80edfaf901f9b57cabc02cd6ec5d942f99) six days ago (14th of March) still worked, and it did install `DAISIE`
 * [Build 2428](https://travis-ci.org/richelbilderbeek/pbdmms/builds/211270453) from commit [ca90e7](https://github.com/richelbilderbeek/pbdmms/commit/ca90e7fc7b9328e302616cb820d793fdd7c4ddb8) five days ago (15th of March)  failed.

Instead of the cause being at `igraph`, it may also be that in between the builds, another package started depending on `igraph`, bringing the problem to light.

I hope this helps you and me with this problem. Keep up the good work!

**Comment by richelbilderbeek** [comment]
Hmm, [a build I did today passes](https://travis-ci.org/richelbilderbeek/RibiClasses/builds/212931235),  [the build one hour later fails](https://travis-ci.org/richelbilderbeek/RibiClasses/builds/212948302). Looks more like a networking problem to me then...

**Comment by ntamas** [comment]
...or a problem with the build environment, e.g., some build nodes are not configured in exactly the same way as other build nodes, and the build succeeds or fails depending on which node it ends up on. This could also explain why the ones with `language: r` don't have this problem -- maybe they use a completely different build environment.

**Comment by richelbilderbeek** [comment]
I have found the cause of the bug: `g++` must *not* be redirected to `g++-5`

Here [the travis_qmake_gcc_cpp14_r_igraph GitHub's .travis.yml](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_r_igraph/blob/develop/.travis.yml):

```
language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # R
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # R
  - sudo apt-get install r-base r-base-dev
  - sudo Rscript -e 'install.packages("igraph", repos = "http://cran.r-project.org")'
```

Removing `sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90` makes `igraph` compile.

**Comment by richelbilderbeek** [comment]
Alternative solution: do the C++ stuff after the R stuff :sunglasses: 

```
language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # R
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update -qq

install: 
  # R
  - sudo apt-get install r-base r-base-dev
  - sudo Rscript -e 'install.packages("igraph", repos = "http://cran.r-project.org")'
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
```

**Comment by ntamas** [comment]
Great job! Is there anything we can do about this on our side?

**Comment by richelbilderbeek** [comment]
I think not. I think all we can do is have this error documented here, and I will mention it where it applies. 

And close this solved Issue :sunglasses:
