### ISSUE TITLE
R crashes when reading in gml file

### ISSUE THREAD

**Issue by dlarochelle** [igraph/igraph#980]
[igraph_seg_fault.zip](https://github.com/igraph/igraph/files/859695/igraph_seg_fault.zip)
R is segfaulting when I try to read in a gml file with igraph.

**I have attached the code and the GML file.**

Code:
```R
rm(list = ls())
library(igraph)
sessionInfo()
print("Reading File")
g <- read.graph("week8_PhysiciansNetwork.gml",  format="gml")
```

Result:
```
Traceback:
 1: base::.Call(.NAME, ...)
 2: .Call("R_igraph_read_graph_gml", file, PACKAGE = "igraph")
 3: read.graph.gml(file, ...)
 4: read.graph("week8_PhysiciansNetwork.gml", format = "gml")
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
```

According to sessionInfo(), I'm running R 3.3.1, igraph 1.0.1 and ubuntu 16.04

I have shown the full sessionInfo() output below:

```
R version 3.3.1 (2016-06-21)
[igraph_seg_fault.zip](https://github.com/igraph/igraph/files/859685/igraph_seg_fault.zip)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.0.1

loaded via a namespace (and not attached):
[1] magrittr_1.5
```

**Comment by ntamas** [comment]
Tried this on Mac OS X 10.11.6 with R 3.3.0 and igraph 1.0.1 - the GML file was loaded successfully. Maybe it's platform-specific, but I don't have access to a Linux machine right now. @gaborcsardi ?

**Comment by dlarochelle** [comment]
Yes, I have colleagues who were able to open the file on OS X.

FWIW, I tested this on 2 Ubuntu 16.04 systems and found the issue to be present in each case.

**Comment by ntamas** [comment]
Confirmed that this happens on Ubuntu but not on OS X. The full error message for Ubuntu is as follows:

```
> g <- read.graph("week8_PhysiciansNetwork.gml", format="gml")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: base::.Call(.NAME, ...)
 2: .Call("R_igraph_read_graph_gml", file, PACKAGE = "igraph")
 3: read.graph.gml(file, ...)
 4: read.graph("week8_PhysiciansNetwork.gml", format = "gml")
```

I strongly suspect that this has something to do with the fact that OS X does not have `fmemopen` so GML files are opened with an ordinary `fopen` call on OS X, while Ubuntu uses `fmemopen`.

As this is an R-specific issue, I'm moving this issue over to igraph/rigraph and handing it over to @gaborcsardi

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#184
