### ISSUE TITLE
Wishlist: Random walk with weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#981]
There is already `igraph_random_walk`, but it does not support weights.

It would be nice to have a similar function (or an extension to this function) which chooses an out-edge to take a step along with probability proportional to its weight.

I might do this in the future if @gaborcsardi or @ntamas approve and will let me know if a separate function or an extension to `igraph_random_walk` is preferable.

**Comment by ntamas** [comment]
Sounds like a good idea and I would prefer a separate function for this.

I will probably not have time to review the PR this week but I'll try to do it during the weekend or next week.

**Comment by szhorvat** [comment]
OK. I'll just go ahead and add weight support for the original function as well, so you can review everything at the same time (there's no rush).  It will be a minor change.

**Comment by ncdingari** [comment]
Did you implement random_walk based on Weights of Edges and Nodes?

**Comment by szhorvat** [comment]
Yes, but I didn't send it as a PR as it was basically done in terms of `random_edge_walk` as a quick-fix for my own application.

It's something like this:

```c
igraph_random_edge_walk(&graph, &weights, &edgeWalk, start, IGRAPH_OUT, steps-1, stuck)

long len = igraph_vector_size(&edgeWalk) + 1;
long last = start;
vertexWalk[0] = last;
for (long i=1; i < len; ++i) {
    last = IGRAPH_OTHER(&graph, edgeWalk[i-1], last);
    vertexWalk[i] = last;
}
```

(This is simplified code and I almost certainly introduces mistakes, but you get the idea.)

An implementation that uses edge weights would be almost a copy-paste of what `random_edge_walk` does anyway. However, it would avoid having to keep *two* walk vectors in memory.

----

As for "based on weights of nodes", it is not clear to me what you mean.

**Comment by ncdingari** [comment]
Thanks for quick reply. Do you have similar function `random_edge_walk` in R. I can't find it in `igraph `library

**Comment by szhorvat** [comment]
My contribution was to the C core. Perhaps the next version of the R API will expose it.

**Comment by jefferis** [comment]
Did `random_edge_walk` ever get added to R igraph?

**Comment by vtraag** [comment]
@jefferis, no it is not yet implemented in the R interface. We are currently working on updating the R interface to the recently released C core, version 0.8.0, see https://github.com/igraph/rigraph/pull/372. If that is done, the new contributions could start to be added.

**Comment by vtraag** [comment]
@szhorvat and @ntamas , from the code it seems a bit redundant to have two separate implementation of the `igraph_random_walk`. Wouldn't it make more sense to simply have one `igraph_random_walk` function that has both a `vertex_walk` and `edge_walk` arguments (either one can be `NULL`) that returns respectively the vertices visited during the random walk or the edges visited during the random walk?

**Comment by szhorvat** [comment]
Maybe, but in my opinion it would be a case of fixing something that's not broken and right now there are better things we can spend our limited time on (I have a huge todo list for igraph).

That said, I have no objection to the change.

**Comment by jefferis** [comment]
Do you mean for the R interface? That makes sense to me. I’d be happy to help. Best, Greg.

**Comment by szhorvat** [comment]
@vtraag Something you should be aware before working on this:

One concern is that the implementations are currently different. The edge-walk implementation is noticeably slower than that vertex-walk one.

In principle, the implementation can be simplified: just use the edge-walk code for everything, as the vertex-walk can be derived from that anyway. But that would make things 2x slower in some cases.

There is a benchmark in examples/benchmarks, and here's a sample run:

```
 1 Random edge walk,   directed,   unweighted, small graph   0.93s
 2 Random edge walk,   directed,   weighted,   small graph   1.01s
 3 Random vertex walk, directed,   unweighted, small graph   0.688s
 4 Random edge walk,   undirected, unweighted, small graph   1.05s
 5 Random edge walk,   undirected, weighted,   small graph   1.45s
 6 Random vertex walk, undirected, unweighted, small graph   0.692s
 7 Random edge walk,   directed,   unweighted, large graph   2.59s
 8 Random edge walk,   directed,   weighted,   large graph   4.87s
 9 Random vertex walk, directed,   unweighted, large graph   1.79s
10 Random edge walk,   undirected, unweighted, large graph   3.24s
11 Random edge walk,   undirected, weighted,   large graph   10.8s
12 Random vertex walk, undirected, unweighted, large graph   3.91s
```

The vertex-walk uses a `lazy_adjlist` which the edge walk uses a non-lazy `inclist`.  I remember worrying about the performance quite a bit when I implemented this. That is why I wrote the benchmark. Unfortunately, I do not remember if I tried a `lazy_inclist` and if it helped.

**Comment by vtraag** [comment]
> Do you mean for the R interface? 

No, I mean for the C interface.

> Maybe, but in my opinion it would be a case of fixing something that's not broken and right now there are better things we can spend our limited time on (I have a huge todo list for igraph).

You are right of course! But when I got notified about this issue, I read through it. It is something for later though.

> The edge-walk implementation is noticeably slower than that vertex-walk one.

Good to know about these differences! As you also say, it does not seem to be consistently slower, so perhaps the performance difference is not that important.

**Comment by vtraag** [comment]
@szhorvat , just an FYI, the binary search for the weights, as you do here:
https://github.com/igraph/igraph/blob/5ec361c41376a944050336877ce701741244abf6/src/random_walk.c#L232-L254
can now be more easily done (without having to re-allocate a new vector every time) using `igraph_i_vector_binsearch_slice`. Here is how I use it elsewhere
https://github.com/igraph/igraph/blob/5ec361c41376a944050336877ce701741244abf6/src/community_leiden.c#L421-L424

**Comment by szhorvat** [comment]
I ran the benchmark on a desktop machine (Linux) with excellent cooling. The timings are still not terribly stable, and I have no explanation for that (the RNG is seeded). But they're much more stable than on my laptop.

Three runs:

```
 1 Random edge walk,   directed,   unweighted, small graph   1.35s
 2 Random edge walk,   directed,   weighted,   small graph   1.56s
 3 Random vertex walk, directed,   unweighted, small graph   1.05s
 4 Random edge walk,   undirected, unweighted, small graph   1.24s
 5 Random edge walk,   undirected, weighted,   small graph   2.03s
 6 Random vertex walk, undirected, unweighted, small graph   0.884s
 7 Random edge walk,   directed,   unweighted, large graph   3.65s
 8 Random edge walk,   directed,   weighted,   large graph   5.3s
 9 Random vertex walk, directed,   unweighted, large graph   2.7s
10 Random edge walk,   undirected, unweighted, large graph   3.78s
11 Random edge walk,   undirected, weighted,   large graph   6.53s
12 Random vertex walk, undirected, unweighted, large graph   2.83s


 1 Random edge walk,   directed,   unweighted, small graph   1.24s
 2 Random edge walk,   directed,   weighted,   small graph   1.41s
 3 Random vertex walk, directed,   unweighted, small graph   0.944s
 4 Random edge walk,   undirected, unweighted, small graph   1.31s
 5 Random edge walk,   undirected, weighted,   small graph   1.94s
 6 Random vertex walk, undirected, unweighted, small graph   0.928s
 7 Random edge walk,   directed,   unweighted, large graph   3.42s
 8 Random edge walk,   directed,   weighted,   large graph   5.09s
 9 Random vertex walk, directed,   unweighted, large graph   2.86s
10 Random edge walk,   undirected, unweighted, large graph   3.68s
11 Random edge walk,   undirected, weighted,   large graph   6.17s
12 Random vertex walk, undirected, unweighted, large graph   2.79s


 1 Random edge walk,   directed,   unweighted, small graph   1.24s
 2 Random edge walk,   directed,   weighted,   small graph   2.15s
 3 Random vertex walk, directed,   unweighted, small graph   1.3s
 4 Random edge walk,   undirected, unweighted, small graph   1.44s
 5 Random edge walk,   undirected, weighted,   small graph   2.05s
 6 Random vertex walk, undirected, unweighted, small graph   0.952s
 7 Random edge walk,   directed,   unweighted, large graph   3.72s
 8 Random edge walk,   directed,   weighted,   large graph   5.73s
 9 Random vertex walk, directed,   unweighted, large graph   2.64s
10 Random edge walk,   undirected, unweighted, large graph   3.65s
11 Random edge walk,   undirected, weighted,   large graph   6.45s
12 Random vertex walk, undirected, unweighted, large graph   2.72s
```

**Comment by szhorvat** [comment]
@vtraag Re binsearch: I'm not following. Can you expand the explanation? What does `binsearch_slice` do (compared to `binsearch`)? Doesn't it just do a binary search in a restricted range of a sorted vector?

For every vertex, there is at most one allocation. After that, the cumulative dsitribution function (CDF) vectors are re-used.

BTW there should be proper (internal) headers for these internal functions. It's used without declaration in `community_leiden.c`.

**Comment by ntamas** [comment]
In case someone is interested in profiling results on macOS, only for tests #10 and #12; igraph had to be compiled in debug mode with `-O0` to get meaningful stack traces so this is not entirely representative of the real performance:

<img width="523" alt="Screenshot 2020-02-27 at 12 49 12" src="https://user-images.githubusercontent.com/195637/75442391-ac8e6600-595f-11ea-9922-bdc33fc1f907.png">

The most notable difference is that `igraph_random_edge_walk()` spends significantly more time in "itself" than in `igraph_random_walk()`. There are two hotspot lines in the function:

`edge = VECTOR(*edges)[idx];` (sampled 2062x)

and

`start = IGRAPH_OTHER(graph, edge, start);` (sampled 2890x)

I think the second one is the more interesting part; basically, since we only have an edge index after the sampling, we need todo extra legwork to figure out which vertex is the "other" endpoint of the edge.

**Comment by vtraag** [comment]
> Doesn't it just do a binary search in a restricted range of a sorted vector?

Yes, exactly. That allowed me to reuse the same vector every time, instead of having to resize or anything.

> For every vertex, there is at most one allocation. After that, the cumulative distribution function (CDF) vectors are re-used.

Ah yes, you are right, then it doesn't matter indeed.

> BTW there should be proper (internal) headers for these internal functions. It's used without declaration in community_leiden.c.

I thought it was properly defined through `vector.pmt`, but I'll check it.

> I think the second one is the more interesting part; basically, since we only have an edge index after the sampling, we need todo extra legwork to figure out which vertex is the "other" endpoint of the edge.

This is good to know! At some earlier time I suggested to have a type of `inclist` that returns *both* the neighbour and the edge index (but I can't locate that comment anywhere). Right now you always need both `inclist` and `adjlist` or use `IGRAPH_OTHER`. The former is a bit annoying, but clearly preferably to using `IGRAPH_OTHER` then apparently, at least in terms of performance.

**Comment by vtraag** [comment]
I've quickly tested whether a combination of using `inclist` and `adjlist` is indeed quicker then using `inclist` in combination with `IGRAPH_OTHER`. In some test (just looping over all edges of an ER graph with n=1e5 and m=1e7), the difference is quite clear:
```
Using IGRAPH_OTHER took 76.4875ms on average.
Using igraph_adjlist took 50.5476ms on average.
```
Using `IGRAPH_OTHER` is almost 50% slower than using the combination of `igraph_adjlist` instead.

**Comment by vtraag** [comment]
> BTW there should be proper (internal) headers for these internal functions. It's used without declaration in community_leiden.c.

Yes, you are right. It is not included in any header. It would not make sense to include it in the public header `igraph_vector.h`, because it is an internal function. But it makes it a bit obscure how to properly include it in a header, since `igraph_vector_binsearch` now depends on `igraph_i_vector_binsearch_slice`. We would then need a `igraph_vector_i.h` or something in addition to `igraph_vector.h`. Perhaps it is easier to make it a public function in the end?

**Comment by vtraag** [comment]
> BTW there should be proper (internal) headers for these internal functions. It's used without declaration in community_leiden.c.

Yes, you are right. It is not included in any header. It would not make sense to include it in the public header `igraph_vector.h`, because it is an internal function. But it makes it a bit obscure how to properly include it in a header, since `igraph_vector_binsearch` now depends on `igraph_i_vector_binsearch_slice`. We would then need a `igraph_vector_i.h` or something in addition to `igraph_vector.h`. Perhaps it is easier to make it a public function in the end?

**Comment by ntamas** [comment]
I think that `igraph_vector_binsearch_slice()` clearly has some general utility and it could be made part of the public API. Is anyone willing to tackle that?

**Comment by vtraag** [comment]
I will do that.
