### ISSUE TITLE
Integration of fluid communities algorithm into igraph

### ISSUE THREAD

**Issue by FerranPares** [igraph/igraph#983]
Hello there,

We are interested in adding the fluid communities algorithm [1] to igraph. It's competitive both in performance (close to multilevel) and in scalability (close to LPA).
So far we have a compiling and tested version of the code (for the C library) based on the LPA code originally found in igraph.
If that's ok we will make the pull request. 

[1] https://arxiv.org/pdf/1703.09307.pdf

**Comment by FerranPares** [comment]
As explained above, we still interested in adding our algorithm called fluid communities [1]. Paper has been improved and extended from April and it has been accepted at the 6th International Conference on Complex Networks and Their Applications, so it has already passed the peer review process. Furthermore, it has been already merged into networkx python package (https://github.com/networkx/networkx/pull/2420).

Pull request #990 is still open and not commented. All checks have passed. Hope everything is ok and someone is willing to check it and comment.

**Comment by ntamas** [comment]
@szhorvat has now started to look into the PR (and sorry for the delay, personally I don't have too much time to dedicate to igraph nowadays so I have a terribly long backlog of everything). I'll close this issue - any comments will be added to #990.
