### ISSUE TITLE
Weights still ignored in layout_with_fr

### ISSUE THREAD

**Issue by ppapasaikas** [igraph/igraph#984]
Hello,
This issue had previously been reported fro the R version of igraph (#839) but now appears as closed. Is still the rigraph development version the way to go? Is there a plan to release soon the version incorporating the fix?
Many thanks and sorry if this is an rigraph specific issue and would have been more appropriate to report there...

**Comment by ntamas** [comment]
I think you should still go for the development version; @gaborcsardi can tell whether there are any plans to release a new version of either igraph or R/igraph in the foreseeable future.
