### ISSUE TITLE
dominator_tree() does not return -1 for root

### ISSUE THREAD

**Issue by nick-ulle** [igraph/igraph#985]
Contrary to the documentation, the `dom` field of the output from `dominator_tree()` does not include a -1 as the immediate dominator of the root vertex.

Including a sentinel value for the root (or treating the root as its own immediate dominator) is useful because otherwise the indexes of `dom` will be off by one compared to the vertices of the original graph.

Minimal example:
```r
g = make_empty_graph() + vertices("A", "B", "C")
g = g + edges(c("B", "A", "B", "C"))

dom = dominator_tree(g, "B")$dom
# Now the immediate dominator for "C" (index 3 in g) is at index 2
```
It would be even better if `dom` retained the names of the vertices.

**Comment by ntamas** [comment]
This issue was moved to igraph/rigraph#186
