### ISSUE TITLE
igraph_avg_nearest_neighbor_degree() weighted result dubious

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#987]
`igraph_avg_nearest_neighbor_degree()` computes the mean degree the vertices' nearest neighbours.  To find out what it does for edge-weighted graphs, I looked at the source code.

For weighted graphs, for a given node `i` it will add up the strengths of `i`'s neighbours, then divide the result by `i`'s strength.

This is not clear from the documentation, and is inconsistent with the reference given there.

http://igraph.org/r/doc/knn.html

The documentation says that for weighted graphs, "vertex strength (see strength) is used instead of vertex degree". From this, I would have assumed that it computes the mean neighbour strength, but this is not the case.  In fact, what is being computed cannot even be called an average.

The reference being given in the documentation is http://dx.doi.org/10.1073/pnas.0400087101

This paper has a similar "knn" measure defined in equation (6).  But again, it does not agree with what igraph computes.  Barrat's "knn" is a weighted average of degrees (not strengths). The weighting is done according to edge weights.

The documentation suggests that this function was meant to compute what is in the paper, but it doesn't. I assume that this is a bug.

**Comment by szhorvat** [comment]
@gaborcsardi  Could you comment on the intention behind this function?

Which one is the preferred fix?

 - change the function to match Eq. (6) in the Barrat paper
 - change the documentation to explain what the function does currently

**Comment by yoelcabo** [comment]
Confusion because of the documentation brought me to this issue. I would say that in any case the documentation needs to be amended. For instance http://igraph.org/r/doc/transitivity.html is more clear on the fact that the weighted version is using Barrat's definition.

**Comment by ntamas** [comment]
I have tried to clarify the documentation for the time being, although I agree with @szhorvat that the measure being calculated here is not really an "average" and is probably a bug. Since I am not the one who implemented the function originally, I don't know what the original intention was, but at least it is now documented how the function behaves.

**Comment by MF-git** [comment]
looks like weighted knn still gives: knn^w[nn,i] = 1/(s[i])  * sum a[ij]*w[ij]***s**[j] instead of Barrat's formulation knn^w[nn,i] = 1/(s[i])  * sum a[ij]*w[ij]***k**[j] 

this leads to knn[nn,i]<knn^w[nn,i] for all nodel i with degree k=1 - but should be knn[nn,i]=knn^w[nn,i]
