### ISSUE TITLE
Wishlist: rewire while keeping in- or out-degree sequence

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#999]
There are two rewiring functions, `rewire` and `rewire_edges`.  The former keeps the degree sequence.  The latter only keeps the number of edges.

I propose an extension to `rewire_edges` where it can keep either the in- or out-degree sequence of directed graphs (but not both).  I.e. for each `s -> t` edge, rewire only the `s` end (or only the `t` end).  This could be done through a `mode` argument with `IGRAPH_OUT`, `IGRAPH_IN` or `IGRAPH_ALL` values.

Does this sound reasonable?

**Comment by ntamas** [comment]
Makes sense - but it's unfortunately very unlikely that I will have time to implement this in the near future. Pull requests are welcome (as usual), but if it breaks the API, we need to keep in mind that higher-level interfaces also have to be updated.

**Comment by szhorvat** [comment]
Just let me know which is better:

 - change the existing function, as I suggested
 - add a completely new function

**Comment by ntamas** [comment]
Adding a new function won't break the existing API so I would prefer that.
